### PR TITLE
Fix NPE while checking for user data provider

### LINKED ISSUE #9847: Delete edge vr showing internal server error.
Bug Report

VR

4.18.2

```
cloudstack-0 cloudstack ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-91:ctx-f65e2666 job-174) (logid:4dce969b) Unexpected exception while executing org.apache.cloudstack.api.command.admin.router.DestroyRouterCmd
cloudstack-0 cloudstack java.lang.NullPointerException
cloudstack-0 cloudstack         at com.cloud.network.NetworkModelImpl.getUserDataUpdateProvider(NetworkModelImpl.java:928)
cloudstack-0 cloudstack         at com.cloud.network.element.ConfigDriveNetworkElement.postStateTransitionEvent(ConfigDriveNetworkElement.java:322)
cloudstack-0 cloudstack         at com.cloud.network.element.ConfigDriveNetworkElement.postStateTransitionEvent(ConfigDriveNetworkElement.java:94)
cloudstack-0 cloudstack         at com.cloud.utils.fsm.StateMachine2.transitTo(StateMachine2.java:142)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.stateTransitTo(VirtualMachineManagerImpl.java:2248)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.advanceExpunge(VirtualMachineManagerImpl.java:614)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.advanceExpunge(VirtualMachineManagerImpl.java:594)
cloudstack-0 cloudstack         at com.cloud.vm.VirtualMachineManagerImpl.expunge(VirtualMachineManagerImpl.java:583)
cloudstack-0 cloudstack         at com.cloud.network.router.NetworkHelperImpl.destroyRouter(NetworkHelperImpl.java:272)
cloudstack-0 cloudstack         at com.cloud.network.router.VirtualNetworkApplianceManagerImpl.destroyRouter(VirtualNetworkApplianceManagerImpl.java:405)
cloudstack-0 cloudstack         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cloudstack-0 cloudstack         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cloudstack-0 cloudstack         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cloudstack-0 cloudstack         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cloudstack-0 cloudstack         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
cloudstack-0 cloudstack         at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
cloudstack-0 cloudstack         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
cloudstack-0 cloudstack         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
cloudstack-0 cloudstack         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
cloudstack-0 cloudstack         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
cloudstack-0 cloudstack         at com.sun.proxy.$Proxy280.destroyRouter(Unknown Source)
cloudstack-0 cloudstack         at org.apache.cloudstack.api.command.admin.router.DestroyRouterCmd.execute(DestroyRouterCmd.java:97)
cloudstack-0 cloudstack         at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:163)
cloudstack-0 cloudstack         at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:112)
cloudstack-0 cloudstack         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
cloudstack-0 cloudstack         at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
cloudstack-0 cloudstack         at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
cloudstack-0 cloudstack         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cloudstack-0 cloudstack         at java.base/java.lang.Thread.run(Thread.java:829)
```

##### STEPS TO REPRODUCE
1. Create edge zone
2. Create shared network without using direct download system template
3. Destory the vr systemvm will cause the error.

##### EXPECTED RESULTS
1. delete the vr without any error

##### ACTUAL RESULTS
1. internal server error

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR fixes NPE issues while checking for user data provider.

Fixes #9847 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/network/element/VirtualRouterElement.java [hunk 1]
```diff
@@ -767,7 +767,8 @@ public boolean saveSSHKey(final Network network, final NicProfile nic, final Vir
 
     @Override
     public boolean saveHypervisorHostname(NicProfile nicProfile, Network network, VirtualMachineProfile vm, DeployDestination dest) throws ResourceUnavailableException {
-        if (_networkModel.getUserDataUpdateProvider(network).getProvider().equals(Provider.VirtualRouter) && vm.getVirtualMachine().getType() == VirtualMachine.Type.User) {
+        final UserDataServiceProvider userDataUpdateProvider = _networkModel.getUserDataUpdateProvider(network);
+        if (userDataUpdateProvider != null && Provider.VirtualRouter.equals(userDataUpdateProvider.getProvider()) && vm.getVirtualMachine().getType() == VirtualMachine.Type.User) {
```
Comment (Pearl1594) [inline server/src/main/java/com/cloud/network/element/VirtualRouterElement.java:771]: Should we return false if userdata provider is null?  This will atleast log the appropriate error message.

**Review by Pearl1594 — COMMENTED** [review]
Overall LGTM, just one comment.

File: server/src/main/java/com/cloud/network/element/VirtualRouterElement.java (hunk 1 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/network/element/VirtualRouterElement.java:771]: @sureshanaparti can you answer this query?

Comment (sureshanaparti) [reply server/src/main/java/com/cloud/network/element/VirtualRouterElement.java]: addressed, thanks @Pearl1594

**Comment by sureshanaparti** [comment]
> @sureshanaparti , the issue speaks of deletion of a VR in an edge zone. Are there special requirements for testing this fix concerning making an edge zone? tnx

@DaanHoogland create edge zone and don't register direct download systemvm template. Create shared network and try to deploy VM (The network creation fails as there is no direct download systemvm template to create the VR, at this point - destroy the VR).

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]
Thanks @sureshanaparti. LGTM. Code has been made more defensive to prevent NPEs.
