### PR TITLE
[VMware] Sync the disk path or datastore changes for IDE disks, and before any volume resize during start vm (for the volumes on datastore cluster)

### LINKED ISSUE #10626: Unable to start a vm which has a iso after vmware storage drs get's triggered in datastore cluster
### problem

Unable to start a vm which has a iso after vmware storage drs get's triggered in datastore cluster

### versions

Cloudstack version 4.18,4.19,4.20
Vmware 8.0

### The steps to reproduce the bug

This issue was also reported  before  in #7536

1. Have a Cloudstack environment with Vmware 8.0 and datastore cluster and vsphere storage drs enabled

2. Deploy a vm with a iso image 

3. Stop the vm

4. Trigger a vsphere storage drs on one of the datastore cluster ( this can done filling up a datastore)

5. Start the vm > vm unable to start

Logs exception

```
2025-03-26 11:04:13,868 INFO  [c.c.h.v.m.VirtualMachineMO] (DirectAgent-10:ctx-345e2492 10.0.34.33, job-380/job-383, cmd: StartCommand) (logid:a7625e6e) No disk device exactly matching [b41d32cde3184e0ebbe16a706c2aaaa1] was found for volume [b41d32cde3184e0ebbe16a706c2aaaa1.vmdk]. Looking for disk device info against trimmed base name [b41d32cde3184e0ebbe16a706c2aaaa1].
2025-03-26 11:04:13,868 WARN  [c.c.h.v.m.VirtualMachineMO] (DirectAgent-10:ctx-345e2492 10.0.34.33, job-380/job-383, cmd: StartCommand) (logid:a7625e6e) Disk device info lookup for volume [b41d32cde3184e0ebbe16a706c2aaaa1.vmdk] failed as no matching disk device was found.
2025-03-26 11:04:13,869 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-10:ctx-345e2492 10.0.34.33, job-380/job-383, cmd: StartCommand) (logid:a7625e6e) [ignored]failed to get message for exception: No such disk device: b41d32cde3184e0ebbe16a706c2aaaa1.vmdk
2025-03-26 11:04:13,869 ERROR [c.c.h.v.r.VmwareResource] (DirectAgent-10:ctx-345e2492 10.0.34.33, job-380/job-383, cmd: StartCommand) (logid:a7625e6e) StartCommand failed due to [Exception: java.lang.Exception
Message: No such disk device: b41d32cde3184e0ebbe16a706c2aaaa1.vmdk
].
java.lang.Exception: No such disk device: b41d32cde3184e0ebbe16a706c2aaaa1.vmdk

```

6. Check the volumes 

```
mysql> select name,path,pool_id,chain_info from volumes where instance_id=63 \G;
*************************** 1. row ***************************
      name: ROOT-63
      path: b41d32cde3184e0ebbe16a706c2aaaa1
   pool_id: 12
chain_info: {"diskDeviceBusName":"ide0:1","diskChain":["[ids1] i-2-63-VM/b41d32cde3184e0ebbe16a706c2aaaa1.vmdk"]}
1 row in set (0.00 sec)
```

Complete logs 

[startlogs.txt](https://github.com/user-attachments/files/19486632/startlogs.txt)

### What to do about it?

Cloudstack should start the vm which has a ISO attached after a vsphere storage drs is triggered

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR syncs the disk path or datastore changes for IDE disks as well, and before any volume resize during start vm (for the volumes on datastore cluster pool) in VMware.

Fixes #10626 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested VM (with ISO) start after storage drs triggered in datastore cluster for the ROOT volume.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test ol8 vmware-7u3

**Comment by Pearl1594** [comment]
@blueorangutan test ol8 vmware-70u3

**Review by kiranchavala — COMMENTED** [review]
@sureshanaparti Tested the pr, issue is still present

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM

1. Have a Cloudstack environment with Vmware 8.0 and datastore cluster and vsphere storage drs enabled

2. Deploy a vm with a iso image

3. Stop the vm

4. Trigger a vsphere storage drs on one of the datastore cluster ( this can done filling up a datastore)

 5. Start the vm > vm able to start 
 
 
 Logs 
 
```
 2025-04-29 07:33:14,967 INFO  [c.c.h.v.m.BaseMO] (DirectAgent-240:[ctx-d7f4865e, 10.0.35.221, job-51/job-52, cmd: StartCommand]) (logid:976681f9) Looking for disk device info for volume [i-2-6-VM.vmdk] with base name [i-2-6-VM].
2025-04-29 07:33:14,967 INFO  [c.c.h.v.m.BaseMO] (DirectAgent-240:[ctx-d7f4865e, 10.0.35.221, job-51/job-52, cmd: StartCommand]) (logid:976681f9) Testing if disk device with controller key [200] and unit number [1] has backing of type VirtualDiskFlatVer2BackingInfo.
2025-04-29 07:33:14,967 INFO  [c.c.h.v.m.BaseMO] (DirectAgent-240:[ctx-d7f4865e, 10.0.35.221, job-51/job-52, cmd: StartCommand]) (logid:976681f9) Testing if backing datastore name [ds2] from backing [[ds2] i-2-6-VM/i-2-6-VM.vmdk] matches source datastore name [].
2025-04-29 07:33:14,967 INFO  [c.c.h.v.m.BaseMO] (DirectAgent-240:[ctx-d7f4865e, 10.0.35.221, job-51/job-52, cmd: StartCommand]) (logid:976681f9) Disk backing [[ds2] i-2-6-VM/i-2-6-VM.vmdk] matches device bus name [ide0:1].
2025-04-29 07:33:15,179 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-240:[ctx-d7f4865e, 10.0.35.221, job-51/job-52, cmd: StartCommand]) (logid:976681f9) Found existing disk info from volume path: i-2-6-VM
2025-04-29 07:33:18,997 DEBUG [c.c.h.v.r.VmwareResource] (DirectAgent-240:[ctx-d7f4865e, 10.0.35.221, job-51/job-52, cmd: StartCommand]) (logid:976681f9) VM i-2-6-VM has been started successfully with hostname i-2-6-VM.
2025-04-29 07:33:19,001 DEBUG [c.c.a.t.Request] (Work-Job-Executor-12:[ctx-c071f476, job-51/job-52, ctx-46c70ab3]) (logid:976681f9) Seq 1-6852789782997631226: Received:  { Ans: , MgmtId: 32987496317188, via: 1(10.0.35.221), Ver: v1, Flags: 10, { StartAnswer } }
2025-04-29 07:33:19,025 INFO  [o.a.c.e.o.VolumeOrchestrator] (Work-Job-Executor-12:[ctx-c071f476, job-51/job-52, ctx-46c70ab3]) (logid:976681f9) Updating volume's disk chain info. Volume: [{"name":"ROOT-6","uuid":"281e0a25-11fa-456e-b61b-aaeb2d086a80"}]. Path: [90e32def4fad4217a9590ac3434484e3] -> [i-2-6-VM], Disk Chain Info: [{"diskDeviceBusName":"ide0:1","diskChain":["[ds1] i-2-6-VM/90e32def4fad4217a9590ac3434484e3.vmdk"]}] -> [{"diskDeviceBusName":"ide0:1","diskChain":["[ds2] i-2-6-VM/i-2-6-VM.vmdk"]}].
2025-04-29 07:33:19,057 DEBUG [c.c.n.NetworkModelImpl] (Work-Job-Executor-12:[ctx-c071f476, job-51/job-52, ctx-46c70ab3]) (logid:976681f9) Service SecurityGroup is not supported in the network Network {"id": 204, "name": "test", "uuid": "f5c3bb0a-cf73-42a2-803b-fdd745cffc03", "networkofferingid": 10}
2025-04-29 07:33:19,060 DEBUG [c.c.n.NetworkModelImpl] (Work-Job-Executor-12:[ctx-c071f476, job-51/job-52, ctx-46c70ab3]) (logid:976681f9) Service SecurityGroup is not supported in the network Network {"id": 204, "name": "test", "uuid": "f5c3bb0a-cf73-42a2-803b-fdd745cffc03", "networkofferingid": 10}
2025-04-29 07:33:19,063 DEBUG [c.c.c.CapacityManagerImpl] (Work-Job-Executor-12:[ctx-c071f476, job-51/job-52, ctx-46c70ab3]) (logid:976681f9) VM instance {"id":6,"instanceName":"i-2-6-VM","state":"Running","type":"User","uuid":"3ee2497d-2ace-4c1e-9892-eb3f5a814490"} state transited from [Starting] to [Running] with event [OperationSucceeded]. VM's original host: Host {"id":1,"name":"10.0.35.221","type":"Routing","uuid":"33452dc5-9409-4124-80bf-1b409cfbdc7e"}, new host: Host {"id":1,"name":"10.0.35.221","type":"Routing","uuid":"33452dc5-9409-4124-80bf-1b409cfbdc7e"}, host before state transition: Host {"id":1,"name":"10.0.35.221","type":"Routing","uuid":"33452dc5-9409-4124-80bf-1b409cfbdc7e"}
2025-04-29 07:33:19,066 DEBUG [c.c.v.ClusteredVirtualMachineManagerImpl] (Work-Job-Executor-12:[ctx-c071f476, job-51/job-52, ctx-46c70ab3]) (logid:976681f9) Start completed for VM VM instance {"id":6,"instanceName":"i-2-6-VM","state":"Running","type":"User","uuid":"3ee2497d-2ace-4c1e-9892-eb3f5a814490"}
```

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 1]
```diff
@@ -2350,13 +2350,59 @@ protected StartAnswer execute(StartCommand cmd) {
...
+                            String actualPoolUuid = diskDatastoreMofromVM.getCustomFieldValue(CustomFieldConstants.CLOUD_UUID);
+                            if (actualPoolUuid != null && !actualPoolUuid.equalsIgnoreCase(primaryStore.getUuid())) {
+                                volumeDsDetails = new Pair<>(diskDatastoreMofromVM.getMor(), diskDatastoreMofromVM);
+                                if (logger.isInfoEnabled())
+                                    logger.info("Detected datastore uuid change on volume: " + volumeTO.getId() + " " + primaryStore.getUuid() + " -> " + actualPoolUuid);
+                                ((PrimaryDataStoreTO)primaryStore).setUuid(actualPoolUuid);
+                            }
+                        }
+                    }
+                }
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:2398]: @sureshanaparti , can you extract these lines in extra methods?

Comment (sureshanaparti) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java]: updated @DaanHoogland , please check.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test ol9  vmware-70u3
