### PR TITLE
fix HMAC Signatures and API Keys Logged in Plaintext

### LINKED ISSUE #11988: Security: HMAC Signatures and API Keys Logged in Plaintext Across Authentication Components
### Summary
Multiple authentication components log sensitive cryptographic material (HMAC signatures, API keys, timestamps) at DEBUG and INFO levels without masking. This exposes shared secret derivatives that can be used for request replay attacks, signature analysis, and authentication bypass attempts.

### Severity
**Critical** - Exposure of HMAC signatures and API keys enables request replay attacks and potential compromise of the authentication mechanism.

---

#### Location
- **File**: `server/src/main/java/com/cloud/user/AccountManagerImpl.java`
- **Method**: `getUserAccountForSSO()`
- **Line**: 

https://github.com/apache/cloudstack/blob/dbda673e1fa813856deb0f0b6328dad0222b702c/server/src/main/java/com/cloud/user/AccountManagerImpl.java#L3009

---

#### Location
- **File**: `client/tomcatconf/ConsoleProxyServlet.java` (or similar path)
- **Method**: `verifyRequest()` 

https://github.com/apache/cloudstack/blob/dbda673e1fa813856deb0f0b6328dad0222b702c/server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java#L537

#### Exposed Data
- API Key (plaintext)
- Incoming HMAC signature
- Computed HMAC signature (on mismatch)
- Request validation context

---

### Why Signature Exposure is Critical

The `signature` is an **HMAC digest** generated from:
```
signature = HMAC(shared_secret, request_parameters)
```

This makes it cryptographically sensitive material. Even at DEBUG level, exposure enables:

#### 1. **Request Replay Attacks**
- Attacker captures signature + timestamp from logs
- Replays the exact request to impersonate legitimate client
- Bypasses authentication if timestamp validation is weak

#### 2. **Signature Analysis & Cryptanalysis**
- Collecting multiple signature samples reveals patterns
- May expose weaknesses in HMAC implementation
- Could lead to shared secret recovery if implementation is flawed
- Helps identify signature generation algorithm details

#### 3. **Information Disclosure**
- Reveals which requests fail validation (signature mismatch scenarios)
- Exposes expected signature values (when both supplied and computed are logged)
- Provides attackers with oracle for testing signature generation

#### 4. **API Key Compromise**
- Direct exposure of API keys enables full account impersonation
- Combined with signature, gives complete authentication context
- Permanent credential (unlike session tokens)

### PR DESCRIPTION
**Pull request by YLChen-007**
### Description

This PR fixes HMAC Signatures and API Keys Logged in Plaintext Across Authentication Components Fixes: #11988

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
clgtm

File: core/src/main/java/com/cloud/storage/template/HttpTemplateDownloader.java [hunk 1]
```diff
@@ -151,7 +151,7 @@ private void checkCredentials(String user, String password) {
                 client.getParams().setAuthenticationPreemptive(true);
                 Credentials defaultcreds = new UsernamePasswordCredentials(user, password);
                 client.getState().setCredentials(new AuthScope(hostAndPort.first(), hostAndPort.second(), AuthScope.ANY_REALM), defaultcreds);
-                logger.info("Added username=" + user + ", password=" + password + "for host " + hostAndPort.first() + ":" + hostAndPort.second());
+                logger.info("Added username=" + user + ", password=******" + "for host " + hostAndPort.first() + ":" + hostAndPort.second());
```
Comment (DaanHoogland) [inline core/src/main/java/com/cloud/storage/template/HttpTemplateDownloader.java]: not concerning you part of the change @YLChen-007 , but sggesting anyway;

```suggestion
                logger.info("Added username={}, password=****** for host {}:{}”, user, hostAndPort.first(), hostAndPort.second());
```

File: core/src/main/java/com/cloud/storage/template/HttpTemplateDownloader.java [hunk 2]
```diff
@@ -151,7 +151,7 @@ private void checkCredentials(String user, String password) {
                 client.getParams().setAuthenticationPreemptive(true);
                 Credentials defaultcreds = new UsernamePasswordCredentials(user, password);
                 client.getState().setCredentials(new AuthScope(hostAndPort.first(), hostAndPort.second(), AuthScope.ANY_REALM), defaultcreds);
-                logger.info("Added username=" + user + ", password=" + password + "for host " + hostAndPort.first() + ":" + hostAndPort.second());
+                logger.info("Added username={}, password=****** for host {}:{}”, user, hostAndPort.first(), hostAndPort.second());
```
Comment (DaanHoogland) [inline core/src/main/java/com/cloud/storage/template/HttpTemplateDownloader.java]:
```suggestion
                logger.info("Added username={}, password=****** for host {}:{}", user, hostAndPort.first(), hostAndPort.second());
```

**Review by abh1sar — APPROVED** [review]
code lgtm
