### PR TITLE
Set nfsVersion in ssvm agent.properties only if it is not null

### LINKED ISSUE #12415: secstorage.nfs.version = NULL results in vers=null mount option and SSVM NFS mount failure
### problem

When secstorage.nfs.version is SQL NULL, CloudStack incorrectly generates an NFS mount option vers=null when mounting Secondary Storage on the Secondary Storage VM (SSVM).

This results in mount.nfs failing with a parsing error, even though the configuration description states that NULL should trigger default NFS version negotiation.

**Expected Behavior:** If secstorage.nfs.version is NULL, CloudStack should omit the vers= mount option entirely and allow the OS to auto-negotiate the NFS version.

**Actual Behavior:** CloudStack passes vers=null to mount.nfs, which results in a mount failure.

**Evidence**

1. Configuration value (in DB)

```
mysql> SELECT name,value,description
    -> FROM configuration
    -> WHERE name RLIKE 'secstorage.*nfs.*version|(^|\\.)nfs\\..*version|(^|\\.)nfs\\.version'
    -> ORDER BY name;
+------------------------+-------+-------------------------------------------------------------------------------------------------------+
| name                   | value | description                                                                                           |
+------------------------+-------+-------------------------------------------------------------------------------------------------------+
| secstorage.nfs.version | NULL  | Enforces specific NFS version when mounting Secondary Storage. If NULL default selection is performed |
+------------------------+-------+-------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

2. SSVM mount command generated by CloudStack

From SSVM logs:

```
/var/log/cloud.log:192:2026-01-13T07:34:23,658 WARN  [storage.resource.NfsSecondaryStorageResource] (AgentRequest-Handler-7:[]) Execution of process [4146] for command [mount -t nfs -o soft,timeo=133,retrans=2147483647,tcp,acdirmax=0,acdirmin=0,vers=null 10.0.32.4:/acs/secondary/ref-trl-10584-k-Mol9-rositsa-kyuchukova/ref-trl-10584-k-Mol9-rositsa-kyuchukova-sec3 /mnt/SecStorage/6ff0eb2d-ffed-31c8-8f8c-e2c5c1fb2db5 ] failed.
```

3. Error produced:

```
/var/log/cloud.log:214:2026-01-13T07:34:23,684 ERROR [storage.resource.NfsSecondaryStorageResource] (AgentRequest-Handler-7:[]) failed to copy filetemplate/tmpl/1/4/0c364cce-8288-3a92-9234-4ffde372aec7.qcow2 com.cloud.utils.exception.CloudRuntimeException: GetRootDir for nfs://10.0.32.4/acs/secondary/ref-trl-10584-k-Mol9-rositsa-kyuchukova/ref-trl-10584-k-Mol9-rositsa-kyuchukova-sec3 failed due to com.cloud.utils.exception.CloudRuntimeException: Unable to mount 10.0.32.4:/acs/secondary/ref-trl-10584-k-Mol9-rositsa-kyuchukova/ref-trl-10584-k-Mol9-rositsa-kyuchukova-sec3 at /mnt/SecStorage/6ff0eb2d-ffed-31c8-8f8c-e2c5c1fb2db5 due to mount.nfs: parsing error on 'vers=' option
```

4. SSVM environment confirmation:

```
root@s-4-VM:~# uname -a
Linux s-4-VM 6.1.0-40-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.153-1 (2025-09-20) x86_64 GNU/Linux
root@s-4-VM:~# 
root@s-4-VM:~# 
root@s-4-VM:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@s-4-VM:~# 
root@s-4-VM:~# 
root@s-4-VM:~# mount.nfs -V
mount.nfs: (linux nfs-utils 2.6.2)
```

5. NFS works for the same Secondary Storage export when an invalid vers= option is not supplied

The same NFS export path used for sec3 mounts successfully on the SSVM with negotiated NFSv4.2, as shown by existing mounts:

```
root@s-4-VM:~# mount | egrep -i 'nfs|sec' || true
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)

10.0.32.4:/acs/secondary/ref-trl-10584-k-Mol9-rositsa-kyuchukova/ref-trl-10584-k-Mol9-rositsa-kyuchukova-sec3 on /mnt/SecStorage/6ff0eb2d-ffed-31c8-8f8c-e2c5c1fb2db5 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acdirmin=0,acdirmax=0,soft,proto=tcp,timeo=133,retrans=2147483647,sec=sys,clientaddr=10.0.42.148,local_lock=none,addr=10.0.32.4)
```

**Impact**

- Adding a new Secondary Storage may fail intermittently or fully
- Template copy operations can fail with misleading “copy failed” errors
- Behavior contradicts documented configuration semantics

### versions

**Environment**

- Apache CloudStack: 4.20.3.0-SNAPSHOT
- Hypervisor: KVM
- Secondary Storage: NFS
- SSVM OS: Debian GNU/Linux 12 (bookworm)
- Kernel: Linux 6.1.0-40-amd64
- nfs-utils: mount.nfs (linux nfs-utils 2.6.2)

### The steps to reproduce the bug

1. Deploy Apache CloudStack 4.20.3.0-SNAPSHOT with:

- KVM hypervisor
- NFS-based Secondary Storage
- SSVM template: Debian 12 (environment detail)
- Ensure global setting secstorage.nfs.version is unset (NULL):

```
mysql> SELECT name,value FROM configuration WHERE name='secstorage.nfs.version';
+------------------------+-------+
| name                   | value |
+------------------------+-------+
| secstorage.nfs.version | NULL  |
+------------------------+-------+
1 row in set (0.00 sec)
```

2. Add a new Secondary Storage (Image Store) backed by NFS (UI/API: addImageStore).

3. Observe SSVM logs: mount command contains vers=null.

4. Observe mount fails with mount.nfs: parsing error on 'vers=' option.

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR fixes #12415 

The agent.properties contains "nfsVersion = null" if the global settings `secstorage.nfs.version` is not set.
`NfsSecondaryStorageResource` picks up the nfsVersion as "null" String in `CopyCommand` and some other commands, and tries to mount the secondary storage with `vers=null` option leading  to mount failures in logs.

Screenshot 2026-01-16 at 12 40 19 PM

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by abh1sar** [comment]
@blueorangutan package

**Review by DaanHoogland — COMMENTED** [review]
@abh1sar , this looks good, but you mention, "in CopyCommand and some other commands”. Does this mean this construct needs to be applied in several locations? (and hence methodised)

File: services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java [hunk 1]
```diff
@@ -1225,7 +1225,9 @@ public boolean finalizeVirtualMachineProfile(VirtualMachineProfile profile, Depl
             buf.append(" dns2=").append(dc.getDns2());
         }
         String nfsVersion = imageStoreDetailsUtil != null ? imageStoreDetailsUtil.getNfsVersion(secStores.get(0).getId()) : null;
-        buf.append(" nfsVersion=").append(nfsVersion);
+        if (nfsVersion != null) {
```
Comment (vishesh92) [inline services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java]: Should we add a check for isNotBlank instead? If for some reason, `secstorage.nfs.version` is an empty string for the image store instead of null, this might cause errors.

Comment (abh1sar) [reply services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java]: that's a good idea. I'll make the change.

**Comment by abh1sar** [comment]
> @abh1sar , this looks good, but you mention, "in CopyCommand and some other commands”. Does this mean this construct needs to be applied in several locations? (and hence methodised)

All the commands take the value from the same place.

**Comment by DaanHoogland** [comment]
> > @abh1sar , this looks good, but you mention, "in CopyCommand and some other commands”. Does this mean this construct needs to be applied in several locations? (and hence methodised)
> 
> All the commands take the value from the same place.

meaning they all pass through this big ass `finalizeVirtualMachineProfile()` right? in that case 👍 .

**Review by DaanHoogland — APPROVED** [review]
clgtm, (of course this method needs chopping up.)

**Comment by abh1sar** [comment]
> > > @abh1sar , this looks good, but you mention, "in CopyCommand and some other commands”. Does this mean this construct needs to be applied in several locations? (and hence methodised)
> > 
> > 
> > All the commands take the value from the same place.
> 
> meaning they all pass through this big ass `finalizeVirtualMachineProfile()` right? in that case 👍 .

Yes, they all read the value of nfsVersion from agent.properties which is set via `finalizeVirtualMachineProfile()`

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by RosiKyu — APPROVED** [review]
**LGTM**

<p><strong>Fixes:</strong> #12415 - <code>secstorage.nfs.version = NULL</code> results in <code>vers=null</code> mount option and SSVM NFS mount failure</p>
<hr>
<h2>Pre-Test Configuration</h2>
<p>Confirmed <code>secstorage.nfs.version</code> is NULL (the bug trigger condition):</p>
<pre><code class="language-sql">mysql&gt; SELECT name, value FROM configuration WHERE name='secstorage.nfs.version';
+------------------------+-------+
| name                   | value |
+------------------------+-------+
| secstorage.nfs.version | NULL  |
+------------------------+-------+
1 row in set (0.00 sec)
</code></pre>
<hr>
<h2>Test 1: Verify nfsVersion Not in SSVM Boot Arguments</h2>
<pre><code class="language-bash">root@s-1-VM:~# cat /var/cache/cloud/cmdline | tr ' ' '\n' | grep -i nfs
root@s-1-VM:~# 

root@s-1-VM:~# grep -i nfsversion /etc/cloudstack/agent/agent.properties
grep: /etc/cloudstack/agent/agent.properties: No such file or directory
</code></pre>
<p><strong>Result: PASS</strong> - <code>nfsVersion</code> parameter is ABSENT from boot arguments (not <code>nfsVersion=null</code>)</p>
<hr>
<h2>Test 2: Verify Existing NFS Mounts Working</h2>
<pre><code class="language-bash">root@s-1-VM:~# mount | grep nfs
10.0.32.4:/acs/secondary/ref-trl-10637-k-Mol9-rositsa-kyuchukova/ref-trl-10637-k-Mol9-rositsa-kyuchukova-sec1 on /mnt/SecStorage/db6cac5e-bd12-3be8-ad93-324d1bd6a5a9 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acdirmin=0,acdirmax=0,soft,proto=tcp,timeo=133,retrans=2147483647,sec=sys,clientaddr=10.0.37.116,local_lock=none,addr=10.0.32.4)
10.0.32.4:/acs/secondary/ref-trl-10637-k-Mol9-rositsa-kyuchukova/ref-trl-10637-k-Mol9-rositsa-kyuchukova-sec2 on /mnt/SecStorage/41c5fac8-5833-3769-a25b-d326c94bf416 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acdirmin=0,acdirmax=0,soft,proto=tcp,timeo=133,retrans=2147483647,sec=sys,clientaddr=10.0.37.116,local_lock=none,addr=10.0.32.4)
</code></pre>
<p><strong>Result: PASS</strong> - Both sec1 and sec2 mounted successfully with auto-negotiated <code>vers=4.2</code></p>
<hr>
<h2>Test 3: Verify No vers=null Errors in Logs</h2>
<pre><code class="language-bash">root@s-1-VM:~# grep -i "vers=null" /var/log/cloud.log
root@s-1-VM:~#
</code></pre>
<p><strong>Result: PASS</strong> - No <code>vers=null</code> mount errors found in SSVM logs</p>
<hr>
<h2>Test 4: Add New Secondary Storage (Critical Test)</h2>
<p>Added new secondary storage sec3. This is the operation that failed in the bug report.</p>
<pre><code class="language-bash">root@s-1-VM:~# mount | grep sec3
10.0.32.4:/acs/secondary/ref-trl-10637-k-Mol9-rositsa-kyuchukova/ref-trl-10637-k-Mol9-rositsa-kyuchukova-sec3 on /mnt/SecStorage/809fc3bc-3a29-335e-ac0d-eb1acc7551bb type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acdirmin=0,acdirmax=0,soft,proto=tcp,timeo=133,retrans=2147483647,sec=sys,clientaddr=10.0.37.116,local_lock=none,addr=10.0.32.4)
</code></pre>
<p><strong>Result: PASS</strong> - sec3 mounted successfully with auto-negotiated <code>vers=4.2</code>, NO <code>vers=null</code> error</p>
<hr>
<h2>Test 5: Verify Template Copy Operations</h2>
<pre><code class="language-bash">[root@mgmt1 ~]# tail -500 /var/log/cloudstack/management/management-server.log | grep -i "sec3"
2026-01-18 07:40:34,984 INFO  [o.a.c.s.i.TemplateServiceImpl] (pool-378-thread-2:[]) (logid:793cfd5b) Copied template [routing-3] to image store [sec3].
2026-01-18 07:40:51,369 INFO  [o.a.c.s.i.TemplateServiceImpl] (pool-378-thread-1:[]) (logid:793cfd5b) Copied template [centos55-x86_64] to image store [sec3].
2026-01-18 07:41:11,790 DEBUG [c.c.s.StatsCollector] (secstorage-1:[ctx-7ae0f021]) (logid:a61f3242) Verifying image storage [ImageStore {"id":3,"name":"sec3","uuid":"60472c35-d821-46cb-a5cc-7c94abbb6da8"}]. Capacity: total=[2.6357 TB], used=[1.5384 TB], threshold=[95.00%].
</code></pre>
<p><strong>Result: PASS</strong> - Templates copied successfully to new secondary storage</p>
<hr>
<h2>Test 6: Verify SSVM Initialization</h2>
<pre><code class="language-bash">root@s-1-VM:~# journalctl -u cloud --no-pager | tail -5
Jan 18 07:40:28 s-1-VM _run.sh[3439]: 07:40:28,384  INFO NfsSecondaryStorageResource:3168 - Determined host 10.0.32.4 corresponds to IP 10.0.32.4
Jan 18 07:40:28 s-1-VM _run.sh[3439]: 07:40:28,685  INFO NfsSecondaryStorageResource:3232 - snapshots directory created/exists on Secondary Storage.
Jan 18 07:40:28 s-1-VM _run.sh[3439]: 07:40:28,689  INFO NfsSecondaryStorageResource:3232 - volumes directory created/exists on Secondary Storage.
Jan 18 07:40:49 s-1-VM _run.sh[3439]: 07:40:49,349  INFO NfsSecondaryStorageResource:3168 - Determined host 10.0.32.4 corresponds to IP 10.0.32.4
</code></pre>
<p><strong>Result: PASS</strong> - Secondary storage initialized successfully, required directories created</p>
<hr>
<h2>Summary</h2>

Test | Result
-- | --
Existing NFS mounts (sec1, sec2) | PASS - vers=4.2
Add new secondary storage (sec3) | PASS - vers=4.2
Template copy to sec3 | PASS
SSVM initialization | PASS


<hr>
<h2>Conclusion</h2>
<p><strong>LGTM </strong></p>
<p>The fix correctly omits the <code>nfsVersion</code> parameter from SSVM boot arguments when <code>secstorage.nfs.version</code> is NULL, allowing the OS to auto-negotiate the NFS version instead of failing with <code>mount.nfs: parsing error on 'vers=' option</code>.</p></body></html>

**Comment by abh1sar** [comment]
@blueorangutan test

**Comment by abh1sar** [comment]
@blueorangutan test keepEnv

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test
