### PR TITLE
Fix url in password reset email

### LINKED ISSUE #12050: [Password Reset Email Template Ignores {{domainUrl}} Variable in CloudStack 4.22]
### problem

When configuring password reset email templates in CloudStack 4.22, the variable _{{domainUrl}}_ or _{{{domainUrl}}}_ is ignored during email generation.
The reset link in the email only contains a relative path (e.g., _/client/#/user/resetPassword?..._) instead of a complete URL (_https://cloudstack.example.com/client/#/user/resetPassword?..._).

This causes broken links when users click “Reset Password” from the email, as the base domain is missing.

### versions

General Information:
- CloudStack version: 4.22.0 (upgraded from 4.21.0)
- Operating System: Ubuntu Server 24.04 LTS
- Java version: OpenJDK 17.0.16

Deployment Setup:
- Number of Management Server(s): 2 (1 Active + 1 Stopped)
- CloudStack DB Server(s): 2 MySQL DB (1 Primary + 1 Replica)
- Hypervisor: VMware ESXi (version 7.0 Update 3)
- vCenter Version: vSphere Client version 7.0.3.00000
- ESXi Hosts: 2
- SMTP Server: Microsoft Office 365 (smtp.office365.com, port 587)

### The steps to reproduce the bug

1. Find the global configuration called "User password reset mail domain url" and put in the relevant domain name.
2. Find another global configuration called "User password reset mail template" and you can choose to either edit or use the default email template to test SMTP.
3. Once configured both, you need to wait for 30 seconds then try to request a password reset on the landing / login page.
4. Once the email comes in, it will show the message you've written with the broken password reset link. It will not have the {{{domainUrl}}} called into the email / message template. Only resetLink, token will be called succesfully into the email / message.
...

### What to do about it?

The variable _{{{domainUrl}}}_ defined in **Global Settings → user.password.reset.mail.domain.url** should be properly parsed and included in the email body when rendering the reset link.

Currently, the email template engine ignores the {{{domainUrl}}} placeholder entirely, resulting in an incomplete reset link that starts only from _client/#/user/resetPassword?...._

To fix this:

1. Ensure that the _domainUrl_ variable is fetched and passed correctly to the email rendering context (e.g., in _UserPasswordResetManagerImpl.java_).
2. Verify that both _domainUrl_ and _resetLink_ variables are available to the Mustache template at render time.
3. Consider adding a validation check to confirm that _domainUrl_ is not null or empty before sending the email.
4. (Optional) Update the documentation to clarify how _user.password.reset.mail.domain.url_ interacts with the reset link template variables.

This would ensure the password reset email renders correctly as:
`https://cloudstack.example.com/client/#/user/resetPassword?username=user&token=xxxx`

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR fixes the url in password reset email. (regression from https://github.com/apache/cloudstack/pull/11379)

Fixes #12050 

Doc PR: https://github.com/apache/cloudstack-documentation/pull/621

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java [hunk 1]
```diff
@@ -179,10 +180,14 @@ public void setResetTokenAndSend(UserAccount userAccount) {
         final String email = userAccount.getEmail();
         final String username = userAccount.getUsername();
         final String subject = "Password Reset Request";
-        final String domainUrl = UserPasswordResetDomainURL.value();
+        String domainUrl = UserPasswordResetDomainURL.value();
+        if (StringUtils.isBlank(domainUrl)) {
+            domainUrl = ManagementServerAddresses.value().split(",")[0];
```
[the remark this answers is not in the document]
Comment (sureshanaparti) [reply server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java]: `ManagementServerAddresses.value().split(",")[0]` used previously, and no issues with it. ManagementServerAddresses.value() is defaulted to localhost.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java [hunk 2]
```diff
@@ -179,10 +180,14 @@ public void setResetTokenAndSend(UserAccount userAccount) {
...
+        }
+        domainUrl = domainUrl.trim().replaceAll("/+$", "");
```
Comment (DaanHoogland) [inline server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java]: is this needed?

**Review by DaanHoogland — COMMENTED** [review]
looks generally good, one question.

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java (hunk 2 above)
Comment (sureshanaparti) [reply server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java]: yes @DaanHoogland , in case the domain url setting has value like "https://xyz.com/" , trail / are not needed as it's considered while formatting the reset link.

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java (hunk 2 above)
Comment (DaanHoogland) [reply server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java]: but it will not be in the way either, will it?

Comment (daviftorres) [reply server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java]: Good point, @DaanHoogland. While the extra `/` usually won’t cause issues, it could create problems in environments where admins use a reverse proxy with strict access rules for the reset-password URL.

For example, some organization could only allow access to password-reset endpoints from the office network or over the company VPN. This would reduce the attack surface to a very sensitive endpoint that is often forgotten.

**Comment by vladimirpetrov** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by kiranchavala — COMMENTED** [review]
Hi @sureshanaparti 

As discussed please add http before the domain or management IP to make sure the link is clickable 

Please check  the screenshot 

with domainurl 

Screenshot 2025-12-05 at 5 51 56 PM


Without domainurl 

Screenshot 2025-12-05 at 5 57 02 PM

**Comment by sureshanaparti** [comment]
> Hi @sureshanaparti
> 
> As discussed please add http before the domain or management IP to make sure the link is clickable
> 

updated @kiranchavala

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by davift** [comment]
> Hi @sureshanaparti
> 
> As discussed please add http before the domain or management IP to make sure the link is clickable
> 
> Please check the screenshot
> 
> with domainurl
> 
> Screenshot 2025-12-05 at 5 51 56 PM
> Without domainurl
> 
> Screenshot 2025-12-05 at 5 57 02 PM

dear @kiranchavala and @sureshanaparti ,

I appreciated the checks for the presence of `http://` or `https://`, as well as the logic to apply a default when neither is provided. My recommendation would be to always default to `https://` and require users to manually choose a less secure option if they really need it.

This mindset should be applied universally, as users tend to accept whatever the default is. Beyond the general risk of “rogue Wi-Fi” exposing password-reset links, browsers are increasingly moving toward HTTPS-first behavior, and email filters/inspection systems are becoming more suspicious of plain-text HTTP URLs.

Please understand this as purely constructive feedback.

**Comment by sureshanaparti** [comment]
> > Hi @sureshanaparti
> > As discussed please add http before the domain or management IP to make sure the link is clickable
> > Please check the screenshot
> > with domainurl
> 
> dear @kiranchavala and @sureshanaparti ,
> 
> I appreciated the checks for the presence of `http://` or `https://`, as well as the logic to apply a default when neither is provided. My recommendation would be to always default to `https://` and require users to manually choose a less secure option if they really need it.
> 
> This mindset should be applied universally, as users tend to accept whatever the default is. Beyond the general risk of “rogue Wi-Fi” exposing password-reset links, browsers are increasingly moving toward HTTPS-first behavior, and email filters/inspection systems are becoming more suspicious of plain-text HTTP URLs.
> 
> Please understand this as purely constructive feedback.

@davift thanks for the feedback. earlier the password reset link was defaulted to `http://`, so I've considered the same. Now, I updated the scheme based on the _https.enabled_ flag in server.properties file in the management server (as SSL is enabled when it is set - https://docs.cloudstack.apache.org/en/4.22.0.0/installguide/optional_installation.html#ssl-optional).

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

File: utils/src/main/java/com/cloud/utils/server/ServerProperties.java [hunk 3]
```diff
@@ -56,4 +63,25 @@ public synchronized static Properties getServerProperties(InputStream inputStrea
 
         return properties;
     }
+
+    public static boolean isHttpsEnabled() {
```
Comment (vishesh92) [inline utils/src/main/java/com/cloud/utils/server/ServerProperties.java]: IMO, it will be better to set a variable during initialization and just return that. Updating https and other things, require restarting server anyway.

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java [hunk 4]
```diff
@@ -179,10 +181,21 @@ public void setResetTokenAndSend(UserAccount userAccount) {
...
-        String resetLink = String.format("/client/#/user/resetPassword?username=%s&token=%s",
-                username, resetToken);
+        if (!domainUrl.startsWith("http://") && !domainUrl.startsWith("https://")) {
+            if (ServerProperties.isHttpsEnabled()) {
+                domainUrl = "https://" + domainUrl;
+            } else {
+                domainUrl = "http://" + domainUrl;
+            }
+        }
+        String resetLink = String.format("%s/client/#/user/resetPassword?username=%s&token=%s",
```
Comment (vishesh92) [inline server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java:202]: This is changing the definition of `resetLink`. This could cause issues during an upgrade. Let's just append `/` at the end of the domain URL and use `{{{domainUrl}}}/{{{resetLink}}}`.

**Review by vishesh92 — COMMENTED** [review]
Left some comments.

File: utils/src/main/java/com/cloud/utils/server/ServerProperties.java (hunk 3 above)
Comment (sureshanaparti) [reply utils/src/main/java/com/cloud/utils/server/ServerProperties.java]: it's already set in ServerDaemon, but not directly accessible. so checking it through server properties where the config is defined.

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java (hunk 4 above)
Comment (sureshanaparti) [reply server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManagerImpl.java:202]: `resetLink` was used earlier, and there is regression with https://github.com/apache/cloudstack/pull/11379. `domainUrl` is never passed to build the message content, keeping `resetLink` as earlier which url as well.

**Comment by kiranchavala** [comment]
@blueorangutan package

File: utils/src/main/java/com/cloud/utils/server/ServerProperties.java (hunk 3 above)
Comment (sureshanaparti) [reply utils/src/main/java/com/cloud/utils/server/ServerProperties.java]: @vishesh92 update, please check.

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested with no value in user.password.reset.mail.domain.url

Screenshot 2026-01-28 at 2 10 29 PM

Tested with value user.password.reset.mail.domain.url set to kiranchavala.in 

HTTP got appened

Screenshot 2026-01-28 at 2 10 22 PM


Tested with value user.password.reset.mail.domain.url to set to a port kiranchavala.in:908

Screenshot 2026-01-28 at 2 17 44 PM


Tested with value user.password.reset.mail.domain.url  set to https

Screenshot 2026-01-28 at 2 19 12 PM
