### PR TITLE
UI support for extraconfig in deploy and update instance 

### LINKED ISSUE #7849: UI: deploy and update vm instances with extraconfig
vm extra config is supported since cloudstack 4.12 (see PR #3510)
However, there is no UI support for it.
- deploy vm with extra config
- update vm with extra config

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR fixes #7849

Also fixes a bug in kvm extraconfig #11718 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot 2025-09-25 at 2 44 25 PM
Screenshot 2025-09-25 at 2 45 04 PM

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code  lgtm

added to 4.20.2 milestone

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

File: api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java [hunk 1]
```diff
@@ -140,6 +140,10 @@ public class CapabilitiesResponse extends BaseResponse {
     @Param(description = "true if dynamically scaling for instances is enabled", since = "4.21.0")
     private Boolean dynamicScalingEnabled;
 
+    @SerializedName(ApiConstants.ADDITONAL_CONFIG_ENABLED)
+    @Param(description = "true if additional configurations or extraconfig can be passed to Instances", since = "4.20.2")
```
Comment (shwstppr) [inline api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java:144]: Not related to this PR but as some point we should start using a generic Map response or some other means. Adding a new response param for a new global setting value is an unnecessary hassle

File: ui/src/views/compute/EditVM.vue [hunk 2]
```diff
@@ -164,7 +170,8 @@ export default {
       groups: {
         loading: false,
         opts: []
-      }
+      },
+      extraConfigEnabled: this.$store.getters.features.additionalconfigenabled
```
Comment (shwstppr) [inline ui/src/views/compute/EditVM.vue]: curious - why a computed variable in DeployVM and a data variable here?

**Review by shwstppr — APPROVED** [review]
LGTM - haven't tested

**Review by shwstppr — COMMENTED** [review]
Tested 4.20.2 env with changes. I could see extraconfig being processed by the host,

```
2025-09-26 09:15:58,523 DEBUG [kvm.resource.LibvirtComputingResource] (AgentRequest-Handler-1:[]) (logid:) Appending extra configuration data [{extraconfig-1=abc=444, extraconfig-2=xyz=777}] to guest VM [VM {id: "23", name: "i-2-23-VM", uuid: "f6c36574-f999-4ea2-b9b0-3474067b0c0f", type: "User"}] domain XML.
```

For update VM,
- Maybe we should highlight that VM needs to be stop-started or allow extraconfig only for stopped VM. `a-alert` can be used to show an appropriate message.
- Currently, existing extraconfig value is overridden so it would be better if UpdateVM form shows the existing value pre-filled.

@abh1sar

File: ui/src/views/compute/EditVM.vue (hunk 2 above)
Comment (abh1sar) [reply ui/src/views/compute/EditVM.vue]: no specific reason. It could have been a data variable in DeployVM as well. Just followed the existing pattern in the file.

File: api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java (hunk 1 above)
Comment (abh1sar) [reply api/src/main/java/org/apache/cloudstack/api/response/CapabilitiesResponse.java:144]: +1

**Comment by abh1sar** [comment]
> For update VM,
> 
> * Maybe we should highlight that VM needs to be stop-started or allow extraconfig only for stopped VM. `a-alert` can be used to show an appropriate message.

I'll add that @shwstppr 
> * Currently, existing extraconfig value is overridden so it would be better if UpdateVM form shows the existing value pre-filled.

This can be done but is a bit tricky as multiple extraconfigs are stored and shown as separate keys. e.g,
```
    "details": {                                     
      "Message.ReservedCapacityFreed.Flag": "false",
      "cpuOvercommitRatio": "2.0",
      "extraconfig-1": "<memoryBacking>\n    <locked/>\n</memoryBacking>",
      "extraconfig-2": "<memoryBacking>\n    <nosharepages/>\n</memoryBacking>"
    },
```
I would have to combine these into a single string in UI
```
<memoryBacking>
    <locked/>
</memoryBacking>

<memoryBacking>
    <nosharepages/>
</memoryBacking>
```

One more thing is that the separator is different in VMware/XenServer and KVM
Vmware/Xen : Single new line (`String[] extraConfigs = decodedUrl.split("\\r?\\n");`
KVM : Double new lines (` String[] extraConfigs = decodedUrl.split("\n\n");`


I am thinking that for displaying, I can insert two double lines between extra config by default. And modify the VMware/Xen separator to handle multiple newlines `split.("\\r?\\n+)"`. That will take care of both cases

This would need testing on all 3 hypervisors

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
> * Maybe we should highlight that VM needs to be stop-started or allow extraconfig only for stopped VM. `a-alert` can be used to show an appropriate message.

@shwstppr the form already contains a warning at the top

Screenshot 2025-09-29 at 5 16 51 PM

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
Image

LGTM. Existing config shown in the Update VM form. Tested with a KVM env

**Comment by weizhouapache** [comment]
thanks @shwstppr for the testing

merging
