### PR TITLE
VPC restart cleanup for Public networks with multi-CIDR data

### LINKED ISSUE #12621: VPC restart with cleanup fails when VPC has multiple public IP ranges from different VLANs — "cidr is not formatted correctly"
### problem

When restarting a VPC with cleanup=true that has public IPs from different VLAN ranges, the operation fails with:

cidr is not formatted correctly: 192.168.2.0/24,160.0.0.0/24

Expected Behavior:

VPC restarts successfully.

Actual Behavior:

VPC restart fails with error:

cidr is not formatted correctly: 192.168.2.0/24,160.0.0.0/24

### versions

4.21
kvm

### The steps to reproduce the bug

Steps to Reproduce:

In an existing zone, add a second public IP range on a different VLAN (e.g., if the zone already has a range like 183.9.9.0/24 on VLAN 100, add a new range like 160.0.0.0/24 on VLAN 200)
Create a VPC
Create a network tier (subnet) inside the VPC
Deploy a VM inside that tier
Acquire a public IP from the second VLAN range and assign it to the VM (so the VPC now has the default Source NAT IP from the first range and the newly acquired IP from the second range)
Go to the VPC and click Restart VPC with "Clean up" enabled

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by jeanvetorello**
#12621
Fix VPC restart with multi-CIDR networks: handle comma-separated CIDR in NetworkVO.equals()

When a network has multiple CIDRs (e.g. '192.168.2.0/24,160.0.0.0/24'), NetworkVO.equals() passes the raw comma-separated string to NetUtils.isNetworkAWithinNetworkB() which expects a single CIDR, causing 'cidr is not formatted correctly' error during VPC restart with cleanup=true.

Extract only the first CIDR value before passing to NetUtils.

### Description
This PR addresses VPC restart failures during cleanup in environments where Public networks contain legacy aggregated network data (multiple values stored in network-level CIDR and gateway fields).

This PR...

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

#### Bug Severity

- [x] Major

### How Has This Been Tested?
- Reproduced the issue on a CloudStack 4.21.0.0 environment with two public IP ranges
  on different VLANs assigned to the same VPC
- Applied the fix and confirmed VPC restart with cleanup=true completes successfully
- Verified unit tests pass for NetworkVO.equals() with both single and comma-separated CIDRs

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
as we discussed in the comments of https://github.com/apache/cloudstack/issues/12621, we need to work on another solution

can you work on the fix ? cc @jeanvetorello @sureshanaparti

File: engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java [hunk 1]
```diff
@@ -600,7 +600,9 @@ public boolean equals(Object obj) {
             return true;
         }
 
-        return NetUtils.isNetworkAWithinNetworkB(cidr, that.cidr);
+        return NetUtils.isNetworkAWithinNetworkB(
+                com.cloud.utils.StringUtils.getFirstValueFromCommaSeparatedString(cidr),
+                com.cloud.utils.StringUtils.getFirstValueFromCommaSeparatedString(that.cidr));
```
[the remark this answers is not in the document]
Comment (sureshanaparti) [reply engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java]: Hi @jeanvetorello Can you check this? Also, Check _getFirstValueFromCommaSeparatedString()_ can be included in cidrToLong() method to avoid this issue from other usages.

**Comment by sureshanaparti** [comment]
@jeanvetorello can you rebase this PR with 4.22 branch, and address the outstanding comments.

**Comment by DaanHoogland** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java [hunk 2]
```diff
@@ -600,7 +600,10 @@ public boolean equals(Object obj) {
             return true;
         }
 
-        return NetUtils.isNetworkAWithinNetworkB(cidr, that.cidr);
+        final String normalizedCidr = com.cloud.utils.StringUtils.getFirstValueFromCommaSeparatedString(cidr);
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java]: these changes should be reverted, I think ?

Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/network/dao/NetworkVO.java]: @jeanvetorello 
are you available to work on this PR ?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@jeanvetorello 
thanks for the update

can you update the PR title add description ?

Can you also add a SQL change to update some fields of Public network to NULL ? https://github.com/apache/cloudstack/blob/4.22/engine/schema/src/main/resources/META-INF/db/schema-42200to42210.sql

I think
```
        broadcast_uri: NULL
              gateway: NULL
                 cidr: NULL
          ip6_gateway: NULL
             ip6_cidr: NULL
```

**Review by weizhouapache — APPROVED** [review]
code lgtm

@jeanvetorello 
can you plaese update the description as well ? thanks

**Comment by DaanHoogland** [comment]
@weizhouapache, @jeanvetorello did update the title. Is this to satisfaction?]
@sureshanaparti, is this lgty now?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by kiranchavala — APPROVED** [review]
LGTM 

Tested manually 


1. In an existing zone, add a second public IP range on a different VLAN (e.g., if the zone already has a range like 183.9.9.0/24 on VLAN 100, add a new range like 160.0.0.0/24 on VLAN 200)

2. Create a VPC

3. Create a network tier (subnet) inside the VPC

4. Deploy a VM inside that tier

5. Acquire a public IP from the second VLAN range and assign it to the VM (so the VPC now has the default Source NAT IP from the first range and the newly acquired IP from the second range)

6. Go to the VPC and click Restart VPC with "Clean up" enabled


VPC got restarted successfully without any issues
