### PR TITLE
Skip systemVM template registration for Simulator

### LINKED ISSUE #5936: NPE on simulator launch
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.0-SNAPSHOT
~~~

##### CONFIGURATION

I'm using the latest 4.16 Master and building the simulator image manually

##### OS / ENVIRONMENT

Ubuntu 21.10
OpenJDK 11

##### SUMMARY

```bash
INFO  [o.a.c.s.d.p.DefaultHostListener] (ApiServer-10:ctx-d982031c ctx-6062c5c0) (logid:aac2a26e) Connection established between storage pool org.apache.cloud
stack.storage.datastore.PrimaryDataStoreImpl@3953e834 and host 1                                                                                              
INFO  [o.a.c.s.d.l.SimulatorImageStoreLifeCycleImpl] (ApiServer-1:ctx-58b428a9 ctx-9c2836b5) (logid:5b4df9e5) Trying to add a new data store at nfs://10.147.2
8.6:/export/home/sandbox/sstor to data center 1                                                                                                               
ERROR [o.a.c.s.i.TemplateServiceImpl] (ApiServer-1:ctx-58b428a9 ctx-9c2836b5) (logid:5b4df9e5) No remote endpoint to send command, check if host or ssvm is do
wn?                                                                                                                                                           
ERROR [c.c.u.SystemVmTemplateRegistration] (ApiServer-1:ctx-58b428a9 ctx-9c2836b5) (logid:5b4df9e5) Failed to register template for hypervisor: Simulator
java.lang.NullPointerException                                                                                                                                
        at com.cloud.upgrade.SystemVmTemplateRegistration.registerTemplate(SystemVmTemplateRegistration.java:676)            
        at com.cloud.storage.StorageManagerImpl$3.doInTransactionWithoutResult(StorageManagerImpl.java:2834)              
        at com.cloud.utils.db.TransactionCallbackNoReturn.doInTransaction(TransactionCallbackNoReturn.java:25)                                      
        at com.cloud.utils.db.Transaction$2.doInTransaction(Transaction.java:50)                                                                              
        at com.cloud.utils.db.Transaction.execute(Transaction.java:40)                                                                                        
        at com.cloud.utils.db.Transaction.execute(Transaction.java:47) 
        at com.cloud.storage.StorageManagerImpl.registerSystemVmTemplateOnFirstNfsStore(StorageManagerImpl.java:2791)                                         
        at com.cloud.storage.StorageManagerImpl.discoverImageStore(StorageManagerImpl.java:2775)                                                       
```

##### STEPS TO REPRODUCE

I'm following the simulator docs [here](https://docs.cloudstack.apache.org/en/4.16.0.0/developersguide/developer_guide.html?highlight=simulator#using-the-simulator)

~~~

~~~

##### EXPECTED RESULTS

~~~
Simulator starts successfully
~~~

##### ACTUAL RESULTS

~~~
Simulator fails with NPE on start and ACS won't boot
~~~

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes #5936 - prevents registration of systemVM template for Simulator hypervisor

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Deploy a simulator hypervisor with advanced zone, and observed logs during addition of secondary store - no NPE

### CODE REVIEW

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java [hunk 1]
```diff
@@ -2808,30 +2808,32 @@ public void doInTransactionWithoutResult(final TransactionStatus status) {
...
-                                    VMTemplateVO vmTemplateVO = null;
-                                    TemplateDataStoreVO templateVO = null;
-                                    if (templateId != null) {
-                                        vmTemplateVO = _templateDao.findById(templateId);
-                                        templateVO = _templateStoreDao.findByTemplate(templateId, DataStoreRole.Image);
-                                        if (templateVO != null) {
-                                            try {
-                                                if (SystemVmTemplateRegistration.validateIfSeeded(url, templateVO.getInstallPath())) {
-                                                    continue;
+                                    if (HypervisorType.Simulator != hypervisorType) {
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/storage/StorageManagerImpl.java:2811]: @Pearl1594 nit-picking but can we use `continue` instead of wrapping everything in a new if statement

**Comment by sureshanaparti** [comment]
Hi @Pearl1594 Is this good to go in 4.16.1 ?

**Comment by Pearl1594** [comment]
yes @sureshanaparti

**Review by rohityadavcloud — APPROVED** [review]

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java [hunk 2]
```diff
@@ -2808,6 +2808,9 @@ public void doInTransactionWithoutResult(final TransactionStatus status) {
                             Pair<String, Long> storeUrlAndId = new Pair<>(url, store.getId());
                             for (HypervisorType hypervisorType : hypSet) {
                                 try {
+                                    if (HypervisorType.Simulator == hypervisorType) {
+                                        continue;
+                                    }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/storage/StorageManagerImpl.java:2813]: I don't like that simulator is referenced in production code. Not sure what the solution would be in this case. Open for suggestions.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test
