### PR TITLE
Prevent deletion of account and domain if either of them has deleted protected instance

### LINKED ISSUE #12895: "Delete Protection" is not honored when clean up an account or a domain
### problem

As title.

Steps to reproduce the issue:

- Create a VM

- Edit the VM and enable “Delete Protection”

- Delete the VM, got an error as expected:
- 
Image

- Disable the account → the VM is stopped, and Delete Protection remains enabled

- Delete the account → the VM is expunged

**Expected behavior: The VM should not be deleted when Delete Protection is enabled.

The same issue also occurs when cleaning up a domain.**

### versions

ACS 4.22
 (4.20.2 is also impacted)

### The steps to reproduce the bug

1.
2.
3.
...

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by sudo87**
### Description

This PR address https://github.com/apache/cloudstack/issues/12895 by skipping Instances having deleteProtection enabled.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

For Account deletion:

1. Create new Account: acc1
2. Create new Instance and enable delete protection for acc1
3. Disable the acc1 from admin account
4. Try deletion acc1 from admin account, expect error

For Domain deletion:

1. Setup t1 -> t2 -> t3 domain
2. Create new Accounts t3acc1, t3acc2 at t3 level
3. Spin off Instances with delete protection for either of the accounts
4. Try deleting Domain t1 or t2 or t3, expect error

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@sudo87 is it good to check any instances with delete protection enabled before proceeding with account deletion, and fail the deletion with relevant msg, eg. "_cannot delete account, there are some instances with delete protection enabled_"? the user/operator can disable the delete protection and retry the account deletion. Check if there is any provision to list delete protection enabled instances for the account.

**Comment by weizhouapache** [comment]
> @sudo87 is it good to check any instances with delete protection enabled before proceeding with account deletion, and fail the deletion with relevant msg, eg. "_cannot delete account, there are some instances with delete protection enabled_"? the user/operator can disable the delete protection and retry the account deletion. Check if there is any provision to list delete protection enabled instances for the account.

agree

**Comment by sudo87** [comment]
@sureshanaparti @weizhouapache

Does this mean that account deletion should not be allowed if any VM/instance has delete protection enabled? If so, we can add an early validation check and return with an error.

**Comment by sureshanaparti** [comment]
> @sureshanaparti @weizhouapache
> 
> Does this mean that account deletion should not be allowed if any VM/instance has delete protection enabled? If so, we can add an early validation check and return with an error.

yes @sudo87

**Comment by sudo87** [comment]
@blueorangutan package

**Comment by sudo87** [comment]
@sureshanaparti @weizhouapache  please review the changes done in the pr to skip account deletion and notify user in case there are vms with delete protection enabled.

Log message:
```
(logid:5b324d04) Cannot delete Account clouddev (id=5), delete protection enabled for Instances: [495d434f-6fc8-4e53-977e-98f2713cf5ed]
```
Notification:

File: server/src/main/java/com/cloud/user/AccountManagerImpl.java [hunk 1]
```diff
@@ -2138,6 +2139,24 @@ protected boolean isDeleteNeeded(AccountVO account, long accountId, Account call
...
+        long accountId = account.getId();
+        List<VMInstanceVO> deleteProtectedVms = _vmDao.listDeleteProtectedVmsByAccountId(accountId);
+        if (deleteProtectedVms.isEmpty()) {
+            return;
+        }
+
+        if (logger.isDebugEnabled()) {
+            List<String> vmUuids = deleteProtectedVms.stream().map(VMInstanceVO::getUuid).collect(Collectors.toList());
+            logger.debug("Cannot delete Account {} (id={}), delete protection enabled for Instances: {}",
+                    account.getAccountName(), accountId, vmUuids);
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/user/AccountManagerImpl.java]:
```suggestion
            logger.debug("Cannot delete Account {}, delete protection enabled for Instances: {}",
                    account, vmUuids);
```
This logs the value of `toString()` method which includes these details.
https://github.com/apache/cloudstack/blob/7eea9ed4488b1df0b9cd3f00c502fea182a09aff/engine/schema/src/main/java/com/cloud/user/AccountVO.java#L232-L234

**Comment by daviftorres** [comment]
Dear @sudo87,

Do you think the raw deletion of a domain below (no state check, no event publishing, no resource cleanup) is related to your effort or honoring the deletion protection of assets? 

https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/user/DomainManagerImpl.java#L345

**Comment by sudo87** [comment]
Hi @daviftorres, I am yet to start on preventing VM deletion if they are deletion protected during Domain cleanup. 

To answer you ques, its not raw domain deletion. There are checks performed before mentioned statement is executed.

https://github.com/apache/cloudstack/blob/4f93ba888c36d992c09af8d2486ea4ec75102f79/server/src/main/java/com/cloud/user/AccountManagerImpl.java#L2622-L2641

And event is published for domain removal:

[[publishRemoveEventsAndRemoveDomain](https://github.com/apache/cloudstack/blob/4f93ba888c36d992c09af8d2486ea4ec75102f79/server/src/main/java/com/cloud/user/DomainManagerImpl.java#L711-L714)](https://github.com/apache/cloudstack/blob/4f93ba888c36d992c09af8d2486ea4ec75102f79/server/src/main/java/com/cloud/user/DomainManagerImpl.java#L524-L533)

**Comment by daviftorres** [comment]
> Hi @daviftorres, I am yet to start on preventing VM deletion if they are deletion protected during Domain cleanup.
> 
> To answer you ques, its not raw domain deletion. There are checks performed before mentioned statement is executed.
> 
> https://github.com/apache/cloudstack/blob/4f93ba888c36d992c09af8d2486ea4ec75102f79/server/src/main/java/com/cloud/user/AccountManagerImpl.java#L2622-L2641
> 
> And event is published for domain removal:
> 
> [[publishRemoveEventsAndRemoveDomain](https://github.com/apache/cloudstack/blob/4f93ba888c36d992c09af8d2486ea4ec75102f79/server/src/main/java/com/cloud/user/DomainManagerImpl.java#L711-L714)](
> 
> https://github.com/apache/cloudstack/blob/4f93ba888c36d992c09af8d2486ea4ec75102f79/server/src/main/java/com/cloud/user/DomainManagerImpl.java#L524-L533
> 
> )

Thank you. Glad to hear that!

**Comment by sudo87** [comment]
@blueorangutan package

**Comment by sudo87** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/user/AccountManagerImpl.java [hunk 2]
```diff
@@ -2097,6 +2097,7 @@ public boolean deleteUserAccount(long accountId) {
             return true;
         }
 
+        validateNoDeleteProtectedVmsForAccount(account);
         checkIfAccountManagesProjects(accountId);
         verifyCallerPrivilegeForUserOrAccountOperations(account);
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/user/AccountManagerImpl.java]:
```suggestion
        checkIfAccountManagesProjects(accountId);
        verifyCallerPrivilegeForUserOrAccountOperations(account);
        validateNoDeleteProtectedVmsForAccount(account);
```

File: server/src/main/java/com/cloud/user/AccountManagerImpl.java [hunk 3]
```diff
@@ -2138,6 +2139,23 @@ protected boolean isDeleteNeeded(AccountVO account, long accountId, Account call
...
+    private void validateNoDeleteProtectedVmsForAccount(Account account) {
+        long accountId = account.getId();
+        List<VMInstanceVO> deleteProtectedVms = _vmDao.listDeleteProtectedVmsByAccountId(accountId);
+        if (deleteProtectedVms.isEmpty()) {
+            return;
+        }
+
+        if (logger.isDebugEnabled()) {
+            List<String> vmUuids = deleteProtectedVms.stream().map(VMInstanceVO::getUuid).collect(Collectors.toList());
+            logger.debug("Cannot delete Account {}, delete protection enabled for Instances: {}", account, vmUuids);
```
[the remark this answers is not in the document]
Comment (sudo87) [reply server/src/main/java/com/cloud/user/AccountManagerImpl.java:2151]: its handled in the Dao, limit of 10 vmUuids are enforced.

**Comment by sudo87** [comment]
@blueorangutan package

**Comment by sudo87** [comment]
@blueorangutan test

**Review by vishesh92 — APPROVED** [review]
clgtm. didn't test.

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested manually 

Create a VM

Edit the VM and enable “Delete Protection”


Disable the account → the VM is stopped, and Delete Protection remains enabled

Delete the account > Exception thrown

Tested by deleing domain > exception thrown

Image

Screenshot 2026-04-10 at 6 45 32 PM
