### PR TITLE
xen/xcpng: set vmr.VCPUsMax to minimum of global setting and host cpu cores

### LINKED ISSUE #7375: Can't create or scale VM to more then 2 vcpus. XCP-NG.
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0
~~~

##### OS / ENVIRONMENT

XCP-NG 8.2.1

Global parameter xen.vm.vcpu.max set to 64

Host has 2 sockets and 16 cores each. 

##### SUMMARY

Unable to start VM from different templates (Debian, Ubuntu) when vcpu more then 2. 
VM with attached iso started successfully with more then 2 vcpu.

Task failed! Task record:                 uuid: 8d2ad021-9c6d-daaa-899a-a55867cd49e7
           nameLabel: Async.VM.start_on
     nameDescription:
   allowedOperations: []
   currentOperations: {}
             created: Tue Mar 28 15:08:19 MSK 2023
            finished: Tue Mar 28 15:08:19 MSK 2023
              status: failure
          residentOn: com.xensource.xenapi.Host@a937b48e
            progress: 1.0
                type: <none/>
              result:
           errorInfo: [VALUE_NOT_SUPPORTED, VCPUs-at-startup, 8, value greater than VCPUs-max]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []

        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.checkForSuccess(CitrixResourceBase.java:508)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.startVM(CitrixResourceBase.java:5143)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixStartCommandWrapper.execute(CitrixStartCommandWrapper.java:111)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixStartCommandWrapper.execute(CitrixStartCommandWrapper.java:57)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.executeRequest(CitrixResourceBase.java:1782)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

GUI error: 

Unable to start a VM [e430f6d7-f13e-47b0-8f7c-d8fcc491e268] due to [Unable to create a deployment for VM instance {"id":148,"instanceName":"i-8-148-VM","type":"User","uuid":"e430f6d7-f13e-47b0-8f7c-d8fcc491e268"}].

##### STEPS TO REPRODUCE

~~~
Create VM with 3 or more CPUs
~~~

##### EXPECTED RESULTS

~~~
VM created successfully
~~~

##### ACTUAL RESULTS

~~~
VM has failed result
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
This fixes #7375

### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky xcpng-82

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xcpng-82

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xcpng82

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xenserver-71

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xcpng-82 keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 xcpng82 keepEnv

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java [hunk 1]
```diff
@@ -96,14 +95,7 @@ public VirtualMachineTO implement(VirtualMachineProfile vm) {
...
             if (host != null) {
-                List<HostVO> clusterHosts = hostDao.listByClusterAndHypervisorType(host.getClusterId(), host.getHypervisorType());
-                HostVO hostWithMinSocket = clusterHosts.stream().min(Comparator.comparing(HostVO::getCpuSockets)).orElse(null);
-                Integer vCpus = MaxNumberOfVCPUSPerVM.valueIn(host.getClusterId());
-                if (hostWithMinSocket != null && hostWithMinSocket.getCpuSockets() != null &&
-                        hostWithMinSocket.getCpuSockets() < vCpus) {
-                    vCpus = hostWithMinSocket.getCpuSockets();
-                }
-                to.setVcpuMaxLimit(vCpus);
+                to.setVcpuMaxLimit(MaxNumberOfVCPUSPerVM.valueIn(host.getClusterId()));
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java:98]: What I see this code do is if there is a host in the cluster with less VCPU than the setting for this cluster, this is the maximum a VM can have.
I see why this needs reverting, but it might also give issues in clusters where some hosts have less cores than others.

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java [hunk 2]
```diff
@@ -96,14 +95,7 @@ public VirtualMachineTO implement(VirtualMachineProfile vm) {
         if (userVmVO != null) {
             HostVO host = hostDao.findById(userVmVO.getHostId());
             if (host != null) {
-                List<HostVO> clusterHosts = hostDao.listByClusterAndHypervisorType(host.getClusterId(), host.getHypervisorType());
-                HostVO hostWithMinSocket = clusterHosts.stream().min(Comparator.comparing(HostVO::getCpuSockets)).orElse(null);
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java:100]: this is looking for sockets instead of vcpu, i.e. cores. might this be the problem?

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java [hunk 3]
```diff
@@ -96,14 +95,7 @@ public VirtualMachineTO implement(VirtualMachineProfile vm) {
...
-                Integer vCpus = MaxNumberOfVCPUSPerVM.valueIn(host.getClusterId());
-                if (hostWithMinSocket != null && hostWithMinSocket.getCpuSockets() != null &&
-                        hostWithMinSocket.getCpuSockets() < vCpus) {
-                    vCpus = hostWithMinSocket.getCpuSockets();
-                }
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java:105]: again sockets instead of cores

Comment (weizhouapache) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java:105]: @DaanHoogland 
you should add comment to #4672 , not this PR :-D

**Comment by weizhouapache** [comment]
@DaanHoogland @shwstppr 
this PR breaks the smoke tests on xcpng82, but xenserver-71 works fine.
I have no idea what caused it. 
I'd like to close this PR and suggest @shwstppr @DaanHoogland to have to look at the issue #7375 .

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> @DaanHoogland @shwstppr this PR breaks the smoke tests on xcpng82, but xenserver-71 works fine. I have no idea what caused it. I'd like to close this PR and suggest @shwstppr @DaanHoogland to have to look at the issue #7375 .

update: 
I tested rocky8/xcpng82 with PR7345 (health check PR), it looks the test failures also exist.
Therefore I reopened this issue, I will run another round of tests

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 xcpng82

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java (hunk 3 above)
Comment (DaanHoogland) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/XenServerGuru.java:105]: ah, I see

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 xcpng81

**Comment by weizhouapache** [comment]
@blueorangutan test centos7 xcpng81

**Review by harikrishna-patnala — COMMENTED** [review]
@weizhouapache if we revert these changes we may still hit another issue of setting higher value of vCPU max (if xen.vm.vcpu.max setting has higher value than the available vCPU in the cluster). Instead I would like to see the VM configured based what is available in the cluster.

The issue #7375 might be hitting because the hosts in the cluster might not have more than 2 vCPUs

**Comment by weizhouapache** [comment]
@harikrishna-patnala 
let's use cpuCores instead of cpuSockets, as @DaanHoogland suggested.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@harikrishna-patnala @DaanHoogland 
I thought about it again, I think we should not set the vcpu max limit to the minimum cpu cores of host in the cluster.
it might be possible that some hosts have enough capacity (cpu cores and cpu speed), but vms cannot be deployed.

**Comment by DaanHoogland** [comment]
> @harikrishna-patnala @DaanHoogland I thought about it again, I think we should not set the vcpu max limit to the minimum cpu cores of host in the cluster. it might be possible that some hosts have enough capacity (cpu cores and cpu speed), but vms cannot be deployed.

you are right @weizhouapache , we should actually set it to the maximum for any host in the cluster, if at all. I wonder if the setting is meant for operators to have some control over the kind of VMs that can be deployed...

**Comment by harikrishna-patnala** [comment]
Reposting my comment here again (which is on the issue #7375 ) regarding cpuCores or cpuSockets.

https://support.citrix.com/article/CTX236977/overcommitting-pcpus-on-individual-xenserver-vms this document says "Citrix recommends that you do not run a VM with more virtual CPUs (vCPUs) than the number physical CPUs (pCPUs) available on the XenServer host"
I think this is the reason we are setting based on host details.

Admin anyways have the control of setting vCPU max using the cluster/global level setting, so this should be fine, unless this won't break any existing tests.

**Comment by harikrishna-patnala** [comment]
> > @harikrishna-patnala @DaanHoogland I thought about it again, I think we should not set the vcpu max limit to the minimum cpu cores of host in the cluster. it might be possible that some hosts have enough capacity (cpu cores and cpu speed), but vms cannot be deployed.
> 
> you are right @weizhouapache , we should actually set it to the maximum for any host in the cluster, if at all. I wonder if the setting is meant for operators to have some control over the kind of VMs that can be deployed...

My opinion is we either use the setting or specific host cpu details (decided by the deployment planner). Using maximum of any host in the cluster may result in using higher value in host which has lower capacity in the cluster (host which is decided by the deployment planner)

**Comment by weizhouapache** [comment]
> > > @harikrishna-patnala @DaanHoogland I thought about it again, I think we should not set the vcpu max limit to the minimum cpu cores of host in the cluster. it might be possible that some hosts have enough capacity (cpu cores and cpu speed), but vms cannot be deployed.
> > 
> > 
> > you are right @weizhouapache , we should actually set it to the maximum for any host in the cluster, if at all. I wonder if the setting is meant for operators to have some control over the kind of VMs that can be deployed...
> 
> My opinion is we either use the setting or specific host cpu details (decided by the deployment planner). Using maximum of any host in the cluster may result in using higher value in host which has lower capacity in the cluster (host which is decided by the deployment planner)

@harikrishna-patnala 
good discussion.

Based on it, I updated the PR to set the vmr.VCPUsMax to minimum of global setting and cpu cores of specific hosts.

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java [hunk 4]
```diff
@@ -1338,7 +1338,12 @@ public VM createVmFromTemplate(final Connection conn, final VirtualMachineTO vmS
                 vmr.VCPUsMax = (long)vmSpec.getCpus();
             } else {
                 if (vmSpec.getVcpuMaxLimit() != null) {
-                    vmr.VCPUsMax = (long)vmSpec.getVcpuMaxLimit();
+                    long vcpuMaxLimit = (long) vmSpec.getVcpuMaxLimit();
+                    if (vcpuMaxLimit <= _host.getCpus()) {
+                        vmr.VCPUsMax = vcpuMaxLimit;
+                    } else {
+                        vmr.VCPUsMax = (long) _host.getCpus();
+                    }
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java:1346]:
```suggestion
                    vmr.VCPUsMax = Math.min(vcpuMaxLimit, _host.getCpus());
```

**Comment by weizhouapache** [comment]
@blueorangutan package

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java [hunk 5]
```diff
@@ -1338,7 +1338,7 @@ public VM createVmFromTemplate(final Connection conn, final VirtualMachineTO vmS
                 vmr.VCPUsMax = (long)vmSpec.getCpus();
             } else {
                 if (vmSpec.getVcpuMaxLimit() != null) {
-                    vmr.VCPUsMax = (long)vmSpec.getVcpuMaxLimit();
+                    vmr.VCPUsMax = Math.min(vcpuMaxLimit, _host.getCpus());
```
Comment (weizhouapache) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java:1341]:
```suggestion
                    vmr.VCPUsMax = Math.min(vmSpec.getVcpuMaxLimit(), _host.getCpus());
```

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java [hunk 6]
```diff
@@ -1338,7 +1338,7 @@ public VM createVmFromTemplate(final Connection conn, final VirtualMachineTO vmS
                 vmr.VCPUsMax = (long)vmSpec.getCpus();
             } else {
                 if (vmSpec.getVcpuMaxLimit() != null) {
-                    vmr.VCPUsMax = (long)vmSpec.getVcpuMaxLimit();
+                    vmr.VCPUsMax = Math.min(vmSpec.getVcpuMaxLimit(), _host.getCpus());
```
Comment (weizhouapache) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java:1341]:
```suggestion
                    vmr.VCPUsMax = Math.min(vmSpec.getVcpuMaxLimit(), (long) _host.getCpus());
```

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xenserver-71

**Comment by weizhouapache** [comment]
@DaanHoogland @harikrishna-patnala @shwstppr 
I have manually tested ok

- The env have 2 hosts (3 sockets, 1 cpu per socket)
```
MariaDB [cloud]> select cpus,cpu_sockets from host where type='Routing';
+------+-------------+
| cpus | cpu_sockets |
+------+-------------+
|    3 |           3 |
|    3 |           3 |
+------+-------------+
2 rows in set (0.00 sec)
```

- Updated db manually to simulate hosts with 1 socket and 3 cpus per socket.
```
MariaDB [cloud]> update host set cpu_sockets  = 1 where type='Routing';
Query OK, 2 rows affected (0.01 sec)
Rows matched: 2  Changed: 2  Warnings: 0

MariaDB [cloud]> 
MariaDB [cloud]> select cpus,cpu_sockets from host where type='Routing';
+------+-------------+
| cpus | cpu_sockets |
+------+-------------+
|    3 |           1 |
|    3 |           1 |
+------+-------------+
2 rows in set (0.00 sec)
```

- changed global/zone configuration to enable dynamic scale
enable.dynamic.scale.vm = true

- changed template to "Dynamically scalable"
image

- created a service offering with 2 cpus and 1GB memory

- create a vm with the new service offering and template

without this PR, it failed
```
com.cloud.utils.exception.CloudRuntimeException: Unable to start VM(i-2-21-VM) on host(4282a91e-dc93-4305-a21a-d87ce4fe7e87) due to Task failed! Task record:                 uuid: 5f732b21-7e74-cf31-2cf4-ddc4f48517bc
           nameLabel: Async.VM.start_on
     nameDescription:
   allowedOperations: []
   currentOperations: {}
             created: Mon Aug 28 10:39:13 UTC 2023
            finished: Mon Aug 28 10:39:13 UTC 2023
              status: failure
          residentOn: com.xensource.xenapi.Host@b83408c7
            progress: 1.0
                type: <none/>
              result:
           errorInfo: [VALUE_NOT_SUPPORTED, VCPUs-at-startup, 2, value greater than VCPUs-max]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []
```

with this PR, succeed to create a vm

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 xenserver-71

**Comment by DaanHoogland** [comment]
reproduced and validated :+1:
