### PR TITLE
xenserver: Add support for XS 7.3, 7.4 and XCP-ng 7.4

### LINKED ISSUE #2523: XCP-ng 7.4 support
# Support for XCP-ng 7.4 in Apache CloudStack 

The new community version of XenServer - XCP-ng 7.4 was released 31/March 2018: 
https://xcp-ng.github.io/news/2018/03/31/first-xcp-ng-release.html

As this will become an important addition to the CloudStack hypervisor ecosystem support for this will be a great feature. Since this version should be close to feature compatible with XenServer 7.4 the existing XenServer code can hopefully be utilised.

## Test results

Test environment:
- CloudStack 4.11 on CentOS 7.4
- Hypervisors running first release of XCP-ng version 7.4
- NFS storage

When tested in CloudStack 4.11 this was as suspected not recognised:

2018-04-03 11:34:29,334 INFO  [c.c.r.ResourceManagerImpl] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) Trying to add a new host at http://IPremoved in data center 1
2018-04-03 11:34:29,638 DEBUG [c.c.h.x.d.XcpServerDiscoverer] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) host IPremoved doesn't have 996dd2e7-ad95-49cc-a0be-2c9adc4dfb0b Hotfix
2018-04-03 11:34:29,648 DEBUG [c.c.h.x.d.XcpServerDiscoverer] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) host IPremoved doesn't have 0850b186-4d47-11e3-a720-001b2151a503 Hotfix
2018-04-03 11:34:29,659 WARN  [c.c.h.x.d.XcpServerDiscoverer] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) Only support XCP 1.0.0, 1.1.0, 1.4.x, 1.5 beta, 1.6.x; XenServer 5.6,  XenServer 5.6 FP1, XenServer 5.6 SP2, Xenserver 6.0, 6.0.2, 6.1.0, 6.2.0, >6.4.0 but this one is XCP-ng 7.4.0
2018-04-03 11:34:29,660 DEBUG [c.c.h.x.d.XcpServerDiscoverer] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) other exceptions: java.lang.RuntimeException: Only support XCP 1.0.0, 1.1.0, 1.4.x, 1.5 beta, 1.6.x; XenServer 5.6,  XenServer 5.6 FP1, XenServer 5.6 SP2, Xenserver 6.0, 6.0.2, 6.1.0, 6.2.0, >6.4.0 but this one is XCP-ng 7.4.0
java.lang.RuntimeException: Only support XCP 1.0.0, 1.1.0, 1.4.x, 1.5 beta, 1.6.x; XenServer 5.6,  XenServer 5.6 FP1, XenServer 5.6 SP2, Xenserver 6.0, 6.0.2, 6.1.0, 6.2.0, >6.4.0 but this one is XCP-ng 7.4.0
        at com.cloud.hypervisor.xenserver.discoverer.XcpServerDiscoverer.createServerResource(XcpServerDiscoverer.java:439)
        at com.cloud.hypervisor.xenserver.discoverer.XcpServerDiscoverer.createServerResource(XcpServerDiscoverer.java:454)
        at com.cloud.hypervisor.xenserver.discoverer.XcpServerDiscoverer.find(XcpServerDiscoverer.java:301)
        at com.cloud.resource.ResourceManagerImpl.discoverHostsFull(ResourceManagerImpl.java:756)
        at com.cloud.resource.ResourceManagerImpl.discoverHosts(ResourceManagerImpl.java:601)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy178.discoverHosts(Unknown Source)
        at org.apache.cloudstack.api.command.admin.host.AddHostCmd.execute(AddHostCmd.java:142)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:150)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:731)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:555)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:310)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:130)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:127)
        at com.cloud.api.ApiServlet.doGet(ApiServlet.java:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
2018-04-03 11:34:29,660 WARN  [c.c.r.ResourceManagerImpl] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) Unable to find the server resources at http://IPremoved
2018-04-03 11:34:29,661 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) Could not find exception: com.cloud.exception.DiscoveryException in error code list for exceptions
2018-04-03 11:34:29,661 WARN  [o.a.c.a.c.a.h.AddHostCmd] (qtp788117692-16:ctx-040da28f ctx-9347d25e ctx-ab04f31e) (logid:a961de98) Exception:
com.cloud.exception.DiscoveryException: Unable to add the host

### PR DESCRIPTION
**Pull request by yadvr**
This adds support for XenServer 7.3 and 7.4, and XCP-ng 7.4 version
as hypervisor hosts. Fixes #2523.

This also fixes the issue of 4.11 VRs stuck in starting for up-to 10mins, before they come up online. /cc @resmo @mike-tutkowski 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [x] All relevant new and existing integration tests have passed.
- [x] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

**Comment by borisstoyanov** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
/cc @DagSonstebo
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-65sp1

File: plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java [hunk 1]
```diff
@@ -2645,7 +2649,7 @@ private String actualIsoTemplate(final Connection conn) throws BadServerResponse
         final String[] items = xenVersion.split("\\.");
 
         // guest-tools.iso for XenServer version 7.0+
-        if (xenBrand.equals("XenServer") && Integer.parseInt(items[0]) >= 7) {
+        if ((xenBrand.equals("XenServer") || xenBrand.equals("XCP-ng")) && Integer.parseInt(items[0]) >= 7) {
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java]: just a comment; how about defining applicable targets as a set for readability.
Also, though it doesn't apply to this PR, parsing an it is not a very prozaic way of saying you need to be at version 7 or higher. that comment at 2651 should have been a method name instead of a comment

**Comment by DaanHoogland** [comment]
one concern though, the number of failures, even when they seem unrelated at first sight, is concerning. I'll give them a little look later today, please do as well @rhtyd @borisstoyanov ?

File: plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java (hunk 1 above)
Comment (rhtyd) [reply plugins/hypervisors/xenserver/src/com/cloud/hypervisor/xenserver/resource/CitrixResourceBase.java]: Not sure how to address this, I'll let it be for this PR.

**Comment by rhtyd** [comment]
@DaanHoogland I compared the failures in this PR against 4.11 smoketest health run: https://github.com/apache/cloudstack/pull/2376. The errors seems to env related, in case of (a) vm_life_cycle test failures, they are due to secure/non-secure test cases run on xenserver which only apply for KVM, they should be skipped for non-KVM hypervisors ( /cc @borisstoyanov - can you open a PR to ensure that we skip the secure/non-secure migration related tests cases for non-KVM hosts?).
(b) for ssvm and router related failures, I'm not sure why they are happening but they are unrelated to this PR as seen against the baseline PR tests, (c) cpu cap related offering failure is happening due to an issue with the test /cc @nvazquez , (d) vm_scale failure happened as that feature is not available in free versions on xenserver 7.4, 7.1.

Given about analysis, I don't see any real failures caused by this PR. I'll address some of the mentioned failures (a)-(d) in separate 4.11 stabilization PR, with that I'll merge this based on review and tests.

**Comment by DaanHoogland** [comment]
@rhtyd thankssss for the failure analysis. no issues there
