### PR TITLE
ui: fix for disk offering quickview details, actions

### LINKED ISSUE #2741: QuickView on DiskOfferings not showing actions
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### SUMMARY

When selecting the quick view on a disk offering the actions are not displayed and the user needs to click on the offering and operate through there. Please note that on service offerings this is working, so mush be something related to disk offerings

##### STEPS TO REPRODUCE

~~~
1. Go to disk offerings
2. On a disk offering select the quick view 
~~~

##### EXPECTED RESULTS

~~~
Quick actions should be displayed
~~~

##### ACTUAL RESULTS

~~~
The are not 
~~~
screen shot 2018-07-12 at 11 06 32

### PR DESCRIPTION
**Pull request by shwstppr**
## Description

Fixes #2741 

Quickview widget for disk offerings list in the UI was missing offering details and action items. `cloudStack.listDiskOfferings` method call for the details view data provider was not working, therefore, it has been replaced with direct ajax API call.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Existing UI behaviour:
Screenshot from 2019-06-10 14-37-30

After changes:
Screenshot from 2019-06-10 14-33-21

## How Has This Been Tested?
UI

### CODE REVIEW

**Comment by rhtyd** [comment]
@anuragaw can you test and review this?

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
This is a UI only change, manual testing/screenshot is only needed. Smoketests not necessary.

File: ui/scripts/configuration.js [hunk 1]
```diff
@@ -2403,16 +2403,19 @@
...
                                     };
-                                    var listDiskOfferingsOptions = {
-                                        isRecursive: true,
-                                        data: data
-                                    };
-                                    var diskOfferings = cloudStack.listDiskOfferings(listDiskOfferingsOptions);
-                                    args.response.success({
-                                        actionFilter: diskOfferingActionfilter,
-                                        data: diskOfferings[0]
+                                    $.ajax({
```
Comment (anuragaw) [inline ui/scripts/configuration.js]: async false?

Comment (anuragaw) [reply ui/scripts/configuration.js]: Also any value to fixing the cloudStack.listDiskOfferings method itself?

**Comment by shwstppr** [comment]
> Tested and veridied. Functionality looks good to me but I think we are ignoring the `cloudStack.listDiskOffering` function's broken nature here. Can you please look into it why it is not working? There are multiple users of the method and if we can reuse / fix the function it would be nice.
@anuragaw  cloudStack.listDiskOffering is not completely broken as such. It just wasn't for quickview, although works when offering details are opened. I'll look into it and will try to fix it for quickview.
