### PR TITLE
Dont add host back after agent service restart

### LINKED ISSUE #4218: Removed kvm host is added back to cloudstack when restart cloudstack-agent on it
When we remove a KVM host from cloudstack, and restart cloudstack-agent on it, the host is added back to cloudstack.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM agent
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

basic/advanced networking

##### OS / ENVIRONMENT

KVM

##### STEPS TO REPRODUCE

~~~
1. add a kvm host  to clodustack
2. put host to maintenance in cloudstack
3. remove host from cloudstack
4. restart cloudstack-agent on the host

~~~

##### EXPECTED RESULTS

~~~

5. host is not added back to cloudstack
~~~

##### ACTUAL RESULTS

~~~
5. host is added back to cloudstack
~~~

### PR DESCRIPTION
**Pull request by ravening**
## Description

Fixes #4218 

If a host is removed from cloudstack, it will be
added back if we restart the agent service on
the host. It should not be added back if manualy
removed.

Provide a global setting "add.host.on.service.restart" with
default value of true. If set to false, the zoneid,
clusterid and podid in agent.properties will be set to
null so that when service is restarted, the agent is not
added back

If true these values will not be set to null so that it
can be still added back on service restart

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
1. Add a host from ui. It will be successfully added
2. Now remove the host
3. Set the global setting `add.host.on.service.restart` to false
3. ssh to host and restart cloudstack-agent service
4. The host is not added back
5. Try to add host from ui again. It will be added

### CODE REVIEW

File: server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java [hunk 1]
```diff
@@ -348,11 +362,19 @@ private void setupAgentSecurity(final Connection sshConnection, final String age
             _hostDao.saveDetails(connectedHost);
             return resources;
         } catch (DiscoveredWithErrorException e) {
+            s_logger.error("Exception: "+ e.getMessage());
```
[the remark this answers is not in the document]
Comment (ravening) [reply server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:365]: I have no idea why it's there in first place. So I'm displaying message whatever we catch

File: server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java [hunk 2]
```diff
@@ -348,11 +362,19 @@ private void setupAgentSecurity(final Connection sshConnection, final String age
...
             throw e;
         } catch (Exception e) {
             String msg = " can't setup agent, due to " + e.toString() + " - " + e.getMessage();
             s_logger.warn(msg);
         } finally {
+            // set guid to null once host is added
```
[the remark this answers is not in the document]
Comment (ravening) [reply server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:371]: Initialguid will always beer null since I'm fetching the value for a removed host. For non removed hosts it will be non null

[the remark this answers is not in the document]
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:371]: exactly. it is not necessarily null. I think you'd better remove this comment, it is confusing.

File: server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:365]: ok, than let's at least make the text describing our course of action:
```suggestion
            s_logger.error("DiscoveredWithErrorException caught and rethrowing, message; " + e.getMessage());
```

**Comment by rhtyd** [comment]
@ravening this will break the host-add feature for a lot of users who use the functionality to add a KVM host out-of-band without using the addHost API.

Instead a middle-ground fix could be to remove a host's certificates when a KVM host is removed (all the /etc/cloudstack/agent/cloud.* files) which will stop KVM agent connections to be accepted by the management server for most deployments (i.e. CA plugin and auth strictness enabled).

File: server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (ravening) [reply server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:371]: @DaanHoogland this code is executed only for the newly added hosts. When the host is removed previously, the guid is set to null. So the initial value of `guid` will always be `null` in this case.
Before adding the host, I set the guid to a temporary value and at the end I set it back to null which is the original value.
I hope to have cleared your confusion

**Comment by ravening** [comment]
> @ravening this will break the host-add feature for a lot of users who use the functionality to add a KVM host out-of-band without using the addHost API.
> 
> Instead a middle-ground fix could be to remove a host's certificates when a KVM host is removed (all the /etc/cloudstack/agent/cloud.* files) which will stop KVM agent connections to be accepted by the management server for most deployments (i.e. CA plugin and auth strictness enabled).

@rhtyd this will work only if CA plugin and auth strictness is enabled but what if we have not configured both in some setup. In that case, the host will still be added

**Comment by rhtyd** [comment]
Well @ravening fixing it otherwise would break some people's way of deploying/adding KVM host. Perhaps there's an easy way to reset the host (domain/IP) and zone/pod/cluster settings in the agent.properties (i.e. reset or remove them) when a host is removed?

**Comment by ravening** [comment]
> Well @ravening fixing it otherwise would break some people's way of deploying/adding KVM host. Perhaps there's an easy way to reset the host (domain/IP) and zone/pod/cluster settings in the agent.properties (i.e. reset or remove them) when a host is removed?

I'm thinking of setting guid to null in agent.properties when host is removed and in connection handler we search for a host based on guid whenever we get a new connection request. Any other suggestions @rhtyd

**Comment by rhtyd** [comment]
@ravening I think resetting the host, zone, cluster, etc to default (or remove) should be enough. Post agent restart the agent will not know where to connect.

**Comment by DaanHoogland** [comment]
@ravening @rhtyd how about hiding this behaviour behind a global setting `auto-add-hosts`? (default would have to be true for backwards compatibility)

**Comment by ravening** [comment]
> @ravening @rhtyd how about hiding this behaviour behind a global setting `auto-add-hosts`? (default would have to be true for backwards compatibility)

Lets say, I add a global setting `add.host.on.service.restart` with default value of true
When we delete the host, if the value is false then we set zone/cluster/pod value to null else retain as it is

Since default value is true, we dont change any value and host will be added back if service is restarted

**Comment by ravening** [comment]
@rhtyd @DaanHoogland please review again

File: server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java [hunk 3]
```diff
@@ -474,7 +477,8 @@ public DeleteHostAnswer deleteHost(HostVO host, boolean isForced, boolean isForc
 
         _resourceMgr.deleteRoutingHost(host, isForced, isForceDeleteStorage);
         try {
-            ShutdownCommand cmd = new ShutdownCommand(ShutdownCommand.DeleteHost, null);
+            ShutdownCommand cmd = AddHostOnServiceRestart.value() ? new ShutdownCommand(ShutdownCommand.DeleteHost, null, false) :
+                    new ShutdownCommand(ShutdownCommand.DeleteHost, "Cleaning up zone/pod/cluster details for host", true);
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:481]: general jist looks good, i'd rather have the tristate operator in the parameter passing then the whole contructor invocation ? note the ?)
```suggestion
            ShutdownCommand cmd = new ShutdownCommand(ShutdownCommand.DeleteHost, null, AddHostOnServiceRestart.value() ? false : true);
```

**Comment by DaanHoogland** [comment]
@wido @GabrielBrascher I think this will impact you guys most. Can you review?

**Comment by wido** [comment]
I have never run into this situation to be honest. But the change seems sane to me.

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java [hunk 4]
```diff
@@ -410,6 +410,10 @@
     public final static ConfigKey<Long> IOPS_MAX_WRITE_LENGTH = new ConfigKey<Long>(Long.class, "vm.disk.iops.maximum.write.length", "Advanced", "0",
             "Maximum IOPS write burst duration (seconds). If '0' (zero) then does not check for maximum burst length.", true, ConfigKey.Scope.Global, null);
 
+    public static final ConfigKey<Boolean> AddHostOnServiceRestart = new ConfigKey<Boolean>(Boolean.class, "add.host.on.service.restart", "Advanced", "true",
```
Comment (GabrielBrascher) [inline server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:413]: Considering that this is defined as a `static final`, I would recommend keeping the code convention such as described on [Oracle Java Naming Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html).

In this case `AddHostOnServiceRestart` should be changed to something as `ADD_HOST_ON_SERVICE_RESTART`.

File: agent/src/main/java/com/cloud/agent/Agent.java [hunk 5]
```diff
@@ -419,6 +419,15 @@ protected void cancelTasks() {
         }
     }
 
+    protected void cleanupAgentZoneProperties() {
+        // Unset zone, cluster and pod values so that host is not added back
+        // when service is restarted. This will be set to proper values
+        // when host is added back
```
Comment (GabrielBrascher) [inline agent/src/main/java/com/cloud/agent/Agent.java:425]: These commented lines could be a nice Javadoc for the method; what do you think of moving them to a Javadoc block?

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java (hunk 4 above)
Comment (ravening) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java]: @GabrielBrascher I made the necessary changes. Please review again

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java [hunk 6]
```diff
@@ -410,6 +410,10 @@
     public final static ConfigKey<Long> IOPS_MAX_WRITE_LENGTH = new ConfigKey<Long>(Long.class, "vm.disk.iops.maximum.write.length", "Advanced", "0",
             "Maximum IOPS write burst duration (seconds). If '0' (zero) then does not check for maximum burst length.", true, ConfigKey.Scope.Global, null);
 
+    public static final ConfigKey<Boolean> ADD_HOST_ON_SERVICE_RESTART = new ConfigKey<Boolean>(Boolean.class, "add.host.on.service.restart", "Advanced", "true",
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:413]: If this is KVM specific can we add kvm in the global setting name @ravening ?

Comment (ravening) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:413]: @rhtyd i don't think this is KVM specific. The code path is same for all HV's I guess. Didn't test it on other Hv types.

Comment (rhtyd) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:413]: The agent only runs on KVM host, for the other two major hypervisors (VMware and XenServer) we don't run an agent on them.

Comment (ravening) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:413]: Didnt know that :P will add KVM in the name

Comment (ravening) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java]: @rhtyd made the change

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@GabrielBrascher @wido @rhtyd are we 🆗 with this?

**Review by rhtyd — APPROVED** [review]
LGTM, I've not manually tested this

**Comment by rhtyd** [comment]
@ravening @weizhouapache can you share your manual test results if any?

**Comment by ravening** [comment]
@rhtyd Sure... I will share the results by tomorrow

**Comment by rhtyd** [comment]
ping @ravening any update? thanks.

**Comment by ravening** [comment]
> ping @ravening any update? thanks.

@rhtyd apart from logs what else can I share? Manual testing involves

Add a host to cloudstack
Put it in maintenance mode
Remove it
Restart agent service on it
The host should not be added back

**Review by DaanHoogland — APPROVED** [review]
