### PR TITLE
UI: Option to choose the isolation method when creating the public IP range

### LINKED ISSUE #9920: VXLAN isolation method does not pass the correct broadcast domain type when creating the vlan public IP range
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Zone Creation, Physical network
~~~

##### CLOUDSTACK VERSION

~~~
Probably all versions - observed on 4.19.1.2 and 4.20
~~~

##### SUMMARY

During zone creation, if the isolation method for public traffic is selected as VXLAN, when adding the public IP range and VNI, the broadcast domain type gets passed as VLAN and not VXLAN. Same holds true when creating vlan public IP range (after zone creation) unless 'vxlan://' is explicitly passed in the vni field.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR enabled option in the UI to choose the isolation method (vlan, vxlan) when creating the public IP range.

Fixes #9920

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Verified the isolation methods set in public IP range, from the UI.

UI-IsolationMethod-PublicIpRange01

UI-IsolationMethod-PublicIpRange02

IPv4:

IsolationMethodIPv4

IPv6:

IsolationMethodIPv6

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@sureshanaparti 
does it work for ipv6 too ?
can we use 'vlan' as default isolated method ?

**Comment by sureshanaparti** [comment]
> @sureshanaparti does it work for ipv6 too ? can we use 'vlan' as default isolated method ?

will check/udpate for ipv6 as well. correct - 'vlan' is used as default isolated method if not set.

File: ui/src/views/infra/network/IpRangesTabPublic.vue [hunk 1]
```diff
@@ -220,6 +220,20 @@
...
+          <a-select
+            v-model:value="form.isolationmethod"
+            showSearch
+            optionFilterProp="label"
+            :filterOption="(input, option) => {
+              return option.label.toLowerCase().indexOf(input.toLowerCase()) >= 0
+            }" >
+            <a-select-option value="">{{ }}</a-select-option>
+            <a-select-option value="vlan"> vlan </a-select-option>
+            <a-select-option value="vxlan"> vxlan </a-select-option>
```
[the remark this answers is not in the document]
Comment (sureshanaparti) [reply ui/src/views/infra/network/IpRangesTabPublic.vue]: fixed

File: ui/src/views/infra/network/IpRangesTabPublic.vue [hunk 2]
```diff
@@ -220,6 +220,20 @@
...
+        <a-form-item name="isolationmethod" ref="isolationmethod" class="form__item" v-if="!basicGuestNetwork">
+          <tooltip-label :title="$t('label.isolation.method')" :tooltip="$t('label.choose.isolation.method.public.ip.range')" class="tooltip-label-wrapper"/>
+          <a-select
+            v-model:value="form.isolationmethod"
+            showSearch
+            optionFilterProp="label"
+            :filterOption="(input, option) => {
+              return option.label.toLowerCase().indexOf(input.toLowerCase()) >= 0
+            }" >
+            <a-select-option value="">{{ }}</a-select-option>
```
[the remark this answers is not in the document]
Comment (sureshanaparti) [reply ui/src/views/infra/network/IpRangesTabPublic.vue:232]: defaults to empty, no changes.

**Comment by sureshanaparti** [comment]
> > @sureshanaparti does it work for ipv6 too ? can we use 'vlan' as default isolated method ?
> 
> will check/udpate for ipv6 as well. correct - 'vlan' is used as default isolated method if not set.

@weizhouapache  it works with ipv6 as well.

**Comment by sureshanaparti** [comment]
@blueorangutan ui

File: api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java [hunk 3]
```diff
@@ -34,6 +34,7 @@
 import com.cloud.exception.ResourceAllocationException;
 import com.cloud.exception.ResourceUnavailableException;
 import com.cloud.user.Account;
+import org.apache.commons.lang3.StringUtils;
```
Comment (DaanHoogland) [inline api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java]:
```suggestion
import com.cloud.utils.StringUtils;
```

File: api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/CreateVlanIpRangeCmd.java [hunk 4]
```diff
@@ -38,6 +38,7 @@
 import com.cloud.exception.ResourceAllocationException;
 import com.cloud.exception.ResourceUnavailableException;
 import com.cloud.user.Account;
+import org.apache.commons.lang3.StringUtils;
```
Comment (DaanHoogland) [inline api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/CreateVlanIpRangeCmd.java]:
```suggestion
import com.cloud.utils.StringUtils;
```

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java [hunk 5]
```diff
@@ -3917,7 +3917,6 @@ public List<Class<?>> getCommands() {
         cmdList.add(StartInternalLBVMCmd.class);
         cmdList.add(ListInternalLBVMsCmd.class);
         cmdList.add(ListNetworkIsolationMethodsCmd.class);
-        cmdList.add(ListNetworkIsolationMethodsCmd.class);
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/server/ManagementServerImpl.java:3920]: should this be deleted?

**Review by DaanHoogland — CHANGES_REQUESTED** [review]

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java (hunk 5 above)
Comment (sureshanaparti) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:3920]: yes, it's duplicate

File: api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/CreateVlanIpRangeCmd.java (hunk 4 above)
Comment (sureshanaparti) [reply api/src/main/java/org/apache/cloudstack/api/command/admin/vlan/CreateVlanIpRangeCmd.java]: updated

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java (hunk 3 above)
Comment (sureshanaparti) [reply api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateManagementNetworkIpRangeCmd.java]: updated

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by RosiKyu** [comment]
@blueorangutan package

**Comment by RosiKyu** [comment]
@blueorangutan package

**Review by RosiKyu — APPROVED** [review]
LGTM

Verification passed. Working as expected with fix from PR. 

**VLAN/VXLAN options on IPV4**

Screenshot from 2025-12-13 10-33-57
Screenshot from 2025-12-13 10-32-32
Screenshot from 2025-12-13 10-31-36

**VLAN/VXLAN options on IPV6**

image

image

image
