### PR TITLE
kvm: add ssvm storage nic null uri check during plug

### LINKED ISSUE #11552: Agent 4.21.0.0 secondarystoragevm
### problem

If you upgrade the Ubuntu KVM cloustack-agent to 4.21.0.0 it longer power of or redeployes.

`2025-09-01 15:42:44,488 INFO  [kvm.resource.LibvirtConnection] (AgentRequest-Handler-4:[]) (logid:b0554662) No existing libvirtd connection found. Opening a new one
2025-09-01 15:42:44,490 WARN  [kvm.resource.LibvirtConnection] (AgentRequest-Handler-4:[]) (logid:b0554662) Can not find a connection for Instance s-14814-VM. Assuming the default connection.
2025-09-01 15:42:44,607 WARN  [kvm.resource.LibvirtKvmAgentHook] (AgentRequest-Handler-4:[]) (logid:b0554662) Groovy script '/etc/cloudstack/agent/hooks/libvirt-vm-state-change.groovy' is not available. Transformations will not be applied.
2025-09-01 15:42:44,607 WARN  [kvm.resource.LibvirtKvmAgentHook] (AgentRequest-Handler-4:[]) (logid:b0554662) Shell script '/etc/cloudstack/agent/hooks/libvirt-vm-state-change.sh' is not available. Transformations will not be applied.
2025-09-01 15:42:44,607 WARN  [kvm.resource.LibvirtKvmAgentHook] (AgentRequest-Handler-4:[]) (logid:b0554662) Groovy scripting engine is not initialized. Data transformation skipped.
2025-09-01 15:43:11,433 WARN  [kvm.resource.LibvirtComputingResource] (AgentRequest-Handler-2:[]) (logid:b0554662) Setting System VM's [VM {id: "14814", name: "s-14814-VM", uuid: "6f242aaa-bb01-408b-9991-5818c70ab7f7", type: "SecondaryStorageVm"}] current memory as max memory [524288].
2025-09-01 15:43:11,435 INFO  [kvm.storage.LibvirtStorageAdaptor] (AgentRequest-Handler-2:[]) (logid:b0554662) Trying to fetch storage pool 11838e6d-4476-32dd-9c19-f884dedd79b4 from libvirt
2025-09-01 15:43:11,473 INFO  [kvm.storage.LibvirtStorageAdaptor] (AgentRequest-Handler-2:[]) (logid:b0554662) Trying to fetch storage pool 11838e6d-4476-32dd-9c19-f884dedd79b4 from libvirt
2025-09-01 15:43:11,528 INFO  [kvm.storage.LibvirtStorageAdaptor] (AgentRequest-Handler-2:[]) (logid:b0554662) Trying to fetch storage pool 11838e6d-4476-32dd-9c19-f884dedd79b4 from libvirt
2025-09-01 15:43:11,538 WARN  [cloud.agent.Agent] (AgentRequest-Handler-2:[]) (logid:b0554662) Caught: java.lang.NullPointerException: Cannot invoke "java.net.URI.getScheme()" because "uri" is null
        at com.cloud.network.Networks$BroadcastDomainType.getSchemeValue(Networks.java:180)
        at com.cloud.network.Networks$BroadcastDomainType.getValue(Networks.java:234)
        at com.cloud.hypervisor.kvm.resource.BridgeVifDriver.plug(BridgeVifDriver.java:258)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.createVif(LibvirtComputingResource.java:3816)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.createVifs(LibvirtComputingResource.java:3395)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStartCommandWrapper.execute(LibvirtStartCommandWrapper.java:86)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStartCommandWrapper.execute(LibvirtStartCommandWrapper.java:52)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:2240)
        at com.cloud.agent.Agent.processRequest(Agent.java:813)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1295)
        at com.cloud.utils.nio.Task.call(Task.java:83)
        at com.cloud.utils.nio.Task.call(Task.java:29)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
`

### versions

Cloudstack Management on 4.21.0.0
Ubuntu 24.04 on both Management and Host
Advanced networking selected without security groups
Secondary storage using NFS

### The steps to reproduce the bug

1. Upgrade cloudstack-agent to  4.21.0.0 stop secondarystoragevm then start again
2. Also breaks on redeploy
To fix the issue roll cloudstack-agent back to 4.20.0.1

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #11552

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java [hunk 1]
```diff
@@ -250,7 +250,7 @@ public LibvirtVMDef.InterfaceDef plug(NicTO nic, String guestOsType, String nicA
             intf.defBridgeNet(_bridges.get("private"), null, nic.getMac(), getGuestNicModel(guestOsType, nicAdapter));
         } else if (nic.getType() == Networks.TrafficType.Storage) {
             String storageBrName = nic.getName() == null ? _bridges.get("private") : nic.getName();
-            if (nic.getBroadcastType() == Networks.BroadcastDomainType.Storage) {
+            if (Networks.BroadcastDomainType.Storage.equals(nic.getBroadcastType()) && nic.getBroadcastUri() != null) {
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/BridgeVifDriver.java:253]: `Networks.BroadcastDomainType.Storage.equals(nic.getBroadcastType()` already implies `nic.getBroadcastUri() != null`.

**Comment by weizhouapache** [comment]
@shwstppr 
I modified the target branch to 4.20

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
Refactored and added tests

@blueorangutan package

**Comment by shwstppr** [comment]
The [change](https://github.com/apache/cloudstack/pull/11245) that is causing issue #11552 went into 4.19, @weizhouapache are you okay if I rebase this to 4.19 or is that not needed considering 4.19 is EOL?

**Comment by weizhouapache** [comment]
> The [change](https://github.com/apache/cloudstack/pull/11245) that is causing issue #11552 went into 4.19, @weizhouapache are you okay if I rebase this to 4.19 or is that not needed considering 4.19 is EOL?

@shwstppr 
I think 4.20 is good for this PR

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
tested by
https://lists.apache.org/thread/8gd4179nq43lzd05h6gf6g23fq3k5yxo

**Comment by daviftorres** [comment]
Hey @weizhouapache , I see that this PR is in the milestone of 4.20.2 but it fixed a bug reported on 4.21.0. It is not intuitive for me. Could you please clarify how this development process works?

**Comment by weizhouapache** [comment]
> Hey @weizhouapache , I see that this PR is in the milestone of 4.20.2 but it fixed a bug reported on 4.21.0. It is not intuitive for me. Could you please clarify how this development process works?

@daviftorres 
all 4.20 commits will be merged into 4.21

**Comment by weizhouapache** [comment]
For those who face the issue after upgrading to 4.21.0.0
- backup /usr/share/cloudstack-agent/lib/cloud-plugin-hypervisor-kvm-4.21.0.0.jar
- download file
[cloud-plugin-hypervisor-kvm-4.21.0.0.zip](https://github.com/user-attachments/files/22293537/cloud-plugin-hypervisor-kvm-4.21.0.0.zip)
- move to  /usr/share/cloudstack-agent/lib/cloud-plugin-hypervisor-kvm-4.21.0.0.jar
- systemctl restart cloudstack-agent

**Comment by daviftorres** [comment]
It works like a charm! Good job!!

image
