### PR TITLE
server: fix snapshot physical size

### LINKED ISSUE #9660: Snapshot defaulting to Physical Size 0
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Snapshot to secondary storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### OS / ENVIRONMENT

KVM, NFS secondary storage

##### SUMMARY

Upgrading from Cloudstack 4.18 to 4.19.1, I see reports in the UI that all snapshots have a 0 Physical Size even when there is a physical size in the database. 
```
select * from snapshot_store_ref where snapshot_id=91517\g
+--------+----------+-------------+---------------------+--------------+--------+------------+-------------+---------------+--------------------+--------------------------------------------------------------------------------------+-------+--------------+---------+---------------------+-----------+----------------+--------------+-----------+---------+------------+
| id     | store_id | snapshot_id | created             | last_updated | job_id | store_role | size        | physical_size | parent_snapshot_id | install_path                                                                         | state | update_count | ref_cnt | updated             | volume_id | download_state | download_pct | error_str | display | local_path |
+--------+----------+-------------+---------------------+--------------+--------+------------+-------------+---------------+--------------------+--------------------------------------------------------------------------------------+-------+--------------+---------+---------------------+-----------+----------------+--------------+-----------+---------+------------+
| 129502 |       69 |       91517 | 2024-09-09 09:00:09 | NULL         | NULL   | Primary    | 85899345920 |   85899345920 |                  0 | cloudstack/1721884e-c618-413b-9f31-4eba9a4acc50/582372a9-a122-4121-b25b-f6ea2d875e38 | Ready |            2 |       0 | 2024-09-09 09:00:10 |     25832 | NULL           |            0 | NULL      |       1 | NULL       |
| 129505 |        1 |       91517 | 2024-09-09 09:00:10 | NULL         | NULL   | Image      | 85899345920 |   56633131008 |                  0 | snapshots/13511/25832/582372a9-a122-4121-b25b-f6ea2d875e38                           | Ready |            2 |       0 | 2024-09-09 09:04:45 |     25832 | NULL           |            0 | NULL      |       1 | NULL       |
+--------+----------+-------------+---------------------+--------------+--------+------------+-------------+---------------+--------------------+--------------------------------------------------------------------------------------+-------+--------------+---------+---------------------+-----------+----------------+--------------+-----------+---------+------------+
2 rows in set (0.000 sec)
```
I am using Ceph and local storage with snapshot.backup.to.secondary enabled. I can give more information if needed. 

##### STEPS TO REPRODUCE

~~~
Snapshot using local storage with snapshot.backup.to.secondary enabled
~~~

##### EXPECTED RESULTS

~~~
Seeing the physical size in the UI as reflected in the database
~~~

##### ACTUAL RESULTS

~~~
"physicalsize": 0,
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9660

Retrieving results from snapshot_view when only a single id passed was always returning Primary role entry (seen in the 3rd query below. To overcome this all entries for the single ID are fetched and sorted in the JAVA code.

```
mysql> SELECT id, store_role FROM snapshot_view ORDER BY snapshot_view.snapshot_store_pair ASC;
+----+------------+
| id | store_role |
+----+------------+
|  1 | Image      |
|  1 | Primary    |
|  2 | Image      |
|  2 | Primary    |
+----+------------+
4 rows in set (0.01 sec)

mysql> SELECT id,store_role FROM snapshot_view WHERE snapshot_view.id IN (1,2) GROUP BY snapshot_view.id ORDER BY snapshot_view.snapshot_store_pair ASC;
+----+------------+
| id | store_role |
+----+------------+
|  1 | Image      |
|  2 | Image      |
+----+------------+
2 rows in set (0.00 sec)

mysql> SELECT id,store_role FROM snapshot_view WHERE snapshot_view.id IN (1) GROUP BY snapshot_view.id ORDER BY snapshot_view.snapshot_store_pair ASC;
+----+------------+
| id | store_role |
+----+------------+
|  1 | Primary    |
+----+------------+
1 row in set (0.00 sec)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 1]
```diff
@@ -5626,17 +5626,15 @@ private Pair<List<SnapshotJoinVO>, Integer> searchForSnapshotsWithParams(final L
 
         Integer count = snapshotDataPair.second();
         if (count == 0) {
-            // empty result
             return snapshotDataPair;
         }
         List<SnapshotJoinVO> snapshotData = snapshotDataPair.first();
         List<SnapshotJoinVO> snapshots;
-        if (isShowUnique) {
+        if (isShowUnique) {c69ad926e2
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:5633]: c&p error?

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
Thanks @shwstppr LGTM - manually tested OK:

Listed snapshots without ID, with specific IDs and verified physical size is displayed on the API and the UI as well:

````
(localcloud) 🐱 > list snapshots listall=true filter=physicalsize,virtualsize,state
{
  "count": 2,
  "snapshot": [
    {
      "physicalsize": 1510539264,
      "state": "BackedUp",
      "virtualsize": 8589934592
    },
    {
      "physicalsize": 1510539264,
      "state": "BackedUp",
      "virtualsize": 8589934592
    }
  ]
}
(localcloud) 🐱 > list snapshots listall=true filter=physicalsize,virtualsize,state id=35cb5416-a5d6-4875-9298-d8e39b15ce77 
{
  "count": 1,
  "snapshot": [
    {
      "physicalsize": 1510539264,
      "state": "BackedUp",
      "virtualsize": 8589934592
    }
  ]
}
(localcloud) 🐱 > list snapshots listall=true filter=physicalsize,virtualsize,state id=60de4d7a-548a-44f1-a957-2f8f77f0999f 
{
  "count": 1,
  "snapshot": [
    {
      "physicalsize": 1510539264,
      "state": "BackedUp",
      "virtualsize": 8589934592
    }
  ]
}
````

Screenshot 2025-01-22 at 23 34 48

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

File: server/src/main/java/com/cloud/api/query/dao/SnapshotJoinDaoImpl.java [hunk 2]
```diff
@@ -246,14 +241,33 @@ public List<SnapshotJoinVO> searchBySnapshotStorePair(String... pairs) {
         return uvList;
     }
 
+    private List<SnapshotJoinVO> findById(Long zoneId, long id) {
+        SearchBuilder<SnapshotJoinVO> sb = createSearchBuilder();
+        sb.and("id", sb.entity().getId(), SearchCriteria.Op.EQ);
+        sb.and("zone_id", sb.entity().getDataCenterId(), SearchCriteria.Op.EQ);
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/api/query/dao/SnapshotJoinDaoImpl.java:247]:
```suggestion
        sb.and("zoneId", sb.entity().getDataCenterId(), SearchCriteria.Op.EQ);
````

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test keepEnv
