### PR TITLE
engine: add support for VMware 7.0 dependency and hypervisor capability

### LINKED ISSUE #4423: Adding a cluster
Hello,

I am trying to add a cluster into my apache cloudstack 4.14
I have v center vSphere Client version 7.0.1.00000

When adding i have following error:

This cluster null belongs to vCenter https. But this zone is associated with VMware DC from vCenter vcenter.cloud.xxx.com Make sure the cluster being added belongs to vCenter vcenter.cloud.xxx.com and VMware DC XXX XXX

### LINKED ISSUE #4441: cpvm not support VMware 7.0 console
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
CPVM
~~~

##### CLOUDSTACK VERSION
~~~
14.1
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This adds support for VMware 7.0 with a jar dependency and sql upgrade path. The jar dependency has been added to support noredist pkging here:
https://github.com/rhtyd/cloudstack-nonoss/blob/master/install-non-oss.sh#L37

Fixes #4441
Fixes #4423

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
Kicked tests against vCenter 7 based env.

**Comment by rhtyd** [comment]
Marvin tests with this PR and vCenter 7.0 with CentOS7 mgmt server but two 6.7u3 ESXi hosts:

Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_deploy_kubernetes_cluster | `Error` | 0.15 | test_kubernetes_clusters.py
test_02_deploy_kubernetes_ha_cluster | `Error` | 0.07 | test_kubernetes_clusters.py
test_04_deploy_and_upgrade_kubernetes_cluster | `Error` | 0.06 | test_kubernetes_clusters.py
test_05_deploy_and_upgrade_kubernetes_ha_cluster | `Error` | 0.07 | test_kubernetes_clusters.py
test_06_deploy_and_invalid_upgrade_kubernetes_cluster | `Error` | 0.06 | test_kubernetes_clusters.py
test_07_deploy_and_scale_kubernetes_cluster | `Error` | 0.06 | test_kubernetes_clusters.py
test_01_add_primary_storage_disabled_host | `Error` | 0.51 | test_primary_storage.py
test_01_primary_storage_nfs | `Error` | 0.18 | test_primary_storage.py
ContextSuite context=TestStorageTags>:setup | `Error` | 0.31 | test_primary_storage.py
test_02_list_snapshots_with_removed_data_store | `Error` | 1.21 | test_snapshots.py
test_02_create_template_with_checksum_sha1 | `Error` | 5.28 | test_templates.py
test_03_create_template_with_checksum_sha256 | `Error` | 5.20 | test_templates.py
test_04_create_template_with_checksum_md5 | `Error` | 5.20 | test_templates.py
test_01_volume_usage | `Error` | 11.57 | test_usage.py
test_11_migrate_vm | `Error` | 50.32 | test_vm_life_cycle.py
test_01_create_volume | `Error` | 134.77 | test_volumes.py
test_02_attach_volume | `Error` | 44.96 | test_volumes.py
test_03_download_attached_volume | `Error` | 1.10 | test_volumes.py
test_04_delete_attached_volume | `Error` | 1.11 | test_volumes.py
test_05_detach_volume | `Error` | 1.10 | test_volumes.py
test_06_download_detached_volume | `Error` | 1.11 | test_volumes.py
test_07_resize_fail | `Error` | 2.28 | test_volumes.py
test_08_resize_volume | `Error` | 1.11 | test_volumes.py
test_09_delete_detached_volume | `Error` | 12.63 | test_volumes.py
test_11_attach_volume_with_unstarted_vm | `Error` | 2.39 | test_volumes.py
ContextSuite context=TestVolumes>:teardown | `Error` | 19.09 | test_volumes.py
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 443.14 | test_vpc_redundant.py
test_04_rvpc_network_garbage_collector_nics | `Error` | 3790.27 | test_vpc_redundant.py
test_04_rvpc_network_garbage_collector_nics | `Error` | 3790.31 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 0.01 | test_vpc_redundant.py
ContextSuite context=TestVPCRedundancy>:teardown | `Error` | 0.02 | test_vpc_redundant.py

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by nvazquez** [comment]
Rebased master - @blueorangutan package

File: engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql [hunk 1]
```diff
@@ -19,6 +19,10 @@
 -- Schema upgrade from 4.14.0.0 to 4.15.0.0
 --;
 
+-- Add support for VMware 7.0
+INSERT IGNORE INTO `cloud`.`hypervisor_capabilities` (uuid, hypervisor_type, hypervisor_version, max_guests_limit, security_group_enabled, max_data_volumes_limit, max_hosts_per_cluster, storage_motion_supported, vm_snapshot_enabled) values (UUID(), 'VMware', '7.0', 1024, 0, 59, 64, 1, 1);
+INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created, is_user_defined) SELECT UUID(),'VMware', '7.0', guest_os_name, guest_os_id, utc_timestamp(), 0  FROM `cloud`.`guest_os_hypervisor` WHERE hypervisor_type='VMware' AND hypervisor_version='6.7';
+
```
Comment (sureshanaparti) [inline engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql:25]: new guest os support in VMware 7.0 will be addressed here?

**Comment by nvazquez** [comment]
Run tests against vCenter 7.0 with 2 ESXi hosts on version 7.0.1:

````
[root@ref-trl-1958-v-M7-nicolas-vazquez-marvin marvin]# cat test-summary.txt 
82 look ok, 4 have errors
[root@ref-trl-1958-v-M7-nicolas-vazquez-marvin marvin]# cat smoketests-summary.txt 
Intermittent failure detected: /marvin/tests/smoke/test_affinity_groups.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_primary_storage.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_life_cycle.py
Intermittent failure detected: /marvin/tests/smoke/test_host_maintenance.py
Smoke tests completed. 82 look OK, 4 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_DeployVmAffinityGroup | `Failure` | 168.65 | test_affinity_groups.py
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 786.00 | test_kubernetes_clusters.py
test_04_deploy_and_scale_kubernetes_cluster | `Failure` | 85.78 | test_kubernetes_clusters.py
test_05_delete_kubernetes_cluster | `Failure` | 96.18 | test_kubernetes_clusters.py
test_07_deploy_kubernetes_ha_cluster | `Failure` | 0.11 | test_kubernetes_clusters.py
test_08_deploy_and_upgrade_kubernetes_ha_cluster | `Failure` | 0.09 | test_kubernetes_clusters.py
test_09_delete_kubernetes_ha_cluster | `Failure` | 0.10 | test_kubernetes_clusters.py
ContextSuite context=TestKubernetesCluster>:teardown | `Error` | 85.21 | test_kubernetes_clusters.py
test_03_migration_options_storage_tags | `Error` | 0.44 | test_primary_storage.py
test_01_migrate_VM_and_root_volume | `Error` | 112.09 | test_vm_life_cycle.py
test_02_migrate_VM_with_two_data_disks | `Error` | 60.85 | test_vm_life_cycle.py
test_03_migrate_detached_volume | `Error` | 73.09 | test_vm_life_cycle.py
ContextSuite context=TestVAppsVM>:setup | `Error` | 62.04 | test_vm_life_cycle.py
````

File: engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql (hunk 1 above)
Comment (nvazquez) [reply engine/schema/src/main/resources/META-INF/db/schema-41400to41500.sql:25]: :+1:

**Comment by nvazquez** [comment]
@blueorangutan package

File: services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java [hunk 2]
```diff
@@ -537,10 +545,14 @@ public static ConsoleProxyNoVncClient getNoVncViewer(ConsoleProxyClientParam par
...
         String clientKey = param.getClientMapKey();
+        String ticketAcquired = param.getTicketAcquired();
+        if (StringUtils.isNotBlank(ticketAcquired)) {
+            s_logger.info(">>>>> NO VNC Viewer received ticket acquired: " + param.getTicketAcquired());
+        }
         synchronized (connectionMap) {
             ConsoleProxyClient viewer = connectionMap.get(clientKey);
             if (viewer == null || viewer.getClass() != ConsoleProxyNoVncClient.class) {
-                authenticationExternally(param);
+                //authenticationExternally(param);
```
Comment (sureshanaparti) [inline services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java:555]: remove the comment if not required here

File: services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java [hunk 3]
```diff
@@ -170,6 +171,13 @@ public static ConsoleProxyAuthenticationResult authenticateConsoleAccess(Console
         authResult.setReauthentication(reauthentication);
         authResult.setHost(param.getClientHostAddress());
         authResult.setPort(param.getClientHostPort());
+        if (StringUtils.isNotBlank(param.getTicketAcquired())) {
+            s_logger.info("Host = " + param.getClientHostAddress() + ", hypervhost = " + param.getHypervHost() +
+                    " pass = " + param.getPassword() + " hostpass = " + param.getClientHostPassword() +
+                    " asd = " + param.getClientHostPort());
+            s_logger.info("Connecting using ticket " + param.getTicketAcquired() + " port 443");
+            authResult.setPort(443);
```
Comment (sureshanaparti) [inline services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxy.java:179]: @nvazquez is this port customizable at vCenter / host (or) fixed ?

**Comment by nvazquez** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java [hunk 4]
```diff
@@ -500,6 +526,20 @@ private String composeConsoleAccessUrl(String rootUrl, VirtualMachine vm, HostVO
...
 
+    /**
+     * Generates an extra parameter to be passed to noVNC server to connect to WebSocket exposed on Vmware hosts.
+     * This method has been introduced as Vmware 7 has deprecated the previous VNC approach to connect to VMs console.
+     * Please check: https://docs.vmware.com/en/VMware-vSphere/7.0/rn/vsphere-esxi-vcenter-server-70-release-notes.html
+     */
+    private String generateExtraNoVNCParameter(ConsoleProxyClientParam param) {
+        String extraParam = null;
+        if (StringUtils.isNotBlank(param.getTicketAcquired())) {
+            extraParam = "wss://" + param.getClientHostAddress() + ":443/ticket/" + param.getTicketAcquired();
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java:537]: @nvazquez declare a constant for port 443 in some common class (may be ConsoleProxyManager), and use it across.

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@davidjumani can you please review the CPVM/noVNC related commits?

**Comment by rhtyd** [comment]
@blueorangutan test matrix

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql [hunk 5]
```diff
@@ -18,4 +18,10 @@
...
+INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created, is_user_defined) SELECT UUID(),'VMware', '7.0', guest_os_name, guest_os_id, utc_timestamp(), 0  FROM `cloud`.`guest_os_hypervisor` WHERE hypervisor_type='VMware' AND hypervisor_version='6.7';
 
+-- Add support for VMware 7.0.1.0
+INSERT IGNORE INTO `cloud`.`hypervisor_capabilities` (uuid, hypervisor_type, hypervisor_version, max_guests_limit, security_group_enabled, max_data_volumes_limit, max_hosts_per_cluster, storage_motion_supported, vm_snapshot_enabled) values (UUID(), 'VMware', '7.0.1.0', 1024, 0, 59, 64, 1, 1);
+INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created, is_user_defined) SELECT UUID(),'VMware', '7.0.1.0', guest_os_name, guest_os_id, utc_timestamp(), 0  FROM `cloud`.`guest_os_hypervisor` WHERE hypervisor_type='VMware' AND hypervisor_version='7.0';
```
Comment (rhtyd) [inline engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:27]: @nvazquez do we (codewise) differentiate between 7.0 and 7.0.1.0? Pl check otherwise there is no need of adding support for 7.0.1.0 if it would fallback and use 7.0. Also can you check and add support for new guest OSs which are missing in the sql upgrade path.

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql [hunk 6]
```diff
@@ -18,4 +18,10 @@
 --;
 -- Schema upgrade from 4.15.0.0 to 4.15.1.0
 --;
+-- Add support for VMware 7.0
```
Comment (sureshanaparti) [inline engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:21]: @nvazquez any new OS supported with 7.0 / 7.0.1.0 to be added to guest os mappings

File: services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java [hunk 7]
```diff
@@ -62,6 +69,27 @@ public void connectTo(String host, int port) throws UnknownHostException, IOExce
...
 
+    public void connectToWebSocket(String websocketUrl, Session session) throws URISyntaxException {
+        webSocketReverseProxy = new WebSocketReverseProxy(new URI(websocketUrl), session);
+        webSocketReverseProxy.connect();
+    }
+
+    public boolean isVncOverWebSocketConnection() {
+        return webSocketReverseProxy != null;
+    }
+
```
Comment (sureshanaparti) [inline services/console-proxy/server/src/main/java/com/cloud/consoleproxy/vnc/NoVncClient.java:80]: Non websocket connections, will cause NPE for the below methods. Either add a comment here to use these methods for _isVncOverWebSocketConnection()_ true, or explicitly add a check.

File: server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java [hunk 8]
```diff
@@ -417,6 +425,40 @@ private String composeThumbnailUrl(String rootUrl, VirtualMachine vm, HostVO hos
         return sb.toString();
     }
 
+    /**
+     * Sets the URL to establish a VNC over websocket connection
+     */
+    private void setWebsocketUrl(VirtualMachine vm, ConsoleProxyClientParam param) {
+        String ticket = acquireVncTicketForVmwareVm(vm);
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java:432]: _ acquireVncTicketForVmwareVm()_ returns null, in case of any errors/expections, check for the same ?

File: core/src/main/java/com/cloud/agent/api/GetVmVncTicketAnswer.java [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+//
+package com.cloud.agent.api;
+
+public class GetVmVncTicketAnswer extends Answer {
+
```
Comment (sureshanaparti) [inline core/src/main/java/com/cloud/agent/api/GetVmVncTicketAnswer.java:22]: cmd result (success / failed - with the reason) in the answer?

File: server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java [hunk 10]
```diff
@@ -417,6 +425,40 @@ private String composeThumbnailUrl(String rootUrl, VirtualMachine vm, HostVO hos
...
+    /**
+     * Acquires a ticket to be used for console proxy as described in 'Removal of VNC Server from ESXi' on:
+     * https://docs.vmware.com/en/VMware-vSphere/7.0/rn/vsphere-esxi-vcenter-server-70-release-notes.html
+     */
+    private String acquireVncTicketForVmwareVm(VirtualMachine vm) {
+        try {
+            s_logger.info("Acquiring VNC ticket for VM = " + vm.getHostName());
+            GetVmVncTicketCommand cmd = new GetVmVncTicketCommand(vm.getInstanceName());
+            Answer answer = agentManager.send(vm.getHostId(), cmd);
+            GetVmVncTicketAnswer ans = (GetVmVncTicketAnswer) answer;
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java:454]: better check for the answer result before continuing with the ticket, as the ticket can be null in case of error scenarios

File: server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java [hunk 11]
```diff
@@ -417,6 +425,40 @@ private String composeThumbnailUrl(String rootUrl, VirtualMachine vm, HostVO hos
...
+            return ans.getTicket();
+        } catch (AgentUnavailableException | OperationTimedoutException e) {
+            s_logger.error("Error acquiring ticket", e);
+            return null;
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java:458]: in case of failure, better send the error msg with result as fail in the answer, and process accordingly on the receiving side.

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql (hunk 5 above)
Comment (nvazquez) [reply engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql]: @rhtyd yes - hosts on 7.0 u1 report the version 7.0.1.0

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql (hunk 6 above)
Comment (nvazquez) [reply engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:21]: @sureshanaparti yes - added on the last commit

**Comment by nvazquez** [comment]
Thanks @sureshanaparti @rhtyd - comments addressed

@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql [hunk 12]
```diff
@@ -18,4 +18,85 @@
...
+-- Add support for vmkernel7Guest from VMware 7.0
+INSERT INTO `cloud`.`guest_os` (id, uuid, category_id, display_name, created) VALUES (334, UUID(), 7, 'vmkernel7Guest', now());
+INSERT INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created, is_user_defined) VALUES (UUID(),'VMware', '7.0', 'vmkernel7Guest', 334, now(), 0);
+
+-- Add support for windows2019srv_64Guest from VMware 7.0
+INSERT INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created, is_user_defined) VALUES (UUID(),'VMware', '7.0', 'windows2019srv_64Guest', 276, now(), 0);
+
+
+-- Add support for VMware 7.0.1.0
+INSERT IGNORE INTO `cloud`.`hypervisor_capabilities` (uuid, hypervisor_type, hypervisor_version, max_guests_limit, security_group_enabled, max_data_volumes_limit, max_hosts_per_cluster, storage_motion_supported, vm_snapshot_enabled) values (UUID(), 'VMware', '7.0.1.0', 1024, 0, 59, 64, 1, 1);
```
Comment (rhtyd) [inline engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:50]: @nvazquez does CloudStack/VMware plugin make a difference between 7.0 and 7.0.1.0 from the DB?

**Comment by rhtyd** [comment]
Let me regression testing
@blueorangutan test centos7 vmware-67u3

**Comment by DaanHoogland** [comment]
@rhtyd @nvazquez this has `[WIP]` in the name. is it still a draft?

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql (hunk 12 above)
Comment (nvazquez) [reply engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:50]: @rhtyd yes - hosts on 7.0 u1 report the version 7.0.1.0

**Comment by nvazquez** [comment]
@DaanHoogland it is ready for review, I have now removed the WIP tag on the name

File: services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java [hunk 13]
```diff
@@ -121,22 +126,33 @@ public void run() {
...
+                        } else {
+                            b = new byte[100];
+                            readBytes = client.read(b);
+                            if (readBytes == -1) {
+                                break;
+                            }
+                            if (readBytes > 0) {
+                                session.getRemote().sendBytes(ByteBuffer.wrap(b, 0, readBytes));
+                                updateFrontEndActivityTime();
+                            }
```
Comment (DaanHoogland) [inline services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java:155]: could you disect `initlient()` into multiple methods, it is sneakily growing too complex.

**Review by DaanHoogland — APPROVED** [review]
code looks good, we'll need to add test possibility for this in several ways (i.e. env/test cases)

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql (hunk 12 above)
Comment (rhtyd) [inline engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:50]: Should the version be just `7.0.1`? 
I see this on esxi - `/resourceGroups/version = "7.0.1"`

Comment (rhtyd) [reply engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:50]: or is it the version returned by vcenter?

**Comment by nvazquez** [comment]
@blueorangutan package

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql (hunk 12 above)
Comment (nvazquez) [reply engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql:50]: I've checked the code and this value comes from the SDK interaction to the hostMO.getHostAboutInfo().getApiVersion();

In a test environment I get:
````
MariaDB [cloud]> select id,name,status,version, hypervisor_version, hypervisor_type from host where type = 'Routing';
+----+-------------+--------+-------------------+--------------------+-----------------+
| id | name        | status | version           | hypervisor_version | hypervisor_type |
+----+-------------+--------+-------------------+--------------------+-----------------+
|  1 | 10.0.33.193 | Up     | 4.15.1.0-SNAPSHOT | 7.0.1.0            | VMware          |
|  2 | 10.0.35.144 | Up     | 4.15.1.0-SNAPSHOT | 7.0.1.0            | VMware          |
+----+-------------+--------+-------------------+--------------------+-----------------+
2 rows in set (0.00 sec)

````

File: engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql [hunk 14]
```diff
@@ -18,4 +18,85 @@
 --;
 -- Schema upgrade from 4.15.0.0 to 4.15.1.0
 --;
+-- Add support for VMware 7.0
+INSERT IGNORE INTO `cloud`.`hypervisor_capabilities` (uuid, hypervisor_type, hypervisor_version, max_guests_limit, security_group_enabled, max_data_volumes_limit, max_hosts_per_cluster, storage_motion_supported, vm_snapshot_enabled) values (UUID(), 'VMware', '7.0', 1024, 0, 59, 64, 1, 1);
+INSERT IGNORE INTO `cloud`.`guest_os_hypervisor` (uuid,hypervisor_type, hypervisor_version, guest_os_name, guest_os_id, created, is_user_defined) SELECT UUID(),'VMware', '7.0', guest_os_name, guest_os_id, utc_timestamp(), 0  FROM `cloud`.`guest_os_hypervisor` WHERE hypervisor_type='VMware' AND hypervisor_version='6.7';
+
+-- Add support for crxPod1Guest from VMware 7.0
+INSERT INTO `cloud`.`guest_os` (id, uuid, category_id, display_name, created) VALUES (330, UUID(), 7, 'crxPod1Guest', now());
```
[the remark this answers is not in the document]
Comment (nvazquez) [reply engine/schema/src/main/resources/META-INF/db/schema-41500to41510.sql]: Thanks

File: services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java (hunk 13 above)
Comment (nvazquez) [reply services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java]: Done, thanks

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by rhtyd** [comment]
@nvazquez can you fix the merge conflict?

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@nvazquez please fix conflicts and re-run a round of smoketests against vmware7 and vmware 6.7

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@nvazquez can you kick smoketests against vmware 7.0 as well? And if we can get support for vsphere7 in Trillian?

**Comment by nvazquez** [comment]
@blueorangutan help

**Comment by nvazquez** [comment]
@blueorangutan help

**Comment by nvazquez** [comment]
@blueorangutan help

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-70u1

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-70u1

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-70u1

**Comment by nvazquez** [comment]
@rhtyd @vladimirpetrov Vmware 7.0 support was introduced into Trillian and the last tests were executed on it, few errors which seem unrelated to this PR. Please advise if we are ready to merge it

**Comment by rhtyd** [comment]
LGTM, @vladimirpetrov are you lgtm on this?

**Review by vladimirpetrov — APPROVED** [review]
Testing finished, LGTM @nvazquez, @rhtyd !

**Comment by rhtyd** [comment]
Merging based on tests and code reviews.
