### PR TITLE
saml: introduce saml2.check.signature

### LINKED ISSUE #4519: SAML signature is optional
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI: SAML login
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0
~~~

##### CONFIGURATION

SAML authentication activated

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The SAML signature is optional and not mandatory. A user can login into a domain where he's not allowed to.

##### STEPS TO REPRODUCE

Use a tool to intercept the web requests between your browser ant the cloudstack UI (our pentester used "burp"). Login to cloudstack using a SSO account (SAML).
Now, you're logged in successfully to your cloudstack domain. 
Logout from cloudstack.

Now, log in again to cloudstack, but with the "interceptor" active. In the request, delete the whole saml-signature and change the username to another SSO user from within another tenant.
Run the modified request, and you're logged in into this foreign account.

~~~

~~~

##### EXPECTED RESULTS

User can't log in into foreign tenant
~~~

~~~

##### ACTUAL RESULTS

User can log in into foreign tenant

~~~

~~~

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Adminstrators should ensure that IDP configuration has signing certificate for the actual signature check to be performed. In addition to this, this change introduces a new global setting `saml2.check.signature` which can deliberately fail a SAML login attempt when the SAML response has missing signature.

Fixes #4519

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

### CODE REVIEW

**Review by shwstppr — APPROVED** [review]
Code LGTM. Would it make sense to move the new check in a separate method and add some unit tests?

File: plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmd.java [hunk 1]
```diff
@@ -238,9 +245,8 @@ public String authenticate(final String command, final Map<String, Object[]> par
                                 params, responseType));
                     }
                 }
-                if (username == null) {
```
Comment (rohityadavcloud) [inline plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/api/command/SAML2LoginAPIAuthenticatorCmd.java:241]: FYI - username is always declared as null above, so no point in checking that.

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by rohityadavcloud** [comment]
Tested locally, in default case the checks are totally skipped; more secured env will need testing with and without encrypted assertions - real world users can test those. Unit tests ensure/test for both cases.
@blueorangutan test
