### PR TITLE
Fix NPE on updating security groups for an instance

### LINKED ISSUE #10347: Unable to update the security groups of a VM
### problem

I'm using the newly released feature that allows enabling security groups support in advanced zones, and I'm unable to change the security groups assigned to VMs in my shared network.

This is the error returned:

```
(dev) 🐱 > update virtualmachine id=450bbfd5-55a7-44d3-966b-99772d50a405 securitygroupnames=default
🙈 Error: (HTTP 530, error code 9999) Cannot invoke "com.cloud.network.Network.getTrafficType()" because "network" is null
```

The problem seems to be related to a permissions check, it's possible to go around that error by manually inserting a record into the `network_permissions` table.

```
(dev) 🐱 > create networkpermissions accountids=7ad6fcd9-bb8b-48e0-83eb-01263c2907c6 networkid=aa67cbd3-4aae-4b7c-87cb-51b1f0605d8e
🙈 Error: (HTTP 431, error code 4350) network is already shared in domain
```

```
MariaDB [cloud]> insert into network_permissions (network_id, account_id) values (228,2319);
Query OK, 1 row affected (0.003 sec)
```

After this, the `update virtualmachine` call works and the SG is updated normally.

Code reference: https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/network/NetworkModelImpl.java#L1727

### versions

Cloudstack 4.20.

### The steps to reproduce the bug

1. Enable security groups support in an advanced zone
2. Create a shared network that is accessible to all accounts (selected scope is ALL), the network offering selected enables SGs.
3. Stop a VM and try to change the security groups either using the UI or API, both won't work

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes #10347 

<details><summary>Details</summary>
<p>

This pull request includes changes to the `UserVmManagerImpl` class and UI components to improve the handling of security groups for virtual machines. The most important changes include refactoring the security group update logic and adding UI support for security groups.

### Backend changes:

* [`server/src/main/java/com/cloud/vm/UserVmManagerImpl.java`](diffhunk://#diff-865f710fe60b9b62ff8c2cbce8a8342e4f6fca658223119762285fd5f7857f08L3108-L3143): Refactored the security group update logic by removing redundant code and encapsulating the update logic in a new `updateSecurityGroup` method. This improves code readability and maintainability. [[1]](diffhunk://#diff-865f710fe60b9b62ff8c2cbce8a8342e4f6fca658223119762285fd5f7857f08L3108-L3143) [[2]](diffhunk://#diff-865f710fe60b9b62ff8c2cbce8a8342e4f6fca658223119762285fd5f7857f08R3140-R3168) [[3]](diffhunk://#diff-865f710fe60b9b62ff8c2cbce8a8342e4f6fca658223119762285fd5f7857f08R3184-R3194)

### UI changes:

* [`ui/src/views/compute/EditVM.vue`](diffhunk://#diff-d97ad918bcafbd002d2abfeb0e54bce71ce96c0338928fe7c287e92b7e0f96e6L209-R209): Modified the security group enablement check to fall back on a Vuex store getter if the zone response does not provide the information. This ensures that the UI correctly reflects the security group support status.
* [`ui/src/views/compute/InstanceTab.vue`](diffhunk://#diff-bf8c6acc9fc55c107b5ddc946c3a479f15e6859f3b98bc263336ebd01d318f73R182): Added a new state variable `showUpdateSecurityGroupsModal` to manage the visibility of the security group update modal in the instance tab. This prepares the UI for future enhancements to support security group updates directly from the instance tab.

</p>
</details> 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 1]
```diff
@@ -3173,6 +3136,35 @@ public UserVm updateVirtualMachine(long id, String displayName, String group, Bo
...
+                } else {
+                    networkIds = networks.stream().map(Network::getId).collect(Collectors.toList());
+                }
+            } catch (InvalidParameterValueException e) {
+                if(logger.isDebugEnabled()) {
+                    logger.debug(e.getMessage(),e);
+                }
+            }
+
+            if (_networkModel.checkSecurityGroupSupportForNetwork(
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3160]: is there any issue if check all networks instead of the default network here ?

Comment (vishesh92) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3160]: It's possible for a VM to have an isolated network as the default network and a shared network with SG as a second one. In this case if we don't check for all networks, security groups won't get updated.

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 2]
```diff
@@ -3173,6 +3136,35 @@ public UserVm updateVirtualMachine(long id, String displayName, String group, Bo
                     .getUuid(), nic.getId(), extraDhcpOptionsMap);
         }
 
+        boolean isVMware = (vm.getHypervisorType() == HypervisorType.VMware);
+
+        if (securityGroupIdList != null && isVMware) {
+            throw new InvalidParameterValueException("Security group feature is not supported for vmWare hypervisor");
```
Comment (JoaoJandre) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3142]:
```suggestion
            throw new InvalidParameterValueException("Security group feature is not supported for VMware hypervisor");
```

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 3]
```diff
@@ -3173,6 +3136,35 @@ public UserVm updateVirtualMachine(long id, String displayName, String group, Bo
...
+        } else if (securityGroupIdList != null){
```
Comment (JoaoJandre) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3143]:
```suggestion
        } else if (securityGroupIdList != null) {
```

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 4]
```diff
@@ -3188,6 +3180,17 @@ public UserVm updateVirtualMachine(long id, String displayName, String group, Bo
...
     }
 
+    private void updateSecurityGroup(UserVmVO vm, List<Long> securityGroupIdList) {
+        if (vm.getState() == State.Stopped) {
+            // Remove instance from security groups
+            _securityGroupMgr.removeInstanceFromGroups(vm);
+            // Add instance in provided groups
+            _securityGroupMgr.addInstanceToGroups(vm, securityGroupIdList);
+        } else {
+            throw new InvalidParameterValueException("Virtual machine must be stopped prior to update security groups ");
```
Comment (JoaoJandre) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3190]: We could add the UUID of the VM on the exception.

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 5]
```diff
@@ -3173,6 +3136,35 @@ public UserVm updateVirtualMachine(long id, String displayName, String group, Bo
...
+                }
+            }
+
+            if (_networkModel.checkSecurityGroupSupportForNetwork(
+                            _accountMgr.getActiveAccountById(vm.getAccountId()),
+                            zone, networkIds, securityGroupIdList)
+            ) {
+                updateSecurityGroup(vm, securityGroupIdList);
+            }
+        }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3166]: can we extract this bit in a checkAndUpdate method?

Comment (harikrishna-patnala) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3184]: Done @DaanHoogland Thanks

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by harikrishna-patnala — APPROVED** [review]
Reproduced the issue and also verified the fix, did not observe the NPE after updating SG. LGTM.

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test securityGroups

**Comment by DaanHoogland** [comment]
51 ok 90 errors, I forgot what the baseline was for running with security groups . maybe we should add it to the matrix somehow (and stablise it)

**Comment by weizhouapache** [comment]
@DaanHoogland 
agree we need to stablize the tests on SG zone

let's re-run the tests to see if the results are consistent

@blueorangutan test securityGroups

**Comment by DaanHoogland** [comment]
@weizhouapache @vishesh92 51 vs 90 again, seems consistent.

**Comment by harikrishna-patnala** [comment]
@blueorangutan test
