### PR TITLE
api/server: cpu, memory values with overprovisioning in metrics response

### LINKED ISSUE #4778: Listhostsmetric cpuallocated >100%
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### SUMMARY

When listhostsmetric calculates cpualocated and cpualocatedghz, it does not set the cpu.overprovisioning.factor The coefficient is included, resulting in cpualocated > 100%

capabilities: "hvm,snapshot"
clusterid: "2c95571e-5cf9-4ff8-b09a-750a517d6dc4"
clustername: "cl01"
clustertype: "CloudManaged"
cpuallocated: "113.84%"
cpuallocateddisablethreshold: false
cpuallocatedghz: "76.50 Ghz"
cpuallocatedthreshold: false
cpudisablethreshold: false
cpuloadaverage: 3.93
cpumodelname: "Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz"
cpunumber: 32
cpusockets: 2
cpuspeed: 2100
cputhreshold: false
cputotalghz: "67.20 Ghz (x 4.0)"
cpuused: "7.66%"
cpuusedghz: "5.15 Ghz"
cpuwithoverprovisioning: "268800"
created: "2021-03-04T18:36:38+0800"

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #4778

Based on the discussion on https://lists.apache.org/thread.html/r9833add572ddd7303c2a523c833a8c863e8d272db268927a7ca9b525%40%3Cdev.cloudstack.apache.org%3E, metrics responses should return values with CPU/memory overprovisioning.
Changes in listHostsMetrics response, cpu and memory values with overprovisioning. Cluster and Zone metrics get correct values with host value changes.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

With cmk:

Without change:
```
(local) 🐱 > list zonesmetrics 
{
  "count": 1,
  "zone": [
    {
      "allocationstate": "Enabled",
      "clusters": "2 / 2",
      "cpuallocated": "0.52%",
      "cpuallocateddisablethreshold": false,
      "cpuallocatedthreshold": false,
      "cpudisablethreshold": false,
      "cputhreshold": false,
      "cputotal": "192.00 Ghz",
      "dhcpprovider": "VirtualRouter",
      "dns1": "10.147.28.6",
      "guestcidraddress": "10.1.1.0/24",
      "id": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "internaldns1": "10.147.28.6",
      "localstorageenabled": false,
      "memoryallocated": "3.13%",
      "memoryallocateddisablethreshold": false,
      "memoryallocatedthreshold": false,
      "memorydisablethreshold": false,
      "memorythreshold": false,
      "memorytotal": "48.00 GB",
      "name": "Sandbox-simulator",
      "networktype": "Advanced",
      "securitygroupsenabled": false,
      "state": "Enabled",
      "tags": [],
      "zonetoken": "20291feb-a0af-3dbf-8757-d5486debc1c3"
    }
  ]
}
(local) 🐱 > list clustersmetrics id=466e1831-8f69-4315-8477-3a16c3180038 
{
  "cluster": [
    {
      "allocationstate": "Enabled",
      "clustertype": "CloudManaged",
      "cpuallocated": "0.39%",
      "cpuallocateddisablethreshold": false,
      "cpuallocatedthreshold": false,
      "cpudisablethreshold": false,
      "cpuovercommitratio": "2.0",
      "cputhreshold": false,
      "cputotal": "128.00 Ghz",
      "hosts": "2 / 2",
      "hypervisortype": "Simulator",
      "id": "466e1831-8f69-4315-8477-3a16c3180038",
      "managedstate": "Managed",
      "memoryallocated": "1.56%",
      "memoryallocateddisablethreshold": false,
      "memoryallocatedthreshold": false,
      "memorydisablethreshold": false,
      "memoryovercommitratio": "2.0",
      "memorythreshold": false,
      "memorytotal": "32.00 GB",
      "name": "C1",
      "podid": "6163b5ba-fc97-422f-9b3c-cc11c70222f5",
      "podname": "POD0",
      "resourcedetails": {
        "cpuOvercommitRatio": "2.0",
        "memoryOvercommitRatio": "2.0"
      },
      "state": "Enabled",
      "zoneid": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "zonename": "Sandbox-simulator"
    }
  ],
  "count": 1
}
(local) 🐱 > list hosts id=17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7 
{
  "count": 1,
  "host": [
    {
      "capabilities": "hvm",
      "clusterid": "466e1831-8f69-4315-8477-3a16c3180038",
      "clustername": "C1",
      "clustertype": "CloudManaged",
      "cpuallocated": "1.56%",
      "cpuallocatedpercentage": "1.56%",
      "cpuallocatedvalue": 500,
      "cpuallocatedwithoverprovisioning": "0.78%",
      "cpuloadaverage": 0,
      "cpunumber": 4,
      "cpuspeed": 8000,
      "cpuused": "0%",
      "cpuwithoverprovisioning": "64000",
      "created": "2021-04-16T16:36:00+0530",
      "disconnected": "2021-04-20T13:57:10+0530",
      "events": "AgentDisconnected; AgentConnected; ManagementServerDown; PingTimeout; Ping; StartAgentRebalance; Remove; ShutdownRequested; HostDown",
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hypervisor": "Simulator",
      "hypervisorversion": "4.15.1.0-SNAPSHOT",
      "id": "17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7",
      "ipaddress": "172.16.15.18",
      "islocalstorageactive": false,
      "lastpinged": "1970-01-19T12:40:44+0530",
      "managementserverid": "981bca31-c0b0-4c43-a0ec-92a93dc05580",
      "memoryallocated": 536870912,
      "memoryallocatedbytes": 536870912,
      "memoryallocatedpercentage": "3.12%",
      "memorytotal": 8589934592,
      "memoryused": 0,
      "memorywithoverprovisioning": "17179869184",
      "name": "SimulatedAgent.e2bbf03f-3f8a-491a-9998-50ba60ab9692",
      "networkkbsread": 32768,
      "networkkbswrite": 16384,
      "outofbandmanagement": {
        "enabled": false,
        "powerstate": "Disabled"
      },
      "podid": "6163b5ba-fc97-422f-9b3c-cc11c70222f5",
      "podname": "POD0",
      "resourcestate": "Enabled",
      "state": "Up",
      "type": "Routing",
      "version": "4.15.1.0-SNAPSHOT",
      "zoneid": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "zonename": "Sandbox-simulator"
    }
  ]
}
(local) 🐱 > list hostsmetrics id=17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7 
{
  "count": 1,
  "host": [
    {
      "capabilities": "hvm",
      "clusterid": "466e1831-8f69-4315-8477-3a16c3180038",
      "clustername": "C1",
      "clustertype": "CloudManaged",
      "cpuallocated": "1.56%",
      "cpuallocateddisablethreshold": false,
      "cpuallocatedghz": "0.50 Ghz",
      "cpuallocatedthreshold": false,
      "cpudisablethreshold": false,
      "cpuloadaverage": 0,
      "cpunumber": 4,
      "cpuspeed": 8000,
      "cputhreshold": false,
      "cputotalghz": "32.00 Ghz (x 2.0)",
      "cpuused": "0%",
      "cpuusedghz": "0.00 Ghz",
      "cpuwithoverprovisioning": "64000",
      "created": "2021-04-16T16:36:00+0530",
      "disconnected": "2021-04-20T13:57:10+0530",
      "events": "AgentDisconnected; AgentConnected; ManagementServerDown; PingTimeout; Ping; StartAgentRebalance; Remove; ShutdownRequested; HostDown",
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hypervisor": "Simulator",
      "hypervisorversion": "4.15.1.0-SNAPSHOT",
      "id": "17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7",
      "instances": "0 / 0",
      "ipaddress": "172.16.15.18",
      "lastpinged": "1970-01-19T12:40:44+0530",
      "managementserverid": "981bca31-c0b0-4c43-a0ec-92a93dc05580",
      "memoryallocated": 536870912,
      "memoryallocateddisablethreshold": false,
      "memoryallocatedgb": "0.50 GB",
      "memoryallocatedthreshold": false,
      "memorydisablethreshold": false,
      "memorythreshold": false,
      "memorytotal": 8589934592,
      "memorytotalgb": "8.00 GB (x 2.0)",
      "memoryused": 0,
      "memoryusedgb": "0.00 GB",
      "name": "SimulatedAgent.e2bbf03f-3f8a-491a-9998-50ba60ab9692",
      "networkkbsread": 32768,
      "networkkbswrite": 16384,
      "networkread": "0.03 GB",
      "networkwrite": "0.02 GB",
      "outofbandmanagement": {
        "enabled": false,
        "powerstate": "Disabled"
      },
      "podid": "6163b5ba-fc97-422f-9b3c-cc11c70222f5",
      "podname": "POD0",
      "powerstate": "Disabled",
      "resourcestate": "Enabled",
      "state": "Up",
      "type": "Routing",
      "version": "4.15.1.0-SNAPSHOT",
      "zoneid": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "zonename": "Sandbox-simulator"
    }
  ]
}
```

With change (difference in host's reponses)
```
(local) 🐱 > list zonesmetrics 
{
  "count": 1,
  "zone": [
    {
      "allocationstate": "Enabled",
      "clusters": "2 / 2",
      "cpuallocated": "0.52%",
      "cpuallocateddisablethreshold": false,
      "cpuallocatedthreshold": false,
      "cpudisablethreshold": false,
      "cputhreshold": false,
      "cputotal": "192.00 Ghz",
      "dhcpprovider": "VirtualRouter",
      "dns1": "10.147.28.6",
      "guestcidraddress": "10.1.1.0/24",
      "id": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "internaldns1": "10.147.28.6",
      "localstorageenabled": false,
      "memoryallocated": "3.13%",
      "memoryallocateddisablethreshold": false,
      "memoryallocatedthreshold": false,
      "memorydisablethreshold": false,
      "memorythreshold": false,
      "memorytotal": "48.00 GB",
      "name": "Sandbox-simulator",
      "networktype": "Advanced",
      "securitygroupsenabled": false,
      "state": "Enabled",
      "tags": [],
      "zonetoken": "20291feb-a0af-3dbf-8757-d5486debc1c3"
    }
  ]
}
(local) 🐱 > list clustersmetrics id=466e1831-8f69-4315-8477-3a16c3180038 
{
  "cluster": [
    {
      "allocationstate": "Enabled",
      "clustertype": "CloudManaged",
      "cpuallocated": "0.39%",
      "cpuallocateddisablethreshold": false,
      "cpuallocatedthreshold": false,
      "cpudisablethreshold": false,
      "cpuovercommitratio": "2.0",
      "cputhreshold": false,
      "cputotal": "128.00 Ghz",
      "hosts": "2 / 2",
      "hypervisortype": "Simulator",
      "id": "466e1831-8f69-4315-8477-3a16c3180038",
      "managedstate": "Managed",
      "memoryallocated": "1.56%",
      "memoryallocateddisablethreshold": false,
      "memoryallocatedthreshold": false,
      "memorydisablethreshold": false,
      "memoryovercommitratio": "2.0",
      "memorythreshold": false,
      "memorytotal": "32.00 GB",
      "name": "C1",
      "podid": "6163b5ba-fc97-422f-9b3c-cc11c70222f5",
      "podname": "POD0",
      "resourcedetails": {
        "cpuOvercommitRatio": "2.0",
        "memoryOvercommitRatio": "2.0"
      },
      "state": "Enabled",
      "zoneid": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "zonename": "Sandbox-simulator"
    }
  ],
  "count": 1
}
(local) 🐱 > list hosts id=17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7 
{
  "count": 1,
  "host": [
    {
      "capabilities": "hvm",
      "clusterid": "466e1831-8f69-4315-8477-3a16c3180038",
      "clustername": "C1",
      "clustertype": "CloudManaged",
      "cpuallocated": "0.78%",
      "cpuallocatedpercentage": "0.78%",
      "cpuallocatedvalue": 500,
      "cpuallocatedwithoverprovisioning": "0.78%",
      "cpuloadaverage": 0,
      "cpunumber": 8,
      "cpuspeed": 8000,
      "cpuused": "0%",
      "cpuwithoverprovisioning": "64000",
      "created": "2021-04-16T16:36:00+0530",
      "disconnected": "2021-04-20T13:57:10+0530",
      "events": "AgentConnected; AgentDisconnected; Ping; ShutdownRequested; Remove; ManagementServerDown; PingTimeout; HostDown; StartAgentRebalance",
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hypervisor": "Simulator",
      "hypervisorversion": "4.15.1.0-SNAPSHOT",
      "id": "17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7",
      "ipaddress": "172.16.15.18",
      "islocalstorageactive": false,
      "lastpinged": "1970-01-19T12:40:43+0530",
      "managementserverid": "981bca31-c0b0-4c43-a0ec-92a93dc05580",
      "memoryallocated": 536870912,
      "memoryallocatedbytes": 536870912,
      "memoryallocatedpercentage": "3.12%",
      "memorytotal": 17179869184,
      "memoryused": 0,
      "memorywithoverprovisioning": "17179869184",
      "name": "SimulatedAgent.e2bbf03f-3f8a-491a-9998-50ba60ab9692",
      "networkkbsread": 32768,
      "networkkbswrite": 16384,
      "outofbandmanagement": {
        "enabled": false,
        "powerstate": "Disabled"
      },
      "podid": "6163b5ba-fc97-422f-9b3c-cc11c70222f5",
      "podname": "POD0",
      "resourcestate": "Enabled",
      "state": "Up",
      "type": "Routing",
      "version": "4.15.1.0-SNAPSHOT",
      "zoneid": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "zonename": "Sandbox-simulator"
    }
  ]
}
(local) 🐱 > list hostsmetrics id=17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7 
{
  "count": 1,
  "host": [
    {
      "capabilities": "hvm",
      "clusterid": "466e1831-8f69-4315-8477-3a16c3180038",
      "clustername": "C1",
      "clustertype": "CloudManaged",
      "cpuallocated": "0.78%",
      "cpuallocateddisablethreshold": false,
      "cpuallocatedghz": "0.50 Ghz",
      "cpuallocatedthreshold": false,
      "cpuallocatedwithoverprovisioning": "0.78%",
      "cpudisablethreshold": false,
      "cpuloadaverage": 0,
      "cpunumber": 8,
      "cpuspeed": 8000,
      "cputhreshold": false,
      "cputotalghz": "64.00 Ghz",
      "cpuused": "0%",
      "cpuusedghz": "0.00 Ghz",
      "cpuwithoverprovisioning": "64000",
      "created": "2021-04-16T16:36:00+0530",
      "disconnected": "2021-04-20T13:57:10+0530",
      "events": "AgentConnected; AgentDisconnected; Ping; ShutdownRequested; Remove; ManagementServerDown; PingTimeout; HostDown; StartAgentRebalance",
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hypervisor": "Simulator",
      "hypervisorversion": "4.15.1.0-SNAPSHOT",
      "id": "17d27b16-ae1e-43b0-89e8-e8ce8f0c54a7",
      "instances": "0 / 0",
      "ipaddress": "172.16.15.18",
      "lastpinged": "1970-01-19T12:40:43+0530",
      "managementserverid": "981bca31-c0b0-4c43-a0ec-92a93dc05580",
      "memoryallocated": 536870912,
      "memoryallocateddisablethreshold": false,
      "memoryallocatedgb": "0.50 GB",
      "memoryallocatedthreshold": false,
      "memorydisablethreshold": false,
      "memorythreshold": false,
      "memorytotal": 17179869184,
      "memorytotalgb": "16.00 GB",
      "memoryused": 0,
      "memoryusedgb": "0.00 GB",
      "name": "SimulatedAgent.e2bbf03f-3f8a-491a-9998-50ba60ab9692",
      "networkkbsread": 32768,
      "networkkbswrite": 16384,
      "networkread": "0.03 GB",
      "networkwrite": "0.02 GB",
      "outofbandmanagement": {
        "enabled": false,
        "powerstate": "Disabled"
      },
      "podid": "6163b5ba-fc97-422f-9b3c-cc11c70222f5",
      "podname": "POD0",
      "powerstate": "Disabled",
      "resourcestate": "Enabled",
      "state": "Up",
      "type": "Routing",
      "version": "4.15.1.0-SNAPSHOT",
      "zoneid": "e2b46eac-7f4b-4d87-a9d6-5a9957747cd5",
      "zonename": "Sandbox-simulator"
    }
  ]
}
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@shwstppr are you going to extend this as you sugested in #4778? or is it ready now? (cgltm)

**Comment by shwstppr** [comment]
@DaanHoogland not sure if we really need to change anything in terms of memory,
```
      "memoryallocated": 268435456,
      "memoryallocateddisablethreshold": false,
      "memoryallocatedgb": "0.25 GB",
      "memoryallocatedthreshold": false,
      "memorytotal": 7277121536,
      "memorytotalgb": "6.78 GB (x 1.0)"
```
`memorytotalgb` mentions overcommit ratio here and unlike cpu `memoryallocated` is giving a bytes value and not a percentage.
Let me know if you see any improvement here.

**Comment by DaanHoogland** [comment]
> @DaanHoogland not sure if we really need to change anything in terms of memory,
> 
> ```
>       "memoryallocated": 268435456,
>       "memoryallocateddisablethreshold": false,
>       "memoryallocatedgb": "0.25 GB",
>       "memoryallocatedthreshold": false,
>       "memorytotal": 7277121536,
>       "memorytotalgb": "6.78 GB (x 1.0)"
> ```
> 
> `memorytotalgb` mentions overcommit ratio here and unlike cpu `memoryallocated` is giving a bytes value and not a percentage.
> Let me know if you see any improvement here.

Yes, but we have an incosistency, `memorytotalgb` and `cputotalgb` have incosistent meanings. That was the reason to add the `-withoverprovisioning`, if i remember correctly.

File: plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java [hunk 1]
```diff
@@ -43,6 +44,10 @@
     @Param(description = "the total cpu allocated in Ghz")
     private String cpuAllocated;
 
+    @SerializedName("cpuallocatedghzwithoverprovisioning")
+    @Param(description = "the total cpu allocated in Ghz after applying the cpu.overprovisioning.factor", since="4.15.1")
+    private String cpuAllocatedWithOverprovisioning;
```
Comment (rhtyd) [inline plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java:49]: I think allocated cpu metric should involve overprovisioning (if the UI is not doing that); if the overprovisioning factor is not being considered is the cpu alllocated same as usage?

**Comment by rhtyd** [comment]
@shwstppr can you start a discussion thread on dev@ to get feedback from others, I think all allocated metrics should include/consider the overprovisioning factor.

**Comment by rhtyd** [comment]
ping @shwstppr cc @davidjumani

**Comment by shwstppr** [comment]
@shwstppr thread on dev@ here, https://lists.apache.org/thread.html/r9833add572ddd7303c2a523c833a8c863e8d272db268927a7ca9b525%40%3Cdev.cloudstack.apache.org%3E

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@shwstppr is this ready for review/merging?

**Review by DaanHoogland — COMMENTED** [review]
clgtm. I'm a bit worried this might come as a surprise to some users and whether scripting will fail on these changes. Not sure how to remedie safe adding response parameters for the changed values.

**Review by vladimirpetrov — APPROVED** [review]
list hosts, clustersmetrics and zonesmetrics commands' output tested and working as expected.
LGTM

**Review by rhtyd — APPROVED** [review]
