### PR TITLE
CKS: Use Zone MTUs when network is created at the time of CKS cluster creation

### LINKED ISSUE #12205: CKS default network does not respect zone restrictions
### problem

When you create an isolated network without specifying the MTU in a zone with a specific MTU, it is respected and the network is set with these Zone MTU.
When you create a CKS with the default network and without specifying the MTU it does not respect the zone MTU and create by default 1500 MTU no matter what is fixed in the zone.

### versions

Cloudstack 4.20.0.2
CKS : 
setup-v1.33.1-calico-x86_64.iso
--
[setup-v1.33.1-calico-x86_64.iso](https://download.cloudstack.org/cks/setup-v1.33.1-calico-x86_64.iso)

### The steps to reproduce the bug

1. Deploy a zone
2. Specify lower MTU than the default 1500 in zone settings
3. Deploy a CKS in the zone
4. Check the default created isolated network's MTU which are 1500 no matter what.

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes: #12205 
When a cluster is created without specifying a network, then an isolated network is created automatically with the default MTU. However, if there is an MTU set at zone level, then it would be ideal to use that instead.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java [hunk 1]
```diff
@@ -1869,6 +1869,18 @@ public Network createGuestNetwork(long networkOfferingId, String name, String di
                 null, null, null, null, null, null, null, null, null, null);
     }
 
+    @Override
+    @DB
+    @ActionEvent(eventType = EventTypes.EVENT_NETWORK_CREATE, eventDescription = "creating network")
+    public Network createGuestNetwork(long networkOfferingId, String name, String displayText, Account owner,
+                                      PhysicalNetwork physicalNetwork, long zoneId, ACLType aclType, Pair<Integer, Integer> vrIfaceMTUs) throws
+            InsufficientCapacityException, ConcurrentOperationException, ResourceAllocationException {
+        return _networkMgr.createGuestNetwork(networkOfferingId, name, displayText,
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/network/NetworkServiceImpl.java:1878]: We can call this directly in KubernetesClusterManagerImpl?

Comment (Pearl1594) [reply server/src/main/java/com/cloud/network/NetworkServiceImpl.java:1878]: I did consider that, but found value in creating a method that takes MTU as a parameter - which "probably" could be reused in future at other places, and it's simpler as it hides a lot of the low level parameters that NetworkManager::createGuestNetwork expects.

**Review by shwstppr — APPROVED** [review]
code lgtm

**Comment by Damans227** [comment]
Created a PR test environment and tested against it. Set zone-level MTU to 1400 (`vr.public.interface.max.mtu` and `vr.private.interface.max.mtu`), then created a CKS cluster without specifying a network. The auto-created network correctly inherited the zone MTU settings (publicmtu=1400, privatemtu=1400) instead of the default 1500. LGTM

image

image

**Review by Damans227 — APPROVED** [review]
I tested it manually and posted my findings. LGTM.

**Comment by DaanHoogland** [comment]
@Pearl1594 is this ready (everybody but you seems to think so ;)
