### PR TITLE
cks: fix events

### LINKED ISSUE #8043: ISO.CREATE event is not present for Kubernetes ISO registration
**ISSUE TYPE**

Bug report

**COMPONENT NAME**

Component: UI

**CLOUDSTACK VERSION**

Cloudstack version 4.18

**SUMMARY**

ISO.CREATE event is not present for Kubernetes ISO registration 

**Steps to reproduce the issue**

Register a kubernetes iso

1. Navigate to 

Image> Kubernetes ISO > Add Kubernetes Iso
 
Screenshot 2023-10-05 at 11 16 15 AM

2. Navigate to 

Image > ISo's > Events

Screenshot 2023-10-05 at 11 22 00 AM

**The iso create event is present in the event section only**

Screenshot 2023-10-05 at 11 14 35 AM

**Expected behavior**

ISO.CREATE event should be present for the kubernetes iso 

**Actual behavior**

ISO.CREATE event should be present for the kubernetes iso

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #8043 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [x] Trivial

### Screenshots (if appropriate):
Screenshot from 2024-05-20 14-19-06
Screenshot from 2024-05-20 14-18-37

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
code looks good @shwstppr , if I read this correctly it adds (fixes) a lot more events than the one reported in #8043 .  Is this worth a doc PR?

**Comment by DaanHoogland** [comment]
> @DaanHoogland this PR just fixes events for different CKS actions for both k8s cluster and k8s supported versions. Mainly the resources linked to the events. I'm not sure what can be added in a doc PR. Do you have any suggestions?

It is not specific to this PR, but I think we can look at more specific event documentation. I had a quick search of the docs and do not see any event documentation for other resources either. Just a thought. Forget it for now.

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java [hunk 1]
```diff
@@ -1270,29 +1280,64 @@ private SecurityGroup getOrCreateSecurityGroupForAccount(Account owner) {
         return securityGroup;
     }
 
+    @Override
+    @ActionEvent(eventType = KubernetesClusterEventTypes.EVENT_KUBERNETES_CLUSTER_CREATE,
+            eventDescription = "creating Kubernetes cluster", async = true)
```
Comment (vishesh92) [inline plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1285]:
```suggestion
    @ActionEvent(eventType = KubernetesClusterEventTypes.EVENT_KUBERNETES_CLUSTER_START,
            eventDescription = "starting Kubernetes cluster", async = true)
```

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java [hunk 2]
```diff
@@ -1384,6 +1431,8 @@ public boolean stopKubernetesCluster(StopKubernetesClusterCmd cmd) throws CloudR
     }
 
     @Override
+    @ActionEvent(eventType = KubernetesClusterEventTypes.EVENT_KUBERNETES_CLUSTER_DELETE,
+            eventDescription = "stopping Kubernetes cluster", async = true)
```
Comment (vishesh92) [inline plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1435]:
```suggestion
            eventDescription = "Deleting Kubernetes cluster", async = true)
```

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java [hunk 3]
```diff
@@ -1526,6 +1575,8 @@ public KubernetesClusterConfigResponse getKubernetesClusterConfig(GetKubernetesC
     }
 
     @Override
+    @ActionEvent(eventType = KubernetesClusterEventTypes.EVENT_KUBERNETES_CLUSTER_SCALE,
+            eventDescription = "scaling Kubernetes cluster", async = true)
     public boolean scaleKubernetesCluster(ScaleKubernetesClusterCmd cmd) throws CloudRuntimeException {
```
Comment (vishesh92) [inline plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1580]:
```java
CallContext.current().setEventDetails("Current min size: ?? New min size: ??");
```
Can we also set event details here? It would be good to have extra information about the change itself in events.

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java [hunk 4]
```diff
@@ -331,12 +345,14 @@ public KubernetesSupportedVersionResponse addKubernetesSupportedVersion(final Ad
...
         supportedVersionVO = kubernetesSupportedVersionDao.persist(supportedVersionVO);
+        CallContext.current().putContextParameter(KubernetesSupportedVersion.class, supportedVersionVO.getUuid());
 
         return createKubernetesSupportedVersionResponse(supportedVersionVO);
     }
 
     @Override
-    @ActionEvent(eventType = KubernetesVersionEventTypes.EVENT_KUBERNETES_VERSION_DELETE, eventDescription = "Deleting Kubernetes supported version", async = true)
+    @ActionEvent(eventType = KubernetesVersionEventTypes.EVENT_KUBERNETES_VERSION_DELETE,
+            eventDescription = "deleting Kubernetes supported version", async = true)
```
Comment (vishesh92) [inline plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java:355]:
```suggestion
            eventDescription = "Deleting Kubernetes supported version", async = true)
```

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java (hunk 1 above)
Comment (shwstppr) [reply plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1285]: @vishesh92 this is not needed as it is done deliberately to allow publishing `Completed` state event for `EVENT_KUBERNETES_CLUSTER_CREATE`. Argument passed for the method here is also `CreateKubernetesClusterCmd` so it will be used only when the cluster is created.

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java (hunk 3 above)
Comment (shwstppr) [reply plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1580]: will check

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java (hunk 2 above)
Comment (shwstppr) [reply plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1435]: will check and update

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java (hunk 4 above)
Comment (shwstppr) [reply plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java:355]: We have some code in ActionEventUtils or Interprator which prefixes `Successfully completed` to the event description

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java (hunk 3 above)
Comment (shwstppr) [reply plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/KubernetesClusterManagerImpl.java:1580]: I tried this. There are too many variables to scale,
- size
- minSize
- maxSize
- offering
I've limited my change to add event details only when there is change in size for now

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM

Before fix there was  no event tab in ISO  > Kubernetes 


Screenshot 2024-06-11 at 4 36 42 PM


After fix

Screenshot 2024-06-11 at 4 09 17 PM


Before fix  no iso.create event was present for k8s iso

Screenshot 2024-06-11 at 4 44 23 PM





Also the iso.create event is present  iso > kubernetes iso > events 


Screenshot 2024-06-11 at 4 33 51 PM

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@shwstppr LGTM but pl check if the package-lock.json needs to be removed and re-added in format/version 1, if only required:
```
npm i --lockfile-version 1
```
This is because, changing the lock file version may not work with older/other npm versions or cause unknown consequences due to change in direct/indirect dependencies; full UI QA may be necessary when/if this happens.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
