### PR TITLE
server: set template type to ROUTING or USER if template type is not specified when upload a template

### LINKED ISSUE #12763: Locally uploaded template is not shown in the deploy instance dialog
### problem

When a template is uploaded from local machine, it has 'NULL' type in the DB, table vm_template which (I guess) is the reason it's not shown in the deploy instance dialog. Here it how it looks in ACS 4.22:

Image

And here is how it looks in ACS 4.21:

Image

Seems related to #12104 

### versions

Found in 4.22, not present in 4.21.

### The steps to reproduce the bug

1. Upload a template from local machine.
2. Try to deploy a VM from the uploaded template.

Result: The template is not shown in deploy instance dialog.

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #12763 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@DaanHoogland @vishesh92 @vladimirpetrov 
do you think we should set the template type to USER in the upgrade sql ?


```
UPDATE `cloud`.`vm_template` SET `type` = "USER" WHERE `type` IS NULL;
```

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
> @DaanHoogland @vishesh92 @vladimirpetrov 
> do you think we should set the template type to USER in the upgrade sql ?
> 
> 
> ```
> UPDATE `cloud`.`vm_template` SET `type` = "USER" WHERE `type` IS NULL;
> ```

Sounds good, is type null leading to NPEs?

**Comment by weizhouapache** [comment]
> > @DaanHoogland @vishesh92 @vladimirpetrov
> > do you think we should set the template type to USER in the upgrade sql ?
> > ```
> > UPDATE `cloud`.`vm_template` SET `type` = "USER" WHERE `type` IS NULL;
> > ```
> 
> Sounds good, is type null leading to NPEs?

I think it does not lead to NPEs, but template/iso are not usable as the type is NULL.
In several places (UI and source code), cloudstack only lists templates with USER template type.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueoranguran package

**Comment by weizhouapache** [comment]
@blueoranguran package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by vladimirpetrov** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/template/TemplateManagerImpl.java [hunk 1]
```diff
@@ -2426,6 +2426,8 @@ public TemplateType validateTemplateType(BaseCmd cmd, boolean isAdmin, boolean i
                 throw new InvalidParameterValueException(String.format("Users can not register Template with template type %s.", templateType));
             } else if (cmd instanceof UpdateTemplateCmd) {
                 throw new InvalidParameterValueException(String.format("Users can not update Template to template type %s.", templateType));
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/template/TemplateManagerImpl.java:2428]:
```suggestion
                throw new InvalidParameterValueException(String.format("Users can not update Template with template type %s.", templateType));
```

in sync with other msgs

Comment (weizhouapache) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java:2428]: @sureshanaparti 
`templateType` here means the new type of the template. would it be good to use `to` ?

Comment (sureshanaparti) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java:2428]: ok, got it, it's update to template type, fine.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test
