### PR TITLE
UI: ignore error host is already in the database when create a zone

### LINKED ISSUE #8597: UI: Host already in the database when adding host
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1 to 4.18.1
~~~

##### CONFIGURATION

Advanced Networking
KVM
##### OS / ENVIRONMENT

CentOS 7
Oracle Linux 9

##### SUMMARY

Error message shown when adding new host, but the host was added actually even with error message. This error happen since 4.17.1, likely there are some DB record influence the process and the API can't handle.

##### STEPS TO REPRODUCE

~~~
Add a new host into cluster

~~~

##### EXPECTED RESULTS

~~~
Host added without error.
~~~

##### ACTUAL RESULTS

~~~
Hosted added but with error.
~~~

```
2024-02-02 13:43:05,541 DEBUG [c.c.a.ApiServer] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) CIDRs from which account 'Account [{"accountName":"admin","id":2,"uuid":"9189844c-0005-11eb-92dc-52540044e551"}]' is allowed to perform API calls: 0.0.0.0/0,::/0
2024-02-02 13:43:05,543 INFO  [o.a.c.a.DynamicRoleBasedAPIAccessChecker] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Account [Account [{"accountName":"admin","id":2,"uuid":"9189844c-0005-11eb-92dc-52540044e551"}]] is Root Admin or Domain Admin, all APIs are allowed.
2024-02-02 13:43:05,545 INFO  [o.a.c.a.ProjectRoleBasedApiAccessChecker] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Account [admin] is Root Admin or Domain Admin, all APIs are allowed.
2024-02-02 13:43:05,546 DEBUG [o.a.c.a.StaticRoleBasedAPIAccessChecker] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) RoleService is enabled. We will use it instead of StaticRoleBasedAPIAccessChecker.
2024-02-02 13:43:05,547 INFO  [o.a.c.r.ApiRateLimitServiceImpl] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Account [{"accountName":"admin","uuid":"9189844c-0005-11eb-92dc-52540044e551"}] is Root Admin, in this case, API limit does not apply.
2024-02-02 13:43:05,550 WARN  [c.c.a.d.ParamGenericValidationWorker] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Received unknown parameters for command addHost. Unknown parameters : clustertype projectid
2024-02-02 13:43:05,552 INFO  [c.c.r.ResourceManagerImpl] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Trying to add a new host at http://compute-2.apac-1b.example.com in data center 14
2024-02-02 13:43:05,555 DEBUG [c.c.h.k.d.LibvirtServerDiscoverer] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7
2024-02-02 13:43:05,555 WARN  [c.c.h.k.d.LibvirtServerDiscoverer] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00)  can't setup agent, due to com.cloud.utils.exception.CloudRuntimeException: Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7 - Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7
2024-02-02 13:43:05,555 DEBUG [c.c.h.k.d.LibvirtServerDiscoverer] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00)  can't setup agent, due to com.cloud.utils.exception.CloudRuntimeException: Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7 - Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7
2024-02-02 13:43:05,556 DEBUG [c.c.r.ResourceManagerImpl] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Could not add host at [http://compute-2.apac-1b.example.com] with zone [14], pod [14] and cluster [11] due to: [ can't setup agent, due to com.cloud.utils.exception.CloudRuntimeException: Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7 - Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7].
2024-02-02 13:43:05,556 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Could not find exception: com.cloud.exception.DiscoveryException in error code list for exceptions
2024-02-02 13:43:05,556 WARN  [o.a.c.a.c.a.h.AddHostCmd] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Exception: 
2024-02-02 13:43:05,558 INFO  [c.c.a.ApiServer] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) Could not add host at [http://compute-2.apac-1b.example.com] with zone [14], pod [14] and cluster [11] due to: [ can't setup agent, due to com.cloud.utils.exception.CloudRuntimeException: Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7 - Skipping host 172.17.0.22 because 3f752e3a-b121-34d7-b98e-efa49c276445 is already in the database for resource 3f752e3a-b121-34d7-b98e-efa49c276445-LibvirtComputingResource with ID 350274d9-d7b1-4cdd-a2e6-fe5f6ee76ec7].
2024-02-02 13:43:05,558 DEBUG [c.c.a.ApiServlet] (qtp1437654187-1615:ctx-e10e9666 ctx-5839d082) (logid:e1b7ea00) ===END===  0:0:0:0:0:0:0:1 -- POST  command=addHost&response=json&projectid=e61c599d-76fb-4cbc-9179-a47b381f49a2
```

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #8597 

note
- I cannot reproduce the same issue that host is "already in the database". (https://github.com/apache/cloudstack/issues/9034#issuecomment-2092819989)
- I was able to reproduce the issue that "Unable to add host" by renaming /usr/sbin/kvm-ok on ubuntu 22.04 host. when I changed the string in this PR, the issue is ignored.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Review by rohityadavcloud — APPROVED** [review]

**Comment by vladimirpetrov** [comment]
@blueorangutan package

File: ui/src/views/infra/zone/ZoneWizardLaunchZone.vue [hunk 1]
```diff
@@ -2093,7 +2093,11 @@ export default {
           resolve()
         }).catch(error => {
           message = error.response.headers['x-description']
-          reject(message)
+          if (message.includes('is already in the database')) {
```
Comment (sureshanaparti) [inline ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: @weizhouapache Is this message coming for API response? Can check/correct the msg if required.

Comment (weizhouapache) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: yes @sureshanaparti 
it comes from the error message in API response.

```
plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/discoverer/HypervServerDiscoverer.java:                logger.debug("Skipping " + agentIp + " because " + guidWithTail + " is already in the database.");
plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/discoverer/XcpServerDiscoverer.java:                    logger.debug("Skipping " + record.address + " because " + record.uuid + " is already in the database.");
server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java:                        final String msg = "Skipping host " + agentIp + " because " + guid + " is already in the database for resource " + existingHost.getGuid() + " with ID " + existingHost.getUuid();
```

Comment (sureshanaparti) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: Ok, if already there, maybe do have to check any other param changes for that host and update?

Comment (weizhouapache) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: @sureshanaparti 
do you mean the param passed in the wizard and the param of the existing host ?

Comment (sureshanaparti) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: If already in database and added again, maybe we can show proper msg, something like Hosts already exists, re-added to the cluster.

Comment (weizhouapache) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: @sureshanaparti 
if host already exists, should we just ignore the error and skip the step ?

**Comment by rohityadavcloud** [comment]
Smoketests not required as this is strictly UI only change
@blueorangutan ui

File: ui/src/views/infra/zone/ZoneWizardLaunchZone.vue (hunk 1 above)
Comment (sureshanaparti) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: as discussed, better update the backend msg, so that it'll be in sync with ui and cmk.

Comment (weizhouapache) [reply ui/src/views/infra/zone/ZoneWizardLaunchZone.vue:2096]: @sureshanaparti 
I tested the following change (similar as others)
```
--- a/server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
+++ b/server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java
@@ -247,7 +247,7 @@ public abstract class LibvirtServerDiscoverer extends DiscovererBase implements
                     if (existingHost.getGuid().toLowerCase().startsWith(guid.toLowerCase())) {
                         final String msg = "Skipping host " + agentIp + " because " + guid + " is already in the database for resource " + existingHost.getGuid() + " with I
+D " + existingHost.getUuid();
                         logger.debug(msg);
-                        throw new CloudRuntimeException(msg);
+                        return null;
                     }
                 }
             }
```

unfortunately I still got an exception 
```
2024-06-25T10:36:29,785 INFO  [c.c.r.ResourceManagerImpl] (qtp1449605932-20:[ctx-7faf5626, ctx-697f7fe4, ctx-dc5eb50d]) (logid:94985073) Trying to add a new host at http://10.0.35.82 in data center 1
2024-06-25T10:36:29,789 DEBUG [c.c.h.k.d.KvmServerDiscoverer] (qtp1449605932-20:[ctx-7faf5626, ctx-697f7fe4, ctx-dc5eb50d]) (logid:94985073) Skipping host 10.0.35.82 because 5ba056d0-0318-3ccc-93a7-037cf61305e2 is already in the database for resource 5ba056d0-0318-3ccc-93a7-037cf61305e2-LibvirtComputingResource with ID e7f4f60c-76bd-4924-8f07-d41baee5e29a
2024-06-25T10:36:29,789 WARN  [c.c.r.ResourceManagerImpl] (qtp1449605932-20:[ctx-7faf5626, ctx-697f7fe4, ctx-dc5eb50d]) (logid:94985073) Cannot find the server resources at http://10.0.35.82
2024-06-25T10:36:29,791 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp1449605932-20:[ctx-7faf5626, ctx-697f7fe4, ctx-dc5eb50d]) (logid:94985073) Could not find exception: com.cloud.exception.DiscoveryException in error code list for exceptions
2024-06-25T10:36:29,792 WARN  [o.a.c.a.c.a.h.AddHostCmd] (qtp1449605932-20:[ctx-7faf5626, ctx-697f7fe4, ctx-dc5eb50d]) (logid:94985073) Exception: com.cloud.exception.DiscoveryException: Unable to add the host: Cannot find the server resources at http://10.0.35.82
    at com.cloud.resource.ResourceManagerImpl.discoverHostsFull(ResourceManagerImpl.java:894)
    at com.cloud.resource.ResourceManagerImpl.discoverHosts(ResourceManagerImpl.java:658)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
```

need some  investigation
