### PR TITLE
Linstor: fix create volume from snapshot on primary storage

### LINKED ISSUE #11451: LINSTOR create template from snapshot not working
### problem

Running the Linstor tests against the 4.21.0.0-rc3, I noticed that create template from snapshot is not working anymore.

Here is the log from the error:

```
2025-08-14 16:08:38,919 DEBUG [c.c.a.ApiServlet] (qtp1438988851-26:[ctx-9798b557]) (logid:f819b910) ===START===  192.168.125.1 -- GET  jobId=36685271-97a9-4b16-882f-bff865b5999d&command=queryAsyncJobResult&response=json&
2025-08-14 16:08:38,919 DEBUG [c.c.a.ApiServlet] (qtp1438988851-26:[ctx-9798b557]) (logid:f819b910) Two factor authentication is already verified for the user 2, so skipping
2025-08-14 16:08:38,921 DEBUG [c.c.a.ApiServer] (qtp1438988851-26:[ctx-9798b557, ctx-8c8c58ff]) (logid:f819b910) CIDRs from which account 'Account [{"accountName":"admin","id":2,"uuid":"073aa3df-7923-11f0-9598-525400000078"}]' is allowed to perform API calls: 0.0.0.0/0,::/0
2025-08-14 16:08:38,922 INFO  [o.a.c.a.DynamicRoleBasedAPIAccessChecker] (qtp1438988851-26:[ctx-9798b557, ctx-8c8c58ff]) (logid:f819b910) Account for user id 073ce01a-7923-11f0-9598-525400000078 is Root Admin or Domain Admin, all APIs are allowed.
2025-08-14 16:08:38,922 DEBUG [o.a.c.a.StaticRoleBasedAPIAccessChecker] (qtp1438988851-26:[ctx-9798b557, ctx-8c8c58ff]) (logid:f819b910) RoleService is enabled. We will use it instead of StaticRoleBasedAPIAccessChecker.
2025-08-14 16:08:38,922 DEBUG [o.a.c.r.ApiRateLimitServiceImpl] (qtp1438988851-26:[ctx-9798b557, ctx-8c8c58ff]) (logid:f819b910) API rate limiting is disabled. We will not use ApiRateLimitService.
2025-08-14 16:08:38,932 DEBUG [o.a.c.e.o.VolumeOrchestrator] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Found [0] snapshots [[]] that have checkpoints for volume with id [3].
2025-08-14 16:08:38,936 DEBUG [c.c.a.ApiServlet] (qtp1438988851-26:[ctx-9798b557, ctx-8c8c58ff]) (logid:f819b910) ===END===  192.168.125.1 -- GET  jobId=36685271-97a9-4b16-882f-bff865b5999d&command=queryAsyncJobResult&response=json&
2025-08-14 16:08:38,951 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) template Template {"format":"RAW","id":202,"name":"centos-test","uniqueName":"202-2-1cf8d6c7-4a47-3dcf-b97f-1b461217902d","uuid":"4cc7ad31-624e-49de-b5ca-c071672519f7"} with id 202 is already in store:ImageStore {"id":1,"name":"nfs:\/\/192.168.125.120\/export\/secondary","uuid":"b423238d-1f38-463d-9ec2-5b30a6f05d08"}, type: Image
2025-08-14 16:08:38,962 DEBUG [o.a.c.s.d.d.LinstorPrimaryDataStoreDriverImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) LinstorPrimaryDataStoreDriverImpl.canCopy: SNAPSHOT -> TEMPLATE
2025-08-14 16:08:38,965 DEBUG [o.a.c.e.o.VolumeOrchestrator] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Found [0] snapshots [[]] that have checkpoints for volume with id [3].
2025-08-14 16:08:38,972 DEBUG [o.a.c.s.m.AncientDataMotionStrategy] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) copyAsync inspecting src type SNAPSHOT copyAsync inspecting dest type TEMPLATE
2025-08-14 16:08:38,974 DEBUG [o.a.c.e.o.VolumeOrchestrator] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Found [0] snapshots [[]] that have checkpoints for volume with id [3].
2025-08-14 16:08:38,985 DEBUG [o.a.c.e.o.VolumeOrchestrator] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Found [0] snapshots [[]] that have checkpoints for volume with id [3].
2025-08-14 16:08:38,993 DEBUG [c.c.a.m.ClusteredAgentManagerImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Wait time setting on org.apache.cloudstack.storage.command.CopyCommand is 10800 seconds
2025-08-14 16:08:38,994 DEBUG [c.c.a.m.ClusteredAgentAttache] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Seq 5-8009933412255137826: Routed from 90520730730616
2025-08-14 16:08:38,994 DEBUG [c.c.a.t.Request] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Seq 5-8009933412255137826: Sending  { Cmd , MgmtId: 90520730730616, via: 5(s-2-VM), Ver: v1, Flags: 100011, [{"org.apache.cloudstack.storage.command.CopyCommand":{"srcTO":{"org.apache.cloudstack.storage.to.SnapshotObjectTO":{"path":"/dev/mapper/storage-cs--2ab552d2--9ef2--494d--9c1e--df1209ebe970_00000_cs--27ef9239--b408--40a9--9278--85f1dfda4674","volume":{"uuid":"2ab552d2-9ef2-494d-9c1e-df1209ebe970","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"3f90e70b-f6af-4ac9-8df4-5792fc477154","name":"Linstor","id":"1","poolType":"Linstor","host":"http://192.168.125.121:3370","path":"cloudstack","port":"3370","url":"Linstor://http://192.168.125.121:3370/cloudstack/?ROLE=Primary&STOREUUID=3f90e70b-f6af-4ac9-8df4-5792fc477154","isManaged":"false"}},"name":"ROOT-3","size":"(8.00 GB) 8589934592","path":"2ab552d2-9ef2-494d-9c1e-df1209ebe970","volumeId":"3","vmName":"i-2-3-VM","accountId":"2","format":"QCOW2","provisioningType":"THIN","poolId":"1","id":"3","deviceId":"0","hypervisorType":"KVM","directDownload":"false","deployAsIs":"false","checkpointPaths":[],"checkpointImageStoreUrls":[],"followRedirects":"false"},"dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"3f90e70b-f6af-4ac9-8df4-5792fc477154","name":"Linstor","id":"1","poolType":"Linstor","host":"http://192.168.125.121:3370","path":"cloudstack","port":"3370","url":"Linstor://http://192.168.125.121:3370/cloudstack/?ROLE=Primary&STOREUUID=3f90e70b-f6af-4ac9-8df4-5792fc477154","isManaged":"false"}},"kvmIncrementalSnapshot":"false","vmName":"i-2-3-VM","name":"test","hypervisorType":"KVM","id":"1","quiescevm":"false","physicalSize":"0","accountId":"2","followRedirects":"false"}},"destTO":{"org.apache.cloudstack.storage.to.TemplateObjectTO":{"path":"template/tmpl/2/202","uuid":"4cc7ad31-624e-49de-b5ca-c071672519f7","id":"202","format":"RAW","accountId":"2","hvm":"true","displayText":"dfasdf","imageDataStore":{"com.cloud.agent.api.to.NfsTO":{"_url":"nfs://192.168.125.120/export/secondary","_role":"Image"}},"name":"202-2-1cf8d6c7-4a47-3dcf-b97f-1b461217902d","hypervisorType":"KVM","bootable":"false","uniqueName":"202-2-1cf8d6c7-4a47-3dcf-b97f-1b461217902d","directDownload":"false","deployAsIs":"false","followRedirects":"false"}},"executeInSequence":"false","options":{},"options2":{},"wait":"10800","bypassHostMaintenance":"false"}}] }
2025-08-14 16:08:39,040 DEBUG [c.c.a.t.Request] (AgentManager-Handler-6:[]) (logid:) Seq 5-8009933412255137826: Processing:  { Ans: , MgmtId: 90520730730616, via: 5, Ver: v1, Flags: 10, [{"com.cloud.agent.api.UnsupportedAnswer":{"result":"false","details":"Unsupported command issued: org.apache.cloudstack.storage.command.CopyCommand.  Are you sure you got the right type of server?","wait":"0","bypassHostMaintenance":"false"}}] }
2025-08-14 16:08:39,040 DEBUG [c.c.a.t.Request] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Seq 5-8009933412255137826: Received:  { Ans: , MgmtId: 90520730730616, via: 5(s-2-VM), Ver: v1, Flags: 10, { UnsupportedAnswer } }
2025-08-14 16:08:39,040 WARN  [c.c.a.m.ClusteredAgentManagerImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Unsupported Command: Unsupported command issued: org.apache.cloudstack.storage.command.CopyCommand.  Are you sure you got the right type of server?
2025-08-14 16:08:39,046 DEBUG [c.c.t.TemplateManagerImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Failed to create templateUnsupported command issued: org.apache.cloudstack.storage.command.CopyCommand.  Are you sure you got the right type of server?
2025-08-14 16:08:39,051 DEBUG [c.c.r.ResourceLimitManagerImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Updating resource Type = template count for Account with id = 2 Operation = decreasing Amount = 1
2025-08-14 16:08:39,064 DEBUG [c.c.r.ResourceLimitManagerImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21, ctx-37aa414a]) (logid:36685271) Updating resource Type = secondary_storage count for Account with id = 2 Operation = decreasing Amount = (8.00 GB) 8589934592
2025-08-14 16:08:39,087 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-11:[ctx-38f6d4e7, job-21]) (logid:36685271) Unexpected exception while executing org.apache.cloudstack.api.command.admin.template.CreateTemplateCmdByAdmin com.cloud.utils.exception.CloudRuntimeException: Failed to create templateUnsupported command issued: org.apache.cloudstack.storage.command.CopyCommand.  Are you sure you got the right type of server?
	at com.cloud.template.TemplateManagerImpl.createPrivateTemplate(TemplateManagerImpl.java:1750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:109)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy3/jdk.proxy3.$Proxy259.createPrivateTemplate(Unknown Source)
	at org.apache.cloudstack.api.command.user.template.CreateTemplateCmd.execute(CreateTemplateCmd.java:305)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:173)
	at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:110)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:689)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:637)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

2025-08-14 16:08:39,088 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-11:[ctx-38f6d4e7, job-21]) (logid:36685271) Complete async job-21, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"530","errortext":"Failed to create templateUnsupported command issued: org.apache.cloudstack.storage.command.CopyCommand.  Are you sure you got the right type of server?"}
```

### versions

4.21.0.0-rc3, linstor primary storage

### The steps to reproduce the bug

1. create/use primary storage Linstor
2. create an instance
3. create a volume snapshot of the instance
4. use create template from snapshot

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by Kukunin**
### Context

I run a private cloud using 4.22 CloudStack, with Linstor primary storage, Kubernetes, CloudStack CSI driver with additional `registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1` sidecar and `snapshot-controller`. 

I wanted to duplicate PVC from kubectl, by creating a snapshot and restoring another PVC from the snapshot. The main problem is that the snapshot wanted to be copied to SecondaryStorage, which is not what I wanted. Secondary storage is slow and outside of the network, so transferring 1TB volume is long and silly. I got a chain of errors, identified those, and prepared a patch that solved my issues. I built and pushed only `cloud-plugin-storage-volume-linstor-4.22.0.0.jar` to my servers, and after restarting both management / agent services, the PVC copy via snapshots worked fine. Also I modified the following cloudstack settings:

| Setting | Value   | Was     | Purpose                       |
|--------------------------------|---------|---------|----------------------------------------------------------|
| kvm.snapshot.enabled           | true    | false   | Allow snapshots on running KVM VMs                       |
| snapshot.backup.to.secondary   | false   | true    | Skip secondary storage backup for  snapshots              |
| lin.backup.snapshots           | false   | false   | Linstor-specific: keep snapshots on  primary storage only |

### Description

When creating a volume from a snapshot on Linstor primary storage (with `lin.backup.snapshots=false`), the operation fails with:

> Only the following image types are currently supported: VHD, OVA, QCOW2, RAW (for PowerFlex and FiberChannel)

**Root cause:** The Linstor driver does not handle SNAPSHOT → VOLUME in its `canCopy()`/`copyAsync()` methods. This causes `DataMotionServiceImpl` to fall through to `StorageSystemDataMotionStrategy` (selected because Linstor advertises `STORAGE_SYSTEM_SNAPSHOT=true`). That strategy's `verifyFormatWithPoolType()` rejects RAW format for Linstor pools, since RAW is only allowed for PowerFlex and FiberChannel.

Additionally, `VolumeOrchestrator.createVolumeFromSnapshot()` attempts to back up the snapshot to secondary storage when the storage plugin does not advertise `CAN_CREATE_TEMPLATE_FROM_SNAPSHOT`. This backup fails because the snapshot only exists on Linstor primary storage.

**Fix:**

- Add `CAN_CREATE_TEMPLATE_FROM_SNAPSHOT` capability so the orchestrator skips the backup-to-secondary path
- Add `canCopySnapshotToVolumeCond()` to match SNAPSHOT → VOLUME when both are on the same Linstor primary store
- Wire it into `canCopy()` to intercept at `DataMotionServiceImpl` before strategy selection, bypassing `StorageSystemDataMotionStrategy` entirely
- Implement `copySnapshotToVolume()` which delegates to the existing `createResourceFromSnapshot()` for native Linstor snapshot restore

This follows the same pattern used by the StorPool plugin, which handles SNAPSHOT → VOLUME directly in its driver rather than going through `StorageSystemDataMotionStrategy`.

Fixes: #11451

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

**Unit tests:** 5 new tests added to `LinstorPrimaryDataStoreDriverImplTest`:
- `testGetCapabilitiesIncludesCreateTemplateFromSnapshot` — verifies the capability is advertised
- `testCanCopySnapshotToVolumeOnSamePrimary` — verifies `canCopy()` returns true for SNAPSHOT → VOLUME on same Linstor primary
- `testCanCopySnapshotToVolumeRejectsNonLinstor` — verifies `canCopy()` returns false for non-Linstor storage
- `testCanCopySnapshotToVolumeRejectsCrossPrimary` — verifies `canCopy()` returns false across different primary stores
- `testCanCopySnapshotToVolumeRejectsImageDest` — verifies `canCopy()` returns false when destination is Image store

**Integration test:** Tested on CloudStack 4.22 with Linstor LVM_THIN storage (DRBD-replicated across 3 nodes), creating a volume from a 1TB CNPG Postgres database snapshot via `createVolume` API:
- Volume creates successfully with state=Ready and correct UUID path
- Volume deletes cleanly (both CloudStack DB and Linstor resource)
- Linstor resource is properly created via native snapshot restore (`resourceSnapshotRestore` API)

#### How did you try to break this feature and the system with this change?

- Verified that the existing `canCopy()` paths (SNAPSHOT→SNAPSHOT to Image, TEMPLATE→TEMPLATE, VOLUME→VOLUME/TEMPLATE) are not affected by the new condition being checked first
- Verified cross-primary-store and non-Linstor scenarios are rejected
- Verified volume path is stored as UUID (not device path) to ensure delete operations work correctly
- The change is confined to the Linstor plugin — no modifications to shared CloudStack code

### CODE REVIEW

File: plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java [hunk 1]
```diff
@@ -766,14 +777,37 @@ public boolean canCopy(DataObject srcData, DataObject dstData)
...
+            String rscName = LinstorUtil.RSC_PREFIX + volumeInfo.getUuid();
+            createResourceFromSnapshot(snapshotInfo.getId(), rscName, storagePoolVO);
+
+            VolumeObjectTO volumeTO = (VolumeObjectTO) volumeInfo.getTO();
+            volumeTO.setPath(volumeInfo.getUuid());
+            volumeTO.setSize(volumeInfo.getSize());
+            answer = new CopyCmdAnswer(volumeTO);
+        } catch (Exception e) {
+            errMsg = "Failed to create volume from snapshot: " + e.getMessage();
+            logger.error(errMsg, e);
```
Comment (rp-) [inline plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java]: Here also a CloudRuntimeException should be thrown, otherwise CloudStack will not notice something went wrong.

**Review by rp- — CHANGES_REQUESTED** [review]
I'll still need to run my testsuite against it, but I guess it will work.

File: plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java (hunk 1 above)
Comment (Kukunin) [reply plugins/storage/volume/linstor/src/main/java/org/apache/cloudstack/storage/datastore/driver/LinstorPrimaryDataStoreDriverImpl.java]: thank you. I addressed this

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by rp-** [comment]
I think the build error comes from a `UnusedImport` checkstyle error.

But I have also bad news as this change broke the `test_10_create_template_from_snapshot`
[TV2SA0.tar.gz](https://github.com/user-attachments/files/26931048/TV2SA0.tar.gz)

I have appened the test logs

**Comment by sureshanaparti** [comment]
@Kukunin can you fix the build error.

**Comment by Kukunin** [comment]
@blueorangutan package

@sureshanaparti thank you for the feedback. Here I tried to fix this.

**Review by rp- — APPROVED** [review]
Tests ran through now, LGTM

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test
