### PR TITLE
api,server: encryptformat in volume response

### LINKED ISSUE #9014: add `encryptionformat` to volume reponse for admins
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API/UI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

On requests like listVolumes or updateVolume the output should include encryption format (at least for admins)
see the discussion in https://github.com/apache/cloudstack/pull/8643#issuecomment-2085073967
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9014

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

File: server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java [hunk 1]
```diff
@@ -275,6 +275,12 @@ public class VolumeJoinVO extends BaseViewWithTagInformationVO implements Contro
     @Column(name = "external_uuid")
     private String externalUuid = null;
 
+    @Column(name = "passphrase_id")
+    private Long passphraseId;
```
[the remark this answers is not in the document]
Comment (shwstppr) [reply server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java:279]: yes @weizhouapache `passphrase_id` is not been used in this PR. I've added in the volume_view and VO for any future use as adding new column in view would need another DB change. These changes can be removed if needed

[the remark this answers is not in the document]
Comment (JoaoJandre) [reply server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java:279]: If it's not being used there is no reason to add it. If future PRs need they can be added then.

File: server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java [hunk 2]
```diff
@@ -610,6 +616,14 @@ public void setExternalUuid(String externalUuid) {
         this.externalUuid = externalUuid;
     }
 
+    public Long getPassphraseId() {
+        return passphraseId;
+    }
+
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java:622]:
```suggestion
```

File: server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (shwstppr) [reply server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java]: @weizhouapache I've removed `passphrase_id` from JoinVO

[the remark this answers is not in the document]
Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/query/vo/VolumeJoinVO.java]: > @weizhouapache I've removed `passphrase_id` from JoinVO

Thanks @shwstppr

**Comment by weizhouapache** [comment]
@blueorangutan package

File: engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql [hunk 3]
```diff
@@ -39,6 +39,8 @@ SELECT
     `volumes`.`path` AS `path`,
     `volumes`.`chain_info` AS `chain_info`,
     `volumes`.`external_uuid` AS `external_uuid`,
+    `volumes`.`passphrase_id` AS `passphrase_id`,
```
Comment (weizhouapache) [inline engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql:42]:
```suggestion
```

**Comment by DaanHoogland** [comment]
@JoaoJandre , are your concerns met?

File: engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql (hunk 3 above)
Comment (JoaoJandre) [reply engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql:42]: > @JoaoJandre , are your concerns met?

@DaanHoogland no, we should apply @weizhouapache's suggestion here, no need to have this view changed for now.

**Review by kiranchavala — APPROVED** [review]
LGTM, In the listVolumes api the response contains

"encryptformat": "luks",

```
(cmk) > list volumes id=68151b4c-5967-4ce8-b747-911ad7f33c73
{
  "count": 1,
  "volume": [
    {
      "account": "admin",
      "clusterid": "f9bf37c6-50a0-4cb5-ae72-5e64baa32cd2",
      "clustername": "p1-c1",
      "created": "2024-06-10T13:00:47+0000",
      "destroyed": false,
      "deviceid": 1,
      "diskioread": 0,
      "diskiowrite": 0,
      "diskkbsread": 0,
      "diskkbswrite": 0,
      "diskofferingdisplaytext": "encrypted-offering",
      "diskofferingid": "c401faa2-6ab7-479c-aa07-46b5786cbbe0",
      "diskofferingname": "encrypted-offering",
      "displayvolume": true,
      "domain": "ROOT",
      "domainid": "6917ae26-2724-11ef-9e8f-1e008b00026c",
      "encryptformat": "luks",
      "hasannotations": false,
      "hypervisor": "KVM",
      "id": "68151b4c-5967-4ce8-b747-911ad7f33c73",
      "isextractable": true,
      "name": "DATA-3",
      "path": "68151b4c-5967-4ce8-b747-911ad7f33c73",
      "physicalsize": 2359296,
      "podid": "c46f480b-210f-455d-a31b-93eb6b8da5ed",
      "podname": "Pod1",
      "provisioningtype": "thin",
      "quiescevm": false,
      "size": 10737418240,
      "state": "Ready",
      "storage": "ref-trl-6784-k-Mr8-kiran-chavala-kvm-pri1",
      "storageid": "299c9a7d-241c-3f54-b546-12a6bae2c537",
      "storagetype": "shared",
      "supportsstoragesnapshot": false,
      "tags": [],
      "type": "DATADISK",
      "utilization": "0.0%",
      "virtualmachineid": "f3ceea8a-376a-4132-a64c-57f31008eda3",
      "virtualsize": 10737418240,
      "vmdisplayname": "vm1",
      "vmname": "vm1",
      "vmstate": "Running",
      "vmtype": "User",
      "zoneid": "7f79d7fa-4ad3-4c00-87a7-2e7e58180757",
      "zonename": "ref-trl-6784-k-Mr8-kiran-chavala"
    }
  ]
}
```

File: engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql [hunk 4]
```diff
@@ -39,6 +39,8 @@ SELECT
...
+    `volumes`.`encrypt_format` AS `encrypt_format`,
```
Comment (shwstppr) [inline engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql:43]:
```suggestion
    `volumes`.`encrypt_format` AS `encrypt_format`,
```

**Comment by shwstppr** [comment]
@blueorangutan package

File: engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql (hunk 3 above)
Comment (DaanHoogland) [reply engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql]: sorry @JoaoJandre , I think we crossed messages (with Kiran in the mix) here. I don't see `passphrase_id` in the PR. so that means it is applied, right?

If not we'll need to create a new PR.

Comment (JoaoJandre) [reply engine/schema/src/main/resources/META-INF/db/views/cloud.volume_view.sql]: Yes, @DaanHoogland, it was applied in the last commit, before merging.
