### PR TITLE
api/server: support deploy-as-is template as VNF template

### LINKED ISSUE #12186: vnf: failure while deploying appliance via deploy-as-is VNF template
### problem

Deploying VN appliance using a deploy-as-is VNF template for VMware fails.

Image

### versions

4.20.1
Must be an issue with some lower versions as well

### The steps to reproduce the bug

1. Register a VNF deploy-as-is template for VMware
2. Deploy the appliance using Deploy VNF appliance wizard while selecting networks
3. Observe error deployment fails with error - `VNF nics list is empty`

### What to do about it?

Fix the case. Server may need to properly check the param `nicnetworklist`

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #12186 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

File: api/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateUtils.java [hunk 1]
```diff
@@ -124,6 +125,9 @@ public static void validateVnfNics(List<VNF.VnfNic> nicsList) {
     public static void validateApiCommandParams(BaseCmd cmd, VirtualMachineTemplate template) {
         if (cmd instanceof RegisterVnfTemplateCmd) {
             RegisterVnfTemplateCmd registerCmd = (RegisterVnfTemplateCmd) cmd;
+            if (registerCmd.isDeployAsIs() && CollectionUtils.isNotEmpty(registerCmd.getVnfNics())) {
+                throw new InvalidParameterValueException("VNF Template cannot be registered with VNF nics as Template settings are read from OVA.");
+            }
```
Comment (DaanHoogland) [inline api/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateUtils.java:130]: Do we want this always to be true? I could imagine a VNF getting a default gateway… Probably my lack of knowledge. I hope this is in the documentation.

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 2]
```diff
@@ -6127,7 +6127,11 @@ public UserVm createVirtualMachine(DeployVMCmd cmd) throws InsufficientCapacityE
...
         if (TemplateType.VNF.equals(template.getTemplateType())) {
-            vnfTemplateManager.validateVnfApplianceNics(template, cmd.getNetworkIds());
+            if (template.isDeployAsIs()) {
+                vnfTemplateManager.validateVnfApplianceNetworksMap(template, cmd.getVmNetworkMap());
+            } else {
+                vnfTemplateManager.validateVnfApplianceNics(template, cmd.getNetworkIds());
+            }
         } else if (cmd instanceof DeployVnfApplianceCmd) {
             throw new InvalidParameterValueException("Can't deploy VNF appliance from a non-VNF template");
         }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:6133]: can we extract this as a new validation method?

File: server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java [hunk 3]
```diff
@@ -213,6 +216,19 @@ public void validateVnfApplianceNics(VirtualMachineTemplate template, List<Long>
...
     }
 
+    @Override
+    public void validateVnfApplianceNetworksMap(VirtualMachineTemplate template, Map<Integer, Long> vmNetworkMap) {
+        if (MapUtils.isEmpty(vmNetworkMap)) {
+            throw new InvalidParameterValueException("VNF networks map is empty");
+        }
+        List<VnfTemplateNicVO> vnfNics = vnfTemplateNicDao.listByTemplateId(template.getId());
+        for (VnfTemplateNicVO vnfNic : vnfNics) {
+            if (vnfNic.isRequired() && vmNetworkMap.size() <= vnfNic.getDeviceId()) {
```
[the remark this answers is not in the document]
Comment (nvazquez) [reply server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java:229]: +1

File: server/src/main/java/com/cloud/template/TemplateManagerImpl.java [hunk 4]
```diff
@@ -2172,6 +2176,11 @@ private VMTemplateVO updateTemplateOrIso(BaseUpdateTemplateOrIsoCmd cmd) {
             templateType = validateTemplateType(cmd, isAdmin, template.isCrossZones());
             if (cmd instanceof UpdateVnfTemplateCmd) {
                 VnfTemplateUtils.validateApiCommandParams(cmd, template);
+                UpdateVnfTemplateCmd updateCmd = (UpdateVnfTemplateCmd) cmd;
+                if (template.isDeployAsIs() && CollectionUtils.isNotEmpty(updateCmd.getVnfNics())) {
```
Comment (nvazquez) [inline server/src/main/java/com/cloud/template/TemplateManagerImpl.java:2180]: Why is this parameter allowed on update but not on VM creation? (https://github.com/apache/cloudstack/pull/12499/files#diff-f5ab861d900497f6f7c83d03a840a7994f407c2dd52c237a4b560aaf9e75c202R128)

Comment (weizhouapache) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java:2180]: @nvazquez 
when register a deploy-as-is template, the template NICs are not available until the template is downloaded successfully. 
I think it is better that user configures VNF nics only when template NICs are fetched from OVA template.

File: api/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateUtils.java (hunk 1 above)
Comment (weizhouapache) [reply api/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateUtils.java:130]:
```suggestion
            if (registerCmd.isDeployAsIs() && CollectionUtils.isNotEmpty(registerCmd.getVnfNics())) {
                throw new InvalidParameterValueException("VNF nics cannot be specified when register a deploy-as-is Template. Please wait until Template settings are read from OVA.");
            }
```

Comment (weizhouapache) [reply api/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateUtils.java:130]: is it clear now ? @DaanHoogland

File: server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (weizhouapache) [reply server/src/main/java/org/apache/cloudstack/storage/template/VnfTemplateManagerImpl.java:229]: @nvazquez 
I have applied the changes, but then reverted it. as I found that in `vmNetworkMap`, the keys do not start with 0 (device IDs are 0,1,2...)

**Comment by RosiKyu** [comment]
**NOTE** https://github.com/apache/cloudstack/pull/12436#issuecomment-3784052907 -> check tooltip fix while verifying this PR

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
thanks @DaanHoogland 

@nvazquez can you please review ? thanks

**Comment by weizhouapache** [comment]
@RosiKyu thanks for the testing

@nvazquez can you review ? thanks
