### PR TITLE
ui: fix test delivery params in create webhook form

### LINKED ISSUE #12317: UI: Create webhook form test delivery not honoring SSL verification; wrong content-type
### problem

When creating a Webhook, CloudStack sends a test delivery. Currently it is sending plain text and not honoring SSL verification flag

### versions

4.20+

### The steps to reproduce the bug

1. Go to create webhook form, enter values for payload url
2. On the server which is listening webhook, observe test payload with plain text data - `true` and plain/text as Content-Type
3. SSL verification flag is also not correctly honored for the test delivery
...

### What to do about it?

Form should send a JSON payload as many webhook integrations strictly expect Content-Type as application/json.

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #12317

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

#### How did you try to break this feature and the system with this change?

Without change:

```
INFO:root:POST request,
Path: /
Headers:
X-CS-Event-ID: 35a50f0c-875f-4bcb-961a-cfe9c009350e
X-CS-Event: TEST.WEBHOOK
User-Agent: CS-Hookshot/018af4b7-df21-11f0-ac67-a02942fcdd70
Content-Length: 4
Content-Type: text/plain; charset=ISO-8859-1
Host: 192.168.1.15:8888
Connection: Keep-Alive
Accept-Encoding: gzip,deflate



Body:
True
```

With change:

```
INFO:root:POST request,
Path: /
Headers:
X-CS-Event-ID: 0737d4b9-2a86-4680-bdee-499fb47607b6
X-CS-Event: TEST.WEBHOOK
User-Agent: CS-Hookshot/018af4b7-df21-11f0-ac67-a02942fcdd70
Content-Length: 26
Content-Type: application/json; charset=UTF-8
Host: 192.168.1.15:8888
Connection: Keep-Alive
Accept-Encoding: gzip,deflate



Body:
{'CloudStack': 'works!'}
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

File: ui/src/views/tools/CreateWebhook.vue [hunk 1]
```diff
@@ -135,7 +135,7 @@
         <test-webhook-delivery-view
           ref="dispatchview"
           :payloadUrl="form.payloadurl"
-          :sslVerification="form.sslverification"
+          :sslVerification="isPayloadUrlHttps && form.sslverification"
```
Comment (DaanHoogland) [inline ui/src/views/tools/CreateWebhook.vue:138]: should this be || instead of &&?

Comment (shwstppr) [reply ui/src/views/tools/CreateWebhook.vue:138]: no @DaanHoogland. SSL option in the form is shown only for HTTPS urls

**Comment by kiranchavala** [comment]
@blueorangutan package
