### PR TITLE
kvm: use preallocation option for fat disk resize

### LINKED ISSUE #10589: Image resize for fat type of disk does not preallocate additional space
### problem

Currently (v.4.20.0.0) I see that sparse and fat disk types result in the same local disk format/size/type.
After digging into it I found the following flow for fat disks:
```
qemu-img create -o preallocation=full -f qcow2 newdisk template_size
qemu-img convert -O qcow2 -o preallocation=full -U --image-opts driver=qcow2,file.filename=template_file newdisk
qemu-img resize newdisk newsize
```
as a result new disk size is set to newsize, but its actual disk size is just of template_size
To be honest I see no reason to do `create` at all, it's overwritten by convert.
And to have fat newdisk there should be `--preallocation=full` in resize command too
```
qemu-img resize --preallocation=full newdisk newsize
```
This affects disk performance. In our CI environment CS disk becomes very fragmented, `qemu-img map` shows some 10K entries.
Also please consider using preallocated raw disks in place of preallocated qcow

Thanks,
Alex.

### versions

CloudStack 4.20.0.0
Ubuntu 22.04.5 LTS
QEMU 1:6.2+dfsg-2ubuntu6.24
libvirt 8.0.0-1ubuntu7.10

### The steps to reproduce the bug

1. Create VM with large fat disk from small template
2. Check qemu-img info to see virtual size is correct according to 1. but disk size is still of original template

### What to do about it?

Add `--preallocation=full` to resize command for fat disk
Use raw instead of qcow

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #10589

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Preallocation flag added after changes,

```
2025-11-05 11:47:33,315 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Executing command [qemu-img create -o preallocation=full -f qcow2 /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 8589934592 ].
2025-11-05 11:49:07,780 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Successfully executed process [476300] for command [qemu-img create -o preallocation=full -f qcow2 /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 8589934592 ].
2025-11-05 11:49:07,781 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Executing command [qemu-img info -U /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 ].
2025-11-05 11:49:07,805 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Successfully executed process [476358] for command [qemu-img info -U /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 ].
2025-11-05 11:49:07,822 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Executing command [qemu-img convert -O qcow2 -o preallocation=full -U --image-opts driver=qcow2,file.filename=/mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/0abce4b6-b562-11f0-9bc2-1e008f00039b /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 ].
2025-11-05 11:50:49,386 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Successfully executed process [476361] for command [qemu-img convert -O qcow2 -o preallocation=full -U --image-opts driver=qcow2,file.filename=/mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/0abce4b6-b562-11f0-9bc2-1e008f00039b /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 ].
2025-11-05 11:50:49,387 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Executing command [qemu-img resize -o preallocation=full /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 10737418240 ].
2025-11-05 11:50:49,395 WARN  [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Execution of process [476480] for command [qemu-img resize -o preallocation=full /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 10737418240 ] failed.
2025-11-05 11:50:49,395 DEBUG [utils.script.Script] (AgentRequest-Handler-4:[]) (logid:729511e8) Exit value of process [476480] for command [qemu-img resize -o preallocation=full /mnt/ea3a10a7-49cb-3d72-bcc3-dec41ebecb7a/6e320e64-0621-43f5-ac4c-9a0f60201f03 10737418240 ] is [1].
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgTest.java [hunk 1]
```diff
@@ -130,8 +134,7 @@ public void testCreateWithSecretObject() throws QemuImgException, LibvirtExcepti
     public void testCreateSparseVolume() throws QemuImgException, LibvirtException {
         String filename = "/tmp/" + UUID.randomUUID() + ".qcow2";
 
-        /* 10TB virtual_size */
-        long size = 10995116277760l;
+        long size = 10 * 1024 * 1024L;
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgTest.java:152]: this is a factor 1024 smaller than before, is that intended?

Comment (shwstppr) [reply plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/qemu/QemuImgTest.java:152]: Yes, because earlier this test class was marked to ignore and this particular test creates a real file

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by RosiKyu** [comment]
@blueorangutan test

**Comment by RosiKyu** [comment]
@blueorangutan test

**Review by RosiKyu — CHANGES_REQUESTED** [review]
@shwstppr , I tested the PR and found an issue with the resize preallocation syntax.

```
2025-12-11 19:18:19,665 DEBUG [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:faa75368) Executing command [qemu-img resize -o preallocation=full /mnt/c79e69a9-87c1-385e-a0c4-f9db885fe205/202472b0-0936-49b8-ba16-11cd5f2956fc 10737418240 ].
2025-12-11 19:18:19,676 WARN  [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:faa75368) Execution of process [85614] for command [qemu-img resize -o preallocation=full /mnt/c79e69a9-87c1-385e-a0c4-f9db885fe205/202472b0-0936-49b8-ba16-11cd5f2956fc 10737418240 ] failed.
2025-12-11 19:18:19,676 DEBUG [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:faa75368) Exit value of process [85614] for command [qemu-img resize -o preallocation=full /mnt/c79e69a9-87c1-385e-a0c4-f9db885fe205/202472b0-0936-49b8-ba16-11cd5f2956fc 10737418240 ] is [1].
2025-12-11 19:18:19,676 WARN  [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:faa75368) Process [85614] for command [qemu-img resize -o preallocation=full /mnt/c79e69a9-87c1-385e-a0c4-f9db885fe205/202472b0-0936-49b8-ba16-11cd5f2956fc 10737418240 ] encountered the error: [qemu-img: unrecognized option '-o'Try 'qemu-img --help' for more information].
```

The `qemu-img resize` command fails because it uses `-o preallocation=full`, but `qemu-img resize` requires `--preallocation=full` as a standalone flag.

**Steps to Reproduce:**

1. Register small template 
2. Create service offering with FAT provisioning and 10GB root disk
3. Deploy VM using the template and service offering
4. Check agent logs on KVM host

**Actual Result:** The resize command fails with exit code 1. The disk appears correctly preallocated only because `qemu-img create` already created it at full target size before the resize was attempted.

```
[root@ref-trl-10368-k-Mol9-rositsa-kyuchukova-kvm1 ~]# qemu-img create -f qcow2 -o preallocation=full /root/test-resize-proof.qcow2 1G
Formatting '/root/test-resize-proof.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off preallocation=full compression_type=zlib size=1073741824 lazy_refcounts=off refcount_bits=16
[root@ref-trl-10368-k-Mol9-rositsa-kyuchukova-kvm1 ~]# ls -lsh /root/test-resize-proof.qcow2
1.1G -rw-r--r--. 1 root root 1.1G Dec 12 09:01 /root/test-resize-proof.qcow2
```

Incorrect synthax:

```
[root@ref-trl-10368-k-Mol9-rositsa-kyuchukova-kvm1 ~]# qemu-img resize -o preallocation=full /root/test-resize-proof.qcow2 5G
qemu-img: unrecognized option '-o'
Try 'qemu-img --help' for more information
[root@ref-trl-10368-k-Mol9-rositsa-kyuchukova-kvm1 ~]# ls -lsh /root/test-resize-proof.qcow2
1.1G -rw-r--r--. 1 root root 1.1G Dec 12 09:01 /root/test-resize-proof.qcow2

```

Correct synthax: 

```
[root@ref-trl-10368-k-Mol9-rositsa-kyuchukova-kvm1 ~]# qemu-img resize --preallocation=full /root/test-resize-proof.qcow2 5G
Image resized.
[root@ref-trl-10368-k-Mol9-rositsa-kyuchukova-kvm1 ~]# ls -lsh /root/test-resize-proof.qcow2
5.1G -rw-r--r--. 1 root root 5.1G Dec 12 09:02 /root/test-resize-proof.qcow2
```

**Comment by shwstppr** [comment]
Thanks @RosiKyu for the tests. I've added the change to fix params

@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
thanks @RosiKyu for testing!

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@shwstppr , can you look at the remaining regression test failure. The title suggests it is related.

**Comment by DaanHoogland** [comment]
> @shwstppr , can you look at the remaining regression test failure. The title suggests it is related.

maybe not but, it is also in https://github.com/apache/cloudstack/pull/11962#issuecomment-3663569703 (definately not related.

**Comment by shwstppr** [comment]
@DaanHoogland looked into the test logs, failure is not related,

```
jobresult : {errorcode : 530, errortext : "Resource limits prevent scaling the cluster: Maximum amount of resources of Type = \'cpu\', tag = \'null\' for Account Name = test-a-TestKubernetesCluster-LKO3MF in Domain Id = 1 is exceeded: Account Resource Limit = 40, Current Account Resource Amount = 4, Current Account Resource Reservation = 0, Requested Resource Amount = 2000."}
```
