### PR TITLE
ui: fix add network offering for vpc

### LINKED ISSUE #5807: UI: Add network offering form not showing "System offering for router" for VPC and provider list is not getting updated on VPC toggle
I've observed 2 issues
1. When trying to create a VPC network offering, option to select "System offering for router" is missing. In case of normal networking offering it is showing.
2. When VPC toggle button turns on and off, supported providers list is updating dynamically, we had to start a new "Add network offering" form.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15, 4.16, main
~~~

##### STEPS TO REPRODUCE

~~~
1. Click "Add network offering"
2. Turn On VPC toggle button 
3. Select any supported services and provider as "VpcVirtualRouter", the "Select Offering for Router" drop down is missing. 
4. To see how it looks, start a fresh "Add network offering" form and select any service with provider as "Virtual Router", we can see the "Select Offering for Router" dropdown like below 
~~~
image
~~~
1. Click "Add network offering"
2. Keep VPC toggle button off
3. Select DNS service and provider "Virtual Router"
4. Turn On VPC toggle button
5. Try to change the DNS provider to "VpcVirtualRouter", we could not do that. This is working fine in 4.15 but not in 4.16 and main.
~~~
image

##### EXPECTED RESULTS

~~~
1. Click "Add network offering"
2. Turn On VPC toggle button 
3. Select any supported services and provider as "VpcVirtualRouter", we should see the "Select Offering for Router" dropdown like below 
~~~
image

~~~
1. Click "Add network offering"
2. Keep VPC toggle button off
3. Select DNS service and provider "Virtual Router"
4. Turn On VPC toggle button
5. Try to change the DNS provider to "VpcVirtualRouter", we should be able see updated list and select "VpcVirtualRouter"
~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes issues with form related to supported services provider and router service offering when offering to be created for VPC.

Fixes #5807

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

File: ui/src/components/CheckBoxSelectPair.vue [hunk 1]
```diff
@@ -97,12 +96,21 @@ export default {
...
     }
   },
   created () {
     this.checked = this.defaultCheckBoxValue
   },
+  watch: {
+    selectOptions () {
+      clearTimeout(this.selectOptionsTimer)
+      this.selectOptionsTimer = setTimeout(() => {
+        this.handleSelectOptionsUpdated()
```
Comment (utchoang) [inline ui/src/components/CheckBoxSelectPair.vue:110]: @shwstppr In my opinion, instead of changing the choice of options according to VPC, we can reset those options to null/blank to avoid repetition causing form crashes. What do you think?

**Comment by utchoang** [comment]
@shwstppr I have a PR to fix the problem you have when changing the VPC selection. you can take a look and merge it here. Thanks

**Comment by utchoang** [comment]
@blueorangutan ui

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by Pearl1594** [comment]
@shwstppr I notice there to be an issue when we toggle the VPC switch in the network offering form, i.e., when it is turned on, and we check the services to be supported, it still lists VirtualRouter:

image

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@Pearl1594 can you please try now

**Review by Pearl1594 — APPROVED** [review]
Thanks @shwstppr. Works as expected.

**Review by rohityadavcloud — APPROVED** [review]
