### PR TITLE
api,server: allow cleaning up vm extraconfig

### LINKED ISSUE #9878: feature: cleanup VM extraconfig in updateVirtualMachine API
For now it is not possible to cleanup VM extraconfig in latest releases.

##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19/4.20
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9878

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
```
(local) 🐱 > update virtualmachine -h
updateVirtualMachine: Updates properties of a virtual machine. The VM has to be stopped and restarted for the new properties to take effect. UpdateVirtualMachine does not first check whether the VM is stopped. Therefore, stop the VM manually before issuing this call.
Required params: id, 
API Params               Type     Description
==========               ====     ===========
cleanupdetails           boolean  optional boolean field, which indicates i
                                  f details should be cleaned up or not (i
                                  f set to true, details removed for this 
                                  resource, details field ignored; if fals
                                  e or not set, no action)
cleanupextraconfig       boolean  Optional boolean field, which indicates i
                                  f extraconfig for the instance should be
                                   cleaned up or not (If set to true, extr
                                  aconfig removed for this instance, extra
                                  config field ignored; if false or not se
                                  t, no action)
customid                 string   an optional field, in case you want to se
                                  t a custom id to the resource. Allowed t
                                  o Root Admins only
...

```

```
(localcloud) 🐱 > list virtualmachines id=d6c566f9-bec2-4daf-b1fb-2da25683229e  filter=id,name,details
{
  "count": 1,
  "virtualmachine": [
    {
      "details": {
        "cpuOvercommitRatio": "2.0",
        "extraconfig-1": "alpha=123\nbeta=456"
      },
      "id": "d6c566f9-bec2-4daf-b1fb-2da25683229e",
      "name": "VM-d6c566f9-bec2-4daf-b1fb-2da25683229e"
    }
  ]
}
(localcloud) 🐱 > update virtualmachine id=d6c566f9-bec2-4daf-b1fb-2da25683229e cleanupextraconfig=true
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "arch": "x86_64",
    "cpunumber": 1,
    "cpuspeed": 500,
    "cpuused": "14.36%",
    "created": "2025-12-01T06:26:23+0000",
    "deleteprotection": false,
    "details": {
      "cpuOvercommitRatio": "2.0"
    },
    "diskioread": 0,
    "diskiowrite": 4,
    "diskkbsread": 0,
    "diskkbswrite": 24,
    "displayname": "VM-d6c566f9-bec2-4daf-b1fb-2da25683229e",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "82f87e9e-ce76-11f0-8a20-1e00060003cb",
    "domainpath": "ROOT",
    "guestosid": "83199135-ce76-11f0-8a20-1e00060003cb",
    "haenable": false,
    "hasannotations": false,
    "hostcontrolstate": "Enabled",
    "hostid": "5249cdbd-9ca9-4c00-a734-0537d89d0dbc",
    "hostname": "pr11974-t14893-kvm-ol8-kvm1",
    "hypervisor": "KVM",
    "id": "d6c566f9-bec2-4daf-b1fb-2da25683229e",
    "instancename": "i-2-3-VM",
    "isdynamicallyscalable": false,
    "lastupdated": "2025-12-01T06:26:37+0000",
    "memory": 512,
    "memoryintfreekbs": -1,
    "memorykbs": 524288,
    "memorytargetkbs": 524288,
    "name": "VM-d6c566f9-bec2-4daf-b1fb-2da25683229e",
    "networkkbsread": 0,
    "networkkbswrite": 0,
    "nic": [
      {
        "broadcasturi": "vlan://1262",
        "deviceid": "0",
        "extradhcpoption": [],
        "id": "4c576998-3258-4f52-9df1-766315d8f14e",
        "isdefault": true,
        "isolationuri": "vlan://1262",
        "macaddress": "02:01:00:cc:00:01",
        "networkid": "882de96d-a74f-4131-814d-9d8e09119125",
        "networkname": "test",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "osdisplayname": "CentOS 5.5 (64-bit)",
    "ostypeid": "83199135-ce76-11f0-8a20-1e00060003cb",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "c049fc6b-1ff2-4ce5-a881-aaa26b9625e1",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.5(64-bit) no GUI (KVM)",
    "templateformat": "QCOW2",
    "templateid": "82fe7d45-ce76-11f0-8a20-1e00060003cb",
    "templatename": "CentOS 5.5(64-bit) no GUI (KVM)",
    "templatetype": "BUILTIN",
    "userid": "bea6206e-ce76-11f0-8a20-1e00060003cb",
    "username": "admin",
    "zoneid": "15d72fa5-8b47-4d90-b1c2-9e2c0d0b78e5",
    "zonename": "pr11974-t14893-kvm-ol8"
  }
}
(localcloud) 🐱 > list virtualmachines id=d6c566f9-bec2-4daf-b1fb-2da25683229e  filter=id,name,details
{
  "count": 1,
  "virtualmachine": [
    {
      "details": {
        "cpuOvercommitRatio": "2.0"
      },
      "id": "d6c566f9-bec2-4daf-b1fb-2da25683229e",
      "name": "VM-d6c566f9-bec2-4daf-b1fb-2da25683229e"
    }
  ]
}
```

https://github.com/user-attachments/assets/23a834b1-f445-408d-98ec-86f51da7e67f

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDetailsDaoImpl.java [hunk 1]
```diff
@@ -31,4 +34,18 @@ public void addDetail(long resourceId, String key, String value, boolean display
...
+        if (StringUtils.isBlank(prefix)) {
+            return 0;
+        }
+        SearchBuilder<VMInstanceDetailVO> sb = createSearchBuilder();
+        sb.and("vmId", sb.entity().getResourceId(), SearchCriteria.Op.EQ);
+        sb.and("prefix", sb.entity().getName(), SearchCriteria.Op.LIKE);
+        sb.done();
+        SearchCriteria<VMInstanceDetailVO> sc = sb.create();
+        sc.setParameters("vmId", vmId);
+        sc.setParameters("prefix", prefix + "%");
```
Comment (DaanHoogland) [inline engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDetailsDaoImpl.java:48]: This bit gives me to think that we might want to include these in a DbConstants, similar to the ApiConstants. No critisism on this PR as I know this is the general practice atm.

File: server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java [hunk 2]
```diff
@@ -466,6 +469,18 @@ public class UserVmManagerImplTest {
     Class<InvalidParameterValueException> expectedInvalidParameterValueException = InvalidParameterValueException.class;
     Class<CloudRuntimeException> expectedCloudRuntimeException = CloudRuntimeException.class;
 
+
+    private void overrideDefaultConfigValue(final ConfigKey configKey, final Object o) {
+        try {
+            final String name = "_defaultValue";
+            Field f = ConfigKey.class.getDeclaredField(name);
```
Comment (abh1sar) [inline server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java]: Should we revert this in teardown?

Comment (shwstppr) [reply server/src/test/java/com/cloud/vm/UserVmManagerImplTest.java]: done

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rajujith** [comment]
@shwstppr Since this is for the 4.22.1 release, could you retarget the PR to the 4.22 branch?

**Comment by shwstppr** [comment]
@rajujith this adds a new API request param, so I think it is better to go in 4.23. I feel this was wrongly added to 4.22.1

**Comment by vishesh92** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 3]
```diff
@@ -2982,14 +2999,7 @@ public UserVm updateVirtualMachine(UpdateVMCmd cmd) throws ResourceUnavailableEx
...
-            if (StringUtils.isNotBlank(extraConfig)) {
-                if (EnableAdditionalVmConfig.valueIn(accountId)) {
-                    logger.info("Adding extra configuration to user vm: " + vmInstance.getUuid());
-                    addExtraConfig(vmInstance, extraConfig);
-                } else {
-                    throw new InvalidParameterValueException("attempted setting extraconfig but enable.additional.vm.configuration is disabled");
-                }
-            }
+            updateVmExtraConfig(userVm, extraConfig, cleanupExtraConfig);
         }
```
[the remark this answers is not in the document]
Comment (vishesh92) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java]: @shwstppr Please check this.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by sudo87 — APPROVED** [review]
lgtm, tested it as well

https://github.com/user-attachments/assets/52377d38-6768-427f-8532-81632415c3e9


https://github.com/user-attachments/assets/c935fa14-9e55-4506-8344-615133919eb5

**Review by vishesh92 — APPROVED** [review]
lgtm
