### PR TITLE
volume: Fix deletion of Uploaded volumes

### LINKED ISSUE #5121: Delete of uploaded volume fails
cleaning up remnance of component test runs, some resources can't be cleaned. Inthis case uploaded volumes.

As it was a full component test run, I don't know which tests left these behind but it were 6 Volumes in total.

only workaround AFAICS, is to edit in the DB.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.16/main
~~~

##### STEPS TO REPRODUCE

~~~
(localcloud) SBCM5> > list volumes listall=true id=d49c18c2-bdc1-4592-bfd1-d7cc0477bd17 
{
  "count": 1,
  "volume": [
    {
      "account": "test-a-TestPrimaryResourceLimitsVolume-test_attach_volume_exceeding_primary_limits-KL4DYO",
      "created": "2021-06-04T15:22:22+0000",
      "destroyed": false,
      "diskofferingdisplaytext": "Custom Disk",
      "diskofferingid": "68470172-5e0c-4f39-9cdd-793e51c9c1b3",
      "diskofferingname": "Custom",
      "displayvolume": true,
      "domain": "domain-W2XAX7",
      "domainid": "56038ea7-bd45-4da7-8a54-bdce352255a0",
      "hypervisor": "Hyperv",
      "id": "d49c18c2-bdc1-4592-bfd1-d7cc0477bd17",
      "isextractable": true,
      "name": "UploadVol",
      "provisioningtype": "thin",
      "quiescevm": false,
      "size": 5368709120,
      "state": "Uploaded",
      "storagetype": "shared",
      "supportsstoragesnapshot": false,
      "tags": [],
      "type": "DATADISK",
      "zoneid": "67198992-a643-41bd-aeaf-26286c23bd4c",
      "zonename": "ref-trl-1030-k-M7-daan-hoogland"
    }
  ]
}
(localcloud) SBCM5> > delete volume id=d49c18c2-bdc1-4592-bfd1-d7cc0477bd17 
{
  "success": true
}
~~~

##### EXPECTED RESULTS

~~~
(localcloud) SBCM5> > list volumes listall=true id=d49c18c2-bdc1-4592-bfd1-d7cc0477bd17 filter=id
~~~
no output

##### ACTUAL RESULTS

~~~
(localcloud) SBCM5> > list volumes listall=true id=d49c18c2-bdc1-4592-bfd1-d7cc0477bd17 filter=id
{
  "count": 1,
  "volume": [
    {
      "id": "d49c18c2-bdc1-4592-bfd1-d7cc0477bd17"
    }
  ]
}

~~~

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes #5121 - where in deletion of uploaded volumes while succeeds on the secondary store does not update the status of the volume in the 'volumes' table

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Uploaded a volume and attempted deletion (on a vmware env):
- volume deleted on secondary store
- volume_store_ref updated with state set to destroyed
- volumes table has state set to Destroy

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by GabrielBrascher — COMMENTED** [review]
Thanks for the PR @Pearl1594! The code looks good (I did not test it).
I am raising just two minor suggestions.

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java [hunk 1]
```diff
@@ -1457,7 +1457,7 @@ protected VolumeVO retrieveAndValidateVolume(long volumeId, Account caller) {
      * The volume is destroyed via {@link VolumeService#destroyVolume(long)} method.
      */
     protected void destroyVolumeIfPossible(VolumeVO volume) {
-        if (volume.getState() != Volume.State.Destroy && volume.getState() != Volume.State.Expunging && volume.getState() != Volume.State.Expunged && volume.getState() != Volume.State.Allocated && volume.getState() != Volume.State.Uploaded) {
+        if (volume.getState() != Volume.State.Destroy && volume.getState() != Volume.State.Expunging && volume.getState() != Volume.State.Expunged && volume.getState() != Volume.State.Allocated) {
```
Comment (GabrielBrascher) [inline server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:1460]: 1. replace big "IFs" to a Set of the ENUM items that should (or not) match with the compared value.
```
        private static final Set<Volume.State> STATES_VOLUME_CANNOT_BE_DESTROYED = new HashSet<>(Arrays.asList(Volume.State.Destroy, Volume.State.Expunging, Volume.State.Expunged, Volume.State.Allocated));
...
        if (!STATES_VOLUME_CANNOT_BE_DESTROYED.contains(volume.getState())) {
```


2. the other suggestion would be to update the Javadoc by adding the Volume.State.Allocated

```
     * <ul>
     *  <li> {@value Volume.State#Destroy};
     *  <li> {@value Volume.State#Expunging};
     *  <li> {@value Volume.State#Expunged}.
     * </ul>
```

**Review by rhtyd — APPROVED** [review]
Lgtm in principle, we need to discuss potential edge cases and do manual testing if it's not covered by smoketests

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java (hunk 1 above)
Comment (Pearl1594) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: Thanks for the review @GabrielBrascher. I've addressed your comments.

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by GabrielBrascher — APPROVED** [review]
Like @rhtyd mentioned, might need some manual tests. I will try to run a few manual tests.

Regarding the code and issue description: LGTM

**Review by shwstppr — APPROVED** [review]

**Review by DaanHoogland — APPROVED** [review]
clgtm (unless this is called without a volume ;)

**Review by GutoVeronezi — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@Pearl1594 your code is very popular (5x :heavy_check_mark: ) but I see some errors in the trillian output. Can you investigate, please?

**Comment by Pearl1594** [comment]
Sure @DaanHoogland , will have a look. But these particular failures seem to be intermittently cropping up on other PRs as well.

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test matrix

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
merging this based on approvals, and smoke tests.
