### PR TITLE
vmware: fix inter-cluster stopped vm and volume migration

### LINKED ISSUE #4838: VMware: VM operations fail after inter-cluster storage migration
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
VMware
~~~

##### CLOUDSTACK VERSION
~~~
4.15
~~~

##### CONFIGURATION
- Advanced networking
- Vmware 6,5 datacenter
   - 2 clusters
   - 1 host per cluster
- 2 NFS cluster-wide storage pools (1 per cluster)

##### SUMMARY
After performing a storage migration of a VM from one cluster to another, it is not possible to start a VM

##### STEPS TO REPRODUCE

~~~
Create VM on cluster 1 (host 1, pool 1)
Stop VM
Migrate instance to pool 2
Start VM
~~~

##### EXPECTED RESULTS
~~~
VM is running
~~~

##### ACTUAL RESULTS
~~~
VM disk cannot be found
~~~

image

````
2021-03-17 17:09:26,591 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-14:ctx-6c9cf0b4 job-73/job-75 ctx-e05b0cda) (logid:4dd5fc60) Unable to contact resource.
com.cloud.exception.StorageUnavailableException: Resource [StoragePool:4] is unreachable: Migrate volume failed: copy volume from primary to secondary failed due to exception: Exception: com.sun.xml.ws.fault.ServerSOAPFaultExc
eption
Message: Client received SOAP Fault from server: 
Required property fileName is missing from data object of type VirtualDiskFlatVer2BackingInfo

while parsing serialized DataObject of type vim.vm.device.VirtualDisk.FlatVer2BackingInfo
at line 1, column 331

while parsing property "backing" of static type VirtualDeviceBackingInfo

while parsing serialized DataObject of type vim.vm.device.VirtualDisk
at line 1, column 233

while parsing property "device" of static type VirtualDevice

while parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec
at line 1, column 193

while parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigSpec

while parsing serialized DataObject of type vim.vm.ConfigSpec
at line 1, column 187

while parsing call information for method ReconfigVM_Task
at line 1, column 110

while parsing SOAP body
at line 1, column 102

while parsing SOAP envelope
at line 1, column 38

while parsing HTTP request for method reconfigure
on object of type vim.VirtualMachine
at line 1, column 0 Please see the server log to find more detail regarding exact cause of the failure.

        at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolume(VolumeOrchestrator.java:1119)
        at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.prepare(VolumeOrchestrator.java:1543)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:1151)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateStart(VirtualMachineManagerImpl.java:5464)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5631)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
````

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #4838

For inter-cluster migration without shared storage, VMware needs a host to be specified. Fix is to specify an appropriate host in the target cluster during a stopped VM migration. Also, find target datastore using the host in the target cluster.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java [hunk 1]
```diff
@@ -209,16 +209,35 @@ protected VMwareGuru() {
...
+            List<VolumeVO> volumes = _volumeDao.findByInstanceAndType(vmId, Volume.Type.ROOT);
+            if (CollectionUtils.isNotEmpty(volumes)) {
+                VolumeVO rootVolume = volumes.get(0);
+                if (rootVolume.getPoolId() != null) {
+                    StoragePoolVO pool = _storagePoolDao.findById(rootVolume.getPoolId());
+                    if (pool != null && pool.getClusterId() != null) {
+                        clusterId = pool.getClusterId();
+                    }
+                }
+            }
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java:239]: please extract into a separate method. i.e. `Long getPoolFromRootVolume(...)`

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java [hunk 2]
```diff
@@ -1066,14 +1087,29 @@ private VirtualDisk getAttachedDisk(VirtualMachineMO vmMo, String diskPath) thro
...
+            if (CollectionUtils.isNotEmpty(hosts)) {
+                hostInTargetCluster = hosts.get(0);
+            }
+            if (hostInTargetCluster == null) {
+                throw new CloudRuntimeException("Migration failed, unable to find suitable target host for VM placement while migrating between storage pools of different clusters without shared storages");
+            }
+        }
+        MigrateVmToPoolCommand migrateVmToPoolCommand = new MigrateVmToPoolCommand(vm.getInstanceName(),
+                vols, destination.getUuid(), hostInTargetCluster == null ? null : hostInTargetCluster.getGuid(), true);
+        commands.add(migrateVmToPoolCommand);
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java:1109]: please restructure this in smaller methods

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 3]
```diff
@@ -4413,9 +4418,17 @@ protected Answer execute(MigrateVmToPoolCommand cmd) {
         }
     }
 
-    private Answer migrateAndAnswer(VirtualMachineMO vmMo, String poolUuid, VmwareHypervisorHost hyperHost, Command cmd) throws Exception {
-        ManagedObjectReference morDs = getTargetDatastoreMOReference(poolUuid, hyperHost);
-
+    private Answer migrateAndAnswer(VirtualMachineMO vmMo, String poolUuid, VmwareHypervisorHost sourceHyperHost,
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4421]: please restructure this method (at least extract the new pieces)

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 4]
```diff
@@ -4627,7 +4640,7 @@ protected Answer execute(MigrateWithStorageCommand cmd) {
             morDc = srcHyperHost.getHyperHostDatacenter();
             morDcOfTargetHost = tgtHyperHost.getHyperHostDatacenter();
             if (!morDc.getValue().equalsIgnoreCase(morDcOfTargetHost.getValue())) {
-                String msg = "Source host & target host are in different datacentesr";
+                String msg = "Source host & target host are in different datacenter";
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4643]: :+1:

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 5]
```diff
@@ -4839,6 +4852,11 @@ private Answer migrateVolume(MigrateVolumeCommand cmd) {
         String path = cmd.getVolumePath();
 
         VmwareHypervisorHost hyperHost = getHyperHost(getServiceContext());
+        VmwareHypervisorHost hyperHostInTargetCluster = null;
+        if (cmd.getHostGuidInTargetCluster() != null) {
+            hyperHostInTargetCluster = VmwareHelper.getHostMOFromHostName(getServiceContext(), cmd.getHostGuidInTargetCluster());
+        }
+        VmwareHypervisorHost targetDSHost = hyperHostInTargetCluster != null ? hyperHostInTargetCluster : hyperHost;
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4859]: this merrits a call to a specific method

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 6]
```diff
@@ -4854,23 +4872,32 @@ private Answer migrateVolume(MigrateVolumeCommand cmd) {
...
             }
 
+            String hardwareVersion = null;
+            if (hyperHostInTargetCluster != null) {
+                Integer sourceHardwareVersion = HypervisorHostHelper.getHostHardwareVersion(hyperHost);
+                Integer destinationHardwareVersion = HypervisorHostHelper.getHostHardwareVersion(hyperHostInTargetCluster);
+                if (sourceHardwareVersion != null && destinationHardwareVersion != null && !sourceHardwareVersion.equals(destinationHardwareVersion)) {
+                    hardwareVersion = String.valueOf(Math.min(sourceHardwareVersion, destinationHardwareVersion));
+                }
+            }
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4891]: please extract

File: plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java [hunk 7]
```diff
@@ -188,20 +177,42 @@ public void copyAsync(DataObject srcData, DataObject destData, Host destHost, As
...
+                if (hostGuidInTargetCluster == null) {
+                    throw new CloudRuntimeException("Offline Migration failed, unable to find suitable target host for worker VM placement while migrating between storage pools of different cluster without shared storages");
+                }
+            }
+        } else if (ScopeType.CLUSTER.equals(targetScopeType)) {
+            hostId = findSuitableHostIdForWorkerVmPlacement(targetPool.getClusterId());
+            if (hostId == null) {
+                throw new CloudRuntimeException("Offline Migration failed, unable to find suitable host for worker VM placement in the cluster of storage pool: " + targetPool.getName());
+            }
+        }
```
Comment (DaanHoogland) [inline plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java:207]: please extract `getTargetScopeType(..)` and possibly more methods from that.

**Review by DaanHoogland — COMMENTED** [review]
mostly structural change requests so far.

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java (hunk 1 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java]: @DaanHoogland done

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java (hunk 2 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java]: @DaanHoogland done

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 3 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java]: @DaanHoogland done

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 5 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4861]: @DaanHoogland which specific method? I didn't get you

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 6 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java]: @DaanHoogland done

File: plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java (hunk 7 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java]: @DaanHoogland done

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 5 above)
Comment (DaanHoogland) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4861]: something like 

```suggestion
        VmwareHypervisorHost targetDSHost = getTargetHostFromTargetCluster(cmd);
```

and

```suggestion
    private VmwareHypervisorHost getTargetHostFromTargetCluster(MigrateVolumeCmd cmd) {
        VmwareHypervisorHost hyperHostInTargetCluster = null;
        if (cmd.getHostGuidInTargetCluster() != null) {
            hyperHostInTargetCluster = VmwareHelper.getHostMOFromHostName(getServiceContext(), cmd.getHostGuidInTargetCluster());
        }
        return hyperHostInTargetCluster != null ? hyperHostInTargetCluster : hyperHost;
    }
```

Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:4861]: @DaanHoogland both `hyperHostInTargetCluster` and `targetDSHost` are used in the method later multiple times. I used two different variables to prevent using if..else multiple times.

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java [hunk 8]
```diff
@@ -209,16 +209,41 @@ protected VMwareGuru() {
...
-        Long hostId;
+    private Long getClusterIdFromVmVolume(long vmId) {
+        Long clusterId = null;
+        List<VolumeVO> volumes = _volumeDao.findByInstanceAndType(vmId, Volume.Type.ROOT);
+        if (CollectionUtils.isNotEmpty(volumes)) {
+            VolumeVO rootVolume = volumes.get(0);
+            if (rootVolume.getPoolId() != null) {
+                StoragePoolVO pool = _storagePoolDao.findById(rootVolume.getPoolId());
+                if (pool != null && pool.getClusterId() != null) {
+                    clusterId = pool.getClusterId();
```
Comment (nvazquez) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java:220]: Maybe add a `break` here? No need to continue iterating

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java [hunk 9]
```diff
@@ -153,6 +153,48 @@
     public static final String VSPHERE_DATASTORE_BASE_FOLDER = "fcd";
     public static final String VSPHERE_DATASTORE_HIDDEN_FOLDER = ".hidden";
 
+    protected final static Map<String, Integer> apiVersionHardwareVersionMap;
+
+    static {
+        apiVersionHardwareVersionMap = new HashMap<String, Integer>();
```
Comment (nvazquez) [inline vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:159]: Is this mapping used only for comparing hosts versions? Maybe we can remove it and do a string comparission?

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java [hunk 10]
```diff
@@ -2211,4 +2253,36 @@ public static void createBaseFolderInDatastore(DatastoreMO dsMo, VmwareHyperviso
...
+      and hardware version of both hosts is different.
+      Return null otherwise
+     */
+    public static String getMinimumHostHardwareVersion(VmwareHypervisorHost host1, VmwareHypervisorHost host2) {
+        String hardwareVersion = null;
+        if (host1 != null & host2 != null) {
+            Integer host1Version = getHostHardwareVersion(host1);
+            Integer host2Version = getHostHardwareVersion(host2);
+            if (host1Version != null && host2Version != null && !host1Version.equals(host2Version)) {
+                hardwareVersion = String.valueOf(Math.min(host1Version, host2Version));
```
Comment (nvazquez) [inline vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:2283]: What about `host1.compareTo(host2)` ? That would give us -1, 0 or 1 and won't need the mapping above

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java (hunk 9 above)
Comment (shwstppr) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:159]: @nvazquez not just comparison, minimum hardware version is needed when migration is between different hosts so the worker VM can be created with lower hardware version

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java (hunk 8 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java:220]: @nvazquez thanks for pointing this out. Though current changes don't have a loop, I'm adding one as VM can have multiple ROOT volumes and some can be on zone-wide store.

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java (hunk 10 above)
Comment (shwstppr) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:2283]: @nvazquez not just comparison, the minimum hardware version is needed when migration is between different hosts so the worker VM can be created with a lower hardware version. eg - when migrating between ESXi 6.0 and 6.5 hosts, VM should have hardwareVersion of ESXi 6.0.
I couldn't find any in-built method to get integer version from ESXi API version. We discussed the same during #4385

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by borisstoyanov** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by borisstoyanov — APPROVED** [review]
LGTM, tested on VMware with single and successive migration of VM

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@nvazquez are you lgtm on the PR? Will hold merging until your confirmation/testing

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java (hunk 10 above)
Comment (shwstppr) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:2283]: When `null` hardwareVersion is passed in `createWorkerVM`, it will use host's hardwareVersion

**Review by nvazquez — APPROVED** [review]
Thanks @shwstppr for addressing the comments, LGTM

**Comment by rhtyd** [comment]
Merged based on Bobby, Nicolas's review and testing, and smoketests.
