### PR TITLE
server: fix enable/disable static nat if userdata is not supported

### LINKED ISSUE #5824: "Disable Static NAT" in VPC results in stuck IP Address
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPC, API
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### CONFIGURATION

Redundant VPC
Custome offerings for VPC and NW-Tier

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Disableing "static NAT" for a public IP fails with error "Service UserData is not supported in the network" shown in GUI while using
custome service offerings for VPC as well as tiers.

##### STEPS TO REPRODUCE

~~~
- create VPC offering without "service UserData"
- create NW offering for usage as VPC-Tier without "service UserData"
- deploy new VPC using custome VPC-offering
- deploy new Tier using custome NW-offering
- Acquire a public IP
- Enable static NAT for IP
- Assaign IP to VM
- Disable static NAT for IP / Release IP
~~~

##### EXPECTED RESULTS

~~~
Static NAT will be disabled and IP can be released afterwards
~~~

##### ACTUAL RESULTS

- Getting error message that disableing failed due to "Service UserData is not supported in the network"
- GUI still showing IP as acquired while state is stuck in "Releasing"
- IP not useable anymore
- Inside VR no interface or iptables entry related to ip existend
- Error log from management-server.log see below
~~~
2022-01-04 01:05:47,032 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:033020cf) Add job-2136 into job monitoring
2022-01-04 01:05:47,036 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (qtp1747352992-1151:ctx-c79a494b ctx-d81bca3e) (logid:32d9eed6) submit async job-2136, details: AsyncJobVO {id:2136, userId: 2, accountId: 2, instanceType: IpAddress, instanceId: 115, cmd: org.apache.cloudstack.api.command.user.address.DisassociateIPAddrCmd, cmdInfo: {"response":"json","ctxUserId":"2","httpmethod":"GET","ctxStartEventId":"7903","id":"12949a47-8a33-4a96-99d0-0ad619e25fe1","ctxDetails":"{\"interface com.cloud.network.IpAddress\":\"12949a47-8a33-4a96-99d0-0ad619e25fe1\"}","ctxAccountId":"2","uuid":"12949a47-8a33-4a96-99d0-0ad619e25fe1","cmdEventType":"NET.IPRELEASE"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 90520740759984, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
2022-01-04 01:05:47,036 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Executing AsyncJobVO {id:2136, userId: 2, accountId: 2, instanceType: IpAddress, instanceId: 115, cmd: org.apache.cloudstack.api.command.user.address.DisassociateIPAddrCmd, cmdInfo: {"response":"json","ctxUserId":"2","httpmethod":"GET","ctxStartEventId":"7903","id":"12949a47-8a33-4a96-99d0-0ad619e25fe1","ctxDetails":"{\"interface com.cloud.network.IpAddress\":\"12949a47-8a33-4a96-99d0-0ad619e25fe1\"}","ctxAccountId":"2","uuid":"12949a47-8a33-4a96-99d0-0ad619e25fe1","cmdEventType":"NET.IPRELEASE"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 90520740759984, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
2022-01-04 01:05:47,037 DEBUG [c.c.a.ApiServlet] (qtp1747352992-1151:ctx-c79a494b ctx-d81bca3e) (logid:32d9eed6) ===END===  10.126.0.110 -- GET  id=12949a47-8a33-4a96-99d0-0ad619e25fe1&command=disassociateIpAddress&response=json
2022-01-04 01:05:47,052 DEBUG [c.c.n.IpAddressManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Revoking all Firewallrules as a part of public IP id=115 release...
2022-01-04 01:05:47,056 DEBUG [c.c.n.f.FirewallManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Releasing 0 firewall rules for ip id=115
2022-01-04 01:05:47,057 DEBUG [c.c.n.f.FirewallManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) There are no firewall rules to apply
2022-01-04 01:05:47,057 DEBUG [c.c.n.f.FirewallManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Successfully released firewall rules for ip id=115 and # of rules now = 0
2022-01-04 01:05:47,060 DEBUG [c.c.n.IpAddressManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Revoking all PortForwarding/StaticNat rules as a part of public IP id=115 release...
2022-01-04 01:05:47,061 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Releasing 0 port forwarding rules for ip id=115
2022-01-04 01:05:47,061 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Releasing 0 static nat rules for ip id=115
2022-01-04 01:05:47,062 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) There are no port forwarding rules to apply for ip id=115
2022-01-04 01:05:47,063 DEBUG [c.c.n.r.RulesManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) There are no static nat rules to apply for ip id=115
2022-01-04 01:05:47,078 INFO  [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Let VpcVirtualRouter handle StaticNat in network 246
2022-01-04 01:05:47,085 DEBUG [o.a.c.n.t.BasicNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) APPLYING STATIC NAT RULES
2022-01-04 01:05:47,085 DEBUG [o.a.c.n.t.BasicNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Applying static nat rules in network Ntwk[246|Guest|30]
2022-01-04 01:05:47,092 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 6-7481041931015921835: Sending  { Cmd , MgmtId: 90520740759984, via: 6(srv-3-comp.dnd-digital.infra), Ver: v1, Flags: 100001, [{"com.cloud.agent.api.routing.SetStaticNatRulesCommand":{"rules":[{"dstIp":"10.1.1.130","id":"0","srcIp":"10.129.0.37","revoked":"true","alreadyAdded":"false","purpose":"StaticNat","icmpType":"0","icmpCode":"0","defaultEgressPolicy":"false"}],"vpcId":"5","accessDetails":{"router.name":"r-61-VM","router.guest.ip":"10.1.1.134","router.ip":"169.254.130.74","zone.network.type":"Advanced"},"wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:47,096 DEBUG [c.c.a.ApiServlet] (qtp1747352992-1113:ctx-7b4e3101) (logid:ec2a8152) ===START===  10.126.0.110 -- GET  jobId=20460f9b-c934-4068-b58d-357ef4aab2c2&command=queryAsyncJobResult&response=json
2022-01-04 01:05:47,101 DEBUG [c.c.a.ApiServer] (qtp1747352992-1113:ctx-7b4e3101 ctx-570fcff6) (logid:ec2a8152) CIDRs from which account 'Acct[60be55c5-1d8a-11ec-83ce-525400c9c662-admin] -- Account {"id": 2, "name": "admin", "uuid": "60be55c5-1d8a-11ec-83ce-525400c9c662"}' is allowed to perform API calls: 0.0.0.0/0,::/0
2022-01-04 01:05:47,114 DEBUG [c.c.a.ApiServlet] (qtp1747352992-1113:ctx-7b4e3101 ctx-570fcff6) (logid:ec2a8152) ===END===  10.126.0.110 -- GET  jobId=20460f9b-c934-4068-b58d-357ef4aab2c2&command=queryAsyncJobResult&response=json
2022-01-04 01:05:48,786 DEBUG [c.c.a.t.Request] (AgentManager-Handler-10:null) (logid:) Seq 6-7481041931015921835: Processing:  { Ans: , MgmtId: 90520740759984, via: 6, Ver: v1, Flags: 0, [{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: Creating file in VR, with ip: 169.254.130.74, file: staticnat_rules.json.dc5d62e4-9aa5-4d7e-be1c-f0d0904665bb","null - success: Invalid unit name "cloud-password-server@10.1.0.65,10.1.0.70" escaped as "cloud-password-server@10.1.0.65\x2c10.1.0.70" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.0.129,10.1.0.134" escaped as "cloud-password-server@10.1.0.129\x2c10.1.0.134" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.1.129,10.1.1.134" escaped as "cloud-password-server@10.1.1.129\x2c10.1.1.134" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.1.65,10.1.1.70" escaped as "cloud-password-server@10.1.1.65\x2c10.1.1.70" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.1.1,10.1.1.14" escaped as "cloud-password-server@10.1.1.1\x2c10.1.1.14" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.0.193,10.1.0.198" escaped as "cloud-password-server@10.1.0.193\x2c10.1.0.198" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.2.33,10.1.2.62" escaped as "cloud-password-server@10.1.2.33\x2c10.1.2.62" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.2.1,10.1.2.30" escaped as "cloud-password-server@10.1.2.1\x2c10.1.2.30" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.0.1,10.1.0.6" escaped as "cloud-password-server@10.1.0.1\x2c10.1.0.6" (maybe you should use systemd-escape?).
iptables v1.8.7 (nf_tables): CONNMARK target: No operation specified
Try `iptables -h' or 'iptables --help' for more information.
"],"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:48,786 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 6-7481041931015921835: Received:  { Ans: , MgmtId: 90520740759984, via: 6(srv-3-comp.dnd-digital.infra), Ver: v1, Flags: 0, { GroupAnswer } }
2022-01-04 01:05:48,786 DEBUG [o.a.c.n.t.BasicNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) APPLYING STATIC NAT RULES
2022-01-04 01:05:48,788 DEBUG [o.a.c.n.t.BasicNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Applying static nat rules in network Ntwk[246|Guest|30]
2022-01-04 01:05:48,798 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 5-4862198747700030093: Sending  { Cmd , MgmtId: 90520740759984, via: 5(srv-4-comp.dnd-digital.infra), Ver: v1, Flags: 100001, [{"com.cloud.agent.api.routing.SetStaticNatRulesCommand":{"rules":[{"dstIp":"10.1.1.130","id":"0","srcIp":"10.129.0.37","revoked":"true","alreadyAdded":"false","purpose":"StaticNat","icmpType":"0","icmpCode":"0","defaultEgressPolicy":"false"}],"vpcId":"5","accessDetails":{"router.name":"r-62-VM","router.guest.ip":"10.1.1.133","router.ip":"169.254.1.55","zone.network.type":"Advanced"},"wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:50,151 DEBUG [c.c.a.ApiServlet] (qtp1747352992-1151:ctx-ce62c823) (logid:cc026a43) ===START===  10.126.0.110 -- GET  jobId=20460f9b-c934-4068-b58d-357ef4aab2c2&command=queryAsyncJobResult&response=json
2022-01-04 01:05:50,161 DEBUG [c.c.a.ApiServer] (qtp1747352992-1151:ctx-ce62c823 ctx-51ddfbfc) (logid:cc026a43) CIDRs from which account 'Acct[60be55c5-1d8a-11ec-83ce-525400c9c662-admin] -- Account {"id": 2, "name": "admin", "uuid": "60be55c5-1d8a-11ec-83ce-525400c9c662"}' is allowed to perform API calls: 0.0.0.0/0,::/0
2022-01-04 01:05:50,171 DEBUG [c.c.a.ApiServlet] (qtp1747352992-1151:ctx-ce62c823 ctx-51ddfbfc) (logid:cc026a43) ===END===  10.126.0.110 -- GET  jobId=20460f9b-c934-4068-b58d-357ef4aab2c2&command=queryAsyncJobResult&response=json
2022-01-04 01:05:50,472 DEBUG [c.c.a.t.Request] (AgentManager-Handler-5:null) (logid:) Seq 5-4862198747700030093: Processing:  { Ans: , MgmtId: 90520740759984, via: 5, Ver: v1, Flags: 0, [{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: Creating file in VR, with ip: 169.254.1.55, file: staticnat_rules.json.ce198886-6591-48a8-9b18-bdb98436037a","null - success: Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
iptables v1.8.7 (nf_tables): CONNMARK target: No operation specified
Try `iptables -h' or 'iptables --help' for more information.
"],"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:50,472 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 5-4862198747700030093: Received:  { Ans: , MgmtId: 90520740759984, via: 5(srv-4-comp.dnd-digital.infra), Ver: v1, Flags: 0, { GroupAnswer } }
2022-01-04 01:05:50,487 DEBUG [o.a.c.n.t.AdvancedNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) APPLYING VPC IP RULES
2022-01-04 01:05:50,489 DEBUG [o.a.c.n.t.BasicNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Applying vpc ip association in network Ntwk[246|Guest|30]
2022-01-04 01:05:50,518 DEBUG [o.a.c.h.HAManagerImpl] (BackgroundTaskPollManager-5:ctx-1ebf821f) (logid:86c54e31) HA health check task is running...
2022-01-04 01:05:50,522 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 6-7481041931015921836: Sending  { Cmd , MgmtId: 90520740759984, via: 6(srv-3-comp.dnd-digital.infra), Ver: v1, Flags: 100001, [{"com.cloud.agent.api.routing.IpAssocVpcCommand":{"ipAddresses":[{"accountId":"5","publicIp":"10.129.0.37","sourceNat":"true","add":"false","oneToOneNat":"true","firstIP":"true","broadcastUri":"vlan://2990","vlanGateway":"10.129.0.1","vlanNetmask":"255.255.255.128","vifMacAddress":"1e:00:59:00:00:b2","networkRate":"-1","trafficType":"Public","networkName":"br3_CS_Pub","newNic":"false","isPrivateGateway":"false"}],"accessDetails":{"router.name":"r-61-VM","router.guest.ip":"10.129.0.42","network.public.last.ip":"false","router.ip":"169.254.130.74","zone.network.type":"Advanced"},"wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:51,443 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-13:null) (logid:) SeqA 10-519737: Processing Seq 10-519737:  { Cmd , MgmtId: -1, via: 10, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"31","_loadInfo":"{
  "connections": []
}","wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:51,451 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-13:null) (logid:) SeqA 10-519737: Sending Seq 10-519737:  { Ans: , MgmtId: 90520740759984, via: 10, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.AgentControlAnswer":{"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:51,581 DEBUG [c.c.s.StatsCollector] (secstorage-1:ctx-3cfdebeb) (logid:745c40b5) Verifying image storage [1]. Capacity: total=[1 TB], used=[353 GB], threshold=[89.99999761581421%].
2022-01-04 01:05:51,585 DEBUG [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-3cfdebeb) (logid:745c40b5) Zone [1] is ready to launch secondary storage VM.
2022-01-04 01:05:51,592 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-e14f6847) (logid:343331d7) Zone 1 is ready to launch console proxy
2022-01-04 01:05:51,636 DEBUG [c.c.a.t.Request] (AgentManager-Handler-1:null) (logid:) Seq 6-7481041931015921836: Processing:  { Ans: , MgmtId: 90520740759984, via: 6, Ver: v1, Flags: 0, [{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: Creating file in VR, with ip: 169.254.130.74, file: ip_associations.json.2470efd6-4b01-450c-b5fe-e6f7ab183206","null - success: Invalid unit name "cloud-password-server@10.1.0.65,10.1.0.70" escaped as "cloud-password-server@10.1.0.65\x2c10.1.0.70" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.0.129,10.1.0.134" escaped as "cloud-password-server@10.1.0.129\x2c10.1.0.134" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.1.129,10.1.1.134" escaped as "cloud-password-server@10.1.1.129\x2c10.1.1.134" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.1.65,10.1.1.70" escaped as "cloud-password-server@10.1.1.65\x2c10.1.1.70" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.1.1,10.1.1.14" escaped as "cloud-password-server@10.1.1.1\x2c10.1.1.14" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.0.193,10.1.0.198" escaped as "cloud-password-server@10.1.0.193\x2c10.1.0.198" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.2.33,10.1.2.62" escaped as "cloud-password-server@10.1.2.33\x2c10.1.2.62" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.2.1,10.1.2.30" escaped as "cloud-password-server@10.1.2.1\x2c10.1.2.30" (maybe you should use systemd-escape?).
Invalid unit name "cloud-password-server@10.1.0.1,10.1.0.6" escaped as "cloud-password-server@10.1.0.1\x2c10.1.0.6" (maybe you should use systemd-escape?).
"],"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:51,636 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 6-7481041931015921836: Received:  { Ans: , MgmtId: 90520740759984, via: 6(srv-3-comp.dnd-digital.infra), Ver: v1, Flags: 0, { GroupAnswer } }
2022-01-04 01:05:51,636 DEBUG [o.a.c.n.t.AdvancedNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) APPLYING VPC IP RULES
2022-01-04 01:05:51,640 DEBUG [o.a.c.n.t.BasicNetworkTopology] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Applying vpc ip association in network Ntwk[246|Guest|30]
2022-01-04 01:05:51,672 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 5-4862198747700030094: Sending  { Cmd , MgmtId: 90520740759984, via: 5(srv-4-comp.dnd-digital.infra), Ver: v1, Flags: 100001, [{"com.cloud.agent.api.routing.IpAssocVpcCommand":{"ipAddresses":[{"accountId":"5","publicIp":"10.129.0.37","sourceNat":"true","add":"false","oneToOneNat":"true","firstIP":"true","broadcastUri":"vlan://2990","vlanGateway":"10.129.0.1","vlanNetmask":"255.255.255.128","vifMacAddress":"1e:00:59:00:00:b2","networkRate":"-1","trafficType":"Public","networkName":"br3_CS_Pub","newNic":"false","isPrivateGateway":"false"}],"accessDetails":{"router.name":"r-62-VM","router.guest.ip":"10.129.0.42","network.public.last.ip":"false","router.ip":"169.254.1.55","zone.network.type":"Advanced"},"wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:52,737 DEBUG [c.c.a.t.Request] (AgentManager-Handler-7:null) (logid:) Seq 5-4862198747700030094: Processing:  { Ans: , MgmtId: 90520740759984, via: 5, Ver: v1, Flags: 0, [{"com.cloud.agent.api.routing.GroupAnswer":{"results":["null - success: Creating file in VR, with ip: 169.254.1.55, file: ip_associations.json.61f85983-0804-4443-8357-a9b934c9a59e","null - success: Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
Error: Nexthop has invalid gateway.
"],"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2022-01-04 01:05:52,737 DEBUG [c.c.a.t.Request] (API-Job-Executor-99:ctx-8eea185f job-2136 ctx-b0c1e685) (logid:20460f9b) Seq 5-4862198747700030094: Received:  { Ans: , MgmtId: 90520740759984, via: 5(srv-4-comp.dnd-digital.infra), Ver: v1, Flags: 0, { GroupAnswer } }
2022-01-04 01:05:52,751 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Unexpected exception while executing org.apache.cloudstack.api.command.user.address.DisassociateIPAddrCmd
com.cloud.exception.UnsupportedServiceException: Service UserData is not supported in the network id=246
	at com.cloud.network.dao.NetworkServiceMapDaoImpl.getProviderForServiceInNetwork(NetworkServiceMapDaoImpl.java:126)
	at jdk.internal.reflect.GeneratedMethodAccessor1754.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy61.getProviderForServiceInNetwork(Unknown Source)
	at com.cloud.network.NetworkModelImpl.getUserDataUpdateProvider(NetworkModelImpl.java:902)
	at com.cloud.network.rules.RulesManagerImpl.applyUserData(RulesManagerImpl.java:633)
	at com.cloud.network.rules.RulesManagerImpl.revokeAllPFAndStaticNatRulesForIp(RulesManagerImpl.java:1147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy122.revokeAllPFAndStaticNatRulesForIp(Unknown Source)
	at com.cloud.network.IpAddressManagerImpl.cleanupIpResources(IpAddressManagerImpl.java:655)
	at com.cloud.network.IpAddressManagerImpl.disassociatePublicIpAddress(IpAddressManagerImpl.java:691)
	at com.cloud.network.NetworkServiceImpl.releaseIpAddressInternal(NetworkServiceImpl.java:967)
	at com.cloud.network.NetworkServiceImpl.releaseIpAddress(NetworkServiceImpl.java:924)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy262.releaseIpAddress(Unknown Source)
	at org.apache.cloudstack.api.command.user.address.DisassociateIPAddrCmd.execute(DisassociateIPAddrCmd.java:80)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
	at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:108)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-04 01:05:52,754 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Complete async job-2136, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"530","errortext":"Service UserData is not supported in the network id=246"}
2022-01-04 01:05:52,755 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Publish async job-2136 complete on message bus
2022-01-04 01:05:52,755 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Wake up jobs related to job-2136
2022-01-04 01:05:52,755 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Update db status for job-2136
2022-01-04 01:05:52,756 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Wake up jobs joined with job-2136 and disjoin all subjobs created from job- 2136
2022-01-04 01:05:52,761 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Done executing org.apache.cloudstack.api.command.user.address.DisassociateIPAddrCmd for job-2136
2022-01-04 01:05:52,761 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-99:ctx-8eea185f job-2136) (logid:20460f9b) Remove job-2136 from job monitoring
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #5824

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
changes LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, do we have a reason for this regression?

**Review by shwstppr — APPROVED** [review]
code LGTM

**Comment by weizhouapache** [comment]
> clgtm, do we have a reason for this regression?

@DaanHoogland 

the exception is thrown at
https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/java/com/cloud/network/dao/NetworkServiceMapDaoImpl.java#L125-L127
```
        if (ntwkSvc == null) {
            throw new UnsupportedServiceException("Service " + service.getName() + " is not supported in the network id=" + networkId);
        }
```

removing the lines might also fix the issue. but it has large impact.
this PR has much smaller impact.

**Comment by DaanHoogland** [comment]
> > clgtm, do we have a reason for this regression?
> 
> @DaanHoogland
> 
> the exception is thrown at https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/java/com/cloud/network/dao/NetworkServiceMapDaoImpl.java#L125-L127
> 
> ```
>         if (ntwkSvc == null) {
>             throw new UnsupportedServiceException("Service " + service.getName() + " is not supported in the network id=" + networkId);
>         }
> ```
> 
> removing the lines might also fix the issue. but it has large impact. this PR has much smaller impact.

I would agree @weizhouapache, I approve of this change and intuitively it is the best solution but still have some questions;

- why is applyUserData called at all if it is not supported? and,
- is this a regression that might have other unforeseen consequences?

It looks like it was introduced by 9c6b02fd8b2282ceb80a1b9205871a4e93a00682.

**Comment by weizhouapache** [comment]
> > > clgtm, do we have a reason for this regression?
> > 
> > 
> > @DaanHoogland
> > the exception is thrown at https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/java/com/cloud/network/dao/NetworkServiceMapDaoImpl.java#L125-L127
> > ```
> >         if (ntwkSvc == null) {
> >             throw new UnsupportedServiceException("Service " + service.getName() + " is not supported in the network id=" + networkId);
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > removing the lines might also fix the issue. but it has large impact. this PR has much smaller impact.
> 
> I would agree @weizhouapache, I approve of this change and intuitively it is the best solution but still have some questions;
> 
> * why is applyUserData called at all if it is not supported? and,
> * is this a regression that might have other unforeseen consequences?
> 
> It looks like it was introduced by [9c6b02f](https://github.com/apache/cloudstack/commit/9c6b02fd8b2282ceb80a1b9205871a4e93a00682).



> 

@DaanHoogland 
when enable/disable static nat, the public IP of the vm needs to also updated in userdata server (=VR).
by default, VM public IP is source nat IP. if static nat is enabled, VM public IP is the static nat IP.
that's why we apply userdata of the vm/nic.

you might have also noticed that there are already check below in code
```
        if (element == null) {
            s_logger.error("Can't find network element for " + Service.UserData.getName() + " provider needed for UserData update");
```
if element cannot be found, then do not apply userdata. but the exception is thrown in Dao (I think it is not a good idea)

I have no idea if there are other issues  caused by the code in Dao I pasted above.
for enable/disable static nat, both should work no matter userdata is supported or not.

**Comment by DaanHoogland** [comment]
> > > > clgtm, do we have a reason for this regression?
> > > 
> > > 
> > > @DaanHoogland
> > > the exception is thrown at https://github.com/apache/cloudstack/blob/main/engine/schema/src/main/java/com/cloud/network/dao/NetworkServiceMapDaoImpl.java#L125-L127
> > > ```
> > >         if (ntwkSvc == null) {
> > >             throw new UnsupportedServiceException("Service " + service.getName() + " is not supported in the network id=" + networkId);
> > >         }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > removing the lines might also fix the issue. but it has large impact. this PR has much smaller impact.
> > 
> > 
> > I would agree @weizhouapache, I approve of this change and intuitively it is the best solution but still have some questions;
> > 
> > * why is applyUserData called at all if it is not supported? and,
> > * is this a regression that might have other unforeseen consequences?
> > 
> > It looks like it was introduced by [9c6b02f](https://github.com/apache/cloudstack/commit/9c6b02fd8b2282ceb80a1b9205871a4e93a00682).
> 
> > 
> 
> @DaanHoogland when enable/disable static nat, the public IP of the vm needs to also updated in userdata server (=VR). by default, VM public IP is source nat IP. if static nat is enabled, VM public IP is the static nat IP. that's why we apply userdata of the vm/nic.
> 
> you might have also noticed that there are already check below in code
> 
> ```
>         if (element == null) {
>             s_logger.error("Can't find network element for " + Service.UserData.getName() + " provider needed for UserData update");
> ```
> 
> if element cannot be found, then do not apply userdata. but the exception is thrown in Dao (I think it is not a good idea)
> 
> I have no idea if there are other issues caused by the code in Dao I pasted above. for enable/disable static nat, both should work no matter userdata is supported or not.

I get it @weizhouapache , as discussed of line `applyUserData` should be renamed to `applyUserDataIfNeeded`. I thought it should not have been invoked in the first place, if it is harmfull. Your solution is good, thanks.

**Comment by weizhouapache** [comment]
> I get it @weizhouapache , as discussed of line `applyUserData` should be renamed to `applyUserDataIfNeeded`. I thought it should not have been invoked in the first place, if it is harmfull. Your solution is good, thanks.

@DaanHoogland thanks.

Renamed the method as per your comment.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java [hunk 1]
```diff
@@ -629,8 +630,14 @@ private boolean enableStaticNat(long ipId, long vmId, long networkId, boolean is
...
     }
 
-    protected void applyUserData(long vmId, Network network, Nic guestNic) throws ResourceUnavailableException {
-        UserDataServiceProvider element = _networkModel.getUserDataUpdateProvider(network);
+    protected void applyUserDataIfNeeded(long vmId, Network network, Nic guestNic) throws ResourceUnavailableException {
+        UserDataServiceProvider element = null;
+        try {
+            element = _networkModel.getUserDataUpdateProvider(network);
+        } catch (UnsupportedServiceException ex) {
+            s_logger.info(String.format("%s is not supported by network %s, skipping", Service.UserData.getName(), network));
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/network/rules/RulesManagerImpl.java:638]:
```suggestion
            s_logger.info(String.format("%s is not supported by network %s, skipping.", Service.UserData.getName(), network));
```

**Review by GutoVeronezi — COMMENTED** [review]
CLGTM

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test
