### PR TITLE
server: fix update vm with unconstrained offering

### LINKED ISSUE #5694: Can't change Setting on VM with Custom Unconstrained Compute Offering
##### ISSUE TYPE
 * Bug Report

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Can't change Setting on VM with Custom Unconstrained Compute Offering

##### STEPS TO REPRODUCE
~~~
Deploy VM with Custom Unconstrained Compute Offering. Choose correct CPU Cores, CPU Speed in MHz (for example 2000), RAM capasity. Poweroff VM from WebUI. Try to change VM's settings. 
~~~
##### EXPECTED RESULTS
~~~
User or Admin can change VM's settings.
~~~

##### ACTUAL RESULTS
~~~
When U try to change any setting U have error about CPU Speed. User don't have any errors with Custom Constrained Compute Offering
~~~
image

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5694

Verify custom params for VM while updating using existing CPU speed when the VM offering is of unconstrained type.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 1]
```diff
@@ -2644,6 +2643,9 @@ private void verifyVmLimits(UserVmVO vmInstance, Map<String, String> details) {
             Map<String, String> customParameters = new HashMap<>();
             customParameters.put(VmDetailConstants.CPU_NUMBER, String.valueOf(newCpu));
             customParameters.put(VmDetailConstants.MEMORY, String.valueOf(newMemory));
+            if (svcOffering.getSpeed() == null) {
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: This cond may not be needed, as Unconstrained offering doesn't have CPU speed set and so it's null always. Pls check.

Comment (shwstppr) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: @sureshanaparti please check the code. This method is not just for unconstrained offerings. CPU Speed detail is added only for offerings that are dynamic and having null speed

Comment (sureshanaparti) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: > 

Ok, will check @shwstppr

**Review by sureshanaparti — APPROVED** [review]

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code LGTM

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java (hunk 1 above)
Comment (harikrishna-patnala) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: @shwstppr do we need similar checks for CPU number and memory?

Comment (shwstppr) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: @harikrishna-patnala cpu and memory are already set in customParameters variable above

Comment (Pearl1594) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: Maybe this check isn't required, as it is already present in validateCustomParameter(), however no biggie

**Review by Pearl1594 — APPROVED** [review]
Verified behavior. LGTM.

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java (hunk 1 above)
Comment (harikrishna-patnala) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: @shwstppr This is about the null check, but yeah as @Pearl1594 mentioned we are checking it in another method.

**Review by harikrishna-patnala — APPROVED** [review]

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 2]
```diff
@@ -2644,6 +2643,9 @@ private void verifyVmLimits(UserVmVO vmInstance, Map<String, String> details) {
...
+                customParameters.put(VmDetailConstants.CPU_SPEED, details.get(VmDetailConstants.CPU_SPEED));
+            }
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2648]:
```suggestion
            customParameters.put(VmDetailConstants.CPU_SPEED, details.get(VmDetailConstants.CPU_SPEED));
```

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 3]
```diff
@@ -2644,6 +2643,7 @@ private void verifyVmLimits(UserVmVO vmInstance, Map<String, String> details) {
             Map<String, String> customParameters = new HashMap<>();
             customParameters.put(VmDetailConstants.CPU_NUMBER, String.valueOf(newCpu));
             customParameters.put(VmDetailConstants.MEMORY, String.valueOf(newMemory));
+            customParameters.put(VmDetailConstants.CPU_SPEED, details.get(VmDetailConstants.CPU_SPEED));
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:2646]: @shwstppr I see, there are resource limit checks for cpu count & memory (check below code), but not cpu speed. The new cpu speed changes are not recorded. Should this be addressed in another PR?

https://github.com/apache/cloudstack/blob/84b9b61b9ba079406e2c0c57e07153cff2a44b76/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L2656-L2657

https://github.com/apache/cloudstack/blob/84b9b61b9ba079406e2c0c57e07153cff2a44b76/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L2667-L2671

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 4]
```diff
@@ -16,6 +16,7 @@
 // under the License.
 package com.cloud.vm;
 
+import static com.cloud.configuration.ConfigurationManagerImpl.VM_USERDATA_MAX_LENGTH;
```
Comment (rohityadavcloud) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:19]: @shwstppr generally bad practice to import/depend on an `impl`; instead refactor the static field from an interface/service/manager than an impl class. If this value is determined/depends on a configkey, maybe use a getter. Otherwise LGTM.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
> Trillian test result (tid-2866) Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7 Total time taken: 35566 seconds Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr5828-t2866-kvm-centos7.zip Smoke tests completed. 91 look OK, 1 have errors Only failed tests results shown below:
> 
> Test	Result	Time (s)	Test File
> test_disable_oobm_ha_state_ineligible	`Error`	1512.28	test_hostha_kvm.py

failed test ^^^ not related to this PR changes.
