### PR TITLE
Consider Instance in Starting state as well for allocation algorithm

### LINKED ISSUE #11606: Userdispersing algorithm does not consider VMs in starting state
### problem

I tried to use userdispersing algorithm for volumes and VMs, still I've got numerous VMs starting on the same host. See https://github.com/apache/cloudstack/discussions/11412
In the end it was confirmed that algorithm considers just running VMs.
As VM start takes time, and VMs are started in packs (Jenkins jcloud plugin), all VMs are placed to the same host. Finally I had to switch to random algo that dispersing a lot better (though not ideal)
I believe  that as soon as VM is assigned for start on a host (still in Starting state), it should be already considered by userdispersing algorithm.

### versions

CloudStack 4.21.0.0, though I had the same issue with 4.20
KVM
local fat volumes

### The steps to reproduce the bug

1. Confiugre CS to use userdispersing algorithm (volumes and VMs)
2. Start several VMs via api without waiting for response that VM was started, e.g.
```
for i in {01..10}; do cloudstack deployVirtualMachine serviceofferingid=XXX templateid=YYY zoneid=ZZZ name=test-${i} & done
```
in my env all VMs start on the same host, even if I add some delay to the loop, unless if delay is enough to fully start VM

### What to do about it?

Algorithm should query both Running and Starting VMs and use that data to decide the next VM placement

### PR DESCRIPTION
**Pull request by sudo87**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/11606

With this change, allocation algorithm will take Instance in starting state as well for allocation.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by sudo87** [comment]
@blueorangutan package

**Comment by sudo87** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
code lgtm

File: engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java [hunk 1]
```diff
@@ -116,17 +116,17 @@ public class VMInstanceDaoImpl extends GenericDaoBase<VMInstanceVO, Long> implem
 
     protected Attribute _updateTimeAttr;
 
-    private static final String ORDER_CLUSTERS_NUMBER_OF_VMS_FOR_ACCOUNT_PART1 = "SELECT host.cluster_id, SUM(IF(vm.state='Running' AND vm.account_id = ?, 1, 0)) " +
+    private static final String ORDER_CLUSTERS_NUMBER_OF_VMS_FOR_ACCOUNT_PART1 = "SELECT host.cluster_id, SUM(IF((vm.state='Running' OR vm.state='Starting') AND vm.account_id = ?, 1, 0)) " +
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java]: maybe use

`
vm.state IN ('Running', 'Starting')
`

**Comment by sudo87** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java (hunk 1 above)
Comment (sudo87) [reply engine/schema/src/main/java/com/cloud/vm/dao/VMInstanceDaoImpl.java]: Thanks @weizhouapache, change is included in the pr. Please review.

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by sudo87** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
this PR makes sense to me, however it is difficult to validate
I think we can merge if there is no regression.
what do you think ? @shwstppr @DaanHoogland

**Comment by sudo87** [comment]
@weizhouapache, agreed. It needs testing with larger env. That said,  I did a basic validation (suggested in the issue) by spinning off 4 instances in 2 different envs running 4.20, one with this change and other without. Both were configured with userdispersing vm allocation algo.

```
for i in {01..4}; do cloudstack deployVirtualMachine serviceofferingid=XXX templateid=YYY zoneid=ZZZ name=test-${i} & done
```
Results:

- With this change: Instances were evenly distributed across 2 hosts (2-2)
- w/o: 3 were placed on host1, 1 on host2

**Comment by weizhouapache** [comment]
> @weizhouapache, agreed. It needs testing with larger env. That said, I did a basic validation (suggested in the issue) by spinning off 4 instances in 2 different envs running 4.20, one with this change and other without. Both were configured with userdispersing vm allocation algo.
> 
> ```
> for i in {01..4}; do cloudstack deployVirtualMachine serviceofferingid=XXX templateid=YYY zoneid=ZZZ name=test-${i} & done
> ```
> 
> Results:
> 
> * With this change: Instances were evenly distributed across 2 hosts (2-2)
> * w/o: 3 were placed on host1, 1 on host2

@sudo87 
can you deploy more (e.g. 20) instances with smaller memory ?

**Comment by sudo87** [comment]
> > @weizhouapache, agreed. It needs testing with larger env. That said, I did a basic validation (suggested in the issue) by spinning off 4 instances in 2 different envs running 4.20, one with this change and other without. Both were configured with userdispersing vm allocation algo.
> > ```
> > for i in {01..4}; do cloudstack deployVirtualMachine serviceofferingid=XXX templateid=YYY zoneid=ZZZ name=test-${i} & done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Results:
> > 
> > * With this change: Instances were evenly distributed across 2 hosts (2-2)
> > * w/o: 3 were placed on host1, 1 on host2
> 
> @sudo87 can you deploy more (e.g. 20) instances with smaller memory ?

End result is same for both envs, each host has 10 instances running. Transition from Initialize -> Starting -> Running is small for a lean image.

**Comment by weizhouapache** [comment]
> End result is same for both envs, each host has 10 instances running. Transition from Initialize -> Starting -> Running is small for a lean image.

ok, so it may happen only if starting vms take a bit long time than usual
