### PR TITLE
Usage: Heartbeat should not schedule usage job when a job is already running

### LINKED ISSUE #12424: bogus usage jobs may be created when usage is behind in processing
### problem

During trouble shooting missing data, when usage is behind it was found that a lot of usage_jobs are created that won’t have a period to process:

```
2026-01-13 01:00:38,566 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) it's been 86438558 ms since last usage job and 66261443 ms until next job, scheduling an immediate job to catch up (aggregation duration is 1440 minutes)
2026-01-13 01:00:38,568 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) Scheduling Usage job...
2026-01-13 01:00:38,570 INFO  [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) starting usage job...
2026-01-13 01:00:38,606 INFO  [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) Parsing usage records between Mon Jan 12 01:00:00 CET 2026 and Tue Jan 13 00:59:59 CET 2026
2026-01-13 01:01:38,581 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) it's been 86498581 ms since last usage job and 66201420 ms until next job, scheduling an immediate job to catch up (aggregation duration is 1440 minutes)
2026-01-13 01:01:38,581 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) Scheduling Usage job...
2026-01-13 01:02:38,559 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) it's been 86558559 ms since last usage job and 66141442 ms until next job, scheduling an immediate job to catch up (aggregation duration is 1440 minutes)
2026-01-13 01:02:38,559 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) Scheduling Usage job...
2026-01-13 01:03:38,558 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) it's been 86618558 ms since last usage job and 66081443 ms until next job, scheduling an immediate job to catch up (aggregation duration is 1440 minutes)
2026-01-13 01:03:38,558 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) Scheduling Usage job...
2026-01-13 01:04:38,559 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) it's been 86678559 ms since last usage job and 66021442 ms until next job, scheduling an immediate job to catch up (aggregation duration is 1440 minutes)
2026-01-13 01:04:38,559 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) Scheduling Usage job...
2026-01-13 01:05:38,558 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) it's been 86738559 ms since last usage job and 65961442 ms until next job, scheduling an immediate job to catch up (aggregation duration is 1440 minutes)
2026-01-13 01:05:38,558 DEBUG [cloud.usage.UsageManagerImpl] (Usage-HB-1:null) (logid:) Scheduling Usage job...
2026-01-13 01:06:02,952 DEBUG [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) Creating networking offering: 18 for Vm: 75432 for account: 239496
2026-01-13 01:06:03,028 DEBUG [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) create volume with id : 163459 for account: 239496
2026-01-13 01:06:03,497 DEBUG [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) deleting network offering: 18 from Vm: 96981
```
the HeartBeat thread should be clever about existing jobs and not create the extra jobs.

### versions

ACS 4.19

### The steps to reproduce the bug

1. have an environment running for a while
2. prune intermediate and usage tables a couple of months
3. set the events of those months to unprocessed
4. start usage
5. observe the a job starts and multiple other jobs are created.
6. the extra jobs seem to have an interval of -1 second and fail (of course)

### What to do about it?

make sure the heartbeat job does not create jobs while jobs are being processed/scheduled already.

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR fixes #12424

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Stop Usage server
2. Set `usage.stats.job.aggregation.range` to 5
3. Start Usage server - wait for a usage job to finish
4. Stop Usage server
5. Execute VM, vol, network creates, Acquire IP addresses etc in a loop using cmk so that lots of events are generated.
7. Start Usage server after 2 hours.
8. Observe that no failed usage job are present in the database and usage logs.

### CODE REVIEW

**Comment by abh1sar** [comment]
@blueorangutan package

File: usage/src/main/java/com/cloud/usage/UsageManagerImpl.java [hunk 1]
```diff
@@ -192,6 +193,7 @@ public class UsageManagerImpl extends ManagerBase implements UsageManager, Runna
     private final List<UsageVmDiskVO> usageVmDisks = new ArrayList<UsageVmDiskVO>();
 
     private final ScheduledExecutorService _executor = Executors.newSingleThreadScheduledExecutor(new NamedThreadFactory("Usage-Job"));
+    private final AtomicBoolean _parseJobRunning = new AtomicBoolean(false);
```
Comment (DaanHoogland) [inline usage/src/main/java/com/cloud/usage/UsageManagerImpl.java]: `isParsingJobRunning` ? No ‘_’ needed but also more descriptive to be a boolean

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

File: usage/src/main/java/com/cloud/usage/UsageManagerImpl.java [hunk 2]
```diff
@@ -2269,7 +2276,9 @@ protected void runInContext() {
                             if (timeToJob > (aggregationDurationMillis / 2)) {
                                 logger.debug("it's been {} ms since last usage job and {} ms until next job, scheduling an immediate job to catch up (aggregation duration is {} minutes)"
                                     , timeSinceLastSuccessJob, timeToJob, _aggregationDuration);
-                                scheduleParse();
+                                if (!isParsingJobRunning.get()) {
```
Comment (shwstppr) [inline usage/src/main/java/com/cloud/usage/UsageManagerImpl.java]: Any logs here?

Comment (abh1sar) [reply usage/src/main/java/com/cloud/usage/UsageManagerImpl.java]: added logging

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan test

**Comment by abh1sar** [comment]
@blueorangutan test keepEnv
