### PR TITLE
server: trim autoscale Windows VM hostname

### LINKED ISSUE #9505: Autoscale VM Name Issue with Windows OS
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Autoscale
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### SUMMARY

When a VM is Autoscaled, the name cloudstack gives is in this format:

autoScaleVM-_VMName_-_RandomNumber_-_RandomAlphabets_

This results in a very long VM name. Anyhow, this isnt an issue for Linux Guest OS. 

However, in Windows VMs, this becomes a problem because Windows VMs can only have a name with max 15 Characters. 

As a result, the name of the VM inside the newly created Windows VM seems to just put 'Windows 2022' or something similar. 

The name of the VM in Cloudstack seems to be fine. 

Im not sure what kind of solution there is to this, cause essentially this is a limitation of Windows VMs. 

Open for discussion

##### STEPS TO REPRODUCE

~~~
1. Create a Windows Template
2. Create Autoscale with Windows Template
3. Check the name of the newly created VM on Cloudstack GUI (The name should be correct)
4. Enter VM, check the VM name from inside the Guest VM (Name will not be correct)
~~~

##### EXPECTED RESULTS

~~~
~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9505

Trim the generated hostname for Windows VM to 15 characters.
Doc PR: https://github.com/apache/cloudstack-documentation/pull/575

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@shwstppr 
is this ready for review ?

**Comment by shwstppr** [comment]
@weizhouapache yes, though I wanted to confirm if it is a good idea to use the last 15 characters of the long generated name. Not using the first 15 as they can turn out to be the same.

**Comment by weizhouapache** [comment]
> @weizhouapache yes, though I wanted to confirm if it is a good idea to use the last 15 characters of the long generated name. Not using the first 15 as they can turn out to be the same.

@shwstppr 
looks ok to me. I could not find a better solution to be honest.

is it possible the first letter is unaccepted (for example `-`) after the truncation ?

File: server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java [hunk 1]
```diff
@@ -1968,12 +1968,19 @@ protected Pair<String, String> getNextVmHostAndDisplayName(AutoScaleVmGroupVO as
...
+        String name = VM_HOSTNAME_PREFIX + asGroup.getName().substring(0, subStringLength) + vmHostNameSuffix;
+        if (!isWindows) {
+            return new Pair<>(name, name);
         }
-        return new Pair<>(hostName, displayName);
+        String hostName = name.substring(Math.max(0, name.length() - 15));
+        if (Character.isLetterOrDigit(hostName.charAt(0))) {
+            return new Pair<>(hostName, name);
+        }
+        String temp = name.substring(0, Math.max(0, name.length() - 15)).replaceAll("[^a-zA-Z0-9]", "");
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java]: edge case: all of the last 15 chars are special chars or whitespace. I think we better do a replace first and then take the last 15.

Comment (shwstppr) [reply server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java]: @DaanHoogland I don't think this case can happen.
The only user-defined part in the VM name is the name of the autoscale group, and we've checks for that to only contain letters, numbers and hyphen. checkAutoScaleVmGroupName` does that

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java [hunk 2]
```diff
@@ -1968,12 +1968,19 @@ protected Pair<String, String> getNextVmHostAndDisplayName(AutoScaleVmGroupVO as
...
-        String hostName = displayName;
-        if (isWindows) {
-            hostName = displayName.substring(Math.max(0, displayName.length() - 15));
+        String name = VM_HOSTNAME_PREFIX + asGroup.getName().substring(0, subStringLength) + vmHostNameSuffix;
+        if (!isWindows) {
+            return new Pair<>(name, name);
         }
-        return new Pair<>(hostName, displayName);
+        String hostName = name.substring(Math.max(0, name.length() - 15));
+        if (Character.isLetterOrDigit(hostName.charAt(0))) {
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java]: it seems digit it not supported as first char ? @shwstppr 

https://github.com/apache/cloudstack/blob/1272b130878d0d8eb73caad2963343082d4be3fc/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L4104-L4109

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by abh1sar** [comment]
@shwstppr I am getting this NPE with a Windows10 qcow2 template. Not sure if I did something wrong.
I have a mixed kvm, vmware env.

Screenshot 2025-09-30 at 4 11 49 PM
Screenshot 2025-09-30 at 4 10 58 PM

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@abh1sar please try one again with new packages. Added a change. I didn't realize we store guest OSes with null name.

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by abh1sar — APPROVED** [review]
Tested on Windows and Linux VM. The Windows VM name is getting truncated correctly.

Image

Image

**Comment by abh1sar** [comment]
@shwstppr please see if we need to add this to documentation?

**Comment by shwstppr** [comment]
Thanks @abh1sar. (I've also added minor refactoring to not consider OS as Windows if both name and display_name turn out to be NULL)
Will check and update regarding documentation

**Comment by shwstppr** [comment]
Added doc PR: https://github.com/apache/cloudstack-documentation/pull/575

@blueorangutan package

File: server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java [hunk 3]
```diff
@@ -1954,13 +1960,46 @@ public void updateVmDetails(Map<String, String> deployParams, Map<String, String
...
+    }
+
+    protected Pair<String, String> getNextVmHostAndDisplayName(AutoScaleVmGroupVO asGroup, VirtualMachineTemplate template) {
+        boolean isWindows = isWindowsOs(template);
         String vmHostNameSuffix = "-" + asGroup.getNextVmSeq() + "-" +
                 RandomStringUtils.random(VM_HOSTNAME_RANDOM_SUFFIX_LENGTH, 0, 0, true, false, (char[])null, new SecureRandom()).toLowerCase();
         // Truncate vm group name because max length of vm name is 63
         int subStringLength = Math.min(asGroup.getName().length(), 63 - VM_HOSTNAME_PREFIX.length() - vmHostNameSuffix.length());
-        return VM_HOSTNAME_PREFIX + asGroup.getName().substring(0, subStringLength) + vmHostNameSuffix;
+        String name = VM_HOSTNAME_PREFIX + asGroup.getName().substring(0, subStringLength) + vmHostNameSuffix;
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java:1996]: Value for `VM_HOSTNAME_PREFIX` is `autoScaleVm-` which is 12 characters leaving only 3 characters for the rest of the string. If we assume the ASG name is 3 letters only, that itself will become 15 characters and won't be unique for VMs.

File: server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java [hunk 4]
```diff
@@ -1954,13 +1960,46 @@ public void updateVmDetails(Map<String, String> deployParams, Map<String, String
...
+        if (!isWindows || name.length() <= 15) {
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java]: IMO, we can get rid of the `name.length() <= 15` check.

`VM_HOSTNAME_RANDOM_SUFFIX_LENGTH` is set to 6. So, excluding the size of ASG's name, `name.length` will always be at least 18 characters. So, this check will always be false.

Also, let's use a constant instead of the number `15` or add some documentation on from where did we arrive at the number 15.

**Review by vishesh92 — COMMENTED** [review]
left some comments.

File: server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java (hunk 3 above)
Comment (vishesh92) [reply server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java:1996]: Just noticed how we are truncating the string. ignore this comment.

File: server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java (hunk 4 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java]: Documentation PR is there already https://github.com/apache/cloudstack-documentation/pull/575

Comment (vishesh92) [reply server/src/main/java/com/cloud/network/as/AutoScaleManagerImpl.java]: I meant some documentation in the code.

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]

**Comment by weizhouapache** [comment]
> Tested on Windows and Linux VM. The Windows VM name is getting truncated correctly.
> 
> Image 

to be frank, I think the name is a bit confusing

can we use a formatted shortname like `asgroup-xxxxxx` or `asg-xx-xxxxxx` instead ?

**Comment by DaanHoogland** [comment]
@weizhouapache @shwstppr is this not ready yet?

**Comment by shwstppr** [comment]
@DaanHoogland based on the latest comments I think we would need changes in naming implementation. I would close this for now for a different solution

**Comment by weizhouapache** [comment]
discussed with @shwstppr , I made some changes on this PR on the name convention of autoscale Windows VM

now the vm name and display name look like
image

the last 6 letters are the same in the two names. they are generated by `RandomStringUtils.random`

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by RosiKyu** [comment]
@blueorangutan package

**Comment by RosiKyu** [comment]
@blueorangutan package

**Comment by RosiKyu** [comment]
@blueorangutan package

**Review by RosiKyu — APPROVED** [review]
LGTM

<b style="font-weight:normal;" id="docs-internal-guid-87157fc4-7fff-7297-d244-1fdfdbecdd92"><div dir="ltr" style="margin-left:0pt;" align="left">
Test Case | Expected | Actual | Status
-- | -- | -- | --
Windows hostname ≤ 15 chars | as-WinVm-xxxxxx | as-WinVm-cifpcf | PASS
Windows displayname full | autoScaleVm-...-1-xxxxxx | autoScaleVm-windows-autoscale-test-1-cifpcf | PASS
Linux name = displayname | Same value | Both autoScaleVm-linux-autoscale-test-1-pjudpx | PASS
No regression for Linux | Full hostname format | Full hostname format | PASS

</div></b>


**Windows VMs**

```
(localcloud) 🐱 > list virtualmachines listall=true keyword=as-WinVm filter=id,name,displayname,state
{
  "count": 3,
  "virtualmachine": [
    {
      "displayname": "autoScaleVm-windows-autoscale-test-1-cifpcf",
      "id": "b13dd0d8-b424-4d55-979a-797b7cf5040c",
      "name": "as-WinVm-cifpcf",
      "state": "Running"
    },
    {
      "displayname": "autoScaleVm-windows-autoscale-test-2-xgvxsl",
      "id": "0eca7403-7ca9-498f-9eda-7582bb179d6f",
      "name": "as-WinVm-xgvxsl",
      "state": "Running"
    },
    {
      "displayname": "autoScaleVm-windows-autoscale-test-3-cacjld",
      "id": "966ea9c0-a16b-4ff8-9bb6-323660814f95",
      "name": "as-WinVm-cacjld",
      "state": "Running"
    }
  ]
}
```

**Linux VMs**

```
(localcloud) 🐱 > list virtualmachines listall=true keyword=autoScaleVm-linux filter=id,name,displayname,state
{
  "count": 1,
  "virtualmachine": [
    {
      "displayname": "autoScaleVm-linux-autoscale-test-1-pjudpx",
      "id": "24a59eb9-d874-4717-aed0-ecda7ecca4b6",
      "name": "autoScaleVm-linux-autoscale-test-1-pjudpx",
      "state": "Running"
    }
  ]
}
```

**DB Evidence**

```
mysql> SELECT 
    ->     v.id,
    ->     v.instance_name,
    ->     v.name AS hostname,
    ->     v.display_name,
    ->     v.state,
    ->     g.display_name AS guest_os
    -> FROM vm_instance v
    -> LEFT JOIN guest_os g ON v.guest_os_id = g.id
    -> WHERE v.display_name LIKE 'autoScaleVm%'
    -> ORDER BY v.created DESC;
+----+---------------+-------------------------------------------+---------------------------------------------+---------+------------------------------+
| id | instance_name | hostname                                  | display_name                                | state   | guest_os                     |
+----+---------------+-------------------------------------------+---------------------------------------------+---------+------------------------------+
|  8 | i-2-8-VM      | autoScaleVm-linux-autoscale-test-1-pjudpx | autoScaleVm-linux-autoscale-test-1-pjudpx   | Running | CentOS 5.5 (64-bit)          |
|  7 | i-2-7-VM      | as-WinVm-cacjld                           | autoScaleVm-windows-autoscale-test-3-cacjld | Running | Windows Server 2019 (64-bit) |
|  6 | i-2-6-VM      | as-WinVm-xgvxsl                           | autoScaleVm-windows-autoscale-test-2-xgvxsl | Running | Windows Server 2019 (64-bit) |
|  5 | i-2-5-VM      | as-WinVm-cifpcf                           | autoScaleVm-windows-autoscale-test-1-cifpcf | Running | Windows Server 2019 (64-bit) |
+----+---------------+-------------------------------------------+---------------------------------------------+---------+------------------------------+
4 rows in set (0.00 sec)
```

**UI Evidence**

image

image
