### PR TITLE
engine/schema: prepend algorithm to checksum during systemvm template registration

### LINKED ISSUE #12042: Cloudstack 4.22 upgrade: SystemVM template update fails
### problem

After upgrading from cloudstack 4.21.0 to 4.22.0 on Ubuntu 24.04 using the official packages, it was expected the systemvm template would be installed for 4.22, however an error is shown:

Image

Image

### versions

4.22.0 on Ubuntu 24.04.  KVM hypervisor.

### The steps to reproduce the bug

1. Start with a working 4.21.0 cluster
2. Upgrade all nodes to 4.22
3. Observe systemvm template was not updated

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #12042

No idea how to reproduce the issue. However, 2 users have faced the same issue which seems to be caused by missing `{SHA-512}` algorithm of checksum value.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

File: utils/src/main/java/org/apache/cloudstack/utils/security/DigestHelper.java [hunk 1]
```diff
@@ -142,4 +142,18 @@ public static String calculateChecksum(File file) {
             throw new CloudRuntimeException(errMsg, e);
         }
     }
+
+    public static String prependAlgorithm(String checksum) {
+        if (StringUtils.isEmpty(checksum)) {
+            return checksum;
+        }
+        int checksumLength = checksum.length();
+        for (Map.Entry<String, Integer> entry : paddingLengths.entrySet()) {
```
Comment (weizhouapache) [inline utils/src/main/java/org/apache/cloudstack/utils/security/DigestHelper.java:152]:
```suggestion
        Map<String, Integer> paddingLengths = getChecksumLengthsMap();
        for (Map.Entry<String, Integer> entry : paddingLengths.entrySet()) {
```

**Comment by weizhouapache** [comment]
@blueorangutan package
