### PR TITLE
Fix of creating volumes from snapshots without backup to secondary storage

### LINKED ISSUE #4433: Failed to create VOLUME from snapshot
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
snapshot
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0
~~~

##### OS / ENVIRONMENT

CentOS 7.7 KVM QEMU 2.12.0,libvirt 4.5.0
Ceph 14.2.10

##### SUMMARY

snapshot.backup.to.secondary=false
kvm.snapshot.enabled=true

When creating a new VOLUME through a VOLUME snapshot,
Only the first snapshot of each VOLUME is successful;
No other snapshots of the same VOLUME can create a new VOLUME

"Path" is missing from CopyCommand: "snapshots/2/5445/4e130b18-a495-4220-8c8d-118d186e961f"

CopyCommand:
{
	"org.apache.cloudstack.storage.command.CopyCommand": {
		"srcTO": {
			"org.apache.cloudstack.storage.to.SnapshotObjectTO": {
				"volume": {
					"uuid": "8c39f2f5-9b18-494e-b990-969d9318eeff",
					"volumeType": "ROOT",
					"dataStore": {
						"org.apache.cloudstack.storage.to.PrimaryDataStoreTO": {
							"uuid": "049f30ad-d4ec-33cb-a0e3-e34df5f2f757",
							"id": 2,
							"poolType": "RBD",
							"host": "10.226.15.3,10.226.15.4,10.226.15.5",
							"path": "cloudstack",
							"port": 6789,
							"url": "RBD://10.226.15.3,10.226.15.4,10.226.15.5/cloudstack/?ROLE=Primary&STOREUUID=049f30ad-d4ec-33cb-a0e3-e34df5f2f757",
							"isManaged": false
						}
					},
					"name": "ROOT-4158",
					"size": 107374182400,
					"path": "8c39f2f5-9b18-494e-b990-969d9318eeff",
					"volumeId": 5445,
					"vmName": "i-2-4158-VM",
					"accountId": 2,
					"format": "QCOW2",
					"provisioningType": "THIN",
					"id": 5445,
					"deviceId": 0,
					"hypervisorType": "KVM",
					"directDownload": false
				},
				"dataStore": {
					"com.cloud.agent.api.to.NfsTO": {
						"_url": "nfs://10.226.15.21/nfs/secstorage",
						"_role": "Image"
					}
				},
				"vmName": "i-2-4158-VM",
				"name": "aaaaa2",
				"hypervisorType": "KVM",
				"id": 27345,
				"quiescevm": false,
				"physicalSize": 0
			}
		},
		"destTO": {
			"org.apache.cloudstack.storage.to.VolumeObjectTO": {
				"uuid": "32cc7365-9bc3-49c5-87f1-871a96fb0bf7",
				"volumeType": "DATADISK",
				"dataStore": {
					"org.apache.cloudstack.storage.to.PrimaryDataStoreTO": {
						"uuid": "049f30ad-d4ec-33cb-a0e3-e34df5f2f757",
						"id": 2,
						"poolType": "RBD",
						"host": "10.226.15.3,10.226.15.4,10.226.15.5",
						"path": "cloudstack",
						"port": 6789,
						"url": "RBD://10.226.15.3,10.226.15.4,10.226.15.5/cloudstack/?ROLE=Primary&STOREUUID=049f30ad-d4ec-33cb-a0e3-e34df5f2f757",
						"isManaged": false
					}
				},
				"name": "aaaaa2-Volume",
				"size": 107374182400,
				"volumeId": 5447,
				"accountId": 2,
				"format": "QCOW2",
				"provisioningType": "THIN",
				"id": 5447,
				"hypervisorType": "KVM",
				"directDownload": false
			}
		},
		"executeInSequence": false,
		"options": {},
		"options2": {},
		"wait": 10800
	}
}

Log:

2020-10-28 09:03:55,535 WARN  [o.a.c.s.d.ObjectInDataStoreManagerImpl] (API-Job-Executor-1:ctx-d3f6d1cd job-127275 ctx-f465d613) (logid:91387467) Unsupported data object (VOLUME, org.apache.cloudstack.storage.datastore.PrimaryDataStoreImpl@2b441866), no need to delete from object in store ref table
2020-10-28 09:03:55,539 DEBUG [o.a.c.e.o.VolumeOrchestrator] (API-Job-Executor-1:ctx-d3f6d1cd job-127275 ctx-f465d613) (logid:91387467) Failed to create volume from snapshot:java.lang.NullPointerException
	at com.cloud.hypervisor.kvm.storage.KVMStorageProcessor.createVolumeFromSnapshot(KVMStorageProcessor.java:1599)
	at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.execute(StorageSubsystemCommandHandlerBase.java:110)
	at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.handleStorageCommands(StorageSubsystemCommandHandlerBase.java:57)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStorageSubSystemCommandWrapper.execute(LibvirtStorageSubSystemCommandWrapper.java:36)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtStorageSubSystemCommandWrapper.execute(LibvirtStorageSubSystemCommandWrapper.java:30)
	at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:89)
	at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1665)
	at com.cloud.agent.Agent.processRequest(Agent.java:644)
	at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1069)
	at com.cloud.utils.nio.Task.call(Task.java:83)
	at com.cloud.utils.nio.Task.call(Task.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

##### STEPS TO REPRODUCE

~~~
1. Create a VOLUME snapshot;
2. Create VOLUME from the volume snapshot (successful);
3. Create a VOLUME snapshot;
4. Create VOLUME from volume snapshot (failure);

~~~

##### EXPECTED RESULTS

~~~
1. Create a VOLUME snapshot;
2. Create VOLUME from the volume snapshot (successful);
3. Create a VOLUME snapshot;
4. Create VOLUME from volume snapshot (successful);
~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by slavkap**
### Description

Fixes #4433 

- `snapshot.backup.to.secondary=false`
- Create 2 or more snapshots on Ceph/NFS
- Create volume/template from a snapshot. The snapshot first is copied to secondary storage
- Create volume/template from the second snapshot. The snapshot is not copied to secondary because the snapshot info is retrieved with the wrong SQL query. Operation fails.

The problem appears on Ceph/NFS but it probably affects other storage plugins.
Bypassing secondary storage is supported only for Ceph primary storage, but it didn't cover the functionality to create volumes from snapshots which are kept only on Ceph.

With this fix, if you create snapshots only on NFS and try to create volume/template from a snapshot first, the snapshots are copied to secondary storage. For Ceph, the snapshot will be copied to secondary only when you create a template from a snapshot.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?

Manual tests
hypervisor KVM
- create RBD volumes from RBD snapshots - the snapshots are not copied to secondary storage
- create NFS volumes from RBD snapshots - the snapshots are not copied to secondary storage
- create templates from RBD snapshots - the snapshot is copied to secondary storage
- create templates from NFS snapshots - the snapshot is copied to secondary storage
- create NFS volumes from NFS snapshots - the snapshot is copied to secondary storage

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

File: engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java [hunk 1]
```diff
@@ -454,18 +456,25 @@ public VolumeInfo createVolumeFromSnapshot(Volume volume, Snapshot snapshot, Use
...
+            //Skipping the backup to secondary storage with NFS/FS could be supported when CLOUDSTACK-5297 is accepted with small enhancement in:
+            //KVMStorageProcessor::createVolumeFromSnapshot and CloudStackPrimaryDataStoreDriverImpl::copyAsync/createAsync
+            if ((!backupSnapToSecondary && (srcPool.getPoolType() == StoragePoolType.NetworkFilesystem || srcPool.getPoolType() == StoragePoolType.Filesystem))) {
+                SnapshotStrategy snapshotStrategy = _storageStrategyFactory.getSnapshotStrategy(snapshot, SnapshotOperation.BACKUP);
+                snapshotStrategy.backupSnapshot(snapInfo);
+                // Attempt to grab it again.
+                snapInfo = snapshotFactory.getSnapshot(snapshot.getId(), dataStoreRole);
+                if (snapInfo == null) {
+                    throw new CloudRuntimeException("Cannot find snapshot " + snapshot.getId() + " on secondary and could not create backup");
+                }
```
Comment (DaanHoogland) [inline engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/VolumeOrchestrator.java:473]: can you extract this to a separate method, please?

**Review by DaanHoogland — COMMENTED** [review]
clgtm, some comments about readability

File: plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java [hunk 2]
```diff
@@ -287,20 +288,45 @@ public void copyAsync(DataObject srcdata, DataObject destData, AsyncCompletionCa
...
+            StoragePoolVO storagePoolVO = primaryStoreDao.findById(destStore.getId());
             if (storagePoolVO != null && storagePoolVO.getPoolType() == Storage.StoragePoolType.CLVM) {
                 return true;
             }
+        } else if (srcData.getType() == DataObjectType.SNAPSHOT && destData.getType() == DataObjectType.VOLUME) {
+            DataStore srcStore = srcData.getDataStore();
+            if (srcStore.getRole() == DataStoreRole.Primary && destStore.getRole() == DataStoreRole.Primary) {
+                StoragePoolVO srcStoragePoolVO = primaryStoreDao.findById(srcStore.getId());
+                StoragePoolVO dstStoragePoolVO = primaryStoreDao.findById(destStore.getId());
+                if (srcStoragePoolVO != null && srcStoragePoolVO.getPoolType() == StoragePoolType.RBD
```
[the remark this answers is not in the document]
Comment (slavkap) [reply plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:324]: @DaanHoogland, thanks for the review! I will make the rest of the comments, but I can't entirely agree here. I mean that for me, it's better to compare enums with `==`. In your case, it's not safe to invoke `equals()` if I remove the check for a null value.
 Which is the preferred way in ACS to compare enums?

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 3]
```diff
@@ -1639,6 +1673,74 @@ public Answer createVolumeFromSnapshot(final CopyCommand cmd) {
         }
     }
 
+    private KVMPhysicalDisk createRBDvolumeFromRBDSnapshot(KVMPhysicalDisk volume, String snapshotName, String name,
+            PhysicalDiskFormat format, long size, KVMStoragePool destPool, int timeout) {
+
+        KVMStoragePool srcPool = volume.getPool();
+        KVMPhysicalDisk disk = null;
+        String newUuid = name;
+        int rbdFeatures = 61;
```
Comment (nvazquez) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1682]: Minor: if this is the same as `LibvirtStorageAdaptor.rbdFeatures`, can we expose it and use it instead of a new variable on this method?

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 4]
```diff
@@ -1639,6 +1673,74 @@ public Answer createVolumeFromSnapshot(final CopyCommand cmd) {
...
+
+        format = PhysicalDiskFormat.RAW;
+        disk = new KVMPhysicalDisk(destPool.getSourceDir() + "/" + newUuid, newUuid, destPool);
+        disk.setFormat(format);
+        if (size > volume.getVirtualSize()) {
```
Comment (nvazquez) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1687]: What about:
````
disk.setSize(size > volume.getVirtualSize() ? size : volume.getVirtualSize());
disk.setVirtualSize(size > volume.getVirtualSize() ? size : disk.getSize());
````

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 5]
```diff
@@ -1639,6 +1673,74 @@ public Answer createVolumeFromSnapshot(final CopyCommand cmd) {
...
+            boolean snapFound = false;
+            for (RbdSnapInfo snap : snaps) {
+                if (snapshotName.equals(snap.name)) {
+                    snapFound = true;
+                    break;
+                }
+            }
+
+            if (!snapFound) {
+                return null;
```
Comment (nvazquez) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1717]: Maybe add a log line as well to help debugging/tracing errors?

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 6]
```diff
@@ -1639,6 +1673,74 @@ public Answer createVolumeFromSnapshot(final CopyCommand cmd) {
...
+            srcImage.snapUnprotect(snapshotName);
+            rbd.close(srcImage);
+            r.ioCtxDestroy(io);
+        } catch (RadosException e) {
+            s_logger.error(String.format("Failed due to %s", e.getMessage()));
+            disk = null;
+        } catch (RbdException e) {
+            s_logger.error(String.format("Failed due to: %s", e.getMessage()));
+            disk = null;
+        }
```
Comment (GutoVeronezi) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1739]: We could join the catches and add the exception as to the log:

```suggestion
        } catch (RbdException | RadosException e) {
            s_logger.error(String.format("Failed due to %s", e.getMessage()), e);
            disk = null;
        }
```

File: plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (GutoVeronezi) [reply plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:324]: I think that what @DaanHoogland meant is:
```suggestion
                if (srcStoragePoolVO != null && StoragePoolType.RBD.equals(srcStoragePoolVO.getPoolType())
```

Technically there are no differences in comparing `enums` with `equals` or `==`, because `Enum#equals` implements `==`:
```java
    public final boolean equals(Object other) {
        return this==other;
    }
```

As far as I know, there is no consensus about it, however I would go with Daan and use `equals` to compare `enums`, as any other object we compare, and let `==` only to primitive types.

[the remark this answers is not in the document]
Comment (slavkap) [reply plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:324]: Thanks, @GutoVeronezi, for the code review! Yes, I know what the implementation of `equals` of Enum is. That's why I thought that it's a developer decision which one to use :) I will make the requested changes

**Comment by slavkap** [comment]
Thanks, @DaanHoogland, @nvazquez, @GutoVeronezi, for the code reviews! I made the requested changes

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test
