### PR TITLE
Mask vncPasswd being logged in agent.log

### LINKED ISSUE #10847: Agent logs libvirt xml while live migrating vms
### problem

When live migrating vms, the whole libvirt xml definition gets logged to /var/log/cloudstack/agent/agent.log (Log Level set to INFO). This includes for example the vnc password, and i guess it would also include the luks password for encrypted volumes.

```
2025-05-09 10:38:46,164 INFO  [resource.wrapper.LibvirtMigrateCommandWrapper] (agentRequest-Handler-1:null) (logid:b55d2348) Starting live migration of instance [i-58-xxx-VM] to destination host [qemu+tls://10.xx.xx.xx/system] having the final XML configuration: [<domain type='kvm'>
  <name>i-58-4522-VM</name>
  <uuid>511d4065-bdd8-4f5f-8dd3-xxxxxxx</uuid>
  <description>Ubuntu 22.04 LTS</description>
  <memory unit='KiB'>67108864</memory>
  <currentMemory unit='KiB'>67108864</currentMemory>
  <vcpu placement='static'>16</vcpu>
  <iothreads>1</iothreads>
  <cputune>
    <shares>1250</shares>
    <period>10000</period>
    <quota>10000</quota>
  </cputune>
  <resource>
    <partition>/machine</partition>
  </resource>
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Apache Software Foundation</entry>
      <entry name='product'>CloudStack KVM Hypervisor</entry>
      <entry name='uuid'>511d4065-bdd8-4f5f-8dd3-xxxxxxxx</entry>
    </system>
  </sysinfo>
  <os>
    <type arch='x86_64' machine='pc-i440fx-8.2'>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
    <smbios mode='sysinfo'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='host-model' check='partial'>
    <topology sockets='4' dies='1' cores='4' threads='1'/>
  </cpu>
  <clock offset='utc'>
    <timer name='kvmclock'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native' discard='unmap'/>
      <source file='/mnt/2c568429-23f5-3e75-8208-xxxxx/0b3ca1d6-bdba-4cc8-bb7f-xxxxx'/>
      <target dev='sda' bus='scsi'/>
      <serial>0b3ca1d6bdba4xxxxx</serial>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native' discard='unmap'/>
      <source file='/mnt/2c568429-23f5-3e75-8208-xxxxx/cd683178-03ad-4834-b51b-xxxxxx'/>
      <target dev='sdb' bus='scsi'/>
      <serial>cd68317803ad4834xxx</serial>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <target dev='hdc' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='1' target='0' unit='0'/>
    </disk>
    <controller type='scsi' index='0' model='virtio-scsi'>
      <driver queues='16' iothread='1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </controller>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </controller>
    <interface type='bridge'>
      <mac address='02:06:01:02:xx:xx'/>
      <source bridge='xxxx'/>
      <bandwidth>
        <inbound average='640000' peak='640000'/>
        <outbound average='640000' peak='640000'/>
      </bandwidth>
      <model type='virtio'/>
      <link state='up'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='unix'>
      <source mode='bind' path='/var/lib/libvirt/qemu/i-58-xxxx-VM.org.qemu.guest_agent.0'/>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='x.x.x.x' passwd='**XYZXYZ**'>
      <listen type='address' address='x.x.x.x'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <watchdog model='i6300esb' action='none'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </watchdog>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </memballoon>
    <rng model='virtio'>
      <rate bytes='2048' period='1000'/>
      <backend model='random'>/dev/random</backend>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </rng>
  </devices>
</domain>
].
```

### versions

ACS 4.19.2

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by sudo87**
### Description

This PR fixes https://github.com/apache/cloudstack/issues/10847

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by abh1sar — APPROVED** [review]
LGTM

**Comment by abh1sar** [comment]
@blueorangutan package

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java [hunk 1]
```diff
@@ -158,7 +158,7 @@ Use VIR_DOMAIN_XML_SECURE (value = 1) prior to v1.0.0.
             final String target = command.getDestinationIp();
             xmlDesc = dm.getXMLDesc(xmlFlag);
             if (logger.isDebugEnabled()) {
-                logger.debug(String.format("VM [%s] with XML configuration [%s] will be migrated to host [%s].", vmName, xmlDesc, target));
+                logger.debug("VM {} with XML configuration {} will be migrated to host {}.", vmName, maskSensitiveInfoInXML(xmlDesc), target);
             }
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java:162]:
```suggestion
            logger.debug("VM {} with XML configuration {} will be migrated to host {}.", vmName, () -> maskSensitiveInfoInXML(xmlDesc), target);
```
just a suggestion, (may apply below as well)

**Review by DaanHoogland — APPROVED** [review]
clgtm, the isDebugEnabled are not strictly needed anymore.

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java [hunk 2]
```diff
@@ -910,4 +910,11 @@ private boolean findSourceNode(Document doc, Node diskNode, String vmName, Strin
         }
         return false;
     }
+
+    public static String maskSensitiveInfoInXML(String xmlDesc) {
+        if (xmlDesc == null) return null;
+        // Mask VNC password in XML for logging
+        return xmlDesc.replaceAll("(graphics\\s+[^>]*type=['\"]vnc['\"][^>]*passwd=['\"])([^'\"]*)(['\"])",
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java:914]: we can also just remove it, btw

**Comment by abh1sar** [comment]
@blueorangutan test

**Comment by sudo87** [comment]
Thanks @DaanHoogland for your review and suggestions. Let me know if my response makes sense:

1. Per argument lambda is not supported, it will perform toString instead of evaluation. It wont work the way we expect:
```
logger.debug("VM {} with XML configuration {} will be migrated to host {}.", vmName, () -> maskSensitiveInfoInXML(xmlDesc), target);
```
2. logger.isDebugEnabled check is added to avoid maskSensitiveInfoInXML invocation. Which is not expensive operation but not required if debug is not enabled. We can definitely remove it.

**Comment by DaanHoogland** [comment]
> 1. Per argument lambda is not supported, it will perform toString instead of evaluation. It wont work the way we expect:
> 
> ```
> logger.debug("VM {} with XML configuration {} will be migrated to host {}.", vmName, () -> maskSensitiveInfoInXML(xmlDesc), target);
> ```

this is not how I read the documentation, but I haven’t tested it. it should lazily evaluate the lambda ony if debug is enabled.

> 2. logger.isDebugEnabled check is added to avoid maskSensitiveInfoInXML invocation. Which is not expensive operation but not required if debug is not enabled. We can definitely remove it.

I do not care if point 1 is out of the way. It is just cleaner code. If you are right about point 1 we have a bigger issue.

I do not think either should stop this PR, but in general my experience is that follow-ups don’t happen,...

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java (hunk 2 above)
Comment (sudo87) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtMigrateCommandWrapper.java:914]: Wont it confuse admin whether vnc section is not part of the xml or not?

**Comment by RosiKyu** [comment]
**WIP** 

### Test Case 1: VM Start - VNC Password Masking

**Objective** Verify that the VNC password is masked (shown as *****) in the agent log when a VM is started.

**Test Steps**

1. Deploy a new VM (or start a stopped VM) in the CloudStack environment
2. SSH to the KVM host where the VM is running
3. Search the agent log for VM start entries containing VNC graphics configuration:

```
grep -i "Starting.*:" /var/log/cloudstack/agent/agent.log | tail -5
```

4. Search for VNC password entries in the log:

```
grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
```

4. Verify no unmasked passwords exist:

```
grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Expected Result** 

- The VNC password in the logged XML should be masked as `passwd='*****'`
- No unmasked VNC passwords should appear in the agent log

**Actual Result** **PASSED** 

- The VNC password is correctly masked as `passwd='*****'`
- No unmasked VNC passwords found in the log

**Evidence**

- VM Start log entry found:

```
2026-01-18 16:57:28,843 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-5:[]) (logid:) Starting r-4-VM : <domain type='kvm'>
```

VNC password masked (grep output):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
```

- No unmasked passwords (empty result confirms fix):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

### Test Case 2: Live Migration - VNC Password Masking.

**Objective** Verify that the VNC password is masked (shown as *****) in the agent log when a VM is live migrated between KVM hosts.

**Test Steps**

1. Identify a running user VM and the host it is currently on
2. Live migrate the VM to another KVM host:
3. After migration completes, SSH to the source host (where VM was before migration) and search for live migration log entries:

```
 grep -i "live migration" /var/log/cloudstack/agent/agent.log
```

4. Search for VNC password entries:

```
grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
```

5. Check for any unmasked passwords:

```
grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Expected Result**

- All VNC passwords in the logged XML should be masked as `passwd='*****'`
- No unmasked VNC passwords should appear in any migration-related log entries

**Actual Result** **PARTIALLY PASSED / BUG FOUND**

- The main migration XML configuration is correctly masked
- However, the `replaceIpForVNCInDescFile` log message **still exposes the actual VNC password**

**Evidence**

- Live migration entry (masked correctly):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -i "live migration" /var/log/cloudstack/agent/agent.log
2026-01-18 17:05:14,161 INFO  [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Starting live migration of instance i-2-3-VM to destination host qemu+tls://10.1.33.95/system having the final XML configuration: <domain type='kvm'>
```

- VNC password entries (mixed results):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='*****'>
2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) 
```

- Replaced the VNC IP address 

```
[<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='*****'>
```

- Unmasked password found (bug):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) 
```

- Replaced the VNC IP address 

```
[<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
```

**Bug Details**

The `replaceIpForVNCInDescFile` method in `LibvirtMigrateCommandWrapper.java` logs the old and new XML snippets when replacing the VNC IP address, but this log statement is not using the maskSensitiveInfoInXML() function, causing the actual VNC password (UzAp0PQ9) to be exposed in the agent log.

**Affected log message:** "Replaced the VNC IP address [...] with [...]"

###  Test Case 3: Console Access Regression Test

**Objective** Verify that the VNC password masking in logs does not break the actual VM console access functionality.

**Test Steps**

1. Open the CloudStack UI
2. Navigate to the test VM (i-2-3-VM)
3. Click on "View Console" button
4. Verify the console window opens and displays the VM screen
5. Verify keyboard input works (login to the VM)

**Expected Result**

- Console should connect successfully
- VM display should be visible
- User should be able to interact with the VM (keyboard/mouse)

**Actual Result: ** **PASSED**

- Console connected successfully via Console Proxy
- VM display visible (CentOS 5.5 login screen)
- Successfully logged in as root - keyboard input working

**Evidence**

Image

### Test Case 4: VM Stop and Start - VNC Password Masking

**Objective** Verify that the VNC password remains masked in the agent log when a VM is stopped and then started again.

**Test Steps**

1. Stop the test VM:
2. Wait for the VM to stop completely
3. Start the VM again:
4. Check the agent log on the host where the VM started:

```
grep -i "Starting.*:" /var/log/cloudstack/agent/agent.log | tail -5
grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Expected Result**

- The VNC password in the logged XML should be masked as `passwd='*****'`
- No unmasked VNC passwords should appear in the agent log

**Actual Result:** **PASSED**

- VM stopped and started successfully on kvm2
- VNC password correctly masked in the start log

**Evidence:**

- VM Start log entry found on kvm2:

```
2026-01-18 17:17:44,269 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-4:[]) (logid:) Starting i-2-3-VM : <domain type='kvm'>
```

- VNC password masked:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.33.95' passwd='*****'/>
```

- No unmasked passwords found:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Review by RosiKyu — CHANGES_REQUESTED** [review]
The PR successfully masks VNC passwords in most scenarios, but there is one missed log statement in the `LibvirtMigrateCommandWrapper` that still exposes the actual VNC password during all types of live migration.

**Bug Summary**

- Affected log message: "Replaced the VNC IP address [...] with [...]"
- Location: `LibvirtMigrateCommandWrapper.java` - `replaceIpForVNCInDescFile` method (or similar)

**Impact:** VNC password exposed in DEBUG level logs during any live migration operation

Confirmed in **TC2**, **TC7**, and **TC8** across both migration directions and storage migration

## Test Execution Summary

| Test Case | Description | Result |
|-----------|-------------|--------|
| TC1 | VM Start - VNC Password Masking | PASSED |
| TC2 | Live Migration - VNC Password Masking | **PARTIAL** |
| TC3 | Console Access Regression | PASSED |
| TC4 | VM Stop/Start - VNC Password Masking | PASSED |
| TC5 | VM Reboot - VNC Password Masking | PASSED  |
| TC6 | System VM - VNC Password Masking | PASSED |
| TC7 | Reverse Migration - VNC Password Masking | **PARTIAL** |
| TC8 | Storage Migration - VNC Password Masking | **PARTIAL** |

## Detailed Test Report 

### Test Case 1: VM Start - VNC Password Masking

**Objective** Verify that the VNC password is masked (shown as *****) in the agent log when a VM is started.

**Test Steps**

1. Deploy a new VM (or start a stopped VM) in the CloudStack environment
2. SSH to the KVM host where the VM is running
3. Search the agent log for VM start entries containing VNC graphics configuration:

```
grep -i "Starting.*:" /var/log/cloudstack/agent/agent.log | tail -5
```

4. Search for VNC password entries in the log:

```
grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
```

4. Verify no unmasked passwords exist:

```
grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Expected Result** 

- The VNC password in the logged XML should be masked as `passwd='*****'`
- No unmasked VNC passwords should appear in the agent log

**Actual Result** **PASSED** 

- The VNC password is correctly masked as `passwd='*****'`
- No unmasked VNC passwords found in the log

**Evidence**

- VM Start log entry found:

```
2026-01-18 16:57:28,843 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-5:[]) (logid:) Starting r-4-VM : <domain type='kvm'>
```

VNC password masked (grep output):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
```

- No unmasked passwords (empty result confirms fix):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

### Test Case 2: Live Migration - VNC Password Masking.

**Objective** Verify that the VNC password is masked (shown as *****) in the agent log when a VM is live migrated between KVM hosts.

**Test Steps**

1. Identify a running user VM and the host it is currently on
2. Live migrate the VM to another KVM host:
3. After migration completes, SSH to the source host (where VM was before migration) and search for live migration log entries:

```
 grep -i "live migration" /var/log/cloudstack/agent/agent.log
```

4. Search for VNC password entries:

```
grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
```

5. Check for any unmasked passwords:

```
grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Expected Result**

- All VNC passwords in the logged XML should be masked as `passwd='*****'`
- No unmasked VNC passwords should appear in any migration-related log entries

**Actual Result** **PARTIALLY PASSED / BUG FOUND**

- The main migration XML configuration is correctly masked
- However, the `replaceIpForVNCInDescFile` log message **still exposes the actual VNC password**

**Evidence**

- Live migration entry (masked correctly):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -i "live migration" /var/log/cloudstack/agent/agent.log
2026-01-18 17:05:14,161 INFO  [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Starting live migration of instance i-2-3-VM to destination host qemu+tls://10.1.33.95/system having the final XML configuration: <domain type='kvm'>
```

- VNC password entries (mixed results):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='*****'>
2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) 
```

- Replaced the VNC IP address 

```
[<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='*****'>
```

- Unmasked password found (bug):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) 
```

- Replaced the VNC IP address 

```
[<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
```

**Bug Details**

The `replaceIpForVNCInDescFile` method in `LibvirtMigrateCommandWrapper.java` logs the old and new XML snippets when replacing the VNC IP address, but this log statement is not using the maskSensitiveInfoInXML() function, causing the actual VNC password (UzAp0PQ9) to be exposed in the agent log.

**Affected log message:** "Replaced the VNC IP address [...] with [...]"

###  Test Case 3: Console Access Regression Test

**Objective** Verify that the VNC password masking in logs does not break the actual VM console access functionality.

**Test Steps**

1. Open the CloudStack UI
2. Navigate to the test VM (i-2-3-VM)
3. Click on "View Console" button
4. Verify the console window opens and displays the VM screen
5. Verify keyboard input works (login to the VM)

**Expected Result**

- Console should connect successfully
- VM display should be visible
- User should be able to interact with the VM (keyboard/mouse)

**Actual Result: ** **PASSED**

- Console connected successfully via Console Proxy
- VM display visible (CentOS 5.5 login screen)
- Successfully logged in as root - keyboard input working

**Evidence**

Image

### Test Case 4: VM Stop and Start - VNC Password Masking

**Objective** Verify that the VNC password remains masked in the agent log when a VM is stopped and then started again.

**Test Steps**

1. Stop the test VM:
2. Wait for the VM to stop completely
3. Start the VM again:
4. Check the agent log on the host where the VM started:

```
grep -i "Starting.*:" /var/log/cloudstack/agent/agent.log | tail -5
grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Expected Result**

- The VNC password in the logged XML should be masked as `passwd='*****'`
- No unmasked VNC passwords should appear in the agent log

**Actual Result:** **PASSED**

- VM stopped and started successfully on kvm2
- VNC password correctly masked in the start log

**Evidence:**

- VM Start log entry found on kvm2:

```
2026-01-18 17:17:44,269 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-4:[]) (logid:) Starting i-2-3-VM : <domain type='kvm'>
```

- VNC password masked:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.33.95' passwd='*****'/>
```

- No unmasked passwords found:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

### Test Case 5: VM Reboot - VNC Password Masking

**Objective** Verify that the VNC password remains masked in the agent log when a VM is rebooted.

**Test Steps:**

1. Reboot the test VM:
2. Check the agent log on the host where the VM is running:

**Expected Result**

- No new `StartCommand/XML` log entries expected (reboot is handled internally by libvirt)
- No unmasked VNC passwords should appear

**Actual Result: ** PASSED 
- VM reboot does not generate new StartCommand log entries
- Reboot is handled internally by libvirt/QEMU without CloudStack agent involvement
- No new XML configuration is logged during reboot
- Existing entries remain properly masked

**Evidence:**

- No new start entries after reboot (only TC4 entry from 17:17:44):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -i "Starting.*i-2-3-VM" /var/log/cloudstack/agent/agent.log | tail -3
2026-01-18 17:17:44,269 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-4:[]) (logid:) Starting i-2-3-VM : <domain type='kvm'>
```

- VNC password remains masked:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.33.95' passwd='*****'/>
```

- No unmasked passwords:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
```

**Notes**  VM reboot operation is handled by libvirt's internal restart mechanism and does not trigger a new CloudStack StartCommand. This is expected behavior - the PR's masking is only relevant when CloudStack explicitly logs VM XML configurations during start or migration operations.

### Test Case 6: System VM - VNC Password Masking

**Objective** Verify that the VNC password is also masked for System VMs (SSVM, CPVM, Virtual Router).

**Test Steps**

1. Check agent logs (including rotated logs) on kvm1 for SSVM s-1-VM:
2. Check agent logs (including rotated logs) on kvm2 for CPVM v-2-VM:

**Expected Result:**

- VNC passwords for System VMs should be masked as passwd='*****'
- No unmasked VNC passwords (except known TC2 bug)

**Actual Result:** **PASSED**

- SSVM (s-1-VM) start log from 2026-01-14 shows masked password
- CPVM (v-2-VM) start log from 2026-01-14 shows masked password
- All System VM VNC entries properly masked

**Evidence:**

- kvm1 - SSVM (s-1-VM) start found in rotated log:

```
/var/log/cloudstack/agent/agent.log.2026-01-14.gz:2026-01-14 14:12:47,490 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Starting s-1-VM : <domain type='kvm'>
```

- kvm1 - VNC password masking (all logs):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# zgrep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log* | head -20
/var/log/cloudstack/agent/agent.log:<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
/var/log/cloudstack/agent/agent.log:<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
/var/log/cloudstack/agent/agent.log:    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='*****'>
/var/log/cloudstack/agent/agent.log:2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
/var/log/cloudstack/agent/agent.log:    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
/var/log/cloudstack/agent/agent.log:    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='*****'>
/var/log/cloudstack/agent/agent.log.2026-01-14.gz:<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
```

(**Note:** Unmasked password visible is the known TC2 bug from migration)

- kvm2 - CPVM (v-2-VM) start found in rotated log:

```
/var/log/cloudstack/agent/agent.log.2026-01-14.gz:2026-01-14 14:13:12,611 DEBUG [resource.wrapper.LibvirtStartCommandWrapper] (AgentRequest-Handler-5:[]) (logid:) Starting v-2-VM : <domain type='kvm'>
```

- kvm2 - VNC password masking (all logs):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# zgrep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log* | head -20
/var/log/cloudstack/agent/agent.log:<graphics type='vnc' autoport='yes' listen='10.1.33.95' passwd='*****'/>
/var/log/cloudstack/agent/agent.log.2026-01-14.gz:<graphics type='vnc' autoport='yes' listen='10.1.33.95' passwd='*****'/>
```

### Test Case 7: Reverse Migration (kvm2 → kvm1)

**Objective:** Confirm that the bug found in TC2 (unmasked VNC password in "Replaced the VNC IP address" log message) is reproducible when migrating in the reverse direction.

**TestSteps:**

1. Migrate VM from kvm2 back to kvm1:
2. After migration completes, check agent log on kvm2 (source host):

**Expected Result:** All VNC passwords should be masked as passwd='*****'

**Actual Result:** PARTIAL  - Bug Confirmed

- Main migration XML configuration is properly masked
- Bug reproduced: The "Replaced the VNC IP address" log message still exposes the actual VNC password

**Evidence:** 

- Live migration entry (masked correctly):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -i "live migration" /var/log/cloudstack/agent/agent.log | tail -3
2026-01-18 17:53:20,092 INFO  [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Starting live migration of instance i-2-3-VM to destination host qemu+tls://10.1.34.189/system having the final XML configuration: <domain type='kvm'>
```

- VNC password entries (mixed results):

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log
<graphics type='vnc' autoport='yes' listen='10.1.33.95' passwd='*****'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='*****'>
2026-01-18 17:53:20,066 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='*****'>
```

- **Unmasked password confirmed (bug):**

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm2 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
2026-01-18 17:53:20,066 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
```

**Notes:** This confirms the bug identified in **TC2** is consistent and reproducible in both migration directions (kvm1→kvm2 and kvm2→kvm1). The same VNC password is exposed in both cases.

### Test Case 8: Storage Migration

**Objective:** Verify that the VNC password is masked when performing live migration with storage (migrating VM and its volumes to a different storage pool simultaneously).

**Test Steps:**

1. Check current volume location
2. Migrate VM with volume to different storage pool:

```
migrate virtualmachinewithvolume virtualmachineid=1170e952-de03-410e-8d8a-896260abf583 hostid=550f5e3f-78e6-4229-b9f4-bc0f07eca952 migrateto[0].volume=a3984f50-61fa-4d41-91a7-3d34058c3c16 migrateto[0].pool=f9d5d615-0697-31e6-9e66-978f2974640f
```

3. After migration completes, check agent log on source host (kvm1):

**Expected Result:**

- All VNC passwords should be masked as `passwd='*****'`
- Storage migration logs should not expose VNC passwords

**Actual Result** **PARTIAL - Same bug as TC2/TC7**

- VM migrated successfully from kvm1 to kvm2 with volume moved from pri1 to pri2
- Main migration XML configuration is properly masked
- Bug reproduced: The "Replaced the VNC IP address" log message exposes the actual VNC password

**Evidence:**

- VNC password entries showing the bug:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd" /var/log/cloudstack/agent/agent.log | tail -10
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
<graphics type='vnc' autoport='yes' listen='10.1.34.189' passwd='*****'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='*****'>
2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) 
Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='*****'>
    <graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='*****'>
2026-01-18 17:59:41,528 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-1:[]) (logid:) 
Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
```

- Unmasked passwords confirmed:

```
[root@ref-trl-6151-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
2026-01-18 17:05:14,129 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) 
Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
2026-01-18 17:59:41,528 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-1:[]) (logid:) Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.34.189' passwd='UzAp0PQ9'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.1.33.95' passwd='UzAp0PQ9'>
```

**Notes** Storage migration (17:59:41) uses the same LibvirtMigrateCommandWrapper code path as regular live migration
The same bug occurs regardless of whether storage is being migrated along with the VM
Volume successfully moved from pri1 (404b015d-...) to pri2 (f9d5d615-...)

**Comment by sudo87** [comment]
Thank you @RosiKyu for the extremely detailed QA validation. This is very helpful.

I have addressed the issue by masking the XML in the log statement within replaceIpForVNCInDescFileAndNormalizePassword method. Please re-test TC2, TC7, and TC8 with the updated package.

**Comment by sudo87** [comment]
@blueorangutan package

**Review by RosiKyu — APPROVED** [review]
**LGTM**

The identified issue was addressed and password is masked in all logs.


1. Migrate VM from kvm2 back to kvm1:
2. After migration completes, check agent log on kvm2 (source host):

**Expected Result:** All VNC passwords should be masked as passwd='*****'

**Actual Result** PASSED (verified after fix)
Reverse migration also shows properly masked passwords

**Evidence (after fix):**

- Agent update timeline on kvm1:
- Agent stopped:  2026-01-19 08:50:46
- Agent started:  2026-01-19 08:53:09 (with cloudstack-agent-4.20.3.0-shapeblue18646)

- Before agent update (04:59:59) - password EXPOSED:

```
[root@ref-trl-10611-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -i "Replaced the VNC IP address" /var/log/cloudstack/agent/agent.log
2026-01-19 04:59:59,508 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.0.35.40' passwd='OjdZYxCj'>
2026-01-19 09:02:39,662 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-2:[]) (logid:) Replaced the VNC IP address <graphics type='vnc' port='-1' autoport='yes' listen='10.0.35.40' passwd='*****'>
```


- After agent update (09:02:39) - password MASKED:

```
[root@ref-trl-10611-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -E "graphics.*vnc.*passwd=['\"][^*]" /var/log/cloudstack/agent/agent.log
2026-01-19 04:59:59,508 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-3:[]) (logid:) Replaced the VNC IP address [<graphics type='vnc' port='-1' autoport='yes' listen='10.0.35.40' passwd='OjdZYxCj'>
    </graphics>] with [<graphics type='vnc' port='-1' autoport='yes' listen='10.0.35.42' passwd='OjdZYxCj'>
```

(The grep for unmasked passwords only returns the old 04:59:59 entry - the new 09:02:39 entry is properly masked and does not appear)

```
[root@ref-trl-10611-k-Mol9-rositsa-kyuchukova-kvm1 ~]# grep -i "Replaced the VNC IP address" /var/log/cloudstack/agent/agent.log
2026-01-19 09:02:39,662 DEBUG [resource.wrapper.LibvirtMigrateCommandWrapper] (AgentRequest-Handler-2:[]) (logid:) Replaced the VNC IP address <graphics type='vnc' port='-1' autoport='yes' listen='10.0.35.40' passwd='*****'>
```

## Test Execution Summary

| Test Case | Description | Result |
|-----------|-------------|--------|
| TC1 | VM Start - VNC Password Masking | **PASSED** |
| TC2 | Live Migration - VNC Password Masking | **PASSED** |
| TC3 | Console Access Regression | **PASSED** |
| TC4 | VM Stop/Start - VNC Password Masking | **PASSED** |
| TC5 | VM Reboot - VNC Password Masking | **PASSED**  |
| TC6 | System VM - VNC Password Masking | **PASSED** |
| TC7 | Reverse Migration - VNC Password Masking | **PASSED** |
| TC8 | Storage Migration - VNC Password Masking | **PASSED** |

### Detailed Test Results https://github.com/apache/cloudstack/pull/12404#pullrequestreview-3675628663
