### PR TITLE
server: Purge all cookies on logout, set /client path on login

### LINKED ISSUE #4136: UI doesn't allow login if sessionkey and JSESSIONID cookies are deleted
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI (old UI, not Primate)
~~~

##### CLOUDSTACK VERSION

~~~
4.14+ (probably present on all older versions as well)
~~~

To consistently reproduce this, this is what I did:
- Login into UI, then open devtools->Application-> cookies
- Delete the sessionkey and JSESSIONID cookies (to simulate session expiry, in browser but not on mgmt server)
- Refresh UI and try to log in, you won't be able to login
- You've to wait until the previous session expires, or clear cache

The solution is for legacy UI to call the logout API when 401/unauthorised happens (logout will expire session on backend mgmt server) and clear cookies.

### PR DESCRIPTION
**Pull request by rhtyd**
This will purge all the cookies on logout including multiple sessionkey
cookies if passed. On login, this will restrict sessionkey cookie
(httponly) to the /client path like the JSESSIONID cookie.

Fixes #4136

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

Needs manual testing

### CODE REVIEW

**Comment by rhtyd** [comment]
Please review and test @davidjumani @shwstppr cc @Pearl1594

**Comment by rhtyd** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/api/ApiServlet.java [hunk 1]
```diff
@@ -213,7 +213,7 @@ void processRequestInContext(final HttpServletRequest req, final HttpServletResp
                     try {
                         responseString = apiAuthenticator.authenticate(command, params, session, remoteAddress, responseType, auditTrailSb, req, resp);
                         if (session != null && session.getAttribute(ApiConstants.SESSIONKEY) != null) {
-                            resp.addHeader("SET-COOKIE", String.format("%s=%s;HttpOnly", ApiConstants.SESSIONKEY, session.getAttribute(ApiConstants.SESSIONKEY)));
+                            resp.addHeader("SET-COOKIE", String.format("%s=%s;HttpOnly;Path=/client", ApiConstants.SESSIONKEY, session.getAttribute(ApiConstants.SESSIONKEY)));
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/api/ApiServlet.java:216]: We need to check if this is necessary or not

**Comment by rhtyd** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/api/ApiServlet.java [hunk 2]
```diff
@@ -238,9 +238,14 @@ void processRequestInContext(final HttpServletRequest req, final HttpServletResp
                             } catch (final IllegalStateException ignored) {
                             }
                         }
-                        Cookie sessionKeyCookie = new Cookie(ApiConstants.SESSIONKEY, "");
-                        sessionKeyCookie.setMaxAge(0);
-                        resp.addCookie(sessionKeyCookie);
+                        final Cookie[] cookies = req.getCookies();
+                        if (cookies != null)
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/api/ApiServlet.java:242]: @rhtyd missing brace

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/api/ApiServlet.java (hunk 1 above)
Comment (davidjumani) [reply server/src/main/java/com/cloud/api/ApiServlet.java:216]: Looks like it is necessary, if not present, two sessionkeys are present
If non-standard implementations are the case, wouldn't JSESSIONID cause issues too?
Also exploring saml logins

Comment (rhtyd) [reply server/src/main/java/com/cloud/api/ApiServlet.java:216]: @davidjumani in a deploy trillian env with this PR (or you may use the primate-qa server as well which has this PR) and both old UI and Primate, can you check side-effects when you change the context in /etc/cloudstack/management/server.properties from `/client/` to say (a) `/somenew-path` and (b) `/` and restart management server and try log-in in both legacy UI and Primate (check network an Application/cookies)

Comment (rhtyd) [reply server/src/main/java/com/cloud/api/ApiServlet.java:216]: Nevermind I tested, this will break if path is restricted to /client only; ideally shoud match the webapp context path

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Tested for local / saml users. LGTM

**Comment by rhtyd** [comment]
@davidjumani did you also test changing the context path from server properties?

**Comment by davidjumani** [comment]
When changing the path, the api calls go to the new path followed by '/client/api', due to which authorization and other calls fail. Guess some changes in the legacy ui code might be needed

**Comment by rhtyd** [comment]
@davidjumani what error/issue do you see for path `/`? Did you change the apiBase to `/api` and for legacy UI in cloud.core.. js file?

**Comment by davidjumani** [comment]
Yes made the changes in the core callback as well as primate apiBase. There was no issue when there was a context path but faced the same issue for just `/`

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@Pearl1594 please review thanks

**Comment by Pearl1594** [comment]
@rhtyd As David mentioned, the context path set to any other path than '/' works, however, the same issue of multiple session keys getting added to the api calls crops in for context.path set to '/'. There are 2 session keys : one mapped to Path: / and another mapped to path: '/api'

multiple_session_keys

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@davidjumani can you help review/test/fix, thnx

**Comment by rhtyd** [comment]
@Pearl1594 @davidjumani any progress on this?

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@rhtyd looking into it

**Comment by Pearl1594** [comment]
@rhtyd it works now - for both changing context.path to a value other that /client and for /
Have to test it for SAML login

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Tests lgtm
