### PR TITLE
directdownload: fix keytool importcert

### LINKED ISSUE #11112: Unable to register a cloud image template with direct download option enabled
### problem

Unable to register a cloud image template with direct download option enabled

### versions

ACS 4.20.1 . 4.19 

### The steps to reproduce the bug

1. Register a cloud image template with direct download option enabled 

```
Ubuntu 24.04: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
Debian 12: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
AlmaLinux 8: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-latest.x86_64.qcow2
OpenSUSE 15: https://download.opensuse.org/distribution/leap/15.5/appliances/openSUSE-Leap-15.5-Minimal-VM.x86_64-Cloud.qcow2
```

2. Exception observed 
```

2025-07-01 05:59:19,553 ERROR [c.c.a.ApiServer] (qtp1390913202-21:[ctx-3cebe65a, ctx-8c1b79c8]) (logid:6f306659) unhandled exception executing api command: [Ljava.lang.String;@15eb3095 com.cloud.utils.exception.CloudRuntimeException: URL: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2 validation failed on host Host {"id":2,"name":"ref-trl-8752-k-Mol8-kiran-chavala-kvm2","type":"Routing","uuid":"5aeefe1c-7404-40e9-92bf-b5b1445e160c"}
	at com.cloud.template.HypervisorTemplateAdapter.performDirectDownloadUrlValidation(HypervisorTemplateAdapter.java:188)
	at com.cloud.template.HypervisorTemplateAdapter.prepare(HypervisorTemplateAdapter.java:246)
	at com.cloud.template.TemplateManagerImpl.registerTemplate(TemplateManagerImpl.java:374)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:105)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
```

The issue should have been fixed in the past 

https://github.com/apache/cloudstack/pull/9900
https://github.com/apache/cloudstack/issues/9086

### What to do about it?

There should be no  exception when registering cloud image templates as direct download

### PR DESCRIPTION
**Pull request by weizhouapache**
This fixes #11112 

the command does not work on oraclelinux 8, which causes registration of direct download with https failed.

```
$ /usr/bin/keytool -importcert file /etc/cloudstack/agent/CSCERTIFICATE-full -keystore /etc/cloudstack/agent/cloud.jks -alias full -storepass DAWsfkJeeGrmhta6
Illegal option:  file
keytool -importcert [OPTION]...

Imports a certificate or a certificate chain

Options:

 -noprompt               do not prompt
 -trustcacerts           trust certificates from cacerts
 -protected              password through protected mechanism
 -alias <alias>          alias name of the entry to process
 -file <file>            input file name
 -keypass <arg>          key password
 -keystore <keystore>    keystore name
 -cacerts                access the cacerts keystore
 -storepass <arg>        keystore password
 -storetype <type>       keystore type
 -providername <name>    provider name
 -addprovider <name>     add security provider by name (e.g. SunPKCS11)
   [-providerarg <arg>]    configure argument for -addprovider
 -providerclass <class>  add security provider by fully-qualified class name
   [-providerarg <arg>]    configure argument for -providerclass
 -providerpath <list>    provider classpath
 -v                      verbose output

Use "keytool -?, -h, or --help" for this help message
```

### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetupDirectDownloadCertificateCommandWrapper.java [hunk 1]
```diff
@@ -86,7 +86,7 @@ private String getKeyStoreFilePath(File agentFile) {
     private void importCertificate(String tempCerFilePath, String keyStoreFile, String certificateName, String privatePassword) {
         s_logger.debug("Importing certificate from temporary file to keystore");
         String keyToolPath = Script.getExecutableAbsolutePath("keytool");
-        int result = Script.executeCommandForExitValue(keyToolPath, "-importcert", "file", tempCerFilePath,
+        int result = Script.executeCommandForExitValue(keyToolPath, "-importcert", "-file", tempCerFilePath,
```
Comment (sureshanaparti) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetupDirectDownloadCertificateCommandWrapper.java:89]: @weizhouapache is the file option updated for other distros as well?

Comment (weizhouapache) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtSetupDirectDownloadCertificateCommandWrapper.java:89]: @sureshanaparti 
I checked ol8, ol9, ubuntu 22, ubuntu 24 and debian12, all give an error like
```
# keytool -importcert file
Illegal option:  file
keytool -importcert [OPTION]...
```

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested with ol8 and direct download template registration works fine after the API is executed

https://cloudstack.apache.org/api/apidocs-4.20/apis/uploadTemplateDirectDownloadCertificate.html


Steps 

1. Execute the command 
   
   
`   openssl s_client -showcerts -servername download.cloudstack.org -connect download.cloudstack.org:443 </dev/null 2>/dev/null | awk '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/{ print }' > cloudstack.pem
`

2. Upload to cloudstack 
   
`   cmk upload templatedirectdownloadcertificate certificate="$(cat cloudstack.pem)" hypervisor=kvm name=cloudstackdownload zoneid=6732a2ff-b30d-4f4b-b520-c8f5809d693e`

3. Login to the kvm host to verify if the certificate got uploaded 
   
   
  ` keytool -list -keystore /etc/cloudstack/agent/cloud.jks -storepass $(grep keystore.passphrase /etc/cloudstack/agent//agent.properties |cut -d "=" -f2)`

**Comment by weizhouapache** [comment]
Merged based on approvals and manual test by @kiranchavala 
thanks @sureshanaparti @kiranchavala
