### PR TITLE
KVM local migration issue #3521

### LINKED ISSUE #3521: Regression bug in 4.13.0.0-SNAPSHOT that affects KVM local storage migration
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM, local storage, volume migration.
~~~

##### CLOUDSTACK VERSION

~~~
master (4.13.0.0-SNAPSHOT)
~~~

##### CONFIGURATION

KVM hosts, zone configured allowing to use local storage for user and system VMs.

##### SUMMARY

Tested with the current CloudStack master branch (4.13.0.0-SNAPSHOT) and it failed to migrate a VM with ROOT volume on local storage.

```
2019-06-14 05:52:57,051 WARN  [c.c.a.m.AgentManagerImpl] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Unsupported Command: Unsupported command issued: com.cloud.agent.api.BadCommand.  Are you sure you got the right type of server?
2019-06-14 05:52:57,070 WARN  [o.a.c.s.d.ObjectInDataStoreManagerImpl] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Unsupported data object (VOLUME, org.apache.cloudstack.storage.datastore.PrimaryDataStoreImpl@2e2f2a28), no need to delete from object in store ref table
2019-06-14 05:52:57,070 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Failed to copy volume
com.cloud.utils.exception.CloudRuntimeException: Copy operation failed in 'StorageSystemDataMotionStrategy.copyAsync': Storage verification failed on host 484a1f93-0b23-45bc-9156-1fcf21ef6778: Unsupported command issued: com.cloud.agent.api.BadCommand.  Are you sure you got the right type of server?
        at org.apache.cloudstack.storage.motion.StorageSystemDataMotionStrategy.copyAsync(StorageSystemDataMotionStrategy.java:1895)
        at org.apache.cloudstack.storage.motion.DataMotionServiceImpl.copyAsync(DataMotionServiceImpl.java:120)
        at org.apache.cloudstack.storage.volume.VolumeServiceImpl.migrateVolumes(VolumeServiceImpl.java:1621)
        at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolumes(VolumeOrchestrator.java:1050)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:2778)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:5168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5271)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:583)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:531)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-14 05:52:57,071 DEBUG [o.a.c.e.o.VolumeOrchestrator] (Work-Job-Executor-2:ctx-bbb8964b job-21647/job-21648 ctx-8f96f85b) (logid:0483aa43) Failed to migrated vm VM[User|i-2-2394-VM] along with its volumes. com.cloud.utils.exception.CloudRuntimeException: Copy operation failed in 'StorageSystemDataMotionStrategy.copyAsync': Storage verification failed on host 484a1f93-0b23-45bc-9156-1fcf21ef6778: Unsupported command issued: com.cloud.agent.api.BadCommand.  Are you sure you got the right type of server?
```

##### STEPS TO REPRODUCE

1. Start a VM on a KVM host with local storage;
2. Migrate the VM to another KVM host that has local storage

##### EXPECTED RESULTS

~~~
Success
~~~

##### ACTUAL RESULTS

~~~
Exception
~~~

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

Fix regression bug that affects KVM local storage migration. Some of the desired execution flows for KVM local storage migration had been altered to allow only managed storage to execute. Fixed allowing managed and non managed storages to execute.

Fixes #3521

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## How Has This Been Tested?

1. Start a VM on a KVM host with local storage;
2. Migrate the VM to another KVM host that has local storage
3. Assert that (i) ACS volumes table, (ii) the VM volume content, and (iii) the VM libvirt xml have all been updated correctly.
4. Keep migrating (repeating steps 2 and 3) the VM around hosts (also migrate back the VM to its first host)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Live storage migration for vmware and kvm for VMs with shared storage would be needed cc @andrijapanicsb @borisstoyanov @nvazquez 
@blueorangutan test matrix

**Comment by rhtyd** [comment]
Tests LGTM, can you review @andrijapanicsb @borisstoyanov - we'll need to test live vm with storage migration of shared/nfs storage on kvm and vmware

File: engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java [hunk 1]
```diff
@@ -1905,6 +1911,23 @@ public void copyAsync(Map<VolumeInfo, DataStore> volumeDataStoreMap, VirtualMach
...
+     * Returns true if at least one of the entries on the map 'volumeDataStoreMap' has both source and destination storage pools of Network Filesystem (NFS).
+     */
+    protected boolean isSourceAndDestinationPoolTypeOfNfs(Map<VolumeInfo, DataStore> volumeDataStoreMap) {
+        for (Map.Entry<VolumeInfo, DataStore> entry : volumeDataStoreMap.entrySet()) {
+            VolumeInfo srcVolumeInfo = entry.getKey();
+            DataStore destDataStore = entry.getValue();
+
+            StoragePoolVO destStoragePool = _storagePoolDao.findById(destDataStore.getId());
+            StoragePoolVO sourceStoragePool = _storagePoolDao.findById(srcVolumeInfo.getPoolId());
+            if (sourceStoragePool.getPoolType() == StoragePoolType.NetworkFilesystem && destStoragePool.getPoolType() == StoragePoolType.NetworkFilesystem) {
```
Comment (rhtyd) [inline engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java]: @GabrielBrascher shouldn't it loop and check for all volumes before returning true? It could be like it can return false if any of the src/dest pools are not nfs

**Comment by andrijapanicsb** [comment]
Testing local storage with CentOS6 - breaks heavily - migration of VM+ROOT volume is, in reality, successful, but ACS will report an error and DB will still point VM/volumes exist on the original host. Stopping and starting VM is not working even when fixing the DB (vm_instance and volumes tables, probably I have not dug deep enough...).

Since we also officially support CentOS6, I would like to see this fixed if possible.

Works fine on Ubuntu 18 (VM+ROOT on local storage, migration to another host).
CentOS7 doesn't work (thanks to RedHat $$$hitty commercial logic)

Will test shared storage volume migration...

**Comment by andrijapanicsb** [comment]
@mike-tutkowski any change to test live storage migration wiht KVM+SolidFire - I see a lot of removed/changed code "xxx_manaded_yyy" ?

@GabrielBrascher can you advise on above ^^^ ?

**Comment by andrijapanicsb** [comment]
@syed ^^^

File: engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java (hunk 1 above)
Comment (GabrielBrascher) [reply engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/StorageSystemDataMotionStrategy.java]: @rhtyd The idea is that if at least one of the disks is NFS it cannot be migrated on the execution flow of local storage. Taking a second look I see that the method name might need enhancements.

Am I missing something? Please let me know if something doesn't look right. Thanks for the review.

**Comment by GabrielBrascher** [comment]
Thanks for testing @andrijapanicsb. I did all tests on KVM + Ubuntu and it worked well; however, I did not test with CentOS6. Is there any log for share so that we can tackle the CentOS6 issue?

**Comment by andrijapanicsb** [comment]
@svenvogel can you kindly test if KVM live migration with SF works fine (NFS/CEPH to SF) ?

**Comment by andrijapanicsb** [comment]
@GabrielBrascher 
here they are:
mgmt logs: https://pastebin.com/L97FgFut
agent logs: https://pastebin.com/D6HnZSnJ

**Comment by rhtyd** [comment]
I think for EL6, storage migration (live) would be limiting. The feature should largely be encouraged on newer distros with newer libvirt.

**Comment by andrijapanicsb** [comment]
@GabrielBrascher need your advice since you guys worked on the local migration with KVM.

I saw a case (didn't reproduce it myself, but while working with the customer, on **4.13**) that when KVM is using local storage, and you try to put a host into maintenance, the following seems to happen:
- User VMs - not sure if they are migrated away - can't say for sure - but I assume they are.
- CPVM and SSVM are NOT live migrated (with storage), fails as before
- VRs are live migrated with their storage/volume to a new host - BUT the volume format in DB seems to be set to RAW (again, this is based other-users data, not my own testing - from the cloud.volumes table)

My question is - what is expected to be happening and what is not, and why is the VR's volume in RAW, vs QCOW2 format? Can you lay down the expected behaviour based on the code you've done so far (in 4.13)

Thanks

**Comment by GabrielBrascher** [comment]
@andrijapanicsb I will run some tests and check this out, thanks for the heads-up.
