### PR TITLE
usage: create backup usage record for vmId-offeringId pair

### LINKED ISSUE #4982: Incorrect backup usage when VM is removed then re-assign to backup offering
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Usage
~~~

##### CLOUDSTACK VERSION
~~~
4.14.1.0
4.15.0.0
~~~

##### CONFIGURATION
Backup framework enabled

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When a VM is removed from a backup offering, then re-assigned to the same backup offering, the usage record generated for the period in which these events occur has an invalid usage value, equal to the sum of the sizes of the backups.

##### STEPS TO REPRODUCE
 
Example scenario:

1. `02:30 PM`: Create a VM and assign it to a backup offering
2. `02:35 PM`: Make backups of the VM (for a size of e.g. 1 GiB)
3. `03:15 PM`: Remove the backup offering, with the "force" option (to delete existing backups)
4. `03:30 PM`: Re-assign the VM to the backup offering
5. `03:35 PM`: Make a backup of the VM (for a size of e.g. 0.8 GiB)

To reproduce the bug, if the usage aggregation range is e.g 1 Hour (`usage.stats.job.aggregation.range = 60`), make sure the steps 3, 4 and 5 are executed in the same hour.

##### EXPECTED RESULTS

**Option 1:** I would expect CloudStack usage server to:
- generate two usage records for the period between `03:00 PM` and `04:00 PM` (one for each period with a backup offering)
- use the fields `raw_usage` / `usage_display` to show the duration of usage, and the field `size` to show the size of the backups (that's the way storage usage records are generated for volumes, templates, ISOs and snashots)

```
+------------+---------------+------------+------------+----------+----------+------------------------+
|  raw_usage | usage_display | size       | start_date | end_date | usage_id | description            |
+------------+---------------+------------+------------+----------+----------+------------------------+
|        0.5 | 0.5 Hrs       | 1073741824 | 14:00:00   | 14:59:59 |       67 | Backup usage VM ID: 67 |
|       0.25 | 0.25 Hrs      | 1073741824 | 15:00:00   | 15:59:59 |       67 | Backup usage VM ID: 67 |
|        0.5 | 0.5 Hrs       |  858993460 | 15:00:00   | 15:59:59 |       67 | Backup usage VM ID: 67 |
+------------+---------------+------------+------------+----------+----------+------------------------+
```

**Option 2:** This could also be ok (even if we loose information):

```
+------------+---------------+------------+------------+----------+----------+------------------------+
|  raw_usage | usage_display | size       | start_date | end_date | usage_id | description            |
+------------+---------------+------------+------------+----------+----------+------------------------+
| 1073741824 | 1.0 GiB       | 1073741824 | 14:00:00   | 14:59:59 |       67 | Backup usage VM ID: 67 |
|  858993460 | 0.8 GiB       |  858993460 | 15:00:00   | 15:59:59 |       67 | Backup usage VM ID: 67 |
+------------+---------------+------------+------------+----------+----------+------------------------+
```

##### ACTUAL RESULTS
Usage records:

```
+------------+---------------+------------+------------+----------+----------+------------------------+
|  raw_usage | usage_display | size       | start_date | end_date | usage_id | description            |
+------------+---------------+------------+------------+----------+----------+------------------------+
| 1073741824 | 1.0 GiB       | 1073741824 | 14:00:00   | 14:59:59 |       67 | Backup usage VM ID: 67 |
| 1932735284 | 1.8 GiB       | 1932735284 | 15:00:00   | 15:59:59 |       67 | Backup usage VM ID: 67 |
+------------+---------------+------------+------------+----------+----------+------------------------+
```

Here, the `raw_usage` for the period from 3 PM to 4 PM is the sum of the backup sizes, which is irrelevant (the 1 GiB backups are deleted before the creation of the 0.8 GiB backup).

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

when creat usage record for backup usages in a period, we need to check if vm offering is changed. if vm offering is changed, create a new cloud usage record, otherwise update existing usage record.

This PR fixes #4982 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
added unit test for BackupUsageParser.java

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java [hunk 1]
```diff
@@ -100,6 +89,33 @@ public static boolean parse(AccountVO account, Date startDate, Date endDate) {
...
+        final Map<Long, Long> vmOffering = new HashMap<Long, Long>();
+        final Map<Long, Integer> vmOfferingIndex = new HashMap<Long, Integer>();
+        final Map<String, BackupInfo> vmUsageMap = new HashMap<>();
+        for (final UsageBackupVO usageBackup : usageBackups) {
+            final Long vmId = usageBackup.getVmId();
+            final Long zoneId = usageBackup.getZoneId();
+            final Long offeringId = usageBackup.getBackupOfferingId();
+            Integer index = vmOfferingIndex.get(vmId) == null ? 0 : vmOfferingIndex.get(vmId);
+            if (vmOffering.get(vmId) == null || vmOffering.get(vmId) != offeringId)  {
+                if (vmOffering.get(vmId) != null) {
```
[the remark this answers is not in the document]
Comment (weizhouapache) [reply usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java]: @GutoVeronezi  done.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java [hunk 2]
```diff
@@ -100,6 +89,32 @@ public static boolean parse(AccountVO account, Date startDate, Date endDate) {
...
+    protected static final Map<String, BackupInfo> getVmUsageMap(final List<UsageBackupVO> usageBackups) {
+        final Map<Long, Long> vmOffering = new HashMap<Long, Long>();
+        final Map<Long, Integer> vmOfferingIndex = new HashMap<Long, Integer>();
+        final Map<String, BackupInfo> vmUsageMap = new HashMap<>();
+        for (final UsageBackupVO usageBackup : usageBackups) {
+            final Long vmId = usageBackup.getVmId();
+            final Long zoneId = usageBackup.getZoneId();
+            final Long offeringId = usageBackup.getBackupOfferingId();
+            Integer index = vmOfferingIndex.get(vmId) == null ? -1 : vmOfferingIndex.get(vmId);
+            boolean isVmOfferingEqualsToPrevious = vmOffering.get(vmId) != null && vmOffering.get(vmId) == offeringId;
```
Comment (DaanHoogland) [inline usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:101]:
```suggestion
            boolean isVmOfferingEqualsToPrevious = offeringId.equals(vmOffering.get(vmId));
```

Comment (DaanHoogland) [reply usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:101]: maybe also change the name to `isVmOfferingEqualToPrevious`, without the 3rd person singular 's'. Also the name `vmOfferingEqualsToPrevious` is better.

**Review by DaanHoogland — APPROVED** [review]
clgtm, two small sugestions

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java (hunk 2 above)
Comment (weizhouapache) [reply usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java]: @DaanHoogland thanks. done!

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java [hunk 3]
```diff
@@ -68,18 +68,7 @@ public static boolean parse(AccountVO account, Date startDate, Date endDate) {
...
-            final Long zoneId = usageBackup.getZoneId();
-            final Long offeringId = usageBackup.getBackupOfferingId();
-            if (vmUsageMap.get(vmId) == null) {
-                vmUsageMap.put(vmId, new BackupUsageParser.BackupInfo(new Backup.Metric(0L, 0L), zoneId, vmId, offeringId));
-            }
-            final Backup.Metric metric = vmUsageMap.get(vmId).getMetric();
-            metric.setBackupSize(metric.getBackupSize() + usageBackup.getSize());
-            metric.setDataSize(metric.getDataSize() + usageBackup.getProtectedSize());
-        }
+        Map<String, BackupInfo> vmUsageMap = getVmUsageMap(usageBackups);
```
Comment (rhtyd) [inline usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:71]: @weizhouapache should we handle it by ensure everytime the offering is changed, a usage event is handled? How does other resources say VM handle this when their offerings are changed, maybe we should follow the same logic? (I've not checked, so maybe your approach is in-line with that)

**Comment by rhtyd** [comment]
@Pearl1594 I think you're aware of the original issue, can you review this? cc @nvazquez @weizhouapache

**Comment by rhtyd** [comment]
Ping @olivierlemasle - can you review/test this? Thanks.

**Comment by weizhouapache** [comment]
@Pearl1594 updated this pr.
the records in cloud_usage looks like
```
mysql> select raw_usage, usage_display, size, virtual_size, start_date, end_date, usage_id, description from cloud_usage where usage_type=28;
+------------------------+---------------+------+--------------+---------------------+---------------------+----------+------------------------------------------------------------------+
| raw_usage              | usage_display | size | virtual_size | start_date          | end_date            | usage_id | description                                                      |
+------------------------+---------------+------+--------------+---------------------+---------------------+----------+------------------------------------------------------------------+

...
|     0.0833333358168602 | 0.083333 Hrs  | 1000 |          100 | 2021-08-31 14:31:34 | 2021-08-31 14:36:34 |       68 | Backup usage VM ID: 68, backup offering: 1                       |
|    0.06708250194787979 | 0.067083 Hrs  | 1000 |          100 | 2021-08-31 14:36:34 | 2021-08-31 14:41:34 |       68 | Backup usage VM ID: 68, backup offering: 1                       |
|  0.0033336111810058355 | 0.003334 Hrs  |    0 |            0 | 2021-08-31 14:36:34 | 2021-08-31 14:41:34 |       68 | Backup usage VM ID: 68, backup offering: 2                       |
|   0.009029166772961617 | 0.009029 Hrs  |    0 |            0 | 2021-08-31 14:36:34 | 2021-08-31 14:41:34 |       68 | Backup usage VM ID: 68, backup offering: 1                       |
|    0.08333361148834229 | 0.083334 Hrs  | 1000 |          100 | 2021-08-31 14:41:34 | 2021-08-31 14:46:34 |       68 | Backup usage VM ID: 68, backup offering: 1                       |
```

main changes
(1) display hours instead of size in raw_usage
(2) create a record for each backup offering in a period (consider there are multiple backup offering if we remove/assign vm from/to backup offering).

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@weizhouapache cc @nvazquez @rhtyd While the new approach fixes the problem; it solves the issue the same way #5005 attempted to and we did have reservations with the approach as it changes the behavior i.e., the columns `usage_display` and `raw_usage` which initially stored the size of the backup, now would show the duration over which the backup offering is assigned to the VM - Please note the comments at the right of the table below - Could this lead to some ambiguity ; I am for representing the usage records in the way the PR does, but do we need to have some upgrade path in place to change already recorded values which have `usage_display` and` raw_usage` in GB?

That said, as of fixing the issue - the solution LGTM
```
select id, raw_usage, usage_display, vm_instance_id, offering_id, usage_id, start_date, end_date, virtual_size, size from cloud_usage where vm_instance_id = 3 and usage_type = 28;

+-------+----------------------+---------------+----------------+-------------+----------+---------------------+---------------------+--------------+------+  
| 18350 |                 1000 | 0.0000 GiB    |              3 |           1 |        3 | 2021-09-01 04:32:00 | 2021-09-01 04:33:00 |          100 | 1000 | <-- When old usage job was running
| 18365 |                 1000 | 0.0000 GiB    |              3 |           1 |        3 | 2021-09-01 04:33:00 | 2021-09-01 04:34:00 |          100 | 1000 |
| 18380 | 0.017889168113470078 | 0.017889 Hrs  |              3 |           1 |        3 | 2021-09-01 04:34:00 | 2021-09-01 04:35:04 |          100 | 1000 | <-- After the new code changes kicked in
| 18395 |  0.01666666753590107 | 0.016667 Hrs  |              3 |           1 |        3 | 2021-09-01 04:35:04 | 2021-09-01 04:36:04 |          100 | 1000 |
| 18410 |  0.01666666753590107 | 0.016667 Hrs  |              3 |           1 |        3 | 2021-09-01 04:36:04 | 2021-09-01 04:37:04 |          100 | 1000 |
....
| 18594 | 0.016668887808918953 | 0.016669 Hrs  |              3 |           1 |        3 | 2021-09-01 04:48:04 | 2021-09-01 04:49:04 |          100 | 1000 |
| 18609 | 0.004332222044467926 | 0.004332 Hrs  |              3 |           1 |        3 | 2021-09-01 04:49:04 | 2021-09-01 04:50:04 |          100 | 1000 | <-- VM unassigned from bkp offering
| 18737 | 0.014833054505288601 | 0.014833 Hrs  |              3 |           1 |        3 | 2021-09-01 04:58:04 | 2021-09-01 04:59:04 |          100 | 1000 | <-- VM re-assinged to the same bkp offering
| 18752 | 0.016666390001773834 | 0.016666 Hrs  |              3 |           1 |        3 | 2021-09-01 04:59:04 | 2021-09-01 05:00:04 |          100 | 1000 |
....
| 18951 |  0.013779444620013237 | 0.013779 Hrs  |              3 |           1 |        3 | 2021-09-01 05:12:04 | 2021-09-01 05:13:04 |          100 | 1000 |
| 18952 | 0.0017772221472114325 | 0.001777 Hrs  |              3 |           2 |        3 | 2021-09-01 05:12:04 | 2021-09-01 05:13:04 |            0 |    0 | <-- VM assigned to new bkp offering (ID:2)
| 18967 |  0.016665834933519363 | 0.016666 Hrs  |              3 |           2 |        3 | 2021-09-01 05:13:04 | 2021-09-01 05:14:04 |          100 | 1000 |
+-------+-----------------------+---------------+----------------+-------------+----------+---------------------+---------------------+--------------+------+
```

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]
clgtm

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java (hunk 3 above)
Comment (weizhouapache) [reply usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java]: @rhtyd 
updated this pr to display the duration of backup offering in the period (see Pearl's testing result).
since you are the author of backup and restore framework, could you please review it ?

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java [hunk 4]
```diff
@@ -68,65 +66,33 @@ public static boolean parse(AccountVO account, Date startDate, Date endDate) {
...
-            final Backup.Metric metric = vmUsageMap.get(vmId).getMetric();
-            metric.setBackupSize(metric.getBackupSize() + usageBackup.getSize());
-            metric.setDataSize(metric.getDataSize() + usageBackup.getProtectedSize());
-        }
+            if (removedDate == null || removedDate.after(endDate)) {
+                removedDate = endDate;
+            }
+            final long duration = (removedDate.getTime() - createdDate.getTime()) + 1;
+            final float usage = duration / 1000f / 60f / 60f;
+            DecimalFormat dFormat = new DecimalFormat("#.######");
```
Comment (rhtyd) [inline usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:83]: Could this cause issue where localisation is not English?

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java [hunk 5]
```diff
@@ -68,65 +66,33 @@ public static boolean parse(AccountVO account, Date startDate, Date endDate) {
...
-            final String description = String.format("Backup usage VM ID: %d", vmId);
-            final String usageDisplay = String.format("%.4f GiB", sizeGib);
+            final Double rawUsage = (double) usageBackup.getSize();
+            final String description = String.format("Backup usage VM ID: %d, backup offering: %d", vmId, offeringId);
 
             final UsageVO usageRecord =
-                    new UsageVO(zoneId, account.getAccountId(), account.getDomainId(), description, usageDisplay,
-                            UsageTypes.BACKUP, rawUsage, vmId, null, offeringId, null, vmId,
-                            backupInfo.getMetric().getBackupSize(), backupInfo.getMetric().getDataSize(), startDate, endDate);
+                    new UsageVO(zoneId, account.getAccountId(), account.getDomainId(), description, usageDisplay + " Hrs",
```
Comment (rhtyd) [inline usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:90]: This may not make sense, effectively a backup takes up space and not time. For example, two instances of backups can have different sizes - can you check how we do it for snapshots and volumes. Effectively backups of a VM are like snapshots for a volume.

Comment (weizhouapache) [reply usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:90]: @rhtyd 
I have checked the usage for snapshots and volumes - cloudstack displays running time for both. see

https://github.com/apache/cloudstack/blob/main/usage/src/main/java/com/cloud/usage/parser/VolumeUsageParser.java#L150-L153

https://github.com/apache/cloudstack/blob/main/usage/src/main/java/com/cloud/usage/parser/VMSnapshotUsageParser.java#L131-L134

File: usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java (hunk 4 above)
Comment (weizhouapache) [reply usage/src/main/java/com/cloud/usage/parser/BackupUsageParser.java:83]: @rhtyd 
good question ......
the usage records are not displayed on UI so it is not an issue I think.

**Comment by weizhouapache** [comment]
@Pearl1594 @borisstoyanov 
does it LGTY ?

**Review by Pearl1594 — APPROVED** [review]
The solution achieves consistency in the way the usage records are gathered for backup usage - considering that no previous records exist for backups, the PR LGTM

**Comment by olivierlemasle** [comment]
Hi, I'll look at it today.

**Comment by rhtyd** [comment]
That would be great, thanks @olivierlemasle

**Comment by rhtyd** [comment]
Thanks @weizhouapache @Pearl1594 for your agreement, let's wait for @olivierlemasle to share his test results then we'll merge this.

**Review by olivierlemasle — APPROVED** [review]
LGTM - Tested only with the dummy provider because I've no longer access to a Veeam environment.
It is now more aligned with other CloudStack usage types.

**Comment by rhtyd** [comment]
Thanks @olivierlemasle merging this based on your feedback, as well comments from Pearl and Wei.
