### PR TITLE
check for active MSses before starting DB upgrade

### LINKED ISSUE #11973: Avoid accidental live DB upgrades if other management servers are in Up state
### problem

A user might execute an incident upgrade when adding a new management server with later version(if let's say there's a new minor version meanwhile in the same upstream repo).

To avoid this, I propose when we identify an upgrade path is due we: 

1.  Check DB if there's any other management server in Up state
2. If yes, we skip the DB upgrade and shut down the management server. 

### versions

any, detected with 4.20.1 env and recent 4.20.2 release 

### The steps to reproduce the bug

1. Have an env running 4.20.1
2. Add new management server, with version 4.20.2 
3. Start the management server 
...

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR...

Fixes: #11973

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 1]
```diff
@@ -448,39 +451,71 @@ public void check() {
...
+            doUpgrades(lock);
+        } finally {
+            lock.releaseRef();
+        }
+    }
+    private void checkIfStandalone() throws CloudRuntimeException {
+        boolean standalone = Transaction.execute(new TransactionCallback<>() {
+            @Override
+            public Boolean doInTransaction(TransactionStatus status) {
+                String sql = "SELECT COUNT(*) FROM `cloud`.`management_server` WHERE `status` = 'UP'";
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]: is the table name  `mshost` ?

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 2]
```diff
@@ -448,39 +451,71 @@ public void check() {
...
+                try (Connection conn  = TransactionLegacy.getStandaloneConnection();
+                     PreparedStatement pstmt = conn.prepareStatement(sql);
+                     ResultSet rs = pstmt.executeQuery()) {
+                    if (rs.next()) {
+                        int count = rs.getInt(1);
+                        return count <= 1;
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]: `count <= 1` or `count == 0` ?

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java (hunk 1 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]:
```suggestion
                String sql = "SELECT COUNT(*) FROM `cloud`.`mshosts` WHERE `state` = 'UP'";
```

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java (hunk 2 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]:
```suggestion
                        return count = 0;
```

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 3]
```diff
@@ -468,7 +468,7 @@ public Boolean doInTransaction(TransactionStatus status) {
                      ResultSet rs = pstmt.executeQuery()) {
                     if (rs.next()) {
                         int count = rs.getInt(1);
-                        return count <= 1;
+                        return count = 0;
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]: == or = ?

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 4]
```diff
@@ -448,39 +451,71 @@ public void check() {
...
+            doUpgrades(lock);
+        } finally {
+            lock.releaseRef();
+        }
+    }
+    private void checkIfStandalone() throws CloudRuntimeException {
+        boolean standalone = Transaction.execute(new TransactionCallback<>() {
+            @Override
+            public Boolean doInTransaction(TransactionStatus status) {
+                String sql = "SELECT COUNT(*) FROM `cloud`.`mshosts` WHERE `state` = 'UP'";
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]: mshost ?

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java (hunk 3 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]: doing too many things at once 🤕

Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]:
```suggestion
                        return count == 0;
```

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java (hunk 4 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]:
```suggestion
                String sql = "SELECT COUNT(*) FROM `cloud`.`mshost` WHERE `state` = 'UP'";
```

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 5]
```diff
@@ -448,39 +451,71 @@ public void check() {
...
+                } catch (SQLException e) {
+                    String errorMessage = "Unable to check if the management server is running in standalone mode.";
+                    LOGGER.error(errorMessage, e);
+                    throw new CloudRuntimeException(errorMessage, e);
+                }
+                return true;
+            }
+        });
+        if (! standalone) {
+            String msg = "CloudStack is running multiple management servers and attempting to upgrade. Upgrades can only be run in standalone mode. Skipping database upgrade check.";
```
[the remark this answers is not in the document]
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]:
```suggestion
            String msg = "CloudStack is running multiple management servers while attempting to upgrade. Upgrades can only be run in standalone mode. Aborting.";
```

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 6]
```diff
@@ -448,39 +451,71 @@ public void check() {
...
+                    if (rs.next()) {
+                        int count = rs.getInt(1);
+                        return count == 0;
+                    }
+                } catch (SQLException e) {
+                    String errorMessage = "Unable to check if the management server is running in standalone mode.";
+                    LOGGER.error(errorMessage, e);
+                    throw new CloudRuntimeException(errorMessage, e);
+                }
+                return true;
```
Comment (DaanHoogland) [inline engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java:481]: maybe be save and return false as we are not sure.

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 7]
```diff
@@ -448,39 +451,66 @@ public void check() {
                 throw new CloudRuntimeException("Unable to acquire lock to check for database integrity.");
             }
 
-            try {
-                initializeDatabaseEncryptors();
+            if (isStandalone()) {
+                doUpgrades(lock);
+            }
```
Comment (DaanHoogland) [inline engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java]: so when not standalone, some check for the right version still needed?

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java [hunk 8]
```diff
@@ -448,39 +450,76 @@ public void check() {
...
+        return Transaction.execute(new TransactionCallback<>() {
+            @Override
+            public Boolean doInTransaction(TransactionStatus status) {
+                String sql = "SELECT COUNT(*) FROM `cloud`.`mshost` WHERE `state` = 'UP'";
+                try (Connection conn = TransactionLegacy.getStandaloneConnection();
+                     PreparedStatement pstmt = conn.prepareStatement(sql);
+                     ResultSet rs = pstmt.executeQuery()) {
+                    if (rs.next()) {
+                        int count = rs.getInt(1);
+                        return count == 0;
```
[the remark this answers is not in the document]
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java:470]: one valid issue is that an MS performing an upgrade is not yet registered as UP. so this fix is better than what we have but certainly not watertight yet.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by borisstoyanov — APPROVED** [review]
LGTM, tested that the management server is shut down if upgrade is required but there are other management servers running

File: engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java:470]: > one valid issue is that an MS performing an upgrade is not yet registered as UP. so this fix is better than what we have but certainly not watertight yet.

yes, this works based on the assumption that the mshost.state is correct and update to date.
however I doubt it is true ...

[the remark this answers is not in the document]
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/DatabaseUpgradeChecker.java:470]: You are right however we cannot defend against what we do not know. I think any MS being Up will be registered as Up, maybe not the other way around. In which case we will stop and a manual DB action will have to be taken to remedie. Is there any reason to doubt the added value of this check though, @weizhouapache ?

**Review by weizhouapache — APPROVED** [review]
there might be an issue if the MS state is incorrect (for example MS is Down but the state is still Up)
but this will avoid the incidental upgrade of a mgmt server while but other mgmt servers are still running.

I think it is good. this brings more benefits than disadvantages.

**Comment by DaanHoogland** [comment]
> there might be an issue if the MS state is incorrect (for example MS is Down but the state is still Up) but this will avoid the incidental upgrade of a mgmt server while but other mgmt servers are still running.
> 
> I think it is good. this brings more benefits than disadvantages.

tnx @weizhouapache , as mentioned off-line I’ll add a doc PR to address any in-clarities in the changed behaviour.

**Comment by abh1sar** [comment]
> > there might be an issue if the MS state is incorrect (for example MS is Down but the state is still Up) but this will avoid the incidental upgrade of a mgmt server while but other mgmt servers are still running.
> > I think it is good. this brings more benefits than disadvantages.
> 
> tnx @weizhouapache , as mentioned off-line I’ll add a doc PR to address any in-clarities in the changed behaviour.

@DaanHoogland can you please link the doc PR if you have raised one?
