### PR TITLE
server: add user.password.reset.smtp.useStartTLS and enabledSecurityProtocols for password reset

### LINKED ISSUE #11159: CS 4.20.1 Password Reset Functionality
### problem

The Password Reset Functionality throws an error, Using ubuntu msmtp works.

We have enabled the password reset functionality:

the sender username is noreply@mydomain.com

Image

Image

Logs from the management server:

2025-07-04 15:01:57,332 ERROR [o.a.c.u.m.SMTPMailSender] (qtp1404565079-345:[ctx-80979faa]) (logid:0e1f5dee) Unable to send mail [Password Reset Request] to the recipcients [[{"mailAddress":"[tatay@mymail.com](mailto:tatay@mymail.com)"}]]. javax.mail.MessagingException: Could not connect to SMTP host: [smtp.office365.com](http://smtp.office365.com/), port: 587;
at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
at javax.mail.Service.connect(Service.java:295)
at javax.mail.Service.connect(Service.java:176)
at javax.mail.Service.connect(Service.java:125)
at org.apache.cloudstack.utils.mailing.SMTPMailSender.sendMail(SMTPMailSender.java:175)
at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:527)
at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:332)
at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:234)
at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927)
2025-07-04 15:01:57,336 DEBUG [o.a.c.u.UserPasswordResetManagerImpl] (qtp1404565079-345:[ctx-80979faa]) (logid:0e1f5dee) User password reset email for user UserAccount {"accountName":"domain1","id":5,"username":"tatay"}. account id: 5 domain id: 3 sent to [tatay@mymail.com](mailto:tatay@mymail.com) with token expiry at 2025-07-04T15:31:57.243+0000
2025-07-04 15:08:28,663 WARN  [c.c.c.ConfigurationManagerImpl] (qtp1404565079-447:[ctx-7d09367d, ctx-af7db5cb]) (logid:37392271) Configuration user.password.reset.email.sender no found. Perhaps moved to ConfigDepot
2025-07-04 15:08:28,675 WARN  [c.c.c.ConfigurationManagerImpl] (qtp1404565079-447:[ctx-7d09367d, ctx-af7db5cb]) (logid:37392271) Configuration user.password.reset.mail.template no found. Perhaps moved to ConfigDepot

We tested from the server and **Works** using the **msmtp** in Ubuntu

### versions

ACS version 4.20.1

### The steps to reproduce the bug

1. create an email account in Microsoft, with TLS and and AUTH port 587
2. Fill the information in the CS management servers
3. test.
...

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #11159 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
much more needed on this @weizhouapache ?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> much more needed on this @weizhouapache ?

@DaanHoogland 
that's all, I think

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@DaanHoogland 
I added another configuration "user.password.reset.smtp.enabledSecurityProtocols"

**Comment by DaanHoogland** [comment]
> @DaanHoogland I added another configuration "user.password.reset.smtp.enabledSecurityProtocols"

still looks good. ;) still needs testing though. ...

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManager.java [hunk 1]
```diff
@@ -55,6 +55,17 @@ public interface UserPasswordResetManager {
             "Use auth in the SMTP server for sending emails for resetting password for ACS users",
             false, ConfigKey.Scope.Global);
 
+    ConfigKey<Boolean> UserPasswordResetSMTPUseStartTLS = new ConfigKey<>(ConfigKey.CATEGORY_ADVANCED,
```
Comment (harikrishna-patnala) [inline server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManager.java:58]: @weizhouapache do we need to use these settings anywhere ? I don't see any usages!

**Comment by harikrishna-patnala** [comment]
@weizhouapache also please check if this PR needs any branch or milestone changes

**Comment by weizhouapache** [comment]
thanks @harikrishna-patnala 
changed the target branch to 4.20

File: server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManager.java (hunk 1 above)
Comment (weizhouapache) [reply server/src/main/java/org/apache/cloudstack/user/UserPasswordResetManager.java:58]: oops, forgot to push a commit

thanks @harikrishna-patnala

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by vishesh92 — APPROVED** [review]
lgtm. tested with [mailpit](https://mailpit.axllent.org/) after enabling STARTTLS required.
