### PR TITLE
User data content size validation, and related code improvements

### LINKED ISSUE #8415: Unable to create managed user data, with content > (around)3100 bytes
Failed to register user data, with content > (around)3100 bytes. Error:` User data is too long for an http GET request`

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Compute / User Data
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0 
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Oracle Linux Server 9.0 / KVM Hypervisor

##### SUMMARY

Unable to create managed user data, with content > (around)3100 bytes, as it is being restricted with certain bytes for the http GET request.

Also, the actual user data length is not considered to check the allowed limit.

should allow user data with GET request call?

userdata-error

##### STEPS TO REPRODUCE

- Go to Compute -> User Data section
- Register User Data with content > (around)3100 bytes

##### EXPECTED RESULTS

~~~
Able to register user data content upto 1048576 bytes (based on the setting 'vm.userdata.max.length') with POST request call, and 4096 bytes with GET request call.
~~~

##### ACTUAL RESULTS

~~~
Unable to register user data content > around 3100 bytes, with GET request call.
~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR validates the user data with actual length only, and has some code improvements.

Fixes #8415

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested managed user data registration, and instance creation from UI.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java [hunk 1]
```diff
@@ -90,49 +90,50 @@ public String concatenateUserData(String userdata1, String userdata2, String use
...
-        if (userData != null) {
-
-            if (userData.contains("%")) {
-                try {
-                    userData = URLDecoder.decode(userData, "UTF-8");
-                } catch (UnsupportedEncodingException e) {
-                    throw new InvalidParameterValueException("Url decoding of userdata failed.");
-                }
-            }
+        if (StringUtils.isBlank(userData)) {
```
Comment (DaanHoogland) [inline engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:93]: why is userdata obligatory?

**Review by DaanHoogland — COMMENTED** [review]
clgtm, just one functional question

**Review by harikrishna-patnala — COMMENTED** [review]
@sureshanaparti, along with these changes is it better to call the registerUserData API using POST from UI ?

**Comment by rohityadavcloud** [comment]
@sureshanaparti can you review the outstanding comments?
@blueorangutan package

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java (hunk 1 above)
Comment (sureshanaparti) [reply engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:91]: > why is userdata obligatory?

userdata is not mandatory, updated it to return null as earlier.

**Comment by sureshanaparti** [comment]
> @sureshanaparti, along with these changes is it better to call the registerUserData API using POST from UI ?

changes done

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by JoaoJandre** [comment]
@sureshanaparti can you rebase with 4.18.2? As the related issue is also aimed at 4.18.2

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java [hunk 2]
```diff
@@ -90,49 +88,50 @@ public String concatenateUserData(String userdata1, String userdata2, String use
...
             }
+        }
 
-            if (decodedUserData == null || decodedUserData.length < 1) {
-                throw new InvalidParameterValueException("User data is too short");
-            }
-            // Re-encode so that the '=' paddings are added if necessary since 'isBase64' does not require it, but python does on the VR.
-            return Base64.encodeBase64String(decodedUserData);
+        if (!Base64.isBase64(userData)) {
+            throw new InvalidParameterValueException("User data is not base64 encoded");
```
Comment (JoaoJandre) [inline engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:104]:
```suggestion
            throw new InvalidParameterValueException("User data is not base64 encoded.");
```

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java [hunk 3]
```diff
@@ -90,49 +88,50 @@ public String concatenateUserData(String userdata1, String userdata2, String use
...
-        if (userData != null) {
-
-            if (userData.contains("%")) {
-                try {
-                    userData = URLDecoder.decode(userData, "UTF-8");
-                } catch (UnsupportedEncodingException e) {
-                    throw new InvalidParameterValueException("Url decoding of userdata failed.");
-                }
-            }
+        if (StringUtils.isBlank(userData)) {
```
Comment (JoaoJandre) [inline engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:91]: Could you add a log line at the start of the method that logs the userdata that is being validated? something like:
```suggestion
        logger.debug(String.format("Validating userdata [%s].", userData));
        
        if (StringUtils.isBlank(userData)) {
```

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java [hunk 4]
```diff
@@ -90,49 +88,50 @@ public String concatenateUserData(String userdata1, String userdata2, String use
...
-            throw new InvalidParameterValueException("User data has exceeded configurable max length : " + ConfigurationManager.VM_USERDATA_MAX_LENGTH.value());
+
+        // Re-encode so that the '=' paddings are added if necessary since 'isBase64' does not require it, but python does on the VR.
+        return Base64.encodeBase64String(decodedUserData);
+    }
+
+    private byte[] validateAndDecodeByHTTPMethod(String userData, int maxHTTPLength, BaseCmd.HTTPMethod httpMethod) {
+        byte[] decodedUserData = Base64.decodeBase64(userData.getBytes());
+        if (decodedUserData == null || decodedUserData.length < 1) {
+            throw new InvalidParameterValueException("User data is too short");
```
Comment (JoaoJandre) [inline engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:123]:
```suggestion
            throw new InvalidParameterValueException("User data is too short.");
```

**Review by JoaoJandre — COMMENTED** [review]
Overall looks good, just a few remarks

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java (hunk 3 above)
Comment (sureshanaparti) [reply engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:91]: @JoaoJandre may not be good to log user data here (can be of more length sometimes).

**Review by DaanHoogland — APPROVED** [review]
clgtm

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java (hunk 3 above)
Comment (JoaoJandre) [reply engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:91]: @sureshanaparti Maybe leave it at `trace` level? This way it will only show up when someone really needs to see it.

Comment (sureshanaparti) [reply engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:91]: we can log it later, may be before validation, in case needed @JoaoJandre I think, logger obj for only this trace is unnecessary.

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test keepEnv

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@JoaoJandre can you check the changes on your remarks?

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java [hunk 5]
```diff
@@ -90,49 +90,54 @@ public String concatenateUserData(String userdata1, String userdata2, String use
...
-            // If GET, use 4K. If POST, support up to 1M.
-            if (httpmethod.equals(BaseCmd.HTTPMethod.GET)) {
-                decodedUserData = validateAndDecodeByHTTPMethod(userData, MAX_HTTP_GET_LENGTH, BaseCmd.HTTPMethod.GET);
-            } else if (httpmethod.equals(BaseCmd.HTTPMethod.POST)) {
-                decodedUserData = validateAndDecodeByHTTPMethod(userData, MAX_HTTP_POST_LENGTH, BaseCmd.HTTPMethod.POST);
+        if (userData.contains("%")) {
+            try {
+                userData = URLDecoder.decode(userData, "UTF-8");
+            } catch (UnsupportedEncodingException e) {
+                throw new InvalidParameterValueException("Url decoding of user data failed.");
```
Comment (JoaoJandre) [inline engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:102]:
```suggestion
                throw new InvalidParameterValueException(String.format("Url decoding of user data [%s] failed.", userData));
```
If we are not logging it at the beginning of the method, could we at least add it to the exception's message?

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java [hunk 6]
```diff
@@ -90,49 +90,54 @@ public String concatenateUserData(String userdata1, String userdata2, String use
...
             }
+        }
 
-            if (decodedUserData == null || decodedUserData.length < 1) {
-                throw new InvalidParameterValueException("User data is too short");
-            }
-            // Re-encode so that the '=' paddings are added if necessary since 'isBase64' does not require it, but python does on the VR.
-            return Base64.encodeBase64String(decodedUserData);
+        if (!Base64.isBase64(userData)) {
+            throw new InvalidParameterValueException("User data is not base64 encoded.");
```
Comment (JoaoJandre) [inline engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:107]: Add the userdata in this message as well.

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java (hunk 5 above)
Comment (sureshanaparti) [reply engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:102]: @JoaoJandre exception message can be long when more content passed in user data, better log it at trace level. Add log for user data in the beginning of the valid method.

File: engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java (hunk 6 above)
Comment (sureshanaparti) [reply engine/userdata/src/main/java/org/apache/cloudstack/userdata/UserDataManagerImpl.java:107]: Added log for user data in the beginning of method, should be fine.

**Comment by sureshanaparti** [comment]
> @JoaoJandre can you check the changes on your remarks?

@JoaoJandre pls check your remarks. thanks.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by JoaoJandre — APPROVED** [review]
CLGTM, did not test it.

**Review by kiranchavala — COMMENTED** [review]
@sureshanaparti  as discussed, the userdata registration from the browser is not working 

Regsiter  a userdata of size 686kb 

[test2.zip](https://github.com/user-attachments/files/15820248/test2.zip)

Error

Screenshot 2024-06-13 at 4 34 36 PM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by kiranchavala — COMMENTED** [review]
@sureshanaparti 

As discussed, the registerUserdata api call Is failing with 400 error , if the userdata size is  of 916kb

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
> @sureshanaparti
> 
> As discussed, the registerUserdata api call Is failing with 400 error , if the userdata size is of 916kb

@kiranchavala Allowed size is for the userdata after base64 encoding. Updated descriptions for the cmd param and config  `vm.userdata.max.length`.

```
MaxSizeInBytesAfterEncoding = (SizeInBytesBeforeEncoding / 3 * 4) + 4

So, it seems 786432 bytes / 768 KB actual user data supported
```

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@kiranchavala all good now?

**Review by kiranchavala — APPROVED** [review]
LGTM, Followed these steps 

1. Global setting (vm.userdata.max.length) change it to 1048576
2. Compute > userdata > register userdata


 registering a user data 
 
  

A Post request will be sent 

Screenshot 2024-06-18 at 4 47 49 PM

and the logs will contain the userdata size 

**Configured base64 encoded user data size: 914652 bytes, actual user data size: 685987 bytes**

LOGS

```

[root@ref-trl-6845-k-Mr8-kiran-chavala-mgmt1 ~]# cat   /var/log/cloudstack/management/management-server.log  |grep -i "logid:c0d4d084"
2024-06-14 09:26:08,934 DEBUG [c.c.a.ApiServlet] (qtp931675031-19:ctx-56f46fc4) (logid:c0d4d084) ===START===  10.0.3.251 -- POST  command=registerUserData&response=json
2024-06-14 09:26:08,935 DEBUG [c.c.a.ApiServlet] (qtp931675031-19:ctx-56f46fc4) (logid:c0d4d084) Two factor authentication is already verified for the user 2, so skipping
2024-06-14 09:26:08,943 DEBUG [c.c.a.ApiServer] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) CIDRs from which account 'Account [{"accountName":"admin","id":2,"uuid":"7669013f-2a0a-11ef-9a70-1e00da00037e"}]' is allowed to perform API calls: 0.0.0.0/0,::/0
2024-06-14 09:26:08,946 INFO  [o.a.c.a.DynamicRoleBasedAPIAccessChecker] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) Account [Account [{"accountName":"admin","id":2,"uuid":"7669013f-2a0a-11ef-9a70-1e00da00037e"}]] is Root Admin or Domain Admin, all APIs are allowed.
2024-06-14 09:26:08,947 WARN  [o.a.c.a.ProjectRoleBasedApiAccessChecker] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) Project is null, ProjectRoleBasedApiAccessChecker only applies to projects, returning API [registerUserData] for user [User {"username":"admin","uuid":"766a609c-2a0a-11ef-9a70-1e00da00037e"}.] as allowed.
2024-06-14 09:26:08,948 DEBUG [o.a.c.a.StaticRoleBasedAPIAccessChecker] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) RoleService is enabled. We will use it instead of StaticRoleBasedAPIAccessChecker.
2024-06-14 09:26:08,949 DEBUG [o.a.c.r.ApiRateLimitServiceImpl] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) API rate limiting is disabled. We will not use ApiRateLimitService.
2024-06-14 09:26:09,102 INFO  [o.a.c.u.UserDataManagerImpl] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) Configured base64 encoded user data size: 914652 bytes, actual user data size: 685987 bytes
2024-06-14 09:26:09,421 DEBUG [c.c.a.ApiServlet] (qtp931675031-19:ctx-56f46fc4 ctx-bdb563ce) (logid:c0d4d084) ===END===  10.0.3.251 -- POST  command=registerUserData&response=json


```


Sent a userdata of higher size > 1048576  , and a  400 exception will be thrown

Screenshot 2024-06-18 at 5 44 58 PM
