### PR TITLE
Fix listing service offerings with different host tags

### LINKED ISSUE #11407: Ability to change compute offering with different host tags
### The required feature described as a wish

As a User/Admin/Operator, I would like to be able to change the compute offering to one with different host tags when scaling a VM. Currently, this can only be done by first changing the offering to one without tags, and then changing it again to one with the desired tags, or by using the scaleVirtualMachine API request. However, this is not convenient for regular users. This functionality could be implemented with a toggle in the global settings for installations where it is not acceptable due to hardware compatibility.
discussed in #11402

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR introduces the global setting: `allow.different.host.tags.offerings.for.vm.scale` to fix the listing of service offerings for VMs, including offerings that contain different host tags.
- Previously only offerings without any host tag or offerings matching exactly the same VM offering host tags were displayed
- By default the setting is set to false, to preserve the previous behavior. 
- When the setting is enabled, the listing of service offerings for a VM will include offerings containing different host tags than the current offering

Fixes: #11407 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

- Create service offering A with host tag = TAG_A
- Create service offering B with host tag = TAG_B
- Edit hosts, some using tag TAG_A and some using TAG_B
- Deploy VM from service offering A
- Stop VM
- Click on Scale VM, observe that offering B is available, select offering B
- VM is properly scaled to use offering B

### CODE REVIEW

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/host/dao/HostTagsDaoImpl.java [hunk 1]
```diff
@@ -43,9 +45,12 @@ public class HostTagsDaoImpl extends GenericDaoBase<HostTagVO, Long> implements
     private final SearchBuilder<HostTagVO> stSearch;
     private final SearchBuilder<HostTagVO> tagIdsearch;
     private final SearchBuilder<HostTagVO> ImplicitTagsSearch;
+    private final GenericSearchBuilder<HostTagVO, String> tagSearch;
 
     @Inject
     private ConfigurationDao _configDao;
+    @Autowired
```
Comment (DaanHoogland) [inline engine/schema/src/main/java/com/cloud/host/dao/HostTagsDaoImpl.java]: why not @Inject, as we usually do?

Comment (nvazquez) [reply engine/schema/src/main/java/com/cloud/host/dao/HostTagsDaoImpl.java]: Fixed, thanks

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by Pearl1594 — COMMENTED** [review]
I was wondering if it would make sense to guard this under a global setting like `vm.scale.allow.differing.host.tags`, which by default would be false, to keep the existing behaviour. The reason being, with this PR it definitely gives flexibility to scale to an offering with different host tags, but end users may not be able to tell from the list which offerings would actually work for them. For example, if a user's VM is currently on a GPU host and they want to scale up for more resources, they may see SSD offerings in the list (because the cluster has SSD hosts as well), but depending on whether their specific host has both GPU and SSD tags or just GPU, the scale operation may succeed or fail with a "host tags" error. A global setting would allow users to opt into this new behaviour while keeping the current behaviour as the default.

**Comment by nvazquez** [comment]
Thanks @Pearl1594 - I have added the setting with default value = false

@blueorangutan package

**Review by Pearl1594 — COMMENTED** [review]
code lgtm

**Review by kiranchavala — COMMENTED** [review]
@nvazquez the setting is not in effect for custom offerings

Steps to reproduce the issue 

1. Have 2 host tags with hosttags h1 and h2 respectively 

2. Create a custom unconstrained offering c1 with host tag h1

3. Create another custom unconstrained offering c2 with host tag h2

4. Make sure dynamic scaling is enabled in the global settings and service offering and the registered template

5. Deploy a vm with the custom unconstrained offering c1

6. Make sure the global setting "allow.different.host.tags.offerings.for.vm.scale" is enabled 

7. Scale the running vm 

8. The custom unconstrained offering c2 with host tag h2 is not displayed 

Image


9. If the vm is stopped then all the offerings are displayed 

Screenshot 2026-04-06 at 4 19 16 PM

**Comment by nvazquez** [comment]
Hi @kiranchavala this is similar to issue: https://github.com/apache/cloudstack/issues/6865 and it seems to be by design from PR: #5923. I do see it is planned to be fixed by: #12908

**Review by kiranchavala — COMMENTED** [review]
@nvazquez  can you add the host tags and storage tags in the UI 

when a user tries to scale the VM, it's handy to see the tags associated with the service offering 

https://cloudstack.apache.org/api/apidocs-4.22/apis/listServiceOfferings.html

Image

```
(local) 🐱 > list serviceofferings id=57d7582f-d854-477c-9690-329eeada8d32  filter=hosttags,storagetags
{
  "count": 1,
  "serviceoffering": [
    {
      "hosttags": "test3",
      "storagetags": "test3"
    }
  ]
}

```

**Comment by nvazquez** [comment]
@kiranchavala please find the fix pushed, host tags and/or storage tags will only be displayed when available at least in one offering from the list

@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested the issue manually 

Tested with both admin and with normal user role 

Have 2 host tags with hosttags h1 and h2 respectively

Create a compute offering c1,c2,c3  with host tags h1,h2,h3 respectively 


Stop the vm 

Scale the vm 

Only the compute offering c3 is visible, as it has the same host tag 

Make sure the global setting "allow.different.host.tags.offerings.for.vm.scale" is enabled

Scale the vm 

Compute offering c2 is also visible, though it having a host tag h2

Also the host tags and storage tags are visible in the ui 


Image
