### PR TITLE
server: fix unwanted txn commit warning messages

### LINKED ISSUE #2642: DB Exceptions seen on latest master
On latest master, with only db deployed and no environments I see this:
```
2018-05-14 16:57:47,617 INFO  [c.c.r.ResourceLimitManagerImpl] (ResourceCountChecker-1:ctx-ed4a764d) (logid:d70d0be5) Started resource counters recalculation periodic task.
2018-05-14 16:57:47,637 WARN  [c.c.r.ResourceLimitManagerImpl] (ResourceCountChecker-1:ctx-ed4a764d) (logid:d70d0be5) Discrepency in the resource count (original count=0 correct count = 13) for type template for account ID 1 is fixed during resource count recalculation.
2018-05-14 16:57:47,657 DEBUG [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ed4a764d) (logid:d70d0be5) Rolling back the transaction: Time = 2 Name =  ResourceCountChecker-1; called by -TransactionLegacy.rollback:889-TransactionLegacy.removeUpTo:832-TransactionLegacy.close:656-TransactionContextInterceptor.invoke:36-ReflectiveMethodInvocation.proceed:174-ExposeInvocationInterceptor.invoke:92-ReflectiveMethodInvocation.proceed:185-JdkDynamicAopProxy.invoke:212-$Proxy71.countCpuNumberAllocatedToAccount:-1-ResourceLimitManagerImpl.countCpusForAccount:929-ResourceLimitManagerImpl$4.doInTransaction:902-ResourceLimitManagerImpl$4.doInTransaction:872
2018-05-14 16:57:47,658 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ed4a764d) (logid:d70d0be5) txn: Commit called when it is not a transaction: -Transaction.execute:41-Transaction.execute:47-ResourceLimitManagerImpl.recalculateAccountResourceCount:872-ResourceLimitManagerImpl$ResourceCountCheckTask.runInContext:1065-ManagedContextRunnable$1.run:49-DefaultManagedContext$1.call:56-DefaultManagedContext.callWithContext:103-DefaultManagedContext.runWithContext:53-ManagedContextRunnable.run:46-Executors$RunnableAdapter.call:511-FutureTask.runAndReset:308-ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301:180
2018-05-14 16:57:47,661 DEBUG [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ed4a764d) (logid:d70d0be5) Rolling back the transaction: Time = 3 Name =  tx-320; called by -TransactionLegacy.rollback:889-TransactionLegacy.removeUpTo:832-TransactionLegacy.close:656-TransactionContextInterceptor.invoke:36-ReflectiveMethodInvocation.proceed:174-ExposeInvocationInterceptor.invoke:92-ReflectiveMethodInvocation.proceed:185-JdkDynamicAopProxy.invoke:212-$Proxy71.countMemoryAllocatedToAccount:-1-ResourceLimitManagerImpl.calculateMemoryForAccount:933-ResourceLimitManagerImpl$4.doInTransaction:904-ResourceLimitManagerImpl$4.doInTransaction:872
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
DB, API, background tasks
~~~

##### CLOUDSTACK VERSION

~~~
master, possibly 4.11 branch
~~~

##### OS / ENVIRONMENT

Basic install with no env deployed

##### STEPS TO REPRODUCE

~~~
Deploy latest master, start mgmt server with no env deployed see logs
~~~

##### EXPECTED RESULTS

~~~
Exceptions should not be seen
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes unwanted transaction commit warning messages such:

  txn: Commit called when it is not a transaction:

The code does not need to be in a transaction following the eventually
consistent design. Fixes #2642.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Testing

Run the `update resourcecount` API for an account, it should no longer produce annoying logs.

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

File: server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java [hunk 1]
```diff
@@ -886,60 +886,54 @@ public Long doInTransaction(TransactionStatus status) {
 
     @DB
     protected long recalculateAccountResourceCount(final long accountId, final ResourceType type) {
-        Long newCount = Transaction.execute(new TransactionCallback<Long>() {
-                @Override
-                public Long doInTransaction(TransactionStatus status) {
-                    Long newCount = null;
-                    lockAccountAndOwnerDomainRows(accountId, type);
```
Comment (rafaelweingartner) [inline server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java]: Shouldn't you maintain the lock account? I mean, if this method is called when a VM is being deployed, this can generate race conditions that will lead the table to be populated with inconsistent data.

**Comment by rhtyd** [comment]
@blueorangutan test

File: server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java (hunk 1 above)
Comment (rafaelweingartner) [reply server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java]: Aren't these aggregated values (of resources usage/allocated) used to control the deployment of new resources?

I thought they were, that is why I thought it is important to have them consistent at all time.

File: server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java [hunk 2]
```diff
@@ -886,60 +887,62 @@ public Long doInTransaction(TransactionStatus status) {
...
+        }
+
+        if (newCount == null || !newCount.equals(oldCount)) {
+            Transaction.execute(new TransactionCallbackNoReturn() {
                 @Override
-                public Long doInTransaction(TransactionStatus status) {
-                    Long newCount = null;
+                public void doInTransactionWithoutResult(TransactionStatus status) {
                     lockAccountAndOwnerDomainRows(accountId, type);
-                    ResourceCountVO accountRC = _resourceCountDao.findByOwnerAndType(accountId, ResourceOwnerType.Account, type);
```
Comment (rafaelweingartner) [inline server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java]: Now you removed the aggregation of data out of the transaction, but you maintained the lock account. It will not make any difference here. Therefore, right after the data is aggregated, but not updated, some VM/resources can be allocated/deployed, and then the value is updated here. This means, we will set an invalid value.

When I suggested to maintain the lock account, was to use it out of the transaction as this mechanism is used differently. AS far as I have seen, this lock account/domain is some sort of transaction management that is executed manually based on resources that ACS does. Therefore, you can execute this command right at the beginning (at line 889) .

Comment (DaanHoogland) [reply server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java]: this line has now moved to 922. that seems right to me @rafaelweingartner , or is there another concern that I don't see?

Comment (rafaelweingartner) [reply server/src/com/cloud/resourcelimit/ResourceLimitManagerImpl.java]: are you talking about this ` lockAccountAndOwnerDomainRows(accountId, type);` line?

**Comment by rhtyd** [comment]
@rafaelweingartner @DaanHoogland sorry guys accidently resolved the conversation than reply on it (using phone).
@rafaelweingartner yes that's why I did not put them in transaction before, it was only a single update that needed to be done. Will review your comments and get back to you (eod, and on leave tomorrow and on weekends).

**Comment by rhtyd** [comment]
@rafaelweingartner wrt the old vs new implementation, there is not much change. We only update when there is a change b/w old and new resource count values. The important thing is to lock the rows from the point we decide to update for anybody reading will not get stale/old values. The transaction was not necessary actually, the locking of rows should happen only when there is a need for an update otherwise no need. Therefore, in the new/refactored logic we check if there is a change between old vs new resource count values before deciding to an update. The system as with other parts of the cloudstack are design to be eventually consistent. The method `recalculateAccountResourceCount` is supposed to get the counts/stats eventually consitent in db and is called by a periodic task (background thread), `updateResourceCount` API, whenever template is synced or deleted, or recalculation of domain triggers it. I don't see any race or locking issues.

**Comment by rhtyd** [comment]
@rafaelweingartner any more objections? We would like to get this merged before RC4 is cut.
@blueorangutan test
