### PR TITLE
UI: Fixes in the Usage UI

### LINKED ISSUE #9992: Usage server metrics section shown to users without access to the API
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.20.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

In the Usage UI, the metrics section is shown to users that do not have access to the `listUsageServerMetrics` API

image

~~~
Open the Usage UI in a user that does not have access to `listUsageServerMetrics`
~~~

##### EXPECTED RESULTS

~~~
Section is hidden
~~~

##### ACTUAL RESULTS

~~~
Section is shown with null values
~~~

### LINKED ISSUE #9994: Generate usage records action shown to users without access to `generateUsageRecords`
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.20.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

In the Usage UI, the generate usage records action is shown to users that do not have access to the `generateUsageRecords` API

image

image

~~~
Open the Usage UI in a user that does not have access to `generateUsageRecords`
~~~

##### EXPECTED RESULTS

~~~
Action is hidden
~~~

##### ACTUAL RESULTS

~~~
Action is shown
~~~

### LINKED ISSUE #9995: Purge usage records action shown to users without access to `removeRawUsageRecords`
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.20.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

In the Usage UI, the purge usage records action is shown to users that do not have access to the `removeRawUsageRecords` API

image

image

~~~
Open the Usage UI in a user that does not have access to `removeRawUsageRecords`
~~~

##### EXPECTED RESULTS

~~~
Action is hidden
~~~

##### ACTUAL RESULTS

~~~
Action is shown
~~~

### LINKED ISSUE #9996: Possible to scroll past the usage records table's footer
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.20.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

In the Usage UI, it is possible to scroll past the usage records table's footer

image

~~~
1. Open the Usage UI
2. Click on a resource's ID to copy it
3. Scroll down
~~~

##### EXPECTED RESULTS

~~~
Scroll ends on table's footer
~~~

##### ACTUAL RESULTS

~~~
Scroll goes past the table's footer
~~~

### PR DESCRIPTION
**Pull request by bernardodemarco**
### Description

This PR addresses the following issues related to the Usage UI:
- Usage metrics section is displayed with `null` values to users without access to the `listUsageServerMetrics` API (Fixes #9992);
- Purge usage records action is displayed to users without access to the `removeRawUsageRecords` API (Fixes #9995);
- Generate usage records action is displayed to users without access to the `generateUsageRecords` API (Fixes #9994);
- Vertical scroll overflow in the usage records table (Fixes #9996);
- Usage types input field is displayed to users without access to the `listUsageTypes` API. Since the `usageid` parameter of the `listUsageRecords` API can only be used alongside the `type` parameter, both form fields are now hidden when the caller does not have access to the `listUsageTypes` API.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):

- Usage UI view when the user does not have access to the `listUsageServerMetrics`,  `removeRawUsageRecords`, `generateUsageRecords` and `listUsageTypes` APIs

image

### How Has This Been Tested?

- Verified that users without access to the `listUsageServerMetrics`,  `removeRawUsageRecords`, `generateUsageRecords` and `listUsageTypes` APIs were not able to interact with them through the UI.
- Verified that the vertical overflow issue was resolved.

### CODE REVIEW

**Comment by bernardodemarco** [comment]
@blueorangutan ui

**Comment by vishesh92** [comment]
@blueorangutan ui

**Comment by bernardodemarco** [comment]
> Just one thing: the last heartbeat may be undefined. We could show something like "never" instead of "null" for the last heartbeat for this case.

@winterhazel, done

image

**Comment by winterhazel** [comment]
> > Just one thing: the last heartbeat may be undefined. We could show something like "never" instead of "null" for the last heartbeat for this case.
> 
> @winterhazel, done
> 
> image

It would also be good to change the "a few seconds ago" in this case

**Comment by bernardodemarco** [comment]
> It would also be good to change the "a few seconds ago" in this case

Done.

image

File: ui/src/views/infra/UsageRecords.vue [hunk 1]
```diff
@@ -50,6 +50,7 @@
           <a-row justify="end">
             <a-col>
               <tooltip-button
+                v-if="'generateUsageRecords' in this.$store.getters.apis"
```
Comment (Pearl1594) [inline ui/src/views/infra/UsageRecords.vue:53]: minor nit: there's no need to use `this` here
```suggestion
                v-if="'generateUsageRecords' in $store.getters.apis"
```

File: ui/src/views/infra/UsageRecords.vue [hunk 2]
```diff
@@ -70,7 +72,7 @@
     </a-card>
   </a-affix>
   <a-col>
-    <a-card size="small" :loading="serverMetricsLoading">
+    <a-card size="small" :loading="serverMetricsLoading" v-if="'listUsageServerMetrics' in this.$store.getters.apis">
```
Comment (Pearl1594) [inline ui/src/views/infra/UsageRecords.vue:75]:
```suggestion
    <a-card size="small" :loading="serverMetricsLoading" v-if="'listUsageServerMetrics' in $store.getters.apis">
```

File: ui/src/views/infra/UsageRecords.vue [hunk 3]
```diff
@@ -58,6 +59,7 @@
             </a-col>&nbsp;&nbsp;
             <a-col>
               <tooltip-button
+                v-if="'removeRawUsageRecords' in this.$store.getters.apis"
```
Comment (Pearl1594) [inline ui/src/views/infra/UsageRecords.vue:62]: same here
```suggestion
                v-if="'removeRawUsageRecords' in $store.getters.apis"
```

File: ui/src/views/infra/UsageRecords.vue [hunk 4]
```diff
@@ -159,7 +161,7 @@
               />
             </a-form-item>
           </a-col>
-          <a-col :span="3">
+          <a-col :span="3" v-if="'listUsageTypes' in this.$store.getters.apis">
```
Comment (Pearl1594) [inline ui/src/views/infra/UsageRecords.vue:164]:
```suggestion
          <a-col :span="3" v-if="'listUsageTypes' in $store.getters.apis">
```

File: ui/src/views/infra/UsageRecords.vue [hunk 5]
```diff
@@ -173,7 +175,7 @@
...
```
Comment (Pearl1594) [inline ui/src/views/infra/UsageRecords.vue:178]:
```suggestion
          <a-col :span="3" v-if="'listUsageTypes' in $store.getters.apis">
```

**Comment by bernardodemarco** [comment]
@blueorangutan ui
