### PR TITLE
Fix snapshot chaining on Xen

### LINKED ISSUE #12524: After upgrade to 4.22.0.0 snapshot.delta.max not respected
### problem

I upgraded to 4.22.0.0 on Nov 11.  I have many volumes that are set to 3 snapshots max stored by my users.

I noticed that all snapshots since Nov 11 (all existing and new ones) seem to create a massive chain of snapshots.
I had 60+ days snapshot files on the disk for every volume with daily snapshots, while the snapshot.delta.max is only  set to 7. And snapshot policy is 3 snapshots only. 

It seems the full snapshot before Nov 11 in my case was the last full snapshot. After that there is no more full snapshots, only incremental snapshots.  

What I see in database: 

in snapshots table: 

Image

And in snapshot_store_ref (have hidden rows in between - but they all show as "Hidden"

Image

Please help! I cannot even clear my storage which is now hit 95% used capacity and about to blow up!! Its tens of extra terabytes of data!! with no way to clear it other than deleting all snapshots which is a huge problem for users... 

### versions

ACS 4.22.0
XCP-NG 8.2

### The steps to reproduce the bug

1.Upgraded from 4.19 .1 to 4.22
2.
3.
...

### What to do about it?

Identify what is causing the snapshot.delta.max to not be respected.

### PR DESCRIPTION
**Pull request by JoaoJandre**
### Description

This PR fixes #12524.

After the introduction of the `Hidden` state, the snapshot chain calculation no longer works as expected for XenServer as it does not consider hidden snapshots as part of the chain, possibly leading to unending chains. This PR fixes this issue by adding the hidden snapshots  to the chain calculation.

This PR also fixes a regression introduced in commit d700e2db643c6d1adbda82957f21a6a8b696f704 which made snapshot deletion impossible.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
In an environment using XCP-ng, I set `snapshot.delta.max` to 3 and followed the steps below:
1. Create 3 volume snapshots
2. Delete the oldest volume snapshot
3. Create a new volume snapshot

Before the changes, the new snapshot would be part of the old chain. With the changes, the last snapshot is a full snapshot that is not part of the old chain.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java [hunk 1]
```diff
@@ -151,6 +154,16 @@ public boolean configure(String name, Map<String, Object> params) throws Configu
...
 
+        idStateNinSearch = createSearchBuilder();
+        idStateNinSearch.and(SNAPSHOT_ID, idStateNinSearch.entity().getSnapshotId(), SearchCriteria.Op.EQ);
+        idStateNinSearch.and(STATE, idStateNinSearch.entity().getState(), SearchCriteria.Op.NOTIN);
+        idStateNinSearch.done();
+
+        idEqRoleEqStateInSearch = createSearchBuilder();
+        idEqRoleEqStateInSearch.and(SNAPSHOT_ID, idEqRoleEqStateInSearch.entity().getSnapshotId(), SearchCriteria.Op.EQ);
+        idEqRoleEqStateInSearch.and(STORE_ROLE, idEqRoleEqStateInSearch.entity().getRole(), SearchCriteria.Op.EQ);
+        idEqRoleEqStateInSearch.and(STATE, idEqRoleEqStateInSearch.entity().getState(), SearchCriteria.Op.IN);
```
[the remark this answers is not in the document]
Comment (JoaoJandre) [reply engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java:158]: the `.create()` already calls `finalize()` (which is what `done()` does).

**Comment by JoaoJandre** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test ol9 xcpng83

**Comment by JoaoJandre** [comment]
@DaanHoogland can we rerun the tests?

**Comment by JoaoJandre** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test ol9 xcpng83

**Comment by rajujith** [comment]
@blueorangutan test ol9 xcpng83

**Comment by nvazquez** [comment]
@blueorangutan package

File: engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java [hunk 2]
```diff
@@ -387,6 +400,15 @@ public SnapshotDataStoreVO findBySnapshotIdAndDataStoreRoleAndState(long snapsho
         return findOneBy(sc);
     }
 
+    @Override
+    public List<SnapshotDataStoreVO> findBySnapshotIdAndDataStoreRoleAndStateIn(long snapshotId, DataStoreRole role, State... state) {
```
Comment (nvazquez) [inline engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java]: Very minor: usually with `findBy..` methods we would expect one item to be retrieved, in this case I think `listBy..` would be more suitable for this method

File: engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java [hunk 3]
```diff
@@ -68,6 +68,9 @@ public class SnapshotDataStoreDaoImpl extends GenericDaoBase<SnapshotDataStoreVO
     protected SearchBuilder<SnapshotDataStoreVO> searchFilteringStoreIdEqStateEqStoreRoleEqIdEqUpdateCountEqSnapshotIdEqVolumeIdEq;
     private SearchBuilder<SnapshotDataStoreVO> stateSearch;
     private SearchBuilder<SnapshotDataStoreVO> idStateNeqSearch;
+
+    private SearchBuilder<SnapshotDataStoreVO> idStateNinSearch;
```
Comment (sureshanaparti) [inline engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java:70]: @JoaoJandre changes here would conflict (rebase if it is merged) - https://github.com/apache/cloudstack/pull/12789

File: engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java (hunk 2 above)
Comment (JoaoJandre) [reply engine/schema/src/main/java/org/apache/cloudstack/storage/datastore/db/SnapshotDataStoreDaoImpl.java]: You're correct, I'll refactor it.

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test ol9 xcpng83

**Comment by JoaoJandre** [comment]
@nvazquez I looked at the errors reported by Blue Orangutan but no issues were related to this PR.

**Comment by nvazquez** [comment]
Thanks @JoaoJandre let me kick one more round of packaging and tests

@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test ol9 xcpng83

**Comment by vladimirpetrov** [comment]
@blueorangutan test ol9 xcpng83

**Comment by JoaoJandre** [comment]
Thanks for testing @vladimirpetrov

**Comment by sureshanaparti** [comment]
@blueorangutan test ol8 xcpng83
