### PR TITLE
console-proxy: fix potential NPE condition

### LINKED ISSUE #3164: Cannot open console: ConsoleProxyServlet NullPointerException
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Console proxy
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7.6.1810

##### SUMMARY

I've upgraded CloudStack from version 4.9.3.1 to ver. 4.11.2.0 on CentOS 7.6.1810. I use VMWare as hypervisor with system VM images and CS package from Shape Blue.
From VM console in Console Proxy's VM console I can see version 4.11.2.0 banner, so the system VM look upgraded.
Since the upgrade when I try to open an instance's console I get a "Server Internal Error" message inside the new window. In the management server log I'm getting this exception:

ERROR [c.c.s.ConsoleProxyServlet] (qtp510113906-18:null) (logid Unexepected exception in ConsoleProxyServlet
java.lang.NullPointerException
at com.cloud.info.ConsoleProxyInfo.formatProxyAddress(ConsoleProxyInfo.java:59)
at com.cloud.info.ConsoleProxyInfo.<init>(ConsoleProxyInfo.java:40)
at com.cloud.consoleproxy.ConsoleProxyManagerImpl.assignProxy(ConsoleProxyManagerImpl.java:389)
at com.cloud.server.ManagementServerImpl.getConsoleProxyForVm(ManagementServerImpl.java:2274)
at com.cloud.server.ManagementServerImpl.getConsoleAccessUrlRoot(ManagementServerImpl.java:2305)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
at com.sun.proxy.$Proxy193.getConsoleAccessUrlRoot(Unknown Source)
at com.cloud.servlet.ConsoleProxyServlet.handleAccessRequest(ConsoleProxyServlet.java:275)
at com.cloud.servlet.ConsoleProxyServlet.doGet(ConsoleProxyServlet.java:188)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:530)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
at java.lang.Thread.run(Thread.java:748)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by rhtyd**
When checking if the console proxy URL domain starts with *, the code
does not check if the provided string is null. When domain is not
configured the IP address should be used.

Fixes #3164

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

File: core/src/main/java/com/cloud/info/ConsoleProxyInfo.java [hunk 1]
```diff
@@ -56,14 +56,12 @@ public ConsoleProxyInfo(boolean sslEnabled, String proxyIpAddress, int port, int
     private String formatProxyAddress(String consoleProxyUrlDomain, String proxyIpAddress) {
         StringBuffer sb = new StringBuffer();
         // Domain in format *.example.com, proxy IP is 1.2.3.4 --> 1-2-3-4.example.com
-        if (consoleProxyUrlDomain.startsWith("*")) {
```
Comment (ustcweizhou) [inline core/src/main/java/com/cloud/info/ConsoleProxyInfo.java]: LGTM

**Comment by rhtyd** [comment]
@anuragaw @shwstppr @nvazquez please review

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

File: core/src/main/java/com/cloud/info/ConsoleProxyInfo.java [hunk 2]
```diff
@@ -56,14 +56,12 @@ public ConsoleProxyInfo(boolean sslEnabled, String proxyIpAddress, int port, int
...
+        if (consoleProxyUrlDomain != null && consoleProxyUrlDomain.startsWith("*")) {
```
Comment (nvazquez) [inline core/src/main/java/com/cloud/info/ConsoleProxyInfo.java]: Can we reorder this if-then-else to:

````
if (StringUtils.isBlank(consoleProxyUrlDomain) {
   // Blank config, we use the proxy IP
   sb.append(proxyIpAddress);
} else if (consoleProxyUrlDomain.startsWith("*")) {
   sb.append(proxyIpAddress.replaceAll("\\.", "-"));
   sb.append(consoleProxyUrlDomain.substring(1)); // skip the *
} else {
   // Otherwise we assume a valid domain if config not blank
   sb.append(consoleProxyUrlDomain);
}
````

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test
