### PR TITLE
kvm: fix wrong CheckVirtualMachineAnswer when vm does not exist

### LINKED ISSUE #12920: KVM HA: VM remains Running after virsh destroy; PowerReportMissing schedules HA but KVMInvestigator reports alive=true and restart is cancelled
##### ISSUE TYPE

* Bug Report

##### COMPONENT NAME

KVM, Orchestration, HA

##### CLOUDSTACK VERSION

4.22.x

##### CONFIGURATION

- KVM hypervisor
- Shared primary storage on NFS
- HA-enabled user VM
- sync.interval = 60
- no ha.tag configured
- tested with an HA-enabled VM deployed on a healthy KVM host
- multiple management servers in the zone/cluster

##### OS / ENVIRONMENT

- CloudStack management servers on Ubuntu 24.04
- MySQL 8
- KVM hosts on Linux/libvirt
- Primary storage: NFS

##### SUMMARY

On CloudStack 4.22.x, if a KVM VM is stopped unexpectedly on the hypervisor using `virsh destroy`, CloudStack detects `PowerReportMissing`, waits for the grace period, and schedules HA restart work. However, the HA worker then fails to restart the VM because `KVMInvestigator` reports the VM as alive (`alive? true`) while the host is still up.

As a result:
- the VM remains in `Running` state in CloudStack/UI
- the VM is not transitioned to `Stopped`
- HA does not restart it
- the same HA scheduling/investigation loop repeats on subsequent sync cycles

This appears related to #10406 / #10407, which were intended to fix cases where VMs were not moving to `Stopped` when `PowerReportMissing` is processed.

##### EXPECTED RESULTS

After the grace period passes, CloudStack should process `PowerReportMissing`, transition the VM to `Stopped`, and, because HA is enabled, restart the VM automatically.

Expected behavior for this test case:

1. `virsh destroy <domain>` removes the libvirt domain.
2. CloudStack detects the VM as missing.
3. After the graceful period expires, CloudStack updates the VM power report to `PowerReportMissing`.
4. CloudStack transitions the VM state from `Running` to `Stopped`.
5. HA schedules a restart for the VM.
6. The VM is restarted automatically on an eligible host.
7. The CloudStack UI/API reflects the VM state correctly and does not continue to show the VM as `Running`.

##### ACTUAL RESULTS

CloudStack detects the VM as missing and the graceful period is working correctly:

```text
2026-03-31 02:28:43,791 DEBUG ... Detected missing VM. host: 6, vm id: 91(...), power state: PowerReportMissing, last state update: 2026-03-31T02:27:43+0000
2026-03-31 02:28:43,791 DEBUG ... vm id: 91 - time since last state update(60791 ms) has not passed graceful period yet

2026-03-31 02:29:43,722 DEBUG ... Detected missing VM. host: 6, vm id: 91(...), power state: PowerReportMissing, last state update: 2026-03-31T02:27:43+0000
2026-03-31 02:29:43,722 DEBUG ... vm id: 91 - time since last state update(120722 ms) has passed graceful period
```
After the graceful period passes, CloudStack updates the VM power report and schedules HA restart work:
```
2026-03-31 02:29:43,742 DEBUG ... VM state report is updated. Host {...}, VM instance {"id":91,"instanceName":"i-2-91-VM","state":"Running"...}, power state: PowerReportMissing
2026-03-31 02:29:43,775 INFO  ... Detected out-of-band stop of a HA enabled VM ... will schedule restart.
2026-03-31 02:29:43,798 INFO  ... Schedule vm for HA: VM instance {"id":91,"instanceName":"i-2-91-VM","state":"Running"...}
2026-03-31 02:29:43,820 INFO  ... HA on VM instance {"id":91,"instanceName":"i-2-91-VM","state":"Running"...}
```
The HA worker checks the VM, and the host-side agent confirms that the libvirt domain no longer exists:
```
2026-03-31 02:29:43,855 DEBUG ... Unable to get vm state on VM instance {"id":91,"instanceName":"i-2-91-VM","state":"Running"...}```
```
KVM host agent log:
```
2026-03-31 02:29:43,928 ERROR ... Could not get state for VM [i-2-91-VM] (retry=0) due to: org.libvirt.LibvirtException: Domain not found: no domain with matching name 'i-2-91-VM'
```
However, KVMInvestigator then reports the VM as alive, and the HA restart is cancelled:
```
2026-03-31 02:29:43,859 INFO  ... KVMInvestigator found VM instance {"id":91,"instanceName":"i-2-91-VM","state":"Running"...} to be alive? true
2026-03-31 02:29:43,860 INFO  ... VM instance {"id":91,"instanceName":"i-2-91-VM","state":"Running"...} is alive and host is up. No need to restart it.
```
This same pattern repeats on later sync cycles, including 02:31:43, 02:33:43, and 02:36:43.

Final observed behavior:

the VM remains in Running state in CloudStack/UI
the VM is not transitioned to Stopped
HA does not restart the VM
the missing-domain / HA-scheduled / KVMInvestigator alive=true loop repeats continuously

### versions

cloudstack-management  4.22.0.0
cloudstack-agent 4.22.0.0 
libvirt 10.0.0-2ubuntu8.11
ubuntu 24.04 LTS

### The steps to reproduce the bug

1. Deploy a user VM on a KVM host with HA enabled.
2. Confirm the VM is in `Running` state in CloudStack.
3. On the KVM host, destroy the domain unexpectedly:

   ```bash
   virsh destroy <domain-name>

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR should fix #12920

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
makes sense

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckVirtualMachineCommandWrapperTest.java [hunk 1]
```diff
@@ -0,0 +1,196 @@
...
+
+        verify(libvirtComputingResource).getLibvirtUtilitiesHelper();
+        verify(libvirtUtilitiesHelper).getConnectionByVmName(VM_NAME);
+    }
+}
+
+
+
+
+
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/test/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtCheckVirtualMachineCommandWrapperTest.java]:
```suggestion

```

**Review by sureshanaparti — APPROVED** [review]
code lgtm

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested manually 

1. Deployed a vm with ha offering on a kvm host1

```

[root@ref-trl-11549-k-Mol8-kiran-chavala-kvm1 ~]# virsh list
 Id   Name       State
--------------------------
 2    i-2-3-VM   running
```
2. virsh destroy <domain> removes the libvirt domain.

3. CloudStack detects the VM as missing.

4. After the graceful period expires, CloudStack updates the VM power report to PowerReportMissing.

5. The VM is restarted automatically on an eligible host and the state is shown as running 
```
[root@ref-trl-11549-k-Mol8-kiran-chavala-kvm1 ~]# virsh list
 Id   Name       State
--------------------------
 3    i-2-3-VM   running
```
logs

```
2026-04-10 10:09:28,721 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-12:[]) (logid:) Detected missing VM. host: 1, vm id: 3(68a0af3d-5f59-4480-95dd-4af1456d6d2f), power state: PowerReportMissing, last state update: 2026-04-10T10:07:28+0000



2026-04-10 10:09:28,731 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-12:[]) (logid:) VM state report is updated. Host {"id":1,"name":"ref-trl-11549-k-Mol8-kiran-chavala-kvm1","type":"Routing","uuid":"f65d0b2f-e1f2-47f6-887d-31f26b257e1a"}, VM instance {"id":3,"instanceName":"i-2-3-VM","state":"Running","type":"User","uuid":"68a0af3d-5f59-4480-95dd-4af1456d6d2f"}, power state: PowerReportMissing

2026-04-10 10:09:28,741 INFO  [c.c.v.ClusteredVirtualMachineManagerImpl] (AgentManager-Handler-12:[ctx-5542e17c]) (logid:) VM VM instance {"id":3,"instanceName":"i-2-3-VM","state":"Running","type":"User","uuid":"68a0af3d-5f59-4480-95dd-4af1456d6d2f"} is at Running and we received a PowerReportMissing report while there is no pending jobs on it

2026-04-10 10:09:28,742 INFO  [c.c.v.ClusteredVirtualMachineManagerImpl] (AgentManager-Handler-12:[ctx-5542e17c]) (logid:) Detected out-of-band stop of a HA enabled VM VM instance {"id":3,"instanceName":"i-2-3-VM","state":"Running","type":"User","uuid":"68a0af3d-5f59-4480-95dd-4af1456d6d2f"}, will schedule restart.

2026-04-10 10:09:28,744 DEBUG [c.c.h.HighAvailabilityManagerExtImpl] (AgentManager-Handler-12:[ctx-5542e17c]) (logid:) HA schedule restart

2026-04-10 10:09:28,750 INFO  [c.c.h.HighAvailabilityManagerExtImpl] (AgentManager-Handler-12:[ctx-5542e17c]) (logid:) Schedule vm for HA:  VM instance {"id":3,"instanceName":"i-2-3-VM","state":"Running","type":"User","uuid":"68a0af3d-5f59-4480-95dd-4af1456d6d2f"}

2026-04-10 10:09:28,750 DEBUG [c.c.h.HighAvailabilityManagerExtImpl] (AgentManager-Handler-12:[ctx-5542e17c]) (logid:) Wakeup workers HA

2026-04-10 10:09:28,750 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-12:[ctx-5542e17c]) (logid:) Done with process of VM state report. host: Host {"id":1,"name":"ref-trl-11549-k-Mol8-kiran-chavala-kvm1","type":"Routing","uuid":"f65d0b2f-e1f2-47f6-887d-31f26b257e1a"}

2026-04-10 10:09:28,759 INFO  [c.c.h.HighAvailabilityManagerExtImpl] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) Processing work HAWork[1-HA-3-Running-Investigating]

2026-04-10 10:09:28,768 DEBUG [c.c.h.HighAvailabilityManagerExtImpl] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) RESTART with HAWORK

2026-04-10 10:09:28,772 INFO  [c.c.h.HighAvailabilityManagerExtImpl] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) HA on VM instance {"id":3,"instanceName":"i-2-3-VM","state":"Running","type":"User","uuid":"68a0af3d-5f59-4480-95dd-4af1456d6d2f"}
2026-04-10 10:09:28,775 DEBUG [c.c.a.m.ClusteredAgentManagerImpl] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) Wait time setting on com.cloud.agent.api.CheckVirtualMachineCommand is 20 seconds


2026-04-10 10:09:28,776 DEBUG [c.c.a.m.ClusteredAgentAttache] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) Seq 4-8020347986393432246: Routed from 32985566938254

2026-04-10 10:09:28,776 DEBUG [c.c.a.t.Request] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) Seq 1-8020347986393432246: Sending  { Cmd , MgmtId: 32985566938254, via: 1(
ref-trl-11549-k-Mol8-kiran-chavala-kvm1), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.CheckVirtualMachineCommand":{"vmName":"i-2-3-VM","wait":"20","bypassHostMaintenance":"false"}}] }

2026-04-10 10:09:28,785 DEBUG [c.c.a.t.Request] (AgentManager-Handler-13:[]) (logid:) Seq 1-8020347986393432246: Processing:  { Ans: , MgmtId: 32985566938254, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.CheckVirtualMachineAnswer":{"state":"PowerOff","result":"true","wait":"0","bypassHostMaintenance":"false"}}] }

2026-04-10 10:09:28,785 DEBUG [c.c.a.t.Request] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) Seq 1-8020347986393432246: Received:  { Ans: , MgmtId: 32985566938254, via: 1(ref-trl-11549-k-Mol8-kiran-chavala-kvm1), Ver: v1, Flags: 10, { CheckVirtualMachineAnswer } }

2026-04-10 10:09:36,141 INFO  [c.c.h.HighAvailabilityManagerExtImpl] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) HA is now restarting VM instance {"id":3,"instanceName":"i-2-3-VM","state":"Running","type":"User","uuid":"68a0af3d-5f59-4480-95dd-4af1456d6d2f"} on Host {"id":1,"name":"ref-trl-11549-k-Mol8-kiran-chavala-kvm1","type":"Routing","uuid":"f65d0b2f-e1f2-47f6-887d-31f26b257e1a"}

2026-04-10 10:09:36,157 INFO  [c.c.h.HighAvailabilityManagerExtImpl] (HA-Worker-2:[ctx-e2886928, work-1]) (logid:fcb78e90) Completed work HAWork[1-HA-3-Running-Scheduled]. Took 1/5 attempts.

```
