### PR TITLE
Fix #3448 quota calculation for monthly tariffs

### LINKED ISSUE #3448: Quota calculation is incorrect
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Quota
~~~

##### CLOUDSTACK VERSION

~~~
master branch
~~~

##### SUMMARY

https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java#L101
The default value of `usage.stats.job.aggregation.range` is 1440.
_aggregationDuration = Integer.parseInt(aggregationRange);
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java#L142
The value of `aggregationRatio` calculated is `1440/(30 * 24 * 60)`.

All updateQuota* functions have the bug below.
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java#L436
This line would be one-day-cost not one-hour-cost.
So the `aggregationRatio` should be fixed with `1/(30 * 24)`.

### PR DESCRIPTION
**Pull request by jairov4**
### Description

The quota calculation has been wrong for monthly tariffs (like Compute-Month, GB-Month, etc) for so much time but even when #3448 was reported it was closed without evaluation.

The wrong calculation was the price per hour, it was taking the monthly tariff and multiplying by the aggregation ratio which has no sense at all.

The right price per hour is the monthly tariff divided by the standard number of hours in a month.

Fixes #3448.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [X] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Partial execution of the component with a test vector.
Tracing the values and compared with spreadsheet.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
Your code looks alright @jairov4 but only if the aggregation is always hourly. I think there is another problem with the code and that is that the onehour vars are not named correctly; `BigDecimal onehourcostpercpu, onehourcostper100mhz, onehourcostper1mb, onehourcostforvmusage;`. I think these should have been called 'oneaggregation*'.
Have you tested with other agrregation durations?
Care to comment @abhinandanprateek , @rhtyd , @rafaelweingartner ? (not sure who else to ask)

**Comment by jairov4** [comment]
@DaanHoogland yes, this calculation is independent of the aggregation ratio because the raw usage variable is the number of hours used and we only need the hour cost. As you can see in `src/main/java/com/cloud/usage/parser/VMInstanceUsageParser.java`
image

**Comment by jairov4** [comment]
btw: should I rebase it to 4.15?

**Comment by DaanHoogland** [comment]
You can rebase it @jairov4 , if you want it on that branch. It is unlikely an new 4.15 version will come out. if you do it will be merged forward to 4.16 as well.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java [hunk 1]
```diff
@@ -340,7 +340,7 @@ public QuotaUsageVO updateQuotaDiskUsage(UsageVO usageRecord, final BigDecimal a
             BigDecimal quotaUsgage;
             BigDecimal onehourcostpergb;
             BigDecimal noofgbinuse;
-            onehourcostpergb = tariff.getCurrencyValue().multiply(aggregationRatio);
+            onehourcostpergb = tariff.getCurrencyValue().divide(s_hoursInMonth, 8, RoundingMode.HALF_DOWN);
```
Comment (DaanHoogland) [inline framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java:343]: I think you need to remove the parameter aggregationRotio` on this change as it is no longer used is it?

**Review by DaanHoogland — COMMENTED** [review]
genrally good to go, but some instances of the parameter `aggregationRotio` need to be removed.

File: framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java [hunk 2]
```diff
@@ -368,7 +368,7 @@ public QuotaUsageVO updateQuotaDiskUsage(UsageVO usageRecord, final BigDecimal a
         QuotaTariffVO tariff = _quotaTariffDao.findTariffPlanByUsageType(QuotaTypes.CPU_NUMBER, usageRecord.getEndDate());
         if (tariff != null && tariff.getCurrencyValue().compareTo(BigDecimal.ZERO) != 0 && serviceoffering.getCpu() != null) {
             BigDecimal cpu = new BigDecimal(serviceoffering.getCpu());
-            onehourcostpercpu = tariff.getCurrencyValue().multiply(aggregationRatio);
```
Comment (sureshanaparti) [inline framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java:371]: Hi @jairov4 The `aggregationRatio` considers the aggregation range specified in the global setting 'usage.stats.job.aggregation.range', which would be skipped when it is removed. Please check.

Comment (GutoVeronezi) [reply framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java:371]: @sureshanaparti, actually, considering the global setting `usage.stats.job.aggregation.range` in the calculation turns it wrong. The global setting `usage.stats.job.aggregation.range` only defines the range between each record, but the raw usage is always inserted in hours.

The `aggregationRatio` is defined by the `aggregationDuration` (`usage.stats.job.aggregation.range`) divided by `minutesInMonth` (43200). If the setting `usage.stats.job.aggregation.range` has `1440` (1 day) as value, the cost per hour will be `0.033333333`. Otherwise, if it has `60` (1 hour) as value, the cost per hour will be `0.001388889`. 

Therefore, the lower the global setting `usage.stats.job.aggregation.range` is, the lower the cost per hour will be, which is incorrect, because the raw usage is always in hour.

Comment (jairov4) [reply framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java:371]: @sureshanaparti considering the `aggregationRatio` here is actually causing the missbehavior. The raw usage already comes in hours as I pointed in the image above so it is independent of that ratio.

**Review by DaanHoogland — CHANGES_REQUESTED** [review]
@jairov4 , please remove the parameter `aggregationRatio` from methods that no longer use it.

**Comment by sureshanaparti** [comment]
> @jairov4 , please remove the parameter `aggregationRatio` from methods that no longer use it.

Hi @jairov4 Can you address the outstanding comments please. Thanks.

**Comment by jairov4** [comment]
@sureshanaparti  done!

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
cltgm

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@jairov4 looks good no regressions. The test_quota.py integration test is not run in either the smoke tests or in travis, So I'll run thos manually to make triple sure.

**Comment by DaanHoogland** [comment]
I ran the quota tests and got all to succeed except for one that requires more than a single day of data to accumulate. recarding this as success and merging because of succesfull testing and multiple LTGM.
