### PR TITLE
Fixed instance creation failure on dvswitch when using vlan id 4095

### LINKED ISSUE #4358: ACS unable to set VLAN to Trunk on Distributed Virtual Switches
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
Networking

##### CLOUDSTACK VERSION
4.14

##### CONFIGURATION
Advanced networking, Distributed Virtual Switches on VMWare 6.7

##### SUMMARY
ACS unable to set VLAN to Trunk on Distributed Virtual Switches

##### STEPS TO REPRODUCE

1- Create physical network with Distributed Virtual Switches
2- Create guest network on the physical switch with DVS
3- Set VLAN/VNI id to 4095 
4 - Deploy VM in new network

Error shows up on vCenter

### PR DESCRIPTION
**Pull request by Spaceman1984**
### Description

When creating an instance on a guest network where the vlan id has been set to 4095, the instance fails to start.
This PR sets the vlan id and range on the created port group to allow the instance to be created.

Fixes #4358

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

This has been tested by creating a guest network and setting the vlan id to 4095 and creating an instance using the specific network.

### CODE REVIEW

**Comment by rhtyd** [comment]
@Spaceman1984 have you tested this
@alexandremattioli can you review/test this, thanks.
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by rhtyd — COMMENTED** [review]
LGTM - but should the vlan range be `1-4094` @Spaceman1984 ?

**Review by rhtyd — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
LGTM 0-4094 is correct, thnx Alex for confirming.

**Comment by Spaceman1984** [comment]
Seems like there are some test failures, looking into it

**Comment by Spaceman1984** [comment]
@blueorangutan package

**Review by rhtyd — APPROVED** [review]

**Comment by Spaceman1984** [comment]
@blueorangutan test help

**Comment by Spaceman1984** [comment]
@blueorangutan test matrix

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java [hunk 1]
```diff
@@ -1073,6 +1073,10 @@ public static VMwareDVSPvlanConfigSpec createDVPortPvlanConfigSpec(int vlanId, i
     }
 
     public static VmwareDistributedVirtualSwitchVlanSpec createDVPortVlanSpec(Integer vlanId, String vlanRange) {
+        if (vlanId != null && vlanId == 4095){
+            vlanId = null;
+            vlanRange = "0-4094";
+        }
```
Comment (DaanHoogland) [inline vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:1079]: so `if (vlanId == 4095)` we set the range and  vlanId but `if (vlanId == null)` we don't care about the set range. is this intentional?

Comment (rhtyd) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:1079]: @DaanHoogland Yes the 4095 vlan ID is used a magic no. to create a trunked port group; this already exists for other hypervisors like kvm - https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+vlan+4095+%27tag+passthrough%27+for+KVM

Comment (DaanHoogland) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:1079]: yes, i understand the function of `vlandId == 4095` but my point is that it will be possible to pass `vlanId == null` and `range == '2-9,15-99,4000-4094'` or even `range == '4000-4095'`, and should we correct that combination of parameters?

Comment (DaanHoogland) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:1079]: maybe not relevant enough to this fix, never mind

**Comment by rhtyd** [comment]
@alexandremattioli @andrijapanicsb have you tested/reviewed this? Thanks

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java [hunk 2]
```diff
@@ -1073,6 +1073,10 @@ public static VMwareDVSPvlanConfigSpec createDVPortPvlanConfigSpec(int vlanId, i
     }
 
     public static VmwareDistributedVirtualSwitchVlanSpec createDVPortVlanSpec(Integer vlanId, String vlanRange) {
+        if (vlanId != null && vlanId == 4095){
```
Comment (sureshanaparti) [inline vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:1076]: @Spaceman1984 Have you tested this?

this method `createDVPortVlanSpec()` is called only when `vlanId` is null, so if check here is always 'false' and the underlying code never executes. Please check and try to fix this in the appropriate top level method in the call stack.

Comment (Spaceman1984) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/HypervisorHostHelper.java:1076]: This method is not olnly called when vlanid is null.
If vid is not null, spvlanid would be evaluated and if spvlanid is null, the method will be called.
```
if (vid == null || spvlanid == null) {
    vlanspec = createDVPortVlanSpec(vid, vlanRange);
    ...
}
```
I tested this as in the description.

**Comment by alexandremattioli** [comment]
Tested. LGTM
