### PR TITLE
api: fix account deletion event description

### LINKED ISSUE #3109: Account removal triggers event of unrelated user (from the different account) removal which has the same ID as account which is being deleted
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2.0
~~~

##### CONFIGURATION

Advanced networking, KVM

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When account is deleted, an event is generated which prints attempt of deletion of user which has the same database ID as the account which is being deleted, although the user can be from completelly different account/domain.  

##### STEPS TO REPRODUCE

* Create an account under one domain e.g. account 'account2' under 'TEST' domain.
* Then create additional user (e.g. 'account2-user2') under the same 'account2' account and note the new user ID in the DB e.g 21
* Then create several more accounts under some other domain (e.g. 'domain-test') and check in the DB that ID of one of those new accounts (e.g. 'account5') is the same as the second user ('account2-user2') ID from the previous account
* Delete the 'account5'
* Now check Events and find the attempt to delete unrelated user (account2-user2) and account (account2) while deleting 'account5'

account-accounts

User table:
account-table-user

Account table:
account-table-account

Events:
account-delete-events2

~~~

~~~

##### EXPECTED RESULTS

~~~
It was expected to generate an event to only delete account which is mented to be deleted (account5)
~~~

##### ACTUAL RESULTS

~~~
Additional event is generated saying that unrelated user and account will be deleted (account2-user2, account2)
As can be seen in the DB, the unrelated user/account are not deleted, but the event is there.


~~~
Account table:
account-account-table
User table:
account-user-table

Events:
account-delete-events2

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
Fixes #3109 

~This change fixes wrong event description with incorrect user and account IDs on account deletion.
While deleting an account, existing code was using accountID to query User from cloud.user. This resulted in the wrong user and account details in the event description. This has been fixed by listing all users for the given account and then using the first user(this will be the user with lowest ID value and will correspond to default user for the account) for details.~

As per https://github.com/apache/cloudstack/pull/3483#pullrequestreview-260554610, show only account details and nothing for user.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
Events on account delete,
Screenshot from 2019-07-11 14-47-58

## How Has This Been Tested?
UI, cmk, DB validation

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
ping for review @rhtyd @anuragaw @borisstoyanov

File: api/src/main/java/org/apache/cloudstack/api/command/admin/account/DeleteAccountCmd.java [hunk 1]
```diff
@@ -92,7 +93,8 @@ public String getEventType() {
 
     @Override
     public String getEventDescription() {
-        User user = _responseGenerator.findUserById(getId());
+        List<User> users = _accountService.getAccountUsers(_accountService.getAccount(getId()));
+        User user = users.isEmpty() ? null : users.get(0);
```
Comment (rhtyd) [inline api/src/main/java/org/apache/cloudstack/api/command/admin/account/DeleteAccountCmd.java]: The event description is wrong, the account is being deleted it may not even mention the users and simply say removing all users under the account.

File: api/src/main/java/org/apache/cloudstack/api/command/admin/account/DeleteAccountCmd.java [hunk 2]
```diff
@@ -92,7 +93,8 @@ public String getEventType() {
...
         return (user != null ? ("deleting User " + user.getUsername() + " (id: " + user.getId() + ") and accountId = " + user.getAccountId())
```
Comment (rhtyd) [inline api/src/main/java/org/apache/cloudstack/api/command/admin/account/DeleteAccountCmd.java]: can you use uuids?

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
> LGTM, please rectify the event description to (a) use UUIDs instead of internal DB integer ids, (b) write `id` as `ID` in the string, (c) write `accountId` as `account ID` (you may also provide the name), (d) consider rewriting the desdeletcription to say that the account with name and ID is being removed.

@rhtyd is it better now?

**Comment by rhtyd** [comment]
Good work @shwstppr thanks!
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by borisstoyanov** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
cc @anuragaw @borisstoyanov can you review this? Thanks.
