### PR TITLE
server: increment deviceid while importing vm data volumes

### LINKED ISSUE #6121: [vmware]device_id duplicated for multiple data disks after VM import
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### STEPS TO REPRODUCE

~~~
1. Import a VM with multiple disks
2. Observe device_id has been duplicated

~~~

##### EXPECTED RESULTS

~~~
There shouldn't be duplication 
~~~

##### ACTUAL RESULTS

~~~
MariaDB [cloud]> select id,instance_id,device_id from volumes where instance_id=9;
+----+-------------+-----------+
| id | instance_id | device_id |
+----+-------------+-----------+
| 11 |           9 |         0 |
| 12 |           9 |         1 |
| 13 |           9 |         1 |
| 14 |           9 |         2 |
+----+-------------+-----------+
4 rows in set (0.00 sec)
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #6121

deviceId for a volume/disk is never used by CloudStack VMware hypervisor plugin. Still it would be correct to increment value for each data volume/disk, behaviour similar to adding data volumes/disks.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
cltgm

File: server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java [hunk 1]
```diff
@@ -1016,14 +1016,16 @@ private UserVm importVirtualMachineInternal(final UnmanagedInstanceTO unmanagedI
             diskProfileStoragePoolList.add(importDisk(rootDisk, userVm, cluster, serviceOffering, Volume.Type.ROOT, String.format("ROOT-%d", userVm.getId()),
                     (rootDisk.getCapacity() / Resource.ResourceType.bytesToGiB), minIops, maxIops,
                     template, owner, null));
```
Comment (sureshanaparti) [inline server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:1018]: @shwstppr Is the device id 0 properly set for root disk here.

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-65u2
