### PR TITLE
vpc: optimize createMonitorServiceCommand() execution

### LINKED ISSUE #8055: Backup virtual router of a redundant VPC stays in starting state after restart with clean up.
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
VR, VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### CONFIGURATION

Advance zone with isolated network

##### SUMMARY

One of our CloudStack environments has been upgraded from `4.17.2` to `4.18.1`, last week. Then we restarted a big VPC with 11 tiers and ACLs that have 8 rules in them.
After restarting that VPC, we noticed the following behavior:

1. The backup VR stopped and destroyed (expected).
2. The new VR created and put in Starting state (expected).
3. The new VR stayed in Starting state for approximately 30 minutes. Then it turned into Stopped state.
4. 1 hour later the Async job poll returned error "Unable to serialize: Job is cancelled as it has been blocking others for too long".
5. The new VR remains in Stopped state.

We checked these, they weren't the case:
* Pod, host and cluster have enough capacity to start the VR.
* VR uses the correct system vm template.
* We removed all of our custom features from Cloudstack and ran exactly the community version but that didn't help.

##### STEPS TO REPRODUCE

~~~
1. Create a VPC with redundant VRs with 11 tiers in it.
2. Create ACLs with 10 rules and use it for all the tiers to make sure you have big amount of firewall rules in each VPC tier.
3. Attach VMs to each tier and make sure the VMs are started, so all VPC tiers turn into "Implemented" state.
4. Try to restart VPC with cleanup.
~~~

##### EXPECTED RESULTS

~~~
Both VRs will be reprovisioned in reasonable amount of time (several minutes).
~~~

##### ACTUAL RESULTS

~~~
One of the VRs will be recreated but never started.
~~~

##### ADDITIONAL INFORMATION
We notice that the actual libvirt domain of VR was never even attempted to be provisioned on the hypervisor.
Looks like the management server holds this job until it gets cancelled by some timeout.

Watching the management server log with grep by VR instance name shows the following behavior:

```
tail -f /var/log/cloudstack/management/management-server.log | grep r-27209-VM
2023-10-09 12:57:50,398 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 0 firewall Egress rule(s) to apply as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start.
2023-10-09 12:57:50,399 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 0 Ipv6 firewall rule(s) to apply as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start.
2023-10-09 12:57:50,408 DEBUG [c.c.n.r.VpcVirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 3 network ACLs to apply as a part of VPC VR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start for guest network id=4140
2023-10-09 12:57:50,455 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating  monitoring services on VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...

# 1,5 minutes later

2023-10-09 12:59:22,010 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Reapplying dhcp entries as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...
2023-10-09 12:59:22,023 DEBUG [c.c.n.r.CommandSetupHelper] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating dhcp entry for vm VM instance {"id":27189,"instanceName":"i-877-27189-VM","type":"User","uuid":"f34641cc-1885-430e-9eef-0f2560527f69"} on domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"}.
2023-10-09 12:59:22,037 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Reapplying vm data (userData and metaData) entries as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...
2023-10-09 12:59:22,048 DEBUG [c.c.n.r.CommandSetupHelper] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating user data entry for vm VM instance {"id":27189,"instanceName":"i-877-27189-VM","type":"User","uuid":"f34641cc-1885-430e-9eef-0f2560527f69"} on domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"}
2023-10-09 12:59:22,092 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 0 firewall Egress rule(s) to apply as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start.
2023-10-09 12:59:22,092 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 0 Ipv6 firewall rule(s) to apply as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start.
2023-10-09 12:59:22,100 DEBUG [c.c.n.r.VpcVirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 3 network ACLs to apply as a part of VPC VR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start for guest network id=4141
2023-10-09 12:59:22,146 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating  monitoring services on VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...

# 1,5 minutes later

2023-10-09 13:00:56,723 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Reapplying dhcp entries as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...
2023-10-09 13:00:56,734 DEBUG [c.c.n.r.CommandSetupHelper] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating dhcp entry for vm VM instance {"id":27190,"instanceName":"i-877-27190-VM","type":"User","uuid":"4aa04dae-091d-4f78-bc32-af5da5a1ca2d"} on domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"}.
2023-10-09 13:00:56,747 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Reapplying vm data (userData and metaData) entries as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...
2023-10-09 13:00:56,758 DEBUG [c.c.n.r.CommandSetupHelper] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating user data entry for vm VM instance {"id":27190,"instanceName":"i-877-27190-VM","type":"User","uuid":"4aa04dae-091d-4f78-bc32-af5da5a1ca2d"} on domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"}
2023-10-09 13:00:56,797 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 0 firewall Egress rule(s) to apply as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start.
2023-10-09 13:00:56,798 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 0 Ipv6 firewall rule(s) to apply as a part of domR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start.
2023-10-09 13:00:56,805 DEBUG [c.c.n.r.VpcVirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Found 3 network ACLs to apply as a part of VPC VR VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start for guest network id=4142
2023-10-09 13:00:56,851 DEBUG [c.c.n.r.VirtualNetworkApplianceManagerImpl] (Work-Job-Executor-6:ctx-ba2a3ea5 job-2776242/job-2776251 ctx-b405daf9) (logid:46201edd) Creating  monitoring services on VM instance {"id":27209,"instanceName":"r-27209-VM","type":"DomainRouter","uuid":"b78b470a-2a88-4705-9909-26ba84277fca"} start...

... and it contines iterating over networks, one network per 1,5 minutes. The router hasn't started on the node yet.
```

### PR DESCRIPTION
**Pull request by phsm**
### Description
This PR moves an expensive getRouterHealthChecksConfig() upper the execution stack during VPC restart. So this way it is only executed once instead of tens or hundreds times (depending on VPC tiers amount). 

This is done by introducing a `Map<String, String> routerHealthCheckConfig` argument to createMonitorServiceCommand() method that accepts pre-computed health check config.
 
Fixes #8055

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
1. Prepared a test VPC: 
- 10 tiers
- redundant offering (2 VRs)
- each tier has 1 running VM in it. 
2. Performed VPC restart with clean up. Took 61 minutes to fully restart in my case
3. Applied these changes
4. Performed VPC restart with clean up. Took 9 minutes to fully restart.

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Review by harikrishna-patnala — COMMENTED** [review]
results seems to be very interesting @phsm

File: server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java [hunk 1]
```diff
@@ -2350,7 +2350,7 @@ public boolean finalizeCommandsOnStart(final Commands cmds, final VirtualMachine
             if (reprogramGuestNtwks) {
                 finalizeIpAssocForNetwork(cmds, router, provider, guestNetworkId, null);
                 finalizeNetworkRulesForNetwork(cmds, router, provider, guestNetworkId);
-                finalizeMonitorService(cmds, profile, router, provider, guestNetworkId, true);
+                finalizeMonitorService(cmds, profile, router, provider, guestNetworkId, true, getRouterHealthChecksConfig(router));
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java:2353]:
```suggestion
                finalizeMonitorService(cmds, profile, router, provider, guestNetworkId, true, routerHealthCheckConfig);
```

@phsm seems it is called in loop here, so better get the map outside loop and pass here.

Comment (phsm) [reply server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java]: Good catch, updated

Comment (sureshanaparti) [reply server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java]: > Good catch, updated

thanks @phsm

**Review by sureshanaparti — APPROVED** [review]
Code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by phsm** [comment]
Is there anything else that I can do for this PR to be merged? I see some tests are failed but my Java knowledge isn't that great to actually fix them so I'd appreciate any help on this.

**Review by DaanHoogland — APPROVED** [review]
clgtm, not sure what we need to test for this (assuming the smoke tests have tested health check functionality)

**Comment by weizhouapache** [comment]
> So, can this PR be merged if everyone approves? :)

Not yet. 
Needs someone to manually test it

**Comment by weizhouapache** [comment]
@phsm 
would you like this PR to be merged into 4.18 or 4.19 ?

**Comment by phsm** [comment]
My opinion is since the fix doesn't break any API, then it would be better to have it merged to 4.18 (+4.19, master). 
We already have this fix applied on our production systems, no issues found.

**Comment by weizhouapache** [comment]
> My opinion is since the fix doesn't break any API, then it would be better to have it merged to 4.18 (+4.19, master). We already have this fix applied on our production systems, no issues found.

@phsm  I agree with you.
I asked you is because, if you want this to be merged into 4.18, you need to rebase with 4.18 branch.
(if I change the target branch of this PR to 4.18, there are 368 commits and lots of conflicts)

**Comment by DaanHoogland** [comment]
@phsm I think you wanted to rebase your commit onto 4.18, did you?

**Comment by weizhouapache** [comment]
@phsm 
please try the following commands
```
git fetch apache
git checkout apache/4.18
git branch -D main
git checkout -b main
git cherry-pick e34959fe66f6078b259041bd8023a1f73dec0a3c
git cherry-pick b6b7d47089d39f10712c027826ee0de830d6d9e0
git push origin main -f
```

**Comment by phsm** [comment]
> @phsm please try the following commands
> 
> ```
> git fetch apache
> git checkout apache/4.18
> git branch -D main
> git checkout -b main
> git cherry-pick e34959fe66f6078b259041bd8023a1f73dec0a3c
> git cherry-pick b6b7d47089d39f10712c027826ee0de830d6d9e0
> git push origin main -f
> ```

Thanks, that seems to have worked.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vishesh92** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by vishesh92** [comment]
Tested these changes. I couldn't find any difference in performance for these changes. I followed these steps:

1. Setup 2 envs (with and without this patch)
2. Create a VPC with redundant offering
3. Add 10 networks and launch 1 VM in each
4. Restarted VPC with cleanup
5. Check the difference in created, removed in async_job table for VPCRestartCmd

**Comment by phsm** [comment]
> Tested these changes. I couldn't find any difference in performance for these changes. I followed these steps:
> 
>     1. Setup 2 envs (with and without this patch)
> 
>     2. Create a VPC with redundant offering
> 
>     3. Add 10 networks and launch 1 VM in each
> 
>     4. Restarted VPC with cleanup
> 
>     5. Check the difference in created, removed in async_job table for VPCRestartCmd

Hi, 
As I mentioned earlier, this is only reproducible on CS installations "with history", i.e. with a large cloudstack database with a lot of both running and removed services (VMs, networks, VPCs etc).
Only then the getRouterHealthChecksConfig() takes 1-2 seconds to complete, which with combination of hundreds of executions adds a significant time to the process.

**Comment by weizhouapache** [comment]
> Tested these changes. I couldn't find any difference in performance for these changes. I followed these steps:
> 
> 1. Setup 2 envs (with and without this patch)
> 2. Create a VPC with redundant offering
> 3. Add 10 networks and launch 1 VM in each
> 4. Restarted VPC with cleanup
> 5. Check the difference in created, removed in async_job table for VPCRestartCmd

@vishesh92 
it is probably because our database is too small.
if the platforms have been running for many years (for example, more than 5), it could make big difference.

considering this is an optimization, it looks there is no regression (in manual and smoke tests), can we say it is good to merge ? @vishesh92

**Comment by vishesh92** [comment]
@weizhouapache @phsm Got it. It is good to merge from my side.

For manual testing, I just did what I mentioned in the above steps and tried to connect VMs I launched.

**Comment by weizhouapache** [comment]
> @weizhouapache @phsm Got it. It is good to merge from my side.
> 
> For manual testing, I just did what I mentioned in the above steps and tried to connect VMs I launched.

thanks @vishesh92 for the testing

I will merge it then
