### PR TITLE
vmware: fix cpu reservation during vm scale

### LINKED ISSUE #5706: vmware: on dynamic scaling a VM incorrect CPU reservation is set
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
vmware
~~~

##### CLOUDSTACK VERSION

~~~
4.16, may also exist on earlier versions
~~~

##### CONFIGURATION

4.16.0 Advanced zone; single VMware cluster with 2x ESXi 6.5 hosts

##### OS / ENVIRONMENT

Any

##### SUMMARY

Incorrect value of CPU reservation is set when a VM is dynamically scaled for a new offering.
This creates issue on subsequent VM scaling with vCenter giving error like,
```
2021-11-23 07:45:34,228 ERROR [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-1:ctx-cf5b2019 job-115/job-116 ctx-ec3931c3) (logid:83aea77d) Unable to scale vm due to Unable to execute ScaleVmCommand due to java.lang.RuntimeException: The hot-plug operation failed.
```

##### STEPS TO REPRODUCE

~~~
1. Global setting, vmware.reserve.cpu, is unchanged from default value false.
2. Enable global setting - enable.dynamic.scale.vm, create 2 offerings with dynamic scalable flag and different memory cpu/values, register dynamic scalable template and deploy a dynamic scalable VM
3. Once started, scale running VM to higher offering..
4. Observe in vCenter CPU reservation is set for the VM.
~~~

##### EXPECTED RESULTS

~~~
No CPU reservation set for the VM
~~~

##### ACTUAL RESULTS

~~~
CPU reservation set for the VM as seen from vCenter
~~~

Problem may be due to min CPU speed used here as CPU reservation, https://github.com/apache/cloudstack/blob/4.16/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L1768

While during VM deployment CPU reservation is properly calculated, https://github.com/apache/cloudstack/blob/4.16/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L1999

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5706

Correctly set CPU reservation while scaling a dynamically scalable VM.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

**Before fix** (CPU reservation is set using offering's CPU speed for the VM after scaling even when global setting vmware.reserve.cpu is false):

```
> deploy virtualmachine zoneid=d295b42c-c67b-4224-9ea7-4777ce3e788e templateid=a9c03b25-4c1e-11ec-b0f8-1e006d000305 serviceofferingid=cdb3674b-aab0-4d75-a09f-a1ad48046bd6 networkids=4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13 name=v1
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 2,
    "cpuspeed": 1000,
    "created": "2021-11-23T08:37:28+0000",
    "details": {
      "cpuOvercommitRatio": "4.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "v1",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "a9bbca90-4c1e-11ec-b0f8-1e006d000305",
    "guestosid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "haenable": false,
    "hasannotations": false,
    "hostid": "22f5a5da-88dd-476b-97af-54b53d2a8040",
    "hostname": "10.0.34.196",
    "hypervisor": "VMware",
    "id": "1f3e742b-c220-4353-b80f-9328b9127128",
    "instancename": "i-2-12-VM",
    "isdynamicallyscalable": true,
    "jobid": "1d821c40-7165-447b-a20a-a78feacd404e",
    "jobstatus": 0,
    "lastupdated": "2021-11-23T08:37:40+0000",
    "memory": 1024,
    "name": "v1",
    "nic": [
      {
        "broadcasturi": "vlan://1871",
        "deviceid": "0",
        "extradhcpoption": [],
        "id": "14715db2-d9e8-4bed-bf47-00c6a118d5ad",
        "isdefault": true,
        "isolationuri": "vlan://1871",
        "macaddress": "02:00:5c:b6:00:0a",
        "networkid": "4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13",
        "networkname": "L2-1",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "cdb3674b-aab0-4d75-a09f-a1ad48046bd6",
    "serviceofferingname": "2vCPU1G",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "a9c03b25-4c1e-11ec-b0f8-1e006d000305",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "c3206062-4c1e-11ec-b0f8-1e006d000305",
    "username": "admin",
    "zoneid": "d295b42c-c67b-4224-9ea7-4777ce3e788e",
    "zonename": "pr5700-t2575-vmware-65u2"
  }
}
```
Screenshot from 2021-11-23 14-08-18

```
> scale virtualmachine id=1f3e742b-c220-4353-b80f-9328b9127128 serviceofferingid=f57056ba-db2e-4801-b391-4d825a8eb221 
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 2,
    "cpuspeed": 1000,
    "cpuused": "NaN%",
    "created": "2021-11-23T08:37:28+0000",
    "details": {
      "cpuOvercommitRatio": "4.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "diskioread": 11,
    "diskiowrite": 0,
    "diskkbsread": 345,
    "diskkbswrite": 0,
    "displayname": "v1",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "a9bbca90-4c1e-11ec-b0f8-1e006d000305",
    "guestosid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "haenable": false,
    "hasannotations": false,
    "hostid": "22f5a5da-88dd-476b-97af-54b53d2a8040",
    "hostname": "10.0.34.196",
    "hypervisor": "VMware",
    "id": "1f3e742b-c220-4353-b80f-9328b9127128",
    "instancename": "i-2-12-VM",
    "isdynamicallyscalable": true,
    "lastupdated": "2021-11-23T08:37:40+0000",
    "memory": 2048,
    "memoryintfreekbs": 0,
    "memorykbs": 1048576,
    "memorytargetkbs": 1048576,
    "name": "v1",
    "networkkbsread": 0,
    "networkkbswrite": 0,
    "nic": [
      {
        "broadcasturi": "vlan://1871",
        "deviceid": "0",
        "extradhcpoption": [],
        "id": "14715db2-d9e8-4bed-bf47-00c6a118d5ad",
        "isdefault": true,
        "isolationuri": "vlan://1871",
        "macaddress": "02:00:5c:b6:00:0a",
        "networkid": "4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13",
        "networkname": "L2-1",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "f57056ba-db2e-4801-b391-4d825a8eb221",
    "serviceofferingname": "2vCPU2G",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "a9c03b25-4c1e-11ec-b0f8-1e006d000305",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "c3206062-4c1e-11ec-b0f8-1e006d000305",
    "username": "admin",
    "zoneid": "d295b42c-c67b-4224-9ea7-4777ce3e788e",
    "zonename": "pr5700-t2575-vmware-65u2"
  }
}
```
Screenshot from 2021-11-23 14-09-22

**After fix** (CPU reservation is set to 0 for the VM after scaling when global setting vmware.reserve.cpu is false):
```
> deploy virtualmachine zoneid=d295b42c-c67b-4224-9ea7-4777ce3e788e templateid=a9c03b25-4c1e-11ec-b0f8-1e006d000305 serviceofferingid=cdb3674b-aab0-4d75-a09f-a1ad48046bd6 networkids=4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13 name=v2
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 2,
    "cpuspeed": 1000,
    "created": "2021-11-23T08:59:53+0000",
    "details": {
      "cpuOvercommitRatio": "4.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "v2",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "a9bbca90-4c1e-11ec-b0f8-1e006d000305",
    "guestosid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "haenable": false,
    "hasannotations": false,
    "hostid": "8dc1aeec-49fa-4fe9-a176-098d754a3efb",
    "hostname": "10.0.34.112",
    "hypervisor": "VMware",
    "id": "693fb47f-84ee-4dd1-acc9-fe7477d3d6e6",
    "instancename": "i-2-13-VM",
    "isdynamicallyscalable": true,
    "jobid": "107b12ff-aad4-44a7-869a-78cab0291782",
    "jobstatus": 0,
    "lastupdated": "2021-11-23T09:00:06+0000",
    "memory": 1024,
    "name": "v2",
    "nic": [
      {
        "broadcasturi": "vlan://1871",
        "deviceid": "0",
        "extradhcpoption": [],
        "id": "5085808c-ad64-4cbf-b410-f65558efeeea",
        "isdefault": true,
        "isolationuri": "vlan://1871",
        "macaddress": "02:00:12:46:00:0b",
        "networkid": "4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13",
        "networkname": "L2-1",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "cdb3674b-aab0-4d75-a09f-a1ad48046bd6",
    "serviceofferingname": "2vCPU1G",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "a9c03b25-4c1e-11ec-b0f8-1e006d000305",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "c3206062-4c1e-11ec-b0f8-1e006d000305",
    "username": "admin",
    "zoneid": "d295b42c-c67b-4224-9ea7-4777ce3e788e",
    "zonename": "pr5700-t2575-vmware-65u2"
  }
}
```

Screenshot from 2021-11-23 14-30-26

```
> scale virtualmachine id=693fb47f-84ee-4dd1-acc9-fe7477d3d6e6 serviceofferingid=f57056ba-db2e-4801-b391-4d825a8eb221 
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 2,
    "cpuspeed": 1000,
    "cpuused": "0%",
    "created": "2021-11-23T08:59:53+0000",
    "details": {
      "cpuOvercommitRatio": "4.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "diskioread": 0,
    "diskiowrite": 0,
    "diskkbsread": 11,
    "diskkbswrite": 0,
    "displayname": "v2",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "a9bbca90-4c1e-11ec-b0f8-1e006d000305",
    "guestosid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "haenable": false,
    "hasannotations": false,
    "hostid": "8dc1aeec-49fa-4fe9-a176-098d754a3efb",
    "hostname": "10.0.34.112",
    "hypervisor": "VMware",
    "id": "693fb47f-84ee-4dd1-acc9-fe7477d3d6e6",
    "instancename": "i-2-13-VM",
    "isdynamicallyscalable": true,
    "lastupdated": "2021-11-23T09:00:06+0000",
    "memory": 2048,
    "memoryintfreekbs": 786432,
    "memorykbs": 1048576,
    "memorytargetkbs": 1048576,
    "name": "v2",
    "networkkbsread": 0,
    "networkkbswrite": 0,
    "nic": [
      {
        "broadcasturi": "vlan://1871",
        "deviceid": "0",
        "extradhcpoption": [],
        "id": "5085808c-ad64-4cbf-b410-f65558efeeea",
        "isdefault": true,
        "isolationuri": "vlan://1871",
        "macaddress": "02:00:12:46:00:0b",
        "networkid": "4cf8b5b5-d2a9-475f-9bd4-5d872ce66c13",
        "networkname": "L2-1",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "a9c4b2bd-4c1e-11ec-b0f8-1e006d000305",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "f57056ba-db2e-4801-b391-4d825a8eb221",
    "serviceofferingname": "2vCPU2G",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "a9c03b25-4c1e-11ec-b0f8-1e006d000305",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "c3206062-4c1e-11ec-b0f8-1e006d000305",
    "username": "admin",
    "zoneid": "d295b42c-c67b-4224-9ea7-4777ce3e788e",
    "zonename": "pr5700-t2575-vmware-65u2"
  }
}
```

Screenshot from 2021-11-23 14-31-18

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 1]
```diff
@@ -1765,7 +1765,7 @@ protected ScaleVmAnswer execute(ScaleVmCommand cmd) {
 
             // Check if license supports the feature
             VmwareHelper.isFeatureLicensed(hyperHost, FeatureKeyConstants.HOTPLUG);
-            VmwareHelper.setVmScaleUpConfig(vmConfigSpec, vmSpec.getCpus(), vmSpec.getMaxSpeed(), vmSpec.getMinSpeed(), (int) requestedMaxMemoryInMb, ramMb,
+            VmwareHelper.setVmScaleUpConfig(vmConfigSpec, vmSpec.getCpus(), vmSpec.getMaxSpeed(), getReservedCpuMHZ(vmSpec), (int) requestedMaxMemoryInMb, ramMb,
```
Comment (rhtyd) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1768]: How about min of both min speed and reserved mhz?

Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1768]: @rhtyd `getReservedCpuMHZ()` method seems to be using min CPU speed itself based CPU reservation global setting. 

https://github.com/apache/cloudstack/blob/4.16/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L3052-L3057

Same method is used while deploying VM, https://github.com/apache/cloudstack/blob/4.16/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L1999

**Review by DaanHoogland — APPROVED** [review]
Code looks good @shwstppr , but can you please be more explicit about what the significant chances are in the befare and after output you gave? I can see that the before screenshot has a value of 250 MHz where the after has 0 MHz but cannot determine why this is good. I read the issue 5706 where it states this is a bug, but it doesn't explain why. What are the undesired consequences?

**Comment by shwstppr** [comment]
@DaanHoogland updated summary for screenshots.
Before fix, ACS sets CPU reservation for the VM while scaling irrespective of the value of global setting - vmware.reserve.cpu. It should be set only when vmware.reserve.cpu is true. Also, it maybe wrong as it is not calculated the same way as it is done during VM deployment.
After fix, the same method is used for setting CPU reservation which is used during VM deployment.

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 1 above)
Comment (harikrishna-patnala) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1768]: yes getReservedCpuMHZ() makes sense, since it will set 0 if VmwareReserveCPU is false which is correct.

**Review by harikrishna-patnala — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by sureshanaparti** [comment]
@blueorangutan help

**Comment by sureshanaparti** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test centos7 vmware-67u3
