### PR TITLE
removed the use of SharedMountPoint storage type for the StorPool plugin

### LINKED ISSUE #6455: Bug : SharedMountPoint not working after StorPool plugin support
After adding support for StorPool in CloudStack version 4.17, Default Primary Storage of SharedMountPoint Type is no longer created. This Bug is related and caused by #6007 

This is an issue caused by the StoragePoolType of the StorPoolStorageAdaptor.

Currently, the Pool Type of StorPoolStorageAdaptor is set to SharedMountPoint.
See the following code.

StorPoolStorageAdaptor : 
~~~
@StorageAdaptorInfo(storagePoolType=StoragePoolType.SharedMountPoint)
public class StorPoolStorageAdaptor implements StorageAdaptor {
    public static void SP_LOG(String fmt, Object... args) {
    ......
~~~

For this reason, even if it is a Default SharedMountPoint type of storage other than StorPool, LibvirtStorageAdaptor is not selected by the following code, but StorPoolStorageAdaptor is selected and an error occurs.

KVMStoragePoolManager :
~~~
    private StorageAdaptor getStorageAdaptor(StoragePoolType type) {
        // type can be null: LibVirtComputingResource:3238
        if (type == null) {
            return _storageMapper.get("libvirt");
        }
        StorageAdaptor adaptor = _storageMapper.get(type.toString());
        if (adaptor == null) {
            // LibvirtStorageAdaptor is selected by default
            adaptor = _storageMapper.get("libvirt");
        }
        return adaptor;
    }
~~~

In my opinion, it is better to create a separate Pool Type for StorPoolStorageAdaptor like the LINSTOR Plugin.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, API, Plugin
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
~~~

##### CONFIGURATION

3 Hosts, GFS2 Clustered File System, Shared Mount Point : /mnt/gfs2

##### OS / ENVIRONMENT

CentOS 8.5, CloudStack 4.17.0

##### STEPS TO REPRODUCE

~~~
1. AddPrimaryStorage 
2. Select SharedMountPoint Protocol
3. Input Mount Directory
4. Select DefaultPrimary Provider
5. Submit 
~~~

##### EXPECTED RESULTS

Create Shared Mount Point Primary Storage

##### ACTUAL RESULTS

SharedMountPoint Primary Storage is recorded in DB, but the pool is not actually created because an appropriate StorageAdaptor is not selected.

### PR DESCRIPTION
**Pull request by slavkap**
### Description

This PR fixes #6455 

The default storage adaptor - `LibvirtStorageAdaptor` - is used by different storage types and doesn't use the annotation `@StorageAdaptorInfo`. In this case, a storage plugin that wants to adopt one of the predefined storage pool types will override the default behaviour. If fixing the issue in general (for new storage plugins or current ones that want to reuse the existing storage pool types) would affect all volume/snapshot/VM cases. This will lead to the need of extensive testing for each storage plugin for which we don't have the resources to do it. That's why this patch fixes the old behaviour for the SharedMountPoint by adding a new storage pool type for the StorPool plugin.

### Types of changes

- [] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [X] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Tested with the upgrade from CS 4.17.0.0 to 4.17.1.0
Manually tested test cases with created instances before the upgrade
executed smoke tests for the StorPool plugin

### CODE REVIEW

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java [hunk 1]
```diff
@@ -83,4 +96,25 @@ public void updateSystemVmTemplates(Connection conn) {
             throw new CloudRuntimeException("Failed to find / register SystemVM template(s)");
         }
     }
+
+    private void updateStorageType() {
```
Comment (sureshanaparti) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java:100]:
```suggestion
    private void updateStorPoolStorageType() {
```

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java [hunk 2]
```diff
@@ -83,4 +96,25 @@ public void updateSystemVmTemplates(Connection conn) {
...
+        storageDao = new PrimaryDataStoreDaoImpl();
+        List<StoragePoolVO> storPoolPools = storageDao.findPoolsByProvider("StorPool");
```
Comment (sureshanaparti) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java:102]: Can you use the same string constant defined for StorPool provider ?

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java [hunk 3]
```diff
@@ -83,4 +96,25 @@ public void updateSystemVmTemplates(Connection conn) {
...
+        for (StoragePoolVO storagePoolVO : storPoolPools) {
+            if (StoragePoolType.SharedMountPoint == storagePoolVO.getPoolType()) {
+                storagePoolVO.setPoolType(StoragePoolType.StorPool);
+                storageDao.update(storagePoolVO.getId(), storagePoolVO);
+            }
+            updateStorPoolVolumesToStorPoolType(storagePoolVO.getId());
+        }
+    }
+
+    private void updateStorPoolVolumesToStorPoolType(long storagePoolId) {
```
Comment (sureshanaparti) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java:112]:
```suggestion
    private void updateStorageTypeForStorPoolVolumes(long storagePoolId) {
```

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java [hunk 4]
```diff
@@ -83,4 +96,25 @@ public void updateSystemVmTemplates(Connection conn) {
...
+
+    private void updateStorageType() {
+        storageDao = new PrimaryDataStoreDaoImpl();
+        List<StoragePoolVO> storPoolPools = storageDao.findPoolsByProvider("StorPool");
+        for (StoragePoolVO storagePoolVO : storPoolPools) {
+            if (StoragePoolType.SharedMountPoint == storagePoolVO.getPoolType()) {
+                storagePoolVO.setPoolType(StoragePoolType.StorPool);
+                storageDao.update(storagePoolVO.getId(), storagePoolVO);
+            }
+            updateStorPoolVolumesToStorPoolType(storagePoolVO.getId());
```
Comment (sureshanaparti) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java:108]: better move this call to if above

File: plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java [hunk 5]
```diff
@@ -233,7 +233,6 @@ public void createAsync(DataStore dataStore, DataObject data, AsyncCompletionCal
 
                     VolumeVO volume = volumeDao.findById(vinfo.getId());
                     volume.setPoolId(dataStore.getId());
-                    volume.setPoolType(StoragePoolType.SharedMountPoint);
```
Comment (sureshanaparti) [inline plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/driver/StorPoolPrimaryDataStoreDriver.java:236]: I think, you can keep pool type as StoragePoolType.StorPool

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java (hunk 4 above)
Comment (slavkap) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java:108]: I don't think there will be cases with StorPool primary storage with a different storage type than the `SharedMountPoint`. But just in case, if there are any, I want to update all the volumes of the pool with the new storage type

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java (hunk 2 above)
Comment (sureshanaparti) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41700to41710.java:102]: > Hi, @sureshanaparti. Thanks for the code review!
> I don't want to add a dependency for the StorPool plugin to use one string. Also, I didn't check it, but I think there will be a circular dependency problem here if I add the plugin as a dependency

fine, ensure the provider string is correct/the same as in the StorPool plugin.

File: api/src/main/java/com/cloud/storage/Storage.java [hunk 6]
```diff
@@ -148,7 +148,8 @@ public static enum StoragePoolType {
         PowerFlex(true, true), // Dell EMC PowerFlex/ScaleIO (formerly VxFlexOS)
         ManagedNFS(true, false),
         Linstor(true, true),
-        DatastoreCluster(true, true); // for VMware, to abstract pool of clusters
+        DatastoreCluster(true, true), // for VMware, to abstract pool of clusters
+        StorPool(true, false);
```
[the remark this answers is not in the document]
Comment (slavkap) [reply api/src/main/java/com/cloud/storage/Storage.java:152]: I forgot to change it to true. Thanks!

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan test matrix

**Review by nvazquez — APPROVED** [review]
Code LGTM

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@slavkap does this need more changes or can it be marked ready for review?

**Comment by slavkap** [comment]
@shwstppr, I need to execute a few more tests in our lab. For that reason, it's still marked as a draft if there is a need to change something

**Comment by slavkap** [comment]
Hi @dhslove, @mlsorensen! If you have time, is it possible to test this PR with SharedMountPoint?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@slavkap are you done with tests? Smoke tests look good. Should we merge?

**Comment by slavkap** [comment]
@shwstppr, yes, it's ready, but isn't it better for users with `SharedMountPoint` to test it?

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 7]
```diff
@@ -2868,7 +2869,8 @@ public int compare(final DiskTO arg0, final DiskTO arg1) {
                     && (pool.getType() == StoragePoolType.NetworkFilesystem
                     || pool.getType() == StoragePoolType.SharedMountPoint
                     || pool.getType() == StoragePoolType.Filesystem
-                    || pool.getType() == StoragePoolType.Gluster)) {
+                    || pool.getType() == StoragePoolType.Gluster
+                    || pool.getType() == StoragePoolType.StorPool)) {
```
Comment (GutoVeronezi) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2873]: We could create a `Set` with the types allowed and verify if it "contains", to reduce the `if` complexity.

**Comment by dhslove** [comment]
> @shwstppr, yes, it's ready, but isn't it better for users with `SharedMountPoint` to test it?

@slavkap I can test during next week. I will share the result after testing.

**Review by shwstppr — APPROVED** [review]
LGTM. Tested with a KVM centos7 env. Was able to add a SharedMountPoint primary storage and deploy VM, volumes using it.

**Comment by rohityadavcloud** [comment]
ping @dhslove any update on your testing?
I think this can be merged, looks like @shwstppr has tested this.

**Comment by dhslove** [comment]
> ping @dhslove any update on your testing? I think this can be merged, looks like @shwstppr has tested this.

@slavkap @rohityadavcloud LGTM, I tested with CentOS 8 KVM environment. I checked create Shared Mount Point Storage. Also I checked working fine with already existing Shared Mount Point Storage. It works fine.

**Comment by slavkap** [comment]
Thank you, everyone, for the reviews and tests!
