### PR TITLE
[KVM] Disconnect the volumes with the proper storage adaptor.

### LINKED ISSUE #6026: KVM - Volumes are not disconnected from the host while migrate or stop a VM
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM hypervisor
~~~

##### CLOUDSTACK VERSION

~~~
4.16 and newer
~~~

##### SUMMARY

When you migrate a Virtual machine to another host the volumes are still connected to the old one. Also, the situation is the same when you stop a virtual machine, the volumes are not disconnected.

Affected Storage drivers are - SolidFire, Linstor, StorPool and those using `IscsiAdmStorageAdaptor`

##### STEPS TO REPRODUCE

~~~
Stop a Virtual Machine - the attached volumes has to be disconnected from the host
Migrate a Virtual machine - the attached volumes has to be disconnected from the old host
~~~

##### EXPECTED RESULTS

~~~
all volumes have to be disconnected when you stop a VM or disconnected from the old host while migrating
~~~

##### ACTUAL RESULTS

~~~
The volumes are still connected on the host
~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR addresses the changes to disconnect the volumes with the proper storage adaptor.

Fixes #6026 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested some VM operations (mainly stop and migrate) with NFS and PowerFlex storage pools.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java [hunk 1]
```diff
@@ -165,6 +166,20 @@ public boolean connectPhysicalDisksViaVmSpec(VirtualMachineTO vmSpec) {
     }
 
     public boolean disconnectPhysicalDisk(Map<String, String> volumeToDisconnect) {
+        if (MapUtils.isEmpty(volumeToDisconnect)) {
+            return false;
+        }
+
```
Comment (sureshanaparti) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java:172]: The pool type is set in the StopCommand here, so it is better to use the respective adaptor to disconnect the volume (instead of looping through all the adaptors).

https://github.com/apache/cloudstack/blob/ac794a0c850480bd75837b003bd065b9a3d6e629/engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java#L1688-L1691

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java [hunk 2]
```diff
@@ -214,12 +214,12 @@ public boolean disconnectPhysicalDisk(String volumePath, KVMStoragePool pool) {
 
     @Override
     public boolean disconnectPhysicalDisk(Map<String, String> volumeToDisconnect) {
-        return true;
+        return false;
     }
 
     @Override
     public boolean disconnectPhysicalDiskByPath(String localPath) {
```
Comment (sureshanaparti) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java:221]: The overridden adaptor methods not processing / disconnecting the file in the local path should return '`false`' as per the comment here.

https://github.com/apache/cloudstack/blob/ac794a0c850480bd75837b003bd065b9a3d6e629/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/StorageAdaptor.java#L53-L55

The first adaptor which returns _true_ is considered to be the adaptor that processed the volume disconnection request.

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java [hunk 3]
```diff
@@ -331,12 +331,6 @@ public boolean disconnectPhysicalDisk(String volumeUuid, KVMStoragePool pool) {
 
     @Override
     public boolean disconnectPhysicalDisk(Map<String, String> volumeToDisconnect) {
```
Comment (sureshanaparti) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/IscsiAdmStorageAdaptor.java:333]: This code is not needed as the PowerFlex/ScaleIO adaptor method is called now, during the StopCommand.

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by slavkap — APPROVED** [review]
the code LGTM, manually tested

**Review by nvazquez — APPROVED** [review]
LGTM

**Review by GutoVeronezi — APPROVED** [review]
Code LGTM, did not tested it though.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DennisKonrad — APPROVED** [review]
Quick manual test an code review
LGTM

**Review by svenvogel — APPROVED** [review]
@sureshanaparti LGTM! Tested in our Testenvironment.

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java (hunk 2 above)
Comment (DaanHoogland) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/ScaleIOStorageAdaptor.java:221]: sounds correct. I am assuming you have tested the behaviour.

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
Hi @slavkap @DennisKonrad Can you test with latest changes and confirm. Thanks.

**Review by svenvogel — APPROVED** [review]
LVGTM. 👍

**Comment by DennisKonrad** [comment]
@sureshanaparti I like the improved logging. 
LGTM

**Review by slavkap — APPROVED** [review]
