### PR TITLE
vmware: fix stopped VM volume migration

### LINKED ISSUE #4674: vmware: vm operations fail after ROOT volume migration
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### CONFIGURATION

Hypervisor: VMware, 2x VMware 6.7.3 ESXi hosts
Advanced networking
2x NFS primary stores
One NFS based datastorecluster primary store

##### OS / ENVIRONMENT

CentOS 7 management server

##### SUMMARY

When ROOT volume of a stopped VM is migrated from one primary store to another, VM operations start failing.
~~~
====================== ==================== ===========================
Template deployasis    VM has data disks    VM start after migration   
====================== ==================== ===========================
True                   No                   fail (VM not found in vcenter)        
True                   Yes                  fail (VM not found in vcenter)             
False                  No                   success         
False                  Yes                  fail (data disk not found in vcenter)                 
====================== ==================== ===========================
~~~

##### STEPS TO REPRODUCE

~~~
Start a VM with a ROOT and a DATA disk
Stop the VM after deployment
Migrate ROOT disk to a different store using migrateVolume API or volume details view
Start the VM
~~~

##### EXPECTED RESULTS

~~~
VM can be started, destroyed
~~~

##### ACTUAL RESULTS

~~~
VM fails to start, destroy. Failure in other operations
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #4674 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Deploy VM with data disk(s)
2. Stop VM
3. Migrate ROOT volume of the VM to another storage pool
4. Start VM <- VM should successfully start

```
(localcloud) SBCM5> > list virtualmachines id=88afcb03-b3b8-48f1-913a-f9b8224e16d7 
{
  "count": 1,
  "virtualmachine": [
    {
      "account": "admin",
      "affinitygroup": [],
      "cpunumber": 1,
      "cpuspeed": 500,
      "cpuused": "0%",
      "created": "2021-03-26T07:12:40+0000",
      "details": {
        "Message.ReservedCapacityFreed.Flag": "false",
        "cpuOvercommitRatio": "2.0",
        "dataDiskController": "osdefault",
        "memoryOvercommitRatio": "1.0",
        "rootDiskController": "lsilogic"
      },
      "diskioread": 0,
      "diskiowrite": 0,
      "diskkbsread": 0,
      "diskkbswrite": 0,
      "displayname": "t1",
      "displayvm": true,
      "domain": "ROOT",
      "domainid": "f4ba1ec0-8dfe-11eb-a621-1e00d1000368",
      "guestosid": "f4ce8b5a-8dfe-11eb-a621-1e00d1000368",
      "haenable": false,
      "hostid": "0ac50654-1bf1-4dce-ae61-3e303b4ca2bc",
      "hostname": "10.0.33.107",
      "hypervisor": "VMware",
      "id": "88afcb03-b3b8-48f1-913a-f9b8224e16d7",
      "instancename": "i-2-3-VM",
      "isdynamicallyscalable": false,
      "memory": 512,
      "memoryintfreekbs": 5120,
      "memorykbs": 524288,
      "memorytargetkbs": 524288,
      "name": "t1",
      "networkkbsread": 0,
      "networkkbswrite": 0,
      "nic": [
        {
          "broadcasturi": "vlan://1638",
          "extradhcpoption": [],
          "gateway": "10.1.1.1",
          "id": "180a8231-142a-4b41-8970-3db230eb9c7f",
          "ipaddress": "10.1.1.54",
          "isdefault": true,
          "isolationuri": "vlan://1638",
          "macaddress": "02:00:78:cd:00:01",
          "netmask": "255.255.255.0",
          "networkid": "1d953710-bdc5-43d6-be18-2b600a5ec9ee",
          "networkname": "net1",
          "secondaryip": [],
          "traffictype": "Guest",
          "type": "Isolated"
        },
        {
          "broadcasturi": "vlan://1631",
          "extradhcpoption": [],
          "gateway": "10.1.1.1",
          "id": "0734faa4-30da-4ebf-b088-0baeac55387e",
          "ipaddress": "10.1.1.94",
          "isdefault": false,
          "isolationuri": "vlan://1631",
          "macaddress": "02:00:1e:cb:00:01",
          "netmask": "255.255.255.0",
          "networkid": "e5c58088-03d9-41b7-9832-04bfe6ff3da0",
          "networkname": "net2",
          "secondaryip": [],
          "traffictype": "Guest",
          "type": "Isolated"
        }
      ],
      "osdisplayname": "Other Linux (64-bit)",
      "ostypeid": "f4ce8b5a-8dfe-11eb-a621-1e00d1000368",
      "passwordenabled": false,
      "rootdeviceid": 0,
      "rootdevicetype": "ROOT",
      "securitygroup": [],
      "serviceofferingid": "2ced6329-96a0-4bad-bdce-9c004501fb03",
      "serviceofferingname": "Small Instance",
      "state": "Running",
      "tags": [],
      "templatedisplaytext": "ma",
      "templateid": "03a2c29f-9d9e-4d74-ad0f-8888ac1db3f7",
      "templatename": "ma",
      "userid": "0c02b74a-8dff-11eb-a621-1e00d1000368",
      "username": "admin",
      "zoneid": "000fb9f9-6d97-4a6e-860f-1875b8270907",
      "zonename": "pr4758-t268-vmware-65u2"
    }
  ]
}
(localcloud) SBCM5> > list volumes virtualmachineid=88afcb03-b3b8-48f1-913a-f9b8224e16d7 
{
  "count": 2,
  "volume": [
    {
      "account": "admin",
      "chaininfo": "{\"diskDeviceBusName\":\"scsi0:0\",\"diskChain\":[\"[95a458528779364c8d96bd3d35df2392] i-2-3-VM/f239c0a2f9c5492bb81dabcd701fc5ce.vmdk\"]}",
      "clusterid": "1fa7097a-204a-4e19-a827-0b4ebd4a14cf",
      "clustername": "p1-c1",
      "created": "2021-03-26T07:17:38+0000",
      "destroyed": false,
      "deviceid": 0,
      "diskioread": 0,
      "diskiowrite": 0,
      "diskkbsread": 0,
      "diskkbswrite": 0,
      "displayvolume": true,
      "domain": "ROOT",
      "domainid": "f4ba1ec0-8dfe-11eb-a621-1e00d1000368",
      "hypervisor": "VMware",
      "id": "3b449766-aee3-49ee-a34b-b91f8561358d",
      "isextractable": false,
      "name": "ROOT-3-0",
      "path": "f239c0a2f9c5492bb81dabcd701fc5ce",
      "physicalsize": 43319296,
      "podid": "94f99c85-3285-4f0e-876d-f5653f97ade4",
      "podname": "Pod1",
      "provisioningtype": "thin",
      "quiescevm": false,
      "serviceofferingdisplaytext": "Small Instance",
      "serviceofferingid": "2ced6329-96a0-4bad-bdce-9c004501fb03",
      "serviceofferingname": "Small Instance",
      "size": 52428800,
      "state": "Ready",
      "storage": "pr4758-t268-vmware-65u2-esxi-pri1",
      "storageid": "95a45852-8779-364c-8d96-bd3d35df2392",
      "storagetype": "shared",
      "tags": [],
      "templatedisplaytext": "ma",
      "templateid": "03a2c29f-9d9e-4d74-ad0f-8888ac1db3f7",
      "templatename": "ma",
      "type": "ROOT",
      "utilization": "82.6%",
      "virtualmachineid": "88afcb03-b3b8-48f1-913a-f9b8224e16d7",
      "virtualsize": 52428800,
      "vmdisplayname": "t1",
      "vmname": "t1",
      "vmstate": "Running",
      "zoneid": "000fb9f9-6d97-4a6e-860f-1875b8270907",
      "zonename": "pr4758-t268-vmware-65u2"
    },
    {
      "account": "admin",
      "attached": "2021-03-26T07:16:54+0000",
      "chaininfo": "{\"diskDeviceBusName\":\"scsi0:1\",\"diskChain\":[\"[95a458528779364c8d96bd3d35df2392] i-2-3-VM/f2a259f17f644d019ff0f13f2e5db5a0.vmdk\"]}",
      "clusterid": "1fa7097a-204a-4e19-a827-0b4ebd4a14cf",
      "clustername": "p1-c1",
      "created": "2021-03-26T07:16:45+0000",
      "destroyed": false,
      "deviceid": 1,
      "diskioread": 0,
      "diskiowrite": 0,
      "diskkbsread": 0,
      "diskkbswrite": 0,
      "diskofferingdisplaytext": "Small Disk, 5 GB",
      "diskofferingid": "a17dc876-7bf6-4ebb-afa5-205723073343",
      "diskofferingname": "Small",
      "displayvolume": true,
      "domain": "ROOT",
      "domainid": "f4ba1ec0-8dfe-11eb-a621-1e00d1000368",
      "hypervisor": "VMware",
      "id": "548ff64d-5385-41fa-8365-f2593a4551fb",
      "isextractable": true,
      "name": "d1",
      "path": "f2a259f17f644d019ff0f13f2e5db5a0",
      "physicalsize": 0,
      "podid": "94f99c85-3285-4f0e-876d-f5653f97ade4",
      "podname": "Pod1",
      "provisioningtype": "thin",
      "quiescevm": false,
      "size": 5368709120,
      "state": "Ready",
      "storage": "pr4758-t268-vmware-65u2-esxi-pri1",
      "storageid": "95a45852-8779-364c-8d96-bd3d35df2392",
      "storagetype": "shared",
      "tags": [],
      "type": "DATADISK",
      "utilization": "0.0%",
      "virtualmachineid": "88afcb03-b3b8-48f1-913a-f9b8224e16d7",
      "virtualsize": 5368709120,
      "vmdisplayname": "t1",
      "vmname": "t1",
      "vmstate": "Running",
      "zoneid": "000fb9f9-6d97-4a6e-860f-1875b8270907",
      "zonename": "pr4758-t268-vmware-65u2"
    }
  ]
}
(localcloud) SBCM5> > stop virtualmachine id=88afcb03-b3b8-48f1-913a-f9b8224e16d7 
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "cpuused": "0%",
    "created": "2021-03-26T07:12:40+0000",
    "details": {
      "Message.ReservedCapacityFreed.Flag": "false",
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "lsilogic"
    },
    "diskioread": 0,
    "diskiowrite": 0,
    "diskkbsread": 0,
    "diskkbswrite": 0,
    "displayname": "t1",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "f4ba1ec0-8dfe-11eb-a621-1e00d1000368",
    "guestosid": "f4ce8b5a-8dfe-11eb-a621-1e00d1000368",
    "haenable": false,
    "hypervisor": "VMware",
    "id": "88afcb03-b3b8-48f1-913a-f9b8224e16d7",
    "instancename": "i-2-3-VM",
    "isdynamicallyscalable": false,
    "jobid": "a97c141d-71b8-452e-859a-28868ac11ddc",
    "jobstatus": 0,
    "memory": 512,
    "memoryintfreekbs": 5120,
    "memorykbs": 524288,
    "memorytargetkbs": 524288,
    "name": "t1",
    "networkkbsread": 0,
    "networkkbswrite": 0,
    "nic": [
      {
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "180a8231-142a-4b41-8970-3db230eb9c7f",
        "ipaddress": "10.1.1.54",
        "isdefault": true,
        "macaddress": "02:00:78:cd:00:01",
        "netmask": "255.255.255.0",
        "networkid": "1d953710-bdc5-43d6-be18-2b600a5ec9ee",
        "networkname": "net1",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      },
      {
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "0734faa4-30da-4ebf-b088-0baeac55387e",
        "ipaddress": "10.1.1.94",
        "isdefault": false,
        "macaddress": "02:00:1e:cb:00:01",
        "netmask": "255.255.255.0",
        "networkid": "e5c58088-03d9-41b7-9832-04bfe6ff3da0",
        "networkname": "net2",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "Other Linux (64-bit)",
    "ostypeid": "f4ce8b5a-8dfe-11eb-a621-1e00d1000368",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "2ced6329-96a0-4bad-bdce-9c004501fb03",
    "serviceofferingname": "Small Instance",
    "state": "Stopped",
    "tags": [],
    "templatedisplaytext": "ma",
    "templateid": "03a2c29f-9d9e-4d74-ad0f-8888ac1db3f7",
    "templatename": "ma",
    "userid": "0c02b74a-8dff-11eb-a621-1e00d1000368",
    "username": "admin",
    "zoneid": "000fb9f9-6d97-4a6e-860f-1875b8270907",
    "zonename": "pr4758-t268-vmware-65u2"
  }
}
(localcloud) SBCM5> > list storagepools filter=id,name,scope,clusterid,clustername,hypervisor
{
  "count": 2,
  "storagepool": [
    {
      "clusterid": "1fa7097a-204a-4e19-a827-0b4ebd4a14cf",
      "clustername": "p1-c1",
      "id": "4616afa5-447f-3846-bfc9-f7c5108b4c67",
      "name": "pr4758-t268-vmware-65u2-esxi-pri2",
      "scope": "CLUSTER"
    },
    {
      "clusterid": "1fa7097a-204a-4e19-a827-0b4ebd4a14cf",
      "clustername": "p1-c1",
      "id": "95a45852-8779-364c-8d96-bd3d35df2392",
      "name": "pr4758-t268-vmware-65u2-esxi-pri1",
      "scope": "CLUSTER"
    }
  ]
}
(localcloud) SBCM5> > migrate volume volumeid=3b449766-aee3-49ee-a34b-b91f8561358d storageid=4616afa5-447f-3846-bfc9-f7c5108b4c67
{
  "volume": {
    "account": "admin",
    "clusterid": "1fa7097a-204a-4e19-a827-0b4ebd4a14cf",
    "clustername": "p1-c1",
    "created": "2021-03-26T07:53:57+0000",
    "destroyed": false,
    "deviceid": 0,
    "displayvolume": true,
    "domain": "ROOT",
    "domainid": "f4ba1ec0-8dfe-11eb-a621-1e00d1000368",
    "hypervisor": "VMware",
    "id": "3b449766-aee3-49ee-a34b-b91f8561358d",
    "isextractable": false,
    "name": "ROOT-3-0",
    "path": "fc78a63779bb4ee6bce2f5d47b88ea55",
    "podid": "94f99c85-3285-4f0e-876d-f5653f97ade4",
    "podname": "Pod1",
    "provisioningtype": "thin",
    "quiescevm": false,
    "serviceofferingdisplaytext": "Small Instance",
    "serviceofferingid": "2ced6329-96a0-4bad-bdce-9c004501fb03",
    "serviceofferingname": "Small Instance",
    "size": 52428800,
    "state": "Ready",
    "storage": "pr4758-t268-vmware-65u2-esxi-pri2",
    "storageid": "4616afa5-447f-3846-bfc9-f7c5108b4c67",
    "storagetype": "shared",
    "tags": [],
    "templatedisplaytext": "ma",
    "templateid": "03a2c29f-9d9e-4d74-ad0f-8888ac1db3f7",
    "templatename": "ma",
    "type": "ROOT",
    "virtualmachineid": "88afcb03-b3b8-48f1-913a-f9b8224e16d7",
    "vmdisplayname": "t1",
    "vmname": "t1",
    "vmstate": "Stopped",
    "zoneid": "000fb9f9-6d97-4a6e-860f-1875b8270907",
    "zonename": "pr4758-t268-vmware-65u2"
  }
}
(localcloud) SBCM5> > start virtualmachine id=88afcb03-b3b8-48f1-913a-f9b8224e16d7 
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "cpuused": "0%",
    "created": "2021-03-26T07:12:40+0000",
    "details": {
      "Message.ReservedCapacityFreed.Flag": "false",
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "lsilogic"
    },
    "diskioread": 0,
    "diskiowrite": 0,
    "diskkbsread": 0,
    "diskkbswrite": 0,
    "displayname": "t1",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "f4ba1ec0-8dfe-11eb-a621-1e00d1000368",
    "guestosid": "f4ce8b5a-8dfe-11eb-a621-1e00d1000368",
    "haenable": false,
    "hostid": "0ac50654-1bf1-4dce-ae61-3e303b4ca2bc",
    "hostname": "10.0.33.107",
    "hypervisor": "VMware",
    "id": "88afcb03-b3b8-48f1-913a-f9b8224e16d7",
    "instancename": "i-2-3-VM",
    "isdynamicallyscalable": false,
    "jobid": "445c10a7-cb0f-4c76-8fe5-96f4f48879ed",
    "jobstatus": 0,
    "memory": 512,
    "memoryintfreekbs": 5120,
    "memorykbs": 524288,
    "memorytargetkbs": 524288,
    "name": "t1",
    "networkkbsread": 0,
    "networkkbswrite": 0,
    "nic": [
      {
        "broadcasturi": "vlan://1638",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "180a8231-142a-4b41-8970-3db230eb9c7f",
        "ipaddress": "10.1.1.54",
        "isdefault": true,
        "isolationuri": "vlan://1638",
        "macaddress": "02:00:78:cd:00:01",
        "netmask": "255.255.255.0",
        "networkid": "1d953710-bdc5-43d6-be18-2b600a5ec9ee",
        "networkname": "net1",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      },
      {
        "broadcasturi": "vlan://1631",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "0734faa4-30da-4ebf-b088-0baeac55387e",
        "ipaddress": "10.1.1.94",
        "isdefault": false,
        "isolationuri": "vlan://1631",
        "macaddress": "02:00:1e:cb:00:01",
        "netmask": "255.255.255.0",
        "networkid": "e5c58088-03d9-41b7-9832-04bfe6ff3da0",
        "networkname": "net2",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "Other Linux (64-bit)",
    "ostypeid": "f4ce8b5a-8dfe-11eb-a621-1e00d1000368",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "2ced6329-96a0-4bad-bdce-9c004501fb03",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "ma",
    "templateid": "03a2c29f-9d9e-4d74-ad0f-8888ac1db3f7",
    "templatename": "ma",
    "userid": "0c02b74a-8dff-11eb-a621-1e00d1000368",
    "username": "admin",
    "zoneid": "000fb9f9-6d97-4a6e-860f-1875b8270907",
    "zonename": "pr4758-t268-vmware-65u2"
  }
}
```

### CODE REVIEW

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java [hunk 1]
```diff
@@ -2683,15 +2683,14 @@ public Answer deleteVolume(DeleteCommand cmd) {
                         List<VirtualDisk> virtualDisks = vmMo.getVirtualDisks();
                         List<String> managedDatastoreNames = getManagedDatastoreNamesFromVirtualDisks(virtualDisks);
 
+                        // Preserve other disks of the VM
```
Comment (harikrishna-patnala) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:2686]: Thanks for these changes @shwstppr. 
Can you please test destroy VM and expunge VM cases with VM having disks. Because this particular block is removed to address disk detachments in case of destroy VM. If those operations are not effected, this looks good to me.

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java (hunk 1 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:2686]: @harikrishna-patnala I've verified the destroy case and have seen any issue.
Will try to share API responses if needed

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
`test_03_migrate_detached_volume` failure related to https://github.com/apache/cloudstack/pull/4785

**Comment by rhtyd** [comment]
@nvazquez @harikrishna-patnala can you review this?

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 2]
```diff
@@ -1898,10 +1900,14 @@ protected StartAnswer execute(StartCommand cmd) {
...
-                                controllerInfo, systemVm)) {
-                            throw new Exception("Failed to create VM. vmName: " + vmInternalCSName);
+                        } else {
+                            boolean blankVmCreated = hyperHost.createBlankVm(vmNameOnVcenter, vmInternalCSName, vmSpec.getCpus(), vmSpec.getMaxSpeed().intValue(), getReservedCpuMHZ(vmSpec),
+                                    vmSpec.getLimitCpuUse(), (int) (vmSpec.getMaxRam() / ResourceType.bytesToMiB), getReservedMemoryMb(vmSpec), guestOsId, rootDiskDataStoreDetails.first(), false,
+                                    controllerInfo, systemVm);
+                            if (!blankVmCreated) {
+                                throw new Exception("Failed to create VM. vmName: " + vmInternalCSName);
+                            }
+                            deployAsIs = false;
```
Comment (nvazquez) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1910]: Can you please include a log line explaining why not deploying-as-is in this case? Otherwise will look confusion as the StartCommand may receive deployAsIs = true and not honouring it

Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1911]: @nvazquez I've added a log message. Please see if there needs to be any change in the text.
Also, I've found that systemvms use the same flow with the default systemvm template, i.e., register a blank VM and then start it. Though deployAsIs was already `false` in that case.

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 2 above)
Comment (nvazquez) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1911]: Yes - as long a new system VM template is not registered it uses the non-deploy-as-is behaviour

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
LGTM

Manually tested these scenarios, all succeeded:

````
====================== ==================== ===========================
Template deployasis    VM has data disks    VM start after migration   
====================== ==================== ===========================
True                   No                   success       
True                   Yes                  success             
False                  No                   success         
False                  Yes                  success                 
====================== ==================== ===========================
````

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java (hunk 2 above)
Comment (sureshanaparti) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1911]: @shwstppr possible to consider user input through some strictness flag for deployAsIs, and then fallback to not deploying-as-is case if strictness flag is false?

Comment (harikrishna-patnala) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1911]: @shwstppr, a small concern here. Since we are starting the VM as not deployAsIs for a VM which is actually a deployAsIs, will there be any problem while applying vApp properties as it is. Can you please test that.

Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:1911]: Thanks for pointing it out @harikrishna-patnala . There seem an issue vApp appliances. Re-working on it.

**Comment by shwstppr** [comment]
Moved to draft for rework

**Comment by shwstppr** [comment]
@blueorangutan package

@nvazquez @harikrishna-patnala I've made changes to use relocateVM API for migrating attached volumes of a stopped VM. Please review.
Inter-cluster migration, in this case, won't be allowed (part overlaps with #4895)
In the case of inter-cluster migration we shouldn't allow migration using migrateVolume API when VM has more than one disk (rather ask user to use migrateVirtualMachine API?)
cc @rhtyd

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@shwstppr looks like in UI we do support migration of stopped VM (https://github.com/apache/cloudstack/blob/master/ui/src/config/section/compute.js#L298), so I think we should allow migration of stopped VM, i.e. all disks. The migrateVolume API will do this for individual disk, so it's fundamentally different from migrating the entire VM with all its disks. If the issue is merge conflict, you may meld both your PRs together. Let's see what others have to say - @harikrishna-patnala @nvazquez @andrijapanicsb

**Comment by harikrishna-patnala** [comment]
In my understanding the concern is about inter cluster migration.
So if we use migrateVolumeAPI and if there is a possibility that disks of a stopped VM can land on different storage pools which are different clusters then we should not allow that operation.
I agree with @shwstppr on this to disallow the API for inter-cluster migration.

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java [hunk 3]
```diff
@@ -138,11 +144,83 @@ private boolean isOnVmware(DataObject srcData, DataObject destData) {
...
+            }
+        }
+        if (clusterId == null && hostId != null) {
+            HostVO host = hostDao.findById(hostId);
+            if (host != null) {
+                clusterId = host.getClusterId();
+            }
+        }
+        return new Pair<>(clusterId, hostId);
+    }
```
Comment (shwstppr) [inline plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java:182]: @rhtyd @DaanHoogland @Pearl1594 @harikrishna-patnala I want to move this method to some common class where it can be accessed by: 

1. `engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java`
2. `plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java`
3. `plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java`

Any suggestions to which class?

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

File: plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java (hunk 3 above)
Comment (harikrishna-patnala) [reply plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java:182]: @shwstppr I think virtualMachineManagerImpl.java is the better place since I don't see any hypervisor specific code here and this can be useful later for other usecases too.

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java (hunk 3 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java]: thanks @harikrishna-patnala. Done.

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

File: engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java [hunk 4]
```diff
@@ -255,4 +256,10 @@ static String getHypervisorHostname(String name) {
     boolean unmanage(String vmUuid);
 
     UserVm restoreVirtualMachine(long vmId, Long newTemplateId) throws ResourceUnavailableException, InsufficientCapacityException;
+
+    Pair<Long, Long> findClusterAndHostIdForVmFromVolumes(long vmId);
+
+    Pair<Long, Long> findClusterAndHostIdForVm(VirtualMachine vm);
+
+    Pair<Long, Long> findClusterAndHostIdForVm(long vmId);
```
Comment (nvazquez) [inline engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java:264]: As methods are related, why not leaving only this one and make the first two methods as private on the implementation?

File: engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java [hunk 5]
```diff
@@ -2294,43 +2294,6 @@ private void markVolumesInPool(VMInstanceVO vm, StoragePool destPool, Answer[] h
...
-            if (host != null) {
-                clusterId = host.getClusterId();
-            }
-        }
-        return new Pair<>(clusterId, hostId);
-    }
-
     private void migrateThroughHypervisorOrStorage(StoragePool destPool, VMInstanceVO vm) throws StorageUnavailableException, InsufficientCapacityException {
         final VirtualMachineProfile profile = new VirtualMachineProfileImpl(vm);
         Pair<Long, Long> vmClusterAndHost = findClusterAndHostIdForVm(vm);
```
Comment (nvazquez) [inline engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java:2299]: With the above comment, this should be receiving vm.getId() instead

File: plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java [hunk 6]
```diff
@@ -210,7 +173,7 @@ private VirtualMachine getVolumeVm(DataObject srcData) {
     private Pair<Long, String> getHostIdForVmAndHostGuidInTargetClusterForAttachedVm(VirtualMachine vm,
                                                                                      StoragePool targetPool,
                                                                                      ScopeType targetScopeType) {
-        Pair<Long, Long> clusterAndHostId = findClusterAndHostIdForVm(vm);
+        Pair<Long, Long> clusterAndHostId = vmManager.findClusterAndHostIdForVm(vm);
```
Comment (nvazquez) [inline plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java:163]: With the above comment, this should be passing vm.getId() instead

Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/org/apache/cloudstack/storage/motion/VmwareStorageMotionStrategy.java]: Done

File: engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java (hunk 5 above)
Comment (shwstppr) [reply engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java:2299]: Uses private method

File: engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java (hunk 4 above)
Comment (shwstppr) [reply engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java:260]: Made other methods private

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by nvazquez — APPROVED** [review]
Thanks @shwstppr LGTM

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@borisstoyanov @nvazquez are you lgtm on this?

**Comment by nvazquez** [comment]
Yes, LGTM after various rounds of review and manual testing

**Review by vladimirpetrov — APPROVED** [review]
LGTM, tested with both standard template and multi-disk one.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3
