### PR TITLE
UI: fix issues when deploy VNF applicance on network with SG

### LINKED ISSUE #12435: UI: No checkbox to configure rules for VNF management interfaces
### problem

- Zone type: Advanced
- Security group enabled in the zone: No
- Network Type: Shared
- Security group enabled with the network: Yes

### versions

4.20

### The steps to reproduce the bug

1.
2.
3.
...

### What to do about it?

_No response_

### LINKED ISSUE #12470: UI:VNF Appliance management information is not displayed
### problem

The VNF appliance management information is not displayed in the appliance UI although its configured on the VNF template. Details are visible with API/CMK. 

### versions

4.20.2

### The steps to reproduce the bug

1.Register a VNF template
2.Configure the VNF settings with access details, in this case https_path,https_port,web_user,web_password
3.Deploy a VNF appliance and check the VNF appliance management information
...

### What to do about it?

Fix the UI to show the management information.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

since #9415 , shared network with Security groups are supported in advanced zone (with SG)

This PR fixes two issues when deploy VNF appliance on such network
- "Configure network rules for VNF's management interfaces" is not visible (#12435)

image

- "Security groups" are not listed in details of VNF appliance

image

- Fix Access details of VNF appliance (#12470)

image

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@weizhouapache could you add some test configuration description to this PR?

File: ui/src/config/section/network.js [hunk 1]
```diff
@@ -356,7 +356,10 @@ export default {
       permission: ['listVnfAppliances'],
       resourceType: 'UserVm',
       params: () => {
-        return { details: 'servoff,tmpl,nics', isvnf: true }
+        return {
+          details: 'group,nics,secgrp,tmpl,servoff,diskoff,iso,volume,affgrp,backoff',
```
Comment (weizhouapache) [inline ui/src/config/section/network.js]:
```suggestion
          details: 'group,nics,secgrp,tmpl,servoff,diskoff,iso,volume,affgrp,backoff,vnfnics',
```

File: ui/src/views/network/VnfAppliancesTab.vue [hunk 2]
```diff
@@ -120,7 +120,7 @@ export default {
   methods: {
     fetchData () {
       var params = {
-        details: 'servoff,tmpl,nics',
+        details: 'group,nics,secgrp,tmpl,servoff,diskoff,iso,volume,affgrp,backoff',
```
Comment (weizhouapache) [inline ui/src/views/network/VnfAppliancesTab.vue]:
```suggestion
        details: 'group,nics,secgrp,tmpl,servoff,diskoff,iso,volume,affgrp,backoff,vnfnics',
```

**Comment by weizhouapache** [comment]
> @weizhouapache could you add some test configuration description to this PR?

added a paragraph in the description. cc @RosiKyu 

> Refer to https://docs.cloudstack.apache.org/en/latest/adminguide/networking/security_groups.html
> `To enable security groups for an existing advanced zone which doesn’t have security groups enabled, the administrator can enable the SecurityGroupProvider for the physical network of the zone. This will allow user to create networks with Security Groups.`

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by RosiKyu** [comment]
@blueorangutan package

**Review by RosiKyu — APPROVED** [review]
### LGTM 

### Test Report 

**Environment:** KVM, Advanced Zone with Shared Network + Security Groups enabled

### Test Results

| Test Case | Result |
|-----------|--------|
| Toggle "Configure network rules for VNF's management interfaces" visible | PASS |
| Toggle default state (OFF) | PASS |
| Security groups tab visible in VNF details | PASS |
| VNF Security Group created and assigned | PASS |
| Management access information displayed | PASS |

### Evidence
Screenshot from 2026-01-22 00-27-43
Screenshot from 2026-01-22 00-26-52
Screenshot from 2026-01-22 00-26-44

Screenshot from 2026-01-22 00-29-15

Screenshot from 2026-01-22 00-34-13


### Minor Issue
The tooltip says "**True by default**" but the [documentation](https://docs.cloudstack.apache.org/en/latest/adminguide/networking/vnf_templates_appliances.html#deploying-vnf-appliances) and actual behavior is "**False by default**". 

Consider updating the tooltip for consistency

**Comment by weizhouapache** [comment]
thanks @RosiKyu for the testing, awesome


> ### Minor Issue
> The tooltip says "**True by default**" but the [documentation](https://docs.cloudstack.apache.org/en/latest/adminguide/networking/vnf_templates_appliances.html#deploying-vnf-appliances) and actual behavior is "**False by default**".
> 
> Consider updating the tooltip for consistency

I will fix the minor issue in #12499 

cc @DaanHoogland
