### PR TITLE
server: prevent duplicate HA works and alerts

### LINKED ISSUE #10367: Multiple alerts for HA on VM and host
### problem

HA jobs for VM on host disconnection/down are not synchronized. CloudStack creates multiple HA jobs for the same VM when host goes into the Down state

### versions

4.19.2.0-SNAPSHOT, other 4.19 and above versions as wel

### The steps to reproduce the bug

1. Create a cluster with 2 hypervisor hosts
2. Create a HA enabled VM
3. Make the host running VM go into down state (used https://linuxconfig.org/how-to-crash-your-linux-system-with-fork-bomb)
4. After sometime when VM is started on a different hosts observe multiple HA alerts are generated for the same

Image

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #10367

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
@DaanHoogland @sureshanaparti just a heads up, I'm still investigating more on this. I'm looking into AgentManagerImpl to not call HA process using HighAvailabilityManagerImpl multiple times.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@shwstppr any update on this?

**Comment by shwstppr** [comment]
@Pearl1594 I'm looking into this. I'll update today or tomorrow.

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java [hunk 1]
```diff
@@ -294,6 +295,10 @@ public void scheduleRestartForVmsOnHost(final HostVO host, boolean investigate)
                 "Host [" + hostDesc + "] is down." + ((sb != null) ? sb.toString() : ""));
 
         for (VMInstanceVO vm : reorderedVMList) {
+            VMInstanceVO finalVm = vm;
+            if (pendingHaWorks.stream().anyMatch(h -> h.getInstanceId() == finalVm.getId())) {
+                continue;
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:300]: @shwstppr , should we/does it make sense to add a debug or trace statement here?

**Comment by shwstppr** [comment]
@DaanHoogland @Pearl1594 @sureshanaparti this is ready for review now

@blueorangutan package

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java [hunk 2]
```diff
@@ -265,36 +266,49 @@ public void scheduleRestartForVmsOnHost(final HostVO host, boolean investigate)
...
         final List<VMInstanceVO> vms = _instanceDao.listByHostId(host.getId());
+        final List<HaWorkVO> pendingHaWorks = _haDao.listPendingHAWorkForHost(host.getId());
         final DataCenterVO dcVO = _dcDao.findById(host.getDataCenterId());
 
         // send an email alert that the host is down
         StringBuilder sb = null;
         List<VMInstanceVO> reorderedVMList = new ArrayList<VMInstanceVO>();
-        if ((vms != null) && !vms.isEmpty()) {
+        int skippedHAVms = 0;
+        if (CollectionUtils.isNotEmpty(vms)) {
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:276]: I think this block could go in its own method.

**Review by DaanHoogland — APPROVED** [review]
clgtm (only style remark)

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
tested with `z(){ z|z& }; z&` on the host running the VM. Between host down and vm starting only one alert per type was reported:

Screenshot 2025-05-06 at 10 40 08
