### PR TITLE
server: set download volume format to qcow2 for KVM volumes

### LINKED ISSUE #10937: Unable to Copy Or Register Cloudstack +KVM RAW Template on Ceph
### problem

This Issue is created with reference to discussion 
https://github.com/apache/cloudstack/discussions/10383

I Have cloudstack infrastructure using ceph as primary storage and all the templates created from existing volumes are in RAW format. I cannot use copy function to copy the template to another zone or download and register the template. The Error on download is as follows
Failed to install: Template content is unsupported, or mismatch between selected format and template content. Found : QEMU QCOW2 Image (v3), 11811160064 bytes

### versions

4.20 +KVM + CEPH Storge

### The steps to reproduce the bug

1.templates created from existing volumes are in RAW format
2.
3.
...

### What to do about it?

As per previous releases the Volume Downloaded  was in qcow2. Current release its in RAW

### LINKED ISSUE #10963: CS-4.20.0.0 KVM Volume Download RAW template instead of QCOW2
### problem

Download template:

Cloudstack

WHen I attempt to upload  a Qcow2 I got an error that the format is not supported.

https://M-Y-I-P.ourclouddomain.com/userdata/47705e02-ee10-434f-b04d-54ef043842f0/ROOT-22.raw

There are no errors, at all
I saw the file copied to the Secondary storage via the SSVM and its just come as raw.

My understanding is the File at the secondary storage should be .qcow2 when using kvm, even if we are using CEPH as primary.

Is there a hidden setting ?
Is the new normal behavior?
What is the process in this case to Register a template, Should we use a RAW file in this scenario to register a Template.

Thank you

Tata Y.

### versions

Cloudstack 4.20.0.0
Primary Storage CEPH IPV6
Secondary Storage NFS - EMC ipv4
Hypervisor KVM 

consoleproxy.url.domain = *.ourclouddomain.com
consoleproxy.sslEnabled = true
secstorage.ssl.cert.domain = *.ourclouddomain.com
secstorage.encrypt.copy = true

### The steps to reproduce the bug

1. Create a VNF from an ISO
2. Configure the VNF general settings
3. Download the Volume template from Volume> Download - show raw extension instead of QCOW2

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #10963 #10383 #10937

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java [hunk 1]
```diff
@@ -74,7 +76,14 @@ private String createObjectNameForExtractUrl(String installPath, ImageFormat for
         }
 
         if (format != null) {
-            objectNameInUrl = objectNameInUrl + "." + format.getFileExtension();
+            if (dataObject.getTO() != null
+                    && DataObjectType.VOLUME.equals(dataObject.getTO().getObjectType())
+                    && HypervisorType.KVM.equals(dataObject.getTO().getHypervisorType())) {
+                // Fix: The format of KVM volumes on image store is qcow2
+                objectNameInUrl = objectNameInUrl + "." + ImageFormat.QCOW2.getFileExtension();
```
Comment (nvazquez) [inline plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java:83]: Hi @weizhouapache, the fix looks good but was thinking that since the format is passed from the format stored on the `volume_store_ref` table, could it be simpler to fix that instead? (subject to testing)

Comment (weizhouapache) [reply plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java:83]: Thanks Nicolas for the advice
I thought the format is from `volumes` table
I will have a look

Comment (nvazquez) [reply plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java:83]: Sorry @weizhouapache please discard, I thought the copy for the download will be stored on that table, but that table doesn't have the format column, should be using the format from volumes table.

**Review by nvazquez — APPROVED** [review]
Code LGTM - haven't tested it

File: plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java (hunk 1 above)
Comment (weizhouapache) [reply plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java:83]: Actually you give me a hint to check if the install_path in volume_store_ref table is correct.

I suspect the install_path ends with .raw for volumes on ceph too. I do not have a ceph environment to verify it for now.

Even if this PR fixes the suffix of download URL, the install_path needs to be fixed as well (to .qcow2).

Comment (slavkap) [reply plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java:83]: @weizhouapache, I've checked, and you are right that install_path ends with .raw
```
*************************** 1. row ***************************
                  id: 21
            store_id: 1
           volume_id: 680
             zone_id: 1
             created: 2025-07-18 10:23:19
        last_updated: NULL
              job_id: NULL
        download_pct: 100
                size: 0
       physical_size: 0
      download_state: DOWNLOADED
            checksum: NULL
           error_str: NULL
          local_path: NULL
        install_path: volumes/2/680/873d67fc-df4c-41f1-891d-1f8202b0d17f.raw
                 url: NULL
        download_url: http://10.2.133.42/userdata/c0e1a78e-752e-44b5-ab70-89f47fec144f/ROOT-426.raw
               state: Ready
           destroyed: 0
        update_count: 2
             ref_cnt: 0
             updated: 2025-07-18 10:23:42
download_url_created: 2025-07-18 10:23:42
```

Comment (weizhouapache) [reply plugins/storage/image/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackImageStoreDriverImpl.java:83]: > @weizhouapache, I've checked, and you are right that install_path ends with .raw
> ```
> *************************** 1. row ***************************
>                   id: 21
>             store_id: 1
>            volume_id: 680
>              zone_id: 1
>              created: 2025-07-18 10:23:19
>         last_updated: NULL
>               job_id: NULL
>         download_pct: 100
>                 size: 0
>        physical_size: 0
>       download_state: DOWNLOADED
>             checksum: NULL
>            error_str: NULL
>           local_path: NULL
>         install_path: volumes/2/680/873d67fc-df4c-41f1-891d-1f8202b0d17f.raw
>                  url: NULL
>         download_url: http://10.2.133.42/userdata/c0e1a78e-752e-44b5-ab70-89f47fec144f/ROOT-426.raw
>                state: Ready
>            destroyed: 0
>         update_count: 2
>              ref_cnt: 0
>              updated: 2025-07-18 10:23:42
> download_url_created: 2025-07-18 10:23:42
> ```
> 

thanks @slavkap for checking !

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@weizhouapache is this ready for review? any further changes needed on this?

**Comment by weizhouapache** [comment]
> @weizhouapache is this ready for review? any further changes needed on this?

@sureshanaparti
I do not have a ceph env to verifiy if this PR works 
as @slavkap shared, the install_path (in volume_store_ref table) ends with `.raw`, we might need to fix it too

**Comment by weizhouapache** [comment]
Updated this PR. 
It is not ready for review and testing

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@kiranchavala  
can you please test this PR when you have time ? thanks

**Review by shwstppr — COMMENTED** [review]
@weizhouapache After applying changes I was able to see download volumes are now QCOW2 format.
But this is only for volumes which I tried downloading after upgrade.
If I had already tried a volume before upgrade, it continues to give a RAW file link.
Is this expected?

Image

**Review by shwstppr — APPROVED** [review]
LGTM. After starting and stopping VM again and then trying to download the volume, the issue mentioned in https://github.com/apache/cloudstack/pull/11198#pullrequestreview-3271924787 is not seen. 

Image

**Comment by weizhouapache** [comment]
thanks a lot for the testing @shwstppr

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package
