### PR TITLE
VPC VR: return UNKNOWN redundant state if no guest nics

### LINKED ISSUE #10677: listRouter provides "FAULT" redundantstate for VPC with no instance running
### problem

When all instances are stopped in a VPC with redundant routers the redundantstate will change to FAULT. This is a misleading state, because the routers are still running and working correctly. If you start an instance the routers will change to PRIMARY and BACKUP redundantstate.

### versions

The versions of ACS: 4.19.2.0

### The steps to reproduce the bug

1. create a vpc
2. create networks and instances in this vpc
3. stop all instances in vpc
4. use api call listRouters or take aloook at the UI in Infrastructure -> Virtual routers
...

### What to do about it?

I would not expect FAULT as Redundant state when all instnaces are stopped in a vpc, because this indicates that something is wrong with the it. But this is not the case, after starting at least 1 instance the Redundant state gets back to PRIMARY and BACKUP.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #10677 

steps to reproduce the issue
- create a redundant VPC
- create a vpc tier
- create a vm but do not start it
- check the VR redundant state after a while, both vpc VRs are FAULT state

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: systemvm/debian/opt/cloud/bin/checkrouter.sh [hunk 1]
```diff
@@ -18,13 +18,29 @@
...
+if [ "$ROUTER_TYPE" = "vpcrouter" ];then
+    GUEST_NICS=$(python3 -c "
+import json
+data = json.load(open('/etc/cloudstack/ips.json'))
+for nic, objs in data.items():
+   if isinstance(objs, list):
+       for obj in objs:
+           if obj.get('nw_type') == 'guest' and obj.get('add'):
+               print(nic)
+                     ")
```
Comment (DaanHoogland) [inline systemvm/debian/opt/cloud/bin/checkrouter.sh]: create a method for readability?

**Review by DaanHoogland — APPROVED** [review]
clgtm, one remark though

File: systemvm/debian/opt/cloud/bin/checkrouter.sh (hunk 1 above)
Comment (weizhouapache) [reply systemvm/debian/opt/cloud/bin/checkrouter.sh]: done. thanks @DaanHoogland for the review

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by harikrishna-patnala — APPROVED** [review]
image

Tested LGTM. VRs state is Unknown for both after a while too.

**Comment by weizhouapache** [comment]
thanks @harikrishna-patnala  for the testing

I am wondering if the status should be UNKNOWN or BACKUP
what do you think ? @harikrishna-patnala @DaanHoogland

**Comment by harikrishna-patnala** [comment]
> thanks @harikrishna-patnala for the testing
> 
> I am wondering if the status should be UNKNOWN or BACKUP what do you think ? @harikrishna-patnala @DaanHoogland

UNKNOWN seems to be fine @weizhouapache as it is really an unknown state right, both as BACKUP may not look good.

**Comment by weizhouapache** [comment]
> UNKNOWN seems to be fine @weizhouapache as it is really an unknown state right, both as BACKUP may not look good.

correct, BACKUP state means there is another VR in PRIMARY state
let's keep UNKNOWN, thanks @harikrishna-patnala 

@DaanHoogland 
if no objection, let's merge ?
