### PR TITLE
engine, server, services: fix for respecting secondary storage threshold limit

### LINKED ISSUE #3287: Secondary storage pool 90pct limit ignored
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
* Secondary storage pool / SSVM

##### CLOUDSTACK VERSION
* Any

##### CONFIGURATION
* Any

##### OS / ENVIRONMENT
* N/A

##### SUMMARY
* Secondary storage pools should in theory not be considered for template / volume / ISO / snapshot upload if percentage utilisation is > 90%
* However if no other pool exist < 90% then the first available secondary pool will be chosen and the 90% utilisation limit ignored.
* This results in secondary storage pools potentially filling up until copy process fails, potentially leading to data loss
* In the following line secondary pools below 90% utilisation are returned:
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java#L155
* However if no secondary storage pool exists <90% then the first secondary storage pool is still picked: https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java#L160

##### STEPS TO REPRODUCE
* Create zone with single secondary pool and fill this to above 90%
* Try to upload template / ISO / volume and observe this succeeding

##### EXPECTED RESULTS
* Upload process should gracefully fail.

##### ACTUAL RESULTS
* Upload process allows for upload to happen above 90% utilisation

### PR DESCRIPTION
**Pull request by shwstppr**
Retrieval of an image store using ImageStoreProviderManager has been refactored by introducing three different methods,
`DataStore getRandomImageStore(List<DataStore> imageStores);`
To get an image store for reading purpose. Threshold capacity check will not be used here.
`DataStore getImageStoreWithFreeCapacity(List<DataStore> imageStores);`
To get an image store for reading purpose. Threshold capacity check will be used here and the store with max free space will be returned. If no store with filled storage less than the threshold is found, the NULL value will be returned.
`List<DataStore> listImageStoresWithFreeCapacity(List<DataStore> imageStores);`
To get a list of image stores for writing purpose which fulfills threshold capacity check.

Correspondingly DataStoreManager methods have been refactored to return similar values for a given zone,
```
DataStore getRandomImageStore(long zoneId);
DataStore getImageStoreWithFreeCapacity(long zoneId);
List<DataStore> listImageStoresWithFreeCapacity(long zoneId);
```
Consumers have been refactored to accept NULL value and throw exception or log error if needed.

Fixes -
#3287 - NULL value will be returned when secondary storage is needed for writing but there is not store with free space.
#3041 - Rather than returning random secondary storage for writing, storage with max. free space will be returned.
#3478 - For migration on VMware, all writable secondary storage will be mounted while preparation.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

File: engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java [hunk 1]
```diff
@@ -198,18 +198,20 @@ protected void copyTemplateToTargetFilesystemStorageIfNeeded(VolumeInfo srcVolum
         VMTemplateStoragePoolVO sourceVolumeTemplateStoragePoolVO = vmTemplatePoolDao.findByPoolTemplate(destStoragePool.getId(), srcVolumeInfo.getTemplateId());
         if (sourceVolumeTemplateStoragePoolVO == null && destStoragePool.getPoolType() == StoragePoolType.Filesystem) {
             DataStore sourceTemplateDataStore = dataStoreManagerImpl.getImageStore(srcVolumeInfo.getDataCenterId());
-            TemplateInfo sourceTemplateInfo = templateDataFactory.getTemplate(srcVolumeInfo.getTemplateId(), sourceTemplateDataStore);
-            TemplateObjectTO sourceTemplate = new TemplateObjectTO(sourceTemplateInfo);
+            if (sourceTemplateDataStore != null) {
```
Comment (shwstppr) [inline engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java]: @rhtyd Throwing an exception or returning null for Image store can fail this. This might not be needing a sec store for writing. Maybe need to handle this separately?

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java [hunk 2]
```diff
@@ -2677,6 +2677,9 @@ private String orchestrateExtractVolume(long volumeId, long zoneId) {
         }
         // perform extraction
         ImageStoreEntity secStore = (ImageStoreEntity)dataStoreMgr.getImageStore(zoneId);
+        if (secStore == null) {
+            throw new InvalidParameterValueException(String.format("Secondary storage to satisfy storage needs cannot be found for zone: %d", zoneId));
+        }
         String value = _configDao.getValue(Config.CopyVolumeWait.toString());
```
Comment (kioie) [inline server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: What about the `VolumeVO uploadVolume` and the `GetUploadParamsResponse uploadVolume` , that also use  `getImageStore` , will you also handle the null returns there?

File: services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java [hunk 3]
```diff
@@ -1118,7 +1118,10 @@ public boolean finalizeVirtualMachineProfile(VirtualMachineProfile profile, Depl
         vm.setDetails(details);
 
         DataStore secStore = _dataStoreMgr.getImageStore(dest.getDataCenter().getId());
-        assert (secStore != null);
+        if (secStore != null) {
```
Comment (kioie) [inline services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java]: `if (secStore == null){`

File: engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java (hunk 1 above)
Comment (kioie) [reply engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java]: Could this be the reason you are using `(sourceTemplateDataStore != null)` ? If so, you might need an else at the end to manage the nulls

Comment (shwstppr) [reply engine/storage/datamotion/src/main/java/org/apache/cloudstack/storage/motion/KvmNonManagedStorageDataMotionStrategy.java]: @kioie It should never be getting null value for image store as it needs the store only for reading and threshold limit shouldn't be affecting this. Will have to make changes for it.

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java (hunk 2 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: Not seeing any reference for getImageStore(Long zoneId) here,
https://github.com/shapeblue/cloudstack/blob/secondary-storage-limit-3287/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L290-L388
`DataStore getImageStore(String storeUuid, Long zoneId)` from `TemplateManager.java` used in these methods already handles null value.

File: services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java (hunk 3 above)
Comment (shwstppr) [reply services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java]: Done

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java (hunk 2 above)
Comment (kioie) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: Yes, you are correct, hadn't seen the `CloudRuntimeException` inside the method.

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java [hunk 4]
```diff
@@ -146,17 +145,30 @@ public ImageStoreEntity getImageStore(String uuid) {
...
+                return imageStores.get(0);
+            }
         }
-        return imageStores.get(0);
+
+        // No store with space found
+        s_logger.error(String.format("Can't find an image storage in zone with less than %d usage",
+                Math.round(_statsCollector.getImageStoreCapacityThreshold()*100)));
+        return null;
     }
```
Comment (kioie) [inline engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java]: Besides checking for whether the store is below the threshold, are you also considering doing a check if the image will fit in the imagestore and what capacity remains afterwards....for example, if the current used capacity is at 89% and the image might move it to even upto 99%....or is that check happening elsewhere?

Comment (shwstppr) [reply engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java]: @kioie I'm not sure that is possible to implement for scenarios at this point with the current design. For example, while registering a template through URL we don't know actual size after download and install.
But such a check can be considered for copy template, snapshots, etc. I've to check the code for that. Anyway, the requirement of this method is to return an image store with capacity within the threshold and I don't think we can have a check for resultant size here.

Comment (kioie) [reply engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/manager/ImageStoreProviderManagerImpl.java]: That's okay, just wanted to know the possibility of it happening

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@shwstppr were the vmware specific fixes also done? You can kick tests now.
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by shwstppr** [comment]
@rhtyd yes I made the changes for vmware migration issue. Would help if you can review last 2 commits

File: engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java [hunk 5]
```diff
@@ -33,7 +33,11 @@
 
     List<DataStore> getImageStoresByScope(ZoneScope scope);
 
-    DataStore getImageStore(long zoneId);
+    DataStore getImageStoreForRead(long zoneId);
+
+    DataStore getImageStoreForWrite(long zoneId);
+
+    List<DataStore> getImageStoresForWrite(long zoneId);
```
Comment (rhtyd) [inline engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java]: Rename it something more meaningful like `listImagesStoresWithFreeCapacity`?

File: engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java [hunk 6]
```diff
@@ -33,7 +33,11 @@
 
     List<DataStore> getImageStoresByScope(ZoneScope scope);
 
-    DataStore getImageStore(long zoneId);
+    DataStore getImageStoreForRead(long zoneId);
+
+    DataStore getImageStoreForWrite(long zoneId);
```
Comment (rhtyd) [inline engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java]: How about getImagesStoresWithFreeCapacity?

File: engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java [hunk 7]
```diff
@@ -33,7 +33,11 @@
 
     List<DataStore> getImageStoresByScope(ZoneScope scope);
 
-    DataStore getImageStore(long zoneId);
+    DataStore getImageStoreForRead(long zoneId);
```
Comment (rhtyd) [inline engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/DataStoreManager.java]: `getRandomImageStore` or something that conveys meaning? You may also put javadocs on them to convey which method does what?

**Comment by shwstppr** [comment]
@rhtyd done the refactoring
@blueorangutan package

**Comment by rhtyd** [comment]
Can you check the build failure @shwstppr  on backend jenkins?

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@rhtyd Not sure why it failed the first time. Logs showed checkstyle errors related to files unrelated to this PR. Packaging seems fine now.

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
Re-kicking Travis

**Comment by rhtyd** [comment]
I've rekicked Travis jobs, please check again in case they fail @shwstppr 
@blueorangutan test matrix

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-55u3

**Comment by shwstppr** [comment]
@borisstoyanov will look into it

> I think I'm hitting an issue with this one. I cannot sync the templates across a newly added image store. Here's my steps:
> 
> Originally created environement with 4 secondary storages
> deleted 3 of them so I just have 1 running.
> On the deleted storages I've clean all files.
> Registered a few templates in cloudstack and they ended up on the running storage
> Added back one of the storages and destroyed the SSVM in a while
> After a day I went back to the machine and the newly added templates were not on the new image store, just the default ones were added. Also the new secondary storage is not being mounted on any of the hosts

**Comment by rhtyd** [comment]
Tests LGTM, any comments @shwstppr @borisstoyanov  ?
@shwstppr can you test/fix Bobby's issue?

**Comment by shwstppr** [comment]
@rhtyd looking into the issue

@blueorangutan package

**Comment by shwstppr** [comment]
> I think I'm hitting an issue with this one. I cannot sync the templates across a newly added image store. Here's my steps:
> 
> Originally created environement with 4 secondary storages
> deleted 3 of them so I just have 1 running.
> On the deleted storages I've clean all files.
> Registered a few templates in cloudstack and they ended up on the running storage
> Added back one of the storages and destroyed the SSVM in a while
> After a day I went back to the machine and the newly added templates were not on the new image store, just the default ones were added. Also the new secondary storage is not being mounted on any of the hosts

@borisstoyanov I've verified, the issue you are facing is unrelated to this PR. Currently, code skips downloading a template to new secondary store if is not public and not featured and not a system template.
https://github.com/apache/cloudstack/blob/master/engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java#L517-L520
If you can repeat your steps while making new template public/fetured(or remove your new stores, edit template to make it public and re-add store) it will be downloaded instantly after storage addition. There is no issue with template sync and it should start as soon as a new storage is added. I fixed that with #3302 
Not sure if it is by design that a normal template(not featured, not public) will remain on a single secondary store for a zone. @rhtyd @nvazquez any thoughts?

**Comment by borisstoyanov** [comment]
Sure, thanks on the investigation @shwstppr, will check

**Comment by rhtyd** [comment]
@borisstoyanov @shwstppr have you tested this simple case:
(a) deploy a VM on a host
(b) add a new secondary storage to a zone, then check that the secondary storage is not mounted on any of the hosts
(c) then migrate that VM to another host, check that the secondary storage is mounted on that host.
