### PR TITLE
ui: fix merge issue that causes VR duplicates

### LINKED ISSUE #3926: VRs listed twice in GUI
Picture worth a thousand words...Current Master version:

image

### PR DESCRIPTION
**Pull request by rhtyd**
This fixes issue from merging 4d8a2da133b74f2de9ecc599eebafdfc68e6fa60
on master/4.14-snapshot which causes duplicate VRs to show up.

Fixes #3926 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
This is UI only change backend smoketests not necessary, manual test/confirmation is asked
@blueorangutan package

File: ui/scripts/system.js [hunk 1]
```diff
@@ -9996,7 +9996,7 @@
                                             }
 
                                             $.ajax({
-                                                url: createURL("listRouters&listAll=true&page=" + args.page + "&pagesize=" + pageSize + array1.join("") + "&projectid=-1"),
+                                                url: createURL("listRouters&page=" + args.page + "&pagesize=" + pageSize + array1.join("") + "&projectid=-1"),
```
Comment (DaanHoogland) [inline ui/scripts/system.js]:
```
listall | If  set to false, list only resources belonging to the command's caller; if  set to true - list resources that the caller is authorized to see.  Default value is false
```
so if the admin calls this and a router would not belong to them... I'll test some scenarios

**Comment by rhtyd** [comment]
@DaanHoogland please merge once you've tested and are satisfied

**Comment by DaanHoogland** [comment]
tested with isolated vpc and shared as user and admin
