### PR TITLE
VMware: match nic mac for ip address fetch

### LINKED ISSUE #7142: GSoC 2023 Idea: Autodetect IPs used inside the VM
With regards to IP info reporting, Cloudstack relies entirely on it's DHCP data bases and so on. When this is not available (L2 networks etc) no IP information is shown for a given VM.

I propose we introduce a mechanism for "IP autodetection" and try to discover the IPs used inside the machines by means of querying the hypervisors. For example with KVM/libvirt we can simply do something like this:

```
root@fedora35 ~]# virsh domifaddr win2k22 --source agent
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 Ethernet   52:54:00:7b:23:6a    ipv4         192.168.0.68/24
 Loopback Pseudo-Interface 1                      ipv6         ::1/128
 -          -                    ipv4         127.0.0.1/8
```

The above command queries the qemu-guest-agent inside the Windows VM. The VM needs to have the qemu-guest-agent installed and running as well as the virtio serial drivers (easily done in this case with [virtio-win-guest-tools.exe](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.215-2/virtio-win-guest-tools.exe) ) as well as a guest-agent socket channel defined in libvirt.

Once we have this information we could display it in the UI/API as "Autodetected VM IPs" or something like that.

I imagine it's very similar for VMWare and XCP-ng.

Thank you

### LINKED ISSUE #10640: Nics for routers or guest networks lose their IP on VM reboot
### problem

I've noticed this issue a while ago and it has been present for at least 2 years since we have Cloudstack in production with VMware as hypervisor backend. Based on the logic I see here this issue should be present with other hypervisors however I did not see an issue with Xcp-ng hypervisor. I may have not tested Xcp well enough though.

Based on the current logic, for external dhcp, Cloudstack tryies to fill in the gaps based on information from the hypervisor vm agent to have as much information for the NICs it is managing however this does not work well in practice especially when there is no external dhcp but only manual IP assignments. 

The issue has two sides to it:
1. VMs that have a NIC created in a shared guest network will "randomly" lose their IPs after a bit of time after a reboot. This is because Cloudstack as I mentioned above, will fetch wrongly the IP from the vm agent which can have one of two side effects. As an example say we have a VM with one NIC in a CS managed VPC network with DHCP, which gives the VM the IP 172.16.0.1, and one NIC in a guest network defined in CS. As an admin, I can configure an IP in Cloudstack for the 2nd NIC however on start/reboot, the external dhcp IP fetcher will attempt to get the IP from the VM guest tools. For VMware the code is getting the default IP which most of the time will be 172.16.0.1 which means we will end up in Cloudstack with two NICs having the same IP. The  2nd NIC will most likely have either "NULL" or 172.16.0.1 with the wrong network subnet.
2. At the same time, I noticed that VPC routers are affected the same way sometimes, where the NIC for the control plane that is managed by ControlNetworkGuru will sometimes lose their IP. I am assuming that the issue is the same one but I am not certain, as I don't know how to reproduce this bug.

I will follow up with a PR but I do believe some discussion is to be had around this whole external dhcp ip fetcher because it looks like it has some conflicts with manual assigning of ips.

### versions

ACS: 4.19.1.0
VMware vSphere 7.0.3

### The steps to reproduce the bug

For normal VM bug:

Create a VPC and a network with DHCP. 
Create a shared guest network with no DHCP.

Create a VM and allocate one nic in VPC network and one nic in shared network. 
Restart the VM and wait 5 minutes (or whatever time period is configured for external dhcp ip fetcher) and you will see that the nic for the shared guest network has the same ip as the dhcp nic.

Example of result:

Image

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by alexandru-bagu**
### Description

This PR fixes #10640

The main solution for the issue here would be to make sure that we are getting the IP for the correct NIC which we can do based on the MAC of the NIC. Additionally, a null IP is also a valid response because a NIC can have no IP assigned.

It's up for discussion whether we should pull any IP even if it does not match the network subnet because the user can in fact use the NIC with another subnet as well, but that is not necessarily relevant to this issue.
 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

I am in the process of testing on my dev environment then going to push in prod once I am happy with the results.

### CODE REVIEW

**Review by weizhouapache — COMMENTED** [review]
overall looks good

A related pr for l2 network #10431

**Comment by weizhouapache** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 1]
```diff
@@ -788,12 +793,6 @@ protected void runInContext() {
                         }
                     }
                 } else {
-                    //previously vm has ip and nic table has ip address. After vm restart or stop/start
```
Comment (alexandru-bagu) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:791]: In my opinion, if we cannot know if the VM still has the IP assigned or not then we should not modify the database. In other words, we should be sure that the VM's NIC does not have an IP assigned before updating the database.

**Comment by alexandru-bagu** [comment]
> overall looks good
> 
> A related pr for l2 network #10431

Interesting. I see your PR has more changes than this PR. Feel free to grab my code for VMware and close this PR.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@alexandru-bagu 
can you rebase with 4.20 branch so it will be included into 4.20.1.0 release ?

**Comment by alexandru-bagu** [comment]
> @alexandru-bagu can you rebase with 4.20 branch so it will be included into 4.20.1.0 release ?

I rebased the changes onto 4.20 and changed merge target branch to 4.20.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> > @alexandru-bagu can you rebase with 4.20 branch so it will be included into 4.20.1.0 release ?
> 
> I rebased the changes onto 4.20 and changed merge target branch to 4.20.

great, thanks @alexandru-bagu 
I will test it next week

**Comment by DaanHoogland** [comment]
@alexandru-bagu , i fixed some conflict eagerly on you PR. I hope you’ll forgive someday soon. Please have a check?

**Comment by alexandru-bagu** [comment]
Daan, #10431 handles kvm. This PR properly handles IPs detected using vmtools for VMware. This bit should be merged either way.

What I leave up for discussion is the case where the `GetVmIpAddressCommand` returns false or true with a null ip. In my opinion, if the command returns false (as in there was an error) the IP should not be released - basically the code I wrote in `server/src/main/java/com/cloud/vm/UserVmManagerImpl.java`.

**Comment by DaanHoogland** [comment]
> Daan, #10431 handles kvm. This PR properly handles IPs detected using vmtools for VMware. This bit should be merged either way.

sorry, I did not read the code well enough :|

> What I leave up for discussion is the case where the `GetVmIpAddressCommand` returns false or true with a null ip. In my opinion, if the command returns false (as in there was an error) the IP should not be released - basically the code I wrote in `server/src/main/java/com/cloud/vm/UserVmManagerImpl.java`.

@weizhouapache , Can you chime in? This is to be resolved before merging!
cc @Pearl1594 , I think this would be good to have if we resolve this question.

**Comment by weizhouapache** [comment]
> > What I leave up for discussion is the case where the `GetVmIpAddressCommand` returns false or true with a null ip. In my opinion, if the command returns false (as in there was an error) the IP should not be released - basically the code I wrote in `server/src/main/java/com/cloud/vm/UserVmManagerImpl.java`.
> 
> @weizhouapache , Can you chime in? This is to be resolved before merging! cc @Pearl1594 , I think this would be good to have if we resolve this question.

@DaanHoogland 
I agree with @alexandru-bagu 
the new logic seems good to me

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by DaanHoogland** [comment]
@blueorangutan test ol8 vmware-80u3

**Comment by alexandru-bagu** [comment]
Reviewing the code I observed that the IP usage was still being decremented even though no action has been done due to an error being returned by the fetcher thread. In case of errors, since we don't actually do anything, we should not make any changes to the current state.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@alexandru-bagu can you please suggest if there any more changes needed for this PR and also please update how this has been tested.

**Comment by alexandru-bagu** [comment]
I don't have any other changes to push to this PR. This has been pushed to our production environment since I created this PR. Not sure what you mean by how this has been tested. It was tested to update the IP information in Cloudstack from external sources where the reporter of the IP information is the vSphere API.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test ol8 vmware80u3

**Comment by DaanHoogland** [comment]
@blueorangutan test ol8 vmware-80u3

**Comment by DaanHoogland** [comment]
tested in production (as per https://github.com/apache/cloudstack/pull/10641#issuecomment-3252269411) , will we trust this and merge @weizhouapache ? 

there are some smoke test error, they may require investigation.

**Comment by DaanHoogland** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan test ol8 vmware-70u3

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 2]
```diff
@@ -5837,11 +5837,19 @@ protected Answer execute(GetVmIpAddressCommand cmd) {
...
-                    if (ip != null) {
-                        result = true;
+                    var normalizedMac = cmd.getMacAddress().replaceAll("-", ":");
+                    for(var guestInfoNic : guestInfo.getNet()) {
+                        var normalizedNicMac = guestInfoNic.getMacAddress().replaceAll("-", ":");
+                        if (!result && normalizedNicMac.equalsIgnoreCase(normalizedMac)) {
+                            result = true;
+                            details = null;
+                            for (var ipAddr : guestInfoNic.getIpAddress()) {
+                                if(NetUtils.isIpWithInCidrRange(ipAddr, cmd.getVmNetworkCidr())) {
```
Comment (weizhouapache) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java]:
```suggestion
                                if (cmd.getVmNetworkCidr() == null || NetUtils.isIpWithInCidrRange(ipAddr, cmd.getVmNetworkCidr())) {
```

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> I don't have any other changes to push to this PR. This has been pushed to our production environment since I created this PR. Not sure what you mean by how this has been tested. It was tested to update the IP information in Cloudstack from external sources where the reporter of the IP information is the vSphere API.

I will test it @DaanHoogland 

added a change for L2 network

**Comment by weizhouapache** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 3]
```diff
@@ -5837,11 +5837,19 @@ protected Answer execute(GetVmIpAddressCommand cmd) {
...
-                    if (ip != null) {
-                        result = true;
+                    var normalizedMac = cmd.getMacAddress().replaceAll("-", ":");
+                    for(var guestInfoNic : guestInfo.getNet()) {
+                        var normalizedNicMac = guestInfoNic.getMacAddress().replaceAll("-", ":");
+                        if (!result && normalizedNicMac.equalsIgnoreCase(normalizedMac)) {
+                            result = true;
+                            details = null;
+                            for (var ipAddr : guestInfoNic.getIpAddress()) {
+                                if (cmd.getVmNetworkCidr() == null || NetUtils.isIpWithInCidrRange(ipAddr, cmd.getVmNetworkCidr())) {
```
Comment (weizhouapache) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java]:
```suggestion
                                if (NetUtils.isValidIp4(ipAddr) && (cmd.getVmNetworkCidr() == null || NetUtils.isIpWithInCidrRange(ipAddr, cmd.getVmNetworkCidr()))) {
```

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test ol8 vmware-80u3

**Comment by weizhouapache** [comment]
verified OK on both
- shared network without services (QuickCloud with no services) and
- L2 networks

tested with ubuntu cloud image
- assigned Ip manually

image

- waited a while
image

- reboot the vm, the assigned IP is gone, the IP field is empty
image

- assigned another IP inside the vm
image

- new IP is fetched
image

**Review by weizhouapache — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 4]
```diff
@@ -778,8 +778,13 @@ protected void runInContext() {
                 Answer answer = _agentMgr.send(hostId, cmd);
                 if (answer.getResult()) {
                     String vmIp = answer.getDetails();
-
-                    if (NetUtils.isValidIp4(vmIp)) {
+                    if (null == vmIp) {
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java]:
```suggestion
                    if (vmIp == null) {
```

File: plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java [hunk 5]
```diff
@@ -5837,11 +5837,19 @@ protected Answer execute(GetVmIpAddressCommand cmd) {
...
+                    for(var guestInfoNic : guestInfo.getNet()) {
+                        var normalizedNicMac = guestInfoNic.getMacAddress().replaceAll("-", ":");
+                        if (!result && normalizedNicMac.equalsIgnoreCase(normalizedMac)) {
+                            result = true;
+                            details = null;
+                            for (var ipAddr : guestInfoNic.getIpAddress()) {
+                                if (NetUtils.isValidIp4(ipAddr) && (cmd.getVmNetworkCidr() == null || NetUtils.isIpWithInCidrRange(ipAddr, cmd.getVmNetworkCidr()))) {
+                                    details = ipAddr;
+                                }
+                            }
```
Comment (vishesh92) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:5850]:
```suggestion
                            }
                            break;
```

Comment (vishesh92) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java:5850]: once the result is set to true, we can break out of the for loop.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test ol8 vmware-80u3
