### PR TITLE
Fix deploy VM from ISOs with UEFI

### LINKED ISSUE #4244: Attach iso failed  for kvm UEFI
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
KVM UEFI
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0
~~~

##### OS / ENVIRONMENT

OS CentOS 7.6
Compiled against library: libvirt 4.5.0
Using library: libvirt 4.5.0
Using API: QEMU 4.5.0
Running hypervisor: QEMU 2.12.0

OVMF-20180508-6.gitee3198e672e2.el7.noarch
##### SUMMARY

When VM is running in UEFI Secure Boot mode, the controller of CDROM is SATA,
But when executing attach iso cmd, IDE controller is used
So unable to complete Attache ISO

Need to be modified to STAT controller
##### STEPS TO REPRODUCE

~~~
1.Deploy VM through template, boot type select UEFI.Boot Mode select SECURE
2.Attach iso to deploy vm
~~~

##### EXPECTED RESULTS

~~~
attache iso  to vm done
~~~

##### ACTUAL RESULTS

~~~
Failed to attach device to i-2-3148-VM: internal error: No device with bus 'ide' and target 'hdc'. cdrom and floppy device hotplug isn't supported by libvirt
~~~

### PR DESCRIPTION
**Pull request by slavkap**
### Description

This PR fixes #4244 
deploying of VMs from ISOs and from templates with UEFI boot type
deploying of VMs from ISOs and from templates with UEFI boot type with
volumes in RAW format

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
manual tests with CentOS8 and Windows ISOs/templates
primary storages - NFS/StorPool

I'll appreciate it if somebody could test this with Ceph and another storage plugin that supports RAW image format

### CODE REVIEW

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 1]
```diff
@@ -3454,6 +3448,8 @@ public boolean isCentosHost() {
             return DiskDef.DiskBus.IDE;
         } else if (platformEmulator.startsWith("Other PV Virtio-SCSI")) {
             return DiskDef.DiskBus.SCSI;
+        } else if (isUefiEnabled && platformEmulator.startsWith("Windows")) {
+            return DiskDef.DiskBus.SATA;
```
Comment (sureshanaparti) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:3452]: Is this only required in case of UEFI secure mode only?

**Comment by sureshanaparti** [comment]
@slavkap Have you tested both UEFI Legacy and Secure modes ?

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 2]
```diff
@@ -2564,16 +2565,9 @@ public int compare(final DiskTO arg0, final DiskTO arg1) {
...
-                        disk.defISODisk(null, devId,isSecureBoot,isWindowsTemplate);
-                    } else {
-                        /* Add iso as placeholder */
-                        disk.defISODisk(null, devId);
-                    }
-                } else {
-                    disk.defISODisk(volPath, devId);
-                }
+
+                disk.defISODisk(volPath, devId, isUefiEnabled);
```
[the remark this answers is not in the document]
Comment (slavkap) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2569]: @sureshanaparti here we check if UEFI is enabled because cdrom disk controller should be SATA for q35 machines

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java (hunk 1 above)
Comment (slavkap) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:3452]: this is required for both secure/legacy UEFI boot type on Windows machines

**Comment by slavkap** [comment]
@sureshanaparti, I have tested both scenarios (UEFI secure/legacy) on CentOS8 and Windows 10 and with RAW/QCOW2 images. But for the RBD storage pool I'm not sure is it going to work

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
In your opinion @slavkap, can we automate those tests in a marvin script, using a smaller linux iso?

**Comment by slavkap** [comment]
Hi @DaanHoogland, what should be the expectations of Marvin's tests? I mean, do they have to do an automated install (probably with a kickstart for CentOS) and check if UEFI is enabled. Or deploy a VM from ISO with UEFI secure/legacy and check that we have access to it through ssh?

**Comment by DaanHoogland** [comment]
> Hi @DaanHoogland, what should be the expectations of Marvin's tests? I mean, do they have to do an automated install (probably with a kickstart for CentOS) and check if UEFI is enabled. Or deploy a VM from ISO with UEFI secure/legacy and check that we have access to it through ssh?

@slavkap, the only expectation is that the verification is automated. This could be with ssh to host or instance, but also with APIs. Both are done a lot in the current set of tests. the problem would probably be with the install from ISO I imagine, but it was a genuine question, You did the testing and probably know best if the manual actions can be automated in python.

**Comment by slavkap** [comment]
@DaanHoogland, I could do the python tests, but the only problem (for me) is the automating of the installation. I should research how and is it possible to automate the installation from ISO. This will take time, and I can't commit how much

**Comment by DaanHoogland** [comment]
> @DaanHoogland, I could do the python tests, but the only problem (for me) is the automating of the installation. I should research how and is it possible to automate the installation from ISO. This will take time, and I can't commit how much

I understand, I think the main issue is that a VM with the ISO would be started (in UEFI mode), no? If we can verify that some prompt for installation is there, the rest of the installation is not sifnificant for this functionality. Or am I missing something?

**Comment by rhtyd** [comment]
@blueorangutan package

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java [hunk 3]
```diff
@@ -725,7 +725,7 @@ private String getDevLabel(int devId, DiskBus bus, boolean forIso) {
             } else if(devId >= 2) {
                 devId += 2;
             }
-            return (DiskBus.SATA == bus) ? "sdb" : "hd" + getDevLabelSuffix(devId);
+            return (DiskBus.SATA == bus) ? "sd" + getDevLabelSuffix(devId) : "hd" + getDevLabelSuffix(devId);
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java:728]:
```suggestion
            return ((DiskBus.SATA == bus) ? "sd" : "hd") + getDevLabelSuffix(devId);
```
also, also, are those prefixes really really usniversal across OSses?

**Review by DaanHoogland — APPROVED** [review]
code looks good

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java (hunk 3 above)
Comment (slavkap) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java:728]: @DaanHoogland actually this is only applied only for SATA disks, and without the change, the problem will appear when we deploy Windows VM from a template with 2 disks.

```
<disk  device='disk' type='file'>
<driver name='qemu' type='qcow2' cache='none' />
<source file='/mnt/46aa22fc-815b-34cd-96fe-fb1f8fea2754/f28ed907-b9e4-46c2-b543-2b34f0140018'/>
<target dev='sda' bus='sata'/>
<serial>f28ed907b9e446c2b543</serial></disk>
<disk  device='disk' type='file'>
<driver name='qemu' type='qcow2' cache='none' />
<source file='/mnt/46aa22fc-815b-34cd-96fe-fb1f8fea2754/bb1c40f8-0867-4197-a1e7-3cef7da7f1e5'/>
<target dev='vdb' bus='virtio'/>
<serial>bb1c40f808674197a1e7</serial></disk>
<disk  device='cdrom' type='file'>
<driver name='qemu' type='raw' />
<source file=''/>
<target dev='sda' bus='sata'/>
</disk>
```
`org.libvirt.LibvirtException: XML error: target 'sda' duplicated for disk sources '/mnt/46aa22fc-815b-34cd-96fe-fb1f8fea2754/f28ed907-b9e4-46c2-b543-2b34f0140018' and '<null>'`

Comment (slavkap) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtVMDef.java:728]: And just saw that the second disk is virtio, and it should be SATA also. I Will add a fix for this, I just need to test it first

**Comment by slavkap** [comment]
@DaanHoogland, sorry for the late response! I tried few things with python on how to access the VM (because with ssh will not happen). Unfortunately, I couldn't find a way to be prompt that UEFI is enabled before or during the installation. The easiest way is to get the VM's dumpxml and check if the machine type is q35 or if the loader is OVMF. What is your opinion about this?

**Comment by DaanHoogland** [comment]
> @DaanHoogland, sorry for the late response! I tried few things with python on how to access the VM (because with ssh will not happen). Unfortunately, I couldn't find a way to be prompt that UEFI is enabled before or during the installation. The easiest way is to get the VM's dumpxml and check if the machine type is q35 or if the loader is OVMF. What is your opinion about this?

I gather you are talking testing; yes this can be done as ssh to the host during verification is easy, there are examples around.

**Comment by slavkap** [comment]
Just to be sure that we are talking about the same thing - are you OK with the tests only to get the dumpxml and verify that UEFI is enabled from there, not to do the installation?

**Comment by DaanHoogland** [comment]
> Just to be sure that we are talking about the same thing - are you OK with the tests only to get the dumpxml and verify that UEFI is enabled from there, not to do the installation?

yes, the purpose of this code is just that is it? there is no assumption that the install actually works and this is out of our hands anyway , *if* i understand correctly.

**Comment by slavkap** [comment]
OK, I'll leave the PR as a draft until I'm ready with the tests. Is the test environment for KVM set to support UEFI?

**Comment by DaanHoogland** [comment]
> OK, I'll leave the PR as a draft until I'm ready with the tests. Is the test environment for KVM set to support UEFI?

I'll have to check. It is a standard centos7 install. If it isn't we will have to update it and rely on your manual tests anyway. You can put it in a separate PR, if you wish.

**Comment by slavkap** [comment]
> I'll have to check. It is a standard centos7 install. If it isn't we will have to update it and rely on your manual tests anyway. You can put it in a separate PR, if you wish.

Yes, it's standard CentOS7 with OVMF installed. I've added in `/etc/cloudstack/agent/uefi.properties` these information:

> guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS.secboot.fd
> guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS.fd
> guest.loader.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
> guest.nvram.path=/var/lib/libvirt/qemu/nvram/
> guest.loader.legacy=/usr/share/OVMF/OVMF_CODE.secboot.fd

and into ` /etc/libvirt/qemu.conf`:

> nvram = [ "/usr/share/OVMF/OVMF_CODE.secboot.fd:/usr/share/OVMF/OVMF_VARS.fd" ]

Also, in the `host_details` table, if it's not a new host, the detail `host.uefi.enable` of the host should be set to true.

I think that it'll be better to add the tests in this PR.

**Comment by rhtyd** [comment]
@slavkap is the PR work in progress? If not can you change the draft PR to 'ready for review'? Thanks.
@blueorangutan package

**Comment by slavkap** [comment]
@rhtyd, I have to do the Marvin tests. That's why I've put it into a draft until I'm ready

**Comment by slavkap** [comment]
@DaanHoogland, may I ask for some help? I've added the element "iso3" to test_data.py, but the UEFI tests failed because it's not in the dictionary. Is Marvin upgraded with the new changes, or did I not put the changes into the right place? I've tested them on my test environment, and it works

**Comment by shwstppr** [comment]
@slavkap Trillian which reported the test results above has its own copy of test_data.py which will need updating.
I've updated the test_data.py there and started a test run from the backend. Let's see how that goes.

**Comment by slavkap** [comment]
Thanks, @shwstppr! Does it also have to be updated and the Marvin base.py file (because there are added few changes either)?

**Comment by shwstppr** [comment]
Marvin base.py file will get auto updated @slavkap

**Comment by slavkap** [comment]
OK! Thanks again, @shwstppr, for your reply and the help!

**Comment by shwstppr** [comment]
@slavkap Looks like Trillian hosts are not having UEFI capability. Do we need to skip UEFI tests in this case?

```
2021-03-26 14:08:42,630 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62 FirstFitRoutingAllocator) (logid:b61c10e9) Looking for hosts in dc: 1  pod:1  cluster:1
2021-03-26 14:08:42,631 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62 FirstFitRoutingAllocator) (logid:b61c10e9) Hosts with tag 'UEFI' are:[]
2021-03-26 14:08:42,631 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62 FirstFitRoutingAllocator) (logid:b61c10e9) FirstFitAllocator has 0 hosts to check for allocation: []
2021-03-26 14:08:42,633 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62 FirstFitRoutingAllocator) (logid:b61c10e9) Found 0 hosts for allocation after prioritization: []
2021-03-26 14:08:42,633 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62 FirstFitRoutingAllocator) (logid:b61c10e9) Looking for speed=256Mhz, Ram=256 MB
2021-03-26 14:08:42,633 DEBUG [c.c.a.m.a.i.FirstFitAllocator] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62 FirstFitRoutingAllocator) (logid:b61c10e9) Host Allocator returning 0 suitable hosts
2021-03-26 14:08:42,633 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62) (logid:b61c10e9) No suitable hosts found
2021-03-26 14:08:42,633 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62) (logid:b61c10e9) No suitable hosts found under this Cluster: 1
2021-03-26 14:08:42,633 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-37:ctx-56e8e114 job-311 ctx-38d5fd62) (logid:b61c10e9) Could not find suitable Deployment Destination for this VM under any clusters, returning.-
```

**Comment by slavkap** [comment]
@shwstppr, you mean to skip the tests if non of the Trillian hosts doesn't have UEFI? Are you planning to set up at least one host to support UEFI? If the answer is no, maybe those tests aren't needed at all.

**Comment by slavkap** [comment]
@shwstppr, just to inform you that I have a zone with 4 hypervisors in my test environment. If I set up only one hypervisor to support UEFI, everything works fine, but when I set up a second one to support it, CloudStack couldn't find a suitable host to deploy the VM. Unfortunately, I didn't have time to research this problem.

**Comment by rhtyd** [comment]
@slavkap can you add checks in the code to skip the test if the host is not UEFI enabled (you can use ssh client to check on the host)?

**Comment by slavkap** [comment]
@rhtyd, isn't it easier to list the hosts and check if one of them has "ueficapability" enabled? I'm not sure when I connect to the host for what to look:
1 - to check that OVMF is installed `rpm -qi OVMF` (this information won't tell us if the agent is set to support UEFI)
2 - to check if `uefi.properties` file exists
3 - or to look for something else

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
Last test run LGTM, can you review and test @sureshanaparti @Spaceman1984

**Review by shwstppr — APPROVED** [review]
Code changes lgtm

File: tools/marvin/marvin/config/test_data.py [hunk 4]
```diff
@@ -928,6 +928,16 @@
         "ostype": "CentOS 5.6 (64-bit)",
         "mode": 'HTTP_DOWNLOAD',
     },
+    "iso3": {
+        "displaytext": "Test ISO 3",
+        "name": "ISO 3",
+        "url": "http://people.apache.org/~tsp/dummy.iso",
```
Comment (rhtyd) [inline tools/marvin/marvin/config/test_data.py:934]: URL is dummy, is there a valid iso url we can use?

**Review by sureshanaparti — APPROVED** [review]
code LGTM, haven't tested. Pls address other comments with respect to tests (to skip the tests on hosts with UEFI disabled).

**Comment by rhtyd** [comment]
@sureshanaparti in the last run as I see the hosts are skipped, don't see those failures. The test code also checks if hosts have uefi enabled.

File: tools/marvin/marvin/config/test_data.py (hunk 4 above)
Comment (slavkap) [reply tools/marvin/marvin/config/test_data.py:934]: @rhtyd, I could add a valid URL, but what is the reason? I've followed the rest of Marvin's test, and no one is using a valid ISO, only dummies

Comment (rhtyd) [reply tools/marvin/marvin/config/test_data.py:934]: @slavkap does your newly added test work with the fix?

Yes, that's a practice we should avoid if/when possible. For running tests with blueorangutan/Trillian, we patch the test_data.py file https://github.com/shapeblue/Trillian/blob/master/Ansible/roles/marvin/templates/test_data.py.j2

So anytime anyone adds invalid data, we manually patch it.

Comment (slavkap) [reply tools/marvin/marvin/config/test_data.py:934]: @rhtyd, I tested it with UEFI enabled/disabled, and the test works as expected, but it only checks the dumpxml of the domain, nothing more (that's why I don't see a reason to add a valid ISO). Do I have to open a PR with the changes of test_data.py to your repo?

Comment (rhtyd) [reply tools/marvin/marvin/config/test_data.py:934]: Ah okay so the invalid ISO doesn't make any difference. No need since by default Trillian env don't have UEFI enabled hosts, the tests will be skipped. I'll merge the PR based on your remark.
