### PR TITLE
engine: honour bypass VLAN id/range for L2 networks

### LINKED ISSUE #4273: Multiple L2 networks with same VLAN cannot be created even with Bypass VLAN id/range overlap checked
Till 4.13 ACS allowed creating multiple L2 networks with the same VLAN ID when Bypass VLAN id/range overlap is checked in the UI. But this behaviour is changed with 4.14 which throws an error,
Screenshot from 2020-08-19 12-47-02

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
L2 networks
~~~

##### CLOUDSTACK VERSION

~~~
4.14 and above
~~~

##### CONFIGURATION

Advanced networking

##### OS / ENVIRONMENT

KVM, CentOS7 but doesn't seem to be hypervisor, OS specific

##### STEPS TO REPRODUCE

~~~
1. Create a L2 network with some VLAN ID, say 100, while Bypass VLAN id/range overlap option checked. Network will be created successfully
2. Create another L2 network with same VLAN ID with Bypass VLAN id/range overlap option checked. Network will fail to create with error.
~~~

##### EXPECTED RESULTS

~~~
Second network succesfully created with same VLAN ID as Bypass VLAN id/range overlap option was checked
~~~

##### ACTUAL RESULTS

~~~
Server returns error with message - Network with vlan 100 already exists or overlaps with other network vlans in zone 1
~~~

Issue is seen with both UI and cmk

### PR DESCRIPTION
**Pull request by rhtyd**
Commit e894238d904a9c49c1140371f612a51d251efc1 (#3899) allowed private
gateways to bypass vlan check while refactoring it did not cover the
case for L2 but only shared network. This fix will re-enable honouring
the bypass vlan check option for L2 guest network (in addition to the
Shared networks).

Fixes #4273

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by wido — APPROVED** [review]
LGTM

File: engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java [hunk 1]
```diff
@@ -2529,7 +2529,7 @@ public Network doInTransaction(final TransactionStatus status) {
    * @param ntwkOff network offering
    */
   private boolean hasGuestBypassVlanOverlapCheck(final boolean bypassVlanOverlapCheck, final NetworkOfferingVO ntwkOff, final boolean isPrivateNetwork) {
-    return bypassVlanOverlapCheck && (ntwkOff.getGuestType() == GuestType.Shared || isPrivateNetwork);
+    return bypassVlanOverlapCheck && (ntwkOff.getGuestType() == GuestType.Shared || ntwkOff.getGuestType() == GuestType.L2 || isPrivateNetwork);
```
Comment (DaanHoogland) [inline engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2532]: the condition is getting more complex this way. would
```suggestion
    return bypassVlanOverlapCheck && (ntwkOff.getGuestType() != GuestType.Isolated || isPrivateNetwork);
```
be a good alternative?

**Review by DaanHoogland — APPROVED** [review]
lgtm, pending testing

File: engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java (hunk 1 above)
Comment (rhtyd) [reply engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2532]: Yes that works as well

**Comment by rhtyd** [comment]
@DaanHoogland thnx, addressed fix
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@Spaceman1984 can you review and test this, thnx

**Comment by Spaceman1984** [comment]
Tested, LGTM

**Review by davidjumani — APPROVED** [review]
Code LGTM
