### PR TITLE
Restore VMware VM naming convention option

### LINKED ISSUE #4206: Behavior of vm.instancename.flag not as expected/documented
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware plugin
~~~

##### CLOUDSTACK VERSION

~~~
4.13.0
~~~

##### CONFIGURATION

~~~
vCenter-Version: 6.7.0, 15976728
vSphere-Version: ESXi, 6.7.0, 10302608

`vm.instancename.flag` = `true`
~~~

##### SUMMARY

Behavior of global parameter `vm.instancename.flag` has been changed with 51ee90074d5b53be261dcc746e4bd8a1058dfb6a and therefore does not work as expected by documentation http://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines.html#id2

##### STEPS TO REPRODUCE

~~~
- set `vm.instancename.flag` to `true`
- reboot management instance
- create new instance via WebUI on VMware powered zone with provided "Name (Optional) = dummy-03"
~~~

##### EXPECTED RESULTS

~~~
Name on vCenter = i-<user_id>-<vm_id>-displayName
Internal Name = i-<user_id>-<vm_id>-displayName
~~~

##### ACTUAL RESULTS

~~~
Name on vCenter = dummy-03
Internal Name = i-9-140-VM
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

This PR is a bug fix, to restore the behaviour as per the original intent and the documentation. Documented behaviour https://github.com/apache/cloudstack-documentation/pull/177

Fixes #4206 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

UI and cmk

**Case 1: vm.instancename.flag=true, display name is passed:**
```
> list configurations name=vm.instancename.flag
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "If set to true, will set guest VM's name as it appears on the hypervisor, to its hostname. The flag is supported for VMware hypervisor only",
      "isdynamic": false,
      "name": "vm.instancename.flag",
      "value": "true"
    }
  ],
  "count": 1
}


> deploy virtualmachine zoneid=94e87940-a0ac-42a3-90d1-91fef41a3f56 templateid=dddb9c0e-5b0a-11eb-aad0-1e000d013b27 serviceofferingid=a53b72ee-b5e7-411c-883b-9ffd4b75b8d4 name=case1
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2021-01-28T06:56:47+0000",
    "details": {
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "case1",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "ddd6f66d-5b0a-11eb-aad0-1e000d013b27",
    "guestosid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "haenable": false,
    "hostid": "7c6757ba-d295-4f15-a016-4abfb55552d3",
    "hostname": "10.10.3.161",
    "hypervisor": "VMware",
    "id": "85b75e3c-e877-44f6-9239-a58df813f45a",
    "instancename": "i-2-33-case1",
    "isdynamicallyscalable": false,
    "jobid": "336ec4ea-1a68-4e19-b321-26d2ca50e16f",
    "jobstatus": 0,
    "memory": 512,
    "name": "case1",
    "nic": [
      {
        "broadcasturi": "vlan://1499",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "452868db-8965-4159-ab59-f8455423fbd8",
        "ipaddress": "10.1.1.211",
        "isdefault": true,
        "isolationuri": "vlan://1499",
        "macaddress": "02:00:40:58:00:07",
        "netmask": "255.255.255.0",
        "networkid": "f4b9e712-9b6e-44ae-bb29-c291bc3c41d2",
        "networkname": "t1-network",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "a53b72ee-b5e7-411c-883b-9ffd4b75b8d4",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "dddb9c0e-5b0a-11eb-aad0-1e000d013b27",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "f408e03e-5b0a-11eb-aad0-1e000d013b27",
    "username": "admin",
    "zoneid": "94e87940-a0ac-42a3-90d1-91fef41a3f56",
    "zonename": "pr4581-t3398-vmware-65u2"
  }
}

```
case1-1
case1-2

**Case 2: vm.instancename.flag=true, display name is not passed:**
```
> list configurations name=vm.instancename.flag
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "If set to true, will set guest VM's name as it appears on the hypervisor, to its hostname. The flag is supported for VMware hypervisor only",
      "isdynamic": false,
      "name": "vm.instancename.flag",
      "value": "true"
    }
  ],
  "count": 1
}

> list configurations name=instance.name
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "Name of the deployment instance.",
      "isdynamic": false,
      "name": "instance.name",
      "value": "VM"
    }
  ],
  "count": 1
}

> deploy virtualmachine zoneid=94e87940-a0ac-42a3-90d1-91fef41a3f56 templateid=dddb9c0e-5b0a-11eb-aad0-1e000d013b27 serviceofferingid=a53b72ee-b5e7-411c-883b-9ffd4b75b8d4
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2021-01-28T06:58:00+0000",
    "details": {
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "VM-33f7e2cc-37b5-415f-83c4-f1ddd684b83e",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "ddd6f66d-5b0a-11eb-aad0-1e000d013b27",
    "guestosid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "haenable": false,
    "hostid": "ad66b51e-1aa7-45f8-a065-4542afa9a8a5",
    "hostname": "10.10.3.129",
    "hypervisor": "VMware",
    "id": "33f7e2cc-37b5-415f-83c4-f1ddd684b83e",
    "instancename": "i-2-34-VM",
    "isdynamicallyscalable": false,
    "jobid": "d6c8a4fc-b6ff-4355-b793-cdc4272bf8b6",
    "jobstatus": 0,
    "memory": 512,
    "name": "VM-33f7e2cc-37b5-415f-83c4-f1ddd684b83e",
    "nic": [
      {
        "broadcasturi": "vlan://1499",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "1defd648-da89-4a5d-9b7a-cfb6e9d9887a",
        "ipaddress": "10.1.1.119",
        "isdefault": true,
        "isolationuri": "vlan://1499",
        "macaddress": "02:00:6f:8c:00:08",
        "netmask": "255.255.255.0",
        "networkid": "f4b9e712-9b6e-44ae-bb29-c291bc3c41d2",
        "networkname": "t1-network",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "a53b72ee-b5e7-411c-883b-9ffd4b75b8d4",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "dddb9c0e-5b0a-11eb-aad0-1e000d013b27",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "f408e03e-5b0a-11eb-aad0-1e000d013b27",
    "username": "admin",
    "zoneid": "94e87940-a0ac-42a3-90d1-91fef41a3f56",
    "zonename": "pr4581-t3398-vmware-65u2"
  }
}

```
case2-1
case2-2

**Case 3: vm.instancename.flag=false and display name is passed**
```
> list configurations name=vm.instancename.flag
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "If set to true, will set guest VM's name as it appears on the hypervisor, to its hostname. The flag is supported for VMware hypervisor only",
      "isdynamic": false,
      "name": "vm.instancename.flag",
      "value": "false"
    }
  ],
  "count": 1
}

> deploy virtualmachine zoneid=94e87940-a0ac-42a3-90d1-91fef41a3f56 templateid=dddb9c0e-5b0a-11eb-aad0-1e000d013b27 serviceofferingid=a53b72ee-b5e7-411c-883b-9ffd4b75b8d4 name=case3
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2021-01-28T06:39:37+0000",
    "details": {
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "case3",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "ddd6f66d-5b0a-11eb-aad0-1e000d013b27",
    "guestosid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "haenable": false,
    "hostid": "ad66b51e-1aa7-45f8-a065-4542afa9a8a5",
    "hostname": "10.10.3.129",
    "hypervisor": "VMware",
    "id": "88598ec0-d3c9-47d7-bca6-f5c345397b95",
    "instancename": "i-2-31-VM",
    "isdynamicallyscalable": false,
    "jobid": "4ed837fb-8529-487e-a54f-dffa772383df",
    "jobstatus": 0,
    "memory": 512,
    "name": "case3",
    "nic": [
      {
        "broadcasturi": "vlan://1499",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "bc9fadd1-8b3c-419a-82a2-ee66f05a4bd3",
        "ipaddress": "10.1.1.155",
        "isdefault": true,
        "isolationuri": "vlan://1499",
        "macaddress": "02:00:1f:38:00:05",
        "netmask": "255.255.255.0",
        "networkid": "f4b9e712-9b6e-44ae-bb29-c291bc3c41d2",
        "networkname": "t1-network",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "a53b72ee-b5e7-411c-883b-9ffd4b75b8d4",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "dddb9c0e-5b0a-11eb-aad0-1e000d013b27",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "f408e03e-5b0a-11eb-aad0-1e000d013b27",
    "username": "admin",
    "zoneid": "94e87940-a0ac-42a3-90d1-91fef41a3f56",
    "zonename": "pr4581-t3398-vmware-65u2"
  }
}
```
case3-1
case3-2

**Case 4: vm.instancename.flag=false and display name is not passed**
```
> list configurations name=vm.instancename.flag
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "If set to true, will set guest VM's name as it appears on the hypervisor, to its hostname. The flag is supported for VMware hypervisor only",
      "isdynamic": false,
      "name": "vm.instancename.flag",
      "value": "false"
    }
  ],
  "count": 1
}

> deploy virtualmachine zoneid=94e87940-a0ac-42a3-90d1-91fef41a3f56 templateid=dddb9c0e-5b0a-11eb-aad0-1e000d013b27 serviceofferingid=a53b72ee-b5e7-411c-883b-9ffd4b75b8d4
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2021-01-28T06:45:23+0000",
    "details": {
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "VM-52719267-f3d0-4dcd-b4ba-4a94b123a734",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "ddd6f66d-5b0a-11eb-aad0-1e000d013b27",
    "guestosid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "haenable": false,
    "hostid": "7c6757ba-d295-4f15-a016-4abfb55552d3",
    "hostname": "10.10.3.161",
    "hypervisor": "VMware",
    "id": "52719267-f3d0-4dcd-b4ba-4a94b123a734",
    "instancename": "i-2-32-VM",
    "isdynamicallyscalable": false,
    "jobid": "f30fb72f-6935-4000-9399-ab6b6d6c5170",
    "jobstatus": 0,
    "memory": 512,
    "name": "VM-52719267-f3d0-4dcd-b4ba-4a94b123a734",
    "nic": [
      {
        "broadcasturi": "vlan://1499",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "48913683-80d1-4b6a-ba6e-9b7a541f0e55",
        "ipaddress": "10.1.1.51",
        "isdefault": true,
        "isolationuri": "vlan://1499",
        "macaddress": "02:00:4b:a3:00:06",
        "netmask": "255.255.255.0",
        "networkid": "f4b9e712-9b6e-44ae-bb29-c291bc3c41d2",
        "networkname": "t1-network",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "dde07c5e-5b0a-11eb-aad0-1e000d013b27",
    "passwordenabled": false,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "serviceofferingid": "a53b72ee-b5e7-411c-883b-9ffd4b75b8d4",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "dddb9c0e-5b0a-11eb-aad0-1e000d013b27",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "f408e03e-5b0a-11eb-aad0-1e000d013b27",
    "username": "admin",
    "zoneid": "94e87940-a0ac-42a3-90d1-91fef41a3f56",
    "zonename": "pr4581-t3398-vmware-65u2"
  }
}

```
case4-1
case4-2

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
Re-ran test_vpc_redundant.py manually,
```

Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network and check default routes ... === TestName: test_02_redundant_VPC_default_routes | Status : SUCCESS ===
ok
Create a redundant VPC with two networks with two VMs in each network ... === TestName: test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | Status : SUCCESS ===
ok
Create a redundant VPC with 1 Tier, 1 VM, 1 ACL, 1 PF and test Network GC Nics ... === TestName: test_04_rvpc_network_garbage_collector_nics | Status : SUCCESS ===
ok
Create a redundant VPC with multiple tiers ... === TestName: test_05_rvpc_multi_tiers | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 5 tests in 5902.009s

OK
```

**Review by rhtyd — APPROVED** [review]
LGTM - needs thorough testing

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 1]
```diff
@@ -3844,7 +3848,10 @@ private UserVm createVirtualMachine(DataCenter zone, ServiceOffering serviceOffe
             // Check is hostName is RFC compliant
             checkNameForRFCCompliance(hostName);
         }
-        instanceName = VirtualMachineName.getVmName(id, owner.getId(), _instance);
+        instanceName = VirtualMachineName.getVmName(id, owner.getId(), instanceSuffix);
```
Comment (harikrishna-patnala) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3851]: here `instanceName` variable is used to set name on hypervisor but the same variable is used later for internal name.
`instanceSuffix` is assigned based on displayName (not considering instanceNameFlag), does this effect the case where flag is false and displayName is provided ? 
In that case internal-name should be `i - <user_id> - <vm_id> -<instance.name>` but here we are assigning `i - <user_id> - <vm_id> -<hostName>`.

Comment (shwstppr) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3851]: @harikrishna-patnala default value of `instanceSuffix` is `_instance` (which should get instance.name). Only in case of VMware and instanceFlag it is set to hostname at ln 3832.
Therefore, only when instanceFlag and other conditions are satisfied `instanceName` will be `i - <user_id> - <vm_id> -<hostName>` and will be later set to hypervisor

Comment (harikrishna-patnala) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3851]: Thanks @shwstppr I missed the check at 3823

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 2]
```diff
@@ -4072,7 +4079,11 @@ public UserVmVO doInTransaction(TransactionStatus status) throws InsufficientCap
 
                 persistVMDeployAsIsProperties(vm, userVmOVFPropertiesMap);
 
-                _vmDao.saveDetails(vm);
+                List<String> hiddenDetails = new ArrayList<>();
```
Comment (harikrishna-patnala) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:4082]: @shwstppr I think we can use a single line something like below to add display value.
        `super.addDetail(new UserVmDetailVO(resourceId, key, value, display))`

Comment (shwstppr) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:4082]: @harikrishna-patnala using addDetail method directly here still won't make it single line as detail that will be added needs to be removed from vm.details,

```
if (customParameters.containsKey(VmDetailConstants.NAME_ON_HYPERVISOR)) {
    userVmDetailsDao.addDetail(vm.getId(), VmDetailConstants.NAME_ON_HYPERVISOR, customParameters.get(VmDetailConstants.NAME_ON_HYPERVISOR), false);
    customParameters.remove(VmDetailConstants.NAME_ON_HYPERVISOR);
}
```
Current code may allow setting display=false for multiple details in future

**Review by harikrishna-patnala — APPROVED** [review]
Looks good to me, with code changes and test results.

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by vladimirpetrov** [comment]
@blueorangutan test matrix

**Comment by vladimirpetrov** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package
