### PR TITLE
server: allow migration of vm with snapshots for vmware

### LINKED ISSUE #9061: Unable to live migrate VMware VMs with snapshot
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Core
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### OS / ENVIRONMENT

vSphere 7.0

##### SUMMARY

If I try to live migrate a VM with storage and the VM has a snapshot, the live migration does not start with the following error:

DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-47:ctx-e8daf7c5 job-50058) (logid:28b2b6fb) Complete async job-5
0058, jobStatus: FAILED, resultCode: 431, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"431","erro
rtext":"VM with VM Snapshots cannot be migrated with storage, please remove all VM snapshots"}

##### STEPS TO REPRODUCE

~~~
In a VMware cluster, try to live migrate with storage a VM with at lease an active snapshot
~~~

##### EXPECTED RESULTS

~~~
The VM is correctly migrated

Live storage migration with VM with snapshot is supported in vSphere from version 5.0 so I guess it should be possible to perform the operation --> https://knowledge.broadcom.com/external/article?legacyId=1035550

~~~

##### ACTUAL RESULTS

~~~
You receive an error before the migration start.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9061

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 1]
```diff
@@ -682,6 +682,9 @@ public void setKubernetesServiceHelpers(final List<KubernetesServiceHelper> kube
             HypervisorType.XenServer,
             HypervisorType.Simulator
     ));
+    public static final List<HypervisorType> VM_STORAGE_MIGRATION_WITH_SUPPORTING_SUPPORTING_HYPERVISORS = new ArrayList<>(Arrays.asList(
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:685]: the name is a bit confusing

Comment (shwstppr) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:685]:
```suggestion
    public static final List<HypervisorType> VM_STORAGE_MIGRATION_WITH_SNAPSHOTS_SUPPORTING_HYPERVISORS = new ArrayList<>(Arrays.asList(
```

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 2]
```diff
@@ -7229,7 +7232,8 @@ public VirtualMachine migrateVirtualMachineWithVolume(Long vmId, Host destinatio
             throw new InvalidParameterValueException(String.format("Unsupported hypervisor: %s for VM migration, we support XenServer/VMware/KVM only", vm.getHypervisorType()));
         }
 
-        if (_vmSnapshotDao.findByVm(vmId).size() > 0) {
+        if (!VM_STORAGE_MIGRATION_WITH_SUPPORTING_SUPPORTING_HYPERVISORS.contains(vm.getHypervisorType()) &&
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:7235]:
```suggestion
        if (!VM_STORAGE_MIGRATION_WITH_SNAPSHOTS_SUPPORTING_HYPERVISORS.contains(vm.getHypervisorType()) &&
```

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java (hunk 1 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java]: Thanks @weizhouapache. Too many `SUPPORTING`. Fixed now

**Review by weizhouapache — APPROVED** [review]
code lgtm

not tested yet

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test ol8 vmware-70u3

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by shwstppr** [comment]
@blueorangutan test ol8 vmware-70u3

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test all

**Comment by DaanHoogland** [comment]
> @blueorangutan test all

??
matrix?

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

**Comment by Pearl1594** [comment]
@blueorangutan help

**Comment by Pearl1594** [comment]
@blueorangutan ol8 vmware-70u3

**Comment by Pearl1594** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by Pearl1594** [comment]
@blueorangutan test ol8 vmware-70u3

**Review by Pearl1594 — APPROVED** [review]
clgtm

**Comment by rosi-shapeblue** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by rosi-shapeblue** [comment]
@blueorangutan test ol8 vmware-70u3 keepEnv

**Comment by rosi-shapeblue** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by rosi-shapeblue** [comment]
@blueorangutan test ol8 vmware-70u3 keepEnv

**Comment by rosi-shapeblue** [comment]
@DaanHoogland looks like the build is failing here

**Comment by shwstppr** [comment]
@rosi-shapeblue I guess the build failure was environmental as we've had smoke tests running previously, https://github.com/apache/cloudstack/pull/9305#issuecomment-2741964682. Lets re-package and retry

@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Comment by rohityadavcloud** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test ol8 vmware-70u3

**Comment by DaanHoogland** [comment]
@blueorangutan test ol9 vmware-80u3

**Comment by weizhouapache** [comment]
Tested OK
- deploy vm
- create vm snapshot
- try to migrate vm with volumes (to another pool)

prior to this change

image


after this change: it worked
