### PR TITLE
Fix VM import & VM delete with custom offering

### LINKED ISSUE #8785: Unable to import qcow2 image present on shared/local to a custom offering
ISSUE TYPE

BUG 

Component Name

Import, kvm 

CLOUDSTACK VERSION

Cloudstack version 4.19 

SUMMARY

Unable to import qcow2 image present on shared/local to a custom offering

Steps to reproduce the issue

1. Create a custom service offering

custom-offering

2. Have a qcow2 file present in the shared storage/localstorage 

3. Navigate to tools> Import > kvm > 

Screenshot 2024-03-14 at 10 20 16 AM

Screenshot 2024-03-13 at 1 58 56 PM

4. Exception 

Screenshot 2024-03-13 at 1 59 06 PM

Logs
----

```

2024-03-12 13:50:12,144 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-87:ctx-cd9f62c7 job-409803) (logid:273d199c) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.ImportVmCmd
java.lang.NumberFormatException: For input string: "null"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.cloud.vm.UserVmManagerImpl.commitUserVm(UserVmManagerImpl.java:4524)
	at com.cloud.vm.UserVmManagerImpl.importVM(UserVmManagerImpl.java:8230)


```

Actual Behaviour

The qcow2 file is not getting imported successfully with a custom offering

Expected Behaviour

The qcow2 file should get imported successfully with a custom offering

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes #8785.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

File: server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java [hunk 1]
```diff
@@ -2252,7 +2255,7 @@ private UserVm importKvmVirtualMachineFromDisk(final ImportSource importSource,
         UserVm userVm = null;
 
         Map<String, String> allDetails = new HashMap<>(details);
-        if (serviceOffering.isDynamic()) {
+        if (!serviceOffering.isDynamic()) {
             allDetails.put(VmDetailConstants.CPU_NUMBER, String.valueOf(serviceOffering.getCpu()));
```
Comment (sureshanaparti) [inline server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:2259]: these are set for custom offering?

**Review by sureshanaparti — APPROVED** [review]
minor question on dynamic offering, overall code lgtm

File: server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java (hunk 1 above)
Comment (vishesh92) [reply server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:2259]: Yes. service offering's cpu & memory is null for custom offerings. And value from details needs to be used to override the values for the service offering.

Comment (weizhouapache) [reply server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:2259]: are these details needed for dynamic offering, or non-dynamic offering ?

Comment (vishesh92) [reply server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:2259]: This needs to be updated only for non-dynamic service offering. Because CPU & memory is not set in details for those cases.

 For a dynamic offering, this is already set in `details` from the user input.

Comment (weizhouapache) [reply server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:2259]: @vishesh92 
it is different from what I thought: if service offering is not dynamic, the CPU and Memory are fixed and no need to add record to user_vm_details for them.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

File: server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java [hunk 2]
```diff
@@ -2189,6 +2185,8 @@ private UserVm importExternalKvmVirtualMachine(final UnmanagedInstanceTO unmanag
         }
 
         final VirtualMachineProfile profile = new VirtualMachineProfileImpl(userVm, template, serviceOffering, owner, null);
+        ServiceOfferingVO dummyOffering = serviceOfferingDao.findByIdIncludingRemoved(userVm.getId(), serviceOffering.getId());
```
Comment (vishesh92) [inline server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java:2188]: Use `findById` instead.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
> Packaging result [SF]: ✖️ el7 ✖️ el8 ✖️ el9 ✖️ debian ✖️ suse15. SL-JID 9050

Unit tests are failing. Fixing.

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by kiranchavala — APPROVED** [review]
LGTM, tested manually able to import to a custom offering 

Screenshot 2024-04-10 at 10 06 15 AM
Screenshot 2024-04-10 at 10 07 13 AM
