### PR TITLE
Fixed list networks in projects after setting network permissions

### LINKED ISSUE #6544: Guest network permissions not working with projects
When networks are shared with projects, in the project view (both UI and API) those networks aren't listed and therefore couldn't be used to deploy VM.

The feature isn't working as per https://docs.cloudstack.apache.org/en/4.17.0.0/adminguide/networking_and_traffic.html#guest-network-permissions

Please test and add support for allowing sharing of following types of networks with other accounts and projects:

- L2 networks not in Project
- Isolated networks not in Project
- Shared networks with scope is Account

Please add basic smoketests for this, both as admin and normal user accounts; across accounts and projects (where both the admin and normal user is an owner).

##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
API, Networks
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0
~~~

##### STEPS TO REPRODUCE

~~~

- creating a network "Net1", using offering "DefaultIsolatedNetworkOfferingWithSourceNatService"

- creating a project "Proj1"

- add permissions for network "Net1" to project "Proj1"

- switch to project "Proj1"

- (hit refresh/F5 as workaround for the empty resource list bug)

- list networks (empty)

- create a new instance, but networks is still empty

~~~

##### EXPECTED RESULTS

~~~
Networks should list the network permitted to the project (in project view and API)
~~~

##### ACTUAL RESULTS

~~~
The network wasn't list in the API or UI (even with the projectid=-1 param in API)
~~~

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes #6544 where it could not list networks in a project even after network permissions are set.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Created multiple networks N1, N2
2. Created a project P1
3. Created a user U1
4. Under network permissions in N1, added the project P1
5. Under network permissions in N2, added the user account U1
6. When switched to project view P1, I see only network N1
7. When logged in as U1, I see only N2

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@bluorangutan package

**Review by sureshanaparti — APPROVED** [review]
code LGTM, needs testing.

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java [hunk 1]
```diff
@@ -2035,23 +2035,23 @@ public Pair<List<? extends Network>, Integer> searchForNetworks(ListNetworksCmd
                 if (Arrays.asList(Network.NetworkFilter.Domain, Network.NetworkFilter.AccountDomain, Network.NetworkFilter.All).contains(networkFilter)) {
                     //add domain specific networks of domain + parent domains
                     networksToReturn.addAll(listDomainSpecificNetworksByDomainPath(buildNetworkSearchCriteria(sb, keyword, id, isSystem, zoneId, guestIpType, trafficType, physicalNetworkId, networkOfferingId,
-                            aclType, skipProjectNetworks, restartRequired, specifyIpRanges, vpcId, tags, display, vlanId, associatedNetworkId), searchFilter, path, isRecursive));
+                            aclType, true, restartRequired, specifyIpRanges, vpcId, tags, display, vlanId, associatedNetworkId), searchFilter, path, isRecursive));
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/network/NetworkServiceImpl.java:2038]: @weizhouapache is it ok to skip the project networks in all these cases? can you check and confirm when the project networks can be skipped.

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

File: test/integration/component/test_network_permissions.py [hunk 2]
```diff
@@ -758,3 +758,24 @@ def test_04_deploy_vm_for_other_user_and_test_vm_operations(self):
...
+        self.create_network_permission(self.apiclient, self.user_network, self.domain_admin, self.project, expected=True)
+        self.list_network(self.apiclient, self.domain_admin, self.user_network, self.project, None, expected=True)
+
+        self.remove_network_permission(self.apiclient, self.user_network, self.domain_admin, self.project, expected=True)
+        self.list_network(self.apiclient, self.domain_admin, self.user_network, self.project, None, expected=False)
+
+    @attr(tags=["advanced"], required_hardware="false")
+    def test_06_list_networks_under_account(self):
+        """ Testing list networks under an account """
+        self.create_network_permission(self.apiclient, self.user_network, self.domain_admin, None, expected=True)
```
Comment (weizhouapache) [inline test/integration/component/test_network_permissions.py:774]: @harikrishna-patnala 
would it be good to create network permission to `otheruser` (not `domain_admin`) as well ?

**Review by rohityadavcloud — APPROVED** [review]

File: test/integration/component/test_network_permissions.py [hunk 3]
```diff
@@ -758,3 +758,24 @@ def test_04_deploy_vm_for_other_user_and_test_vm_operations(self):
         command = """self.reset_network_permission({apiclient}, self.user_network, expected=True)"""
         self.exec_command("self.otheruser_apiclient", command, expected=False)
         self.exec_command("self.user_apiclient", command, expected=True)
+
+    @attr(tags=["advanced"], required_hardware="false")
+    def test_05_list_networks_under_project(self):
```
Comment (rohityadavcloud) [inline test/integration/component/test_network_permissions.py:763]: - is this test run against simulator (check travis yml)
- if not, can we move some sort of quick validation tests to smoke/

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java [hunk 4]
```diff
@@ -2035,23 +2035,23 @@ public Pair<List<? extends Network>, Integer> searchForNetworks(ListNetworksCmd
...
                     //add networks of subdomains
                     if (domainId == null) {
                         networksToReturn.addAll(listDomainLevelNetworks(buildNetworkSearchCriteria(sb, keyword, id, isSystem, zoneId, guestIpType, trafficType, physicalNetworkId, networkOfferingId,
-                                aclType, true, restartRequired, specifyIpRanges, vpcId, tags, display, vlanId, associatedNetworkId), searchFilter, caller.getDomainId(), true));
+                            aclType, true, restartRequired, specifyIpRanges, vpcId, tags, display, vlanId, associatedNetworkId), searchFilter, caller.getDomainId(), true));
```
[the remark this answers is not in the document]
Comment (sureshanaparti) [reply server/src/main/java/com/cloud/network/NetworkServiceImpl.java:2042]: yes, seems indentation

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java (hunk 1 above)
Comment (sureshanaparti) [reply server/src/main/java/com/cloud/network/NetworkServiceImpl.java:2038]: thanks for confirming it @weizhouapache

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (harikrishna-patnala) [reply server/src/main/java/com/cloud/network/NetworkServiceImpl.java:2042]: yes, its just indentation.

File: test/integration/component/test_network_permissions.py (hunk 3 above)
Comment (harikrishna-patnala) [reply test/integration/component/test_network_permissions.py:763]: Moved this to smoke tests, I see some tests require hardware.

File: test/integration/component/test_network_permissions.py (hunk 2 above)
Comment (harikrishna-patnala) [reply test/integration/component/test_network_permissions.py:774]: added few more checks in the same test case @weizhouapache

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
Appears like build failures @harikrishna-patnala

**Comment by harikrishna-patnala** [comment]
> Appears like build failures @harikrishna-patnala

Failing at some unknown place to this PR 
[ERROR] /jenkins/workspace/acs-centos8-pkg-builder/dist/rpmbuild/BUILD/cloudstack-4.17.1.0-SNAPSHOT/plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolHelper.java:[188,21] error: cannot find symbol
[ERROR]   symbol:   method setConversionPattern(String)

Rebased the PR and running the package again

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@harikrishna-patnala can you look at the travis failrue ?
```
2022-07-20 12:46:53,365 - CRITICAL - EXCEPTION: Failure:: ['Traceback (most recent call last):\n', '  File "/opt/pyenv/versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor\n    yield\n', '  File "/opt/pyenv/versions/3.6/lib/python3.6/unittest/case.py", line 605, in run\n    testMethod()\n', '  File "/home/travis/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest\n    raise self.exc_val.with_traceback(self.tb)\n', '  File "/home/travis/.local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName\n    addr.filename, addr.module)\n', '  File "/home/travis/.local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath\n    return self.importFromDir(dir_path, fqname)\n', '  File "/home/travis/.local/lib/python3.6/site-packages/nose/importer.py", line 79, in importFromDir\n    fh, filename, desc = find_module(part, path)\n', '  File "/opt/pyenv/versions/3.6/lib/python3.6/imp.py", line 297, in find_module\n    raise ImportError(_ERR_MSG.format(name), name=name)\n', "ImportError: No module named 'test_network_permissions'\n"]
```

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
Test using cmk

As user *ACSUser* create a project and create a network outside this project

```
(sblab) 🐕 > create project name=shareproject displaytext=shareproject
{
  "project": {
    "cpuavailable": "40",
    "cpulimit": "40",
    "cputotal": 0,
    "created": "2022-07-27T08:15:58+0000",
    "displaytext": "shareproject",
    "domain": "ROOT",
    "domainid": "2e8b5f3a-f71a-11ec-87b5-1e0057000461",
    "id": "1ad3e648-c9d2-4b7f-b87a-2a713477762e",
    "ipavailable": "18",
    "iplimit": "20",
    "iptotal": 0,
    "memoryavailable": "40960",
    "memorylimit": "40960",
    "memorytotal": 0,
    "name": "shareproject",
    "networkavailable": "20",
    "networklimit": "20",
    "networktotal": 0,
    "owner": [
      {
        "account": "ACSUser"
      }
    ],
    "primarystorageavailable": "200",
    "primarystoragelimit": "200",
    "primarystoragetotal": 0,
    "projectaccountname": "PrjAcct-shareproject-1",
    "secondarystorageavailable": "400.0",
    "secondarystoragelimit": "400",
    "secondarystoragetotal": 0,
    "snapshotavailable": "20",
    "snapshotlimit": "20",
    "snapshottotal": 0,
    "state": "Active",
    "tags": [],
    "templateavailable": "20",
    "templatelimit": "20",
    "templatetotal": 0,
    "vmavailable": "20",
    "vmlimit": "20",
    "vmrunning": 0,
    "vmstopped": 0,
    "vmtotal": 0,
    "volumeavailable": "20",
    "volumelimit": "20",
    "volumetotal": 0,
    "vpcavailable": "20",
    "vpclimit": "20",
    "vpctotal": 0
  }
}
(sblab) 🐓 > create network zoneid=2e44d4bc-63a5-4510-885d-f5ee182a46a3 networkofferingid=6004bac4-624d-4ed5-85b7-939fcf08bdbf name=testshare displaytext=testshare
{
  "network": {
    "account": "ACSUser",
    "acltype": "Account",
    "broadcastdomaintype": "Vlan",
    "canusefordeploy": true,
    "created": "2022-07-27T08:16:46+0000",
    "displaytext": "testshare",
    "dns1": "10.0.32.1",
    "dns2": "8.8.8.8",
    "domain": "ROOT",
    "domainid": "2e8b5f3a-f71a-11ec-87b5-1e0057000461",
    "hasannotations": false,
    "id": "9e4f4ddc-cef9-4edb-adf5-c0fb8ca53eff",
    "ispersistent": false,
    "issystem": false,
    "name": "testshare",
    "networkofferingavailability": "Optional",
    "networkofferingconservemode": true,
    "networkofferingdisplaytext": "Offering for L2 networks",
    "networkofferingid": "6004bac4-624d-4ed5-85b7-939fcf08bdbf",
    "networkofferingname": "DefaultL2NetworkOffering",
    "physicalnetworkid": "c70efc52-66d9-4287-b404-56234aff5a69",
    "receivedbytes": 0,
    "redundantrouter": false,
    "related": "9e4f4ddc-cef9-4edb-adf5-c0fb8ca53eff",
    "restartrequired": false,
    "sentbytes": 0,
    "service": [],
    "specifyipranges": false,
    "state": "Allocated",
    "strechedl2subnet": false,
    "tags": [],
    "traffictype": "Guest",
    "type": "L2",
    "zoneid": "2e44d4bc-63a5-4510-885d-f5ee182a46a3",
    "zonename": "ref-trl-3339-v-M7-abhishek-kumar"
  }
}
```


As root admin *admin* add user *user1* to the project and share network in the project

```
(sblab) 🐧 > set username admin
(sblab) 🐄 > add accounttoproject projectid=1ad3e648-c9d2-4b7f-b87a-2a713477762e account=user1 
{
  "success": true
}
(sblab) 🕊 > create networkpermissions networkid=9e4f4ddc-cef9-4edb-adf5-c0fb8ca53eff projectids=1ad3e648-c9d2-4b7f-b87a-2a713477762e 
{
  "success": true
}
```


As user *user1* list the network shared with the project and deploy vm using it

```
(sblab) 🐋 > set username user1
(sblab) 🐌 > sync
Discovered 287 APIs
(sblab) 🐥 > list networks projectid=1ad3e648-c9d2-4b7f-b87a-2a713477762e filter=id,name
{
  "count": 1,
  "network": [
    {
      "id": "9e4f4ddc-cef9-4edb-adf5-c0fb8ca53eff",
      "name": "testshare"
    }
(sblab) 🕊 > deploy virtualmachine zoneid=2e44d4bc-63a5-4510-885d-f5ee182a46a3 templateid=2e8ff6e7-f71a-11ec-87b5-1e0057000461 serviceofferingid=d3c5c723-cfda-4157-9944-276aebb9c7f8 projectid=1ad3e648-c9d2-4b7f-b87a-2a713477762e networkids=9e4f4ddc-cef9-4edb-adf5-c0fb8ca53eff
{
  "virtualmachine": {
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2022-07-27T08:21:24+0000",
    "details": {
      "dataDiskController": "osdefault",
      "rootDiskController": "ide"
    },
    "displayname": "VM-1cbcbcf1-92e3-4daa-b58c-0a427450f4a0",
    "domain": "ROOT",
    "domainid": "2e8b5f3a-f71a-11ec-87b5-1e0057000461",
    "guestosid": "2e94757c-f71a-11ec-87b5-1e0057000461",
    "haenable": false,
    "hasannotations": false,
    "hypervisor": "VMware",
    "id": "1cbcbcf1-92e3-4daa-b58c-0a427450f4a0",
    "isdynamicallyscalable": false,
    "jobid": "ced60ad4-8142-4cec-9839-04179f53bc79",
    "jobstatus": 0,
    "lastupdated": "2022-07-27T08:22:14+0000",
    "memory": 512,
    "name": "VM-1cbcbcf1-92e3-4daa-b58c-0a427450f4a0",
    "nic": [
      {
        "broadcasturi": "vlan://1028",
        "deviceid": "0",
        "extradhcpoption": [],
        "id": "c6ded695-c1ea-4429-8d21-95e92a429fe0",
        "isdefault": true,
        "isolationuri": "vlan://1028",
        "macaddress": "02:00:14:57:00:01",
        "networkid": "9e4f4ddc-cef9-4edb-adf5-c0fb8ca53eff",
        "networkname": "testshare",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "L2"
      }
    ],
    "osdisplayname": "CentOS 5.3 (64-bit)",
    "ostypeid": "2e94757c-f71a-11ec-87b5-1e0057000461",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "project": "shareproject",
    "projectid": "1ad3e648-c9d2-4b7f-b87a-2a713477762e",
    "readonlydetails": "dataDiskController, rootDiskController",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "d3c5c723-cfda-4157-9944-276aebb9c7f8",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "templateid": "2e8ff6e7-f71a-11ec-87b5-1e0057000461",
    "templatename": "CentOS 5.3(64-bit) no GUI (vSphere)",
    "userid": "3d668558-b1fe-4aad-bded-9cbc8515dedf",
    "username": "user1",
    "zoneid": "2e44d4bc-63a5-4510-885d-f5ee182a46a3",
    "zonename": "ref-trl-3339-v-M7-abhishek-kumar"
  }
}
```

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing (as admin and as a user, default or custom project)

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3
