### PR TITLE
server: fix url check for storages without a valid url

### LINKED ISSUE #8352: Cannot create primary on StorPool
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Primary storage plugin
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

##### SUMMARY

Creating primary storage on StorPool is impossible because the URL needed is not valid. I checked that a few storage plugins could be affected as well (according to the code), like SolidFire, Nexenta and Cloudbyte (Elastisitor). 
The issue is caused by this change [PR 6699](https://github.com/apache/cloudstack/pull/6699/files#diff-cf68e132ad7711cfa9250cda5819c09f51cba9933aa595cd82ad5a02b4edbe64R783)

I could fix it for StorPool but I think there is a need to be tested for those Storage drives mentioned above and to deliver a general fix.

##### STEPS TO REPRODUCE

create primary storage from UI/CLI

##### EXPECTED RESULTS

~~~
successfully created a storage pool
~~~

##### ACTUAL RESULTS

~~~
SP_API_HTTP=10.2.23.1:81;SP_AUTH_TOKEN=4343423;SP_TEMPLATE=ssd2 is not a valid uri
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #8352
Some managed storages may not need a valid URL to be passed. We can skip check and extraction of host or path from url of such storages.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java [hunk 1]
```diff
@@ -923,42 +924,47 @@ public PrimaryDataStoreInfo createPool(CreateStoragePoolCmd cmd) throws Resource
         return (PrimaryDataStoreInfo)_dataStoreMgr.getDataStore(store.getId(), DataStoreRole.Primary);
     }
 
-    private Map<String,String> extractUriParamsAsMap(String url){
+    protected Map<String,String> extractUriParamsAsMap(String url, boolean managed) {
         Map<String,String> uriParams = new HashMap<>();
         UriUtils.UriInfo uriInfo = UriUtils.getUriInfo(url);
```
Comment (slavkap) [inline server/src/main/java/com/cloud/storage/StorageManagerImpl.java:929]: @shwstppr, it will fail here if the URL is not valid. Also, the Storpool plugin doesn't use the managed tag

Comment (weizhouapache) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:928]: May check the first characters of url instead of the managed parameter

Comment (shwstppr) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:928]: @slavkap @weizhouapache thanks for the pointers. I'll make the change

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java [hunk 2]
```diff
@@ -808,7 +809,7 @@ protected String createLocalStoragePoolName(Host host, StoragePoolInfo storagePo
     @Override
     public PrimaryDataStoreInfo createPool(CreateStoragePoolCmd cmd) throws ResourceInUseException, IllegalArgumentException, UnknownHostException, ResourceUnavailableException {
         String providerName = cmd.getStorageProviderName();
-        Map<String,String> uriParams = extractUriParamsAsMap(cmd.getUrl());
+        Map<String,String> uriParams = extractUriParamsAsMap(cmd.getUrl(), cmd.isManaged());
```
Comment (slavkap) [inline server/src/main/java/com/cloud/storage/StorageManagerImpl.java:811]: @shwstppr, sorry github doesn't allow you to comment on lines without any changes. On lines 825 and 897  there will be null pointer if the uriParams is empty.

```
 825       ScopeType scopeType = uriParams.get("scheme").toString().equals("file") ? ScopeType.HOST : ScopeType.CLUSTER;

 897       if (params.get("scheme").toString().equals("file")) 
```

**Review by slavkap — APPROVED** [review]
thanks @shwstppr, code LGTM
tested with NFS, StorPool and Ceph primary storage

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@shwstppr ready for review and merge?

**Comment by shwstppr** [comment]
> @shwstppr ready for review and merge?

@weizhouapache it should be ready now. Add some more changes to check for a possible NPE

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java [hunk 3]
```diff
@@ -684,12 +685,19 @@ public boolean stop() {
...
         }
-        String hostAddress = poolInfos.get("host").toString();
+        String hostAddress = poolInfos.get("host") == null ? null : poolInfos.get("host").toString();
+        if (StringUtils.isEmpty(hostAddress)) {
+            throw new InvalidParameterValueException("Invalid host provided");
+        }
+        String hostPath = poolInfos.get("hostPath") == null ? null : poolInfos.get("hostPath").toString();
+        if (StringUtils.isEmpty(hostPath)) {
+            throw new InvalidParameterValueException("Invalid path provided");
+        }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/storage/StorageManagerImpl.java:700]: can these be two extra methods for readability?

Comment (weizhouapache) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:700]: this looks more readable to me  :-D

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:700]: I think we should have more discipline to keep methods simple. Our code should be readable by humans *and* computers.

Comment (weizhouapache) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:700]: on the other hand if there are too many methods and method hierarchies, it is not readable by humans.
we need a tradeoff

Comment (shwstppr) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java]: @DaanHoogland I've done the refactor. Do you approve the changes?

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java (hunk 3 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java]: yes @shwstppr 
@weizhouapache if that is the case we need more refactoring, not less. Organising the methods into logical groups and extract them into their own modules. The only trade-off is "Do we have enough time to do it" imnsho.
