### PR TITLE
ui: show tags only for supported resources

### LINKED ISSUE #5727: Tags are displayed incorrectly or aren't displayed at all
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Storage tags are displayed incorrectly:
image

image

Host tags aren't displayed

image

image

##### STEPS TO REPRODUCE
~~~
Add tag to storage
~~~
##### EXPECTED RESULTS
~~~
Storage's tags are displayed correctly. Host's tags are displayed.
~~~

##### ACTUAL RESULTS
~~~
Storage tags are displayed incorrectly. Host tags aren't displayed.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Tags in info card of the UI are related to tags functionality(create/delete/listTags API)
UI was incorrectly showing storage tags as these tags in the UI.

Fixes #5727

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Before:
Screenshot from 2021-12-21 16-17-51

After:
Screenshot from 2021-12-23 12-27-52

### How Has This Been Tested?

Using UI

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

File: ui/src/components/view/InfoCard.vue [hunk 1]
```diff
@@ -772,7 +772,8 @@ export default {
       this.showKeys = false
       this.setData()
 
-      if ('tags' in this.resource) {
+      console.log(this.resourceType)
```
Comment (rhtyd) [inline ui/src/components/view/InfoCard.vue:775]: remove console logging?

**Comment by shwstppr** [comment]
@blueorangutan ui

File: ui/src/components/view/InfoCard.vue (hunk 1 above)
Comment (shwstppr) [reply ui/src/components/view/InfoCard.vue]: @rhtyd done

**Review by utchoang — APPROVED** [review]
LGTM!

**Comment by harikrishna-patnala** [comment]
Thanks for fix @shwstppr. #5727 bug also reports about tags for host, Can you please consider fixing that as well, it says after adding tags, it is not displaying the tags. I've checked that and there is an issue.

**Comment by shwstppr** [comment]
@harikrishna-patnala made change to show tags only for supported resource types

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by sureshanaparti** [comment]
@blueorangutan ui

File: ui/src/components/view/InfoCard.vue [hunk 2]
```diff
@@ -794,6 +796,12 @@ export default {
     await this.getIcons()
   },
   computed: {
+    tagsSupportingResourceTypes () {
+      return ['UserVm', 'Template', 'ISO', 'Volume', 'Snapshot', 'Backup', 'Network',
+        'LoadBalancer', 'PortForwardingRule', 'FirewallRule', 'SecurityGroup', 'SecurityGroupRule',
+        'PublicIpAddress', 'Project', 'Account', 'Vpc', 'NetworkACL', 'StaticRoute', 'VMSnapshot',
+        'RemoteAccessVpn', 'User', 'SnapshotPolicy', 'VpcOffering']
```
Comment (sureshanaparti) [inline ui/src/components/view/InfoCard.vue:803]: @shwstppr Is this the complete resources list supporting tags? how about keeping unsupported resource types only?

Comment (shwstppr) [reply ui/src/components/view/InfoCard.vue:803]: @sureshanaparti some of the resource types used in the UI are not even present in the backend, https://github.com/shapeblue/cloudstack/blob/4.16/ui/src/config/section/infra/primaryStorages.js#L42

**Review by rohityadavcloud — APPROVED** [review]
