### PR TITLE
UI: Fix missing locale strings for Status widget

### LINKED ISSUE #8783: UI: publicip VM listing missing locale string
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.18.1
~~~

##### CONFIGURATION
Standard install

##### OS / ENVIRONMENT
Rocky Linux 8

##### SUMMARY
When adding a VM to a port forwarding to a public IP address, the VM listing's mouse-over message is missing a locale string.

Eg:
Screenshot from 2024-03-13 11-28-36
Screenshot from 2024-03-13 14-05-37

`message.publicip.state.running` does not exist. These should probably use the existing locale strings such as `message.vm.state.running` that's in use by the VM listing page, however.

##### STEPS TO REPRODUCE
~~~
Network -> Public IP addresses -> IP -> Port forwarding -> Click on the 'Add' button and hover over the state of the VM.
~~~

##### EXPECTED RESULTS
~~~
Show the VM state in the user's language
~~~

##### ACTUAL RESULTS
~~~
Shows the locale key (eg. `message.publicip.state.running) instead of the resolved string.
~~~

### PR DESCRIPTION
**Pull request by vishesh92**
### Description

This PR fixes #8783. Status widget changes the tooltip message based on the url. To fix this, before returning the tooltip message, we check if there is no string available in locale and set the message to state.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by vishesh92** [comment]
@blueorangutan ui

File: ui/src/components/widgets/Status.vue [hunk 1]
```diff
@@ -166,23 +166,24 @@ export default {
       if (!(state && this.displayText)) {
         return ''
       }
```
Comment (DaanHoogland) [inline ui/src/components/widgets/Status.vue:168]:
```sugestion
        result = ''
```
???

**Review by DaanHoogland — APPROVED** [review]
lgtm, btw

File: ui/src/components/widgets/Status.vue (hunk 1 above)
Comment (vishesh92) [reply ui/src/components/widgets/Status.vue:168]: Trying to retain the same behavior of widget. Suggested implementation will make the conditions in L182 a little complicated and hard to understand.

**Review by rohityadavcloud — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
tested in qa
