### PR TITLE
Fix snapshot chain being deleted on XenServer

### LINKED ISSUE #9446: Whole snapshot chain is lost when the latest snapshot is deleted
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
4.19.1
4.19.2
main
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Env with XenServer

##### SUMMARY
When deleting a snapshot on XenServer, all of its parents will be erased, causing data loss. 

##### STEPS TO REPRODUCE

~~~
1. Create a VM
2. Take a volume snapshot (S1).
3. Access the VM and write some data, for example with: dd if=/dev/zero of=test bs=1M count=1000
4. Use sync to make sure data is written to disk
5. Take a second volume snapshot (S2).
6. Delete the last volume snapshot (S2).
~~~

##### EXPECTED RESULTS

~~~
Only the last volume snapshot (S2) is deleted.
~~~

##### ACTUAL RESULTS

~~~
On the UI, only the last volume snapshot (S2) is deleted. However, actually, the whole snapshot chain is deleted (S2 AND S1). This can be verified directly on storage or through the snapshot_store_ref table. Any operation with the deleted snapshot (S1) will fail.
~~~

### PR DESCRIPTION
**Pull request by JoaoJandre**
### Description

Using XenServer as the hypervisor, when deleting a snapshot that has a parent, that parent will also get erased on storage, causing data loss. This behavior was introduced with #7873, where the list of snapshot states that can be deleted was changed to add `BackedUp` snapshots. 

This PR changes the states list back to the original list, and swaps the while loop for a do while loop to account for the changes in #7873.

Fixes #9446 

### Types of changes

- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [X] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Created a VM
2. Took a volume snapshot (S1).
3. Accessed the VM and wrote some data with: `dd if=/dev/zero of=test bs=1M count=1000`
4. Used `sync` to make sure data is written to disk
5. Took a second volume snapshot (S2).
6. Deleted the last volume snapshot (S2).

Before the change, S1 would be mistakenly deleted from storage as well, and an inconsistent snapshot record would remain.
After the change, S1 is untouched and works as intended.

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test alma8 xcpng82

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java [hunk 1]
```diff
@@ -247,7 +248,7 @@ protected boolean deleteSnapshotChain(SnapshotInfo snapshot, String storageToStr
                 }
 
                 snapshot = parent;
-            }
+            } while (snapshot != null && snapshotStatesAbleToDeleteSnapshot.contains(snapshot.getState()));
```
Comment (harikrishna-patnala) [inline engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java:251]: will this have any effect on the KVM and VMware snapshots ? @JoaoJandre

Comment (shwstppr) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java:251]: Don't think VMware and KVM should be affected as we don't have linked snapshots there

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java [hunk 2]
```diff
@@ -199,9 +201,8 @@ protected boolean deleteSnapshotChain(SnapshotInfo snapshot, String storageToStr
 
         boolean result = false;
         boolean resultIsSet = false;
-        final List<Snapshot.State> snapshotStatesAbleToDeleteSnapshot = Arrays.asList(Snapshot.State.BackedUp, Snapshot.State.Destroying, Snapshot.State.Destroyed, Snapshot.State.Error);
```
Comment (shwstppr) [inline engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java:202]: I seem to have made a mistake here. `Snapshot.State.BackedUp` was added to allow the deletion of snapshot copies. Using do-while should allow the deletion of the first snapshot entry irrespective of the state

**Review by shwstppr — APPROVED** [review]
Code LGTM. Will test with a multi-zone env

**Review by shwstppr — APPROVED** [review]
Tested with a 2 zone (**z1**, **z2**) env with one XCP-ng82 host in each.

1. Deployed VM
2. Created ROOT volume snapshot(**snap1**) in both zones
3. Made changes inside VM
4. Again created ROOT volume snapshot(**snap2**) in both zones
5. Deleted _snap2_ from _z2_. Successful. _snap2_ was intact in zone _z1_. _snap1_ was intact in both _z1_ and _z2_
6. Deleted snap2 without passing zoneid. Successful. _snap1_ was intact in both _z1_ and _z2_

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java (hunk 1 above)
Comment (JoaoJandre) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/snapshot/DefaultSnapshotStrategy.java:251]: @harikrishna-patnala @shwstppr I actually caught this problem when working in #9270, as the same behavior of deleting the whole chain was happening there too. I have tested the fix both on main and with #9270, and it worked for both Xen and KVM (with and without incremental snaps). I currently do not have an available VMware env to test, but as @shwstppr said, VMware only works with full snapshot at the moment so this should work without any issues.

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by borisstoyanov** [comment]
@blueorangutan help

**Comment by borisstoyanov** [comment]
@blueorangutan test ol8 vmware-80u1

**Review by borisstoyanov — APPROVED** [review]
LGTM, manually check the PR following the steps

**Comment by JoaoJandre** [comment]
Are your concerns met @harikrishna-patnala ? if so, can we move on with this PR @shwstppr ?

**Review by harikrishna-patnala — APPROVED** [review]
LGTM

**Comment by harikrishna-patnala** [comment]
> Are your concerns met @harikrishna-patnala ? if so, can we move on with this PR @shwstppr ?

Yes, thanks @JoaoJandre

**Comment by shwstppr** [comment]
Merging based on review and tests
