### PR TITLE
edge-zone,kvm,iso,cks: allow k8s deployment with direct-download iso

### LINKED ISSUE #7284: Edge Zone can not register iso
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME
API,  UI,

~~~

~~~

##### CLOUDSTACK VERSION
main ,4.18.0.0 RC1

~~~
We created Edge Zone named edge1,when registered iso , we can not choose the edge1(only all zone), then it rasied error:
Unable to find image store to download template null 

![Uploading image.png…]()

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

- Allows registering direct-download ISOs
- Allows VM deployment using ISOs in edge zones
- Allows registering k8s versions as direct-download
- Enables k8s cluster deployment in edge-zones

Fixes #7284 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM - didn't test it, @shwstppr pl also look at any smoketests/unit tests changes

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java [hunk 1]
```diff
@@ -204,11 +205,9 @@ public List<TemplateInfo> listTemplateOnCache(long templateId) {
      */
     private Long getOneMatchingPoolIdFromRefs(List<VMTemplateStoragePoolVO> existingRefs, List<StoragePoolVO> pools) {
         if (pools.isEmpty()) {
-            throw new CloudRuntimeException("No storage pools found");
+            return null;
```
Comment (DaanHoogland) [inline engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java:208]: returning null is not a good practice. Can this `if (pools.isEmpty())` be handled in the calling methods and an exception be thrown here?

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java [hunk 2]
```diff
@@ -217,20 +216,23 @@ private Long getOneMatchingPoolIdFromRefs(List<VMTemplateStoragePoolVO> existing
...
-        return null;
+        return pools.get(0).getId();
     }
 
     /**
-     * Retrieve storage pools with scope = cluster or zone matching clusterId or dataCenterId depending on their scope
+     * Retrieve storage pools with scope = cluster or zone or local matching clusterId or dataCenterId or hostId depending on their scope
      */
-    private List<StoragePoolVO> getStoragePoolsFromClusterOrZone(Long clusterId, long dataCenterId, Hypervisor.HypervisorType hypervisorType) {
+    private List<StoragePoolVO> getStoragePoolsFromClusterOrZoneOrLocal(Long clusterId, long dataCenterId, Hypervisor.HypervisorType hypervisorType, long hostId) {
```
Comment (DaanHoogland) [inline engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java:225]: naming suggestion
```suggestion
    private List<StoragePoolVO> getStoragePoolsForScope(Long clusterId, long dataCenterId, Hypervisor.HypervisorType hypervisorType, long hostId) {
```

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java [hunk 3]
```diff
@@ -294,12 +294,14 @@ public KVMStoragePool getStoragePoolByURI(String uri) {
         String uuid = null;
         String sourceHost = "";
         StoragePoolType protocol = null;
-        if (storageUri.getScheme().equalsIgnoreCase("nfs") || storageUri.getScheme().equalsIgnoreCase("NetworkFilesystem")) {
+        final String scheme = storageUri.getScheme().toLowerCase();
+        List<String> acceptedSchemes = List.of("nfs", "networkfilesystem", "filesystem");
+        if (acceptedSchemes.contains(scheme)) {
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java:299]: the `IgnoreCase` part disappeared here. Could that give issue for for instance "networkFileSystem"?

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java [hunk 4]
```diff
@@ -244,7 +246,7 @@ public TemplateInfo getReadyBypassedTemplateOnPrimaryStore(long templateId, Long
         if (poolId == null) {
             //Get ISO from existing pool ref
             HostVO host = hostDao.findById(hostId);
-            List<StoragePoolVO> pools = getStoragePoolsFromClusterOrZone(host.getClusterId(), host.getDataCenterId(), host.getHypervisorType());
+            List<StoragePoolVO> pools = getStoragePoolsFromClusterOrZoneOrLocal(host.getClusterId(), host.getDataCenterId(), host.getHypervisorType(), hostId);
```
Comment (DaanHoogland) [inline engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java:249]: here we can 
```suggestion
            List<StoragePoolVO> pools = getStoragePoolsFromClusterOrZoneOrLocal(host.getClusterId(), host.getDataCenterId(), host.getHypervisorType(), hostId);
            if (pools.isEmpty()) {
                 throw new CloudRuntimeException("No storage pool found where to download template: " + templateId);
            }
```
because we know `null` will be returned otherwise. (and I think that should be an exception as well.)

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java [hunk 5]
```diff
@@ -163,6 +164,9 @@ private VirtualMachineTemplate registerKubernetesVersionIso(final Long zoneId, f
         if (StringUtils.isNotEmpty(isoChecksum)) {
             registerIsoCmd.setChecksum(isoChecksum);
         }
+        if (directDownload != null) {
+            registerIsoCmd.setDirectDownload(directDownload);
+        }
```
Comment (DaanHoogland) [inline plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java:169]: default is false. Should we make that explicit here?

File: plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java [hunk 6]
```diff
@@ -297,8 +302,14 @@ public KubernetesSupportedVersionResponse addKubernetesSupportedVersion(final Ad
...
         }
-        if (zoneId != null && dataCenterDao.findById(zoneId) == null) {
-            throw new InvalidParameterValueException("Invalid zone specified");
+        if (zoneId != null) {
+            DataCenter zone = dataCenterDao.findById(zoneId);
+            if (zone == null) {
+                throw new InvalidParameterValueException("Invalid zone specified");
+            }
+            if (DataCenter.Type.Edge.equals(zone.getType())) {
+                directDownload = true;
```
Comment (DaanHoogland) [inline plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/version/KubernetesVersionManagerImpl.java:311]: aha

File: ui/src/views/image/AddKubernetesSupportedVersion.vue [hunk 7]
```diff
@@ -207,23 +218,30 @@ export default {
...
+    handleZoneChange (zoneIdx) {
+      const zone = this.zones[zoneIdx]
+      if (zone.type && zone.type === 'Edge') {
+        this.form.directdownload = true
+        this.directDownloadDisabled = true
+        return
+      }
+      this.form.directdownload = false
+      this.directDownloadDisabled = false
+    },
```
Comment (DaanHoogland) [inline ui/src/views/image/AddKubernetesSupportedVersion.vue:230]: The value directDownload is set to false , when the prior selection was an edge zone and the current is not. But what if before it was already selected to be true, then edge zone was selected and deselected again?

**Review by DaanHoogland — COMMENTED** [review]
looks mostly good. one potential UI issue.

**Review by kiranchavala — COMMENTED** [review]
@shwstppr 

Can we direct download section in Images> Kubernetes iso details page 

The detail is shown only under Images> ISO's

iso1


The detail is not shown under Images> Kubernetes ISO's

direct download iso 1

**Review by kiranchavala — COMMENTED** [review]
@shwstppr Cloudstack should not show L2 networks in the, network dropdown create kubernetes cluster form.

Currently its allowing to create k8s cluster in l2 network, its should throw a pop up saying l2 networks are not supported 



Screenshot 2023-11-03 at 9 59 25 AM

**Comment by shwstppr** [comment]
@kiranchavala will try to make changes for your suggestions along with Daan's review comments. If you're done with testing can you please comment on the functionality part?

**Comment by kiranchavala** [comment]
@shwstppr  Thanks 

functionality wise it's working fine , was able to spin up k8s cluster on edge zones  and launch vm's from iso

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java (hunk 3 above)
Comment (shwstppr) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStoragePoolManager.java:299]: Line 297 should take care of that

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java (hunk 2 above)
Comment (shwstppr) [reply engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java]: Done

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java (hunk 1 above)
Comment (shwstppr) [reply engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java]: Refactored

File: engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java (hunk 4 above)
Comment (shwstppr) [reply engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateDataFactoryImpl.java]: Refactored

File: ui/src/views/image/AddKubernetesSupportedVersion.vue (hunk 7 above)
Comment (shwstppr) [reply ui/src/views/image/AddKubernetesSupportedVersion.vue]: [lastest](https://github.com/apache/cloudstack/pull/8142/commits/af37049643b26669f5cb4e6e574cbe3296e06f51) commit should take care of this

**Comment by shwstppr** [comment]
@DaanHoogland @kiranchavala I've addressed your comments and feedback

@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@shwstppr is this ready for review now?

**Comment by shwstppr** [comment]
@DaanHoogland was waiting for the test result but I guess the test result didn't come due to API limit

**Comment by DaanHoogland** [comment]
from the backend:

Smoke tests completed. 108 look OK, 1 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_06_stop_cpvm | `Failure` | 35.29 | test_ssvm.py

**Comment by shwstppr** [comment]
@kiranchavala Is it okay to merge now? I addressed your comments.

**Review by kiranchavala — APPROVED** [review]
LGTM, tested manually and it works
