### PR TITLE
api/server: fix hahost value in listHosts

### LINKED ISSUE #3717: Host HA is configre fail
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Host Ha 
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
4.11.3
4.12
4.13
~~~

##### SUMMARY

When the ha.tag tag in the global configuration is not the first tag in the host tag, the host will display HA Enabled=No

HOST HA will fail

##### STEPS TO REPRODUCE

~~~
1.configure Global Settings the host.ha=ha
2.Restart cloudstack management service
3.Log in to ACS UI and set tag "test, ha" of host
4.View host ha status




~~~

##### EXPECTED RESULTS

~~~
Host HA Enable =Yes
~~~

##### ACTUAL RESULTS

~~~
Host HA Enable =No

ps: After configure host ha to "ha, test", host ha will display yes. And ha function test is normal
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #3717 

Hosts can have multiple tags assigned to them therefore changes have been made to check for all of the host tags if they match `ha.tag` configuration value.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

With a 2xKVM hosts env with advanced networking
Global config - ha.tag:
```
(localcloud) SBCM5> > list configurations name=ha.tag
{
  "configuration": [
    {
      "category": "Advanced",
      "description": "HA tag defining that the host marked with this tag can be used for HA purposes only",
      "isdynamic": false,
      "name": "ha.tag",
      "value": "ha"
    }
  ],
  "count": 1
}
```
Before changes:
```
(localcloud) SBCM5> > list hosts type='Routing' filter=id,name,hahost,hosttags,hostha
{
  "count": 2,
  "host": [
    {
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "id": "845ba3d4-3c28-497d-a4b5-f3918a3031b3",
      "name": "pr4710-t3640-kvm-centos7-kvm2"
    },
    {
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hosttags": "test,ha",
      "id": "4937aa4f-6f27-4dc8-af70-2335279edf27",
      "name": "pr4710-t3640-kvm-centos7-kvm1"
    }
  ]
}
```
After changes:
```
(localcloud) SBCM5> > list hosts type='Routing' filter=id,name,hahost,hosttags,hostha
{
  "count": 2,
  "host": [
    {
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "id": "845ba3d4-3c28-497d-a4b5-f3918a3031b3",
      "name": "pr4710-t3640-kvm-centos7-kvm2"
    },
    {
      "hahost": true,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hosttags": "test,ha",
      "id": "4937aa4f-6f27-4dc8-af70-2335279edf27",
      "name": "pr4710-t3640-kvm-centos7-kvm1"
    }
  ]
}
```

### CODE REVIEW

**Comment by weizhouapache** [comment]
@shwstppr 
I think it would be better to remove host_tags.tag from host_view. but it requires db change.

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java [hunk 1]
```diff
@@ -274,12 +269,19 @@ public HostResponse newHostResponse(HostJoinVO host, EnumSet<HostDetails> detail
...
-        if (tag != null) {
-            if (response.getHostTags() != null && response.getHostTags().length() > 0) {
+        if (StringUtils.isNotEmpty(tag)) {
+            if (StringUtils.isNotEmpty(response.getHostTags())) {
                 response.setHostTags(response.getHostTags() + "," + tag);
             } else {
                 response.setHostTags(tag);
             }
+
+            if (!Boolean.TRUE.equals(response.getHaHost())) {
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:279]: Suggestion:
Some ways to improve this validation:

- As it does not have an `else` operator, we could just validate with `!responsegetHaHost()`;
- We could use `commons.lang3.BooleanUtils`,  `BooleanUtils.isFalse(response.getHaHost())`;
- As it is validating if it is `false`, we could use `Boolean.FALSE.equals(response.getHaHost())`;
- Do we use the third value of a Boolean (`null`) in `haHost`, somewhere?  If not, we could do a validation on `getHaHost()`;

**Comment by shwstppr** [comment]
> @shwstppr
> I think it would be better to remove host_tags.tag from host_view. but it requires db change.

@weizhouapache we re-create host_view to have concatenated tags with the following changes maybe in 4.16?
```
DROP VIEW IF EXISTS `cloud`.`host_view`;
CREATE VIEW `cloud`.`host_view` AS
    SELECT
        host.id,
        host.uuid,
        host.name,
        host.status,
        host.disconnected,
        host.type,
        host.private_ip_address,
        host.version,
        host.hypervisor_type,
        host.hypervisor_version,
        host.capabilities,
        host.last_ping,
        host.created,
        host.removed,
        host.resource_state,
        host.mgmt_server_id,
        host.cpu_sockets,
        host.cpus,
        host.speed,
        host.ram,
        cluster.id cluster_id,
        cluster.uuid cluster_uuid,
        cluster.name cluster_name,
        cluster.cluster_type,
        data_center.id data_center_id,
        data_center.uuid data_center_uuid,
        data_center.name data_center_name,
        data_center.networktype data_center_type,
        host_pod_ref.id pod_id,
        host_pod_ref.uuid pod_uuid,
        host_pod_ref.name pod_name,
        GROUP_CONCAT(DISTINCT(host_tags.tag)) AS tag,
        guest_os_category.id guest_os_category_id,
        guest_os_category.uuid guest_os_category_uuid,
        guest_os_category.name guest_os_category_name,
        mem_caps.used_capacity memory_used_capacity,
        mem_caps.reserved_capacity memory_reserved_capacity,
        cpu_caps.used_capacity cpu_used_capacity,
        cpu_caps.reserved_capacity cpu_reserved_capacity,
        async_job.id job_id,
        async_job.uuid job_uuid,
        async_job.job_status job_status,
        async_job.account_id job_account_id,
        oobm.enabled AS `oobm_enabled`,
        oobm.power_state AS `oobm_power_state`,
        ha_config.enabled AS `ha_enabled`,
        ha_config.ha_state AS `ha_state`,
        ha_config.provider AS `ha_provider`,
        `last_annotation_view`.`annotation` AS `annotation`,
        `last_annotation_view`.`created` AS `last_annotated`,
        `user`.`username` AS `username`
    FROM
        `cloud`.`host`
            LEFT JOIN
        `cloud`.`cluster` ON host.cluster_id = cluster.id
            LEFT JOIN
        `cloud`.`data_center` ON host.data_center_id = data_center.id
            LEFT JOIN
        `cloud`.`host_pod_ref` ON host.pod_id = host_pod_ref.id
            LEFT JOIN
        `cloud`.`host_details` ON host.id = host_details.host_id
            AND host_details.name = 'guest.os.category.id'
            LEFT JOIN
        `cloud`.`guest_os_category` ON guest_os_category.id = CONVERT ( host_details.value, UNSIGNED )
            LEFT JOIN
        `cloud`.`host_tags` ON host_tags.host_id = host.id
            LEFT JOIN
        `cloud`.`op_host_capacity` mem_caps ON host.id = mem_caps.host_id
            AND mem_caps.capacity_type = 0
            LEFT JOIN
        `cloud`.`op_host_capacity` cpu_caps ON host.id = cpu_caps.host_id
            AND cpu_caps.capacity_type = 1
            LEFT JOIN
        `cloud`.`async_job` ON async_job.instance_id = host.id
            AND async_job.instance_type = 'Host'
            AND async_job.job_status = 0
            LEFT JOIN
        `cloud`.`oobm` ON oobm.host_id = host.id
            left join
        `cloud`.`ha_config` ON ha_config.resource_id=host.id
            and ha_config.resource_type='Host'
            LEFT JOIN
        `cloud`.`last_annotation_view` ON `last_annotation_view`.`entity_uuid` = `host`.`uuid`
            LEFT JOIN
        `cloud`.`user` ON `user`.`uuid` = `last_annotation_view`.`user_uuid`
    GROUP BY
        `host`.`id`;
```

**Comment by weizhouapache** [comment]
> > @shwstppr
> > I think it would be better to remove host_tags.tag from host_view. but it requires db change.
> 
> @weizhouapache we re-create host_view to have concatenated tags with the following changes maybe in 4.16?
> 
> ```
> DROP VIEW IF EXISTS `cloud`.`host_view`;
> CREATE VIEW `cloud`.`host_view` AS
>     SELECT
>         host.id,
>         host.uuid,
>         host.name,
>         host.status,
>         host.disconnected,
>         host.type,
>         host.private_ip_address,
>         host.version,
>         host.hypervisor_type,
>         host.hypervisor_version,
>         host.capabilities,
>         host.last_ping,
>         host.created,
>         host.removed,
>         host.resource_state,
>         host.mgmt_server_id,
>         host.cpu_sockets,
>         host.cpus,
>         host.speed,
>         host.ram,
>         cluster.id cluster_id,
>         cluster.uuid cluster_uuid,
>         cluster.name cluster_name,
>         cluster.cluster_type,
>         data_center.id data_center_id,
>         data_center.uuid data_center_uuid,
>         data_center.name data_center_name,
>         data_center.networktype data_center_type,
>         host_pod_ref.id pod_id,
>         host_pod_ref.uuid pod_uuid,
>         host_pod_ref.name pod_name,
>         GROUP_CONCAT(DISTINCT(host_tags.tag)) AS tag,
>         guest_os_category.id guest_os_category_id,
>         guest_os_category.uuid guest_os_category_uuid,
>         guest_os_category.name guest_os_category_name,
>         mem_caps.used_capacity memory_used_capacity,
>         mem_caps.reserved_capacity memory_reserved_capacity,
>         cpu_caps.used_capacity cpu_used_capacity,
>         cpu_caps.reserved_capacity cpu_reserved_capacity,
>         async_job.id job_id,
>         async_job.uuid job_uuid,
>         async_job.job_status job_status,
>         async_job.account_id job_account_id,
>         oobm.enabled AS `oobm_enabled`,
>         oobm.power_state AS `oobm_power_state`,
>         ha_config.enabled AS `ha_enabled`,
>         ha_config.ha_state AS `ha_state`,
>         ha_config.provider AS `ha_provider`,
>         `last_annotation_view`.`annotation` AS `annotation`,
>         `last_annotation_view`.`created` AS `last_annotated`,
>         `user`.`username` AS `username`
>     FROM
>         `cloud`.`host`
>             LEFT JOIN
>         `cloud`.`cluster` ON host.cluster_id = cluster.id
>             LEFT JOIN
>         `cloud`.`data_center` ON host.data_center_id = data_center.id
>             LEFT JOIN
>         `cloud`.`host_pod_ref` ON host.pod_id = host_pod_ref.id
>             LEFT JOIN
>         `cloud`.`host_details` ON host.id = host_details.host_id
>             AND host_details.name = 'guest.os.category.id'
>             LEFT JOIN
>         `cloud`.`guest_os_category` ON guest_os_category.id = CONVERT ( host_details.value, UNSIGNED )
>             LEFT JOIN
>         `cloud`.`host_tags` ON host_tags.host_id = host.id
>             LEFT JOIN
>         `cloud`.`op_host_capacity` mem_caps ON host.id = mem_caps.host_id
>             AND mem_caps.capacity_type = 0
>             LEFT JOIN
>         `cloud`.`op_host_capacity` cpu_caps ON host.id = cpu_caps.host_id
>             AND cpu_caps.capacity_type = 1
>             LEFT JOIN
>         `cloud`.`async_job` ON async_job.instance_id = host.id
>             AND async_job.instance_type = 'Host'
>             AND async_job.job_status = 0
>             LEFT JOIN
>         `cloud`.`oobm` ON oobm.host_id = host.id
>             left join
>         `cloud`.`ha_config` ON ha_config.resource_id=host.id
>             and ha_config.resource_type='Host'
>             LEFT JOIN
>         `cloud`.`last_annotation_view` ON `last_annotation_view`.`entity_uuid` = `host`.`uuid`
>             LEFT JOIN
>         `cloud`.`user` ON `user`.`uuid` = `last_annotation_view`.`user_uuid`
>     GROUP BY
>         `host`.`id`;
> ```

@shwstppr yeah, 4.16 or 4.15.1.

I suggest to remove tags (resource tags, host tags, etc) from all mysql views.
Assume there are 10 tags, the mysql view with tags will be 10 times larger than the mysql view without tags.
we can easily get and set all tags by a mysql query.

**Comment by shwstppr** [comment]
@weizhouapache with above SQL create view statement we will have a single entry for each host with multiple tags comma-separated. Something like, 
```
*************************** 1. row ***************************
                      id: 1
                    uuid: 4937aa4f-6f27-4dc8-af70-2335279edf27
                    name: pr4710-t3640-kvm-centos7-kvm1
                  status: Disconnected
            disconnected: NULL
                    type: Routing
      private_ip_address: 10.10.3.146
                 version: 4.15.1.0-SNAPSHOT
         hypervisor_type: KVM
      hypervisor_version: NULL
            capabilities: hvm,snapshot
               last_ping: 1577598635
                 created: 2021-03-03 06:09:26
                 removed: NULL
          resource_state: Enabled
          mgmt_server_id: NULL
             cpu_sockets: 3
                    cpus: 3
                   speed: 2350
                     ram: 7277121536
              cluster_id: 1
            cluster_uuid: 881c01ec-7a4b-4c55-af5c-d53de5880b5e
            cluster_name: p1-c1
            cluster_type: CloudManaged
          data_center_id: 1
        data_center_uuid: 3f4d015c-7d6b-4b5e-86b0-79552910f77b
        data_center_name: pr4710-t3640-kvm-centos7
        data_center_type: Advanced
                  pod_id: 1
                pod_uuid: 496029eb-411a-4736-954d-73d5a8d15e56
                pod_name: Pod1
                     tag: test,ha
    guest_os_category_id: NULL
  guest_os_category_uuid: NULL
  guest_os_category_name: NULL
    memory_used_capacity: 268435456
memory_reserved_capacity: 0
       cpu_used_capacity: 500
   cpu_reserved_capacity: 0
                  job_id: NULL
                job_uuid: NULL
              job_status: NULL
          job_account_id: NULL
            oobm_enabled: NULL
        oobm_power_state: NULL
              ha_enabled: NULL
                ha_state: NULL
             ha_provider: NULL
              annotation: NULL
          last_annotated: NULL
                username: NULL
```

**Comment by weizhouapache** [comment]
> @weizhouapache with above SQL create view statement we will have a single entry for each host with multiple tags comma-separated. Something like,
> 
> ```
> *************************** 1. row ***************************
>                       id: 1
>                     uuid: 4937aa4f-6f27-4dc8-af70-2335279edf27
>                     name: pr4710-t3640-kvm-centos7-kvm1
>                   status: Disconnected
>             disconnected: NULL
>                     type: Routing
>       private_ip_address: 10.10.3.146
>                  version: 4.15.1.0-SNAPSHOT
>          hypervisor_type: KVM
>       hypervisor_version: NULL
>             capabilities: hvm,snapshot
>                last_ping: 1577598635
>                  created: 2021-03-03 06:09:26
>                  removed: NULL
>           resource_state: Enabled
>           mgmt_server_id: NULL
>              cpu_sockets: 3
>                     cpus: 3
>                    speed: 2350
>                      ram: 7277121536
>               cluster_id: 1
>             cluster_uuid: 881c01ec-7a4b-4c55-af5c-d53de5880b5e
>             cluster_name: p1-c1
>             cluster_type: CloudManaged
>           data_center_id: 1
>         data_center_uuid: 3f4d015c-7d6b-4b5e-86b0-79552910f77b
>         data_center_name: pr4710-t3640-kvm-centos7
>         data_center_type: Advanced
>                   pod_id: 1
>                 pod_uuid: 496029eb-411a-4736-954d-73d5a8d15e56
>                 pod_name: Pod1
>                      tag: test,ha
>     guest_os_category_id: NULL
>   guest_os_category_uuid: NULL
>   guest_os_category_name: NULL
>     memory_used_capacity: 268435456
> memory_reserved_capacity: 0
>        cpu_used_capacity: 500
>    cpu_reserved_capacity: 0
>                   job_id: NULL
>                 job_uuid: NULL
>               job_status: NULL
>           job_account_id: NULL
>             oobm_enabled: NULL
>         oobm_power_state: NULL
>               ha_enabled: NULL
>                 ha_state: NULL
>              ha_provider: NULL
>               annotation: NULL
>           last_annotated: NULL
>                 username: NULL
> ```

@shwstppr it looks perfect.

**Comment by shwstppr** [comment]
@weizhouapache I've created PR #4796 against 4.15 to recreate hosts_view in 4.15.1. I will do some more testing before marking it ready for review
We can use fixes in this PR to address the issue in the 4.14.2 or else close this.
cc @rhtyd

**Review by weizhouapache — APPROVED** [review]
code lgtm

Does #4796 have conflict with this  ?

**Comment by shwstppr** [comment]
@weizhouapache yes #4796 will conflict in the current form. I'll rebase my changes there if this is accepted.

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java (hunk 1 above)
Comment (GutoVeronezi) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:279]: @shwstppr could you take a look at this?

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:279]: my choice would be
```suggestion
            if (Boolean.FALSE.equals(response.getHaHost())) {
```
@shwstppr can you answer @GutoVeronezi ?

**Comment by DaanHoogland** [comment]
clgtm

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java (hunk 1 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:279]: @DaanHoogland I would prefer code as it is

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java (hunk 1 above)
Comment (GutoVeronezi) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:279]: @shwstppr 
I do not see any technical reason to keep a `negation of a TRUE` when we could simply use `FALSE`, besides that it goes against KISS principle; but it is my opinion against yours, in your PR, so I have nothing more to say.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java [hunk 2]
```diff
@@ -419,6 +417,13 @@ public HostForMigrationResponse setHostForMigrationResponse(HostForMigrationResp
...
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:421]:
```suggestion
            if (Boolean.FALSE.equals(response.getHaHost())) {
```

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan test

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test

**Review by rhtyd — APPROVED** [review]
