### PR TITLE
utils: cleanup MacAddress and MacAddressTest

### LINKED ISSUE #8174: Restarting management server causes multiple entries for the same node
Restart management server several times, even if there's only one mgmt server, it causes several entries in the cloud.mshost table and in the API:

Screenshot 2023-11-01 at 11 17 34 PM

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Mgmt server
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### CONFIGURATION

Adv zone KVM env with Ubuntu 22.04

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Cleanup old mac address handling code to use JDK11 lib instead of hacks. Also really strange to see some basic string parsing code was written by hand, replaced with Long.parseValue(str, 16) to convert hex string to long.

Fixes #8174

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java [hunk 1]
```diff
@@ -79,209 +72,45 @@ public String toString() {
...
-                p.destroy();
-            }
+            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
+            while (networkInterfaces.hasMoreElements()) {
+                 NetworkInterface network = networkInterfaces.nextElement();
+                 final byte [] mac = network.getHardwareAddress();
+                 if (mac != null && !network.isVirtual() &&
+                         !network.getName().startsWith("br-") &&
+                         !network.getName().startsWith("veth") &&
+                         !network.getName().startsWith("vnet")) {
```
Comment (DaanHoogland) [inline utils/src/main/java/com/cloud/utils/net/MacAddress.java:83]: sh-/could this test be a method for reuse and readability?

**Review by DaanHoogland — APPROVED** [review]
nice cleanup

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java (hunk 1 above)
Comment (rohityadavcloud) [reply utils/src/main/java/com/cloud/utils/net/MacAddress.java:83]: I'm not sure that's really necessary; unless if you know there's a utility to scan and find if string starts with on an array of provided substrings?

Comment (rohityadavcloud) [reply utils/src/main/java/com/cloud/utils/net/MacAddress.java:83]: One concern though, cc @weizhouapache if you know - do people run CloudStack in containers - if so, could this cause issues (if we ignore virtual nics?)

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java [hunk 2]
```diff
@@ -79,209 +72,45 @@ public String toString() {
...
-            if (p != null) {
-                closeAutoCloseable(in, "closing init process input stream");
-                closeAutoCloseable(p.getErrorStream(), "closing init process error output stream");
-                closeAutoCloseable(p.getOutputStream(), "closing init process std output stream");
-                p.destroy();
-            }
+            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
+            while (networkInterfaces.hasMoreElements()) {
+                 NetworkInterface network = networkInterfaces.nextElement();
+                 final byte [] mac = network.getHardwareAddress();
```
Comment (sureshanaparti) [inline utils/src/main/java/com/cloud/utils/net/MacAddress.java:79]:
```suggestion
                 final byte[] mac = network.getHardwareAddress();
```

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java [hunk 3]
```diff
@@ -79,209 +72,45 @@ public String toString() {
...
+                 if (mac != null && !network.isVirtual() &&
+                         !network.getName().startsWith("br-") &&
+                         !network.getName().startsWith("veth") &&
+                         !network.getName().startsWith("vnet")) {
+                     StringBuilder macAddressBuilder = new StringBuilder();
+                     for (byte b : mac) {
+                         macAddressBuilder.append(String.format("%02X", b));
+                     }
+                     macAddress = macAddressBuilder.toString();
```
Comment (sureshanaparti) [inline utils/src/main/java/com/cloud/utils/net/MacAddress.java:88]: break loop here?

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java [hunk 4]
```diff
@@ -79,209 +72,45 @@ public String toString() {
...
+                 }
+             }
+        } catch (SocketException ignore) {
```
Comment (sureshanaparti) [inline utils/src/main/java/com/cloud/utils/net/MacAddress.java:91]: want to log exception here, in case any issues while fetching network information?

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java (hunk 3 above)
Comment (weizhouapache) [reply utils/src/main/java/com/cloud/utils/net/MacAddress.java:88]: +1

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java (hunk 4 above)
Comment (rohityadavcloud) [reply utils/src/main/java/com/cloud/utils/net/MacAddress.java:91]: Logging wouldn't be necessary here, we ignore it anyway.

File: utils/src/main/java/com/cloud/utils/net/MacAddress.java (hunk 1 above)
Comment (rohityadavcloud) [reply utils/src/main/java/com/cloud/utils/net/MacAddress.java]: Found this to be a non-issue. Interfaces inside containers were found to have non-virtual Nic names.

**Comment by rohityadavcloud** [comment]
Thanks @weizhouapache @sureshanaparti I've addressed the review comments.

@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Review by shwstppr — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
code lgtm

deployed it on an existing environment, there is no new management server added to `mshost` table

**Review by weizhouapache — APPROVED** [review]
