### PR TITLE
Stat collector solidfire capacity fix

### LINKED ISSUE #4911: solidfire primary capacity is reset to zero bytes
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Primary iSCSI solidfire
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0 (after upgrade from 4.11.3)
~~~

##### CONFIGURATION

zone wide storage

##### SUMMARY

a 4.11.3 environment with solidfire zone wide primary storage is upgraded to 4.15.0. After the upgrade the capacity of the storage is set to 0 bytes. After adjusting it it will be reset within a few minutes to 0 bytes again.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

This happened in 4.11.3 and was expected in 4.15.0 as well
~~~
2021-04-12 10:01:25,843 DEBUG c.c.s.StorageManagerImpl (logid:) Found storage pool London Primary Storage of type Iscsi
2021-04-12 10:01:25,843 DEBUG c.c.s.StorageManagerImpl (logid:) Total over provisioned capacity of the pool London Primary Storage id: 2 is 17592186044416
2021-04-12 10:01:25,844 DEBUG c.c.s.StorageManagerImpl (logid:) Successfully set Capacity - 17592186044416 for capacity type - 3 , DataCenterId - 2, HostOrPoolId - 2, PodId null
~~~

##### ACTUAL RESULTS

~~~
2021-04-12 09:17:26,370 DEBUG c.c.s.StorageManagerImpl (logid:) Found storage pool London Primary Storage of type Iscsi
2021-04-12 09:17:26,371 DEBUG c.c.s.StorageManagerImpl (logid:) Total over provisioned capacity of the pool London Primary Storage id: 2 is (0 bytes) 0
2021-04-12 09:17:26,372 DEBUG c.c.s.StorageManagerImpl (logid:) Successfully set Capacity - (0 bytes) 0 for capacity type - 3 , DataCenterId - 2, HostOrPoolId - 2, PodId null
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
Fixes regression introduced in 71c5dbcf492a023dbea5f8c34f8fd883c3ad653f
    which would cause capacity bytes of certain pools to be update which
    shouldn't get updated by StatsCollector such as solidfire.
    
Fixes #4911

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

Temporary repo builds here for testing purposes for community: http://download.cloudstack.org/testing/pr-4918/
(This will be removed after the PR is merged)

### CODE REVIEW

**Comment by rhtyd** [comment]
cc @ravening - pl review the regression was introduced in 71c5dbcf492a023dbea5f8c34f8fd883c3ad653f
With the fix, anyone upgrading to 4.15 will be unable to use solidfire storage where the capacity bytes is `0`.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

File: server/src/main/java/com/cloud/server/StatsCollector.java [hunk 1]
```diff
@@ -1020,14 +1020,18 @@ protected void runInContext() {
...
-                                    pool.getUsedBytes() != ((StorageStats)answer).getByteUsed()) {
+                            if (_storagePoolStats.get(poolId) != null && _storagePoolStats.get(poolId).getCapacityBytes() != ((StorageStats)answer).getCapacityBytes()) {
                                 pool.setCapacityBytes(((StorageStats)answer).getCapacityBytes());
-                                if (pool.getStorageProviderName().equalsIgnoreCase(DataStoreProvider.DEFAULT_PRIMARY)) {
-                                    pool.setUsedBytes(((StorageStats) answer).getByteUsed());
-                                    pool.setUpdateTime(new Date());
-                                }
+                                poolNeedsUpdating = true;
+                            }
+                            if (pool.getUsedBytes() != ((StorageStats)answer).getByteUsed() && pool.getStorageProviderName().equalsIgnoreCase(DataStoreProvider.DEFAULT_PRIMARY) && ((StorageStats)answer).getByteUsed() > 0) {
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/server/StatsCollector.java:1029]: This restricts updating, when no bytes used in the pool. Suppose, there are few volumes in the pool which are removed later and the answer for 'GetStorageStatsCommand' returns 0 bytes used for that pool.

File: server/src/main/java/com/cloud/server/StatsCollector.java [hunk 2]
```diff
@@ -1020,14 +1020,18 @@ protected void runInContext() {
                         if (answer != null && answer.getResult()) {
                             storagePoolStats.put(pool.getId(), (StorageStats)answer);
 
+                            boolean poolNeedsUpdating = false;
                             // Seems like we have dynamically updated the pool size since the prev. size and the current do not match
-                            if (pool.getCapacityBytes() != ((StorageStats)answer).getCapacityBytes() ||
-                                    pool.getUsedBytes() != ((StorageStats)answer).getByteUsed()) {
+                            if (_storagePoolStats.get(poolId) != null && _storagePoolStats.get(poolId).getCapacityBytes() != ((StorageStats)answer).getCapacityBytes()) {
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/server/StatsCollector.java:1025]: @rhtyd may be you can update the capacity bytes (from the 'GetStorageStatsCommand' answer) when it is > 0. Otherwise, better to log a WARN message indicating that answer holds the capacity bytes <= 0.

File: server/src/main/java/com/cloud/server/StatsCollector.java (hunk 1 above)
Comment (rhtyd) [reply server/src/main/java/com/cloud/server/StatsCollector.java:1029]: When pool is added to cloudstack or cloudstack is restarted, if the pool is empty the usage will be set to 0. I see that case, let me see what/how can we handle that. This change was recently added in 4.15 only.

File: server/src/main/java/com/cloud/server/StatsCollector.java (hunk 2 above)
Comment (rhtyd) [reply server/src/main/java/com/cloud/server/StatsCollector.java:1025]: The code is reverted to how it was structured in 4.11.3; I suppose at least the solidfire storage pool capacity wouldn't reset to 0. But good idea to add some guarding (either for the 0 check or if the pool is solidfire).

File: server/src/main/java/com/cloud/server/StatsCollector.java [hunk 3]
```diff
@@ -1020,14 +1020,22 @@ protected void runInContext() {
...
-                                    pool.setUpdateTime(new Date());
+                            if (_storagePoolStats.get(poolId) != null && _storagePoolStats.get(poolId).getCapacityBytes() != ((StorageStats)answer).getCapacityBytes()) {
+                                if (((StorageStats)answer).getCapacityBytes() > 0) {
+                                    pool.setCapacityBytes(((StorageStats)answer).getCapacityBytes());
+                                    poolNeedsUpdating = true;
+                                } else {
+                                    s_logger.warn("Received 0 capacity for pool ID " + poolId);
                                 }
+                            }
+                            if (pool.getUsedBytes() != ((StorageStats)answer).getByteUsed() && pool.getStorageProviderName().equalsIgnoreCase(DataStoreProvider.DEFAULT_PRIMARY) && !pool.isManaged()) {
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/server/StatsCollector.java:1033]: @sureshanaparti I've added a check to not update when pool is managed, cc @skattoju4 @mike-tutkowski

File: server/src/main/java/com/cloud/server/StatsCollector.java [hunk 4]
```diff
@@ -1020,14 +1020,22 @@ protected void runInContext() {
...
+                            boolean poolNeedsUpdating = false;
                             // Seems like we have dynamically updated the pool size since the prev. size and the current do not match
-                            if (pool.getCapacityBytes() != ((StorageStats)answer).getCapacityBytes() ||
-                                    pool.getUsedBytes() != ((StorageStats)answer).getByteUsed()) {
-                                pool.setCapacityBytes(((StorageStats)answer).getCapacityBytes());
-                                if (pool.getStorageProviderName().equalsIgnoreCase(DataStoreProvider.DEFAULT_PRIMARY)) {
-                                    pool.setUsedBytes(((StorageStats) answer).getByteUsed());
-                                    pool.setUpdateTime(new Date());
+                            if (_storagePoolStats.get(poolId) != null && _storagePoolStats.get(poolId).getCapacityBytes() != ((StorageStats)answer).getCapacityBytes()) {
+                                if (((StorageStats)answer).getCapacityBytes() > 0) {
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/server/StatsCollector.java:1026]: @sureshanaparti cc @DaanHoogland added check to log warning when capacity is reported 0; it's updated only when the value is > 0.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test matrix

File: server/src/main/java/com/cloud/server/StatsCollector.java (hunk 3 above)
Comment (sureshanaparti) [reply server/src/main/java/com/cloud/server/StatsCollector.java:1033]: @rhtyd I think managed pool(s) doesn't use DefaultPrimary as its provider, in that case managed pool check is not required.

**Review by DaanHoogland — APPROVED** [review]

File: server/src/main/java/com/cloud/server/StatsCollector.java [hunk 5]
```diff
@@ -1020,14 +1020,22 @@ protected void runInContext() {
...
+                                    pool.setCapacityBytes(((StorageStats)answer).getCapacityBytes());
+                                    poolNeedsUpdating = true;
+                                } else {
+                                    s_logger.warn("Received 0 capacity for pool ID " + poolId);
```
Comment (nvazquez) [inline server/src/main/java/com/cloud/server/StatsCollector.java:1030]:
```suggestion
                                    s_logger.warn("Not setting capacity bytes, received " + ((StorageStats)answer).getCapacityBytes()  + " capacity for pool ID " + poolId);
```

File: server/src/main/java/com/cloud/server/StatsCollector.java (hunk 3 above)
Comment (mike-tutkowski) [reply server/src/main/java/com/cloud/server/StatsCollector.java:1033]: That's a good point about managed-storage providers not using DefaultPrimary. Each of these storage providers probably provides its own plug-in.

File: server/src/main/java/com/cloud/server/StatsCollector.java [hunk 6]
```diff
@@ -1020,14 +1020,22 @@ protected void runInContext() {
...
-                                    pool.setUpdateTime(new Date());
+                            if (_storagePoolStats.get(poolId) != null && _storagePoolStats.get(poolId).getCapacityBytes() != ((StorageStats)answer).getCapacityBytes()) {
+                                if (((StorageStats)answer).getCapacityBytes() > 0) {
+                                    pool.setCapacityBytes(((StorageStats)answer).getCapacityBytes());
+                                    poolNeedsUpdating = true;
+                                } else {
+                                    s_logger.warn("Not setting capacity bytes, received " + ((StorageStats)answer).getCapacityBytes()  + " capacity for pool ID " + poolId);
                                 }
+                            }
+                            if (pool.getUsedBytes() != ((StorageStats)answer).getByteUsed() && pool.getStorageProviderName().equalsIgnoreCase(DataStoreProvider.DEFAULT_PRIMARY)) {
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/server/StatsCollector.java:1033]: Thanks @sureshanaparti @mike-tutkowski - I've addressed the comment, removed the check for managed storage.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test
