### PR TITLE
orchestration,hypervisor: allow custom manufacturer, product for vm metadata

### LINKED ISSUE #9142: Allow Users To Change Guest VM 'Hardware Information'
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
LibvirtVMDef.java
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### SUMMARY

When Users spin up a VM, from the Virtual Machine, they can see the 'Hardware information' as:

- Hardware Information: Apache Software Foundation Cloudstack KVM Hypervisor.
 
Upon further checking, this value seems to be hardcoded in the VM XML in LibvirtVMDef.java

entry name='manufacturer'>Apache Software Foundation
entry name='product'>CloudStack KVM Hypervisor

Would like to request to enhance this to allow Cloud Operators to configure this to other values.

Screenshot 2024-05-29 at 6 42 31 pm

##### STEPS TO REPRODUCE

~~~
For Windows, open server manager
~~~

##### EXPECTED RESULTS

~~~
To allow Cloud Operators to change these values to their own decided values.
~~~

##### ACTUAL RESULTS

~~~
Unable to change those values as they are hardcoded
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9142

Doc PR: https://github.com/apache/cloudstack-documentation/pull/402

New global settings added to specify VM metadata wrt manufacturer and product:
- `vm.metadata.manufacturer`
- `vm.metadata.product`

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

File: engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java [hunk 1]
```diff
@@ -87,6 +87,20 @@ public interface VirtualMachineManager extends Manager {
...
+                    "A custom manufacturer may break cloud-init functionality with CloudStack datasource. Please " +
+                    "refer documentation", true, ConfigKey.Scope.Zone);
+    ConfigKey<String> VmMetadataProductName = new ConfigKey<>("Advanced", String.class,
+            "vm.metadata.product", "",
+            "If provided, a custom product name will be used in the instance metadata. When an empty" +
+                    "value is set then default product name will be 'CloudStack <HYPERVISIOR_NAME> Hypervisor'. " +
+                    "A custom product name may break cloud-init functionality with CloudStack datasource. Please " +
+                    "refer documentation",
+            true, ConfigKey.Scope.Zone);
+
```
Comment (DaanHoogland) [inline engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java:103]: can we encode the defaults in these configkeys? (at least in the first one, i can see how the second would complicate things.)

File: engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java [hunk 2]
```diff
@@ -1262,6 +1262,8 @@ public void orchestrateStart(final String vmUuid, final Map<VirtualMachineProfil
                     vmGuru.finalizeVirtualMachineProfile(vmProfile, dest, ctx);
 
                     final VirtualMachineTO vmTO = hvGuru.implement(vmProfile);
+                    vmTO.setMetadataManufacturer(VmMetadataManufacturer.valueIn(vm.getDataCenterId()));
+                    vmTO.setMetadataProductName(VmMetadataProductName.valueIn(vm.getDataCenterId()));
```
Comment (DaanHoogland) [inline engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java:1266]: the check would be here.

**Review by DaanHoogland — APPROVED** [review]
clgtm, one minor design option/issue. I would prefer the check to be MS side

File: engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java (hunk 1 above)
Comment (shwstppr) [reply engine/api/src/main/java/com/cloud/vm/VirtualMachineManager.java]: done

**Review by rohityadavcloud — APPROVED** [review]
LGTM but we should add caveat that it could break cloud-init

**Comment by rohityadavcloud** [comment]
@shwstppr is this ready for review or still need some work (as the PR is in draft)

@blueorangutan package

**Comment by shwstppr** [comment]
@rohityadavcloud marked it ready

A note about cloud-init behaviour is added in the global config descriptions and in the doc PR

**Comment by weizhouapache** [comment]
> @rohityadavcloud marked it ready
> 
> A note about cloud-init behaviour is added in the global config descriptions and in the doc PR

thanks @shwstppr 

overall looks good to me
- is it implemented for kvm ?
- can  you add a unit test for it ?

**Comment by shwstppr** [comment]
@weizhouapache added tests
Currently only used in KVM VM definitions. I couldn't find any reference in other hypervisor plugins

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> @weizhouapache added tests Currently only used in KVM VM definitions. I couldn't find any reference in other hypervisor plugins

thanks
code lgtm

**Review by rohityadavcloud — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan LLtest alma8 kvm-alma8

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing. Tested with Oracle Linux 8 KVM and CentOS 7 guest OS.
