### PR TITLE
Set RAW format to RBD DATADISK

### LINKED ISSUE #5531: Deployment of a VM with a DATADISK on Ceph sets QCOW2 format
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Ceph storage
~~~

##### CLOUDSTACK VERSION

~~~
4.15.3.0/main but may exist on previous versions
~~~

##### OS / ENVIRONMENT

CentOS 7
KVM hypervisors

##### SUMMARY

After deploying a VM with a `DATADISK` (both volumes - ROOT/DATADISK  are on Ceph) the `DATADISK` gets `QCOW2` format

```
select id, pool_type, storage_provider_name from storage_pool where id=203;
+-----+-----------+-----------------------+
| id  | pool_type | storage_provider_name |
+-----+-----------+-----------------------+
| 203 | RBD       | DefaultPrimary        |
+-----+-----------+-----------------------+
1 row in set (0.00 sec)

SELECT format, pool_id, name, instance_id FROM cloud.volumes where instance_id=5360;
+--------+---------+-----------+-------------+
| format | pool_id | name      | instance_id |
+--------+---------+-----------+-------------+
| RAW    |     203 | ROOT-5360 |        5360 |
| QCOW2  |     203 | DATA-5360 |        5360 |
+--------+---------+-----------+-------------+
2 rows in set (0.00 sec)
```

##### STEPS TO REPRODUCE

~~~
Deploy a virtual machine with a `datadisk` on Ceph
~~~

##### EXPECTED RESULTS

~~~
The format of the volume should be in `RAW` format
~~~

##### ACTUAL RESULTS

~~~
in the database, the volume's format is `QCOW2`
~~~

### PR DESCRIPTION
**Pull request by slavkap**
### Description

This PR fixes #5531 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
branch 4.16
hypervisor KVM
deploy a VM with data disk, the format of ROOT/DATADISK is set to RAW

### CODE REVIEW

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 1]
```diff
@@ -1463,7 +1463,7 @@ public Answer createVolume(final CreateObjectCommand cmd) {
             primaryPool = storagePoolMgr.getStoragePool(primaryStore.getPoolType(), primaryStore.getUuid());
             disksize = volume.getSize();
             PhysicalDiskFormat format;
-            if (volume.getFormat() == null) {
+            if (volume.getFormat() == null || StoragePoolType.RBD.equals(primaryStore.getPoolType())) {
```
Comment (sureshanaparti) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1466]: @slavkap this might be applicable to volumes on other storage pools as well, as the format depends on the underlying pool. I think, it is better to set the right volume format based on the primary storage in the volume orchestrator, instead of overriding here based on the pool type when the format is null. (or) update the correct format in the the primary storage driver while creating volume.

Comment (slavkap) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1466]: Hi @sureshanaparti, thank you for the review! I wondered where to set the correct format. When we attach an allocated  Ceph volume, we set RAW format here. That's why I decided to do this in one place and in my case.

Comment (sureshanaparti) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1466]: To set the format after volume creation, check here: https://github.com/apache/cloudstack/blob/b32f3697e6f98ca209bba222fa8c58112f94d85f/engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java#L663

Comment (rohityadavcloud) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1466]: @slavkap @sureshanaparti do we need more changes, or is this PR ready for testing?

Comment (sureshanaparti) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1466]: > To set the format after volume creation, check here:
> 
> https://github.com/apache/cloudstack/blob/b32f3697e6f98ca209bba222fa8c58112f94d85f/engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeObject.java#L663
> 
> Irrespective of the current disk format, update to RAW when pool type is RBD.

Hi @slavkap Can you check if the format can be updated here. Thanks.

Comment (slavkap) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java:1466]: Hi @sureshanaparti, I can check, but the correct volume format is set here if you create an allocated RBD volume. Therefore, in my case also, I prefer the format to be set here.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]

**Review by rohityadavcloud — APPROVED** [review]
