### PR TITLE
server: mark volume snapshots as Destroyed if it does not exist on primary and secondary storage when delete a volume

### LINKED ISSUE #5433: KVM problem with volume snapshots kept only on the primary storage (non-managed storages)
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
volume snapshots 
~~~

##### CLOUDSTACK VERSION

~~~
from 4.11.3.0 to main
~~~

##### SUMMARY

When `snapshot.backup.to.secondary` is set to `false` the snapshots are kept only on the primary storage. When you take more than one snapshot of a volume and delete this volume the snapshots are still active in the UI/DB but deleted from the storage. The problem with different primary storages is:
- for the current NFS implementation is that the snapshots are internal, and they are deleted when you delete the volume - active in the UI/DB
- for Ceph - the snapshots are deleted from the pool, but active in DB/UI
- probably with the new Linstor driver the problem will be the same
- for StorPool the snapshots are not deleted, but a random record is deleted from the `snapshot_store_ref` table and the reference to the snapshot's path is lost
- with this PR - [#5297](https://github.com/apache/cloudstack/pull/5297) - the problem will be the same as the StorPool primary storage

##### STEPS TO REPRODUCE

~~~
- set `snapshot.backup.to.secondary` to `false`
- take a few snapshots of a volume
- delete the volume

The snapshots are visible in the UI, active in DB table `snapshots` and one of them is deleted in `snapshot_store_ref` DB table, because of this code in VolumeServiceImpl.deleteVolumeCallback:


                SnapshotDataStoreVO snapStoreVo = _snapshotStoreDao.findByVolume(vo.getId(), DataStoreRole.Primary);

                if (snapStoreVo != null) {
                    long storagePoolId = snapStoreVo.getDataStoreId();
                    StoragePoolVO storagePoolVO = storagePoolDao.findById(storagePoolId);

                    if (storagePoolVO.isManaged()) {
                        DataStore primaryDataStore = dataStoreMgr.getPrimaryDataStore(storagePoolId);
                        Map<String, String> mapCapabilities = primaryDataStore.getDriver().getCapabilities();

                        String value = mapCapabilities.get(DataStoreCapabilities.STORAGE_SYSTEM_SNAPSHOT.toString());
                        Boolean supportsStorageSystemSnapshots = new Boolean(value);

                        if (!supportsStorageSystemSnapshots) {
                            _snapshotStoreDao.remove(snapStoreVo.getId());
                        }
                    } else {
                        _snapshotStoreDao.remove(snapStoreVo.getId());
                    }
                }



 ~~~

##### EXPECTED RESULTS

~~~
Probably for all non-managed primary storages we should not delete the snapshots. For NFS this PR - #5297 will fix the problem with the internal snapshots. 

~~~

##### ACTUAL RESULTS

~~~
Snapshots are deleted from the storage, but active in the UI/DB as a garbage 
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
when delete a volume in QCOW2 format, if volume snapshot does not exist on primary and secondary storage, mark the snapshot as Destroyed.

This fixes #5433 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@weizhouapache can you please target the PR to the main branch?
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
LGTM

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java [hunk 1]
```diff
@@ -1583,12 +1583,27 @@ public Volume destroyVolume(long volumeId, Account caller, boolean expunge, bool
...
             }
+            markVolumeSnapshotsAsDestroyed(volume);
             removeVolume(volume.getId());
         }
 
         return volume;
     }
 
+    private void markVolumeSnapshotsAsDestroyed(VolumeVO volume) {
+        if (!Storage.ImageFormat.QCOW2.equals(volume.getFormat())) {
```
Comment (slavkap) [inline server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:1594]: If you have a VM with Ceph's volumes, for example, and `snapshot.backup.to.secondary` is disabled when you expunge the VM, all snapshots remain active in UI, but there are no records in the `snapshot_store_ref` table.

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java [hunk 2]
```diff
@@ -1583,12 +1583,27 @@ public Volume destroyVolume(long volumeId, Account caller, boolean expunge, bool
                 s_logger.warn("Failed to expunge volume: " + volumeId);
                 return null;
             }
+            markVolumeSnapshotsAsDestroyed(volume);
```
Comment (slavkap) [inline server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:1586]: @weizhouapache, this is not applied for the ROOT volumes. If the `snapshot.backup.to.secondary` is disabled and you have snapshots on the ROOT volume when you expunge the VM the snapshots will be in a `BackedUp` state in the DB table `snapshots`, but with no records in the `snapshot_store_ref` table, it is removed.

File: engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java [hunk 3]
```diff
@@ -448,9 +448,9 @@ public Void deleteVolumeCallback(AsyncCallbackDispatcher<VolumeServiceImpl, Comm
                     volDao.remove(vo.getId());
                 }
 
-                SnapshotDataStoreVO snapStoreVo = _snapshotStoreDao.findByVolume(vo.getId(), DataStoreRole.Primary);
+                List<SnapshotDataStoreVO> snapStoreVOs = _snapshotStoreDao.listAllByVolumeAndDataStore(vo.getId(), DataStoreRole.Primary);
 
-                if (snapStoreVo != null) {
+                for (SnapshotDataStoreVO snapStoreVo : snapStoreVOs) {
```
Comment (slavkap) [inline engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:453]: It's only my opinion, but we should handle this in each storage plugin. Each storage has to decide whether it wants to keep the snapshots on the primary, like they handle deleting or keeping the snapshots when a volume is deleted.

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java (hunk 1 above)
Comment (weizhouapache) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:1594]: @slavkap 
I was not quite sure if the snapshots still work and removing this check will not lead to other unexpected issues.
If we can make sure it is not a problem to mark volume snapshot as destroyed if snapshot does not exist in primary and secondary storage, we can remove this check.

Comment (slavkap) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:1594]: Yes, it's better to remove this check because if we don't have snapshots on primary and secondary storage, the snapshot has to be marked as destroyed. I will test it

Comment (weizhouapache) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: @slavkap 
good.
I have removed this check, and fixed the issue in vm expunge/destroy.

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

File: engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java [hunk 4]
```diff
@@ -468,6 +471,7 @@ public Void deleteVolumeCallback(AsyncCallbackDispatcher<VolumeServiceImpl, Comm
                         _snapshotStoreDao.remove(snapStoreVo.getId());
```
Comment (slavkap) [inline engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:471]: Hi @weizhouapache, isn't it better to keep the info in the DB for the snapshots and update the State as `Destroyed`?

**Review by slavkap — APPROVED** [review]
code LGTM - tested but left a comment

File: engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java (hunk 4 above)
Comment (weizhouapache) [reply engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:471]: @slavkap 
is there any benifit ?
the records will be cleaned up by storage garbage collector.

Comment (weizhouapache) [reply engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:471]: @slavkap 
thanks for testing

Comment (slavkap) [reply engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:471]: @weizhouapache, to keep it as history, nothing more

Comment (weizhouapache) [reply engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:471]: @slavkap ah ok, thanks for reply.
the records will be finally cleaned up by storage garbage collector (by default run once every day). They will be kept for only 1 day.
The behaviour is not changed by this PR. It was introduced by 336df84f1787de962a67d0a34551f9027303040e and ccb68e13a74342d4798aae11fe5c57890ff6c0ae

**Comment by nvazquez** [comment]
Merging based on approvals and test results
