### PR TITLE
Fix for Clone VM issue (Unable to access file...since it is locked) with VMware 80u3

### LINKED ISSUE #12035: Unable to access vmdk sice it is locked
### problem

After upgrading VMware to 8.0.3, i got this error during every first deployment from new template. Next deployments are fine, but this error repeats multiple times every time during first deployment of every kind of template.
VM is usually deployed regardless of these errors, but sometimes not.

I can see the same errors in management-server.log as well as in vCenter.

2025-11-09 13:50:36,318 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-34:[ctx-e96ea891, exp070103a.infra.rpc.datacentrum.sk, job-522/job-524, cmd: CopyCommand]) (logid:6403181a) [ignored]failed to get message for exception: Unable to access file /vmfs/volumes/686bd05a-e4a7d1d3-28cd-62e53b800068/fb0a3c60dd74350281c0e7de141ae92b/fb0a3c60dd74350281c0e7de141ae92b-000001.vmdk since it is locked
2025-11-09 13:50:36,318 ERROR [c.c.h.v.r.VmwareResource] (DirectAgent-34:[ctx-e96ea891, exp070103a.infra.rpc.datacentrum.sk, job-522/job-524, cmd: CopyCommand]) (logid:6403181a) CopyCommand failed due to [Exception: java.lang.RuntimeException
Message: Unable to access file /vmfs/volumes/686bd05a-e4a7d1d3-28cd-62e53b800068/fb0a3c60dd74350281c0e7de141ae92b/fb0a3c60dd74350281c0e7de141ae92b-000001.vmdk since it is locked
]. java.lang.RuntimeException: Unable to access file /vmfs/volumes/686bd05a-e4a7d1d3-28cd-62e53b800068/fb0a3c60dd74350281c0e7de141ae92b/fb0a3c60dd74350281c0e7de141ae92b-000001.vmdk since it is locked
	at com.cloud.hypervisor.vmware.util.VmwareClient.waitForTask(VmwareClient.java:428)
	at com.cloud.hypervisor.vmware.mo.VirtualMachineMO.createFullClone(VirtualMachineMO.java:857)
	at com.cloud.storage.resource.VmwareStorageProcessor.createVMFullClone(VmwareStorageProcessor.java:773)
	at com.cloud.storage.resource.VmwareStorageProcessor.createVMAndFolderWithVMName(VmwareStorageProcessor.java:936)
	at com.cloud.storage.resource.VmwareStorageProcessor.cloneVolumeFromBaseTemplate(VmwareStorageProcessor.java:859)
	at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.execute(StorageSubsystemCommandHandlerBase.java:107)
	at com.cloud.storage.resource.VmwareStorageSubsystemCommandHandler.execute(VmwareStorageSubsystemCommandHandler.java:209)
	at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.handleStorageCommands(StorageSubsystemCommandHandlerBase.java:65)
	at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:592)
	at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:306)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

Image

[management-server.log.zip](https://github.com/user-attachments/files/23439295/management-server.log.zip)

### versions

ACS: 4.21
VMware vCenter 8.0.3
Vmware ESXi 8.0.3
Primary storage is VMFS datastores on SAN storage

### The steps to reproduce the bug

1. Create new template - for example Ubuntu 24.04
2. Deploy new VM in ACS from this template

i had this error consistently in all my production and testing environments.

### What to do about it?

It is eventually working, but i presume it is not very good to see multiple such an errors and deployment of first VM is taking very long time

### LINKED ISSUE #12328: Unable to launch a vm on vmware cluster
### problem

Unable to launch a vm on vmware cluster

### versions

ACS 4.22 
vSphere Client version 8.0.3.00000
kvm ubuntu 24.0.4

### The steps to reproduce the bug

1. Have a cloudstack zone with a vmware cluster and a KVM cluster 

2. Make sure the systemvm's are running on kvm  by setting the value "system.vm.default.hypervisor" to KVM

3. Register a ova template

4. Launch a vm  on the vmware hypervisor 

5. Vm fails to launch  with the  following exception 

```
2025-12-23 10:51:46,865 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-11:[ctx-13625a0e, 192.168.55.162, job-2496/job-2497, cmd: CopyCommand]) (logid:09638309) [ignored]failed to get message for exception: Unable to access file /vmfs/volumes/7f631381-bb601b02/9fbc19108407304cb68734a287c50236/9fbc19108407304cb68734a287c50236-000001.vmdk since it is locked
2025-12-23 10:51:46,867 ERROR [c.c.h.v.r.VmwareResource] (DirectAgent-11:[ctx-13625a0e, 192.168.55.162, job-2496/job-2497, cmd: CopyCommand]) (logid:09638309) CopyCommand failed due to [Exception: java.lang.RuntimeException
Message: Unable to access file /vmfs/volumes/7f631381-bb601b02/9fbc19108407304cb68734a287c50236/9fbc19108407304cb68734a287c50236-000001.vmdk since it is locked
]. java.lang.RuntimeException: Unable to access file /vmfs/volumes/7f631381-bb601b02/9fbc19108407304cb68734a287c50236/9fbc19108407304cb68734a287c50236-000001.vmdk since it is locked
        at com.cloud.hypervisor.vmware.util.VmwareClient.waitForTask(VmwareClient.java:428)
        at com.cloud.hypervisor.vmware.mo.VirtualMachineMO.createFullClone(VirtualMachineMO.java:857)
        at com.cloud.storage.resource.VmwareStorageProcessor.createVMFullClone(VmwareStorageProcessor.java:774)
        at com.cloud.storage.resource.VmwareStorageProcessor.createVMAndFolderWithVMName(VmwareStorageProcessor.java:937)
        at com.cloud.storage.resource.VmwareStorageProcessor.cloneVolumeFromBaseTemplate(VmwareStorageProcessor.java:860)
        at com.cloud.storage.resource.StorageSubsystemCommandHandlerBase.execute(StorageSubsystemCommandHandlerBase.java:107)

```

Image

Image

--------

The issue doesn't occur if the system vm are  running on kvm hypervisor  or 

If the ova Template is already present in the primary storage.

Previous related issue 

https://github.com/apache/cloudstack/pull/10586

### What to do about it?

CloudStack should launch vm on vmware if the systemvm's are running

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR addresses Clone VM issue with VMware 80u3, retries cloneVM task when any file access issue while cloning from volume or template and should succeed after few attempts.

This is another issue, recently identified with VMware 80u3 (other related issues addressed here: https://github.com/apache/cloudstack/pull/10586)

Fixes #12035 #12328 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested with multicluster env

Was able to deploy a vm from a ova file 

```
2025-12-26 07:48:12,899 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:ImageStore {"id":1,"name":"NFS:\/\/10.1.32.4\/acs\/secondary\/ref-trl-6142-v-Mu24-kiran-chavala\/ref-trl-6142-v-Mu24-kiran-chavala-sec1","uuid":"59a429d6-9367-45ed-b06f-af5d18201119"}, type: Image
2025-12-26 07:48:12,903 DEBUG [o.a.c.s.d.PrimaryDataStoreImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Not found (templateId:202poolId:1conf:null) in template_spool_ref, persisting it
2025-12-26 07:48:12,910 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"}, type: Primary
2025-12-26 07:48:12,911 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Found template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} in storage pool StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"} with VMTemplateStoragePool: TmplPool[3-202-1-null]
2025-12-26 07:48:12,912 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Acquire lock on VMTemplateStoragePool 3 with timeout 3600 seconds
2025-12-26 07:48:12,917 INFO  [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) lock is acquired for VMTemplateStoragePool 3

2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (DirectAgent-482:[ctx-16173aa5]) (logid:aae472c7) Seq 2-8532350969030120521: Processing:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, [{"org.apache.cloudstack.storage.command.CopyCmdAnswer":{"newData":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"size":"(3.50 GB) 3758096384","path":"ROOT-3","accountId":"0","id":"0","directDownload":"false","deployAsIs":"false","followRedirects":"false"}},"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Seq 2-8532350969030120521: Received:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, { CopyCmdAnswer } }
2025-12-26 07:49:50,887 DEBUG [o.a.c.s.v.VolumeObject] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Updated {"name":"ROOT-3","uuid":"085a9cfe-ae78-4cee-9dd1-2f4697b2c643"} from {"encryptFormat":null,"format":"OVA","path":null,"poolId":1,"size":3758096384} to {"encryptFormat":null,"format":"OVA","path":"ROOT-3","poolId":1,"size":3758096384}


2025-12-26 07:50:17,958 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-29:[ctx-7c16c813, job-35, ctx-a9d8fb99]) (logid:aae472c7) Complete async job-35, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.UserVmResponse/virtualmachine/{"id":"18646751-7e92-45e6-b858-4ed896eaf58d","name":"VM-18646751

```

**Comment by kiranchavala** [comment]
@blueorangutan test matrix

**Comment by weizhouapache** [comment]
> LGTM, Tested with multicluster env
> 
> Was able to deploy a vm from a ova file
> 
> ```
> 2025-12-26 07:48:12,899 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:ImageStore {"id":1,"name":"NFS:\/\/10.1.32.4\/acs\/secondary\/ref-trl-6142-v-Mu24-kiran-chavala\/ref-trl-6142-v-Mu24-kiran-chavala-sec1","uuid":"59a429d6-9367-45ed-b06f-af5d18201119"}, type: Image
> 2025-12-26 07:48:12,903 DEBUG [o.a.c.s.d.PrimaryDataStoreImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Not found (templateId:202poolId:1conf:null) in template_spool_ref, persisting it
> 2025-12-26 07:48:12,910 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"}, type: Primary
> 2025-12-26 07:48:12,911 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Found template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} in storage pool StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"} with VMTemplateStoragePool: TmplPool[3-202-1-null]
> 2025-12-26 07:48:12,912 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Acquire lock on VMTemplateStoragePool 3 with timeout 3600 seconds
> 2025-12-26 07:48:12,917 INFO  [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) lock is acquired for VMTemplateStoragePool 3
> 
> 2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (DirectAgent-482:[ctx-16173aa5]) (logid:aae472c7) Seq 2-8532350969030120521: Processing:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, [{"org.apache.cloudstack.storage.command.CopyCmdAnswer":{"newData":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"size":"(3.50 GB) 3758096384","path":"ROOT-3","accountId":"0","id":"0","directDownload":"false","deployAsIs":"false","followRedirects":"false"}},"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
> 2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Seq 2-8532350969030120521: Received:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, { CopyCmdAnswer } }
> 2025-12-26 07:49:50,887 DEBUG [o.a.c.s.v.VolumeObject] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Updated {"name":"ROOT-3","uuid":"085a9cfe-ae78-4cee-9dd1-2f4697b2c643"} from {"encryptFormat":null,"format":"OVA","path":null,"poolId":1,"size":3758096384} to {"encryptFormat":null,"format":"OVA","path":"ROOT-3","poolId":1,"size":3758096384}
> 
> 
> 2025-12-26 07:50:17,958 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-29:[ctx-7c16c813, job-35, ctx-a9d8fb99]) (logid:aae472c7) Complete async job-35, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.UserVmResponse/virtualmachine/{"id":"18646751-7e92-45e6-b858-4ed896eaf58d","name":"VM-18646751
> ```

as I remember, the issue appears very randomly. 
it would better to register several tempates and deploy vms to see if the issue can be reproduced and the retry fixes the issue

File: vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java [hunk 1]
```diff
@@ -852,16 +848,42 @@ public boolean createFullClone(String cloneName, ManagedObjectReference morFolde
...
+                logger.debug("Cloning VM {}, attempt #{}", cloneName, retryAttempt);
+                return cloneVMTask(cloneName, morFolder, cloneSpec);
+            } catch (Exception e) {
+                logger.info("Got exception while cloning VM {}", cloneName, e);
+                if (e.getMessage() != null && e.getMessage().contains("Unable to access file")) {
+                    logger.debug("Failed to clone VM {}. Retrying", cloneName);
+                    try {
+                        Thread.sleep(1000);
+                    } catch (InterruptedException ie) {
+                        logger.debug("Waiting to clone VM {} been interrupted: ", cloneName);
```
Comment (abh1sar) [inline vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java:880]: Do we really need to ignore interrupts for vm cloning?

Comment (sureshanaparti) [reply vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java:880]: that's for only sleep call @abh1sar

**Comment by kiranchavala** [comment]
> > LGTM, Tested with multicluster env
> > Was able to deploy a vm from a ova file
> > ```
> > 2025-12-26 07:48:12,899 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:ImageStore {"id":1,"name":"NFS:\/\/10.1.32.4\/acs\/secondary\/ref-trl-6142-v-Mu24-kiran-chavala\/ref-trl-6142-v-Mu24-kiran-chavala-sec1","uuid":"59a429d6-9367-45ed-b06f-af5d18201119"}, type: Image
> > 2025-12-26 07:48:12,903 DEBUG [o.a.c.s.d.PrimaryDataStoreImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Not found (templateId:202poolId:1conf:null) in template_spool_ref, persisting it
> > 2025-12-26 07:48:12,910 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"}, type: Primary
> > 2025-12-26 07:48:12,911 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Found template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} in storage pool StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"} with VMTemplateStoragePool: TmplPool[3-202-1-null]
> > 2025-12-26 07:48:12,912 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Acquire lock on VMTemplateStoragePool 3 with timeout 3600 seconds
> > 2025-12-26 07:48:12,917 INFO  [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) lock is acquired for VMTemplateStoragePool 3
> > 
> > 2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (DirectAgent-482:[ctx-16173aa5]) (logid:aae472c7) Seq 2-8532350969030120521: Processing:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, [{"org.apache.cloudstack.storage.command.CopyCmdAnswer":{"newData":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"size":"(3.50 GB) 3758096384","path":"ROOT-3","accountId":"0","id":"0","directDownload":"false","deployAsIs":"false","followRedirects":"false"}},"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
> > 2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Seq 2-8532350969030120521: Received:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, { CopyCmdAnswer } }
> > 2025-12-26 07:49:50,887 DEBUG [o.a.c.s.v.VolumeObject] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Updated {"name":"ROOT-3","uuid":"085a9cfe-ae78-4cee-9dd1-2f4697b2c643"} from {"encryptFormat":null,"format":"OVA","path":null,"poolId":1,"size":3758096384} to {"encryptFormat":null,"format":"OVA","path":"ROOT-3","poolId":1,"size":3758096384}
> > 
> > 
> > 2025-12-26 07:50:17,958 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-29:[ctx-7c16c813, job-35, ctx-a9d8fb99]) (logid:aae472c7) Complete async job-35, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.UserVmResponse/virtualmachine/{"id":"18646751-7e92-45e6-b858-4ed896eaf58d","name":"VM-18646751
> > ```
> 
> as I remember, the issue appears very randomly. it would better to register several tempates and deploy vms to see if the issue can be reproduced and the retry fixes the issue

Tested with multiple templates and the issue is not reproducible

**Review by abh1sar — APPROVED** [review]
Code LGTM

**Comment by DaanHoogland** [comment]
> > > LGTM, Tested with multicluster env
> > > Was able to deploy a vm from a ova file
> > > ```
> > > 2025-12-26 07:48:12,899 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:ImageStore {"id":1,"name":"NFS:\/\/10.1.32.4\/acs\/secondary\/ref-trl-6142-v-Mu24-kiran-chavala\/ref-trl-6142-v-Mu24-kiran-chavala-sec1","uuid":"59a429d6-9367-45ed-b06f-af5d18201119"}, type: Image
> > > 2025-12-26 07:48:12,903 DEBUG [o.a.c.s.d.PrimaryDataStoreImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Not found (templateId:202poolId:1conf:null) in template_spool_ref, persisting it
> > > 2025-12-26 07:48:12,910 DEBUG [o.a.c.s.i.TemplateDataFactoryImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} with id 202 is already in store:StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"}, type: Primary
> > > 2025-12-26 07:48:12,911 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Found template Template {"format":"OVA","id":202,"name":"ubuntu24","uniqueName":"202-2-979c3d6c-906b-3186-9fef-d05872b1fc3a","uuid":"1d8b5254-c5f4-4b1f-8997-7029bd904531"} in storage pool StoragePool {"id":1,"name":"ref-trl-6142-v-Mu24-kiran-chavala-esxi-pri1","poolType":"NetworkFilesystem","uuid":"f5a29843-7c46-3fb1-a0ea-844860f848f1"} with VMTemplateStoragePool: TmplPool[3-202-1-null]
> > > 2025-12-26 07:48:12,912 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Acquire lock on VMTemplateStoragePool 3 with timeout 3600 seconds
> > > 2025-12-26 07:48:12,917 INFO  [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) lock is acquired for VMTemplateStoragePool 3
> > > 
> > > 2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (DirectAgent-482:[ctx-16173aa5]) (logid:aae472c7) Seq 2-8532350969030120521: Processing:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, [{"org.apache.cloudstack.storage.command.CopyCmdAnswer":{"newData":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"size":"(3.50 GB) 3758096384","path":"ROOT-3","accountId":"0","id":"0","directDownload":"false","deployAsIs":"false","followRedirects":"false"}},"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
> > > 2025-12-26 07:49:50,874 DEBUG [c.c.a.t.Request] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Seq 2-8532350969030120521: Received:  { Ans: , MgmtId: 32989492808056, via: 2(10.1.32.115), Ver: v1, Flags: 10, { CopyCmdAnswer } }
> > > 2025-12-26 07:49:50,887 DEBUG [o.a.c.s.v.VolumeObject] (Work-Job-Executor-3:[ctx-880d0346, job-35/job-36, ctx-31015cc3]) (logid:aae472c7) Updated {"name":"ROOT-3","uuid":"085a9cfe-ae78-4cee-9dd1-2f4697b2c643"} from {"encryptFormat":null,"format":"OVA","path":null,"poolId":1,"size":3758096384} to {"encryptFormat":null,"format":"OVA","path":"ROOT-3","poolId":1,"size":3758096384}
> > > 
> > > 
> > > 2025-12-26 07:50:17,958 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-29:[ctx-7c16c813, job-35, ctx-a9d8fb99]) (logid:aae472c7) Complete async job-35, jobStatus: SUCCEEDED, resultCode: 0, result: org.apache.cloudstack.api.response.UserVmResponse/virtualmachine/{"id":"18646751-7e92-45e6-b858-4ed896eaf58d","name":"VM-18646751
> > > ```
> > 
> > 
> > as I remember, the issue appears very randomly. it would better to register several tempates and deploy vms to see if the issue can be reproduced and the retry fixes the issue
> 
> Tested with multiple templates and the issue is not reproducible

does this remove your doubts @weizhouapache ?
