### PR TITLE
ui: speed up compute instance listing

### LINKED ISSUE #7910: GUI -  search instance always give the first VM name and GUI is very slow
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

Categorize the issue - UI

##### CLOUDSTACK VERSION
CloudStack 4.18.0.0

##### OS / ENVIRONMENT
KVM with OEL9

##### SUMMARY
in GUI - when  search instance with particular instance name always give the first VM name in the dashboard 
 GUI is very slow

##### STEPS TO REPRODUCE
GUI- Compute-Instances - search tab - give instance name 

##### EXPECTED RESULTS
search should give the exact VM(instance) name 

##### ACTUAL RESULTS
searching one VM gives the  other VM name ( the first VM in list ) 
~~~

### PR DESCRIPTION
**Pull request by rohityadavcloud**
The default listVirtualMachinesMetrics APIs assumings details=all which isn't really used in the list view. By changing this to a subset of details, we can see gains upto 10x in listing speed in the UI. When moving to the resource/detail view of the UI, don't pass state or details so `all` the details of the instance are returned.

Possibly fixes #7910

In the screenshot below, we can see passing details=min, and other combinations show significant reduction in network time (from 300-400ms to 20-40ms)

Screenshot 2023-08-25 at 12 25 22 PM
Screenshot 2023-08-25 at 12 28 25 PM

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

File: ui/src/config/section/compute.js [hunk 1]
```diff
@@ -32,9 +32,9 @@ export default {
       permission: ['listVirtualMachinesMetrics'],
       resourceType: 'UserVm',
       params: () => {
-        var params = {}
+        var params = { details: 'servoff,tmpl,nics' }
         if (store.getters.metrics) {
-          params = { state: 'running' }
```
Comment (rohityadavcloud) [inline ui/src/config/section/compute.js:37]: I've removed running as otherwise metrics doesn't return all VMs in the list. One can select VM `state` explicitly in the compute/instance page if they want.

File: ui/src/store/mutation-types.js [hunk 2]
```diff
@@ -37,6 +37,7 @@ export const DOMAIN_STORE = 'DOMAIN_STORE'
 export const DARK_MODE = 'DARK_MODE'
 export const VUE_VERSION = 'VUE_VERSION'
 export const CUSTOM_COLUMNS = 'CUSTOM_COLUMNS'
+export const RELOAD_ALL_PROJECTS = 'RELOAD_ALL_PROJECTS'
```
Comment (rohityadavcloud) [inline ui/src/store/mutation-types.js:40]: This fixes a warning

File: ui/src/config/section/compute.js [hunk 3]
```diff
@@ -32,9 +32,9 @@ export default {
...
+          params = { details: 'servoff,tmpl,nics,stats' }
```
Comment (rohityadavcloud) [inline ui/src/config/section/compute.js:37]: VM stats in the API response can cause 5-10x delay compared to normal list API response

File: ui/src/views/AutogenView.vue [hunk 4]
```diff
@@ -858,6 +858,11 @@ export default {
         delete params.showunique
       }
 
+      if (['listVirtualMachinesMetrics'].includes(this.apiName) && this.dataView) {
+        delete params.state
+        delete params.details
+      }
```
Comment (weizhouapache) [inline ui/src/views/AutogenView.vue:864]: @rohityadavcloud 
can you explain why state and details are removed ?

all others look good

File: ui/src/config/section/compute.js (hunk 3 above)
Comment (DaanHoogland) [reply ui/src/config/section/compute.js:37]: is `tmpl` needed in the details? or `stats`?

**Review by DaanHoogland — APPROVED** [review]
code looks good. I can't judge the performance gain in qa, but am relying on the author in this case.

**Review by Pearl1594 — APPROVED** [review]

File: ui/src/config/section/compute.js (hunk 3 above)
Comment (weizhouapache) [reply ui/src/config/section/compute.js:37]: my concern is opposite to @DaanHoogland  :-D
is `'servoff,tmpl,nics`' or `servoff,tmpl,nics,stats` enough for UI ?

File: ui/src/views/AutogenView.vue (hunk 4 above)
Comment (rohityadavcloud) [reply ui/src/views/AutogenView.vue:864]: These are added by the router config, I'll ping you on that code; so we must remove if the keys exists for dataView (or resource view, when only one item is being listed such as the VM)

File: ui/src/config/section/compute.js [hunk 5]
```diff
@@ -32,9 +32,9 @@ export default {
       permission: ['listVirtualMachinesMetrics'],
       resourceType: 'UserVm',
       params: () => {
-        var params = {}
+        var params = { details: 'servoff,tmpl,nics' }
```
Comment (rohityadavcloud) [inline ui/src/config/section/compute.js:35]: @weizhouapache because of these params, details and state...

File: ui/src/config/section/compute.js (hunk 1 above)
Comment (rohityadavcloud) [reply ui/src/config/section/compute.js:37]: just realised I can remove state from the params

File: ui/src/config/section/compute.js (hunk 3 above)
Comment (rohityadavcloud) [reply ui/src/config/section/compute.js:37]: Yes, these are enough just for list view (table view); the stats are only needed when the metrics button is clicked. For the resource view, we delete the params.details, so by default details=all is used when listing a single VM.

File: ui/src/views/AutogenView.vue [hunk 6]
```diff
@@ -858,6 +858,10 @@ export default {
         delete params.showunique
       }
 
+      if (['listVirtualMachinesMetrics'].includes(this.apiName) && this.dataView) {
+        delete params.details
```
Comment (rohityadavcloud) [inline ui/src/views/AutogenView.vue:862]: we remove the details are it may not be `all` as set for the list view (tabular view)

File: ui/src/config/section/compute.js (hunk 3 above)
Comment (rohityadavcloud) [reply ui/src/config/section/compute.js:37]: @weizhouapache @DaanHoogland 
I tested this again both as root admin and normal user account; for VMs and templates with and without resource icons; these are enough details to render the list view (table); when the user clicks any VM/instance, then we call the API remove the details and all details are listed/used in the resource view. While not ideal, this speeds up the listing.

**Comment by rohityadavcloud** [comment]
@blueorangutan ui

File: ui/src/config/section/compute.js (hunk 3 above)
Comment (weizhouapache) [reply ui/src/config/section/compute.js:37]: great, thanks @rohityadavcloud 
I will test it

**Review by weizhouapache — APPROVED** [review]
code lgtm

the display is almost identical to the original page

without this PR
image


with this PR
image

**Comment by dseralathan** [comment]
the VM search give exact VM and is not changing to the first VM in list after we exclude state,IP of VM at filter in field
