### PR TITLE
Fix rollback disk snapshots on instance snapshot failure

### LINKED ISSUE #12927: snapshot resourcecount not updated when deleting a failed VM snapshot
### problem

If I take a VM instance instance snapshot and that shapshot fails (https://github.com/apache/cloudstack/issues/12871) the snapshot resourcecount increases by one.
The problem is that the resourcecount doesn't decrease when I delete that failed snapshot.

### versions

CloudStack 4.22.0
KVM hypervisor
Ceph storage
Rocky Linux 10

### The steps to reproduce the bug

```
(localcloud) 🐱 > update resourcecount domainid=3a5204fc-7280-4318-b13a-8923357462b3 resourcetype=3
{
  "count": 1,
  "resourcecount": [
    {
      "domain": "DPSS",
      "domainid": "3a5204fc-7280-4318-b13a-8923357462b3",
      "domainpath": "ROOT/DPSS",
      "resourcecount": 28,
      "resourcetype": "3",
      "resourcetypename": "snapshot"
    }
  ]
}
```
Taking a snapshot the resourcecount increases from 28 to 29.
```
(localcloud) 🐱 > create vmsnapshot virtualmachineid=0c7d8c55-753b-401d-b719-93284b653122 quiescevm=true name=test
{
  "account": "admin",
  "accountid": "343654c8-dd39-11f0-80ce-405b7f9c291c",
  "cmd": "org.apache.cloudstack.api.command.user.vmsnapshot.CreateVMSnapshotCmd",
  "completed": "2026-03-31T11:53:59+0200",
  "created": "2026-03-31T11:53:57+0200",
  "domainid": "50618dea-dd37-11f0-80ce-405b7f9c291c",
  "domainpath": "ROOT",
  "jobid": "cf4acfc7-d65d-47e0-9681-8b05e0e5a743",
  "jobinstancetype": "VmSnapshot",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 530,
    "errortext": "Failed to create vm snapshot: [VMSnapshot {\"id\":173,\"name\":\"i-4-21-VM_VS_20260331095357\",\"uuid\":\"20189ea2-92db-44fe-8954-db79ccac401a\",\"vmId\":21}] due to: can't handle quiescevm equal true for volume snapshot"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "34368425-dd39-11f0-80ce-405b7f9c291c"
}
🙈 Error: async API failed for job cf4acfc7-d65d-47e0-9681-8b05e0e5a743
(localcloud) 🐱 > update resourcecount domainid=3a5204fc-7280-4318-b13a-8923357462b3 resourcetype=3
{
  "count": 1,
  "resourcecount": [
    {
      "domain": "DPSS",
      "domainid": "3a5204fc-7280-4318-b13a-8923357462b3",
      "domainpath": "ROOT/DPSS",
      "resourcecount": 29,
      "resourcetype": "3",
      "resourcetypename": "snapshot"
    }
  ]
}
```
But even after deleting the snapshot the resource count stays at 29.
```
(localcloud) 🐱 > delete vmsnapshot vmsnapshotid=20189ea2-92db-44fe-8954-db79ccac401a
{
  "success": true
}
(localcloud) 🐱 > update resourcecount domainid=3a5204fc-7280-4318-b13a-8923357462b3 resourcetype=3
{
  "count": 1,
  "resourcecount": [
    {
      "domain": "DPSS",
      "domainid": "3a5204fc-7280-4318-b13a-8923357462b3",
      "domainpath": "ROOT/DPSS",
      "resourcecount": 29,
      "resourcetype": "3",
      "resourcetypename": "snapshot"
    }
  ]
}
```

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR fixes rollback disk snapshots on instance snapshot failure.

Fixes #12927 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java [hunk 1]
```diff
@@ -448,6 +455,7 @@ protected SnapshotInfo createDiskSnapshot(VMSnapshot vmSnapshot, List<SnapshotIn
         vol.addPayload(setPayload(vol, snapshot, quiescevm));
         SnapshotInfo snapshotInfo = snapshotDataFactory.getSnapshot(snapshot.getId(), vol.getDataStore());
         snapshotInfo.addPayload(vol.getpayload());
+        volumeToSnapshotInfoMapForRollback.put(vol.getId(), snapshotInfo);
```
Comment (DaanHoogland) [inline engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: so it might be added twice right? so why the else at line 466?

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java [hunk 2]
```diff
@@ -222,7 +223,7 @@ public VMSnapshot takeVMSnapshot(VMSnapshot vmSnapshot) {
                 }
             }
             if (!result) {
-                for (SnapshotInfo snapshotInfo : forRollback) {
+                for (SnapshotInfo snapshotInfo : volumeToSnapshotInfoMapForRollback.values()) {
```
Comment (DaanHoogland) [inline engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: this seems the only usage, why not a HashSet?

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java (hunk 1 above)
Comment (JoaoJandre) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: The else is so we have the updated snapshot info to delete. Although, I'm not familiar enough with this code to say that it makes a difference. Anyway, if it does make a difference, I would just remove the else to reduce indentation; if it does not make a difference, I would only add the info once on the hashmap.

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java (hunk 2 above)
Comment (sureshanaparti) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: the snapshot info object after take snapshot can be new/updated one, which will be considered during rollback. with HashSet, chances that another snapshot object for the same volume is added if it's new.

Comment (sureshanaparti) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: @DaanHoogland I updated it, back to List

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java [hunk 3]
```diff
@@ -111,7 +111,7 @@ public VMSnapshot takeVMSnapshot(VMSnapshot vmSnapshot) {
         FreezeThawVMAnswer freezeAnswer = null;
         FreezeThawVMCommand thawCmd = null;
         FreezeThawVMAnswer thawAnswer = null;
-        List<SnapshotInfo> forRollback = new ArrayList<>();
+        List<SnapshotInfo> snapshotInfoListForRollback = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (DaanHoogland) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: `snapshotsForRollback` seems appropriate, @sureshanaparti ? (or close/ignore)

[the remark this answers is not in the document]
Comment (sureshanaparti) [reply engine/storage/snapshot/src/main/java/org/apache/cloudstack/storage/vmsnapshot/StorageVMSnapshotStrategy.java]: done

**Comment by sureshanaparti** [comment]
@blueorangutan package
