### PR TITLE
Delete template from storage pool instantly if no volume is using it

### LINKED ISSUE #10688: Deleting template does not remove the template images on primary storages
### problem

When delete a template, ACS will remove the image from secondary storages.
however, the template images are not immediately removed on primary storages even if it is not used by any VMs.

### versions

4.20 +  NFS

I think the issue exists in other ACS versions and storage agonistic

### The steps to reproduce the bug

1. register a template
2. deploy some vms
3. expunge the vms
4. delete the template

now check `template_spool_ref` table to get the path of template image on primary storages
check the files on storage, they are still there

### What to do about it?

More findings:

there are some global settings for template cleanup
- storage.cleanup.enabled (default: true)
- storage.template.cleanup.enabled (default: true)
- storage.cleanup.interval (default: 86400 seconds= 1 day)

the unused templates will be marked as GC in the first round and removed in the next round.
so the templates might be removed in two rounds (2 days with default settings)

since the template has been removed in ACS and it is not used by any VM, we could remove it immediately from primary storages, which will free the storage space as soon as possible.

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR fixes #10688 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

| # | Scenario                                                                 | Action                                                                  | Observed Result                                                                 |
|---|---------------------------------------------------------------------------|-------------------------------------------------------------------------|---------------------------------------------------------------------------------|
| 1 | `template.delete.from.primary.storage` setting toggle                     | Delete template with setting **true** vs **false**                      | Template file deleted only if setting is **true**                                |
| 2 | Instance created from template, then template deleted with **force=true** | Delete template (force) without deleting the instance                   | Template file **not** deleted from Primary Storage                               |
| 3 | Template installed on 2 zones, VMs created and expunged everywhere        | Delete template **without** specifying `zoneId`                         | Template files deleted from **all Primary Storages**                             |
| 4 | Template installed on 2 zones, VMs created and expunged everywhere        | Delete template specifying only `zoneId=zoneA`                          | Template file deleted only on Primary Storages belonging to **zoneA**            |

### CODE REVIEW

**Comment by abh1sar** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/template/TemplateManagerImpl.java [hunk 1]
```diff
@@ -1024,33 +1024,53 @@ public boolean delete(long userId, long templateId, Long zoneId) {
...
             }
         }
-
         return unusedTemplatesInPool;
     }
 
+    @Override
+    public void evictTemplateFromStoragePoolsForZones(Long templateId, List<Long> zoneIds) {
+        List<Long> poolIds = new ArrayList<>();
+        if (zoneIds != null && !zoneIds.isEmpty()) {
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/template/TemplateManagerImpl.java]: CollectionUtils.isNotEmpty ?

**Review by weizhouapache — APPROVED** [review]
code lgtm

thanks @abh1sar

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

File: engine/components-api/src/main/java/com/cloud/template/TemplateManager.java [hunk 2]
```diff
@@ -56,6 +56,13 @@ public interface TemplateManager {
             + "will validate if the provided URL is resolvable during the register of templates/ISOs before persisting them in the database.",
             true);
 
+    ConfigKey<Boolean> TemplateDeleteFromPrimaryStorage = new ConfigKey<Boolean>("Advanced",
```
Comment (harikrishna-patnala) [inline engine/components-api/src/main/java/com/cloud/template/TemplateManager.java:59]: @abh1sar do we really need a global setting for this usecase, I think we can directly delete the template if there is no usage found.

Comment (abh1sar) [reply engine/components-api/src/main/java/com/cloud/template/TemplateManager.java:59]: @harikrishna-patnala I added it as a failsafe or in case someone doesn't care about how faster the space is reclaimed, but doesn't want to risk any kind of data loss. Also in case someone wants to use the setting `storage.template.cleanup.enabled=false` or `storage.cleanup.enabled=false` where the deleted template is never cleaned up.

File: engine/schema/src/main/java/com/cloud/storage/dao/VMTemplatePoolDaoImpl.java [hunk 3]
```diff
@@ -150,6 +150,16 @@ public VMTemplateStoragePoolVO findByPoolTemplate(long poolId, long templateId,
         return findOneIncludingRemovedBy(sc);
     }
 
+    @Override
+    public List<VMTemplateStoragePoolVO> listByPoolIdsAndTemplate(List<Long> poolIds, Long templateId) {
+        SearchCriteria<VMTemplateStoragePoolVO> sc = PoolTemplateSearch.create();
+        if (CollectionUtils.isNotEmpty(poolIds)) {
+            sc.setParameters("pool_id", poolIds.toArray());
+        }
```
[the remark this answers is not in the document]
Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/storage/dao/VMTemplatePoolDaoImpl.java:158]: @abh1sar 
does Copilot's suggestion look good to you ?

[the remark this answers is not in the document]
Comment (abh1sar) [reply engine/schema/src/main/java/com/cloud/storage/dao/VMTemplatePoolDaoImpl.java:158]: @weizhouapache no, the method is supposed to return all template_spool_refs if poolIds is empty.

[the remark this answers is not in the document]
Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/storage/dao/VMTemplatePoolDaoImpl.java:158]: got it, thanks

**Review by vishesh92 — APPROVED** [review]
clgtm. Tested with 1 zone. Works as expected.

File: engine/components-api/src/main/java/com/cloud/template/TemplateManager.java (hunk 2 above)
Comment (weizhouapache) [reply engine/components-api/src/main/java/com/cloud/template/TemplateManager.java:59]: @harikrishna-patnala 
does it look ok to you ?

Comment (harikrishna-patnala) [reply engine/components-api/src/main/java/com/cloud/template/TemplateManager.java:59]: okay @weizhouapache and thanks @abh1sar

**Review by harikrishna-patnala — APPROVED** [review]
code LGTM
