### PR TITLE
VPC: fix private mtu of vpc tier

### LINKED ISSUE #10001: Network uses the default mtu values if public/private mtu are not set
There are two global settings for mtu size
- vr.private.interface.max.mtu
- vr.public.interface.max.mtu

however, when I create a VPC tier without specified mtu, the VPC tier is created with default private mtu (1500) .
It should use the mtu size in the global settings if not set in api parameters of createNetwork api.

Please note:
isolated networks do not have the issue

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.20, the same issue should exist in 4.19 as well.
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #10001

Steps to reproduce the issue
- update global setting for public/private mtu from 1500 to 1450
- create vpc, the public/private mtu is 1450/1450
- create vpc tier

expected result: public/private mtu is 1450/1450
actual result: public/private mtu is 1450/1500

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java [hunk 1]
```diff
@@ -1902,7 +1902,7 @@ protected void mtuCheckForVpcNetwork(Long vpcId, Pair<Integer, Integer> interfac
             }
             s_logger.warn(String.format("VPC public MTU already set at VPC creation phase to: %s. Ignoring public MTU " +
                     "passed during VPC network tier creation ", vpc.getPublicMtu()));
-            interfaceMTUs.set(vpc.getPublicMtu(), privateMtu);
+            interfaceMTUs.set(vpc.getPublicMtu(), interfaceMTUs.second());
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/network/NetworkServiceImpl.java:1905]: I think we can do with some more cleanup in this method. this method is passed a pair of MTUs and a public and a private MTU.

**Review by Pearl1594 — APPROVED** [review]
code LGTM

**Comment by Pearl1594** [comment]
@weizhouapache Could you please address the comment provided? Thanks.

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

File: server/src/main/java/com/cloud/network/NetworkServiceImpl.java (hunk 1 above)
Comment (weizhouapache) [reply server/src/main/java/com/cloud/network/NetworkServiceImpl.java:1905]: @DaanHoogland 
`publicMtu` is the public MTU passed by API
the pair `interfaceMTUs` is the final public/private MTUs to be used

`privateMtu` is the MTU private passed by API, it is not used in this method, I will remove it

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@weizhouapache is this ready for review/test/merge?

**Comment by weizhouapache** [comment]
> @weizhouapache is this ready for review/test/merge?

yes @DaanHoogland

**Review by DaanHoogland — APPROVED** [review]
verified in lab env
