### PR TITLE
Extensions: use home directory of cloud user instead of /var/lib/cloudstack/management/

### LINKED ISSUE #11593: Missing extensions directory after upgrade 4.21.0
### problem

When upgrade ACS from 4.20.1 to 4.21.0, management server fail to restart and compliant a directory is missing.

```
2025-09-05 23:43:14,355 ERROR [o.a.c.h.e.p.ExternalPathPayloadProvisioner] (main:[]) (logid:) Unable to create extensions data directory [/var/lib/cloudstack/management/extensions] java.nio.file.AccessDeniedException: /var/lib/cloudstack
```

after manually create that directory, management will able to start

```
mkdir -p /var/lib/cloudstack/management/extensions 
chown -R cloud:cloud /var/lib/cloudstack
```

### versions

ACS: 4.20.1
OS: OL9 x86_64
hypervisors: KVM
storage: NFS(SharedMountPoint)
network: vxlan

### The steps to reproduce the bug

1. Have 4.20.1 installed
2. yum upgrade cloudstack-management
3. systemctl start cloudstack-management
4. examine /var/log/cloudstack/management/management-server.log

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR should fix #11593 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

File: plugins/hypervisors/external/src/main/java/org/apache/cloudstack/hypervisor/external/provisioner/ExternalPathPayloadProvisioner.java [hunk 1]
```diff
@@ -104,7 +104,7 @@ public class ExternalPathPayloadProvisioner extends ManagerBase implements Exter
     private static final String PROPERTIES_FILE = "server.properties";
     private static final String EXTENSIONS_DEPLOYMENT_MODE_NAME = "extensions.deployment.mode";
     private static final String EXTENSIONS_DIRECTORY_PROD = "/usr/share/cloudstack-management/extensions";
-    private static final String EXTENSIONS_DATA_DIRECTORY_PROD = "/var/lib/cloudstack/management/extensions";
+    private static final String EXTENSIONS_DATA_DIRECTORY_PROD = System.getProperty("user.home") + "/extensions";
     private static final String EXTENSIONS_DIRECTORY_DEV = "extensions";
```
Comment (DaanHoogland) [inline plugins/hypervisors/external/src/main/java/org/apache/cloudstack/hypervisor/external/provisioner/ExternalPathPayloadProvisioner.java]:
```suggestion
    private static final String EXTENSIONS_DIRECTORY = "extensions";
    private static final String EXTENSIONS_DATA_DIRECTORY_PROD = System.getProperty("user.home") + EXTENSIONS_DIRECTORY;
    private static final String EXTENSIONS_DIRECTORY_DEV = EXTENSIONS_DIRECTORY;
```

**Review by DaanHoogland — APPROVED** [review]

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
great, thanks @abh1sar for the testing !

merging
