### PR TITLE
ui: fix considerlasthost for start vm

### LINKED ISSUE #10601: UI: Consider Last Host is ignored
### problem

On starting an instance I disabled the 'Consider Last Host' in the UI , I expected it to send the API call with the parameter considerlasthost=false but nothing was sent. 

### versions

4.19.2

### The steps to reproduce the bug

1. Deploy an instance and stop it
2. Start the instance by deselecting the 'Consider Last Host' in UI.
3. Check the API or logs. 
...

### What to do about it?

Consider Last Host should work in the UI, It works fine with CMK.

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #10601

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

File: ui/src/views/compute/StartVirtualMachine.vue [hunk 1]
```diff
@@ -237,7 +237,7 @@ export default {
           id: this.resource.id
         }
         for (const key in values) {
-          if (values[key]) {
+          if (values[key] || values[key] === false) {
```
Comment (bernardodemarco) [inline ui/src/views/compute/StartVirtualMachine.vue:240]: Couldn't we simply remove this if condition? I don't see how a form's field value could be `null` or `undefined` here

Comment (shwstppr) [reply ui/src/views/compute/StartVirtualMachine.vue:240]: @bernardodemarco It may be there because some fields may have an empty value which we shouldn't pass to the API

Comment (bernardodemarco) [reply ui/src/views/compute/StartVirtualMachine.vue:240]: Okay. Specifically in this form, in which all fields are select components (except for the `considerlasthost`), the UI does not allow the values to be empty.

However, I think that's a great idea to keep the if statement how you proposed, since that we could, in the future, add more fields to the form that can accept empty/nullable values

**Review by bernardodemarco — COMMENTED** [review]
@shwstppr, I think that we should also tackle this bug when starting VMs through group actions. 

I debugged the current behavior of the `AutogenView` component. On this block of code:

https://github.com/apache/cloudstack/blob/6c40a7bebbc4c9d4dd9c96769834ad4b9c6cb6c7/ui/src/views/AutogenView.vue#L1443-L1447

The `paramsList` variable contains the `considerlasthost` parameter as `undefined` and, thus, it is not sent within the API request. To handle that, we could, in the following `groupMap` field:

https://github.com/apache/cloudstack/blob/6c40a7bebbc4c9d4dd9c96769834ad4b9c6cb6c7/ui/src/config/section/compute.js#L116-L124

Check whether `values.considerlasthost` is `undefined`. If so, the `considerlasthost` field could be set as `false`.

---

Edit: The bug when starting VMs through group actions occurs when the form is opened, and the `considerlasthost` field is not changed. If the field is set to `true` and switched back to `false`, then the UI sets the `considerlasthost` parameter correctly to `false`.

**Comment by shwstppr** [comment]
Thanks guys for group action pointers. Will check and update.

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by DaanHoogland — APPROVED** [review]
tested with devtools in qa , parameter is passed
