### PR TITLE
[4.22] Prevent unmanaging or reinstalling a VM if it is part of a CKS cluster

### LINKED ISSUE #12783: CKS cluster goes into alert state when worker node is unmanaged
### problem

CKS cluster goes into alert state 

### versions

ACS 4.22 , KVM hypervisor

### The steps to reproduce the bug

1. Created a K8s issue with 1 controller, and 3 workers

2. Make sure the CKS cluster is in running state 

3. Navigate to one of the worker  instances and unmanaged it 

Image

4. The CKS cluster went into Alert state

Image

5. Delete the CKS Cluster, following error is issued 

"com.cloud.vm.VMInstanceVO.getBackupOfferingId()" because "vm" is null"

Image

logs 

```
2026-03-10 11:39:56,869 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-55:[ctx-53050b87, job-73]) (logid:755e27ea) Unexpected exception while executing org.apache.cloudstack.api.command.user.kubernetes.cluster.DeleteKubernetesClusterCmd java.lang.NullPointerException: Cannot invoke "com.cloud.vm.VMInstanceVO.getBackupOfferingId()" because "vm" is null
        at com.cloud.kubernetes.cluster.KubernetesClusterManagerImpl.checkIfVmsAssociatedWithBackupOffering(KubernetesClusterManagerImpl.java:2018)

```
    
6. Stop the CKS  cluster if the following error is issued

Failed to find all VMs in Kubernetes cluster : 

Image

logs 

```
2026-03-10 11:40:47,436 ERROR [c.c.k.c.a.KubernetesClusterStopWorker] (API-Job-Executor-56:[ctx-37106f8f, job-74, ctx-f1370fcc]) (logid:eeffc52f) Failed to find all VMs in Kubernetes cluster : test

```

 7. Import back the unmanged instance using the api > select the same cks network

https://cloudstack.apache.org/api/apidocs-4.22/apis/importUnmanagedInstance.html

   
8. Add the imported worker node instance back to the CKS cluster 

Image

logs 

```
2026-03-10 12:52:22,913 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-61:[ctx-3eab1e04, job-81]) (logid:fba281a3) Complete async job-81, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":"530","errortext":"Failed to add nodes to cluster ID 1 due to: No valid nodes found to be added to the Kubernetes cluster"}
```

Image

Other related CKS Alert issues 

https://github.com/apache/cloudstack/issues/12641
https://github.com/apache/cloudstack/issues/12633
https://github.com/apache/cloudstack/issues/11581

### What to do about it?

CloudStack should not allow to unmanage an instance if its a part of a cks cluster 

or Cloudstack CKS cluster should support  addition of an unmanaged instance

### LINKED ISSUE #12837: Validate and don't allow the api restoreVirtualMachine for cks clusters
### problem

https://cloudstack.apache.org/api/apidocs-4.22/apis/restoreVirtualMachine.html

### versions

ACS 4.22 

### The steps to reproduce the bug

1. Launch a cks cluster with 2 worker node 

2.  CKS cluster in running state

3. Navigate to the instance > worker node > Restore virtual Machine > select a differnt template 

Image

Image

4. CKS cluster goes into  alert state 

...

### What to do about it?

Cloudstack should not allow a user to reinstall a vm which is part of a cks cluster.

A exception message should be thrown

Similar to the pr 

https://github.com/apache/cloudstack/pull/12800

### PR DESCRIPTION
**Pull request by nvazquez**
### Description

This PR prevents unmanaging or reinstalling a VM if it belongs to a CKS cluster, with a descriptive message

Fixes: #12783 
Fixes: #12837 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java [hunk 1]
```diff
@@ -2376,6 +2381,15 @@ void performUnmanageVMInstancePrechecks(VMInstanceVO vmVO) {
...
                     " as there is an ISO attached. Please detach ISO before unmanaging.");
         }
+
+        if (belongsToCksCluster(vmVO)) {
+            throw new UnsupportedServiceException("Cannot unmanage VM with id = " + vmVO.getUuid() +
+                    " as it belongs to a CKS cluster. Please remove the VM from the CKS cluster before unmanaging.");
+        }
+    }
+
+    private boolean belongsToCksCluster(VMInstanceVO vmVO) {
```
Comment (sureshanaparti) [inline server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java]:
```suggestion
    private boolean vmBelongsToCksCluster(VMInstanceVO vmVO) {
```

or _isVmInCksCluster_

**Review by sureshanaparti — APPROVED** [review]
clgtm

File: server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java (hunk 1 above)
Comment (nvazquez) [reply server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java]: Thanks @sureshanaparti - I renamed it to: `isVmPartOfCKSCluster`

**Comment by nvazquez** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by kiranchavala** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by kiranchavala — COMMENTED** [review]
@nvazquez 

Unable to deploy systemvm's with the pr packages 

Getting the following exceptions 

```
2026-03-16 05:00:29,098 ERROR [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-2:[ctx-1d43103b, job-15992/job-15994, ctx-46eb4f82]) (logid:f4bd0cb7) Invocation exception, caused by: java.lang.NullPointerException: Cannot invoke "com.cloud.hypervisor.HypervisorGuru.implement(com.cloud.vm.VirtualMachineProfile)" because "hvGuru" is null
2026-03-16 05:00:29,098 INFO  [c.c.v.VmWorkJobHandlerProxy] (Work-Job-Executor-2:[ctx-1d43103b, job-15992/job-15994, ctx-46eb4f82]) (logid:f4bd0cb7) Rethrow exception java.lang.NullPointerException: Cannot invoke "com.cloud.hypervisor.HypervisorGuru.implement(com.cloud.vm.VirtualMachineProfile)" because "hvGuru" is null
2026-03-16 05:00:29,098 DEBUG [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-2:[ctx-1d43103b, job-15992/job-15994]) (logid:f4bd0cb7) Done with run of VM work job: com.cloud.vm.VmWorkStart for VM 4, job origin: 15992
2026-03-16 05:00:29,098 ERROR [c.c.v.VmWorkJobDispatcher] (Work-Job-Executor-2:[ctx-1d43103b, job-15992/job-15994]) (logid:f4bd0cb7) Unable to complete AsyncJob {"accountId":1,"cmd":"com.cloud.vm.VmWorkStart","cmdInfo":"rO0ABXNyABhjb20uY2xvdWQudm0uVm1Xb3JrU3RhcnR9cMGsvxz73gIAC0oABGRjSWRMAAZhdm9pZHN0ADBMY29tL2Nsb3VkL2RlcGxveS9EZXBsb3ltZW50UGxhbm5lciRFeGNsdWRlTGlzdDtMAAljbHVzdGVySWR0ABBMamF2YS9sYW5nL0xvbmc7TAAGaG9zdElkcQB-AAJMAAtqb3VybmFsTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAEXBoeXNpY2FsTmV0d29ya0lkcQB-AAJMAAdwbGFubmVycQB-AANMAAVwb2RJZHEAfgACTAAGcG9vbElkcQB-AAJMAAlyYXdQYXJhbXN0AA9MamF2YS91dGlsL01hcDtMAA1yZXNlcnZhdGlvbklkcQB-AAN4cgATY29tLmNsb3VkLnZtLlZtV29ya5-ZtlbwJWdrAgAESgAJYWNjb3VudElkSgAGdXNlcklkSgAEdm1JZEwAC2hhbmRsZXJOYW1lcQB-AAN4cAAAAAAAAAABAAAAAAAAAAEAAAAAAAAABHQAGVZpcnR1YWxNYWNoaW5lTWFuYWdlckltcGwAAAAAAAAAAHBwcHBwcHBwcHA","cmdVersion":0,"completeMsid":null,"created":"Mon Mar 16 05:00:23 UTC 2026","id":15994,"initMsid":32985667600753,"instanceId":null,"instanceType":null,"lastPolled":null,"lastUpdated":null,"processStatus":0,"removed":null,"result":null,"resultCode":0,"status":"IN_PROGRESS","userId":1,"uuid":"509eb5a5-24e5-4bc3-b0e2-71b170c42f2f"}, job origin: 15992 java.lang.NullPointerException: Cannot invoke "com.cloud.hypervisor.HypervisorGuru.implement(com.cloud.vm.VirtualMachineProfile)" because "hvGuru" is null

2026-03-16 05:00:29,124 WARN  [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:[ctx-c3c3424a]) (logid:6d3a850d) Unable to allocate console proxy standby capacity for zone [Zone {"id": "1", "name": "ref-trl-11326-k-Mol8-kiran-chavala", "uuid": "ebe31a7b-1e2c-4891-b408-2133ce560d8d"}] due to [null]. java.lang.NullPointerException


```

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test keepEnv

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test keepEnv

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by kiranchavala** [comment]
@blueorangutan test

**Review by kiranchavala — COMMENTED** [review]
@nvazquez Please provide proper error message when a end user unamanges a instance which is a part of a cks cluster 


Image

```
(localcloud) 🐱 > unmanage virtualmachine id=0aa8147a-1002-49e9-bcc6-5af4b35f05d2
{
  "account": "admin",
  "accountid": "7f089b6c-21c6-11f1-92f3-1e004e000380",
  "cmd": "org.apache.cloudstack.api.command.admin.vm.UnmanageVMInstanceCmd",
  "completed": "2026-03-17T07:33:20+0000",
  "created": "2026-03-17T07:33:20+0000",
  "domainid": "28ca91c8-21c6-11f1-92f3-1e004e000380",
  "domainpath": "ROOT",
  "jobid": "59a56976-d640-419b-b135-86706c5fee19",
  "jobinstanceid": "0aa8147a-1002-49e9-bcc6-5af4b35f05d2",
  "jobinstancetype": "VirtualMachine",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 530,
    "errortext": "No bean named 'com.cloud.kubernetes.cluster.KubernetesServiceHelper' available"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "7f09fbfa-21c6-11f1-92f3-1e004e000380"
}
🙈 Error: async API failed for job 59a56976-d640-419b-b135-86706c5fee19

```


The message can be similar to the one when a end user tries to destroy a machine which is part of the cks cluster 

Image

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM

1. Deploy a cks cluster 

2. Navigate to instance view > on the cks node tried to execute the following api 

https://cloudstack.apache.org/api/apidocs-4.22/apis/restoreVirtualMachine.html
https://cloudstack.apache.org/api/apidocs-4.22/apis/unmanageVirtualMachine.html

Exception thrown

Image

Image
