### PR TITLE
Fix cpuallocated value in findHostsForMIgration api

### LINKED ISSUE #4221: cpuallocated value shows 0 all the time
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

Any type of zone

##### OS / ENVIRONMENT

Any OS

##### SUMMARY

findHostsForMIgration api always returns 0 for cpuallocated field
Also there is inconsistency between memoryallocated field returned by listHosts api and findHostsForMigration api

##### STEPS TO REPRODUCE

~~~
(local) mgt01 > find hostsformigration virtualmachineid=91-aac-477a-b36e-ae54f filter=cpuallocated,memoryallocated
{
  "count": 3,
  "host": [
    {
      "cpuallocated": "0%", <<<<<<<<<<<<<<<<<<<<<<<<
      "memoryallocated": "40.47%"
    },
    {
      "cpuallocated": "0%",
      "memoryallocated": "18.39%"
    }
  ]
}


(local) mgt01 > list hosts virtualmachineid=36b61-acac-477a-b36e-a2f54f filter=cpuallocated,memoryallocated
{
  "count": 3,
  "host": [
    {
      "cpuallocated": "5.68%",
      "memoryallocated": 2952790016 <<<<<<<<<<<<<<<<<<
    },
    {
      "cpuallocated": "3.41%",
      "memoryallocated": 1342177280
    }
  ]
}
~~~

##### EXPECTED RESULTS

~~~
findHostsFormigration should return proper value all the time
Also listHosts and findHostsForMigration should return either absolute or a percentage value
~~~

##### ACTUAL RESULTS

~~~
findHostsFormigration returns 0 all the time
listHosts command returns the absolute value for memoryallocated whereas findHostsForMigration returns percentage
~~~

@rafaelweingartner @GabrielBrascher  @andrijapanicsb @rhtyd @PaulAngus @svenvogel  any inputs on this?

### PR DESCRIPTION
**Pull request by ravening**
## Description

Fixes #4221 

The findHostsForMigration api displays 0% always for
cpuallocated field which is wrong

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested from cloudmonkey api

Before the fix
```
local) > find hostsformigration virtualmachineid=01f155-fffc-493f-95b8-85a76414 filter=cpuallocated,suitableformigration
{
  "count": 221,
  "host": [
    {
      "cpuallocated": "0%",
      "suitableformigration": true
    },
    {
      "cpuallocated": "0%",
      "suitableformigration": true
    },
    {
      "cpuallocated": "0%",
      "suitableformigration": true
    },
```

After the fix

```
(local) mgt01 > list hosts  virtualmachineid=95b4270f-1354-4703-99cb-a769400b2d30 filter=cpuallocated,suitableformigration,name
{
  "count": 3,
  "host": [
    {
      "cpuallocated": "2.27%",
      "name": "node32",
      "suitableformigration": true
    },
    {
      "cpuallocated": "1.14%",
      "name": "node33",
      "suitableformigration": true
    }
  ]
}
```

### CODE REVIEW

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java [hunk 1]
```diff
@@ -330,10 +330,10 @@ public HostForMigrationResponse newHostForMigrationResponse(HostJoinVO host, Enu
 
                 hostResponse.setHypervisorVersion(host.getHypervisorVersion());
 
-                Float cpuWithOverprovisioning = new Float(host.getCpus() * host.getSpeed() * ApiDBUtils.getCpuOverprovisioningFactor(host.getClusterId()));
-                String cpuAlloc = decimalFormat.format(((float)cpu / cpuWithOverprovisioning * 100f)).toString() + "%";
+                float cpuWithOverprovisioning = new Float(host.getCpus() * host.getSpeed() * ApiDBUtils.getCpuOverprovisioningFactor(host.getClusterId()));
+                String cpuAlloc = decimalFormat.format(((float)cpu / cpuWithOverprovisioning * 100f)) + "%";
```
Comment (GabrielBrascher) [inline server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java:334]: I see `100f` a couple of times on the code, there is also `100.0f`.

What do you think of extracting these _magic_ `100f`/`100.0f` into a constant?

Another approach that would be even nicer would be to have these pieces extracted to a method like `calculateResourceAllocatedPercentage`, and add a few unit test case methods.

```
public String calculateResourceAllocatedPercentage(float resource, float resourceWithOverprovisioning) {
	    return decimalFormat.format(((float)resource / resourceWithOverprovisioning * 100f)) + **"%"**
}
```

Comment (ravening) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java]: @GabrielBrascher I made the changes. Also can you look into the issue #4221 ?

Comment (GabrielBrascher) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java]: @ravening thanks **+1** :)

Can you please take a look at line [314](https://github.com/apache/cloudstack/blob/7febf17aa8c8ba6403deeb160a4af5f6dda5111c/server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java#L314), I think that it could also benefit from the created method `calculateResourceAllocatedPercentage`.

Comment (ravening) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java]: @GabrielBrascher I didn't make changes in line 314 because it has different behavior compared to line 165.
I have mentioned the same in issue #4221 also. list hosts api returns absolute value where as findhostsformigration returns percentage. If we decided what to return then I can make changes in these two places also

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by andrijapanicsb** [comment]
(tests failed, re-run after the weekend due to weekend maintenance)

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by ravening** [comment]
> LGTM, did not manually test it

@rhtyd @DaanHoogland its not yet ready for merge. Im waiting for @GabrielBrascher reply for my question.
If you can also reply it then it will be helpful

**Comment by DaanHoogland** [comment]
@ravening if your question is whether a percentage or an absolute number is to be returned i would really not care. I don't think that the two API have to return the same type of value. I do think that the difference should be clear from the name of the parameter and hence both could be returned if so desired.
if that was not your question please correct me.

File: server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java (hunk 1 above)
Comment (GabrielBrascher) [reply server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java]: @ravening sorry for the delay. I think that I was clear about my point.

- the method that you extract [L464](https://github.com/apache/cloudstack/blob/7febf17aa8c8ba6403deeb160a4af5f6dda5111c/server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java#L464):
`decimalFormat.format(((float)resource / resourceWithOverProvision * 100.0f)) + "%"`

- line [314](https://github.com/apache/cloudstack/blob/7febf17aa8c8ba6403deeb160a4af5f6dda5111c/server/src/main/java/com/cloud/api/query/dao/HostJoinDaoImpl.java#L314) that I mentioned:
`decimalFormat.format((float) mem / memWithOverprovisioning * 100.0f) +"%"`

That is why I thought that it could also benefit from `calculateResourceAllocatedPercentage`.

**Comment by GabrielBrascher** [comment]
@DaanHoogland @ravening I am good with the code as it is, I just saw that maybe the method could be also used in the other context considering how similar those lines are.

Note that even `DecimalFormat decimalFormat = new DecimalFormat("#.##");` is duplicated and used on the same way for `cpuAllocated` and `memoryAllocated`. However I don't want to stall this PR with that observation.

**Comment by rhtyd** [comment]
@ravening sorry I missed your comment, and merged based on @GabrielBrascher 's `I am good with the code as it is`. Do you need to do more work on this PR, should we revert? cc @DaanHoogland

**Comment by ravening** [comment]
> @ravening sorry I missed your comment, and merged based on @GabrielBrascher 's `I am good with the code as it is`. Do you need to do more work on this PR, should we revert? cc @DaanHoogland 

Since it's ok for them that two functions returns different value, it's fine with me as well

**Comment by rhtyd** [comment]
Alright I'll not revert it, thnx for replying.
