### PR TITLE
Randomize managed volume copy host

### LINKED ISSUE #5788: Parallel volume migrations on KVM are processed on same host
### SUMMARY

It seems while attempting multiple volume migrations, the same KVM agent is always selected. This severely limits the scalability of doing bulk migrations as we are limited to serial processing at the CopyCommand and network limitations of a single hypervisor host.

### STEPS TO REPRODUCE

Migrate multiple volumes simultaneously from one cluster to another. Observe which hypervisor is selected to execute these and whether they occur in parallel or block on each other.

### PR DESCRIPTION
**Pull request by mlsorensen**
* Managed volume copy was always returning first host that could see storage pools

* Fix null value in logging for ScaleIOPrimaryDataStoreDriver due to if/else logic error

Signed-off-by: Marcus Sorensen <mls@apple.com>

### Description

This PR fixes #5788 

 It shuffles the list of valid host candidates that are used for processing volume migrations.  

It also fixes a logic error in debug logging that caused 'null' to be printed. Originally concatenating a static string with potentially null value and then testing to see if the result is null, which would never be true.

A more ideal solution might be to track the jobs on each host and attempt to balance the load according to how busy each host is.  This was investigated and there's currently no obvious way to look up job assignments to hosts via the DB, the Commands sent to Agents are kept live in memory via the AgentAttache.  The ideal solution would be a much larger feature to coordinate Command assignments across the management server cluster, and possibly need improved agent comms to provide live status of Command progress.

I additionally spent some time looking into how to isolate and unit test `findUpAndEnabledHostWithAccessToStoragePools()`. Currently it would require mocking three Daos, the DataStoreProviderManager, a DataStoreProvider, and a DataStoreDriver.  It's possible to write a test for this, however I was concerned that the unit test would be coding implementation across three methods into the test. These mocked Daos exist up to three methods deep - if the implementation of any of these methods changes then the test needs to be rewritten to code in the new implementation.  I wasn't sure this was the right thing to do just to add a simple one-line shuffle but I'm happy to go that route if needed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### How Has This Been Tested?
Have run this code against a live environment and tested volume migration.

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
thanks for the PR @mlsorensen , code LGTM

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
Hi @mlsorensen I think, this is good to go in 4.16.1. Can you rebase with 4.16 branch. Thanks.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by mlsorensen** [comment]
> Hi @mlsorensen I think, this is good to go in 4.16.1. Can you rebase with 4.16 branch. Thanks.

Done. Do I need a separate PR for main or will this get into main?

**Comment by sureshanaparti** [comment]
> > Hi @mlsorensen I think, this is good to go in 4.16.1. Can you rebase with 4.16 branch. Thanks.
> 
> Done. Do I need a separate PR for main or will this get into main?

Thanks @mlsorensen , No need of separate PR for main, this will be forward merged to main.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java [hunk 1]
```diff
@@ -629,7 +629,8 @@ public void copyAsync(DataObject srcData, DataObject destData, Host destHost, As
 
     private Answer copyTemplateToVolume(DataObject srcData, DataObject destData, Host destHost) {
         // Copy PowerFlex/ScaleIO template to volume
-        LOGGER.debug("Initiating copy from PowerFlex template volume on host " + destHost != null ? destHost.getId() : "");
+        String debugMessage = "Initiating copy from PowerFlex template volume on host ";
+        LOGGER.debug(destHost != null ? debugMessage + destHost.getId() : debugMessage);
```
Comment (GutoVeronezi) [inline plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java:633]: We could use `String.format` here:

```suggestion
        LOGGER.debug(String.format("Initiating copy from PowerFlex template volume on host %s", destHost != null ? destHost.getId() : ""));
        
```

File: plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java [hunk 2]
```diff
@@ -648,7 +649,8 @@ private Answer copyTemplateToVolume(DataObject srcData, DataObject destData, Hos
 
     private Answer copyVolume(DataObject srcData, DataObject destData, Host destHost) {
         // Copy PowerFlex/ScaleIO volume
-        LOGGER.debug("Initiating copy from PowerFlex volume on host " + destHost != null ? destHost.getId() : "");
+        String debugMessage = "Initiating copy from PowerFlex volume on host ";
+        LOGGER.debug(destHost != null ? debugMessage + destHost.getId() : debugMessage);
```
Comment (GutoVeronezi) [inline plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java:653]: We also could use `String.format` here.

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java [hunk 3]
```diff
@@ -2136,6 +2136,7 @@ public Host findUpAndEnabledHostWithAccessToStoragePools(List<Long> poolIds) {
         if (hostIds.isEmpty()) {
             return null;
         }
+        Collections.shuffle(hostIds);
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/storage/StorageManagerImpl.java:2139]: I think we could add some log to this method, about which host was selected (or not).

Comment (mlsorensen) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:2139]: There's logging elsewhere, where the returned value is used.

File: plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java (hunk 1 above)
Comment (mlsorensen) [reply plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java]: Good call!

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java [hunk 4]
```diff
@@ -629,7 +629,7 @@ public void copyAsync(DataObject srcData, DataObject destData, Host destHost, As
 
     private Answer copyTemplateToVolume(DataObject srcData, DataObject destData, Host destHost) {
         // Copy PowerFlex/ScaleIO template to volume
-        LOGGER.debug("Initiating copy from PowerFlex template volume on host " + destHost != null ? destHost.getId() : "");
+        LOGGER.debug(String.format("Initiating copy from PowerFlex template volume on host %s", destHost != null ? destHost.getId() : ""));
```
Comment (DaanHoogland) [inline plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java:632]:
```suggestion
        LOGGER.debug(String.format("Initiating copy from PowerFlex template volume on host %s", destHost != null ? destHost.getId() : "<unknown>"));
```

File: plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java [hunk 5]
```diff
@@ -648,7 +648,7 @@ private Answer copyTemplateToVolume(DataObject srcData, DataObject destData, Hos
 
     private Answer copyVolume(DataObject srcData, DataObject destData, Host destHost) {
         // Copy PowerFlex/ScaleIO volume
-        LOGGER.debug("Initiating copy from PowerFlex volume on host " + destHost != null ? destHost.getId() : "");
+        LOGGER.debug(String.format("Initiating copy from PowerFlex template volume on host %s", destHost != null ? destHost.getId() : ""));
```
Comment (DaanHoogland) [inline plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java:651]: same here

**Review by DaanHoogland — APPROVED** [review]
clgtm (none blocking suggestion added for the log message)

File: plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java (hunk 4 above)
Comment (mlsorensen) [reply plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java:632]: Sure, why not?

Comment (mlsorensen) [reply plugins/storage/volume/scaleio/src/main/java/org/apache/cloudstack/storage/datastore/driver/ScaleIOPrimaryDataStoreDriver.java:632]: Implementing this. Going to use "not specified" @DaanHoogland since that sounds less like an error. There is code later to resolve a destination host if this is not specified.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test keepEnv

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code LGTM !

**Comment by sureshanaparti** [comment]
@blueorangutan test keepEnv

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java (hunk 3 above)
Comment (GabrielBrascher) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:2139]: I might be wrong on this one, but I think that there are not many logs regarding the chosen host to migrate.
Call hierarchy that I've taken a quick check does not present logs. Assuming your comment, this would be logged later on in the call hierarchy ( I haven't checked all the way). Even if it is, you can see that many exceptions can be thrown not too late after the host ID is retrieved.
```
> StorageManagerImpl.findUpAndEnabledHostWithAccessToStoragePools(List<Long>)  (com.cloud.storage)
    > VolumeServiceImpl.copyManagedVolume(VolumeInfo, DataStore)  (org.apache.cloudstack.storage.volume)
        > VolumeServiceImpl.copyVolume(VolumeInfo, DataStore)  (org.apache.cloudstack.storage.volume)
            > VolumeOrchestrator.copyVolumeFromSecToPrimary(VolumeInfo, VirtualMachine, VirtualMachineTemplate, DataCenter, Pod, Long, ServiceOffering, ...)  (org.apache.cloudstack.engine.orchestration)
            ...
            > VolumeOrchestrator.migrateVolume(Volume, StoragePool)  (org.apache.cloudstack.engine.orchestration)
            ...
            > VolumeApiServiceImpl.orchestrateExtractVolume(long, long)  (com.cloud.storage)
            ...
```

Additionally, the `canHostAccessStoragePools` called inside the `findUpAndEnabledHostWithAccessToStoragePools` can return false. If the host cannot access, not much is logged as well.

Please, let us know in case we are missing something here.

**Review by GabrielBrascher — COMMENTED** [review]
Thanks for the PR, @mlsorensen.
Overall looks good, I just added a comment related to the @GutoVeronezi's log suggestion.

I particularly struggle sometimes to debug CloudStack issues due to the lack of information in the logs and it could be that this flow is one of these cases. I am not sure though, so I would need to double-check on this one.

I appreciate any feedback regarding it.

File: server/src/main/java/com/cloud/storage/StorageManagerImpl.java (hunk 3 above)
Comment (rohityadavcloud) [reply server/src/main/java/com/cloud/storage/StorageManagerImpl.java:2139]: The logging is not of the randomised list but the selected host is logged by the deployment planner and startvm cmd.

**Review by GabrielBrascher — APPROVED** [review]
Code LGTM
