### PR TITLE
vmware: delete snapshot disk after backup to secondary storage

### LINKED ISSUE #5334: Vmware: Snapshot are not removed from the primary storage after backup to secondary storage
Vmware: Snapshot are not removed from the primary storage after backup to secondary storage

Steps to reproduce:
- Create a VM and take its root disk's volume snapshot
- Monitor the snapshot operation in ACS and vSphere client
- Notice that worker VM is removed but its vmdk file is left in the worker VM's directory on primary storage

In code, we observe that between 4.15.0 and 4.15.1 there are changes in how volume snapshots are handled where after backup the disks are detached before destroying the worker VM leading to delete VM and its related files (vmx, logs etc) on the primary storage but not its vmdk.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

### PR DESCRIPTION
**Pull request by rhtyd**
Currently, when volume snapshots are taken the server creates a clone VM with the specific volume. This VM exports the volume as snapshot on the secondary store for backup. After export current code detaches volume for the cloned VM and destroys is which leaves the clone VM folder with volume VMDK inside.
This change removes code that detaches volume for the clone VM and destroys it along with its volumes.

Fixes #5334 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### How Has This Been Tested?
- Took snapshot for - a) a VM disk b) a detached data disk
- Verified on the primary store through vCenter no leftover cloned VM folder with a VMDK remain after the operation
- Created template from a volume
- Verified on the primary store through vCenter no leftover cloned VM folder with a VMDK remain after the operation

**Test video:**
[Test](https://www.youtube.com/watch?v=TlAUu-puZmQ)

### CODE REVIEW

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java [hunk 1]
```diff
@@ -2025,7 +2025,6 @@ public Answer backupSnapshot(CopyCommand cmd) {
                 try {
                     if (workerVm != null) {
                         // detach volume and destroy worker vm
-                        workerVm.detachAllDisks();
```
Comment (rhtyd) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:2028]: @harikrishna-patnala can you check if per the new code/manager, we should detach the worker VM's disks after the backup of snapshot to secondary storage passes?
cc @nvazquez @sureshanaparti

**Comment by nvazquez** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@harikrishna-patnala pl carry on any further fixing, changes around the bug, treat this as a proof of concept fix.

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java (hunk 1 above)
Comment (harikrishna-patnala) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:2028]: verified the issue and is reproducible. We need to delete the cloned VM completely including disks, not the worker VM (worker VM has the actual disk attached to it). Also there is another place to fix. I'll fix and update this PR. Thanks @rhtyd for drafting this PR.

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java [hunk 2]
```diff
@@ -1241,6 +1241,7 @@ private void postCreatePrivateTemplate(String installFullPath, long templateId,
             ManagedObjectReference morPool = hyperHost.getHyperHostOwnerResourcePool();
             vmMo.createFullCloneWithSpecificDisk(templateUniqueName, dcMo.getVmFolder(), morPool, VmwareHelper.getDiskDeviceDatastore(volumeDeviceInfo.first()), volumeDeviceInfo);
             clonedVm = dcMo.findVm(templateUniqueName);
+            s_logger.debug(String.format("Cloned VM: %s as %s", vmMo.getName(), clonedVm.getName()));
```
Comment (sureshanaparti) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:1244]: @shwstppr can you move this log before this return stmt (in _createFullCloneWithSpecificDisk() @ VirtualMachineMO_):

https://github.com/apache/cloudstack/blob/04738d7775fac382250932f44c7e2cb44a54617c/vmware-base/src/main/java/com/cloud/hypervisor/vmware/mo/VirtualMachineMO.java#L782

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java [hunk 3]
```diff
@@ -3764,24 +3766,24 @@ private Long restoreVolumeFromSecStorage(VmwareHypervisorHost hyperHost, Datasto
             throw new Exception(msg);
         }
 
-        VirtualMachineMO clonedVm = null;
+        VirtualMachineMO workerVm = null;
```
Comment (sureshanaparti) [inline plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:3769]:
```suggestion
        VirtualMachineMO importedVm = null;
```

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java (hunk 2 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java]: Done

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java (hunk 3 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:3755]: I feel `workerVm` suits more here as we use the VM just to import the OVF created for volume that is to be restored from sec store.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-65u2

**Comment by rhtyd** [comment]
Ping @harikrishna-patnala @sureshanaparti do we keep this or close this in favour of some other PR?

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by rhtyd** [comment]
Lgtm, thanks for picking up the PR @shwstppr
Failures not related to this PR.
@sureshanaparti @harikrishna-patnala are you lgtm on changes, do we need it further testing. Or additional testing than you've done @shwstppr?

**Comment by rhtyd** [comment]
@shwstppr can you resolve conflicts?

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java (hunk 3 above)
Comment (sureshanaparti) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:3755]: @shwstppr If this is a worker VM, please tag it accordingly so that it can be tracked (when not destroyed, in failed scenarios) and cleaned up when worker vms cleanup is enabled.

**Comment by sureshanaparti** [comment]
> Lgtm, thanks for picking up the PR @shwstppr
> Failures not related to this PR.
> @sureshanaparti @harikrishna-patnala are you lgtm on changes, do we need it further testing. Or additional testing than you've done @shwstppr?

@rhtyd  this PR should cover tests for create volume snapshot and create template from snapshot.

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java (hunk 3 above)
Comment (shwstppr) [reply plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageProcessor.java:3743]: Done

**Review by sureshanaparti — APPROVED** [review]
code LGTM

**Comment by rhtyd** [comment]
@blueorangutan test centos7 vmware-67u3

**Review by nvazquez — APPROVED** [review]
