### PR TITLE
api: Warn if query parameters have multiple values

### LINKED ISSUE #5007: Duplicate query string parameters
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

API

##### CLOUDSTACK VERSION
4.15+ (Maybe below)

##### SUMMARY

When duplicate query parameters are passed with the same key but different values, ACS parses only the last occurrence.
Eg: keyword=rick&keyword=basic
It returns values matching basic

##### EXPECTED RESULTS

A possible error thrown for duplicate query params

##### ACTUAL RESULTS

http://primate-qa.cloudstack.cloud:8080/client/api/?listall=true&response=json&command=listVirtualMachines&details=min&keyword=rick&keyword=basic

Returns the VMs with name basic

http://primate-qa.cloudstack.cloud:8080/client/api/?listall=true&response=json&command=listVirtualMachines&details=min&keyword=basic&keyword=rick

Returns the VMs with name rick

### PR DESCRIPTION
**Pull request by davidjumani**
### Description

Fixes #5007 

When duplicate query parameters are passed with the same key but different values, ACS parses only the last occurrence.
Eg: keyword=rick&keyword=basic
It returns values matching basic

This PR fixes it so it throws an error when multiple values for the same key is sent

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

```
http://localhost:8080/client/api/?command=listVirtualMachines&keyword=rick&keyword=basic

WARN  [c.c.a.ApiServlet] (qtp875678495-281:ctx-f7a451f1) (logid:742779bd) Query parameter 'keyword' has multiple values [rick, basic]

```

### CODE REVIEW

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/api/ApiServer.java [hunk 1]
```diff
@@ -456,7 +456,11 @@ public void handle(final HttpRequest request, final HttpResponse response, final
                         responseType = param.getValue();
                         continue;
                     }
-                    parameterMap.put(param.getName(), new String[]{param.getValue()});
+                    if(parameterMap.putIfAbsent(param.getName(), new String[]{param.getValue()}) != null) {
+                        String message = String.format("Query parameter '%s' has multiple values", param.getName());
+                        s_logger.error(message);
+                        throw new ServerApiException(ApiErrorCode.MALFORMED_PARAMETER_ERROR, message);
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/ApiServer.java:462]: this is a repeating bit (also happening in ApuServlet) maybe we can move (parts of) it to a common utility?

**Review by DaanHoogland — APPROVED** [review]

**Comment by GutoVeronezi** [comment]
@davidjumani although you link the issue, could you improve the description of this PR with more context?

**Comment by rhtyd** [comment]
@davidjumani I'm not sure if it may cause any regression, since we're tight for a RC this or early next week, I'm moving the milestone.

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
this might cause backwards compatibility issue. I suggest to hold on 
cc @nvazquez @DaanHoogland @davidjumani

**Comment by DaanHoogland** [comment]
> this might cause backwards compatibility issue. I suggest to hold on cc @nvazquez @DaanHoogland @davidjumani

what kind of issues, @weizhouapache ?

**Comment by weizhouapache** [comment]
> > this might cause backwards compatibility issue. I suggest to hold on cc @nvazquez @DaanHoogland @davidjumani
> 
> what kind of issues, @weizhouapache ?

@DaanHoogland 
I think we should allow duplicated query parameters. and display a warning not throw an error if possible.
some users might pass duplicated parameters in scripts and etc, it worked in the past, but with this PR it won't work any more.

**Comment by davidjumani** [comment]
@weizhouapache I've updated it to a warning and to not throw an error

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by nvazquez** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/api/ApiServlet.java [hunk 2]
```diff
@@ -136,6 +136,16 @@ public void run() {
         });
     }
 
+    private void ensureSingleQueryParameterValue(Map<String, String[]> params) {
```
Comment (nvazquez) [inline server/src/main/java/com/cloud/api/ApiServlet.java:139]: Can we rename this method since we are not ensuring, but simply warning about it?

File: server/src/main/java/com/cloud/api/ApiServlet.java [hunk 3]
```diff
@@ -136,6 +136,16 @@ public void run() {
...
+        params.forEach((k, v) -> {
+            if (v.length > 1) {
+                String message = String.format("Query parameter '%s' has multiple values %s", k, Arrays.toString(v));
+                s_logger.warn(message);
```
Comment (nvazquez) [inline server/src/main/java/com/cloud/api/ApiServlet.java:143]: Should we also advise passing a single value per parameter on both messages?

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by davidjumani** [comment]
Smoke tests won't be needed as they passed the previous time and only cosmetic changes were made

**Comment by nvazquez** [comment]
@davidjumani I've manually tested and looks good, I have some minor improvement request:

If passing 2 values for a parameter we use the last, however if I attempt the same on cmk, cmk only passes the first parameter. Can we change the value used to be the first instead of the last so they are consistent?

File: server/src/main/java/com/cloud/api/ApiServer.java [hunk 4]
```diff
@@ -464,7 +464,11 @@ public void handle(final HttpRequest request, final HttpResponse response, final
                         responseType = param.getValue();
                         continue;
                     }
-                    parameterMap.put(param.getName(), new String[]{param.getValue()});
+                    if(parameterMap.putIfAbsent(param.getName(), new String[]{param.getValue()}) != null) {
+                        String message = String.format("Query parameter '%s' has multiple values [%s, %s]. Only the last value will be respected." +
+                            "It is advised to pass only a single parameter", param.getName(), param.getValue(), parameterMap.get(param.getName()));
+                        s_logger.warn(message);
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/ApiServer.java:470]: is there a joint `ApiServer`/`ApiServlet` Utility to put this warning message in, instead of copying the exact same text?
Alternatively can we change the text to indicate where/why we object to the duplicate parameter?

**Comment by davidjumani** [comment]
> @davidjumani I've manually tested and looks good, I have some minor improvement request:
> 
> If passing multiples values for a parameter we use the last, however if I attempt the same on cmk, cmk only passes the first parameter. Can we change the value used to be the first instead of the last so they are consistent?

This is a cmk specific implementation. If an API is called via a browser or tool which simply creates / forwards the requests the last value is respected

**Comment by nvazquez** [comment]
@davidjumani yes, tested that - proposed to use the first value instead of the last when there are multiple values passed on the request
