### PR TITLE
server: allow user to list available IPs on shared networks

### LINKED ISSUE #7817: Allow users to see free IPs in a shared network
In an isolated network or VPC network, as a domain admin or normal user account I can list free public IPs and select/specificy IP address for my use. However, I can't list free IPs in a shared network for use to deploy VMs or while changing IPs. The error also aren't clear in the UI as a normal user account.

Such a feature would be useful for CAPC to help orchestrate and pick an IP for an instance before deploying it; also for end users to specify/select one of the available free IP from the range. It may be worth adding a global setting if we think there is any security risk (with the setting enabled by default to allow listing of free IPs; and restrictive users can tune/toggle the default behaviour).

##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
API, shared network
~~~

##### CLOUDSTACK VERSION

~~~
4.18+
~~~

##### CONFIGURATION

Adv zone with shared network

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This fixes #7817

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

- deploy vm with specific IP
- change nic IP address to specific IP
- add specific IP as secondary IP

### CODE REVIEW

File: engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java [hunk 1]
```diff
@@ -56,6 +56,10 @@ public interface IpAddressManager {
             "Set placement of vrouter ips in redundant mode in vpc tiers, this can be 3 value: `first` to use first ips in tiers, `last` to use last ips in tiers and `random` to take random ips in tiers.",
             true, ConfigKey.Scope.Account, null, null, null, null, null, ConfigKey.Kind.Select, "first,last,random");
 
+    ConfigKey<Boolean> AllowUserListAvailableIpsOnSharedNetwork = new ConfigKey<Boolean>("Advanced", Boolean.class, "allow.user.list.available.ips.on.shared.network", "false",
```
Comment (rohityadavcloud) [inline engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java:59]: Could this be setup to true by default; it's because users can already see public IPs say in an isolated network or VPC. Only stricter env can disable it.

**Review by rohityadavcloud — APPROVED** [review]
LGTM - but needs testing

File: engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java (hunk 1 above)
Comment (rohityadavcloud) [reply engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java:59]: Also worth testing in the UI -> that users can select shared network IP when adding NIC for example, or deploy a VM? cc @kiranchavala

Comment (weizhouapache) [reply engine/components-api/src/main/java/com/cloud/network/IpAddressManager.java:59]: @rohityadavcloud 
some cloud providers might dislike it (as `true`) , for security reasons.

the UI changes requires some other changes, as normal users cannot list the global setting . we need to add it as a capability of the platform.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@weizhouapache have you tested, if say once a user lists and find a free IP address - does deployVM and add nic to network APIs honour user-supplied public IP address?

**Comment by weizhouapache** [comment]
> @weizhouapache have you tested, if say once a user lists and find a free IP address - does deployVM and add nic to network APIs honour user-supplied public IP address?

@rohityadavcloud 
As I remember, it worked before. I will confirm it.

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
> > @weizhouapache have you tested, if say once a user lists and find a free IP address - does deployVM and add nic to network APIs honour user-supplied public IP address?
> 
> @rohityadavcloud As I remember, it worked before. I will confirm it.

@rohityadavcloud 
tested the following action with specified IP, all work well
- deploy vm with specific IP
- change nic IP address to specific IP
- add specific IP as secondary IP

**Comment by rohityadavcloud** [comment]
Excellent thanks @weizhouapache let's go ahead and merge this once it meets enought reviews; cc @DaanHoogland

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java [hunk 2]
```diff
@@ -2475,7 +2476,20 @@ public Pair<List<? extends IpAddress>, Integer> searchForIPAddresses(final ListP
...
+                s_logger.debug("Non-admin users are not allowed to list available IPs on shared networks");
+            } else {
+                final SearchBuilder<IPAddressVO> searchBuilder = _publicIpAddressDao.createSearchBuilder();
+                buildParameters(searchBuilder, cmd, false);
+
+                SearchCriteria<IPAddressVO> searchCriteria = searchBuilder.create();
+                setParameters(searchCriteria, cmd, vlanType, false);
+                searchCriteria.setParameters("state", IpAddress.State.Free.name());
+                addrs.addAll(_publicIpAddressDao.search(searchCriteria, searchFilter)); // Free IPs on shared network
+            }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/server/ManagementServerImpl.java:2490]: can we move this to a separate method, and the inner else-clause to the Dao?

Comment (weizhouapache) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2490]: @DaanHoogland 
moving to Dao seems difficult, as this code block calls two methods to build and set search parameters: `buildParameters` and `setParameters`

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2490]: all done in `searchForIpAddresses`. this is out off scope but definitely needs factoring.

**Review by DaanHoogland — APPROVED** [review]
