### PR TITLE
server: fix IllegalMonitorStateException on cluster managedstate change

### LINKED ISSUE #11293: Getting NPE when unmange cluster is performed
### problem

Getting NPE when performing Unmanage Cluster 

### versions

ACS 4.19 and 4.20 

### The steps to reproduce the bug

1.  Navigate to cluster and Unmanage a cluster 

2. Exception observed 

Image

3. Execute the API also 

(admin) 🐱 > update cluster managedstate=Unmanaged id=f16d90eb-c351-40d0-9400-bb68baf896a2
🙈 Error: (HTTP 530, error code 9999) current thread is not owner

Logs 

```
2025-07-25 07:26:38,088 ERROR [c.c.a.ApiServer] (qtp253011924-19:[ctx-813f8f25, ctx-7b32b728]) (logid:4995b315) unhandled exception executing api command: [Ljava.lang.String;@ef7f0ca java.lang.IllegalMonitorStateException: current thread is not owner
        at java.base/java.lang.Object.wait(Native Method)
        at com.cloud.resource.ResourceManagerImpl.updateCluster(ResourceManagerImpl.java:1262)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at jdk.proxy3/jdk.proxy3.$Proxy229.updateCluster(Unknown Source)
        at org.apache.cloudstack.api.command.admin.cluster.UpdateClusterCmd.execute(UpdateClusterCmd.java:131)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:173)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:854)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:668)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:416)

```

### What to do about it?

There should be no exception when user perform unmnage cluster

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #11293

The change was introduced in #10518 
Thread.currentThread().wait(...) must be called in a synchronized block and on the object.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM, able to manage and unmage cluster successfully without any issues

File: server/src/main/java/com/cloud/resource/ResourceManagerImpl.java [hunk 1]
```diff
@@ -1217,7 +1217,7 @@ public Cluster updateCluster(UpdateClusterCmd cmd) {
                     for (int i = 0; i < retry; i++) {
                         lsuccess = true;
                         try {
-                            Thread.currentThread().wait(5 * 1000);
+                            Thread.sleep(5 * 1000);
                         } catch (final InterruptedException e) {
                             s_logger.debug("thread unexpectedly interupted during wait, while updating cluster");
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/resource/ResourceManagerImpl.java]:
```suggestion
                            s_logger.debug("thread unexpectedly interrupted during wait, while updating cluster");
```
