### PR TITLE
[VMware to KVM Migration] Fix for converted instance NPE issue when source VMware instance OVF is exported from management server

### LINKED ISSUE #10982: [VMware to KVM Migration] Issue on migration when ovftool is not installed on the conversion KVM hosts
### Problem

There is a problem on VMware to KVM migration in case the converting host doesn't have ovftool installed: conversion process fails with: 

````
Cannot invoke org.apache.cloudstack.vm.UnmanagedInstanceTO.setCpuCores(java.lang.Integer)" because "convertedInstance is null
````

Workaround: install ovftool on the KVM hosts used for conversion

The reason of the failure is that the returned converted instance on line: https://github.com/apache/cloudstack/blob/4.20/server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java#L1985 is null. This logic is missing the import instance logic that is present on: https://github.com/apache/cloudstack/blob/4.20/server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java#L2036-L2056.

### Versions

CloudStack 4.20.1 RC3
KVM hosts installing virt-v2v

### The steps to reproduce the bug

1. Install only virt-v2v on KVM host used for conversion, but not ovftool
2. Migrate VMware VM to KVM through CloudStack

### What to do about it?

Install ovftool on the KVM hosts used for conversion

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR fixes converted instance NPE issue in VMware to KVM Migration when source VMware instance OVF is exported from management server.

Fixes #10982 

Some of the changes of the below PRs were missing in 4.20, resulting in NPE.
- https://github.com/apache/cloudstack/pull/9787
- https://github.com/apache/cloudstack/pull/9764
- https://github.com/apache/cloudstack/pull/10409

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Tested VMware instance migration to KVM, without ovftool installation on KVM hosts. OVF of source VMware instance is downloaded from Management Server.

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: api/src/main/java/com/cloud/storage/VolumeApiService.java [hunk 1]
```diff
@@ -171,6 +171,7 @@ Volume updateVolume(long volumeId, String path, String state, Long storageId,
      *   </table>
      */
     boolean doesStoragePoolSupportDiskOffering(StoragePool destPool, DiskOffering diskOffering);
+
```
Comment (DaanHoogland) [inline api/src/main/java/com/cloud/storage/VolumeApiService.java:174]:
```suggestion
     /**
      * Checks if the intended destination storage pool supports the required tags
      * destPool the pool intended for the deployment
      * diskOfferingTags the tags that should be supported
      * return whether the tags are supported
      */
```

**Review by DaanHoogland — COMMENTED** [review]
One very nitpicking comment.

Is this ready for review yet @sureshanaparti ?

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Review by borisstoyanov — APPROVED** [review]
LGTM, I didn't encounter any issues while testing it

**Comment by sureshanaparti** [comment]
Merging based on the review/tests.
