### PR TITLE
Show menu section if user has access to at least one of its pages

### LINKED ISSUE #8730: [UI] Storage menu not showing even with API permissions
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
Main
~~~

##### SUMMARY
As reported in https://github.com/apache/cloudstack/pull/8713#issuecomment-1969866705, the `Storage` submenu in the sidebar is not displayed to users when they do not have permission to the API `listVolumesMetrics`. However, roles can have permissions to other APIs, such as `listBackups` and `listSnapshots`, in which case the submenu should be displayed. This scenario is probably not exclusive to the `Storage` menu.

##### STEPS TO REPRODUCE
Create a role with permission to allow the APIs `listBackups` and `listSnapshots` and deny the API `listVolumesMetrics`. The UI dashboard will not show the `Storage` menu in the sidebar.

##### EXPECTED RESULTS
The UI should show the `Storage` submenu alongside with its own `Backups` and `Snapshots` submenus.

##### ACTUAL RESULTS
The submenu `Storage` is not displayed, even though the role has permission to list snapshots and backups.

### PR DESCRIPTION
**Pull request by winterhazel**
### Description

As reported in https://github.com/apache/cloudstack/pull/8713#issuecomment-1969866705, the Storage section in the sidebar is not displayed to users when they do not have permission to the API `listVolumesMetrics`. However, roles can have permissions to other APIs, such as `listBackups` and `listSnapshots`, in which case the section should be displayed. This situation is not exclusive to the Storage section.

This PR fixes this issue by changing how the routes are filtered. Now, sections will be shown if they have at least one visible child. For other routes, the previous logic is still applied.

Closes #8730.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [X] Minor
- [ ] Trivial

### Screenshots (if appropriate):

Here's how the menu looks like before (left) and after the changes (right) for a user that does not have permission for `listVolumesMetrics`:

Screenshot from 2024-04-25 10-50-04

### How Has This Been Tested?

1. I created a role `v`, based on the role `User`, that had access to `listSnapshots` and `listBuckets`, but did not have to `listVolumesMetrics`;
2. I created an account `v` using role `v`;
3. I accessed the UI using account `v`;
4. I verified that the Storage section was shown, having the Volume Snapshots and Buckets pages;
5. I verified that the other sections did not change;
6. I clicked the Storage section and verified that I was redirected to the Volume Snapshots page;
7. I denied `listSnaphots` and `listBuckets` for role `v`;
8. I logged out, cleared my cache and logged in again. I verified that the Storage section was not shown anymore.

### CODE REVIEW

**Comment by winterhazel** [comment]
@blueorangutan package

**Comment by BryanMLima** [comment]
@blueorangutan ui

**Review by bernardodemarco — APPROVED** [review]
LGTM, I've manually tested the PR in the QA environment.

1. I created a role based on the `User` role.
2.  I denied the role's access to `listNetworks` and `listVolumesMetrics` APIs.
3. I created an account using the custom role.
4. I checked that the Storage and Network sections and their subsections are being displayed correctly.
<details>
<summary>Storage section</summary>

image
</details>

<details>
<summary>Network section</summary>

image
</details>

Great fix, @winterhazel!

**Comment by DaanHoogland** [comment]
@blueorangutan ui

**Comment by DaanHoogland** [comment]
@winterhazel @bernardodemarco I tried this in qa:

    I created a role based on the Read-Only User role.
    I denied the role's access to listVirtualMachines, listNetworks, listVolumes and listTemplates APIs.
    I created an account using the custom role.
    I tried to log in but could not.

to double check I created a "regular" Read-Only user and could log in.

**Comment by winterhazel** [comment]
> @winterhazel @bernardodemarco I tried this in qa:
> 
> ```
> I created a role based on the Read-Only User role.
> I denied the role's access to listVirtualMachines, listNetworks, listVolumes and listTemplates APIs.
> I created an account using the custom role.
> I tried to log in but could not.
> ```
> 
> to double check I created a "regular" Read-Only user and could log in.

Hey @DaanHoogland, I reproduced your steps in QA and was able to log in. I created the account `t` (password is also `t`).

I suppose that the user you created was `cripple`. I verified that it did not have access to `listZones`, which is an API users are unable to login without. This behavior has nothing to do with the changes here, and you can verify that this account is unable to login in the QA of other PRs as well.

**Comment by DaanHoogland** [comment]
> I suppose that the user you created was `cripple`. I verified that it did not have access to `listZones`, which is an API users are unable to login without. This behavior has nothing to do with the changes here, and you can verify that this account is unable to login in the QA of other PRs as well.

you are right, I added `listZones` and cripple can login with all menus available. :+1:

File: ui/src/store/modules/permission.js [hunk 1]
```diff
@@ -17,24 +17,39 @@
...
 
-function hasApi (apis, route) {
-  if (route.meta && route.meta.permission) {
-    for (const permission of route.meta.permission) {
-      if (!apis.includes(permission)) {
-        return false
-      }
-    }
+function hasAccessToRoute (apis, route) {
+  if (!route.meta || !route.meta.permission) {
```
Comment (BryanMLima) [inline ui/src/store/modules/permission.js:21]: Could use optional chaining here, no?
```suggestion
  if (!route.meta?.permission) {
```

File: ui/src/store/modules/permission.js [hunk 2]
```diff
@@ -17,24 +17,39 @@
...
 }
 
 function filterAsyncRouter (routerMap, apis) {
   const accessedRouters = routerMap.filter(route => {
-    if (hasApi(apis, route)) {
+    if (hasAccessToRoute(apis, route)) {
       if (route.children && route.children.length > 0) {
         route.children = filterAsyncRouter(route.children, apis)
       }
+      if (route.meta && route.meta.section) {
```
Comment (BryanMLima) [inline ui/src/store/modules/permission.js:50]: Could use optional chaining here, no?
```suggestion
      if (route.meta?.section) {
```

File: ui/src/store/modules/permission.js (hunk 1 above)
Comment (BryanMLima) [reply ui/src/store/modules/permission.js:21]: Never mind, did not see it was already merged.
