### PR TITLE
kvm: allow skip forcing disk controller

### LINKED ISSUE #9460: RootDiskController setting not Honored throughout Instance lifecycle
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
 
~~~
Instances
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.0
~~~

##### CONFIGURATION

Advanced Networking

##### OS / ENVIRONMENT

KVM

##### SUMMARY

When creating a Windows Instance configured with "rootDiskController=virtio" in Settings and using UEFI Secure Boot in the OS, existing and added Disks, initially configured with virtio scsi controllers, will lose these controller settings and revert to basic sata controllers after a stop and start. This behavior does not occur on Windows Instance using BIOS boot. 

##### STEPS TO REPRODUCE

~~~
Create Windows 2019 Instance that is assigned the setting "rootDiskController=virtio" and uses UEFI Secure Boot. Install all necessary VirtIO drivers. Reboot the Instance. Log in and Open Device Manager in Windows. Hot-add new Volume to Windows Instance through CloudStack and observe in the OS that the newly added disk will be the correct "Red Hat VirtIO SCSI Disk Device" and the Storage Controller will be the correct "Red Hat VirtIO SCSI Controller." Stop the Instance. Start the Instance. Log in and open Device Manager in OS. Observe that both disks are now "QEMU HARDDISK" and the Storage Controller has been removed. 
~~~

##### EXPECTED RESULTS

~~~
Expected results are that the Disk Controller and Volume settings would persist for the entirety of the Instance Lifecycle. The Disk Controller would remain in the following state as seen in this virsh file snippit. This excerpt is from before the Instance was stopped:

<disk type='file' device='disk'>
<driver name='qemu' type='qcow2' cache='none'/>
<source file='/mnt/7fe777bd-cd27-3b37-bf4c-dc94fcbe6d33/0b4b8825-1465-4221-b42d-8827688baac3' index='4'/>
<backingStore/>
<target dev='vdb' bus='virtio'/>
<serial>0b4b882514654221b42d</serial>
<alias name='virtio-disk1'/>
<address type='pci' domain='0x0000' bus='0x07' slot='0x00' function='0x0'/>
</disk>
~~~

##### ACTUAL RESULTS

~~~
After Shutdown and Startup, the Disk Controller and Volume settings are changed to the following state in the OS and in the virsh file:

<disk type="file" device="disk">
<driver name="qemu" type="qcow2" cache="none"/>
<source file="/mnt/7fe777bd-cd27-3b37-bf4c-dc94fcbe6d33/0b4b8825-1465-4221-b42d-8827688baac3" index="2"/>
<backingStore/>
<target dev="sdb" bus="sata"/>
<serial>0b4b882514654221b42d</serial>
<alias name="sata0-0-1"/>
<address type="drive" controller="0" bus="0" target="0" unit="1"/>


~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #9460

A VM or template detail can be added with key `skip.force.disk.controller` and value `true` to allow skipping forcing disk controllers for the VM especially in case of UEFI VMs.
Otherwise, current behaviour of disk controllers depend on the guest OS, UEFI secure boot where Windows VM may always be provisioned with `sata` and other OS VMs with `virtio`.

Doc PR: https://github.com/apache/cloudstack-documentation/pull/616

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan package

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 1]
```diff
@@ -3161,18 +3198,9 @@ public int compare(final DiskTO arg0, final DiskTO arg1) {
...
-                    } else {
-                        if (isSecureBoot) {
-                            disk.defFileBasedDisk(physicalDisk.getPath(), devId, DiskDef.DiskFmtType.QCOW2, isWindowsTemplate);
-                        } else {
-                            disk.defFileBasedDisk(physicalDisk.getPath(), devId, diskBusType, DiskDef.DiskFmtType.QCOW2);
-                        }
-                    }
-
+                    defineDiskForDefaultPoolType(disk, volume, isWindowsTemplate, isUefiEnabled, isSecureBoot,
+                            physicalDisk,devId, diskBusType, diskBusTypeData, details);
```
Comment (shwstppr) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:3202]:
```suggestion
                            physicalDisk, devId, diskBusType, diskBusTypeData, details);
```

Comment (shwstppr) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java]:
```suggestion
                            physicalDisk, devId, diskBusType, diskBusTypeData, details);
```

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 2]
```diff
@@ -3010,6 +3009,44 @@ public static DiskDef.DiskType getDiskType(KVMPhysicalDisk physicalDisk) {
...
+     * @param diskBusTypeData The disk bus type to use for data disks, if applicable.
+     * @param details A map of VM details containing additional configuration values, such as whether to skip force
+     *                disk controller.
+     */
+    protected void defineDiskForDefaultPoolType(DiskDef disk, DiskTO volume, boolean isWindowsTemplate,
+                    boolean isUefiEnabled, boolean isSecureBoot, KVMPhysicalDisk physicalDisk, int devId,
+                    DiskDef.DiskBus diskBusType, DiskDef.DiskBus diskBusTypeData, Map<String, String> details) {
+        boolean skipForceDiskController = MapUtils.getBoolean(details, VmDetailConstants.KVM_SKIP_FORCE_DISK_CONTROLLER,
+                false);
+        if (skipForceDiskController) {
```
Comment (pavanaravapalli) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:3107]: @shwstppr 
This condition forces the root disk controller to use its configured settings instead of the UEFI workflow settings, even when the VM is deployed with UEFI and this setting "skip.force.disk.controller" is enabled. Consequently, a UEFI-deployed VM may fail to boot because some guest operating systems still depend on SATA disk.  Please include a comment or a note detailing the change in behavior."

File: api/src/main/java/com/cloud/vm/VmDetailConstants.java [hunk 3]
```diff
@@ -53,6 +53,9 @@ public interface VmDetailConstants {
     String NIC_MULTIQUEUE_NUMBER = "nic.multiqueue.number";
     String NIC_PACKED_VIRTQUEUES_ENABLED = "nic.packed.virtqueues.enabled";
 
+    // KVM specific, disk controllers
+    String KVM_SKIP_FORCE_DISK_CONTROLLER = "skip.force.disk.controller";
```
Comment (sureshanaparti) [inline api/src/main/java/com/cloud/vm/VmDetailConstants.java:58]: @shwstppr should it be included for for KVM here: https://github.com/apache/cloudstack/blob/e90e436ef873100b1916c80c0309c1eefcc4a265/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L5060-L5061

also, check if any doc changes needed for this vm detail.

**Comment by sureshanaparti** [comment]
@shwstppr can rebase with 4.20? there wouldn't be any further 4.19.x release, so better target this to 4.20.

**Comment by RosiKyu** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by RosiKyu** [comment]
@blueorangutan test
