### PR TITLE
vr: fix backup router health check

### LINKED ISSUE #4163: health check gateways_check.py for redundant VR will fail for BACKUP router
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Health Checks on VR
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0 LTS
~~~

##### CONFIGURATION

advanced networking with public link on VR

##### OS / ENVIRONMENT

VMWare Hypervisor (may happens on other hypervisor as well)

##### SUMMARY

If you deploy redundant VRs the Backup VR will set the public interface to DOWN until it gets MASTER. As long as he is BACKUP the gateways_check.py will fail as the link is DOWN.

##### STEPS TO REPRODUCE

~~~
deploy redundant VR and execute the health checks. gateways_check.py will never pass on the BACKUP VR.
~~~

##### EXPECTED RESULTS

~~~
As this is an expected behavior the health checks should check the state the VR and in case of BACKUP exclude this check.
~~~

##### ACTUAL RESULTS

~~~
Health Checks will fail and fill up the alerts with error messages.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
## Description
Fixes #4163 

Added excluded tests in the code for BACKUP router.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
BACKUP Router,
Screenshot from 2020-06-24 17-47-02

Before fix,
Screenshot from 2020-06-24 17-32-04

After fix and excluding `gateways_check.py` for BACKUP router,
Screenshot from 2020-06-24 17-45-21

## How Has This Been Tested?
Executing health checks for BACKUP router

### CODE REVIEW

**Comment by shwstppr** [comment]
@Doni7722 @rhtyd please have a look

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by Doni7722** [comment]
@shwstppr LGTM - Does it check the state of the Router on every health check (as the state could change anytime)?

**Comment by shwstppr** [comment]
@Doni7722 `createMonitorServiceCommand`, where the exclusion has been added, is the method used to create command which will be sent to the host for running health. This will be called every time health checks run for a router. State is checked from DomainRouterVO which should hold the correct state even if it has been changed. 

https://github.com/apache/cloudstack/blob/a838a14bd3d42226e858b051f3411a24b718db48/server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java#L1628

https://github.com/apache/cloudstack/blob/a838a14bd3d42226e858b051f3411a24b718db48/server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java#L1652-L1691

@blueorangutan test

File: server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java [hunk 1]
```diff
@@ -1632,7 +1633,11 @@ private SetMonitorServiceCommand createMonitorServiceCommand(DomainRouterVO rout
         command.setAccessDetail(SetMonitorServiceCommand.ROUTER_HEALTH_CHECKS_ENABLED, RouterHealthChecksEnabled.value().toString());
         command.setAccessDetail(SetMonitorServiceCommand.ROUTER_HEALTH_CHECKS_BASIC_INTERVAL, RouterHealthChecksBasicInterval.value().toString());
         command.setAccessDetail(SetMonitorServiceCommand.ROUTER_HEALTH_CHECKS_ADVANCED_INTERVAL, RouterHealthChecksAdvancedInterval.value().toString());
-        command.setAccessDetail(SetMonitorServiceCommand.ROUTER_HEALTH_CHECKS_EXCLUDED, RouterHealthChecksToExclude.valueIn(router.getDataCenterId()));
+        String excludedTests = RouterHealthChecksToExclude.valueIn(router.getDataCenterId());
+        if (router.getIsRedundantRouter() && RedundantState.BACKUP.equals(router.getRedundantState())) {
+            excludedTests = excludedTests.isEmpty() ? BACKUP_ROUTER_EXCLUDED_TESTS : excludedTests + "," + BACKUP_ROUTER_EXCLUDED_TESTS;
```
Comment (rhtyd) [inline server/src/main/java/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java:1638]: Add a null or empty check
