### PR TITLE
UI: Show security group selection in Basic zone VM deployment

### LINKED ISSUE #11685: UI: No Security group Section in DeployVm wizard in Basic zone
### problem

when deploy vm in basic zone, there is no section to choose a SG

### versions

ACS 4.21
Basic zone
KVM

### The steps to reproduce the bug

check screenshots below

1.

Image

2.

Image

3.

Image

4.

Image

5. advanced mode

Image

Image

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by Damans227**
### Description

The Deploy VM wizard does not show the Security Groups selection step in Basic zones. 

Fixes: #11685

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

### Screen-recording

https://github.com/user-attachments/assets/42c7c432-5940-4da3-9a12-407cbf27a606

### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

1. Created a Basic zone and verified the Security Groups step now appears in the Deploy VM wizard
2. Tested cross-domain deployment as root admin and verified SGs from the target domain/account are listed correctly

### CODE REVIEW

**Comment by Damans227** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan ui

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan ui

File: ui/src/views/compute/DeployVM.vue [hunk 1]
```diff
@@ -1501,6 +1504,9 @@ export default {
       return tabList
     },
     showSecurityGroupSection () {
+      if (this.zone && this.zone.networktype === 'Basic') {
+        return true
+      }
```
Comment (weizhouapache) [inline ui/src/views/compute/DeployVM.vue:1509]: change makes sense.

in Basic zone, there is only 1 network, so user do not need to choose a network

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by kiranchavala — APPROVED** [review]
LGTM 

Tested on the QA server

Image
