### PR TITLE
Fixes #2685: broken SXM support

### LINKED ISSUE #2685: Cannot live migrate XenServer VMs between two storage pools
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Hypervisor Controler
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

XenServer clusters with local storage or DefaultPrimary PreSetup SRs.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Trying to migrate a XenServer VM to another storage pool causes a "Can not see storage pool" exception.

This occurs because the SR's path is used to query the SRs by name label on the XenServer host.

##### STEPS TO REPRODUCE

~~~
cs --region preprod migrateVirtualMachineWithVolume virtualmachineid=e731afa7-7aab-4c4b-ab73-0e756dab8cfb hostid=529e6778-5e19-4ff0-806d-680451f5d4d7
~~~

##### EXPECTED RESULTS

~~~
Migration success.
~~~

##### ACTUAL RESULTS

~~~
2018-06-01 16:26:30,222 ERROR [c.c.h.x.r.w.x.XenServer610MigrateWithStorageReceiveCommandWrapper] (DirectAgent-4:ctx-1e92a910) (logid:bdc18e3b) Migration of
vm i-2-1946-VM with storage failed due to com.cloud.utils.exception.CloudRuntimeException: Can not see storage pool: ext from on host:db5ea702-5d01-4bcd-b736
-25c80a506a5e
com.cloud.utils.exception.CloudRuntimeException: Can not see storage pool: ext from on host:db5ea702-5d01-4bcd-b736-25c80a506a5e
        at com.cloud.hypervisor.xenserver.resource.wrapper.xen610.XenServer610MigrateWithStorageReceiveCommandWrapper.execute(XenServer610MigrateWithStorageR
eceiveCommandWrapper.java:73)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xen610.XenServer610MigrateWithStorageReceiveCommandWrapper.execute(XenServer610MigrateWithStorageR
eceiveCommandWrapper.java:48)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-06-01 16:26:30,223 ERROR [o.a.c.s.m.XenServerStorageMotionStrategy] (Work-Job-Executor-2:ctx-3df539ea job-6147/job-6148 ctx-00f4325c) (logid:bdc18e3b) M
igration with storage of vm VM[User|i-2-1946-VM] failed. Details: Exception: com.cloud.utils.exception.CloudRuntimeException
Message: Can not see storage pool: ext from on host:db5ea702-5d01-4bcd-b736-25c80a506a5e
Stack: com.cloud.utils.exception.CloudRuntimeException: Can not see storage pool: ext from on host:db5ea702-5d01-4bcd-b736-25c80a506a5e
        at com.cloud.hypervisor.xenserver.resource.wrapper.xen610.XenServer610MigrateWithStorageReceiveCommandWrapper.execute(XenServer610MigrateWithStorageR
eceiveCommandWrapper.java:73)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xen610.XenServer610MigrateWithStorageReceiveCommandWrapper.execute(XenServer610MigrateWithStorageR
eceiveCommandWrapper.java:48)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2018-06-01 16:26:30,223 ERROR [o.a.c.s.m.XenServerStorageMotionStrategy] (Work-Job-Executor-2:ctx-3df539ea job-6147/job-6148 ctx-00f4325c) (logid:bdc18e3b) c
opy failed
com.cloud.utils.exception.CloudRuntimeException: Error while migrating the vm VM[User|i-2-1946-VM] to host Host[-23-Routing]
        at org.apache.cloudstack.storage.motion.XenServerStorageMotionStrategy.migrateVmWithVolumesAcrossCluster(XenServerStorageMotionStrategy.java:346)
        at org.apache.cloudstack.storage.motion.XenServerStorageMotionStrategy.copyAsync(XenServerStorageMotionStrategy.java:122)
        at org.apache.cloudstack.storage.motion.DataMotionServiceImpl.copyAsync(DataMotionServiceImpl.java:90)
        at org.apache.cloudstack.storage.volume.VolumeServiceImpl.migrateVolumes(VolumeServiceImpl.java:1646)
        at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolumes(VolumeOrchestrator.java:1054)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:2553)
        at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:4987)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
        at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5090)
        at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~~~

### PR DESCRIPTION
**Pull request by dpassante**
## Description

Use the storage pool UUID rather than it's path to find it on XenServer hosts.
 

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## GitHub Issue/PRs

Fixes: #2685 

## How Has This Been Tested?

* Live migration between two XenServer hosts with local storage (different clusters)
* Live migration between two XenServer clusters with DefaultPrimary PreSetup shared SRs

## Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

File: plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java [hunk 1]
```diff
@@ -326,7 +326,7 @@ private Answer migrateVmWithVolumesAcrossCluster(VMInstanceVO vm, VirtualMachine
                     volumeToStorageUuid.add(new Pair<>(volumeTo, iqn));
                 }
                 else {
-                    volumeToStorageUuid.add(new Pair<>(volumeTo, ((StoragePool)entry.getValue()).getPath()));
+                    volumeToStorageUuid.add(new Pair<>(volumeTo, ((StoragePool)entry.getValue()).getUuid()));
```
Comment (rhtyd) [inline plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java]: This can have compatibility issues wrt non-local disks, can any xenserver guru test/comment - @rafaelweingartner @DaanHoogland etc?

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan help

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 xenserver-71

File: plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java (hunk 1 above)
Comment (DaanHoogland) [reply plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java]: I share your concerns, @rhtyd , will run the smoke test and maybe a second run with specific migration tests

**Comment by DaanHoogland** [comment]
@blueorangutan test centos7 xenserver-65sp1

File: plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java (hunk 1 above)
Comment (rafaelweingartner) [reply plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java]: I do not know what is used in the `path` field there, but if you use the storage UUID, you should not have a problem to find storage repositories in the XenServer host.

**Comment by DaanHoogland** [comment]
have the 'standard' migration tests running:
@blueorangutan test centos7 xenserver-71 component/test_volumes.py

File: plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java (hunk 1 above)
Comment (rhtyd) [reply plugins/hypervisors/xenserver/src/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java]: LGTM, in case of xenserver with storage motion across clusters with local storage the path is set to `lvm`. Error I got was:
```
ERROR [c.c.h.x.r.w.x.XenServer610MigrateWithStorageReceiveCommandWrapper] (DirectAgent-214:ctx-d73466f3) (logid:d54ed2c4) Migration of vm i-2-3-VM with storage failed due to com.cloud.utils.exception.CloudRuntimeException: Can not see storage pool: lvm from on host:fd11220b-db52-42b6-b21d-3f660f7b8a4a
com.cloud.utils.exception.CloudRuntimeException: Can not see storage pool: lvm from on host:fd11220b-db52-42b6-b21d-3f660f7b8a4a
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.getStorageRepository(CitrixResourceBase.java:3249)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xen610.XenServer610MigrateWithStorageReceiveCommandWrapper.execute(XenServer610MigrateWithStorageReceiveCommandWrapper.java:73)
	
```
The regression was introduced in `a30a31c9b7f9b5fe246a02285bf820e7fe9ce16e`. /cc @mike-tutkowski

**Comment by rhtyd** [comment]
@DaanHoogland @rafaelweingartner smoketests LGTM, are you okay with this PR? I've tested both local and non-local (nfs) storage migration. In case of local storage, the getPath() returns `lvm` which is incorrect, by using uuid to find storage, it worked.
screenshot from 2018-06-07 16-02-37

**Comment by DaanHoogland** [comment]
jenkins please

**Comment by rafaelweingartner** [comment]
@DaanHoogland yes I am ok with the PR. I do, however, have a question. Do you intend to add this to 4.11.0?

**Comment by DaanHoogland** [comment]
Don't know about an rc2, @rafaelweingartner Yes I plan to put it in 4.11.1 (given @PaulAngus ' consent)

**Comment by rafaelweingartner** [comment]
I thought I saw an e-mail saying something an RC2, but I might be mistaken.

**Comment by DaanHoogland** [comment]
I was soliciting comment on having an rc2 today, but got no reactions yet. We also have a lot of almost done so I will not push for it, now.

**Comment by DaanHoogland** [comment]
no errors in the migration component test it seems. lgtm. merging
