### PR TITLE
Broadcast URI not set to vxlan, but vlan (Fix #3040)

### LINKED ISSUE #3040: Broadcast URI not set to vxlan, but vlan
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Management Server
~~~

##### CLOUDSTACK VERSION
~~~
master / 4.12
~~~

##### CONFIGURATION
Advanced Networking with KVM and VXLAN

##### OS / ENVIRONMENT
- Ubuntu 18.04
- KVM

##### SUMMARY
Advanced Network zone with VXLAN is created. When creating a guest network and setting the VNI this is set for the network:

- broadcast_uri: vlan://1000
- isolation_uri: vlan://1000

##### STEPS TO REPRODUCE
- Create a Advanced Zone with VXLAN
- Create a guest network
- See that broadcast is set to vlan and not vxlan

screenshot from 2018-11-19 09-51-14

screenshot from 2018-11-19 09-51-39

### PR DESCRIPTION
**Pull request by GabrielBrascher**
## Description

This PR sets properly Broadcast URI to `vxlan://vxlan_id` when the physical network is of VXLAN.

Fixes: #3040

Description of issue #3040:
> Advanced Network zone with VXLAN is created. When creating a guest network and setting the VNI this is set for the network:
>     broadcast_uri: vlan://1000
>     isolation_uri: vlan://1000
> 
> STEPS TO REPRODUCE
> 
>     Create a Advanced Zone with VXLAN
>     Create a guest network
>     See that broadcast is set to vlan and not vxlan

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):
**Prior to the fix:**
image

**After the fix:**
image

## How Has This Been Tested?

1. Create a Advanced Zone with VXLAN
2. Create a guest network
3. See that broadcast uri is set to vxlan

### CODE REVIEW

**Comment by rhtyd** [comment]
@blueorangutan package

File: engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java [hunk 1]
```diff
@@ -2475,6 +2475,21 @@ public Network doInTransaction(final TransactionStatus status) {
         return network;
     }
 
+    /**
+     * Encodes VLAN/VXLAN ID into a Broadcast URI according to the isolation method from the Physical Network.
+     * @return Broadcast URI, e.g. 'vlan://vlan_ID' or 'vxlan://vlxan_ID'
+     */
+    protected URI encodeVlanIdIntoBroadcastUri(String vlanId, PhysicalNetwork pNtwk) {
+        if(StringUtils.isNotBlank(pNtwk.getIsolationMethods().get(0))) {
```
Comment (GabrielBrascher) [inline engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2483]: I got wondering if there could be more than one isolation method on a network. Considering that this is a List of isolation methods. I assume that to get into a VLAN conditional (the ones that this method is called) there will be only one isolation method, either VLAN or VXLAN.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by wido** [comment]
LGTM based on the code

**Comment by rhtyd** [comment]
@GabrielBrascher did you try against 4.14, somehow I remember this was fixed recently? Thanks.
@blueorangutan package

**Comment by GabrielBrascher** [comment]
@rhtyd I will take a look at 4.14 and 4.15 then. If it has already been fixed I will close this one. Thanks!

**Comment by GabrielBrascher** [comment]
@rhtyd I just tested on master and the problem is still there.

I also gave a quick look at the codebase and could not see any recent commit addressing this. I am assuming that current master has all 4.14 committs forwarded merged.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
kick

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
(centos8 pkg failure is expected as it's not supported on 4.13/4.14 and before)
@blueorangutan test

**Review by rhtyd — APPROVED** [review]
LGTM, but need another pair of eyes or four

**Review by wido — APPROVED** [review]
LGTM based on code and feedback from @GabrielBrascher

File: engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java (hunk 1 above)
Comment (rhtyd) [inline engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2483]: @GabrielBrascher Should we check if `pNtwk` is null? This could potentially cause a NPE; and the getIsolationMethods() is also a valid list with at least one item

Comment (GabrielBrascher) [reply engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2483]: @rhtyd thanks for the review :-)

Answering your question: I did not add null verification on the respective parameter due to the fact that both methods that call this one already validate the private network

1. the physical network `pNtwk` is validated at [NetworkOrchestrator.java#L2196](https://github.com/apache/cloudstack/blob/2c3a41c7a63dfd1dd271578eacec26442ee039f9/engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java#L2196);

2. the other method that calls `encodeVlanIdIntoBroadcastUri` also validates the private network at this line [NetworkOrchestrator.java#L2397](https://github.com/apache/cloudstack/blob/2c3a41c7a63dfd1dd271578eacec26442ee039f9/engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java#L2397).

However, considering that this method could be reused, I have no problem in adding null validations.

Comment (GabrielBrascher) [reply engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2483]: Actually, NetworkOrchestrator.java#L2397 is not exactly a null validation. I will add a null verification @rhtyd.

**Comment by rhtyd** [comment]
@GabrielBrascher can you advise when this is ready for merging, thnx

**Comment by GabrielBrascher** [comment]
@rhtyd I am a bit offline this week due to vacation. I Will get back at 21st September. As soon as I get back I will add the null validation and update this PR. Thanks!

**Comment by GabrielBrascher** [comment]
@rhtyd update code with the null validation.

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

File: engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java (hunk 1 above)
Comment (rhtyd) [reply engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java:2487]: @GabrielBrascher please add the null validation, thnx

**Comment by rhtyd** [comment]
Will merge and then need to kick tests on 4.14 and master
