### PR TITLE
List templates and ISOs by domain

### LINKED ISSUE #10392: Domain - "View Templates" Button Does Not Filter
### problem

Clicking on View Templates from Domain as Root Admin does not filter correctly.  

Image

Expecting to only see 2 templates:

Image

### versions

4.19.1.3 & 4.20.0.0
GUI
KVM

### The steps to reproduce the bug

1. Logged in as Root Admin click on Domains
2. Choose a Sub-Domain (Note: this Sub-Domain should have its own templates)
3. Click on the View Templates Button
4. Observe the returned results are not for just that domain. There is no filtering done.

### What to do about it?

While this is similar to #10391, I'm not sure on this one.  ListTemplates seems to require an Account Name (Unless this is actually a bug as well).  Simply adding `&templatefilter=self` does not fix this.  

If ListTemplates really requires an account name, is this button needed?

### PR DESCRIPTION
**Pull request by bernardodemarco**
### Description

Currently, it is not possible to list the templates and ISOs of a specific domain. When executing the `listTemplates` and `listIsos` APIs only specifying a `domainid`, all templates/ISOs that the caller has access to are listed; the `domainid` parameter is completely ignored.

Therefore, this PR proposes to add support for listing templates and ISOs by domain. To achieve that, the `listTemplates` and `listIsos` APIs should be called defining the `templatefilter` and `isofilter` parameters to either `self` or `selfexecutable`. Furthermore, the `isrecursive` parameter can be used, to list templates and ISOs recursively by domain.

---

Fixes #10392, #10393

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### Screenshots (if appropriate):

image

image

### How Has This Been Tested?

- Verified that domain access validation is correctly performed
- Verified that it is possible to list templates and ISOs by domain when specifying the `templatefilter` and `isofilter` parameters to either `self` or `selfexecutable`
- Verified that templates and ISOs are recursively listed when the `isrecursive` parameter is specified as true

### CODE REVIEW

**Comment by bernardodemarco** [comment]
@DaanHoogland @shwstppr @sureshanaparti targeting this PR to the 4.19 branch because the #10392 milestone is set to `4.19.4`

**Comment by bernardodemarco** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 1]
```diff
@@ -4490,7 +4493,7 @@ private Pair<List<TemplateJoinVO>, Integer> searchForTemplatesInternal(Long temp
             boolean showDomr, boolean onlyReady, List<Account> permittedAccounts, Account caller,
             ListProjectResourcesCriteria listProjectResourcesCriteria, Map<String, String> tags,
             boolean showRemovedTmpl, List<Long> ids, Long parentTemplateId, Boolean showUnique, String templateType,
-            Boolean isVnf) {
+            Boolean isVnf, Long domainId, boolean isRecursive) {
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:4496]: I am not a fan of extending parameter lists beyond three. It already was, but we should think about passing the command or an interface the command adheres to instead. Not necessarily in this PR but keep in mind this is a maintainability issue. a lot of these are directly retrieved from the cmd object.

**Review by DaanHoogland — APPROVED** [review]
one grumpy old man remark, otherwise lgtm.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 1 above)
Comment (bernardodemarco) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:4496]: @DaanHoogland yes, I agree.

IMHO, the overall workflows of the `listIsos` and `listTemplates` APIs could really benefit from refactoring. There's extensive DAO manipulation within the business/service layer, a lack of modularization, and the current structure makes troubleshooting and maintenance difficult.

I'll open a separate issue to address this.

Comment (bernardodemarco) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:4496]: Done, #11209

**Review by shwstppr — APPROVED** [review]
code lgtm

**Comment by DaanHoogland** [comment]
@bernardodemarco I tested this in a lab env but still view the default template and system template when browsing from the (child)domain. Anything I might have missed?

**Comment by bernardodemarco** [comment]
> @bernardodemarco I tested this in a lab env but still view the default template and system template when browsing from the (child)domain. Anything I might have missed?

@DaanHoogland, thanks for testing!

Have you defined the `templatefilter` and `isofilter` parameters to be equal to either `self` or `selfexecutable`? If so, could you share the API calls that have been performed?

**Comment by DaanHoogland** [comment]
> > @bernardodemarco I tested this in a lab env but still view the default template and system template when browsing from the (child)domain. Anything I might have missed?
> 
> @DaanHoogland, thanks for testing!
> 
> Have you defined the `templatefilter` and `isofilter` parameters to be equal to either `self` or `selfexecutable`? If so, could you share the API calls that have been performed?

I would expect those to be set by the UI when browsing from the domain page, no?

**Comment by bernardodemarco** [comment]
> I would expect those to be set by the UI when browsing from the domain page, no?

@DaanHoogland, yes, for sure. I assumed you were performing the API calls directly from CloudMonkey

Can you share the API request the UI is performing (through the browser's inspect tab)?

Also, could you verify the URL the UI is redirecting the calling user to? It should be something like this

image

**Comment by DaanHoogland** [comment]
> > I would expect those to be set by the UI when browsing from the domain page, no?
> 
> @DaanHoogland, yes, for sure. I assumed you were performing the API calls directly from CloudMonkey

All is good @bernardodemarco , I learned two things:
- I am working on too much at the same time and tested your functionality in an env without  your changes 🤦 .
- when you select a domain and not an account the ownership defaults back to ROOT and what I suppose would be the caller account.

I am not sure if this second point is worth an issue. In any case we are good to go with this PR.
