### PR TITLE
server: fix fail to list public ips of shared networks sometimes

### LINKED ISSUE #8622: Change IP address for NIC or add secondary - IPs not visible - 4.19
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

~~~
Advanced Networking
~~~

##### SUMMARY

~~~
The free IPs are not visible in the UI when you attempt to change or assign secondary IP.
~~~
##### STEPS TO REPRODUCE

~~~

~~~
image

##### EXPECTED RESULTS

~~~
List the free IPs
~~~

##### ACTUAL RESULTS

~~~
Not visible 
~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #8622 

error
```
2024-02-07 10:59:11,110 ERROR [c.c.a.ApiServer] (qtp1146825051-20:ctx-74413901 ctx-b91ecc51) (logid:aa41ab63) unhandled exception executing api command: [Ljava.lang.String;@5a46b058
java.lang.NullPointerException
    at com.cloud.vm.NicVO.getInstanceId(NicVO.java:256)
    at com.cloud.api.ApiResponseHelper.addSystemVmInfoToIpResponse(ApiResponseHelper.java:995)
    at com.cloud.api.ApiResponseHelper.showVmInfoForSharedNetworks(ApiResponseHelper.java:1175)
    at com.cloud.api.ApiResponseHelper.createIPAddressResponse(ApiResponseHelper.java:1088)
    at org.apache.cloudstack.api.command.user.address.ListPublicIpAddressesCmd.execute(ListPublicIpAddressesCmd.java:196)
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [x] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: server/src/main/java/com/cloud/api/ApiResponseHelper.java [hunk 1]
```diff
@@ -992,6 +992,9 @@ private void addSystemVmInfoToIpResponse(NicVO nic, IPAddressResponse ipResponse
         if (!isAdmin) {
             return;
         }
+        if (Nic.ReservationStrategy.PlaceHolder.equals(nic.getReservationStrategy())) {
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]: @weizhouapache , these are 4 more potential NPEs, did you check those?

Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]: Did you mean this code snippet or some where else?

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]: in the condition here. I'll check them tomorrow.

Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]: it is defined as
```
    public enum ReservationStrategy {
        PlaceHolder, Create, Start, Managed;
    }
```

Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]: it is defined as below
```
    public enum ReservationStrategy {
        PlaceHolder, Create, Start, Managed;
    }
```

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]: sorry for the late reply @weizhouapache yes and nic as well would have thrown an NPE before. I think it is not intuitive code but you fix is good and an improvement on it.

**Review by DaanHoogland — APPROVED** [review]
clgtm

File: server/src/main/java/com/cloud/api/ApiResponseHelper.java (hunk 1 above)
Comment (weizhouapache) [inline server/src/main/java/com/cloud/api/ApiResponseHelper.java:995]:
```suggestion
        if (nic == null || Nic.ReservationStrategy.PlaceHolder.equals(nic.getReservationStrategy())) {
```

Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/ApiResponseHelper.java]: Is it ok now?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM, tested manually, the ips are listed 

Screenshot 2024-04-10 at 11 29 16 AM

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> LGTM, tested manually, the ips are listed
> 
> Screenshot 2024-04-10 at 11 29 16 AM

thanks for the testing @kiranchavala 

let me rebuild the packages the kick a trillian test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Comment by weizhouapache** [comment]
merging based on approvals and manual/CI tests

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
there are consistent test failures, need check

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 2]
```diff
@@ -1566,7 +1566,7 @@ public UserVm removeNicFromVirtualMachine(RemoveNicFromVMCmd cmd) throws Invalid
         }
 
         // check to see if nic is attached to VM
-        if (nic.getInstanceId() != vmId) {
+        if (!nic.getInstanceId().equals(vmId)) {
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:1569]: Is it possible for `nic.getInstanceId()` to be `null`? If it can be `null`, this will throw an NPE.

Comment (weizhouapache) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:1569]:
```suggestion
        if (nic.getInstanceId() == null || !nic.getInstanceId().equals(vmId)) {
```

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 3]
```diff
@@ -1637,7 +1637,7 @@ public UserVm updateDefaultNicForVirtualMachine(UpdateDefaultNicForVMCmd cmd) th
         Network existingdefaultnet = _networkModel.getDefaultNetworkForVm(vmId);
 
         //check to see if nic is attached to VM
-        if (nic.getInstanceId() != vmId) {
+        if (!nic.getInstanceId().equals(vmId)) {
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:1640]:
```suggestion
        if (nic.getInstanceId() == null || !nic.getInstanceId().equals(vmId)) {
```

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@weizhouapache I see some other usages of `Nic.getinstanceId()` in code, do we need to fix/address them?
[nic-instanceid.diff.txt](https://github.com/apache/cloudstack/files/15400616/nic-instanceid.diff.txt)

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 4]
```diff
@@ -1566,7 +1566,7 @@ public UserVm removeNicFromVirtualMachine(RemoveNicFromVMCmd cmd) throws Invalid
         }
 
         // check to see if nic is attached to VM
-        if (nic.getInstanceId() != vmId) {
+        if (nic.getInstanceId() == null || !nic.getInstanceId().equals(vmId)) {
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:1569]:
```suggestion
        if (nic.getInstanceId() == null || !vmId.equals(nic.getInstanceId())) {
```

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 5]
```diff
@@ -1637,7 +1637,7 @@ public UserVm updateDefaultNicForVirtualMachine(UpdateDefaultNicForVMCmd cmd) th
         Network existingdefaultnet = _networkModel.getDefaultNetworkForVm(vmId);
 
         //check to see if nic is attached to VM
-        if (nic.getInstanceId() != vmId) {
+        if (nic.getInstanceId() == null || !nic.getInstanceId().equals(vmId)) {
```
Comment (vishesh92) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:1640]:
```suggestion
        if (nic.getInstanceId() == null || !vmId.equals(nic.getInstanceId())) {
```

**Comment by weizhouapache** [comment]
> @weizhouapache I see some other usages of `Nic.getinstanceId()` in code, do we need to fix/address them? [nic-instanceid.diff.txt](https://github.com/apache/cloudstack/files/15400616/nic-instanceid.diff.txt)

thanks @shwstppr 
it looks like we need a lot of other changes due to the integer-> Integer change

probably we can just ignore the error by
```
        try {
            nic.getInstanceId();
        } catch (NullPointerException ex) {
            return;
        }
```

**Comment by shwstppr** [comment]
@weizhouapache unless I'm missing the point, even if we decide on wrapping nic.getInstanceId() in a try-catch for NPE it would still need changes in many more places

**Comment by weizhouapache** [comment]
> @weizhouapache unless I'm missing the point, even if we decide on wrapping nic.getInstanceId() in a try-catch for NPE it would still need changes in many more places

if change the type from integer to Integer, yes
but if the type is still integer, no more changes is needed.

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@DaanHoogland @weizhouapache is this good to merge?

**Comment by DaanHoogland** [comment]
let's make sure it doesn't cause the integration test failures

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test
