### PR TITLE
CKS: add ConfigDrive to cloud-init datasource_list in systemvm template

### LINKED ISSUE #7647: Unable to create a CKS cluster if the network offering contains userdata :ConfigDrive
##### ISSUE TYPE

 * Bug report

##### COMPONENT NAME

~~~

Component: cks, kubernetes

~~~

##### CLOUDSTACK VERSION

~~~
4.18 

~~~

##### SUMMARY

Unable to create a CKS cluster if the network offering contains userdata :Config

Steps to reporoduce the issue 

1. Create a network offering with userdata: config drive as supported services

2. Create an isolated network with network offering in step 1

3. Create CKS cluster 

Expected behaviour 
-----------
The CKS cluster should get created

Actual behaviour 
---------
The CKS cluster is not getting created, the cluster creation fails 

The reason could be due to systemvm template not supporting  ConfigDrive as data source

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7647 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
This requires a new systemvm template
cc @kiranchavala

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test the change, but have tested the URL fix - for the packer/systemvmtemplate build job (using my local jenkins instance)

**Comment by weizhouapache** [comment]
thanks @rohityadavcloud @DaanHoogland for review

I have kicked some trillian test using the new templates. The kvm/vmware test results (see previous comments) look good.
There were some test failures with xcpng82. I have rekick the trillian test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
this is on hold, because multiple datasources are not well-supported by cloud-init
the new systemvm template works well on kvm, but not on vmware/xen

File: tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh [hunk 1]
```diff
@@ -132,7 +132,7 @@ function configure_services() {
 
   # Disable cloud init by default
 cat <<EOF > /etc/cloud/cloud.cfg.d/cloudstack.cfg
-datasource_list: ['CloudStack']
+datasource_list: ['CloudStack', 'ConfigDrive']
```
Comment (rohityadavcloud) [inline tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh:135]: this can be fixed after the setup/init scripts @weizhouapache ? As cloud-init is disabled by default, the post-init or similar scripts can fix this and you won't need a new template for this?

Comment (weizhouapache) [reply tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh:135]: @rohityadavcloud 
yes, good idea.
we could use cloud-early-config to update the setting. It requires testing.
I will update this PR when #7828 is merged (new 4.18.1 systemvm template)

Comment (weizhouapache) [reply tools/appliance/systemvmtemplate/scripts/configure_systemvm_services.sh]: PR is updated
ugly but let's see if it works

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8 keepEnv

**Comment by weizhouapache** [comment]
this still needs some work

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 vmware-67u3

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it though, I reckon these must be covered by the CKS specific functional tests (if any?)

**Comment by weizhouapache** [comment]
moved to 4.18.2.0 as it needs more work

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
is this still a draft @weizhouapache ?

**Comment by weizhouapache** [comment]
> is this still a draft @weizhouapache ?

I think it is ready for review/testing

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@DaanHoogland @rohityadavcloud 
this PR needs a new systemvm template, moved to 4.20.0

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
not related to this PR but https://github.com/apache/cloudstack/actions/runs/8246502117/job/22552660211?pr=7650#step:6:9918

I think  a lint error slipped through

**Comment by weizhouapache** [comment]
> not related to this PR but https://github.com/apache/cloudstack/actions/runs/8246502117/job/22552660211?pr=7650#step:6:9918
> 
> I think  a lint error slipped through

As I remember, it has been fixed in main branch. @DaanHoogland

**Comment by DaanHoogland** [comment]
> As I remember, it has been fixed in main branch. @DaanHoogland

ok, is main the right target for this?

**Comment by weizhouapache** [comment]
> > As I remember, it has been fixed in main branch. @DaanHoogland
> 
> ok, is main the right target for this?

yes @DaanHoogland 
It requires a new systemvm template
The target branch is main, unless we will build 4.19.1 template. cc @sureshanaparti

**Comment by JoaoJandre** [comment]
@weizhouapache @DaanHoogland @rohityadavcloud  are we missing something or can we merge this PR?

**Comment by weizhouapache** [comment]
> @weizhouapache @DaanHoogland @rohityadavcloud are we missing something or can we merge this PR?

@JoaoJandre 
it has label `needs-testing`

**Comment by JoaoJandre** [comment]
> > @weizhouapache @DaanHoogland @rohityadavcloud are we missing something or can we merge this PR?
> 
> @JoaoJandre it has label `needs-testing`

Oh, I didn't see it :laughing:

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Review by JoaoJandre — APPROVED** [review]
LGTM, did not test it

**Comment by DaanHoogland** [comment]
@weizhouapache when we merge this we will need a new systemvm template, or is the current good enough right now? cc @JoaoJandre, @kiranchavala .

**Comment by weizhouapache** [comment]
@DaanHoogland 
I have manually kicked 3 smoke tests (ol8, vmware-80u3, xcpng82)  with new systemvm templates just now

**Review by kiranchavala — APPROVED** [review]
LGTM

Test manually on a kvm hypervisor 

Able to launch a cks cluster successfully on a isolated network

Steps

1. Registered the new systemvm template
2. Create a new network offering with userdata as config drive
3. Created a isolated network with the network offering mentioned step 1
4. Launch a cks cluster 

Performed lifecycle operations on the cks cluster like scaling, aquiring loadbalancer IP and destroying cks cluster

**Comment by weizhouapache** [comment]
> LGTM
> 
> Test manually on a kvm hypervisor
> 
> Able to launch a cks cluster successfully on a isolated network
> 
> Steps
> 
> 1. Registered the new systemvm template
> 2. Create a new network offering with userdata as config drive
> 3. Created a isolated network with the network offering mentioned step 1
> 4. Launch a cks cluster
> 
> Performed lifecycle operations on the cks cluster like scaling, aquiring loadbalancer IP and destroying cks cluster

thanks a lot @kiranchavala for the testing !

let's wait for smoke tests to be complete.

**Comment by DaanHoogland** [comment]
> let's wait for smoke tests to be complete.

@weizhouapache , I see three smoke test feedback replies above.
https://github.com/apache/cloudstack/pull/7650#issuecomment-2356258459 (failed)
https://github.com/apache/cloudstack/pull/7650#issuecomment-2356958992 (lots of errors)
https://github.com/apache/cloudstack/pull/7650#issuecomment-2357549944 (flawless) 

did you start any others?

**Comment by weizhouapache** [comment]
> > let's wait for smoke tests to be complete.
> 
> @weizhouapache , I see three smoke test feedback replies above. [#7650 (comment)](https://github.com/apache/cloudstack/pull/7650#issuecomment-2356258459) (failed) [#7650 (comment)](https://github.com/apache/cloudstack/pull/7650#issuecomment-2356958992) (lots of errors) [#7650 (comment)](https://github.com/apache/cloudstack/pull/7650#issuecomment-2357549944) (flawless)
> 
> did you start any others?

@DaanHoogland 
I have started test with vmware-70u3 and xenserver-74

the tests with xcpng82 and vmware-80u are unstable
refer to the test result of health check PR
https://github.com/apache/cloudstack/pull/9316#issuecomment-2348048158
https://github.com/apache/cloudstack/pull/9316#issuecomment-2357692800
https://github.com/apache/cloudstack/pull/9316#issuecomment-2358316463

**Comment by weizhouapache** [comment]
> @DaanHoogland @weizhouapache should we rerun the smoke tests?

@JoaoJandre 
just rerun some tests (ol8, vmware-70u3, xcpng76) on jenkins manually (as it requires new systemvm template)

**Comment by JoaoJandre** [comment]
@weizhouapache could we rerun just the xpcng tests? the tests for kvm and vmware look ok.

**Comment by JoaoJandre** [comment]
Merging based on reviews, manual testing (https://github.com/apache/cloudstack/pull/7650#pullrequestreview-2311789919) and CI results, the failures are not related to this PR
