### PR TITLE
LDAP: honour nested groups for MSAD

### LINKED ISSUE #10278: Microsoft AD LDAP configuration issues - not working for nested groups / CNs, but working for a single CN / Container / Group with only user's inside
### problem

I have got everything else working and tested, however I'm struggling with some of the functionality specifically related to user authentication.

In it's current state, it is working with authentication when I specify a single CN for the Ldap search group principle, but if I specify an AD Security Group /CN that contains additional CNs (three AD Security groups in this case), cloudstack does not return anything when I use the cloudmonkey command 'list ldapusers'.

I am using manual import mode for Microsoft AD - so I can manually import specific user's from within the CN named below.

I have verified everything is working on the AD side, and even using ldapsearch installed on the management server I can query the AD group and get all of the user's back correctly.

I have enabled nested groups within Global Settings > Access > LDAP and can confirm everything is working when I specify a single CN (I have tested all three that are within the group I'm attempting to use as the ldap.search.group.principle) - these 3 CN's only contains users, and do not contain any other CN's or groups or similar.

Here's my current settings:

ldap.basedn = DC=ads,DC=ntu,DC=ac,DC=uk
ldap.bind.password = REDACTED
ldap.bind.principal = CN=REDACTED,CN=Users,DC=ads,DC=ntu,DC=ac,DC=uk
ldap.email.attribute = mail
ldap.firstname.attribute = givenname
ldap.group.object = group
ldap.group.user.uniquemember = member
ldap.lastname.attribute = sn
ldap.nested.groups.enable = true
ldap.provider = microsoftad
ldap.read.timeout = 1000
ldap.request.page.size = 1000
ldap.search.group.principle = CN=CloudstackUsers,CN=Users,DC=ads,DC=ntu,DC=ac,DC=uk
ldap.user.memberof.attribute = memberof
ldap.user.object = user
ldap.username.attribute = SAMAccountName

I have also tried to change ldap.group.object to groupOfUniqueNames , and ldap.user.memberof.attribute to memberOf. The list ldapusers cloudmonkey command still works with these settings, and returns users, but like before - only when a CN which has no nested group memberships is used for ldap.search.group.principle

Image

Image

Image

The CN/Security Group in AD Group scope is set to 'Domain local', while the Groups within this are all set as 'Universal' - could this be a potential cause?

I also get no meaningful logs within '/var/log/cloudstack/management/management-server.log', I just get "2025-01-24 11:21:50,833 DEBUG [o.a.c.l.LdapContextFactory] (qtp1473611564-19:ctx-cb3f63e9 ctx-b55043b5 ctx-db6c3fa8) (logid:3e0ab5b3) initializing ldap with provider url: ldap://REDACTED.ads.ntu.ac.uk:3268
2025-01-24 11:21:51,204 TRACE [o.a.c.a.c.LdapListUsersCmd] (qtp1473611564-19:ctx-cb3f63e9 ctx-b55043b5 ctx-db6c3fa8) (logid:3e0ab5b3) returning unfiltered list of ldap users"

Please can you advise on the correct settings to use? I get the correct output when I run the following command on the Cloudstack management host, although I expect ldap-utils isn't explicitly used by Cloudstack itself, as I had to install it on the host first:

"ldapsearch -H ldap://REDACTED.ads.ntu.ac.uk:3268 -D "CN=REDACTED,CN=Users,DC=ads,DC=ntu,DC=ac,DC=uk" -W -b "DC=ads,DC=ntu,DC=ac,DC=uk" "(memberOf=CN=CloudstackUsers,CN=Users,DC=ads,DC=ntu,DC=ac,DC=uk)""

I have tried in vein to find any additional documentation on how to do this, but I can't find anything meaningful or verbose enough to describe the different attribute values.

As far as I understand, enabling nested groups should allow Cloudstack to traverse them, but I'm getting no meaningful output. I have also tried to increase the verbosity in the management-server.log by adding:

to

"/etc/cloudstack/management/log4j-cloud.xml"

But I get no additional information outputted in the management-server.log, just 'returning unfiltered list of ldap users'.

Please can you advise and assist on how I can move forward with this, and if I need to produce any additional logs/information.

### versions

I am using Cloudstack with 1 management server and 3 KVM hosts, all using Ubuntu 22.04 server, currently version 4.19.1.3, installed from fresh with version 4.19.

### The steps to reproduce the bug

1. Add ldap settings/attributes within the UI or using Cloudmonkey
2. Use Cloudmonkey 'list ldapusers' to return list of users
3. Observe no user's are returned
4. Change ldap.search.group.principle to a CN with no nested memberships
5. Use Cloudmonkey 'list ldapusers' to return list of users
6. Observe a list of users has been returned
7. Be confused as to why nested CNs are not working for ldap search group principle and do not return any users
...

### What to do about it?

Please can you advise and assist on how I can move forward with this, and if I need to produce any additional logs/information - I believe I have set all the ldap attributes correctly, as it works for CNs without any nested groups, but if a CN is selected that has other CNs inside, ldap user's are not observed.

### PR DESCRIPTION
**Pull request by DaanHoogland**
### Description

This PR makes sure the right memberOf attribute is retrieved in the case of MSAD ...

Fixes: #10278

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by rajujith** [comment]
@blueorangutan package

**Review by rajujith — APPROVED** [review]
LGTM.

Nested group users are listed now: 
```

(LL-ACS-KVM) 🐱 > list ldapusers
{
  "LdapUser": [
    {
      "conflictingusersource": "",
      "domain": "CN=aduser 1,OU=engineering",
      "firstname": "aduser",
      "lastname": "1",
      "principal": "CN=aduser 1,OU=engineering,DC=jithinraju,DC=in",
      "username": "aduser1"
    },
    {
      "conflictingusersource": "",
      "domain": "CN=aduser 2,OU=engineering",
      "firstname": "aduser",
      "lastname": "2",
      "principal": "CN=aduser 2,OU=engineering,DC=jithinraju,DC=in",
      "username": "aduser2"
    },
    {
      "conflictingusersource": "",
      "domain": "CN=aduser 500,OU=Architecture",
      "firstname": "aduser",
      "lastname": "500",
      "principal": "CN=aduser 500,OU=Architecture,DC=jithinraju,DC=in",
      "username": "aduser500"
    },
    {
      "conflictingusersource": "",
      "domain": "CN=Jithin Raju,OU=Architecture",
      "firstname": "Jithin",
      "lastname": "Raju",
      "principal": "CN=Jithin Raju,OU=Architecture,DC=jithinraju,DC=in",
      "username": "jithin"
    },
    {
      "conflictingusersource": "",
      "domain": "CN=Kiran Chavala,OU=engineering",
      "firstname": "Kiran",
      "lastname": "Chavala",
      "principal": "CN=Kiran Chavala,OU=engineering,DC=jithinraju,DC=in",
      "username": "kiran"
    },
    {
      "conflictingusersource": "",
      "domain": "CN=Vishesh Jindal,OU=engineering",
      "firstname": "Vishesh",
      "lastname": "Jindal",
      "principal": "CN=Vishesh Jindal,OU=engineering,DC=jithinraju,DC=in",
      "username": "vishesh"
    }
  ],
  "count": 6
```

Screenshot 2025-09-23 at 11 39 17 AM

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/OpenLdapUserManagerImpl.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ private String generateSearchFilter(final String username, Long domainId) {
         usernameFilter.append((username == null ? "*" : LdapUtils.escapeLDAPSearchFilter(username)));
         usernameFilter.append(")");
 
-        String memberOfAttribute = _ldapConfiguration.getUserMemberOfAttribute(domainId);
+        String memberOfAttribute = getMemberOfAttribute(domainId);
```
Comment (weizhouapache) [inline plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/OpenLdapUserManagerImpl.java:90]: @DaanHoogland 
there is a method in the same file
```
    protected String getMemberOfAttribute(final Long domainId) {
        return _ldapConfiguration.getUserMemberOfAttribute(domainId);
    }
```

which is used only once
```
        if ("GROUP".equals(type)) {
            memberOfFilter.append("(").append(getMemberOfAttribute(domainId)).append("=");
            memberOfFilter.append(name);
            memberOfFilter.append(")"); 
        }
```


is it correct ?

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java [hunk 2]
```diff
@@ -93,10 +93,14 @@ protected boolean isUserDisabled(SearchResult result) throws NamingException {
...
     protected String getMemberOfAttribute(final Long domainId) {
+        String rc;
         if(_ldapConfiguration.isNestedGroupsEnabled(domainId)) {
-            return MICROSOFT_AD_NESTED_MEMBERS_FILTER;
+            rc = MICROSOFT_AD_NESTED_MEMBERS_FILTER;
         } else {
-            return MICROSOFT_AD_MEMBERS_FILTER;
+            rc = MICROSOFT_AD_MEMBERS_FILTER;
         }
+        logger.debug("memberOf filter = " + rc);
```
Comment (weizhouapache) [inline plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java]: it this debugging message needed ? if yes, can we add more details ?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@DaanHoogland 
I changed the target branch from main to 4.20

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java (hunk 2 above)
Comment (DaanHoogland) [reply plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java]: it is debug message to ensure the AD provider is used and in the right way.

We could remove or make it trace.

the only detail to add at this point is the domainid.
```suggestion
        logger.trace(“using memberOf filter = {} for domain with id {}”, rc, domainId);
```

Is that what you mean, @weizhouapache ?

Comment (weizhouapache) [reply plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java]: yes @DaanHoogland

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/OpenLdapUserManagerImpl.java (hunk 1 above)
Comment (DaanHoogland) [reply plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/OpenLdapUserManagerImpl.java:90]: yes, but it is overloaded in the AD user manager, so at this point it is not known which one will be called.

**Review by weizhouapache — APPROVED** [review]
code lgtm

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java [hunk 3]
```diff
@@ -93,10 +93,14 @@ protected boolean isUserDisabled(SearchResult result) throws NamingException {
...
     protected String getMemberOfAttribute(final Long domainId) {
+        String rc;
         if(_ldapConfiguration.isNestedGroupsEnabled(domainId)) {
-            return MICROSOFT_AD_NESTED_MEMBERS_FILTER;
+            rc = MICROSOFT_AD_NESTED_MEMBERS_FILTER;
         } else {
-            return MICROSOFT_AD_MEMBERS_FILTER;
+            rc = MICROSOFT_AD_MEMBERS_FILTER;
         }
+        logger.trace(“using memberOf filter = {} for domain with id {}”, rc, domainId);
```
Comment (DaanHoogland) [inline plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/ADLdapUserManagerImpl.java]:
```suggestion
        logger.trace("using memberOf filter = {} for domain with id {}", rc, domainId);
```

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
Merging based on approvals and test

thanks @DaanHoogland @rajujith
