### PR TITLE
server: fix exception while list users with keyword

### LINKED ISSUE #7165: UI - SQL error when searching/filtering on accountuser page
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
Tested on
* 4.17.2.0
* 4.17.0.1

##### CONFIGURATION
Standard install.

##### OS / ENVIRONMENT
Rocky Linux 8

##### SUMMARY
I am getting the following error message in the web console when trying to search for a specific user account.

```
Request failed. (530)
Caught: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT user_view.id, user_view.uuid, user_view.username, user_view.password, user_view.firstname, user_view.lastname, user_view.email, user_view.state, user_view.api_key, user_view.secret_key, user_view.created, user_view.removed, user_view.timezone, user_view.registration_token, user_view.is_registered, user_view.incorrect_login_attempts, user_view.account_id, user_view.account_uuid, user_view.account_name, user_view.account_type, user_view.account_role_id, user_view.domain_id, user_view.domain_uuid, user_view.domain_name, user_view.domain_path, user_view.job_id, user_view.job_uuid, user_view.job_status, user_view.default, user_view.source FROM user_view WHERE user_view.account_type != 5 AND user_view.id != 1 AND (user_view.username LIKE x'257573657225' OR user_view.firstname LIKE x'257573657225' OR user_view.lastname LIKE x'257573657225' OR user_view.email LIKE x'257573657225' OR user_view.state LIKE x'257573657225' OR user_view.account_name LIKE x'257573657225' OR user_view.account_type LIKE ** NOT SPECIFIED ** ) AND user_view.removed IS NULL ORDER BY user_view.id ASC LIMIT 0, 50
```

The page I am trying to search on is the `/#/accountuser` page.

##### STEPS TO REPRODUCE
1. Log in to CloudStack UI
2. Click on 'Accounts'
3. Click on any account
4. Click on 'View Users'
5. On the user list page (i.e. the /#/accountuser page, eg. https://cloudstack.example.com/client/#/accountuser), use the search box at the top right of the user table.
6. The 'Request failed' error appears.

##### EXPECTED RESULTS
The user table should be filtered by the search.

##### ACTUAL RESULTS
A '500 Internal Server Error.' page is displayed.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7165 

old:

```
(localcloud) 🐱 > list users keyword=ADMIN
🙈 Error: (HTTP 530, error code 4250) Caught: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT user_view.id, user_view.uuid, user_view.username, user_view.password, user_view.firstname, user_view.lastname, user_view.email, user_view.state, user_view.api_key, user_view.secret_key, user_view.created, user_view.removed, user_view.timezone, user_view.registration_token, user_view.is_registered, user_view.incorrect_login_attempts, user_view.account_id, user_view.account_uuid, user_view.account_name, user_view.account_type, user_view.account_role_id, user_view.domain_id, user_view.domain_uuid, user_view.domain_name, user_view.domain_path, user_view.job_id, user_view.job_uuid, user_view.job_status, user_view.default, user_view.source FROM user_view WHERE user_view.account_id=2 AND user_view.account_type != 5  AND user_view.id != 1  AND  (user_view.username LIKE x'2541444D494E25'  OR user_view.firstname LIKE x'2541444D494E25'  OR user_view.lastname LIKE x'2541444D494E25'  OR user_view.email LIKE x'2541444D494E25'  OR user_view.state LIKE x'2541444D494E25'  OR user_view.account_name LIKE x'2541444D494E25'  OR user_view.account_type = ** NOT SPECIFIED ** )  AND user_view.removed IS NULL  ORDER BY user_view.id ASC  LIMIT 0, 500
```

new:

```
(localcloud) 🐱 > list users keyword=admin listall=true  filter=username,roletype
{
  "count": 3,
  "user": [
    {
      "roletype": "Admin",
      "username": "admin"
    },
    {
      "roletype": "Admin",
      "username": "admin-kubeadmin"
    },
    {
      "roletype": "DomainAdmin",
      "username": "testadmin"
    }
  ]
}
```

and
```
(localcloud) 🐱 > list users keyword=domain_admin listall=true  filter=username,roletype
{
  "count": 1,
  "user": [
    {
      "roletype": "DomainAdmin",
      "username": "testadmin"
    }
  ]
}
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by DaanHoogland** [comment]
how about `list users keyword=ADMIN` like what gave the initial exception, now?

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 1]
```diff
@@ -617,7 +618,9 @@ private Pair<List<UserAccountJoinVO>, Integer> getUserListInternal(Account calle
             ssc.addOr("email", Op.LIKE, "%" + keyword + "%");
             ssc.addOr("state", Op.LIKE, "%" + keyword + "%");
             ssc.addOr("accountName", Op.LIKE, "%" + keyword + "%");
-            ssc.addOr("accountType", Op.LIKE, "%" + keyword + "%");
+            if (EnumUtils.isValidEnum(Account.Type.class, keyword.toString().toUpperCase())) {
+                ssc.addOr("accountType", Op.EQ, EnumUtils.getEnum(Account.Type.class, keyword.toString().toUpperCase()));
+            }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:623]: can this be simpler using `Account.Type.valueof(keyword)`? also I think `keyword` does not need a `.toString()`call.

Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:623]: @DaanHoogland 
is valueOf case sensitive ?

**Comment by vladimirpetrov** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 1 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:623]: no, but a `toUpperCase()` can be added, and still the `toString()` can be dropped. It will return null if no value is found. I.E.
```suggestion
            try {
                if (Account.Type.valueOf(keyword.toUpperCase())) {
                    ssc.addOr("accountType", Op.EQ, EnumUtils.getEnum(Account.Type.class, keyword.toUpperCase()));
                }
            } catch ([IllegalArgumentException e) {
                logger.trace("keyword does not cantain an Account.Type");
            }
```
on second thought not really simpler or more legible, unless we let the exception trickle up. ´) never mind.

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 2]
```diff
@@ -617,7 +618,9 @@ private Pair<List<UserAccountJoinVO>, Integer> getUserListInternal(Account calle
             ssc.addOr("email", Op.LIKE, "%" + keyword + "%");
             ssc.addOr("state", Op.LIKE, "%" + keyword + "%");
             ssc.addOr("accountName", Op.LIKE, "%" + keyword + "%");
-            ssc.addOr("accountType", Op.LIKE, "%" + keyword + "%");
+            if (EnumUtils.isValidEnum(Account.Type.class, keyword.toString().toUpperCase())) {
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:621]: we discussed off-line to make `keyword` a string. Will you do that @weizhouapache ?

**Review by stephankruggg — APPROVED** [review]
CLGTM, did not manually test it

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 2 above)
Comment (weizhouapache) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java]: thanks @DaanHoogland 
done

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
errors are not specific to this PR and addressed in #7190 
merging with twoo LGTM and manual testing
