### PR TITLE
kvm: honour disk controller for vm during attach volume

### LINKED ISSUE #12090: [CloudStack 4.20.1.0]Extra lsilogic SCSI controller on aarch64 causes last disk unrecognized
### Environment
- CloudStack Version: 4.20.1.0
- CPU Architecture: aarch64
- Hypervisor: KVM
- UEFI Configuration (relevant for aarch64 VM boot, from `/etc/cloudstack/agent/uefi.properties`):
```
# CloudStack Agent UEFI Configuration for ARM64
# This file configures UEFI boot support for ARM64 virtual machines

# Secure boot mode with Microsoft keys
guest.nvram.template.secure=/usr/share/AAVMF/AAVMF_VARS.ms.fd
guest.loader.secure=/usr/share/AAVMF/AAVMF_CODE.ms.fd

# Secure boot mode without Microsoft keys
guest.nvram.template.secboot=/usr/share/AAVMF/AAVMF_VARS.fd
guest.loader.secboot=/usr/share/AAVMF/AAVMF_CODE.secboot.fd

# Standard UEFI mode (default)
guest.nvram.template.legacy=/usr/share/AAVMF/AAVMF_VARS.fd
guest.loader.legacy=/usr/share/AAVMF/AAVMF_CODE.fd

# No secure boot mode (explicitly disabled)
guest.nvram.template.nosecboot=/usr/share/AAVMF/AAVMF_VARS.fd
guest.loader.nosecboot=/usr/share/AAVMF/AAVMF_CODE.no-secboot.fd

# NVRAM storage path
guest.nvram.path=/var/lib/libvirt/qemu/nvram/
```

### Problem Description
When attaching multiple disks to an aarch64 VM, CloudStack incorrectly adds an **extra lsilogic SCSI controller** after allocating virtio-scsi controllers for every 7 disks. This causes the **last disk** to be unrecognized after VM reboot.

**Key Evidence:** The second SCSI controller switches from `virtio-scsi` to `lsilogic` after reboot.

### Reproduction Steps
1. Deploy an aarch64 VM with 5 disks → all recognized correctly under `virtio-scsi` controller
2. Hot-add a 6th disk while VM running → temporarily works, creates second `virtio-scsi` controller
3. Shutdown and restart the VM → second controller becomes `lsilogic`, 6th disk disappears

### Expected Behavior
All disks assigned to `virtio-scsi` controllers, no `lsilogic` controller added.

### Actual Behavior (with Evidence)
```xml
After reboot - WRONG
<controller type='scsi' index='1' model='lsilogic'>
Should be:  <controller type='scsi' index='1' model='virtio-scsi'>
```

### Related Code
PR #9823 (bug at the end of implementation)

### Attachments
```xml
Step 1: Initial State (5 disks attached)
root@NODE159:/var/log/cloudstack/agent# virsh dumpxml i-2-971-VM  | grep controller
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='2'/>
      <address type='drive' controller='0' bus='0' target='0' unit='4'/>
      <address type='drive' controller='0' bus='0' target='0' unit='5'/>
      <address type='drive' controller='0' bus='0' target='0' unit='6'/>
    <controller type='usb' index='0' model='qemu-xhci'>
    </controller>
    <controller type='scsi' index='0' model='virtio-scsi'>
    </controller>
    <controller type='pci' index='0' model='pcie-root'>
    </controller>
    <controller type='virtio-serial' index='0'>
    </controller>
    <controller type='pci' index='1' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='7' model='pcie-to-pci-bridge'>
    </controller>
    <controller type='pci' index='8' model='pcie-root-port'>
    </controller>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>

Step 2: Hot-add 6th disk while VM running,witch device id is 7
root@NODE159:/var/log/cloudstack/agent# virsh dumpxml i-2-971-VM  | grep controller
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='2'/>
      <address type='drive' controller='0' bus='0' target='0' unit='4'/>
      <address type='drive' controller='0' bus='0' target='0' unit='5'/>
      <address type='drive' controller='0' bus='0' target='0' unit='6'/>
      <address type='drive' controller='1' bus='0' target='0' unit='0'/>
    <controller type='usb' index='0' model='qemu-xhci'>
    </controller>
    <controller type='scsi' index='0' model='virtio-scsi'>
    </controller>
    <controller type='scsi' index='1' model='virtio-scsi'>
    </controller>
    <controller type='pci' index='0' model='pcie-root'>
    </controller>
    <controller type='virtio-serial' index='0'>
    </controller>
    <controller type='pci' index='1' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='7' model='pcie-to-pci-bridge'>
    </controller>
    <controller type='pci' index='8' model='pcie-root-port'>
    </controller>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
Step 3: Reboot VM
root@NODE159:/var/log/cloudstack/agent# virsh dumpxml i-2-971-VM  | grep controller
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='2'/>
      <address type='drive' controller='0' bus='0' target='0' unit='4'/>
      <address type='drive' controller='0' bus='0' target='0' unit='5'/>
      <address type='drive' controller='0' bus='0' target='0' unit='6'/>
      <address type='drive' controller='1' bus='0' target='0' unit='0'/>
    <controller type='usb' index='0' model='qemu-xhci'>
    </controller>
    <controller type='scsi' index='0' model='virtio-scsi'>
    </controller>
    <controller type='pci' index='0' model='pcie-root'>
    </controller>
    <controller type='scsi' index='1' model='lsilogic'>    <!-- BUG: Should be virtio-scsi -->
    </controller>
    <controller type='virtio-serial' index='0'>
    </controller>
    <controller type='pci' index='1' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
    </controller>
    <controller type='pci' index='7' model='pcie-to-pci-bridge'>
    </controller>
    <controller type='pci' index='8' model='pcie-root-port'>
    </controller>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
root@NODE159:/var/log/cloudstack/agent# 
```

### versions

- CloudStack Version: 4.20.1.0
- CPU Architecture: aarch64
- Hypervisor: KVM

### The steps to reproduce the bug

1.Initial State 5 disks attached
2.Hot-add 6th disk while VM running
3.reboot VM
...

Image

### What to do about it?

_No response_

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #12090

Some years back #4569 allowed honouring dataDiskController for KVM VMs during start but the same behviour is not seen while attaching a volume to a running VM.
This PR first checks in the AttachCommand if a valid controller is present. If a valid controller/bus type is not present than existing logic is used.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 1]
```diff
@@ -1320,64 +1320,68 @@ protected boolean checkDetachSuccess(String diskPath, Domain dm) throws LibvirtE
...
 
     /**
      *
      * Attaches or detaches a disk to an instance.
-     * @param conn libvirt connection
-     * @param attach boolean that determines whether the device will be attached or detached
-     * @param vmName instance name
-     * @param attachingDisk kvm physical disk
-     * @param devId device id in instance
+     *
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java]: i think current practice is that blank lines are not desirable in javadoc (iianm)

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by DaanHoogland** [comment]
@blueorangutan package

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 2]
```diff
@@ -1320,64 +1320,68 @@ protected boolean checkDetachSuccess(String diskPath, Domain dm) throws LibvirtE
...
+     * @param conn                    libvirt connection
+     * @param attach                  boolean that determines whether the device will be attached or detached
+     * @param vmName                  instance name
+     * @param attachingDisk           kvm physical disk
```
Comment (shwstppr) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java]:
```suggestion
     * @param conn                    libvirt connection
     * @param attach                  boolean that determines whether the device will be attached or detached
     * @param vmName                  instance name
     * @param attachingDisk           kvm physical disk
```

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java [hunk 3]
```diff
@@ -1320,64 +1320,67 @@ protected boolean checkDetachSuccess(String diskPath, Domain dm) throws LibvirtE
 
     /**
      * Attaches or detaches a disk to an instance.
-     * @param conn libvirt connection
-     * @param attach boolean that determines whether the device will be attached or detached
-     * @param vmName instance name
-     * @param attachingDisk kvm physical disk
-     * @param devId device id in instance
+     *
+     * @param conn                    libvirt connection
```
Comment (shwstppr) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java]:
```suggestion
     * @param conn                    libvirt connection
```

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by kiranchavala — APPROVED** [review]
LGTM

Followed the steps mentioned here

https://github.com/apache/cloudstack/issues/12090#issuecomment-3685607332

After adding the sixth disk , it was correctly assigned scsi driver 

```
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/mnt/9dde54d6-ebe4-3f4e-b185-c88bf7419bfd/bd33ea5a-df96-4449-9b12-f58c1ff4a9ac' index='6'/>
      <backingStore/>
      <target dev='sdb' bus='scsi'/>
      <serial>bd33ea5adf9644499b12</serial>
      <alias name='scsi0-0-0-1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/mnt/9dde54d6-ebe4-3f4e-b185-c88bf7419bfd/2837aa76-1adb-4d0b-b287-b8eabb8ece77' index='5'/>
      <backingStore/>
      <target dev='sdc' bus='scsi'/>
      <serial>2837aa761adb4d0bb287</serial>
      <alias name='scsi0-0-0-2'/>
      <address type='drive' controller='0' bus='0' target='0' unit='2'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/mnt/9dde54d6-ebe4-3f4e-b185-c88bf7419bfd/a3ccfebd-b3f6-4a23-975f-6fc178cd54d4' index='4'/>
      <backingStore/>
      <target dev='sde' bus='scsi'/>
      <serial>a3ccfebdb3f64a23975f</serial>
      <alias name='scsi0-0-0-4'/>
      <address type='drive' controller='0' bus='0' target='0' unit='4'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/mnt/734738cb-cf21-3b12-aa39-f007af1044ea/64f2bfa6-a7c3-4d44-a195-5eda2be1e59b' index='3'/>
      <backingStore/>
      <target dev='sdf' bus='scsi'/>
      <serial>64f2bfa6a7c34d44a195</serial>
      <alias name='scsi0-0-0-5'/>
      <address type='drive' controller='0' bus='0' target='0' unit='5'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/mnt/9dde54d6-ebe4-3f4e-b185-c88bf7419bfd/9007dd03-6806-410c-8c1e-94ac0e2e4e28' index='2'/>
      <backingStore/>
      <target dev='sdg' bus='scsi'/>
      <serial>9007dd036806410c8c1e</serial>
      <alias name='scsi0-0-0-6'/>
      <address type='drive' controller='0' bus='0' target='0' unit='6'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' discard='unmap'/>
      <source file='/mnt/9dde54d6-ebe4-3f4e-b185-c88bf7419bfd/97b78eb6-7be1-4081-a52d-faa7c8056ee7' index='9'/>
      <backingStore/>
      <target dev='sdh' bus='scsi'/>
      <serial>97b78eb67be14081a52d</serial>
      <alias name='scsi1-0-0-0'/>
      <address type='drive' controller='1' bus='0' target='0' unit='0'/>
    </disk>

```

**Comment by DaanHoogland** [comment]
this is ready for merge, @shwstppr ?

**Comment by shwstppr** [comment]
@DaanHoogland I've marked it ready though I'm not completely sure if this would solve the original issue reported in #12090 but definitely solves Kiran's case

**Comment by DaanHoogland** [comment]
ok, will not close the issue (yet) but doesn’t hurt to merge than.
