### PR TITLE
xenserver: retrieve correct name-label for presetup store

### LINKED ISSUE #4729: XenServer, management server sends pool UUID instead of the PATH, as the SR name
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0 tested
~~~

##### CONFIGURATION

Original Cloudplatform 4.7.1 with XenServer with preSetup storage (iscis) - all this is less relevant, see down

##### OS / ENVIRONMENT

NA

##### SUMMARY

After upgrading ACP 4.7.1 to ACS 4.14.0.0, preSetup storage type can not be mounted on XS servers, as ACS DB is sending UUID (instead of the pool name) to the XS to mount it - see details below

DB upgraded to 4.14, but the same data is in 4.7.1 before the upgrade - storage_pool table:

                   id: 2
                 name: XenServer-Primary
                 **uuid: 1e189b97-974d-35b6-bc76-50bca7704ea0**
            pool_type: PreSetup
                 port: 0
       data_center_id: 2
               pod_id: 2
           cluster_id: 3
           used_bytes: 28898754560
       capacity_bytes: 214714810368
         host_address: localhost
            user_info: NULL
                 path: /XEN_PRIMARY
              created: 2021-02-24 10:38:37
              removed: NULL
          update_time: NULL
               status: Maintenance
               storage_provider_name: DefaultPrimary
                scope: CLUSTER
           hypervisor: NULL
              managed: 0
        capacity_iops: NULL

In CLoudPlatform 4.7.1. this used to work fine, "PATH" filed was sent as the SR name to the XS to mount it.

In CloudStack 4.14.0.0, mgmt server sends UUID (1e189b97-974d-35b6-bc76-50bca7704ea0) as the SR name parameter for XS when mounting it, instead of "path" (XEN_PRIMARY), so the SR mount fails:

2021-02-25 03:49:45,306 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-3:ctx-7a7ee26b job-118/job-119 ctx-6e3dd2e5) (logid:edf9d62a) Unable to contact resource.
com.cloud.exception.StorageUnavailableException: Resource [StoragePool:2] is unreachable: Unable to create Vol[26|vm=26|ROOT]:**There are 0 SRs with same name: 1e189b97-974d-35b6-bc76-50bca7704ea0**

The workaround was (this is customer env) to replace UUID value with the value of the "PATH" field so that XS can mount it (what consequences this might have, is unknown)

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #4729

As reported in the issue ACP 4.7 used a normal UUID in db for a presetup primary store on Xenserver.
Later the value has been changed to store's path with '/' removed.
Current changes try to retrieve SR's name-lable from store's path if UUID doesn't match path field for a pre-setup store.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java [hunk 1]
```diff
@@ -44,4 +46,12 @@ public static String getPVbootloaderArgs(String guestOS) {
         }
         return "";
     }
+
+    public static String getSRNameLabel(final StorageFilerTO primaryStore) {
+        if (Storage.StoragePoolType.PreSetup.equals(primaryStore.getType()) &&
+                !primaryStore.getPath().contains(primaryStore.getUuid())) {
+            return  primaryStore.getPath().replace("/", "");
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java:53]: doesn't this replace all '/'? seems dangerous to me

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java [hunk 2]
```diff
@@ -96,6 +96,14 @@ public XenServerStorageProcessor(final CitrixResourceBase resource) {
         hypervisorResource = resource;
     }
 
+    protected String getSRNameLabel(final PrimaryDataStoreTO primaryStore) {
+        if (Storage.StoragePoolType.PreSetup.equals(primaryStore.getPoolType()) &&
+                !primaryStore.getPath().contains(primaryStore.getUuid())) {
+            return  primaryStore.getPath().replace("/", "");
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java:102]: as above. Make sure it is only the last one being replaced.

Comment (DaanHoogland) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java:102]: also why is this method double implemented? here and in CitrixHelper? <quote style='ominous'>there can be only one</quote>

**Review by DaanHoogland — CHANGES_REQUESTED** [review]

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java (hunk 1 above)
Comment (shwstppr) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java:53]: https://github.com/apache/cloudstack/blob/4.15/plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java#L340-L342

Primary store setup code uses the same. I can change this though.
For pre-setup SR path is `/SR_NAME_LABEL` so it might not be as dangerous as it looks.

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java (hunk 2 above)
Comment (shwstppr) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java:102]: `StorageFilerTO`, `PrimaryDataStoreTO` and `StoragePool` different classes

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java [hunk 3]
```diff
@@ -326,7 +327,13 @@ private Answer migrateVmWithVolumesAcrossCluster(VMInstanceVO vm, VirtualMachine
                     volumeToStorageUuid.add(new Pair<>(volumeTo, iqn));
                 }
                 else {
-                    volumeToStorageUuid.add(new Pair<>(volumeTo, ((StoragePool)entry.getValue()).getUuid()));
+                    StoragePool pool = (StoragePool)entry.getValue();
+                    String srNameLabel = pool.getUuid();
+                    if (Storage.StoragePoolType.PreSetup.equals(pool.getPoolType()) &&
+                            !pool.getPath().contains(pool.getUuid())) {
+                        srNameLabel = pool.getPath().replaceFirst("/", "");
+                    }
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/org/apache/cloudstack/storage/motion/XenServerStorageMotionStrategy.java:335]:
```suggestion
                    Sting srNameLabel = CitrixHelper.getSRNameLabel(pool.getUuid(), pool.getPoolType(), pool.getPath())
```
or if need be put the usitlity method elsewere, but make sure it only exists once!?

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java [hunk 4]
```diff
@@ -44,4 +45,14 @@ public static String getPVbootloaderArgs(String guestOS) {
         }
         return "";
     }
+
+    public static String getSRNameLabel(final String poolUuid,
+                                        final Storage.StoragePoolType poolType,
+                                        final String poolPath) {
+        if (Storage.StoragePoolType.PreSetup.equals(poolType) &&
+                !poolPath.contains(poolUuid)) {
```
Comment (DaanHoogland) [inline plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java:53]: aren't there any presetup scenarios where the path could contain the uuid?

**Review by DaanHoogland — COMMENTED** [review]
1 comment, 1 question

**Comment by davidjumani** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by Pearl1594** [comment]
Manually verified the fix - performing the following steps:
- Created an env with nfs stores
- Marked one store as deleted / removed from the db and re-added that store to cloudstack using presetup protocol
- updated the storage_pool table for that corresponding record and replaced uuid field which is currently set to the sr name-label to the actual uuid  of the sr as seen with xe sr-list -> at this point, we have a record similar to what it would have been if the pool  were registered in CloudPlatform 4.7 
- Successfully deployed a VM with its volume on the pool that was added / manipulated as stated above
- Migrated a volume to the storage pool in question and ACS was able to correctly map the uuid to the sr name label

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java (hunk 4 above)
Comment (shwstppr) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/CitrixHelper.java:53]: @DaanHoogland For presetup pools, UUID in DB is set as the path of the pool (without `/`)
But in ACP it was using real UUIDs as reported in the linked issue.
So my change is just to use path (without `/`) when there is a mismatch between path and UUID and the pool is of type presetup

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by Pearl1594** [comment]
blueorangutan test centos7 xenserver-71

**Comment by Pearl1594** [comment]
@blueorangutan test centos7 xenserver-71

File: plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java (hunk 2 above)
Comment (DaanHoogland) [reply plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/XenServerStorageProcessor.java]: Yes, @shwstppr but different classes implementing the exact same doesn't like right to me. It seems to me
1. the method should be a utility (easy dirty quick solution) or
2. the storage path should have it's own class that is referred from all three users of the path.

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Comment by rhtyd** [comment]
@blueorangutan test centos7 xenserver-71

**Review by DaanHoogland — APPROVED** [review]
code looks good

**Comment by rhtyd** [comment]
@Pearl1594 are you testing this, or lgtm on merging this?

**Comment by Pearl1594** [comment]
@rhtyd It's already been tested (https://github.com/apache/cloudstack/pull/4816#issuecomment-806649136). It's ready for merging

**Review by Pearl1594 — APPROVED** [review]
LGTM
