### PR TITLE
Timeout config to copy the disks of remote KVM instance while importing the instance from an external host

### LINKED ISSUE #8819: Timeout with large KVM virtual machines not being imported
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI / Migration
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A

##### SUMMARY

When migrating a virtual machine from a remote KVM which has a large disk a timeout occurs, on the remote host you can see the qemu convert option running which I think takes too long and then SSH times out. 

##### STEPS TO REPRODUCE

~~~
Have  remote KVM host and try to import a large KVM vm (here it stopped at 47GB already) but might depend on the speed of the storage too.

~~~

##### EXPECTED RESULTS

~~~
That the virtual machine imported succesfully
~~~

##### ACTUAL RESULTS

~~~
On the GUI the following is displayed:

"Failed to import volumes while importing vm: test vm. Error while copying volume".

On the agent log of the cloudstack server it's trying to copy it too you can see the following:
2024-03-21 14:05:28,673 ERROR [utils.ssh.SshHelper] (agentRequest-Handler-5:null) (logid:55e6fedb) Timed out in waiting for SSH execution exit status
2024-03-21 14:05:28,674 ERROR [resource.wrapper.LibvirtCopyRemoteVolumeCommandWrapper] (agentRequest-Handler-5:null) (logid:55e6fedb) Error while copying file from remote host: com.cloud.utils.ssh.SshException: Timed out in waiting for SSH execution exit status

In the journal log on the remote host you can see it connected on SSH:
Mar 21 14:03:28 sshd[2790590]: Accepted password for root from IP port 44740 ssh2
Mar 21 14:03:28 sshd[2790590]: pam_unix(sshd:session): session opened for user root(uid=0) by (uid=0)
Mar 21 14:03:28 systemd-logind[897]: New session 601 of user root.
Mar 21 14:03:28 systemd[1]: Started session-601.scope - Session 601 of User root.
Mar 21 14:03:28 sshd[2790590]: pam_env(sshd:session): deprecated reading of user environment enabled
Mar 21 14:05:28 sshd[2790590]: Received disconnect from IP port 44740:11: Closed due to user request.

Already tried to try and have a longer SSH session by setting

ClientAliveInterval 600
ClientAliveCountMax 6

in the SSHD file but that didn't change much, but maybe I need to change a different setting?
~~~

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR introduces the timeout config `remote.kvm.instance.disks.copy.timeout` to copy the disks of remote KVM instance while importing the instance from an external host.

Fixes #8819 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Manually tested import KVM instance. Updated config `remote.kvm.instance.disks.copy.timeout` to 2 hrs.

```
2024-06-11 12:20:05,713 DEBUG [kvm.resource.LibvirtComputingResource] (agentRequest-Handler-3:null) (logid:4f6cb0fd) Converting remote disk file: /root/kvm.qcow2, output file: 532ca85a-40e2-428c-9d9e-929b48a3ef95 (timeout: 7200 secs)

...
2024-06-11 12:20:05,853 DEBUG [resource.wrapper.LibvirtGetRemoteVmsCommandWrapper] (agentRequest-Handler-2:null) (logid:3f8ed04d) Found Vms: 1
2024-06-11 12:20:05,934 DEBUG [kvm.resource.LibvirtComputingResource] (agentRequest-Handler-3:null) (logid:4f6cb0fd) Copying converted remote disk file 532ca85a-40e2-428c-9d9e-929b48a3ef95 to: /mnt/2298fac9-2cf7-371f-b735-17066eb3a87a
2024-06-11 12:20:06,090 DEBUG [kvm.resource.LibvirtComputingResource] (agentRequest-Handler-3:null) (logid:4f6cb0fd) Successfully copied converted remote disk file to: /mnt/2298fac9-2cf7-371f-b735-17066eb3a87a/532ca85a-40e2-428c-9d9e-929b48a3ef95
2024-06-11 12:20:06,090 DEBUG [resource.wrapper.LibvirtCopyRemoteVolumeCommandWrapper] (agentRequest-Handler-3:null) (logid:4f6cb0fd) Volume /root/kvm.qcow2 copy successful, copied to file: 532ca85a-40e2-428c-9d9e-929b48a3ef95
```

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by rohityadavcloud — APPROVED** [review]
LGTM - needs to be tested

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: api/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManager.java [hunk 1]
```diff
@@ -30,6 +30,15 @@ public interface UnmanagedVMsManager extends VmImportService, UnmanageVMService,
             "If set to true, do not remove VM nics (and its MAC addresses) when unmanaging a VM, leaving them allocated but not reserved. " +
                     "If set to false, nics are removed and MAC addresses can be reassigned", true, ConfigKey.Scope.Zone);
 
+    ConfigKey<Integer> RemoteKvmInstanceDisksCopyTimeout = new ConfigKey<>(Integer.class,
+            "remote.kvm.instance.disks.copy.timeout",
+            "Advanced",
+            "1",
```
Comment (vishesh92) [inline api/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManager.java:36]: Should we keep this in minutes instead?

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 2]
```diff
@@ -5336,18 +5336,18 @@ public void setInterfaceDefQueueSettings(Map<String, String> details, Integer cp
...
             String outputFile = UUID.randomUUID().toString();
             StringBuilder command = new StringBuilder("qemu-img convert -O qcow2 ");
             command.append(remoteFile);
-            command.append(" "+tmpPath);
+            command.append(" " + tmpPath);
             command.append(outputFile);
-            s_logger.debug("Converting remoteFile: "+remoteFile);
-            SshHelper.sshExecute(srcIp, 22, username, null, password, command.toString());
-            s_logger.debug("Copying remoteFile to: "+localDir);
+            s_logger.debug(String.format("Converting remote disk file: %s, output file: %s (timeout: %d secs)", remoteFile, outputFile, timeoutInSecs));
```
Comment (vishesh92) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:5346]: Do we need to remove any intermediate files created in case of a timeout?

File: api/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManager.java (hunk 1 above)
Comment (sureshanaparti) [reply api/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManager.java:36]: import from vmware is set in hrs, so thought to keep the same - will convert to mins.

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java (hunk 2 above)
Comment (sureshanaparti) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:5346]: will check, and remove if required

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
clgtm. Didn't test.

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
Tested with a remote KVM host.
By setting `remote.kvm.instance.disks.copy.timeout` to a very small value,  got the below error:
```
Error
Failed to import volumes while importing vm: guest1-rhel7. Error while copying volume of remote instance: Failed to copy volume due to: com.cloud.utils.ssh.SshException: Timed out in waiting for SSH execution exit status
```
Increasing the timeout fixes the issue.

**Comment by vishesh92** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
Merging based on reviews, manual / smoke tests.
