### PR TITLE
Mark LDAP user query timeout as incorrect login instead of disabling user immediately

### LINKED ISSUE #11199: LDAP user disabled after response timed out
### problem

When the LDAP server response timed out, CloudStack immediately disables the user.

`javax.naming.NamingException: LDAP response read timed out, timeout used: 1000 ms. 
`

User is disabled from here: https://github.com/apache/cloudstack/blob/6059724189759470208a8e135744314119323534/plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapAuthenticator.java#L175-L177

https://github.com/apache/cloudstack/blob/6059724189759470208a8e135744314119323534/plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapManagerImpl.java#L305-L307

### versions

ACS 4.20.1 

### The steps to reproduce the bug

1. Keep LDAP server not reachable to the management server (and let the LDAP queries to timeout)
2. Login with the LDAP user

### What to do about it?

Either ignore the timed out errors from the LDAP server during user queries, or allow re-attempts based the configuration '_incorrect.login.attempts.allowed_'.

### PR DESCRIPTION
**Pull request by sureshanaparti**
### Description

This PR marks the LDAP user query timeout as incorrect login instead of disabling user immediately.

Fixes #11199 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by sureshanaparti** [comment]
@blueorangutan package

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LdapListUsersCmd.java [hunk 1]
```diff
@@ -140,9 +140,10 @@ public void execute() throws ServerApiException {
         try {
             final List<LdapUser> users = _ldapManager.getUsers(domainId);
             ldapResponses = createLdapUserResponse(users);
-//            now filter and annotate
+            // now filter and annotate
             ldapResponses = applyUserFilter(ldapResponses);
         } catch (final NoLdapUserMatchingQueryException ex) {
+            logger.debug(ex.getMessage());
             // ok, we'll make do with the empty list ldapResponses = new ArrayList<LdapUserResponse>();
```
Comment (DaanHoogland) [inline plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/api/command/LdapListUsersCmd.java]: maybe just remove the code in comment? it was already initialised on line 138.
```suggestion
            // ok, we'll make do with the empty list
```

**Review by shwstppr — APPROVED** [review]
code looks good. One minor comment

File: plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapAuthenticator.java [hunk 2]
```diff
@@ -229,23 +235,27 @@ private Pair<Boolean, ActionOnFailedAuthentication> authenticate(String username
...
         } catch (NoLdapUserMatchingQueryException e) {
             logger.debug(e.getMessage());
-            // no user in ldap ==>> disable user in cloudstack
-            disableUserInCloudStack(user);
+            if (e.getMessage().contains(LDAP_READ_TIMED_OUT_MESSAGE) && !rc.first()) {
+                rc.second(ActionOnFailedAuthentication.INCREMENT_INCORRECT_LOGIN_ATTEMPT_COUNT);
+            } else {
+                // no user in ldap ==>> disable user in cloudstack
+                disableUserInCloudStack(user);
+            }
```
Comment (shwstppr) [inline plugins/user-authenticators/ldap/src/main/java/org/apache/cloudstack/ldap/LdapAuthenticator.java]: (Sorry I may not have pressed buttons correctly last time)

Can this be moved to a new method as it is being used twice?

**Review by shwstppr — APPROVED** [review]

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by kiranchavala — APPROVED** [review]
LGTM

Tested with a docker image of Openldap (https://github.com/osixia/docker-openldap) and we are not disable the user when there is certain timeout
