### PR TITLE
ui: fix resource tags visibility in infocard

### LINKED ISSUE #6649: ui: tags related options not visible for public IP and maybe some other resources
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

UI for adding, removing resource tags is not visible in the public IP view.
This could be an issue with some other resources as well which support resource tags
Screenshot from 2022-08-17 13-34-07

##### STEPS TO REPRODUCE

~~~
1. Log in to UI
2. Go to details of a public IP
~~~

##### EXPECTED RESULTS

~~~
Tags related UI should be visible
~~~

##### ACTUAL RESULTS

~~~
Tags related UI is not visible
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #6649 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Screenshot from 2022-08-17 15-06-34

### CODE REVIEW

**Review by rohityadavcloud — APPROVED** [review]

File: ui/src/components/view/InfoCard.vue [hunk 1]
```diff
@@ -834,6 +826,19 @@ export default {
     }
   },
   methods: {
+    updateResourceAdditionalData () {
+      if (!this.resource) return
+      this.resourceType = this.$route.meta.resourceType
+      console.log('Updating resource additional data')
```
Comment (utchoang) [inline ui/src/components/view/InfoCard.vue:832]: Please remove this log

**Review by utchoang — APPROVED** [review]

File: ui/src/components/view/InfoCard.vue (hunk 1 above)
Comment (shwstppr) [reply ui/src/components/view/InfoCard.vue]: @utchoang thanks for pointing it out. Done
