### PR TITLE
List users by their authentication source

### LINKED ISSUE #9932: Add a filter option to view the users based on the user type
ISSUE TYPE

Improvement request

COMPONENT NAME

Component: Improvement, UI

CLOUDSTACK VERSION

Cloudstack version 4.19.1.x

SUMMARY

Add a filter option to view the users based on the user type

Steps to reproduce the issue

1.  Have a cloudstack environment with Ldap and saml enabled 

2.  Make sure the ldap user and saml users are imported

3.  Currently the list account and  list users API's supports  provides the parameter "usersource" as response through which the admin can identify the user type

https://cloudstack.apache.org/api/apidocs-4.19/apis/listAccounts.html
https://cloudstack.apache.org/api/apidocs-4.19/apis/listUsers.html

Currently there is no way to identify the usersource from the UI 

4. Navigate to Account > view the account

4. Navigate to Account  > select a account >, View users 

userview1

Screenshot 2024-11-15 at 1 14 57 PM

```
(localcloud) 🐱 > list users filter=username,usersource listall=true
{
  "count": 7,
  "user": [
    {
      "username": "admin",
      "usersource": "native"
    },
    {
      "username": "baremetal-system-account",
      "usersource": "native"
    },
    {
      "username": "user",
      "usersource": "saml2disabled"
    },
    {
      "username": "admin-kubeadmin",
      "usersource": "native"
    },
    {
      "username": "kiran2",
      "usersource": "ldap"
    },
    {
      "username": "user1@example.com",
      "usersource": "saml2"
    },
    {
      "username": "user2@example.com",
      "usersource": "saml2"
    }
  ]
  
```
  

Expected behaviour 

Admin should be able to identify the usersource of a account or a user

### PR DESCRIPTION
**Pull request by bernardodemarco**
### Description

Currently, the `listUsers` API response supports the `usersource` attribute, which represents the authentication source of users, such as `native`, `ldap`, `saml2` and `saml2disabled`.  However, it is neither possible to filter users by their authentication source nor to view this attribute in the users' list view.

Therefore, this PR proposes to extend the `listUsers` API by introducing a new parameter called `usersource`, allowing callers to filter users by their authentication source. Furthermore, the UI has been enhanced to support this parameter in the search view and display the `usersource` attribute in the users' list view.

---

Fixes #9932

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### Screenshots (if appropriate):

image

image

#### Through CloudMonkey
- Verified that all users are listed when the `usersource` parameter is omitted.

<details>
<summary>
<code>list users listall=true filter=account,username,usersource</code>
</summary>

```bash
(localcloud) 🐹 > list users listall=true filter=account,username,usersource
{
  "count": 9,
  "user": [
    {
      "account": "admin",
      "username": "admin",
      "usersource": "native"
    },
    {
      "account": "baremetal-system-account",
      "username": "baremetal-system-account",
      "usersource": "native"
    },
    {
      "account": "admin",
      "username": "admin-kubeadmin",
      "usersource": "native"
    },
    {
      "account": "euler",
      "username": "euler",
      "usersource": "ldap"
    },
    {
      "account": "tesla",
      "username": "tesla",
      "usersource": "ldap"
    },
    {
      "account": "boyle",
      "username": "boyle",
      "usersource": "ldap"
    },
    {
      "account": "gauss",
      "username": "gauss",
      "usersource": "ldap"
    },
    {
      "account": "saml-u1",
      "username": "saml-u1",
      "usersource": "saml2"
    },
    {
      "account": "saml-u2",
      "username": "saml-u2",
      "usersource": "saml2"
    }
  ]
}
```
</details>

- Verified that users are listed according to their source when the `usersource` parameter is specified. 

<details>
<summary>
<code>list users listall=true filter=account,username,usersource usersource="ldap"</code>
</summary>

```bash
(localcloud) 🐲 > list users listall=true filter=account,username,usersource usersource="ldap"
{
  "count": 4,
  "user": [
    {
      "account": "euler",
      "username": "euler",
      "usersource": "ldap"
    },
    {
      "account": "tesla",
      "username": "tesla",
      "usersource": "ldap"
    },
    {
      "account": "boyle",
      "username": "boyle",
      "usersource": "ldap"
    },
    {
      "account": "gauss",
      "username": "gauss",
      "usersource": "ldap"
    }
  ]
}
```
</details>

- Verified that an error message is thrown when the `usersource` value is invalid.

<details>
<summary>
<code>list users listall=true filter=account,username,usersource usersource="notValid"</code>
</summary>

```bash
(localcloud) 🐄 > list users listall=true filter=account,username,usersource usersource="notValid"
🙈 Error: (HTTP 431, error code 4350) Invalid user source: notValid. Valid values are: native, ldap, saml2 and saml2disabled.
```

</details>

#### Through UI

- Verified that the `usersource` is displayed in the users' list view:

image

- Verified that the `usersource` search filter works as expected:

image

### CODE REVIEW

**Comment by bernardodemarco** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Review by kiranchavala — COMMENTED** [review]
@bernardodemarco Tested manually looks great

One small/minor ui  issue I observed. 

On the initial saml user creation, the user type is  created as Native only on the refresh of the page the usertype changes to SAML

Navigate to account >users > add user > Authorize saml > the usertype is Native




Screenshot 2024-12-18 at 11 14 09 AM

Screenshot 2024-12-18 at 11 14 45 AM


Sample video recording

https://www.loom.com/share/5d014a8763434e7f89ca21f95cf60377?sid=3cd60c4a-628b-4532-ba2d-cdb799f85a22

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 1]
```diff
@@ -827,6 +829,10 @@ private Pair<List<UserAccountJoinVO>, Integer> getUserListInternal(Account calle
             }
         }
 
+        if (userSource != null) {
+            sc.setParameters("userSource", userSource.toString());
+        }
```
Comment (JoaoJandre) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:834]: We could use setParametersIfNotNull() here

**Comment by bernardodemarco** [comment]
> On the initial saml user creation, the user type is created as Native only on the refresh of the page the usertype changes to SAML

@kiranchavala, thanks for testing. The bug should be resolved now. Could you please test it again and confirm?

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 1 above)
Comment (bernardodemarco) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:834]: If the `setParametersIfNotNull` method were used, scenarios where `userSource` is `null` would result in an NPE because the `toString` method of the enum is invoked.

**Comment by kiranchavala** [comment]
@blueorangutan package

**Review by JoaoJandre — APPROVED** [review]
CLGTM

**Review by kiranchavala — APPROVED** [review]
LGTM, Tested manually Able to filter the users by their usertypes

ldap
saml
samldisabled
usertype1

**Comment by kiranchavala** [comment]
> > On the initial saml user creation, the user type is created as Native only on the refresh of the page the usertype changes to SAML
> 
> @kiranchavala, thanks for testing. The bug should be resolved now. Could you please test it again and confirm?

Thanks @bernardodemarco Issue is resolved
