### PR TITLE
api,ui: fix empty source cidr value for firewall rule

### LINKED ISSUE #10002: UI bug: the Source/Destination CIDR are set to empty not 0.0.0.0/0
The issue happens when create a firewall rule for source nat, static nat, lb or pf on UI.

for example for port forwarding

- specify the public/private port 22 , the rule is created with source cidr 0.0.0.0/0, which is fine.
- specify the public/private port 23 , input some value as source cidr then clean the field, the rule is created with empty source cidr.

image

in the VR, there is no iptables rules for port 23, which is wrong.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.20, should exist in 4.19 as well
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #10002

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by abh1sar — APPROVED** [review]
LGTM.

p.s. what would be the behaviour if the same was done using api (Passing empty string cidr)? If it is the same, can we sanitise the input or throw some error from the api?

**Comment by shwstppr** [comment]
@abh1sar API was allowing empty cidr as it takes List<String> as input,
```
(qaserver) 🐱 > create firewallrule cidrlist= protocol=tcp ipaddressid=e7314c68-c570-42c5-939e-e61f5b30cb4b startport=22 endport=22
{
  "firewallrule": {
    "cidrlist": "",
    "destcidrlist": "",
    "endport": 22,
    "fordisplay": true,
    "id": "2a0c6f0f-bb4c-4f2d-9c2d-1129b523f584",
    "ipaddress": "192.168.1.173",
    "ipaddressid": "e7314c68-c570-42c5-939e-e61f5b30cb4b",
    "networkid": "00089a57-3cc1-4ddc-973c-251a6f097372",
    "protocol": "tcp",
    "startport": 22,
    "state": "Active",
    "tags": [],
    "traffictype": "Ingress"
  }
}
```
I've added a check

@blueorangutan package

File: api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java [hunk 1]
```diff
@@ -103,14 +105,13 @@ public String getProtocol() {
 
     @Override
     public List<String> getSourceCidrList() {
-        if (cidrlist != null) {
+        if (CollectionUtils.isNotEmpty(cidrlist) && (cidrlist.size() == 1 && StringUtils.isNotBlank(cidrlist.get(0)))) {
```
Comment (weizhouapache) [inline api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java:108]: I wonder if the check is correct 

maybe like
```
        if (CollectionUtils.isNotEmpty(cidrlist) && !(cidrlist.size() == 1 && StringUtils.isBlank(cidrlist.get(0)))) {
```
?

Comment (shwstppr) [reply api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java]: Thanks @weizhouapache

Comment (shwstppr) [reply api/src/main/java/org/apache/cloudstack/api/command/user/firewall/CreateFirewallRuleCmd.java]: I'll add some unit tests to not make a mess of it

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by abh1sar — APPROVED** [review]

**Comment by DaanHoogland** [comment]
@blueorangutan test
