### PR TITLE
Track volume usage data at a vm granularity as well

### LINKED ISSUE #10985: [cloud_usage] vm_instance_id is null for volume usage (usage_type = 6)
### problem

When tracking volume usage in the `cloud_usage` table` (usage_type = 6)`, the `vm_instance_id` field is `NULL`, even if the volume is currently attached to a VM. This leads to potential inaccuracies in historical usage data, especially when volumes are detached and reattached to different VMs.

Expected Behavior: ACS should record the correct `vm_instance_id` associated with a volume when usage occurs and store it in the `cloud_usage` table.

### versions

The ACS version is 4.19.1.1

### The steps to reproduce the bug

Case 1:

1. Create and attach a volume to VM.
2. Use the VM for some time (allow usage data to be generated).
3. Observe that cloud_usage.vm_instance_id is still NULL for this VM.

Case 2:

1. Create and attach a volume to VM A.
2. Use the VM for some time (allow usage data to be generated).
3. Detach the volume and attach it to VM B.
4. Trigger a reprocessing of usage data for the original time period.
5. Observe that cloud_usage.vm_instance_id is still NULL.

### What to do about it?

Consider enhancing the ACS `UsageManagerImpl` or submitting a patch upstream to ensure `vm_instance_id` is consistently captured and stored when usage is recorded.

My goal is to accurately track historical usage of volumes in relation to the VMs they were attached to. To achieve this and mitigate the issue of missing `vm_instance_id` values for` usage_type =` 6 in the `cloud_usage` table.

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR fixes #10985 

Some users have asked to show the virtualmachineid also in volume usage, to track it per instance.

There will be two kinds of records now.

- Without the virtualmachineid - tracking the cumulative volume usage in the usage window. This is to be consistent with the current behaviour.
- With virtualmachineid - tracking the volume usage for the time it was attached to the vm in the usage window.

If the volume was attached to multiple instances in the same usage window, we will have separate entries for each VM.

#### Schema changes
- Add column vm_id to cloud.usage_event and cloud_usage.usage_event
- Add column vm_id to cloud_usage.usage_volume

I have also done some code refactoring in createVolumeHelperEvent() to make it easier to follow.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
listUsageRecords for a volume in a 2 minute (0.033333 hours) window.
The volume was created, then attached to VM-00a42c28-74ae-4а0c-b38a-4e3b88f11241. It was then detached and attached to another VM QA-d6df4657-2fb4-4e26-b7de-21743c5463cd. So we have 3 records.

Screenshot 2025-08-29 at 2 42 20 AM

### CODE REVIEW

**Comment by abh1sar** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/usage/dao/UsageVolumeDaoImpl.java [hunk 1]
```diff
@@ -18,83 +18,48 @@
...
         + "      (deleted BETWEEN ? AND ?) OR ((created <= ?) AND (deleted >= ?)))";
-    protected static final String GET_ALL_USAGE_RECORDS = "SELECT volume_id, zone_id, account_id, domain_id, disk_offering_id, template_id, size, created, deleted "
+    protected static final String GET_ALL_USAGE_RECORDS = "SELECT volume_id, zone_id, account_id, domain_id, disk_offering_id, template_id, vm_id, size, created, deleted "
         + "FROM usage_volume " + "WHERE (deleted IS NULL) OR (created BETWEEN ? AND ?) OR " + "      (deleted BETWEEN ? AND ?) OR ((created <= ?) AND (deleted >= ?))";
+    private SearchBuilder<UsageVolumeVO> volumeSearch;
 
     public UsageVolumeDaoImpl() {
     }
 
-    @Override
```
Comment (abh1sar) [inline engine/schema/src/main/java/com/cloud/usage/dao/UsageVolumeDaoImpl.java:53]: This kind of update method is not required since https://github.com/apache/cloudstack/pull/5785 added auto-increment primary keys. We can directly use the GenericDao.update()

File: usage/src/main/java/com/cloud/usage/UsageManagerImpl.java [hunk 2]
```diff
@@ -1534,92 +1539,113 @@ private void createIPHelperEvent(UsageEventVO event) {
...
-            sc.addAnd("accountId", SearchCriteria.Op.EQ, event.getAccountId());
-            sc.addAnd("entityId", SearchCriteria.Op.EQ, volId);
-            sc.addAnd("storageType", SearchCriteria.Op.EQ, StorageTypes.VOLUME);
-            sc.addAnd("deleted", SearchCriteria.Op.NULL);
-            List<UsageStorageVO> volumesVOs = _usageStorageDao.search(sc, null);
 
-            if (volumesVOs.size() > 0) {
-                //This is a safeguard to avoid double counting of volumes.
-                s_logger.error("Found duplicate usage entry for volume: " + volId + " assigned to account: " + event.getAccountId() + "; marking as deleted...");
+            if (event.getVmId() != null) {
```
Comment (abh1sar) [inline usage/src/main/java/com/cloud/usage/UsageManagerImpl.java:1486]: VOLUME_CREATE event will contain the vmId also when it is created during Instance deployment. Need to add a vm specific entry also in that case.

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41930to41940.java
Comment (DaanHoogland) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41930to41940.java:1]: @abh1sar please retarget 4.20? 4.19 will be eol in less than 3 days ;)

File: engine/schema/src/main/resources/META-INF/db/schema-41930to41940.sql
Comment (DaanHoogland) [inline engine/schema/src/main/resources/META-INF/db/schema-41930to41940.sql:1]: should go in a different file

**Review by DaanHoogland — COMMENTED** [review]
looks good, except for the upgrade path (and needs testing)

**Comment by sudo87** [comment]
clgtm

File: engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41930to41940.java
Comment (abh1sar) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/Upgrade41930to41940.java:1]: rebased to 4.20

File: engine/schema/src/main/resources/META-INF/db/schema-41930to41940.sql
Comment (abh1sar) [reply engine/schema/src/main/resources/META-INF/db/schema-41930to41940.sql:1]: added to file schema-42010to42020.sql

**Comment by DaanHoogland** [comment]
code looks good in isolation @abh1sar , but I see some bears on the road: what if someone upgrades from 20.1 to 21 and then on to 22; How do we guarantee they get the DB updates? 
It may be wiser to put this in version 22.


Sorry, I overlooked this when I asked you to rebase earlier.

**Comment by abh1sar** [comment]
> code looks good in isolation @abh1sar , but I see some bears on the road: what if someone upgrades from 20.1 to 21 and then on to 22; How do we guarantee they get the DB updates? It may be wiser to put this in version 22.
> 
> Sorry, I overlooked this when I asked you to rebase earlier.

Thanks @DaanHoogland. Rebased to main.

File: server/src/main/java/com/cloud/api/ApiResponseHelper.java [hunk 3]
```diff
@@ -4330,6 +4330,9 @@ public UsageRecordResponse createUsageResponse(Usage usageRecord, Map<String, Se
                 if (volume != null) {
                     builder.append("for ").append(volume.getName()).append(" (").append(volume.getUuid()).append(")");
                 }
+                if (vmInstance != null) {
+                    builder.append(" attached to VM ").append(vmInstance.getHostName()).append(" (").append(vmInstance.getUuid()).append(")");
+                }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/ApiResponseHelper.java:4335]: this is adding only three lines to a 530 line method. No issue in the context but `public UsageRecordResponse createUsageResponse(Usage usageRecord)` needs to be refactorred (as many pieces of code).

**Review by DaanHoogland — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

**Comment by vishesh92** [comment]
@blueorangutan test keepEnv

File: usage/src/main/java/com/cloud/usage/UsageManagerImpl.java [hunk 4]
```diff
@@ -1424,92 +1429,112 @@ private void createIPHelperEvent(UsageEventVO event) {
...
             }
-            for (UsageStorageVO volumesVO : volumesVOs) {
-                if (logger.isDebugEnabled()) {
-                    logger.debug("deleting volume: " + volumesVO.getId() + " from account: " + volumesVO.getAccountId());
+            break;
+
+        case EventTypes.EVENT_VOLUME_RESIZE:
+            volumesVOs = _usageVolumeDao.listByVolumeId(volId, event.getAccountId());
+            for (UsageVolumeVO volumesVO : volumesVOs) {
+                String delete_msg = String.format("Setting the volume with id: %s to 'deleted' in the usage_storage table for account: %s.", volId, event.getAccountId());
```
Comment (vishesh92) [inline usage/src/main/java/com/cloud/usage/UsageManagerImpl.java]:
```suggestion
                String delete_msg = String.format("Setting the volume with id: %s to 'deleted' in the usage_volume table for account: %s.", volId, event.getAccountId());
```

**Review by vishesh92 — APPROVED** [review]
code lgtm

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan package

**Review by sureshanaparti — APPROVED** [review]
clgtm

**Comment by sureshanaparti** [comment]
Verified the usage,  event and volumes records when volumes are attached to & detached from VMs. LGTM.

```
mysql> SELECT * FROM cloud.usage_event WHERE type LIKE '%VOLUME%' AND resource_id IN (8, 10) ORDER BY id;
+----+---------------+------------+---------------------+---------+-------------+---------------+-------------+-------------+------------+---------------+-----------+--------------+-------+
| id | type          | account_id | created             | zone_id | resource_id | resource_name | offering_id | template_id | size       | resource_type | processed | virtual_size | vm_id |
+----+---------------+------------+---------------------+---------+-------------+---------------+-------------+-------------+------------+---------------+-----------+--------------+-------+
| 12 | VOLUME.CREATE |          2 | 2025-10-09 09:55:02 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |  NULL |
| 20 | VOLUME.CREATE |          2 | 2025-10-09 09:55:24 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         0 |         NULL |  NULL |
| 22 | VOLUME.ATTACH |          2 | 2025-10-09 09:55:55 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |     3 |
| 24 | VOLUME.ATTACH |          2 | 2025-10-09 09:56:07 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         0 |         NULL |     6 |
| 33 | VOLUME.DETACH |          2 | 2025-10-09 10:31:13 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |  NULL |
| 34 | VOLUME.DETACH |          2 | 2025-10-09 10:31:17 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         0 |         NULL |  NULL |
| 37 | VOLUME.ATTACH |          2 | 2025-10-10 08:42:33 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |     7 |
| 38 | VOLUME.DETACH |          2 | 2025-10-10 08:55:37 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |  NULL |
| 39 | VOLUME.ATTACH |          2 | 2025-10-10 09:00:39 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         0 |         NULL |     3 |
| 40 | VOLUME.ATTACH |          2 | 2025-10-10 09:01:39 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |     6 |
| 41 | VOLUME.DETACH |          2 | 2025-10-10 09:05:23 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         0 |         NULL |  NULL |
| 42 | VOLUME.DETACH |          2 | 2025-10-10 09:05:31 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         0 |         NULL |  NULL |
+----+---------------+------------+---------------------+---------+-------------+---------------+-------------+-------------+------------+---------------+-----------+--------------+-------+
12 rows in set (0.00 sec)

mysql> SELECT * FROM cloud_usage.usage_event WHERE type LIKE '%VOLUME%' AND resource_id IN (8, 10) ORDER BY id;
+----+---------------+------------+---------------------+---------+-------------+---------------+-------------+-------------+------------+---------------+-----------+--------------+-------+
| id | type          | account_id | created             | zone_id | resource_id | resource_name | offering_id | template_id | size       | resource_type | processed | virtual_size | vm_id |
+----+---------------+------------+---------------------+---------+-------------+---------------+-------------+-------------+------------+---------------+-----------+--------------+-------+
| 12 | VOLUME.CREATE |          2 | 2025-10-09 09:55:02 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |  NULL |
| 20 | VOLUME.CREATE |          2 | 2025-10-09 09:55:24 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         1 |         NULL |  NULL |
| 22 | VOLUME.ATTACH |          2 | 2025-10-09 09:55:55 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |     3 |
| 24 | VOLUME.ATTACH |          2 | 2025-10-09 09:56:07 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         1 |         NULL |     6 |
| 33 | VOLUME.DETACH |          2 | 2025-10-09 10:31:13 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |  NULL |
| 34 | VOLUME.DETACH |          2 | 2025-10-09 10:31:17 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         1 |         NULL |  NULL |
| 37 | VOLUME.ATTACH |          2 | 2025-10-10 08:42:33 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |     7 |
| 38 | VOLUME.DETACH |          2 | 2025-10-10 08:55:37 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |  NULL |
| 39 | VOLUME.ATTACH |          2 | 2025-10-10 09:00:39 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         1 |         NULL |     3 |
| 40 | VOLUME.ATTACH |          2 | 2025-10-10 09:01:39 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |     6 |
| 41 | VOLUME.DETACH |          2 | 2025-10-10 09:05:23 |       1 |           8 | DATA02        |           6 |        NULL | 3221225472 | NULL          |         1 |         NULL |  NULL |
| 42 | VOLUME.DETACH |          2 | 2025-10-10 09:05:31 |       1 |          10 | DATA04        |           6 |        NULL | 1073741824 | NULL          |         1 |         NULL |  NULL |
+----+---------------+------------+---------------------+---------+-------------+---------------+-------------+-------------+------------+---------------+-----------+--------------+-------+
12 rows in set (0.01 sec)

mysql> SELECT * FROM cloud_usage.usage_volume WHERE volume_id IN (8, 10) ORDER BY id;
+----+-----------+---------+------------+-----------+------------------+-------------+------------+---------------------+---------------------+-------+
| id | volume_id | zone_id | account_id | domain_id | disk_offering_id | template_id | size       | created             | deleted             | vm_id |
+----+-----------+---------+------------+-----------+------------------+-------------+------------+---------------------+---------------------+-------+
|  8 |         8 |       1 |          2 |         1 |                6 |        NULL | 3221225472 | 2025-10-09 09:55:02 | NULL                |  NULL |
| 10 |        10 |       1 |          2 |         1 |                6 |        NULL | 1073741824 | 2025-10-09 09:55:24 | NULL                |  NULL |
| 12 |         8 |       1 |          2 |         1 |                6 |        NULL | 3221225472 | 2025-10-09 09:55:55 | 2025-10-09 10:31:13 |     3 |
| 14 |        10 |       1 |          2 |         1 |                6 |        NULL | 1073741824 | 2025-10-09 09:56:07 | 2025-10-09 10:31:17 |     6 |
| 63 |         8 |       1 |          2 |         1 |                6 |        NULL | 3221225472 | 2025-10-10 08:42:33 | 2025-10-10 08:55:37 |     7 |
| 66 |        10 |       1 |          2 |         1 |                6 |        NULL | 1073741824 | 2025-10-10 09:00:39 | 2025-10-10 09:05:31 |     3 |
| 67 |         8 |       1 |          2 |         1 |                6 |        NULL | 3221225472 | 2025-10-10 09:01:39 | 2025-10-10 09:05:23 |     6 |
+----+-----------+---------+------------+-----------+------------------+-------------+------------+---------------------+---------------------+-------+
7 rows in set (0.00 sec)
```

Usage records:

```
(cmk) 🐱 > list usagerecords startdate=2025-10-07 enddate=2025-10-10 type=6 usageid=2c218702-abff-46e8-bc8a-3e12fffa2188
{
  "count": 436,
  "usagerecord": [
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) attached to VM testvm01 (282033c0-18df-46cd-809a-470f1a38a800) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-09T09:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "0.068056",
      "size": 3221225472,
      "startdate": "2025-10-09T09:00:00+0000",
      "tags": [],
      "usage": "0.068056 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "virtualmachineid": "282033c0-18df-46cd-809a-470f1a38a800",
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
...
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T07:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 3221225472,
      "startdate": "2025-10-10T07:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) attached to VM testvm04 (332284cf-f56a-4075-adf5-3ac4f4fc8033) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T08:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "0.217778",
      "size": 3221225472,
      "startdate": "2025-10-10T08:00:00+0000",
      "tags": [],
      "usage": "0.217778 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "virtualmachineid": "332284cf-f56a-4075-adf5-3ac4f4fc8033",
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T08:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 3221225472,
      "startdate": "2025-10-10T08:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) attached to VM testvm02 (ca3309cd-15e7-4718-9b33-d2c3af12ecd8) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T09:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "0.062222",
      "size": 3221225472,
      "startdate": "2025-10-10T09:00:00+0000",
      "tags": [],
      "usage": "0.062222 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "virtualmachineid": "ca3309cd-15e7-4718-9b33-d2c3af12ecd8",
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T09:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 3221225472,
      "startdate": "2025-10-10T09:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T10:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 3221225472,
      "startdate": "2025-10-10T10:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA02 (2c218702-abff-46e8-bc8a-3e12fffa2188) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (3.00 GB) 3221225472",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T11:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 3221225472,
      "startdate": "2025-10-10T11:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "2c218702-abff-46e8-bc8a-3e12fffa2188",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    }
  ]
}

(cmk) 🐱 > list usagerecords startdate=2025-10-07 enddate=2025-10-10 type=6 usageid=6c766c5c-1ab8-4428-a3ba-4b9a17b84502
{
  "count": 432,
  "usagerecord": [
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA04 (6c766c5c-1ab8-4428-a3ba-4b9a17b84502) attached to VM testvm02 (ca3309cd-15e7-4718-9b33-d2c3af12ecd8) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (1.00 GB) 1073741824",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-09T09:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "0.064722",
      "size": 1073741824,
      "startdate": "2025-10-09T09:00:00+0000",
      "tags": [],
      "usage": "0.064722 Hrs",
      "usageid": "6c766c5c-1ab8-4428-a3ba-4b9a17b84502",
      "usagetype": 6,
      "virtualmachineid": "ca3309cd-15e7-4718-9b33-d2c3af12ecd8",
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
...
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA04 (6c766c5c-1ab8-4428-a3ba-4b9a17b84502) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (1.00 GB) 1073741824",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T08:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 1073741824,
      "startdate": "2025-10-10T08:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "6c766c5c-1ab8-4428-a3ba-4b9a17b84502",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA04 (6c766c5c-1ab8-4428-a3ba-4b9a17b84502) attached to VM testvm01 (282033c0-18df-46cd-809a-470f1a38a800) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (1.00 GB) 1073741824",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T09:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "0.081111",
      "size": 1073741824,
      "startdate": "2025-10-10T09:00:00+0000",
      "tags": [],
      "usage": "0.081111 Hrs",
      "usageid": "6c766c5c-1ab8-4428-a3ba-4b9a17b84502",
      "usagetype": 6,
      "virtualmachineid": "282033c0-18df-46cd-809a-470f1a38a800",
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA04 (6c766c5c-1ab8-4428-a3ba-4b9a17b84502) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (1.00 GB) 1073741824",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T09:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 1073741824,
      "startdate": "2025-10-10T09:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "6c766c5c-1ab8-4428-a3ba-4b9a17b84502",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA04 (6c766c5c-1ab8-4428-a3ba-4b9a17b84502) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (1.00 GB) 1073741824",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T10:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 1073741824,
      "startdate": "2025-10-10T10:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "6c766c5c-1ab8-4428-a3ba-4b9a17b84502",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    },
    {
      "account": "admin",
      "accountid": "f709bdb4-a4f1-11f0-9b4e-1e00e6000172",
      "description": "Volume usage for DATA04 (6c766c5c-1ab8-4428-a3ba-4b9a17b84502) with disk offering Custom (b528eb0d-0efd-4df7-bffe-f0db170ac2e1) and size (1.00 GB) 1073741824",
      "domain": "ROOT",
      "domainid": "9f57bbb6-a4f1-11f0-9b4e-1e00e6000172",
      "domainpath": "/",
      "enddate": "2025-10-10T11:59:59+0000",
      "offeringid": "b528eb0d-0efd-4df7-bffe-f0db170ac2e1",
      "rawusage": "1",
      "size": 1073741824,
      "startdate": "2025-10-10T11:00:00+0000",
      "tags": [],
      "usage": "1 Hrs",
      "usageid": "6c766c5c-1ab8-4428-a3ba-4b9a17b84502",
      "usagetype": 6,
      "zoneid": "1f5131c0-cb48-4dc4-bb7c-33f8a0de2ec9"
    }
  ]
}
```

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by abh1sar** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by harikrishna-patnala** [comment]
@DaanHoogland @abh1sar there are DB changes made in this PR in schema-42100to42200.sql file which should be in newer sql file, this needs fixing.
