### PR TITLE
Fix invalid consoleproxy url after upgrade

### LINKED ISSUE #2733: invalid consoleproxy domain after upgrade from 4.5 to 4.11.1
Avoid a pitfall after upgrade from 4.5 to 4.11 using invalid domain with `*` for console proxy url

##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
gloabl setting
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When used a setting in 4.5 for consoleproxy.url.domain with `*` which got transformed to the "console IP with dashes + domain" and enabled SSL:

~~~
*.example.com --> https://1-2-3-4.example.com
~~~

However, in 4.11 (at least) there is a separate config to enable SSL, When upgrading from 4.5 the new setting consoleproxy.sslEnabled is defaulted to false. 

In this case the domain is used "as-is" having a `*`and results in a invalid domain. 
~~~
*.example.com --> http://*.example.com
~~~

##### STEPS TO REPRODUCE

set global settings as the following:
* consoleproxy.url.domain=*.example.com
* consoleproxy.sslEnabled=false

##### EXPECTED RESULTS
Always use the valid domain by repalce * or use console IP
~~~
consoleproxy.sslEnabled=false
*.example.com --> http://1-2-3-4.example.com
~~~

~~~
consoleproxy.sslEnabled=true
*.example.com --> https://1-2-3-4.example.com
~~~

##### ACTUAL RESULTS
selection_183

### PR DESCRIPTION
**Pull request by resmo**
## Description
Ensures we have a valid console proxy domain for protocol http even a `*` setting is used. See #2733 

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## GitHub Issue/PRs
Fixes #2733 

## Screenshots (if appropriate):
after fix 
selection_185

## How Has This Been Tested?
Manually in simulator setup

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/apache/cloudstack/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
Testing
- [ ] I have added tests to cover my changes.
- [ ] All relevant new and existing integration tests have passed.
- [ ] A full integration testsuite with all test that can run on my environment has passed.

### CODE REVIEW

File: core/src/main/java/com/cloud/info/ConsoleProxyInfo.java [hunk 1]
```diff
@@ -36,33 +36,33 @@ public ConsoleProxyInfo(int proxyUrlPort) {
...
-                sb.append(consoleProxyUrlDomain);
-            }
-            proxyAddress = sb.toString();
-            proxyPort = port;
-            this.proxyUrlPort = proxyUrlPort;
+        StringBuffer sb = new StringBuffer();
+        // Domain in format *.example.com
+        if (consoleProxyUrlDomain.startsWith("*")) {
+            sb.append(proxyIpAddress);
+            for (int i = 0; i < proxyIpAddress.length(); i++)
```
Comment (rafaelweingartner) [inline core/src/main/java/com/cloud/info/ConsoleProxyInfo.java]: You can replace this block with a "replaceAll" method, right?

File: core/src/main/java/com/cloud/info/ConsoleProxyInfo.java [hunk 2]
```diff
@@ -36,33 +36,33 @@ public ConsoleProxyInfo(int proxyUrlPort) {
...
-                        sb.setCharAt(i, '-');
-                sb.append(consoleProxyUrlDomain.substring(1));//skip the *
-            } else {
-                //LB address
-                sb.append(consoleProxyUrlDomain);
-            }
-            proxyAddress = sb.toString();
-            proxyPort = port;
-            this.proxyUrlPort = proxyUrlPort;
+        StringBuffer sb = new StringBuffer();
```
Comment (rafaelweingartner) [inline core/src/main/java/com/cloud/info/ConsoleProxyInfo.java]: Would you mind extracting this block that creates the "proxyAddress" to a method? Then, we could have unit tests and documentation for it.

**Comment by resmo** [comment]
@rhtyd done

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
Regression test LGTM, I did not test it manually though. @borisstoyanov if you've time next week, can you test and advise? Thanks.

File: core/src/com/cloud/info/ConsoleProxyInfo.java [hunk 3]
```diff
@@ -35,38 +35,40 @@ public ConsoleProxyInfo(int proxyUrlPort) {
...
+        } else {
             proxyImageUrl = "http://" + proxyAddress;
-            if (proxyUrlPort != 80)
+            if (proxyUrlPort != 80) {
                 proxyImageUrl += ":" + proxyUrlPort;
+            }
+        }
+    }
+
+    private String formatProxyAddress(String consoleProxyUrlDomain, String proxyIpAddress) {
```
Comment (rafaelweingartner) [inline core/src/com/cloud/info/ConsoleProxyInfo.java]: @resmo you already did a lot! I would like to see a documentation (instead of inline comments) and unit tests for this method though.

**Comment by resmo** [comment]
will work on the unit test but +14 days and I assume forward merging will be tricky (file renames), suggesting to merge into 4.11 and add the test later on master for 4.12.

**Comment by rafaelweingartner** [comment]
I think the forward merging is working (normally). Somehow git is managing the new folder structure that was applied between 4.11-4.12
