### PR TITLE
server: fix templatetype during iso upload

### LINKED ISSUE #12104: [Cloudstack 4.22] Bug when importing ISO – template_type remains NULL in database
### problem

Hello,
When importing an ISO via the CloudStack UI (version 4.22.x), the template_type field in the vm_template table remains NULL. This causes a blocking error when deploying a VM using this ISO:

Image

2025-11-19 16:23:41,101 ERROR [c.c.v.UserVmManagerImpl] (qtp1438988851-1427:[ctx-44033ac3, ctx-d398c5c8]) (logid:cc3bed8f) error during resource reservation and allocation java.lang.NullPointerException: Cannot invoke "com.cloud.storage.Storage$TemplateType.equals(Object)" because the return value of "com.cloud.storage.VMTemplateVO.getTemplateType()" is null
        at com.cloud.vm.UserVmManagerImpl.getUncheckedUserVmResource(UserVmManagerImpl.java:4393)
        at com.cloud.vm.UserVmManagerImpl.getCheckedUserVmResource(UserVmManagerImpl.java:4243)
        at com.cloud.vm.UserVmManagerImpl.createVirtualMachine(UserVmManagerImpl.java:4214)
        at com.cloud.vm.UserVmManagerImpl.createAdvancedVirtualMachine(UserVmManagerImpl.java:3993)
        at com.cloud.vm.UserVmManagerImpl.createVirtualMachine(UserVmManagerImpl.java:6484)
        at com.cloud.vm.UserVmManagerImpl.createVirtualMachine(UserVmManagerImpl.java:6408)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at jdk.proxy3/jdk.proxy3.$Proxy223.createVirtualMachine(Unknown Source)
        at org.apache.cloudstack.api.command.user.vm.DeployVMCmd.create(DeployVMCmd.java:139)
        at com.cloud.api.dispatch.CommandCreationWorker.handle(CommandCreationWorker.java:47)
        at com.cloud.api.dispatch.DispatchChain.dispatch(DispatchChain.java:37)
        at com.cloud.api.ApiDispatcher.dispatchCreateCmd(ApiDispatcher.java:95)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:775)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:668)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:416)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:193)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:190)
        at com.cloud.api.ApiServlet.doPost(ApiServlet.java:149)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:840)

### versions

Version: CloudStack 4.22.x
Hypervisor: KVM/VMWARE
OS: Ubuntu Noble
Database: Mysql latest

### The steps to reproduce the bug

1. Import Iso 
2. Create instance with this iso

### What to do about it?

To work around this error, we need to update the database as follows:

UPDATE vm_template SET type='USER' WHERE name='<iso_name>';

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #12104

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
```
(test) 🐱 > get uploadparamsforiso  zoneid=dc5ac4bd-b1bd-4b3d-8d3a-c371897163c4 (pr12151-t14874-kvm-ol8) name=test  bootable=true ostypeid=4d02db28-cb86-11f0-9397-1e00d5000394 (Other Linux (64-bit)) filepath=/home/shwstppr/www/html/files/Template-ISO/TinyCore-8.0.iso format=ISO
{
  "getuploadparams": {
    "expires": "2025-11-27T20:17:37.743Z",
    "id": "f7f9cc6e-ca23-46b2-b51c-412c02fcf686",
    "metadata": "J6e+Y/fw5j29+6H4g1CiC+9v9XeBfACB89ugQb+5QepU20/Ugp9Dwf17AiZn3SMs7+42jYTMZDX8A3bIox953syD97kXBwx6G2Iki5IsznCXn0WMoykXqJD+Q/nvjb33Hv27qOCRisPLS2Z0gp+ceIkoKbhI3lJspoQ4KaUjLepT/2wUi+ErDPO/u4xQS2ps40ARPKei75P+F1ENFvb2KY3z32CcjV5S4Lzy2cIy49/KJE+/71q1FuKONldm+79Q4cMloInXXRSWDT1Jp6AlmvmXi8th54LsDgjCPje/PR9cy7WTcC6+9meDV+2wazKSCDzWN2hYZ3jBh+n71QOXpm7wfvRbgj3PzZFKREqo9iHbvr7JFPCp8ytCwmeT9ou90XrZY/YbObvoPXF9K4ZcS2rQ8PalfVx6OxByL3wIR2tjotSidVRxY9BvDUcPsuPwO9MJ9kt94kwizlbnbP1hxu/Ap3/XXgBjA53pb5LyEYTF+rnuemwCIwJuvgjUs+ZW4As1C2a7u0MTK6Z6/teU7KNRUn3TUCT3PMrKDcgQE8BZym3InC63Y87UfuXxIYG2BWmrQVOHl8ZKF7Vc/OSCCJhZx6Xhpc5FIte/kizp3zRSjB8/kAjEdmQR1XLiS6+Q8BO8TuNt7ZoIDUVtvs+fF7M=",
    "postURL": "http://10.0.53.101/upload/f7f9cc6e-ca23-46b2-b51c-412c02fcf686",
    "signature": "GHMt4362nI/t5tSPaPQl2hzwNTg="
  }
}
Uploading files for getUploadParamsForIso : [/home/shwstppr/www/html/files/Template-ISO/TinyCore-8.0.iso]
[1/1] TinyCore-8.0.iso	[========================] ✅
All files uploaded successfully.
(test) 🐱 > list isos isofilter=self id=f7f9cc6e-ca23-46b2-b51c-412c02fcf686
{
  "count": 1,
  "iso": [
    {
      "account": "admin",
      "arch": "x86_64",
      "bits": 64,
      "bootable": true,
      "created": "2025-11-27T19:17:37+0000",
      "crossZones": false,
      "directdownload": false,
      "displaytext": "test",
      "domain": "ROOT",
      "domainid": "4cdc2592-cb86-11f0-9397-1e00d5000394",
      "domainpath": "ROOT",
      "downloaddetails": [
        {
          "datastore": "pr12151-t14874-kvm-ol8-sec1",
          "datastoreId": "d00fd22e-bc60-4645-8505-dc2e016fc606",
          "datastoreRole": "Image",
          "downloadPercent": "100",
          "downloadState": "DOWNLOADED"
        }
      ],
      "format": "ISO",
      "hasannotations": false,
      "id": "f7f9cc6e-ca23-46b2-b51c-412c02fcf686",
      "isdynamicallyscalable": false,
      "isextractable": false,
      "isfeatured": false,
      "ispublic": false,
      "isready": true,
      "name": "test",
      "ostypeid": "4d02db28-cb86-11f0-9397-1e00d5000394",
      "ostypename": "Other Linux (64-bit)",
      "passwordenabled": false,
      "physicalsize": 16777216,
      "size": 16777216,
      "status": "Successfully Installed",
      "tags": [],
      "zoneid": "dc5ac4bd-b1bd-4b3d-8d3a-c371897163c4",
      "zonename": "pr12151-t14874-kvm-ol8"
    }
  ]
}

```

In DB,

```
mysql> select id,name,type from vm_template where uuid='f7f9cc6e-ca23-46b2-b51c-412c02fcf686'\G
*************************** 1. row ***************************
  id: 202
name: test
type: USER
1 row in set (0.01 sec)

```

VM deployment,

```
(test) 🐱 > deploy virtualmachine zoneid=dc5ac4bd-b1bd-4b3d-8d3a-c371897163c4 (pr12151-t14874-kvm-ol8)  serviceofferingid=c3ccc089-5b66-4211-97b4-06eb2609f106 (Small Instance) diskofferingid=5607ab76-127d-4fa9-9001-1262d15e3c68 (Small) templateid=f7f9cc6e-ca23-46b2-b51c-412c02fcf686 hypervisor=KVM
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "arch": "x86_64",
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2025-11-27T19:23:29+0000",
    "deleteprotection": false,
    "details": {
      "cpuOvercommitRatio": "2.0",
      "rootdisksize": "5"
    },
    "diskofferingid": "5607ab76-127d-4fa9-9001-1262d15e3c68",
    "diskofferingname": "Small",
    "displayname": "VM-e12cdbe2-01b1-496f-ae5b-438d6466c3cf",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "4cdc2592-cb86-11f0-9397-1e00d5000394",
    "domainpath": "ROOT",
    "guestosid": "4d02db28-cb86-11f0-9397-1e00d5000394",
    "haenable": false,
    "hasannotations": false,
    "hostcontrolstate": "Enabled",
    "hostid": "23417a35-afff-4223-a7d3-4963dcecb609",
    "hostname": "pr12151-t14874-kvm-ol8-kvm1",
    "hypervisor": "KVM",
    "id": "e12cdbe2-01b1-496f-ae5b-438d6466c3cf",
    "instancename": "i-2-4-VM",
    "ipaddress": "10.1.1.156",
    "isdynamicallyscalable": false,
    "isodisplaytext": "test",
    "isoid": "f7f9cc6e-ca23-46b2-b51c-412c02fcf686",
    "isoname": "test",
    "jobid": "7bbff84c-a725-4fb1-8a82-1fed17095b86",
    "jobstatus": 0,
    "lastupdated": "2025-11-27T19:24:26+0000",
    "memory": 512,
    "name": "VM-e12cdbe2-01b1-496f-ae5b-438d6466c3cf",
    "nic": [
      {
        "broadcasturi": "vlan://1374",
        "deviceid": "0",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "e6aa46e8-17e8-49b1-a9dd-0e8cece77a39",
        "ipaddress": "10.1.1.156",
        "isdefault": true,
        "isolationuri": "vlan://1374",
        "macaddress": "02:01:00:cc:00:01",
        "netmask": "255.255.255.0",
        "networkid": "8585e092-031d-4754-8bc7-335249ea2e2d",
        "networkname": "admin-network",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "Other Linux (64-bit)",
    "ostypeid": "4d02db28-cb86-11f0-9397-1e00d5000394",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "c3ccc089-5b66-4211-97b4-06eb2609f106",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "test",
    "templateformat": "ISO",
    "templateid": "f7f9cc6e-ca23-46b2-b51c-412c02fcf686",
    "templatename": "test",
    "templatetype": "USER",
    "userid": "b6230f1b-cb86-11f0-9397-1e00d5000394",
    "username": "admin",
    "zoneid": "dc5ac4bd-b1bd-4b3d-8d3a-c371897163c4",
    "zonename": "pr12151-t14874-kvm-ol8"
  }
}

```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/template/TemplateManagerImpl.java [hunk 1]
```diff
@@ -2359,12 +2359,15 @@ else if (details != null && !details.isEmpty()) {
...
     @Override
     public TemplateType validateTemplateType(BaseCmd cmd, boolean isAdmin, boolean isCrossZones, HypervisorType hypervisorType) {
-        if (!(cmd instanceof UpdateTemplateCmd) && !(cmd instanceof RegisterTemplateCmd) && !(cmd instanceof GetUploadParamsForTemplateCmd)) {
+        if (!(cmd instanceof UpdateTemplateCmd) &&
+                !(cmd instanceof RegisterTemplateCmd) &&
+                !(cmd instanceof GetUploadParamsForTemplateCmd) &&
+                !(cmd instanceof GetUploadParamsForIsoCmd)) {
             return null;
         }
         TemplateType templateType = null;
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/template/TemplateManagerImpl.java:2368]: can we just use
```
if (cmd instanceof GetUploadParamsForIsoCmd) {
    return TemplateType.USER;
}
```

?

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Review by sureshanaparti — APPROVED** [review]

**Review by vishesh92 — APPROVED** [review]
clgtm. didn't test.
