### PR TITLE
metrics: fix hostsmetricsresponse for zero cpu, locale

### LINKED ISSUE #5300: 'Hosts' in the webui not working
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

Advanced Networking

##### OS / ENVIRONMENT

Ubuntu Server 20.04.2, MySQL Ver 8.0.26-0ubuntu0.20.04.2, KVM

##### SUMMARY

Hardware, setup with 4.15, then upgraded to 4.15.1
http://ipaddress:8080/client/#/host        = 'Hosts' tab in the webui BROKEN with error 	
http://ipaddress:8080/client/legacy/     = 'Hosts' tab in the webui is OK, lists all hosts correctly

Hardware, setup clean with 4.15.1
http://ipaddress:8080/client/#/host        = 'Hosts' tab in the webui is OK, lists all hosts correctly
http://ipaddress:8080/client/legacy/     = 'Hosts' tab in the webui is OK, lists all hosts correctly

##### STEPS TO REPRODUCE

I have been getting an error that when I click 'Infrastructure' then 'Hosts' in the webui (http://ipaddress:8080/client/) the error message: '(X) For input string: " "' is shown briefly, but the hosts are NOT listed. However the old web client works fine (http://ipaddress:8080/client/legacy/).

The boxes that have the error were upgraded from 4.15 to 4.15.1

I have just done a clean install on identical hardware straight to 4.15.1 and there are no longer any errors.

People have suggested that system Locale may be a problem. However using the default locale on the new install works fine (en_GB.UTF-8) and doesn’t need changing.

I don’t think locale is the issue now (for me anyway). I think the mysql database has either been changed somehow during the original systems upgrade procedure. Or the 4.15 created database is being accessed differently from the system that has been through the upgrade procedure to 4.15.1

~~~

~~~

##### EXPECTED RESULTS

~~~
A list of all infrastructure hosts to be displayed in the 'new' webui
~~~

##### ACTUAL RESULTS

An error is briefly shown: (X) For input string: " "

~~~
# CHROME CONSOLE OUTPUT WHEN HOSTS IS CLICKED:
#
xhr.js:177 GET http://10.xx.0.xx:8080/client/api/?listall=true&type=routing&page=1&pagesize=10&command=listHostsMetrics&response=json 431 (Request Header Fields Too Large)
(anonymous) @ xhr.js:177
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:52
Promise.then (async)
c.request @ Axios.js:61
(anonymous) @ bind.js:9
n @ index.js:32
fetchData @ AutogenView.vue:618
created @ AutogenView.vue:432
tt @ vue.runtime.esm.js:1854
$n @ vue.runtime.esm.js:4219
e._init @ vue.runtime.esm.js:5008
o @ vue.runtime.esm.js:5154
rn @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
e @ vue.runtime.esm.js:3301
u @ vue.runtime.esm.js:5978
y @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
Hn.e._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
tr.get @ vue.runtime.esm.js:4479
tr @ vue.runtime.esm.js:4468
Pn @ vue.runtime.esm.js:4073
Cr.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
e @ vue.runtime.esm.js:3301
u @ vue.runtime.esm.js:5978
y @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6516
Hn.e._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
tr.get @ vue.runtime.esm.js:4479
tr.run @ vue.runtime.esm.js:4554
Gn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ct @ vue.runtime.esm.js:1906
Promise.then (async)
it @ vue.runtime.esm.js:1933
dt @ vue.runtime.esm.js:1990
Qn @ vue.runtime.esm.js:4402
tr.update @ vue.runtime.esm.js:4544
pe.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2989
(anonymous) @ vue-router.esm.js:2988
tt.updateRoute @ vue-router.esm.js:2409
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2397
i @ vue-router.esm.js:2001
i @ vue-router.esm.js:2008
i @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
(anonymous) @ vue-router.esm.js:2392
i @ vue-router.esm.js:2001
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ vue-router.esm.js:2162
d @ vue-router.esm.js:2357
i @ vue-router.esm.js:2004
i @ vue-router.esm.js:2008
i @ vue-router.esm.js:2008
i @ vue-router.esm.js:2008
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ permission.js:77
d @ vue-router.esm.js:2357
i @ vue-router.esm.js:2004
i @ vue-router.esm.js:2008
$e @ vue-router.esm.js:2012
tt.confirmTransition @ vue-router.esm.js:2387
tt.transitionTo @ vue-router.esm.js:2260
e.push @ vue-router.esm.js:2704
xt.push @ vue-router.esm.js:3023
g @ vue-router.esm.js:1139
tt @ vue.runtime.esm.js:1854
o @ vue.runtime.esm.js:2179
Zi.o._wrapper @ vue.runtime.esm.js:6917
Show 46 more frames
request.js:34 {data: {…}, status: 431, statusText: "Request Header Fields Too Large", headers: {…}, config: {…}, …}
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

`listHostsMetrics` API could fail in case of zero CPU with Double to String conversion.
Fixes #5300 
Failure could also be seen in case of some locales, #4733
Backports #4900 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### How Has This Been Tested?

In DB:
```
mysql> select * from host where uuid='fc75a8b3-263d-4231-8635-45715edea15a'\G
*************************** 1. row ***************************
                   id: 4
                 name: SimulatedAgent.15a2757a-2285-4ecf-86fc-75fb94c2cd5e
                 uuid: fc75a8b3-263d-4231-8635-45715edea15a
               status: Up
                 type: Routing
   private_ip_address: 172.16.15.23
      private_netmask: NULL
  private_mac_address: 00:00:00:00:00:00
   storage_ip_address: 172.16.15.23
      storage_netmask: NULL
  storage_mac_address: 00:00:00:00:00:00
 storage_ip_address_2: 172.16.15.23
storage_mac_address_2: 172.16.15.23
    storage_netmask_2: NULL
           cluster_id: 2
    public_ip_address: NULL
       public_netmask: NULL
   public_mac_address: NULL
           proxy_port: NULL
       data_center_id: 1
               pod_id: 1
          cpu_sockets: NULL
                 cpus: 0
                speed: 0
                  url: NULL
              fs_type: NULL
      hypervisor_type: Simulator
   hypervisor_version: 4.15.1.0
                  ram: 8589934592
             resource: com.cloud.resource.AgentRoutingResource
              version: 4.15.1.0
               parent: NULL
           total_size: NULL
         capabilities: hvm
                 guid: 15a2757a-2285-4ecf-86fc-75fb94c2cd5e
            available: 1
                setup: 0
          dom0_memory: 0
            last_ping: 1591037319
       mgmt_server_id: 2482942762267
         disconnected: 2021-08-17 17:43:21
              created: 2021-08-17 17:21:13
              removed: NULL
         update_count: 9
       resource_state: Enabled
                owner: NULL
          lastUpdated: NULL
         engine_state: Disabled
1 row in set (0.00 sec)

```

Without change:
```
🙈 Error: (HTTP 431, error code 9999) For input string: "∞"
(local) 🐝 > list hostsmetrics=fc75a8b3-263d-4231-8635-45715edea15a 
```
With change:
```
(local) 🐻 > list hosts id=fc75a8b3-263d-4231-8635-45715edea15a
{
  "count": 1,
  "host": [
    {
      "capabilities": "hvm",
      "clusterid": "16470d72-e2ed-486f-8a88-13e2a6b35f28",
      "clustername": "C1",
      "clustertype": "CloudManaged",
      "cpuallocated": "∞%",
      "cpuallocatedpercentage": "∞%",
      "cpuallocatedvalue": 500,
      "cpuallocatedwithoverprovisioning": "∞%",
      "cpuloadaverage": 0,
      "cpunumber": 0,
      "cpuspeed": 0,
      "cpuused": "0%",
      "cpuwithoverprovisioning": "0",
      "created": "2021-08-17T22:51:13+0530",
      "disconnected": "2021-08-17T23:13:21+0530",
      "events": "PingTimeout; AgentDisconnected; AgentConnected; ShutdownRequested; StartAgentRebalance; HostDown; ManagementServerDown; Ping; Remove",
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hypervisor": "Simulator",
      "hypervisorversion": "4.15.1.0",
      "id": "fc75a8b3-263d-4231-8635-45715edea15a",
      "ipaddress": "172.16.15.23",
      "islocalstorageactive": false,
      "lastpinged": "1970-01-19T15:27:17+0530",
      "managementserverid": "539c4407-9219-4b9b-924b-e21133d370cf",
      "memoryallocated": 1073741824,
      "memoryallocatedbytes": 1073741824,
      "memoryallocatedpercentage": "12.5%",
      "memorytotal": 8589934592,
      "memoryused": 0,
      "memorywithoverprovisioning": "8589934592",
      "name": "SimulatedAgent.15a2757a-2285-4ecf-86fc-75fb94c2cd5e",
      "networkkbsread": 32768,
      "networkkbswrite": 16384,
      "outofbandmanagement": {
        "enabled": false,
        "powerstate": "Disabled"
      },
      "podid": "8603df42-e369-4acc-9f42-f922540ba9c7",
      "podname": "POD0",
      "resourcestate": "Enabled",
      "state": "Up",
      "type": "Routing",
      "version": "4.15.1.0",
      "zoneid": "a5ee5b05-dded-4b2f-bbfb-4251187031c9",
      "zonename": "Sandbox-simulator"
    }
  ]
}

```

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
lgtm

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java [hunk 1]
```diff
@@ -212,4 +216,13 @@ public void setMemoryAllocatedDisableThreshold(final Long memAllocated, final Lo
         }
     }
 
+    private Double parseCPU(String cpu) {
```
Comment (nvazquez) [inline plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java:219]: Can we add some unit tests for it?

File: plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java [hunk 2]
```diff
@@ -212,4 +216,13 @@ public void setMemoryAllocatedDisableThreshold(final Long memAllocated, final Lo
...
+        DecimalFormat decimalFormat = new DecimalFormat("#.##");
+        try {
+            return decimalFormat.parse(cpu).doubleValue();
+        } catch (ParseException e) {
+            throw new CloudRuntimeException(e);
```
Comment (nvazquez) [inline plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java:224]: What about logging the exception and handling the exception? Either here or in the usage of this function. For example, the character in the PR description can cause the API to still fail:
````
"cpuallocated": "∞%",
"cpuallocatedpercentage": "∞%",
"cpuallocatedvalue": 500,
"cpuallocatedwithoverprovisioning": "∞%",
````

File: plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java (hunk 1 above)
Comment (shwstppr) [reply plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java:223]: Added test

File: plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java (hunk 2 above)
Comment (shwstppr) [reply plugins/metrics/src/main/java/org/apache/cloudstack/response/HostMetricsResponse.java:228]: @nvazquez as the ParseException is thrown as CloudRuntimeException, it will get logged:
```
INFO  [c.c.a.ApiServer] (qtp357350214-317:ctx-828b25d5) (logid:77b09f95) Timezone offset from UTC is: 0.0
ERROR [c.c.a.ApiServer] (qtp357350214-32:ctx-f4aa35d7 ctx-d7301148) (logid:b4fa39eb) unhandled exception executing api command: [Ljava.lang.String;@1a6da41c
com.cloud.utils.exception.CloudRuntimeException: Unparseable number: "abc"
	at org.apache.cloudstack.response.HostMetricsResponse.parseCPU(HostMetricsResponse.java:228)
	at org.apache.cloudstack.response.HostMetricsResponse.setCpuUsed(HostMetricsResponse.java:125)
	at org.apache.cloudstack.metrics.MetricsServiceImpl.listHostMetrics(MetricsServiceImpl.java:284)
	at org.apache.cloudstack.api.ListHostsMetricsCmd.execute(ListHostsMetricsCmd.java:50)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
	at com.cloud.api.ApiServer.queueCommand(ApiServer.java:764)
	at com.cloud.api.ApiServer.handleRequest(ApiServer.java:588)
	at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:321)
	at com.cloud.api.ApiServlet$1.run(ApiServlet.java:134)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:131)
	at com.cloud.api.ApiServlet.doGet(ApiServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1386)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.text.ParseException: Unparseable number: "abc"
	at java.base/java.text.NumberFormat.parse(NumberFormat.java:431)
	at org.apache.cloudstack.response.HostMetricsResponse.parseCPU(HostMetricsResponse.java:226)
	at org.apache.cloudstack.response.HostMetricsResponse.setCpuUsed(HostMetricsResponse.java:125)
	... 51 more
```

And API will fail in this case:
```
(local) 🐝 > list hostsmetrics  id=fc75a8b3-263d-4231-8635-45715edea15a
🙈 Error: (HTTP 530, error code 0) Unparseable number: "abc"
```

PR description shows API output. With the change (similar to main branch), `listHostsMetrics` API won't fail when there is 0 cpu for host or locale issue and it will just report `∞%` or `NaN Ghz` as values.
Change for not showing these invalid values can considered in a separate PR.

**Review by rhtyd — APPROVED** [review]

**Comment by rhtyd** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Review by nvazquez — APPROVED** [review]
Thanks @shwstppr. LGTM
