### PR TITLE
api,server: fix listing vm metrics for infra resources

### LINKED ISSUE #6756: Fail to deploy a new KVM Instance when ACS has VMware and KVM hypervisor clusters
##### ISSUE TYPE

~~~ 
 * Bug Report
~~~ 

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0.1
~~~

##### CONFIGURATION
ACS running with VMware and KVM hypervisors in different clusters and same pod 

##### OS / ENVIRONMENT
mgmt server: Rocky Linux 8
database server: Rocky Linux 8 (running together mgmt server)
VMware: 7.0.3.0
KVM: Rocky Linux 8

##### SUMMARY
When deploying a new KVM Instance using UI, it fails with this error message:

image

Using cmk works fine. 

mgmt logs:

 ~~~
2022-09-21 14:59:28,643 DEBUG [c.c.a.ApiServlet] (qtp396883763-22:ctx-a3f55da5) (logid:44a9ba61) ===START===  10.0.3.251 -- POST  command=deployVirtualMachine&response=json
2022-09-21 14:59:28,648 DEBUG [c.c.a.ApiServer] (qtp396883763-22:ctx-a3f55da5 ctx-9b374d70) (logid:44a9ba61) CIDRs from which account 'Acct[6024ea5f-38ff-11ed-939d-1e0070000145-admin] -- Account {"id": 2, "name": "admin", "uuid": "6024ea
5f-38ff-11ed-939d-1e0070000145"}' is allowed to perform API calls: 0.0.0.0/0,::/0
2022-09-21 14:59:28,663 DEBUG [c.c.u.AccountManagerImpl] (qtp396883763-22:ctx-a3f55da5 ctx-9b374d70) (logid:44a9ba61) Access granted to Acct[6024ea5f-38ff-11ed-939d-1e0070000145-admin] -- Account {"id": 2, "name": "admin", "uuid": "6024e
a5f-38ff-11ed-939d-1e0070000145"} to org.apache.cloudstack.quota.vo.ServiceOfferingVO$$EnhancerByCGLIB$$c6a34ac8@4fd3e10a by AffinityGroupAccessChecker
2022-09-21 14:59:28,663 DEBUG [c.c.u.AccountManagerImpl] (qtp396883763-22:ctx-a3f55da5 ctx-9b374d70) (logid:44a9ba61) Access granted to Acct[6024ea5f-38ff-11ed-939d-1e0070000145-admin] -- Account {"id": 2, "name": "admin", "uuid": "6024e
a5f-38ff-11ed-939d-1e0070000145"} to null by AffinityGroupAccessChecker
2022-09-21 14:59:28,667 INFO  [c.c.a.ApiServer] (qtp396883763-22:ctx-a3f55da5 ctx-9b374d70) (logid:44a9ba61) Hypervisor passed to the deployVm call, is different from the hypervisor type of the template
2022-09-21 14:59:28,668 DEBUG [c.c.a.ApiServlet] (qtp396883763-22:ctx-a3f55da5 ctx-9b374d70) (logid:44a9ba61) ===END===  10.0.3.251 -- POST  command=deployVirtualMachine&response=json
~~~

##### STEPS TO REPRODUCE
~~~
- Register a KVM Template
- Deploy a new Instance based on this template
~~~

##### EXPECTED RESULTS
~~~
Instance deployed and running
~~~

##### ACTUAL RESULTS
~~~
Fail to deploy the instance
~~~

### LINKED ISSUE #6786: UI: Instances list not filterable by hostid
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0.1
~~~

##### CONFIGURATION
Standard install

##### OS / ENVIRONMENT
N/A

##### SUMMARY
On the 'Hosts' page, clicking on 'View Instances' brings the user to a table of instances (VMs). However, this table is not filtered by the host appropriately even though the URL includes a `hostid=xxxx`. Instead, the table shows all instances in CloudStack.

##### STEPS TO REPRODUCE
1. Go to Infrastructure -> Hosts
2. Select a host (For example: `hostA`)
3. Click on 'View Instances'
4. See that the Instances table contains all VMs in CloudStack (**not** filtered to show only `hostA`'s VMs). The URL should contain something like: `/client/#/vm?hostid=7b313bd8-81fe-4e57-bccb-90df970f6d67`. Note that `hostA`'s `hostid` is being passed in the URI but has no effect.

##### EXPECTED RESULTS
Expect the Instances table is filtered to show only `hostA`'s VMs.

##### ACTUAL RESULTS
Instances table is **not** filtered to show only `hostA`'s VMs.

##### Additional info
I think the `hostid` parameter isn't actually used by the view. I _think_ the table view is generated and filtered by this file/line:

https://github.com/apache/cloudstack/blob/c5262443595e4ed1bb9898654f3bed728331ffc0/ui/src/views/AutogenView.vue#L1524

I don't see hostid actually be used here.

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #6786

listVirtualMachinesMetrics does not support some of the params that are supported by admin API call for listVirtualMachines. These parameters are used in UI.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+import org.apache.cloudstack.api.response.ClusterResponse;
+import org.apache.cloudstack.api.response.HostResponse;
+import org.apache.cloudstack.api.response.PodResponse;
+import org.apache.cloudstack.api.response.StoragePoolResponse;
+import org.apache.cloudstack.response.VmMetricsResponse;
+
+@APICommand(name = ListVMsMetricsCmd.APINAME, description = "Lists VM metrics", responseObject = VmMetricsResponse.class,
+        requestHasSensitiveInfo = false, responseHasSensitiveInfo = false,  responseView = ResponseObject.ResponseView.Full,
+        since = "4.9.3", authorized = {RoleType.Admin})
+@Deprecated(since = "4.17.0")
```
Comment (DaanHoogland) [inline plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:31]: why create a deprecated class?

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+import org.apache.cloudstack.api.command.admin.AdminCmd;
+import org.apache.cloudstack.api.response.ClusterResponse;
+import org.apache.cloudstack.api.response.HostResponse;
+import org.apache.cloudstack.api.response.PodResponse;
+import org.apache.cloudstack.api.response.StoragePoolResponse;
+import org.apache.cloudstack.response.VmMetricsResponse;
+
+@APICommand(name = ListVMsMetricsCmd.APINAME, description = "Lists VM metrics", responseObject = VmMetricsResponse.class,
+        requestHasSensitiveInfo = false, responseHasSensitiveInfo = false,  responseView = ResponseObject.ResponseView.Full,
+        since = "4.9.3", authorized = {RoleType.Admin})
```
Comment (DaanHoogland) [inline plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:30]:
```suggestion
        since = "4.18.0", authorized = {RoleType.Admin})
```

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java [hunk 3]
```diff
@@ -42,9 +44,9 @@
  */
 @APICommand(name = ListVMsMetricsCmd.APINAME, description = "Lists VM metrics", responseObject = VmMetricsResponse.class,
         requestHasSensitiveInfo = false, responseHasSensitiveInfo = false,  responseView = ResponseObject.ResponseView.Full,
-        since = "4.9.3", authorized = {RoleType.Admin,  RoleType.ResourceAdmin, RoleType.DomainAdmin, RoleType.User})
+        since = "4.9.3", authorized = {RoleType.ResourceAdmin, RoleType.DomainAdmin, RoleType.User})
 @Deprecated(since = "4.17.0")
```
Comment (DaanHoogland) [inline plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java:48]: what was the idea of deprecation? should we leave this annotation in?

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 4]
```diff
@@ -1035,16 +1045,14 @@ private Pair<List<UserVmJoinVO>, Integer> searchForUserVMsInternal(ListVMsCmd cm
         Object backupOfferingId = cmd.getBackupOfferingId();
         Object isHaEnabled = cmd.getHaEnabled();
         Object pod = null;
-        Long clusterId = null;
+        Object clusterId = null;
         Object hostId = null;
         Object storageId = null;
         if (_accountMgr.isRootAdmin(caller.getId())) {
-            if (cmd instanceof ListVMsCmdByAdmin) {
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:1042]: if we remove this, do we still need the extra class, or can we just implement the extra parameters in `ListVMsMetricsCmd`?

Comment (shwstppr) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:1042]: `ListVMsMetricsCmd` is accessible to all users therefore new `ByAdmin` class added and new params not added in the original

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 1 above)
Comment (shwstppr) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:31]: I can remove the deprecated tag but the original api class has this deprecated tag

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 4 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:1042]: does that matter? they will just not be able to use the extra parameters.

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 2 above)
Comment (shwstppr) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:30]: Not sure if it makes sense to add 4.18 here as it is not a new API just an additional Admin class for adding some params for admin account

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 1 above)
Comment (DaanHoogland) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:31]: I don´t know why it has/What the thought behind it was. But we are obviously intending to maintain it so it is not deprecated. Let's remove it.

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 2 above)
Comment (DaanHoogland) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:30]: I think we better remove the since attribute completely. I don't think it add value either way.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test matrix

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 2 above)
Comment (rohityadavcloud) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:30]: it might cause issue with apidocs generation - to be clear this isn't adding a new API; but an admin cmd (api with admin specific params)

**Comment by rohityadavcloud** [comment]
cc @nvazquez

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 1 above)
Comment (DaanHoogland) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:31]: @shwstppr ?

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 2 above)
Comment (DaanHoogland) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:30]: it shouldn´t, there are others without this annotation parameter are there?

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java (hunk 3 above)
Comment (DaanHoogland) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmd.java:48]: let's remove the deprecation annotation

**Review by DaanHoogland — CHANGES_REQUESTED** [review]
can you remove the depcation annotations and the since parameter on the new class?

**Comment by rohityadavcloud** [comment]
I think we should keep the since @DaanHoogland as it's not a new API (may affect data in apidocs), for the Deprecated, can you check 16f2896940cb6ae5557a51b6b439bd71917e1781 where this was introduced? I think too Deprecated should be removed.

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Comment by vladimirpetrov** [comment]
Now we have exactly the opposite behavior - KVM VM deployment works but VMWare fails:

```
2022-12-06 13:31:37,168 INFO  [c.c.a.ApiServer] (qtp1647766367-15:ctx-e93e5c38 ctx-ca4808ff) (logid:3c497499) Hypervisor passed to the deployVm call, is different from the hypervisor type of the template
```

And it works when using cmk.

**Comment by shwstppr** [comment]
> Now we have exactly the opposite behavior - KVM VM deployment works but VMWare fails:
> 
> ```
> 2022-12-06 13:31:37,168 INFO  [c.c.a.ApiServer] (qtp1647766367-15:ctx-e93e5c38 ctx-ca4808ff) (logid:3c497499) Hypervisor passed to the deployVm call, is different from the hypervisor type of the template
> ```
> 
> And it works when using cmk.

It seems I've tagged the wrong issue to this PR. I've fixed that in desc now. Will check #6756 for a fix

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 1 above)
Comment (rohityadavcloud) [inline plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:31]:
```suggestion
```

**Review by rohityadavcloud — APPROVED** [review]

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 4 above)
Comment (rohityadavcloud) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:1042]: I think is this a common pattern (unless we want to deprecate this) used across 54 APIs:


```
> find . | grep ByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vmsnapshot/RevertToVMSnapshotCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/ListIsosCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/UpdateIsoCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/DetachIsoCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/ListIsoPermissionsCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/AttachIsoCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/CopyIsoCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/iso/RegisterIsoCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/zone/ListZonesCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/network/ListNetworksCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/network/UpdateNetworkCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/network/CreateNetworkCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/template/ListTemplatesCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/template/CreateTemplateCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/template/RegisterTemplateCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/template/UpdateTemplateCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/template/CopyTemplateCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/template/ListTemplatePermissionsCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/loadbalancer/ListLoadBalancerRuleInstancesCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/StopVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/DestroyVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ScaleVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ListVMsCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/DeployVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/StartVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/RebootVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/RemoveNicFromVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/UpdateDefaultNicForVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/UpgradeVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ResetVMSSHKeyCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/UpdateVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/AddNicToVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/RestoreVMCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vm/ResetVMPasswordCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/address/ListPublicIpAddressesCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/address/AcquirePodIpCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/address/ReleasePodIpCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/address/AssociateIPAddrCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/ListVPCsCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/CreateVPCCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/vpc/UpdateVPCCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/affinitygroup/UpdateVMAffinityGroupCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/account/ListAccountsCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/domain/ListDomainsCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/ResizeVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/ListVolumesCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/DestroyVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/UpdateVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/CreateVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/AttachVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/RecoverVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/MigrateVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/UploadVolumeCmdByAdmin.java
./api/src/main/java/org/apache/cloudstack/api/command/admin/volume/DetachVolumeCmdByAdmin.java
```

**Review by rohityadavcloud — APPROVED** [review]

**Comment by rohityadavcloud** [comment]
@DaanHoogland can you review/lgtm?

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java (hunk 2 above)
Comment (DaanHoogland) [reply plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:30]:
```suggestion
        authorized = {RoleType.Admin})
```

File: plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+    @Parameter(name=ApiConstants.POD_ID, type= BaseCmd.CommandType.UUID, entityType= PodResponse.class,
+            description="the pod ID")
+    private Long podId;
+
+    @Parameter(name=ApiConstants.STORAGE_ID, type= BaseCmd.CommandType.UUID, entityType= StoragePoolResponse.class,
+            description="the storage ID where vm's volumes belong to")
+    private Long storageId;
+
+    @Parameter(name = ApiConstants.CLUSTER_ID, type = BaseCmd.CommandType.UUID, entityType = ClusterResponse.class,
+            description = "the cluster ID", since = "4.16.0")
```
Comment (DaanHoogland) [inline plugins/metrics/src/main/java/org/apache/cloudstack/api/ListVMsMetricsCmdByAdmin.java:50]:
```suggestion
            description = "the cluster ID")
```

we should not add an antidated parameter.

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 6]
```diff
@@ -971,6 +972,15 @@ public ListResponse<UserVmResponse> searchForUserVMs(ListVMsCmd cmd) {
         return response;
     }
 
+    private Object getObjectPossibleMethodValue(Object obj, String methodName) {
+        Object result = null;
+        try {
+            Method m = obj.getClass().getMethod(methodName);
+            result = m.invoke(obj);
+        } catch (NoSuchMethodException | InvocationTargetException | IllegalAccessException ignored) {}
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:980]: not even logged?

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 4 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:1042]: But these use the `if (cmd instaceof <...>ByAdmin) {}` pattern. Or we changing this? It is a good improvement in some ways but would justify its own PR.

**Review by DaanHoogland — COMMENTED** [review]
still have some remarks. none of these are blockers, but may lead to more `too many gurus` patterns in the code. A consideration to make.

**Comment by shwstppr** [comment]
@DaanHoogland I've closed this PR as I don't think I have the complete understanding to produce a proper fix. Can you please look into the issue for the fix and comment if it is critical for 4.17.2 milestone

**Comment by rohityadavcloud** [comment]
@DaanHoogland can you address your comments in code, fix this and ping me. I appreciate if we can get this merge for 4.17.2; Vladi has already tested this.

**Comment by DaanHoogland** [comment]
> @DaanHoogland I've closed this PR as I don't think I have the complete understanding to produce a proper fix. Can you please look into the issue for the fix and comment if it is critical for 4.17.2 milestone

your fix is mostly good @shwstppr , I only ask to not introduce the reflection pattern for this change (and some minor things). I'll adress the changes.

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
Will merge this after this round of pkging+smoketests.

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 7]
```diff
@@ -1035,7 +1035,7 @@ private Pair<List<UserVmJoinVO>, Integer> searchForUserVMsInternal(ListVMsCmd cm
         Object backupOfferingId = cmd.getBackupOfferingId();
         Object isHaEnabled = cmd.getHaEnabled();
         Object pod = null;
-        Long clusterId = null;
+        Object clusterId = null;
         Object hostId = null;
         Object storageId = null;
         if (_accountMgr.isRootAdmin(caller.getId())) {
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:1041]: @DaanHoogland I am afraid the below code may not work as cmd will be an instance of `ListVMsMetricsCmdByAdmin` and not `ListVMsCmdByAdmin`

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 8]
```diff
@@ -971,6 +972,17 @@ public ListResponse<UserVmResponse> searchForUserVMs(ListVMsCmd cmd) {
         return response;
     }
 
+    private Object getObjectPossibleMethodValue(Object obj, String methodName) {
+        Object result = null;
```
Comment (rohityadavcloud) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:976]: @DaanHoogland could you add a unit test to cover this method?

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java [hunk 9]
```diff
@@ -971,6 +972,17 @@ public ListResponse<UserVmResponse> searchForUserVMs(ListVMsCmd cmd) {
...
+
+        try {
+            Method m = obj.getClass().getMethod(methodName);
+            result = m.invoke(obj);
+        } catch (NoSuchMethodException | InvocationTargetException | IllegalAccessException ignored) {}
```
Comment (rohityadavcloud) [inline server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:981]: Perhaps log here? @DaanHoogland or do you think we may never hit this?

**Comment by rohityadavcloud** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/api/query/QueryManagerImpl.java (hunk 9 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/api/query/QueryManagerImpl.java:981]: i was thinking that as well, but didn´t want to change to much anymore. We will hit this for sure in the current state if ListVMsCmd is called in the API. It will try to add the attributes that don´t exist and we are supposed to ignore those.
```suggestion
        } catch (NoSuchMethodException | InvocationTargetException | IllegalAccessException ignored) {/*ignored when non-ByAdmin are calling this.*/}
```

**Comment by rohityadavcloud** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by rohityadavcloud** [comment]
Unmanage VM test issues fixed in another commit. Merging this but will monitor tests on 4.17 branch.
