### PR TITLE
engine/schema: fix duplicated guest OSes in 4.18.0.0

### LINKED ISSUE #7783: Duplicated guest OSes in ACS 4.18.0.0
database query

```
mysql> select display_name,count(1) as count from guest_os group by display_name having count >1;
+------------------------------+-------+
| display_name                 | count |
+------------------------------+-------+
| SCO OpenServer 5             |     2 |
| Ubuntu 20.04 LTS             |     2 |
| Debian GNU/Linux 11 (64-bit) |     2 |
| Debian GNU/Linux 11 (32-bit) |     2 |
| CentOS 9                     |     2 |
| Oracle Linux 9               |     2 |
+------------------------------+-------+
6 rows in set (0.00 sec)

```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #7783 and #7781

(Need to merge duplicated guest OSes, and keep only one of them)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
hmm, the simulator setup failed with error
```
 Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (create-schema) on project cloud-developer: An exception occured while executing the Java class. null: InvocationTargetException: Unable to upgrade the database: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO guest_os_hypervisor (guest_os_hypervisor.guest_os_id, guest_os_hypervisor.guest_os_name, guest_os_hypervisor.hypervisor_type, guest_os_hypervisor.hypervisor_version, guest_os_hypervisor.uuid, guest_os_hypervisor.created, guest_os_hypervisor.is_user_defined) VALUES (0, x'53555345204C696E757820456E7465727072697365204465736B746F7020313220535033202836342D62697429', x'58656E736572766572', x'382E312E30', x'65353830373034652D653837632D343266302D383730662D376532666639313665323163', '2023-08-02 00:52:10', 0): Cannot add or update a child row: a foreign key constraint fails (`cloud`.`guest_os_hypervisor`, CONSTRAINT `guest_os_hypervisor_ibfk_1` FOREIGN KEY (`guest_os_id`) REFERENCES `guest_os` (`id`)) -> [Help 1]
```

**Comment by weizhouapache** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java [hunk 1]
```diff
@@ -74,18 +74,19 @@ private long getGuestOsIdFromHypervisorMapping(GuestOSHypervisorMapping mapping)
...
         long guestOsId = getGuestOsId(categoryId, displayName);
         if (guestOsId == 0) {
             LOG.debug("No guest OS found with category id: " + categoryId + " and display name: " + displayName);
+            if (!addGuestOs(categoryId, displayName)) {
+                LOG.warn("Couldn't add the guest OS with category id: " + categoryId + " and display name: " + displayName);
+                return;
+            }
+            guestOsId = getGuestOsId(categoryId, displayName);
+        } else {
+            // TODO: update is_user_defined to false
```
Comment (harikrishna-patnala) [inline engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java]: In my opinion, we better leave the user_defined flag as is to keep track of operator activities.

Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java]: we can use the user_defined flag to decide which ones to remove and only keep the system defined one. In this case we, will have to allow for the ectra definition to begin with and deduplicate it right away.

Comment (harikrishna-patnala) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java]: How about adding a new guest OS entry if the existing one is user-defined ?

We are anyways deduplicating the list from listGuestOS command starting 4.19 version, we will show only the latest entry if there duplicates. cc @DaanHoogland

Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java]: @harikrishna-patnala is there another place the deduplication is already taking place (see my pseudo code)?

I do agree we should look at the user defined flag during deduplication. seems like the cleanest way.

Comment (harikrishna-patnala) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java]: @DaanHoogland I'm thinking of not doing any merge operation as it may affect the old entries in older versions as well.

I think the problem here is only that we have duplicate guest OS entries, which is not a critical/major issue. 
My proposal is to leave them as is and make fix for future entries.

Regarding the "Red Hat Enterprise Linux 9" and other similar entries, instead of doing a merge operation, I would suggest adding new mapping entries for both the names (RHEL and RHEL9*) so that if the operator uses any of the Guest OSs it won't behave differently while deploying VM (otherwise if the mapping is not found, CS may choose "default").

@weizhouapache @DaanHoogland

**Comment by DaanHoogland** [comment]
@blueorangutan package

File: api/src/main/java/org/apache/cloudstack/api/command/admin/guest/AddGuestOsCmd.java [hunk 2]
```diff
@@ -16,6 +16,7 @@
 // under the License.
 package org.apache.cloudstack.api.command.admin.guest;
 
+import org.apache.cloudstack.acl.RoleType;
```
Comment (weizhouapache) [inline api/src/main/java/org/apache/cloudstack/api/command/admin/guest/AddGuestOsCmd.java:19]: this can be moved to line 22 for alignment

File: engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDao.java [hunk 3]
```diff
@@ -19,9 +19,16 @@
 import com.cloud.storage.GuestOSVO;
 import com.cloud.utils.db.GenericDao;
 
+import java.util.List;
+import java.util.Set;
+
 public interface GuestOSDao extends GenericDao<GuestOSVO, Long> {
 
-    GuestOSVO listByDisplayName(String displayName);
+    GuestOSVO listOneByDisplayName(String displayName);
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDao.java:27]: use `find` instead of `list` in the method name?

File: engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java [hunk 4]
```diff
@@ -62,4 +71,41 @@ public GuestOSVO findByCategoryIdAndDisplayNameOrderByCreatedDesc(long categoryI
...
+     "select * from guest_os go2 where display_name in"
+     +       "(select display_name from"
+     +               "(select display_name, count(1) as count from guest_os go1 group by display_name having count > 1) tab0)";
+     *
+     * @return
+     */
+    @Override
+    @DB
+    public Set<String> findDoubleNames() {
+        String selectSql = "(select display_name from (select display_name, count(1) as count from guest_os go1 group by display_name having count > 1) tab0)";
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java:85]:
```suggestion
        String selectSql = "select display_name, count(1) as count from guest_os where removed IS NULL group by display_name having count > 1";
```

File: api/src/main/java/org/apache/cloudstack/api/command/admin/guest/UpdateGuestOsCmd.java [hunk 5]
```diff
@@ -16,6 +16,7 @@
 // under the License.
 package org.apache.cloudstack.api.command.admin.guest;
 
+import org.apache.cloudstack.acl.RoleType;
```
Comment (weizhouapache) [inline api/src/main/java/org/apache/cloudstack/api/command/admin/guest/UpdateGuestOsCmd.java:19]: same as previous

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java [hunk 6]
```diff
@@ -51,6 +53,86 @@ public GuestOsMapper() {
...
+            copyMappings(guestOSVO, mappings);
+            // // find VMs
+            // // // for each VM
+            // // // // set the guest_os_id to the one to keep
+            // // find templates
+            // // // for each template
+            // // // // set the guest_os_id to the one to keep
+            // // mark as removed
+
+        }
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:83]: after copying, should we keep only the first or last guest os as is_display=true ?

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java [hunk 7]
```diff
@@ -51,6 +53,86 @@ public GuestOsMapper() {
...
+                guestOSHypervisorDao.persist(newMap);
+            }
+        }
+    }
+
+    private GuestOSVO highestIdFrom(Set<GuestOSVO> setOfGuestOSes) {
+        GuestOSVO rc = null;
+        for (GuestOSVO guestOSVO: setOfGuestOSes) {
+            if (rc == null || (guestOSVO.getId() > rc.getId() && !guestOSVO.getIsUserDefined())) {
+                rc = guestOSVO;
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:105]: just `return guestOSVO` here ?

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java [hunk 8]
```diff
@@ -2798,16 +2798,24 @@ public GuestOS addGuestOs(final AddGuestOsCmd cmd) {
...
         final GuestOS guestOsPersisted = _guestOSDao.persist(guestOsVo);
 
-        if (cmd.getDetails() != null && !cmd.getDetails().isEmpty()) {
-            Map<String, String> detailsMap = cmd.getDetails();
-            for (Object key : detailsMap.keySet()) {
-                _guestOsDetailsDao.addDetail(guestOsPersisted.getId(), (String)key, detailsMap.get(key), false);
-            }
-        }
+        Map<String, String> details = cmd.getDetails();
+        Boolean forDisplay = cmd.getForDisplay();
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/server/ManagementServerImpl.java:2802]: there are following columns in tables
`display_vm` in `vm_instance`
`display_volume` in `volumes`
`display_network` in `networks`
`display_nic` in `nics`
`display` in `vpc`
`display` in `firewall_rules`

can we add a new column `display` to `guest_os` table as well ?

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java (hunk 6 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:83]: I think the default for is_display should be `true` and we should set it only to `false` the ones that we copied the mappings from. We can set `true` on the target, but that wouldn't matter with the right default.

I need to add extra safety checks

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java (hunk 7 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:105]: no, bad pattern to have multiple exit points from a method

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java (hunk 8 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2802]: no, we can not. We painted ourselves in a corner and can not add to that table because it will exception out on upgrades.

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java (hunk 7 above)
Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:105]: ok. you can add a `break;` then

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java (hunk 8 above)
Comment (weizhouapache) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2802]: if we use a detail for display/not-display, it will bring more work on 
- update guest os between display/not-display
- list guest OSes by display or not-display

if we add a column in upgrade sql or in java, will there be exception during upgrade ?

File: engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java (hunk 4 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java:85]: not quite, I want a list of guestos names returned and no counts. I will add the `removed IS NULL`

Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java]: > not quite, I want a list of guestos names returned and no counts. I will add the `removed IS NULL`

@DaanHoogland 
I know. but you have the following code, so it does not matter if count is returned.
```
names.add(rs.getString(1));
```

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java (hunk 6 above)
Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:83]: agree, the default should be `true`

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java (hunk 8 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2802]: yes, there will be

File: engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java (hunk 4 above)
Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java]: I let the DB do what it is good at. makes sense?

File: server/src/main/java/com/cloud/server/ManagementServerImpl.java (hunk 8 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2802]: we need to change the older upgrade sql if we want to prevent this exception from occuring, which is a bad hack

Comment (weizhouapache) [reply server/src/main/java/com/cloud/server/ManagementServerImpl.java:2802]: @DaanHoogland 
We can add the column with default value, then we do not need to update the SQLs.

File: engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java (hunk 4 above)
Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/storage/dao/GuestOSDaoImpl.java]: it is not needed to use 2 select, imho.
If you do not want to change it, it is ok.

File: engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql [hunk 9]
```diff
@@ -1568,4 +1568,6 @@ UPDATE
 SET
   usage_type = 22
 WHERE
-  usage_type = 24 AND usage_display like '% io write';
\ No newline at end of file
+  usage_type = 24 AND usage_display like '% io write';
+
+CALL `cloud`.`IDEMPOTENT_ADD_COLUMN`('cloud.guest_os', 'display', 'tinyint(1) DEFAULT ''1'' COMMENT ''should this guest_os be shown to the end user'' ');
```
Comment (weizhouapache) [inline engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql:1573]: @DaanHoogland 
as we discussed, add this to 4.16.0->4.16.1->4.17.0->4.17.1->4.17.2 as well ?

File: engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java [hunk 10]
```diff
@@ -72,19 +72,17 @@ private void makeNormative(GuestOSVO guestOSVO, Set<GuestOSVO> setOfGuestOSes) {
         for (GuestOSVO oldGuestOs : setOfGuestOSes) {
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/GuestOsMapper.java:72]: skip `if (oldGuestOs.getId() == guestOSVO.getId())` ?

File: engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql (hunk 9 above)
Comment (DaanHoogland) [reply engine/schema/src/main/resources/META-INF/db/schema-41720to41800.sql:1573]: no, I checked (and will test) the guestosmapper is not yet used in those.

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@BryanMLima @weizhouapache I think I addressed all quirks. Only thing left to do is deal with the display flag in a proper manner when creating new mappings. please review

**Comment by DaanHoogland** [comment]
> @BryanMLima @weizhouapache I think I addressed all quirks. Only thing left to do is deal with the display flag in a proper manner when creating new mappings. please review

cc @harikrishna-patnala

**Comment by DaanHoogland** [comment]
@BryanMLima can you test this?

**Comment by DaanHoogland** [comment]
> @DaanHoogland I manually tested this patch. I have some concerns about hiding some Guest OS.
> 
> Root Admins still have access to the duplicate mappings, when I tried to register a new template, or edit one, the duplicate entries were still listed. There are scenarios that Root Admin accounts register templates for the end user; thus, it does not solve for this case.

But they are ROOT admins and should know which guest OSses to use, we can also present a list with only unhidden guest OSses, like for normal users.

As an extra measure we can disable registering new templates with these OSses. does that make sense? (global setting guarded)

> 
> Overall, I do not think the `forDisplay` parameter is necessary, at least not for solving the issue at hand. In the method `mergeDuplicates` it should mark the duplicate entries as removed, instead of hiding it. The mappings are already copied, thus, this approach should not cause any problems.

I heard concerns about the removal for guest OSses that might be still in use. If there are none we can of course implement that as well.

The forDisplay parameter is extra functionality and would also allow admins to hide unwanted OSses. Like, "As a operator I want no ubuntu on my systems", i can now disable it. I would like to keep it anyway.

**Comment by weizhouapache** [comment]
> > @DaanHoogland I manually tested this patch. I have some concerns about hiding some Guest OS.
> > Root Admins still have access to the duplicate mappings, when I tried to register a new template, or edit one, the duplicate entries were still listed. There are scenarios that Root Admin accounts register templates for the end user; thus, it does not solve for this case.
> 
> But they are ROOT admins and should know which guest OSses to use, we can also present a list with only unhidden guest OSses, like for normal users.
> 
> As an extra measure we can disable registering new templates with these OSses. does that make sense? (global setting guarded)
> 
> > Overall, I do not think the `forDisplay` parameter is necessary, at least not for solving the issue at hand. In the method `mergeDuplicates` it should mark the duplicate entries as removed, instead of hiding it. The mappings are already copied, thus, this approach should not cause any problems.
> 
> I heard concerns about the removal for guest OSses that might be still in use. If there are none we can of course implement that as well.
> 
> The forDisplay parameter is extra functionality and would also allow admins to hide unwanted OSses. Like, "As a operator I want no ubuntu on my systems", i can now disable it. I would like to keep it anyway.

@DaanHoogland 
I think we should add a parameter to listGuestOSes API, like the following
```
    @Parameter(name = ApiConstants.FOR_DISPLAY, type = CommandType.BOOLEAN, description = "list resources by display flag; only ROOT admin is eligible to pass this parameter", since = "4.18.1", authorized = {RoleType.Admin})
    private Boolean display;
```
The default value is `true` for all users. Then we will get the guest OSes which have display flag as true on UI and API response.
All others guest OSes will be hidden, but VMs using them will still work, no need to update the guest os id of vm templates and vm instances.

**Comment by weizhouapache** [comment]
> @DaanHoogland I think we should add a parameter to listGuestOSes API, like the following
> 
> ```
>     @Parameter(name = ApiConstants.FOR_DISPLAY, type = CommandType.BOOLEAN, description = "list resources by display flag; only ROOT admin is eligible to pass this parameter", since = "4.18.1", authorized = {RoleType.Admin})
>     private Boolean display;
> ```
> 
> The default value is `true` for all users. Then we will get the guest OSes which have display flag as true on UI and API response. All others guest OSes will be hidden, but VMs using them will still work, no need to update the guest os id of vm templates and vm instances.


updated the PR

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
@weizhouapache @BryanMLima , you two are having different concerns and propose different solutions to those concerns. I think both solutions are viable and neither of the concerns are problematic. Can we agree on a way forward?

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test keepEnv

**Comment by weizhouapache** [comment]
tested a fresh installation with this PR, all looks good
```
MariaDB [cloud]> select display_name,count(1) as count from guest_os group by display_name having count >1;
+------------------+-------+
| display_name     | count |
+------------------+-------+
| Oracle Linux 9   |     2 |
| SCO OpenServer 5 |     2 |
+------------------+-------+
2 rows in set (0.00 sec)

MariaDB [cloud]> 
MariaDB [cloud]> select * from guest_os join (select display_name,count(1) as count from guest_os group by display_name having count >1) dup where guest_os.display_name = dup.display_name;
+-----+-------------+------+--------------------------------------+------------------+---------------------+---------+-----------------+---------+------------------+-------+
| id  | category_id | name | uuid                                 | display_name     | created             | removed | is_user_defined | display | display_name     | count |
+-----+-------------+------+--------------------------------------+------------------+---------------------+---------+-----------------+---------+------------------+-------+
|  85 |           9 | NULL | e37ab646-3db2-11ee-89e3-1e00fe0000fb | SCO OpenServer 5 | 2023-08-18 10:35:25 | NULL    |               0 |       1 | SCO OpenServer 5 |     2 |
| 315 |           1 | NULL | f75a059f-3db2-11ee-89e3-1e00fe0000fb | Oracle Linux 9   | 2023-08-18 10:35:35 | NULL    |               0 |       1 | Oracle Linux 9   |     2 |
| 329 |           3 | NULL | 68dea665-038b-4437-ae31-54599e892a24 | Oracle Linux 9   | 2023-08-18 10:35:37 | NULL    |               0 |       0 | Oracle Linux 9   |     2 |
| 353 |           7 | NULL | 4988ca91-11aa-43e4-91bf-dc1de45265e1 | SCO OpenServer 5 | 2023-08-18 10:35:37 | NULL    |               0 |       0 | SCO OpenServer 5 |     2 |
+-----+-------------+------+--------------------------------------+------------------+---------------------+---------+-----------------+---------+------------------+-------+
4 rows in set (0.00 sec)

MariaDB [cloud]> 
MariaDB [cloud]> select * from guest_os where display_name like "Red Hat Enterprise Linux 9%";
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+---------+
| id  | category_id | name | uuid                                 | display_name                 | created             | removed | is_user_defined | display |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+---------+
| 316 |           1 | NULL | f75a1769-3db2-11ee-89e3-1e00fe0000fb | Red Hat Enterprise Linux 9   | 2023-08-18 10:35:35 | NULL    |               0 |       0 |
| 332 |           4 | NULL | be590632-316c-46ea-970c-9569dfd7e732 | Red Hat Enterprise Linux 9.0 | 2023-08-18 10:35:37 | NULL    |               0 |       1 |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+---------+
2 rows in set (0.00 sec)

MariaDB [cloud]> select * from guest_os_hypervisor where guest_os_id in (select id from guest_os where display_name like "Red Hat Enterprise Linux 9");
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| id   | hypervisor_type | guest_os_name              | guest_os_id | hypervisor_version | uuid                                 | created             | removed | is_user_defined |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| 8584 | KVM             | Red Hat Enterprise Linux 9 |         316 | default            | f75a1f1e-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 8588 | VMware          | rhel9_64Guest              |         316 | 7.0                | f75a62c8-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 8592 | VMware          | rhel9_64Guest              |         316 | 7.0.1.0            | f75aa4cc-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 8596 | VMware          | rhel9_64Guest              |         316 | 7.0.2.0            | f75ae5aa-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 8600 | VMware          | rhel9_64Guest              |         316 | 7.0.3.0            | f75b2753-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 8827 | VMware          | rhel9_64Guest              |         316 | 8.0                | f75bafe2-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 9082 | VMware          | rhel9_64Guest              |         316 | 8.0.0.1            | f75c73f7-3db2-11ee-89e3-1e00fe0000fb | 2023-08-18 10:35:35 | NULL    |               0 |
| 9631 | VMware          | rhel9_64Guest              |         316 | 8.0.1              | 047a6fc6-4649-4993-9be1-3407adb19d57 | 2023-08-18 10:35:37 | NULL    |               0 |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
8 rows in set (0.00 sec)

MariaDB [cloud]> select * from guest_os_hypervisor where guest_os_id in (select id from guest_os where display_name like "Red Hat Enterprise Linux 9.0");
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| id   | hypervisor_type | guest_os_name              | guest_os_id | hypervisor_version | uuid                                 | created             | removed | is_user_defined |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| 9138 | VMware          | rhel9_64Guest              |         332 | 7.0.1.0            | 1d2b9b9d-0fd1-4b56-afa7-fd1ab544bf41 | 2023-08-18 10:35:37 | NULL    |               0 |
| 9646 | KVM             | Red Hat Enterprise Linux 9 |         332 | default            | a179dc2e-2fa8-4d37-b02b-fc4f1c1e7a31 | 2023-08-18 10:35:37 | NULL    |               0 |
| 9647 | VMware          | rhel9_64Guest              |         332 | 7.0                | 250aeb8a-9b28-425e-ad35-febd810ee7c3 | 2023-08-18 10:35:37 | NULL    |               0 |
| 9648 | VMware          | rhel9_64Guest              |         332 | 7.0.2.0            | c5b5703e-9a63-4826-a7d2-d6abe56bad28 | 2023-08-18 10:35:37 | NULL    |               0 |
| 9649 | VMware          | rhel9_64Guest              |         332 | 7.0.3.0            | b4eba39d-55c9-4c46-83e3-f7a31136e64a | 2023-08-18 10:35:37 | NULL    |               0 |
| 9650 | VMware          | rhel9_64Guest              |         332 | 8.0                | 0657753f-1587-40e3-9785-439503ef979a | 2023-08-18 10:35:37 | NULL    |               0 |
| 9651 | VMware          | rhel9_64Guest              |         332 | 8.0.0.1            | fd73ef92-e817-4f91-8963-b3711a7917b7 | 2023-08-18 10:35:37 | NULL    |               0 |
| 9652 | VMware          | rhel9_64Guest              |         332 | 8.0.1              | 7cfdb21e-fbe0-471c-b2f3-6730901073a0 | 2023-08-18 10:35:37 | NULL    |               0 |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
8 rows in set (0.00 sec)
```

**Comment by weizhouapache** [comment]
test2: upgrade from 4.16.1.1 to 4.18, then to this PR

- 4.16.1.1, looks ok, only 1 duplicated guest OS
```
MariaDB [cloud]> select display_name,count(1) as count from guest_os group by display_name having count >1;
+------------------+-------+
| display_name     | count |
+------------------+-------+
| SCO OpenServer 5 |     2 |
+------------------+-------+
1 row in set (0.00 sec)

MariaDB [cloud]> select * from guest_os join (select display_name,count(1) as count from guest_os group by display_name having count >1) dup where guest_os.display_name = dup.display_name;
+-----+-------------+------+--------------------------------------+------------------+---------------------+---------+-----------------+------------------+-------+
| id  | category_id | name | uuid                                 | display_name     | created             | removed | is_user_defined | display_name     | count |
+-----+-------------+------+--------------------------------------+------------------+---------------------+---------+-----------------+------------------+-------+
|  85 |           9 | NULL | 221980dd-3d9d-11ee-af47-1e001e00011f | SCO OpenServer 5 | 2023-08-18 07:59:36 | NULL    |               0 | SCO OpenServer 5 |     2 |
| 324 |           7 | NULL | 916d7fff-4c71-4a8e-9122-e705495a13ce | SCO OpenServer 5 | 2023-08-18 07:59:44 | NULL    |               0 | SCO OpenServer 5 |     2 |
+-----+-------------+------+--------------------------------------+------------------+---------------------+---------+-----------------+------------------+-------+
2 rows in set (0.00 sec)

MariaDB [cloud]> 
MariaDB [cloud]> select * from guest_os where display_name like "Red Hat Enterprise Linux 9%";
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+
| id  | category_id | name | uuid                                 | display_name                 | created             | removed | is_user_defined |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+
| 348 |           4 | NULL | 9458424f-0b9a-4abe-8119-b91b7c705fb1 | Red Hat Enterprise Linux 9.0 | 2023-08-18 07:59:44 | NULL    |               0 |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+
1 row in set (0.00 sec)
```

- upgrade to 4.18, 43 duplicated guest OSes
```
MariaDB [cloud]> select display_name,count(1) as count from guest_os group by display_name having count >1;
+-----------------------------------------------+-------+
| display_name                                  | count |
+-----------------------------------------------+-------+
| Amazon Linux 2 (64 bit)                       |     2 |
| Amazon Linux 3 (64 bit)                       |     2 |
| Asianux Server 4 (32 bit)                     |     2 |
| Asianux Server 4 (64 bit)                     |     2 |
| Asianux Server 5 (32 bit)                     |     2 |
| Asianux Server 5 (64 bit)                     |     2 |
| Asianux Server 7 (32 bit)                     |     2 |
| Asianux Server 7 (64 bit)                     |     2 |
| Asianux Server 8 (64 bit)                     |     2 |
| Asianux Server 9 (64 bit)                     |     2 |
| CentOS 9                                      |     2 |
| Debian GNU/Linux 11 (32-bit)                  |     2 |
| Debian GNU/Linux 11 (64-bit)                  |     2 |
| eComStation 2.0                               |     2 |
| Fedora Linux (64 bit)                         |     2 |
| FreeBSD 13 (32-bit)                           |     2 |
| FreeBSD 13 (64-bit)                           |     2 |
| Linux 3.x Kernel (32 bit)                     |     2 |
| Linux 3.x Kernel (64 bit)                     |     2 |
| Linux 5.x Kernel (32-bit)                     |     2 |
| Linux 5.x Kernel (64-bit)                     |     2 |
| macOS 10.13 (64 bit)                          |     2 |
| macOS 10.14 (64 bit)                          |     2 |
| macOS 10.15 (64 bit)                          |     2 |
| macOS 11 (64 bit)                             |     2 |
| Mandrake Linux                                |     2 |
| Mandriva Linux (64 bit)                       |     2 |
| NeoKylin Linux Server 7                       |     2 |
| OpenSUSE Linux (32 bit)                       |     2 |
| OpenSUSE Linux (64 bit)                       |     2 |
| Oracle Linux 9                                |     3 |
| OVF Configured OS                             |     2 |
| Red Hat Enterprise Linux 9.0                  |     2 |
| Scientific Linux 7                            |     2 |
| SCO OpenServer 5                              |     3 |
| SCO OpenServer 6                              |     2 |
| Solaris 11 (64 bit)                           |     2 |
| SUSE Linux Enterprise Desktop 12 SP3 (64-bit) |     2 |
| SUSE Linux Enterprise Desktop 12 SP4 (64-bit) |     2 |
| SUSE Linux Enterprise Server 12 SP4 (64-bit)  |     2 |
| SUSE Linux Enterprise Server 16 (64-bit)      |     2 |
| Ubuntu 20.04 LTS                              |     2 |
| VMware Photon (64 bit)                        |     2 |
+-----------------------------------------------+-------+
43 rows in set (0.01 sec)
```
the RHEL 9 issue also exist
```
MariaDB [cloud]> select * from guest_os where display_name like "Red Hat Enterprise Linux 9%";
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+
| id  | category_id | name | uuid                                 | display_name                 | created             | removed | is_user_defined |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+
| 348 |           4 | NULL | 9458424f-0b9a-4abe-8119-b91b7c705fb1 | Red Hat Enterprise Linux 9.0 | 2023-08-18 07:59:44 | NULL    |               0 |
| 357 |           1 | NULL | 05a1e5a6-3ff8-11ee-af47-1e001e00011f | Red Hat Enterprise Linux 9   | 2023-08-21 07:54:57 | NULL    |               0 |
| 377 |           4 | NULL | c5c314e4-5da2-4b72-927f-21fb35c8276a | Red Hat Enterprise Linux 9.0 | 2023-08-21 07:54:59 | NULL    |               0 |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+
3 rows in set (0.00 sec)
```

- upgrade to this PR, looks ok (only 1 of duplications has display=1, which has all the guest os mappings of other duplications)

```
MariaDB [cloud]> select * from guest_os join (select display_name,count(1) as count from guest_os group by display_name having count >1) dup where guest_os.display_name = dup.display_name and display=1;
+-----+-------------+------+--------------------------------------+-----------------------------------------------+---------------------+---------+-----------------+---------+-----------------------------------------------+-------+
| id  | category_id | name | uuid                                 | display_name                                  | created             | removed | is_user_defined | display | display_name                                  | count |
+-----+-------------+------+--------------------------------------+-----------------------------------------------+---------------------+---------+-----------------+---------+-----------------------------------------------+-------+
|  85 |           9 | NULL | 221980dd-3d9d-11ee-af47-1e001e00011f | SCO OpenServer 5                              | 2023-08-18 07:59:36 | NULL    |               0 |       1 | SCO OpenServer 5                              |     3 |
| 305 |          11 | NULL | 0bc2fefa-7a5a-4926-b34d-8acdae172201 | OVF Configured OS                             | 2023-08-18 07:59:44 | NULL    |               0 |       1 | OVF Configured OS                             |     2 |
| 307 |           2 | NULL | ebffba86-cd83-41c5-aafe-44138d677f37 | Linux 3.x Kernel (32 bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Linux 3.x Kernel (32 bit)                     |     2 |
| 308 |           7 | NULL | fd352fb9-3dd9-4f97-8d46-1c879670dcce | Amazon Linux 2 (64 bit)                       | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Amazon Linux 2 (64 bit)                       |     2 |
| 310 |           7 | NULL | 88a61592-ed97-46b6-9d29-e0fd543acb1a | Asianux Server 4 (64 bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Asianux Server 4 (64 bit)                     |     2 |
| 311 |           7 | NULL | c1a96eda-b0ba-4e43-86de-95b47194b814 | Asianux Server 5 (32 bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Asianux Server 5 (32 bit)                     |     2 |
| 313 |           7 | NULL | 68ca7cd1-350b-4e57-a97b-93538a0b343a | Asianux Server 7 (32 bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Asianux Server 7 (32 bit)                     |     2 |
| 314 |           7 | NULL | 7f67f35b-9b46-4997-8642-2241e74c110d | Asianux Server 7 (64 bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Asianux Server 7 (64 bit)                     |     2 |
| 316 |           7 | NULL | ee6cd74c-814a-447e-b73c-5ee39736f3f4 | eComStation 2.0                               | 2023-08-18 07:59:44 | NULL    |               0 |       1 | eComStation 2.0                               |     2 |
| 318 |           7 | NULL | b4bbae23-be50-45e2-ba80-07c7d6a60a58 | macOS 10.14 (64 bit)                          | 2023-08-18 07:59:44 | NULL    |               0 |       1 | macOS 10.14 (64 bit)                          |     2 |
| 322 |           7 | NULL | b6458b04-7304-4f5a-841c-40c2d273cc41 | Mandriva Linux (64 bit)                       | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Mandriva Linux (64 bit)                       |     2 |
| 325 |           7 | NULL | 9044236c-4ac8-4217-b856-5b88b7789870 | SCO OpenServer 6                              | 2023-08-18 07:59:44 | NULL    |               0 |       1 | SCO OpenServer 6                              |     2 |
| 326 |           7 | NULL | 71c7a8f9-6880-49b0-a293-e864a3e5084d | OpenSUSE Linux (64 bit)                       | 2023-08-18 07:59:44 | NULL    |               0 |       1 | OpenSUSE Linux (64 bit)                       |     2 |
| 327 |           7 | NULL | 72f19dc8-0c18-49a4-911c-742fcfa17b2b | OpenSUSE Linux (32 bit)                       | 2023-08-18 07:59:44 | NULL    |               0 |       1 | OpenSUSE Linux (32 bit)                       |     2 |
| 331 |           5 | NULL | fe0d744a-421c-4ce7-a3c1-cef3400ba0a8 | SUSE Linux Enterprise Desktop 12 SP4 (64-bit) | 2023-08-18 07:59:44 | NULL    |               0 |       1 | SUSE Linux Enterprise Desktop 12 SP4 (64-bit) |     2 |
| 332 |           5 | NULL | 25f8ac9c-3c58-44a8-a4fc-3182544594e5 | SUSE Linux Enterprise Server 12 SP4 (64-bit)  | 2023-08-18 07:59:44 | NULL    |               0 |       1 | SUSE Linux Enterprise Server 12 SP4 (64-bit)  |     2 |
| 334 |           9 | NULL | 366dc6ea-db79-4b5f-a9a0-1086aa359ac0 | NeoKylin Linux Server 7                       | 2023-08-18 07:59:44 | NULL    |               0 |       1 | NeoKylin Linux Server 7                       |     2 |
| 336 |           7 | NULL | b513396d-37df-4374-a775-e78918f8789e | macOS 10.15 (64 bit)                          | 2023-08-18 07:59:44 | NULL    |               0 |       1 | macOS 10.15 (64 bit)                          |     2 |
| 337 |           2 | NULL | 36bc3d0e-5e83-4774-9089-bbf5d4d60056 | Debian GNU/Linux 11 (64-bit)                  | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Debian GNU/Linux 11 (64-bit)                  |     2 |
| 340 |           7 | NULL | af0c0f2f-fc62-4f42-aa86-9a9cdac14756 | Asianux Server 9 (64 bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Asianux Server 9 (64 bit)                     |     2 |
| 341 |           1 | NULL | 88de984a-677e-48a3-9bdb-42f541cc7c0d | CentOS 9                                      | 2023-08-18 07:59:44 | NULL    |               0 |       1 | CentOS 9                                      |     2 |
| 343 |           9 | NULL | 200d1ad2-9e5f-4ee2-a3ee-88b790377700 | FreeBSD 13 (64-bit)                           | 2023-08-18 07:59:44 | NULL    |               0 |       1 | FreeBSD 13 (64-bit)                           |     2 |
| 347 |           2 | NULL | edf33a5a-b36c-4863-a3d9-68770c4e5ac0 | Linux 5.x Kernel (32-bit)                     | 2023-08-18 07:59:44 | NULL    |               0 |       1 | Linux 5.x Kernel (32-bit)                     |     2 |
| 349 |           5 | NULL | 3f128ad6-1aec-4f82-9e11-f8ad23ce7c11 | SUSE Linux Enterprise Server 16 (64-bit)      | 2023-08-18 07:59:44 | NULL    |               0 |       1 | SUSE Linux Enterprise Server 16 (64-bit)      |     2 |
| 356 |           1 | NULL | 05a19dc1-3ff8-11ee-af47-1e001e00011f | Oracle Linux 9                                | 2023-08-21 07:54:57 | NULL    |               0 |       1 | Oracle Linux 9                                |     3 |
| 359 |           5 | NULL | 75a4607f-7491-4a3a-8b6c-e21794e5927b | SUSE Linux Enterprise Desktop 12 SP3 (64-bit) | 2023-08-21 07:54:58 | NULL    |               0 |       1 | SUSE Linux Enterprise Desktop 12 SP3 (64-bit) |     2 |
| 362 |           9 | NULL | fe13d4de-d9dd-4b2c-8be4-937a94a5da64 | Scientific Linux 7                            | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Scientific Linux 7                            |     2 |
| 364 |          10 | NULL | 6c757299-eb8c-42b5-b51b-cd74f8d1cfc2 | Ubuntu 20.04 LTS                              | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Ubuntu 20.04 LTS                              |     2 |
| 367 |           2 | NULL | 42429e68-bad2-44dc-9b78-207161bcb538 | Debian GNU/Linux 11 (32-bit)                  | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Debian GNU/Linux 11 (32-bit)                  |     2 |
| 368 |           7 | NULL | 03947e9b-f56d-48b8-a0e8-634cc267d391 | Amazon Linux 3 (64 bit)                       | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Amazon Linux 3 (64 bit)                       |     2 |
| 371 |           7 | NULL | 9d30f036-d023-471b-886a-e3b01fc261a3 | macOS 11 (64 bit)                             | 2023-08-21 07:54:59 | NULL    |               0 |       1 | macOS 11 (64 bit)                             |     2 |
| 373 |           9 | NULL | dd4c2b9e-894a-4932-9ffc-b1ec749e3e41 | FreeBSD 13 (32-bit)                           | 2023-08-21 07:54:59 | NULL    |               0 |       1 | FreeBSD 13 (32-bit)                           |     2 |
| 375 |           2 | NULL | 09653b9e-f6fa-4658-8330-cc870f61b245 | Linux 5.x Kernel (64-bit)                     | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Linux 5.x Kernel (64-bit)                     |     2 |
| 377 |           4 | NULL | c5c314e4-5da2-4b72-927f-21fb35c8276a | Red Hat Enterprise Linux 9.0                  | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Red Hat Enterprise Linux 9.0                  |     2 |
| 380 |           2 | NULL | 9c7b9808-e673-4303-a5a0-473aac98739b | Linux 3.x Kernel (64 bit)                     | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Linux 3.x Kernel (64 bit)                     |     2 |
| 383 |           7 | NULL | 6ce50259-0ac3-412d-a8ec-ecc869c40f9e | Asianux Server 4 (32 bit)                     | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Asianux Server 4 (32 bit)                     |     2 |
| 386 |           7 | NULL | fee0669e-b2b6-4f89-acda-727405809c95 | Asianux Server 5 (64 bit)                     | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Asianux Server 5 (64 bit)                     |     2 |
| 389 |           7 | NULL | c38bb854-bc4e-489f-909f-4816d7a6da95 | Asianux Server 8 (64 bit)                     | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Asianux Server 8 (64 bit)                     |     2 |
| 391 |           7 | NULL | 22bf5465-5341-4dde-91d0-f65204e02af4 | macOS 10.13 (64 bit)                          | 2023-08-21 07:54:59 | NULL    |               0 |       1 | macOS 10.13 (64 bit)                          |     2 |
| 393 |           7 | NULL | 347a1787-35e8-483c-af45-ae72ab7c8a6b | Fedora Linux (64 bit)                         | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Fedora Linux (64 bit)                         |     2 |
| 395 |           7 | NULL | 7a08d54d-1bf2-43a8-aa2d-24da3b2ae8bf | Mandrake Linux                                | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Mandrake Linux                                |     2 |
| 402 |           7 | NULL | 8c05e3e9-1226-487f-9c0c-5bcfbaaa1dce | Solaris 11 (64 bit)                           | 2023-08-21 07:54:59 | NULL    |               0 |       1 | Solaris 11 (64 bit)                           |     2 |
| 403 |           7 | NULL | 445ed80a-2eb3-46ad-9fb2-474aa45495d5 | VMware Photon (64 bit)                        | 2023-08-21 07:54:59 | NULL    |               0 |       1 | VMware Photon (64 bit)                        |     2 |
+-----+-------------+------+--------------------------------------+-----------------------------------------------+---------------------+---------+-----------------+---------+-----------------------------------------------+-------+
43 rows in set (0.00 sec)

MariaDB [cloud]> select * from guest_os where display_name like "Red Hat Enterprise Linux 9%";
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+---------+
| id  | category_id | name | uuid                                 | display_name                 | created             | removed | is_user_defined | display |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+---------+
| 348 |           4 | NULL | 9458424f-0b9a-4abe-8119-b91b7c705fb1 | Red Hat Enterprise Linux 9.0 | 2023-08-18 07:59:44 | NULL    |               0 |       0 |
| 357 |           1 | NULL | 05a1e5a6-3ff8-11ee-af47-1e001e00011f | Red Hat Enterprise Linux 9   | 2023-08-21 07:54:57 | NULL    |               0 |       0 |
| 377 |           4 | NULL | c5c314e4-5da2-4b72-927f-21fb35c8276a | Red Hat Enterprise Linux 9.0 | 2023-08-21 07:54:59 | NULL    |               0 |       1 |
+-----+-------------+------+--------------------------------------+------------------------------+---------------------+---------+-----------------+---------+
3 rows in set (0.00 sec)

MariaDB [cloud]> select * from guest_os_hypervisor where guest_os_id in (select id from guest_os where display_name like "Red Hat Enterprise Linux 9");
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| id   | hypervisor_type | guest_os_name              | guest_os_id | hypervisor_version | uuid                                 | created             | removed | is_user_defined |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| 8590 | KVM             | Red Hat Enterprise Linux 9 |         357 | default            | 05a1ee87-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 8594 | VMware          | rhel9_64Guest              |         357 | 7.0                | 05a2529a-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 8598 | VMware          | rhel9_64Guest              |         357 | 7.0.1.0            | 05a2f226-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 8602 | VMware          | rhel9_64Guest              |         357 | 7.0.2.0            | 05a372e3-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 8606 | VMware          | rhel9_64Guest              |         357 | 7.0.3.0            | 05a4299c-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 8834 | VMware          | rhel9_64Guest              |         357 | 8.0                | 05a53053-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 9089 | VMware          | rhel9_64Guest              |         357 | 8.0.0.1            | 05a64903-3ff8-11ee-af47-1e001e00011f | 2023-08-21 07:54:57 | NULL    |               0 |
| 9638 | VMware          | rhel9_64Guest              |         357 | 8.0.1              | 6db6c79e-43e5-4d82-b412-2b9ecd3fea2d | 2023-08-21 08:04:58 | NULL    |               0 |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
8 rows in set (0.00 sec)

MariaDB [cloud]> select * from guest_os_hypervisor where guest_os_id in (select id from guest_os where display_name like "Red Hat Enterprise Linux 9.0");
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| id   | hypervisor_type | guest_os_name              | guest_os_id | hypervisor_version | uuid                                 | created             | removed | is_user_defined |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| 9776 | KVM             | Red Hat Enterprise Linux 9 |         348 | default            | b62fd70c-019c-445c-865b-40c17895501b | 2023-08-21 08:04:59 | NULL    |               0 |
| 9777 | VMware          | rhel9_64Guest              |         348 | 7.0                | 636e53e6-66a3-4568-ac95-1ae2ce364841 | 2023-08-21 08:04:59 | NULL    |               0 |
| 9778 | VMware          | rhel9_64Guest              |         348 | 7.0.1.0            | 9cf341ca-063e-40c3-ad47-92f044642c78 | 2023-08-21 08:04:59 | NULL    |               0 |
| 9779 | VMware          | rhel9_64Guest              |         348 | 7.0.2.0            | 636ee96e-bda4-4dfe-9317-a308cf4b2131 | 2023-08-21 08:04:59 | NULL    |               0 |
| 9780 | VMware          | rhel9_64Guest              |         348 | 7.0.3.0            | 48a54aa1-3662-4709-94da-350642c27d01 | 2023-08-21 08:04:59 | NULL    |               0 |
| 9781 | VMware          | rhel9_64Guest              |         348 | 8.0                | 731ad32f-df0c-43ba-8b7e-1b5d909219f8 | 2023-08-21 08:04:59 | NULL    |               0 |
| 9782 | VMware          | rhel9_64Guest              |         348 | 8.0.0.1            | ab30dfdd-908c-456b-bebc-0ab3a4364148 | 2023-08-21 08:04:59 | NULL    |               0 |
| 9783 | VMware          | rhel9_64Guest              |         348 | 8.0.1              | b4ddf210-11a9-49d1-afa1-4c2f3cb3987a | 2023-08-21 08:04:59 | NULL    |               0 |
| 9144 | VMware          | rhel9_64Guest              |         377 | 7.0.1.0            | a4b5f7f0-8a29-4cb7-9f98-457282d8d5da | 2023-08-21 07:54:59 | NULL    |               0 |
+------+-----------------+----------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
9 rows in set (0.00 sec)

MariaDB [cloud]> 
MariaDB [cloud]> select * from guest_os_hypervisor where guest_os_id in (select id from guest_os where display_name like "Ubuntu 20.04 LTS" and display=1);
+------+-----------------+--------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| id   | hypervisor_type | guest_os_name            | guest_os_id | hypervisor_version | uuid                                 | created             | removed | is_user_defined |
+------+-----------------+--------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
| 9129 | Xenserver       | Ubuntu Focal Fossa 20.04 |         364 | 8.2.0              | a5e42d13-290e-47d3-8325-4cb8cf08d335 | 2023-08-21 07:54:59 | NULL    |               0 |
| 9381 | VMware          | ubuntu64Guest            |         364 | 6.5                | 79944b11-0a6f-4f94-91d1-6fd5a476fd8a | 2023-08-21 08:04:57 | NULL    |               0 |
| 9382 | VMware          | ubuntu64Guest            |         364 | 6.7                | 8a08b735-850d-4a03-b328-1cdbedca5579 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9383 | VMware          | ubuntu64Guest            |         364 | 6.7.1              | 021af9c9-3315-4ded-a480-3f868b7a30b3 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9384 | VMware          | ubuntu64Guest            |         364 | 6.7.2              | 389b791b-9203-4ae7-838a-664ebe96686f | 2023-08-21 08:04:57 | NULL    |               0 |
| 9385 | VMware          | ubuntu64Guest            |         364 | 6.7.3              | cb5cf938-4db6-4ec6-9ca4-90ba551fce43 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9386 | VMware          | ubuntu64Guest            |         364 | 7.0                | 858d1865-012b-4c69-afad-dbce831a6b38 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9387 | VMware          | ubuntu64Guest            |         364 | 7.0.1.0            | 008f4bb7-eb8c-460e-a36d-f647b6ed7eb9 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9388 | VMware          | ubuntu64Guest            |         364 | 7.0.2.0            | 8865f272-19aa-4f15-b493-26a501e1d497 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9389 | VMware          | ubuntu64Guest            |         364 | 7.0.3.0            | 42b1b50a-1d28-4a10-b59d-34ac2decd4f4 | 2023-08-21 08:04:57 | NULL    |               0 |
| 9390 | VMware          | ubuntu64Guest            |         364 | 8.0                | d6d3f917-793f-464d-8540-04737a2940fe | 2023-08-21 08:04:57 | NULL    |               0 |
| 9641 | VMware          | ubuntu64Guest            |         364 | 8.0.1              | 26f3a929-00c0-42b7-8c7d-f8bd14ef14f7 | 2023-08-21 08:04:58 | NULL    |               0 |
| 9742 | KVM             | Ubuntu 20.04 LTS         |         364 | default            | aa0aaf44-c676-4701-8d28-36c6ea187d3e | 2023-08-21 08:04:59 | NULL    |               0 |
+------+-----------------+--------------------------+-------------+--------------------+--------------------------------------+---------------------+---------+-----------------+
13 rows in set (0.00 sec)


```
```

**Review by DaanHoogland — APPROVED** [review]
tested and reviewed, @BryanMLima can you approve it this way?

**Comment by weizhouapache** [comment]
@rohityadavcloud @harikrishna-patnala 
can you review it ?

**Review by rohityadavcloud — APPROVED** [review]
LGTM didn't test it

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test matrix

**Comment by DaanHoogland** [comment]
@BryanMLima @weizhouapache are we ready with this?

**Comment by weizhouapache** [comment]
retested all steps above, got same results
looks good to me. 

thanks @DaanHoogland  for the fix, merging
