### PR TITLE
KVM: fix delete vm snapshot if it does not exist with a Stopped vm

### LINKED ISSUE #11673: Unable to delete Instance snapshot in "Error' state on stopped Instances
### problem

When instance snapshots fail to create on KVM due to various reasons like ' Guest agent is not responding' or 'internal snapshots of a VM with pflash based firmware require QCOW2 nvram format' the instance snapshot is created in CloudStack in 'Error' state. This can be deleted while the instance is 'Running' but when the instance is in 'Stopped' state, the instance snapshot deletion fails since the snapshot was never created in KVM. 

On Management server: 
```
2025-09-18 08:04:33,742 DEBUG [c.c.v.s.VMSnapshotManagerImpl] (Work-Job-Executor-14:[ctx-d7ea3fce, job-59/job-60, ctx-c90903e0]) (logid:f78a6e3a) Failed to create vm snapshot: [VMSnapshot {"id":2,"name":"i-2-6-VM_VS_20250918080427","uuid":"f5cadba9-b1ff-4436-8d34-0fb6768fcd29","vmId":6}] due to: Creating VM snapshot: i-2-6-VM_VS_20250918080427 failed due to  Create VM snapshot failed due to org.libvirt.LibvirtException: Operation not supported: internal snapshots of a VM with pflash based firmware require QCOW2 nvram format com.cloud.utils.exception.CloudRuntimeException: Creating VM snapshot: i-2-6-VM_VS_20250918080427 failed due to  Create VM snapshot failed due to org.libvirt.LibvirtException: Operation not supported: internal snapshots of a VM with pflash based firmware require QCOW2 nvram format
        at org.apache.cloudstack.storage.vmsnapshot.DefaultVMSnapshotStrategy.takeVMSnapshot(DefaultVMSnapshotStrategy.java:179)
```
KVM agent:

```
2025-09-18 08:05:49,263 DEBUG [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:) Executing command [/usr/bin/qemu-img snapshot -d i-2-6-VM_VS_20250918080427 /mnt/a925cc72-8e60-3c29-b18c-0b8444608bd0/2296a6ae-87d5-4da0-89db-34e9f424576c ].
2025-09-18 08:05:49,274 WARN  [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:) Execution of process [76592] for command [/usr/bin/qemu-img snapshot -d i-2-6-VM_VS_20250918080427 /mnt/a925cc72-8e60-3c29-b18c-0b8444608bd0/2296a6ae-87d5-4da0-89db-34e9f424576c ] failed.
2025-09-18 08:05:49,274 DEBUG [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:) Exit value of process [76592] for command [/usr/bin/qemu-img snapshot -d i-2-6-VM_VS_20250918080427 /mnt/a925cc72-8e60-3c29-b18c-0b8444608bd0/2296a6ae-87d5-4da0-89db-34e9f424576c ] is [1].
2025-09-18 08:05:49,274 WARN  [utils.script.Script] (AgentRequest-Handler-1:[]) (logid:) Process [76592] for command [/usr/bin/qemu-img snapshot -d i-2-6-VM_VS_20250918080427 /mnt/a925cc72-8e60-3c29-b18c-0b8444608bd0/2296a6ae-87d5-4da0-89db-34e9f424576c ] encountered the error: [1].
```

Manual deletion attempt : 

```
/usr/bin/qemu-img snapshot -d i-2-6-VM_VS_20250918080427 /mnt/a925cc72-8e60-3c29-b18c-0b8444608bd0/2296a6ae-87d5-4da0-89db-34e9f424576c
qemu-img: Could not delete snapshot 'i-2-6-VM_VS_20250918080427': snapshot not found
```

```
mysql> select * from vm_snapshots where id=2\G
*************************** 1. row ***************************
                 id: 2
               uuid: f5cadba9-b1ff-4436-8d34-0fb6768fcd29
               name: i-2-6-VM_VS_20250918080427
       display_name: sn2
        description: sn2
              vm_id: 6
         account_id: 2
          domain_id: 1
service_offering_id: 13
   vm_snapshot_type: DiskAndMemory
              state: Error
             parent: NULL
            current: NULL
       update_count: 4
            updated: 2025-09-18 08:05:49
            created: 2025-09-18 08:04:28
            removed: NULL
```

### versions

4.20.1
KVM

### The steps to reproduce the bug

1. Deploy a Windows instance where guest agent is not installed or configure vtpm.
2. Create an instance snapshot with memory, it should fail.
3. Stop the instance
4. Delete the instance snapshot in 'Error' state.

### What to do about it?

Avoid creating an instance snapshot in 'Error' state or allow deletion.

### PR DESCRIPTION
**Pull request by weizhouapache**
### Description

This PR fixes #11673

Steps to reproduce the issue
- deploy vm in kvm environments
- create vm snapshot
- delete the vm snapshot by `qemu-img snapshot -d <snapshot name> <qcow2 image path of vm>
- stop the vm
- delete the vm snapshot on cloudstack GUI

Prior to this PR
```
2025-09-19T12:14:05,455 DEBUG [utils.script.Script] (Script-7:[]) (logid:) Piped commands executed successfully
2025-09-19T12:14:05,455 DEBUG [utils.script.Script] (AgentRequest-Handler-2:[]) (logid:) Executing command [/usr/bin/qemu-img snapshot -d i-2-23-VM_VS_20250919102815 /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57 ].
2025-09-19T12:14:05,594 WARN  [utils.script.Script] (AgentRequest-Handler-2:[]) (logid:) Execution of process [983177] for command [/usr/bin/qemu-img snapshot -d i-2-23-VM_VS_20250919102815 /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57 ] failed.
2025-09-19T12:14:05,594 DEBUG [utils.script.Script] (AgentRequest-Handler-2:[]) (logid:) Exit value of process [983177] for command [/usr/bin/qemu-img snapshot -d i-2-23-VM_VS_20250919102815 /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57 ] is [1].
2025-09-19T12:14:05,594 WARN  [utils.script.Script] (AgentRequest-Handler-2:[]) (logid:) Process [983177] for command [/usr/bin/qemu-img snapshot -d i-2-23-VM_VS_20250919102815 /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57 ] encountered the error: [1].
2025-09-19T12:14:05,595 DEBUG [cloud.agent.Agent] (AgentRequest-Handler-2:[]) (logid:) Seq 1-8671962557478622109:  { Ans: , MgmtId: 32986372244225, via: 1, Ver: v1, Flags: 10, [{"com.cloud.agent.api.DeleteVMSnapshotAnswer":{"result":"false","details":"Delete VM Snapshot Failed due to can not remove snapshot from image file /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57 : 1","wait":"0","bypassHostMaintenance":"false"}}] }

```

With this PR
```
2025-09-19T12:59:29,526 DEBUG [utils.script.Script] (Script-9:[]) (logid:) Piped commands executed successfully
2025-09-19T12:59:29,527 DEBUG [resource.wrapper.LibvirtDeleteVMSnapshotCommandWrapper] (AgentRequest-Handler-5:[]) (logid:) qemu_img_snapshot =
2025-09-19T12:59:29,528 INFO  [resource.wrapper.LibvirtDeleteVMSnapshotCommandWrapper] (AgentRequest-Handler-5:[]) (logid:) Cannot find snapshot i-2-23-VM_VS_20250919102815 in file /mnt/92a06402-16ab-35e8-950e-d84499c5e942/57c64582-aa4b-4329-bf18-9bcb14dffd57, return true
```

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] Build/CI
- [ ] Test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by weizhouapache** [comment]
@blueorangutan package

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java [hunk 1]
```diff
@@ -24,6 +24,7 @@
 
 import org.apache.cloudstack.storage.to.PrimaryDataStoreTO;
 import org.apache.cloudstack.storage.to.VolumeObjectTO;
+import org.apache.commons.lang3.StringUtils;
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]:
```suggestion
import com.cloud.utils.StringUtils;
```

maybe also in another location.

Comment (weizhouapache) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: `com.cloud.utils.StringUtils` does not have method `isNotEmpty`

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java (hunk 1 above)
Comment (DaanHoogland) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: `public class StringUtils extends org.apache.commons.lang3.StringUtils`

Comment (weizhouapache) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: ok, thanks @DaanHoogland 
I think these two have no difference, right ?

```
<08:32:31> weizhou:/git/cs (4.20)# git grep utils.StringUtils  |wc -l
113
<08:32:35> weizhou:/git/cs (4.20)# git grep lang3.StringUtils |wc -l
443
```

Comment (DaanHoogland) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: utils.StringUtils  is internal to the project and has some extra utils in comparison to the apache.commons one.

Comment (weizhouapache) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: I suggest we use the native method (org.apache.commons.lang3.StringUtils.isNotEmpty)

Comment (DaanHoogland) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: yes, but please use it through the proxy class

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java (hunk 1 above)
Comment (weizhouapache) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtDeleteVMSnapshotCommandWrapper.java]: done

**Review by abh1sar — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
merging based on approvals and manual test by @rajujith 

thanks all
