### PR TITLE
server: use id column as secondary sort criteria with sortKey 

### LINKED ISSUE #5316: paged listServiceOffering response returns duplicated records in different pages
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
Main and older
~~~

##### SUMMARY

Create a large number of offerings, in my case about 250. list the offerings and divide the response into 3 pages of 100 
While comparing the records from page1 and 2 I was able to find an id on the both pages. Checkout the attached file. 

##### STEPS TO REPRODUCE

~~~
See attachment for details
~~~

##### EXPECTED RESULTS

~~~
Pages should contain unique ids
~~~

##### ACTUAL RESULTS

~~~
pages contained a duplicated id
~~~
[compare paged api response.txt](https://github.com/apache/cloudstack/files/6990673/compare.paged.api.response.txt)

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

For tables that use `sort_key` field, incorrect results can be returned by the list* APIs while using pagination and with the same values for `sort-key` field. (Default value for `sort_key` field remains `0`).
This change adds `id` column as secondary sort criteria in such cases.

Fixes #5316

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

- Created 1000 disk offerings
- Listed 500 disk offerings ids using cmk at a time for 2 pages
- Verified if there are any duplicates
- No duplicates found

[diskoffering-fix.log](https://github.com/apache/cloudstack/files/6992796/diskoffering-fix.log)

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by nvazquez** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan test

**Review by borisstoyanov — APPROVED** [review]
LGTM, 

I've manually checked with ~1600 records and page size of 450, divided in 4 pages I could not get duplicates.
```
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page1 page4 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page2 page4 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page3 page4 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page1 page3 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page1 page2 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page3 page2 | wc
      0       0       0
```

Lets wait for results from smoketests to appear.

File: framework/db/src/main/java/com/cloud/utils/db/Filter.java [hunk 1]
```diff
@@ -77,7 +77,9 @@ public void addOrderBy(Class<?> clazz, String field, boolean ascending) {
 
         Column column = f.getAnnotation(Column.class);
         String name = column != null ? column.name() : field;
-
+        if (!name.equals("id")) {
+            name = String.format("%s, id", name);
```
Comment (rhtyd) [inline framework/db/src/main/java/com/cloud/utils/db/Filter.java:81]: LGTM but I worry as this is used at so many places, @shwstppr - is there a more isolated way to fix the list API issue than this, i.e. what is causing the issue for the listServiceOfferings API response?

Comment (shwstppr) [reply framework/db/src/main/java/com/cloud/utils/db/Filter.java:81]: @rhtyd as mentioned in the PR desc, it is sorting issue when entries in table have same value for the column (for which order by is called). In case of list* APIs where resources have `sort_key` in their corresponding tables.
Since by default value for `sort_key` is `0`, weirdly sorted results are returned when `LIMIT` offset is used. Change will add `id` as secondary sort criteria.

Only issue I see is the case when table doesn't have id column. Don't think that is the case with tables in ACS.

Comment (rhtyd) [reply framework/db/src/main/java/com/cloud/utils/db/Filter.java:81]: What if the table has no `id` column @shwstppr the change is in `Filter` class and could have widespread side-effects. Can we check the service layer handler specific to listServiceOfferings and do something isolated/specific to that?

**Comment by shwstppr** [comment]
Another test run started this morning is still running. Let's see how that goes

File: framework/db/src/main/java/com/cloud/utils/db/Filter.java (hunk 1 above)
Comment (shwstppr) [reply framework/db/src/main/java/com/cloud/utils/db/Filter.java]: @rhtyd changed the logic. No changes in Filter class now

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Review by nvazquez — APPROVED** [review]
LGTM

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by nvazquez** [comment]
@borisstoyanov can you please repeat your tests after the refactor?

**Review by borisstoyanov — APPROVED** [review]
LGTM, rerun the tests with latest changes and it all seems fine
```
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page1 page2 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page1 page3 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page1 page4 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page2 page4 | wc
      0       0       0
[root@pr5320-t1674-kvm-centos7-mgmt1 ~]# grep -x -i -f page3 page4 | wc
      0       0       0
```

**Review by rhtyd — APPROVED** [review]
