### PR TITLE
Fix foreign key constraints and the mysql procedure that is used

### LINKED ISSUE #7370: Missing contraint foreign key in "vm_template" table
#### ISSUE TYPE

 * Bug Report
 
The table "user_vm" and "vm_template" are expected to have the contraint foreign key, which link to "user_data.id".
However, the key exist in "user_vm" table, but missing in "vm_template" table.

##### Reason

The SQL procedure `IDEMPOTENT_ADD_FOREIGN_KEY` is used in the following SQL statements

```
CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.volumes', 'passphrase', 'id');
CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.user_vm', 'user_data', 'id');
CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('cloud.vm_template', 'user_data', 'id');
```

The results are

| table name  | constraint foreign key | note |
| ------------- | ------------- | ------------- |
| volumes  | fk_passphrase_id  | OK |
| user_vm  | fk_user_data_id  | OK |
| vm_template | fk_user_data_id | Missing on mysql 5.5/mysql 8, <br> Error on mysql 5.6/5.7 (#7358) |

The keys are same in "user_vm" and "vm_template" table, which causes MySQL error `Can't write; duplicate key in table '#sql-3755_b'`

The error is ignored in mysql 5.5 and 8.0, but throws an exception in mysql 5.6/5.7 as the error codes are different 
(1005 on mysql 5.5, 1826 on mysql 8.x, 1022 on mysql 5.6/5.7)

##### Suggestion

The key name should be renamed to `f_<table name>_<foreign table name>_<foreign column name>`, for example `f_user_vm_user_data_id`, instead of `f_user_data_id` 

(refer to the old key names in #7255)

If so, need to 
- create a new procedure ot remove the foreign keys if exists
- update the procedure to create new keys with new names

##### Related PRs:

- #6522 
- #7252
- #7255 

##### user_vm table
```

MariaDB [cloud]> show create table user_vm\G
*************************** 1. row ***************************
       Table: user_vm
Create Table: CREATE TABLE `user_vm` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `iso_id` bigint(20) unsigned DEFAULT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `user_data` mediumtext,
  `user_data_id` bigint(20) unsigned DEFAULT NULL COMMENT 'id of the user data',
  `user_data_details` mediumtext COMMENT 'value of the comma-separated list of parameters',
  `update_parameters` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Defines if the parameters have been updated for the vm',
  `user_vm_type` varchar(255) DEFAULT 'UserVM' COMMENT 'Defines the type of UserVM',
  PRIMARY KEY (`id`),
  KEY `fk_user_data_id` (`user_data_id`),
  CONSTRAINT `fk_user_data_id` FOREIGN KEY (`user_data_id`) REFERENCES `user_data` (`id`),
  CONSTRAINT `fk_user_vm__id` FOREIGN KEY (`id`) REFERENCES `vm_instance` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

```

######  vm_template table
```
MariaDB [cloud]> show create table vm_template\G
*************************** 1. row ***************************
       Table: vm_template
Create Table: CREATE TABLE `vm_template` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `unique_name` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `uuid` varchar(40) DEFAULT NULL,
  `public` int(1) unsigned NOT NULL,
  `featured` int(1) unsigned NOT NULL,
  `type` varchar(32) DEFAULT NULL,
  `hvm` int(1) unsigned NOT NULL COMMENT 'requires HVM',
  `bits` int(6) unsigned NOT NULL COMMENT '32 bit or 64 bit',
  `url` varchar(255) DEFAULT NULL COMMENT 'the url where the template exists externally',
  `format` varchar(32) NOT NULL COMMENT 'format for the template',
  `created` datetime NOT NULL COMMENT 'Date created',
  `removed` datetime DEFAULT NULL COMMENT 'Date removed if not null',
  `account_id` bigint(20) unsigned NOT NULL COMMENT 'id of the account that created this template',
  `checksum` varchar(255) DEFAULT NULL COMMENT 'checksum for the template root disk',
  `display_text` varchar(4096) DEFAULT NULL COMMENT 'Description text set by the admin for display purpose only',
  `enable_password` int(1) unsigned NOT NULL DEFAULT '1' COMMENT 'true if this template supports password reset',
  `enable_sshkey` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'true if this template supports sshkey reset',
  `guest_os_id` bigint(20) unsigned NOT NULL COMMENT 'the OS of the template',
  `bootable` int(1) unsigned NOT NULL DEFAULT '1' COMMENT 'true if this template represents a bootable ISO',
  `prepopulate` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'prepopulate this template to primary storage',
  `cross_zones` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Make this template available in all zones',
  `extractable` int(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Is this template extractable',
  `hypervisor_type` varchar(32) DEFAULT NULL COMMENT 'hypervisor that the template belongs to',
  `source_template_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Id of the original template, if this template is created from snapshot',
  `template_tag` varchar(255) DEFAULT NULL COMMENT 'template tag',
  `sort_key` int(32) NOT NULL DEFAULT '0' COMMENT 'sort key used for customising sort method',
  `size` bigint(20) unsigned DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `update_count` bigint(20) unsigned DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `dynamically_scalable` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'true if template contains XS/VMWare tools inorder to support dynamic scaling of VM cpu/memory',
  `parent_template_id` bigint(20) unsigned DEFAULT NULL COMMENT 'If datadisk template, then id of the root template this template belongs to',
  `direct_download` tinyint(1) DEFAULT '0' COMMENT 'Indicates if Secondary Storage is bypassed and template is downloaded to Primary Storage',
  `deploy_as_is` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'True if the template should be deployed with disks and networks as defined by OVF',
  `user_data_id` bigint(20) unsigned DEFAULT NULL COMMENT 'id of the user data',
  `user_data_link_policy` varchar(255) DEFAULT NULL COMMENT 'user data link policy with template',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uc_vm_template__uuid` (`uuid`),
  KEY `i_vm_template__removed` (`removed`),
  KEY `i_vm_template__public` (`public`)
) ENGINE=InnoDB AUTO_INCREMENT=202 DEFAULT CHARSET=utf8
1 row in set (0.00 sec)
```

##### COMPONENT NAME

~~~
DB
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by harikrishna-patnala**
### Description

This PR fixes #7370 where same foreign key names are used for multiple tables which causes issues with different MySQL versions.

I've updated the procedure to be more precise and altered the problematic foreign keys in upgrade files. This way we can log the errors and resume the upgrade. 

Also removed the mysql statements related to foreign key procedure creation and usage from 4.18.0 schema files (those are moved to 4.18.1 java upgrade files) to avoid errors caused in #7370 for certain MySQL versions.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [x] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

File: engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql [hunk 1]
```diff
@@ -19,3 +19,12 @@
 -- Schema upgrade from 4.18.1.0 to 4.19.0.0
 --;
 
+DROP PROCEDURE IF EXISTS `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`;
```
Comment (weizhouapache) [inline engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql:22]: @harikrishna-patnala 
we need to fix this in 4.18.1.0, right ?

Comment (harikrishna-patnala) [reply engine/schema/src/main/resources/META-INF/db/schema-41810to41900.sql]: yeah makes sense, updated it @weizhouapache

File: engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql [hunk 2]
```diff
@@ -19,3 +19,12 @@
...
 
+DROP PROCEDURE IF EXISTS `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`;
+CREATE PROCEDURE `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY` (
+    IN in_table_name VARCHAR(200),
+    IN in_table_column VARCHAR(200),
+    IN in_foreign_table_name VARCHAR(200),
+    IN in_foreign_column_name VARCHAR(200)
+)
+BEGIN
+    DECLARE CONTINUE HANDLER FOR 1005,1826 BEGIN END; SET @ddl = CONCAT('ALTER TABLE cloud.', in_table_name); SET @ddl = CONCAT(@ddl, ' ', ' ADD CONSTRAINT '); SET @ddl = CONCAT(@ddl, 'fk_', in_table_name, '__', in_foreign_table_name, '_', in_foreign_column_name); SET @ddl = CONCAT(@ddl, ' FOREIGN KEY (', in_table_column, ')'); SET @ddl = CONCAT(@ddl, ' REFERENCES ', in_foreign_table_name, '(', in_foreign_column_name, ')'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt; END;
```
Comment (DaanHoogland) [inline engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql:30]: why do we need to recreate it? can´t we just use it as is?

**Comment by harikrishna-patnala** [comment]
> @harikrishna-patnala we also need to remove the codes in 41720to41800.sql otherwise, the users who use mysql 5.6/5.7 will still fail to upgrade to 4.18.1.0 due to same error in #7358

Yes, I'll remove it 41720to41800.sql file

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
@harikrishna-patnala 
I think we do not necessarily need a mysql procedure. 

Refer to the following code block
```
    public void dropKey(Connection conn, String tableName, String key, boolean isForeignKey)
    {
        String alter_sql_str;
        if (isForeignKey) {
            alter_sql_str = "ALTER TABLE " + tableName + " DROP FOREIGN KEY " + key;
        } else {
            alter_sql_str = "ALTER TABLE " + tableName + " DROP KEY " + key;
        }
        try(PreparedStatement pstmt = conn.prepareStatement(alter_sql_str);)
        {
            pstmt.executeUpdate();
            s_logger.debug("Key " + key + " is dropped successfully from the table " + tableName);
        } catch (SQLException e) {
            s_logger.debug("Ignored SQL Exception when trying to drop " + (isForeignKey ? "foreign " : "") + "key " + key + " on table "  + tableName + " exception: " + e.getMessage());

        }
    }
```

**Comment by harikrishna-patnala** [comment]
> @harikrishna-patnala I think we do not necessarily need a mysql procedure.
> 
> Refer to the following code block
> 
> ```
>     public void dropKey(Connection conn, String tableName, String key, boolean isForeignKey)
>     {
>         String alter_sql_str;
>         if (isForeignKey) {
>             alter_sql_str = "ALTER TABLE " + tableName + " DROP FOREIGN KEY " + key;
>         } else {
>             alter_sql_str = "ALTER TABLE " + tableName + " DROP KEY " + key;
>         }
>         try(PreparedStatement pstmt = conn.prepareStatement(alter_sql_str);)
>         {
>             pstmt.executeUpdate();
>             s_logger.debug("Key " + key + " is dropped successfully from the table " + tableName);
>         } catch (SQLException e) {
>             s_logger.debug("Ignored SQL Exception when trying to drop " + (isForeignKey ? "foreign " : "") + "key " + key + " on table "  + tableName + " exception: " + e.getMessage());
> 
>         }
>     }
> ```

I did get you @weizhouapache are you saying we dont need to create procedure in java code?

**Comment by weizhouapache** [comment]
> I did get you @weizhouapache are you saying we dont need to create procedure in java code?

@harikrishna-patnala right, exactly

**Comment by harikrishna-patnala** [comment]
> > I did get you @weizhouapache are you saying we dont need to create procedure in java code?
> 
> @harikrishna-patnala right, exactly

Okay @weizhouapache updated the PR by removing it from java

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

File: engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java [hunk 3]
```diff
@@ -26,6 +26,17 @@ public class DatabaseAccessObject {
 
     private static Logger s_logger = Logger.getLogger(DatabaseAccessObject.class);
 
+    public void addForeignKey(Connection conn, String tableName, String tableColumn, String foreignTableName, String foreignColumnName) {
+        String addForeignKeyStmt = String.format("CALL `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`('%s', '%s', '%s', '%s')", tableName, tableColumn, foreignTableName, foreignColumnName);
```
Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: @harikrishna-patnala 
you can use `ALTER TABLE xxx ADD CONSTRAINT xxx` instead of cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`

Comment (harikrishna-patnala) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: So you are saying we should not use the procedure in future also (I suppose you are saying to avoid errors with multiple mysql versions) ?

Comment (weizhouapache) [inline engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: @DaanHoogland 
my suggestion is (do not commit it)
```suggestion
        String addForeignKeyStmt = String.format("ALTER TABLE xxx ADD CONSTRAINT xxxxx xxxxx");
```
with the changes in schema-41720to41800.sql, the procedure `IDEMPOTENT_ADD_FOREIGN_KEY` is not used at all, so we can remove it to avoid it being used in the future

cc @harikrishna-patnala

**Comment by rohityadavcloud** [comment]
ping @harikrishna-patnala is this ready, could you address any outstanding comments and advise? Thanks.

**Comment by rohityadavcloud** [comment]
ping @harikrishna-patnala @shwstppr any update on this? Thanks.

File: engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java (hunk 3 above)
Comment (shwstppr) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: ping @harikrishna-patnala will you be addressing this ^^ cc @rohityadavcloud

Comment (DaanHoogland) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: I am not sure it is wise to allow changes to the DB to be not IdemPotent if they can be. updating in dot releases that rquire updates will lead to conflicts if we do not keep this policy. I have not understood yet why it would be harmful in this instance. @weizhouapache please explain.

Comment (weizhouapache) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: > I am not sure it is wise to allow changes to the DB to be not IdemPotent if they can be. updating in dot releases that rquire updates will lead to conflicts if we do not keep this policy. I have not understood yet why it would be harmful in this instance. @weizhouapache please explain.

@DaanHoogland 
the try-catch block will handle the exceptions if the column or constrain key has been already added.

I think it is better than MySQL procedure, because the error codes of MySQL procedure are different with MySQL versions, which is the root cause of #7358 

```
    try
        {
            pstmt.executeUpdate();
            s_logger.debug(String.format("Foreign key is added successfully from the table %s", tableName));
        } catch (SQLException e) {
            s_logger.error("Ignored SQL Exception when trying to add foreign key on table "  + tableName + " exception: " + e.getMessage());
        }
    }
}

Comment (harikrishna-patnala) [reply engine/schema/src/main/java/com/cloud/upgrade/dao/DatabaseAccessObject.java:30]: Agree with @weizhouapache it is happening because of the different error codes. 

Sorry for the delay @shwstppr. I'm on this now.

**Comment by andrijapanicsb** [comment]
@harikrishna-patnala can you pls check the conflicts and fix?

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@weizhouapache I've addressed your review comment, can you please review it again

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
> @weizhouapache I've addressed your review comment, can you please review it again

@harikrishna-patnala 
code lgtm
I will test it

**Comment by weizhouapache** [comment]
@blueorangutan test rocky8 kvm-rocky8

**Review by DaanHoogland — APPROVED** [review]
clgtm, some malicious upgrade tests required, ... @vladimirpetrov ;)

**Comment by vladimirpetrov** [comment]
@blueorangutan package

**Review by weizhouapache — APPROVED** [review]
code lgtm

need manual testing

File: engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql [hunk 4]
```diff
@@ -28,3 +28,13 @@ CALL ADD_GUEST_OS_AND_HYPERVISOR_MAPPING (6, 'Windows Server 2022 (64-bit)', 'VM
 CALL ADD_GUEST_OS_AND_HYPERVISOR_MAPPING (6, 'Windows Server 2022 (64-bit)', 'VMware', '8.0', 'windows2019srvNext_64Guest');
 CALL ADD_GUEST_OS_AND_HYPERVISOR_MAPPING (6, 'Windows Server 2022 (64-bit)', 'VMware', '8.0.0.1', 'windows2019srvNext_64Guest');
 CALL ADD_GUEST_OS_AND_HYPERVISOR_MAPPING (6, 'Windows Server 2022 (64-bit)', 'Xenserver', '8.2.0', 'Windows Server 2022 (64-bit)');
+
+DROP PROCEDURE IF EXISTS `cloud`.`IDEMPOTENT_ADD_FOREIGN_KEY`;
```
Comment (weizhouapache) [inline engine/schema/src/main/resources/META-INF/db/schema-41800to41810.sql:32]: this procedure is not used anywhere so it could be removed

**Comment by weizhouapache** [comment]
> > code lgtm
> > need manual testing
> 
> @weizhouapache , with manual testing you mean upgrade tests, right?

@DaanHoogland yes, probably better with mysql 5.6/5.7 which did not work when upgrade to 4.18.0.0

**Comment by DaanHoogland** [comment]
> > > code lgtm
> > > need manual testing
> > 
> > 
> > @weizhouapache , with manual testing you mean upgrade tests, right?
> 
> @DaanHoogland yes, probably better with mysql 5.6/5.7 which did not work when upgrade to 4.18.0.0

cc @vladimirpetrov

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by harikrishna-patnala** [comment]
@blueorangutan package

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Comment by harikrishna-patnala** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing. I tested some upgrades from 4.14, 4.15, 4.16 and 4.17 using KVM and VMware and found no issues.
