### PR TITLE
server: destroy ssvm, cpvm on last host maintenance 

### LINKED ISSUE #3719: VMware: SystemVMs not cleared after forcing them to stop
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Occupy a host with a few VMs and make sure both system vms are there as well

```
MariaDB [cloud]> select name,state,removed from vm_instance where type = 'SecondaryStorageVm' or type ='ConsoleProxy';
+---------+-----------+---------------------+
| name    | state     | removed             |
+---------+-----------+---------------------+
| s-1-VM  | Destroyed | 2019-11-21 09:37:59 |
| v-2-VM  | Destroyed | 2019-11-21 09:48:16 |
| s-28-VM | Destroyed | 2019-11-21 09:38:58 |
| s-29-VM | Destroyed | 2019-11-21 09:45:29 |
| s-30-VM | Destroyed | 2019-11-21 09:46:29 |
| s-31-VM | Destroyed | 2019-11-21 09:47:29 |
| s-32-VM | Destroyed | 2019-11-21 11:50:29 |
| v-33-VM | Destroyed | 2019-11-21 11:44:56 |
| v-39-VM | Destroyed | 2019-11-21 11:45:59 |
| v-40-VM | Destroyed | 2019-11-21 11:50:29 |
| v-41-VM | Running   | NULL                |
| s-42-VM | Destroyed | 2019-11-21 11:51:29 |
| s-43-VM | Destroyed | 2019-11-21 11:52:29 |
| s-44-VM | Destroyed | 2019-11-21 11:53:29 |
| s-45-VM | Destroyed | 2019-11-21 11:54:29 |
| s-46-VM | Destroyed | 2019-11-21 11:55:29 |
| s-47-VM | Destroyed | 2019-11-21 11:56:29 |
| s-48-VM | Running   | NULL                |
+---------+-----------+---------------------+
18 rows in set (0.00 sec)
```

Screenshot 2019-11-21 at 13 41 26

notice how s-29, s-32, 40 are still part of the list but according to cloudstack DB they are removed

##### STEPS TO REPRODUCE

~~~
Make sure the host is the last one in the cluster and set it to maintenance

Observe that all VMs are shut down

Cancel maintenance and observe new system vms will be created

Login to vCenter and see that old system vms are not destroyed
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description
When a single or last UP host enters into maintenance just stopping SSVM and CPVM will leave behind VMs on the hypervisor side. As these system VMs will be recreated they can be destroyed.
Such system VMs will be first stopped with cleanup and then expunged.

Fixes #3719

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
code looks ok, do we need to consider VRs?

**Comment by shwstppr** [comment]
@DaanHoogland yes, probably VR should also be included but right now these changes are not working. Expunging systemvm takes time and between that MS tries to start new systemvm. So still working on fixing...

**Comment by rhtyd** [comment]
Edge case, not critical issue moved to next milestone.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

**Comment by shwstppr** [comment]
@blueorangutan test matrix

**Comment by shwstppr** [comment]
@blueorangutan test centos7 xs71

**Comment by shwstppr** [comment]
@blueorangutan centos7 xcpng74

**Comment by shwstppr** [comment]
@blueorangutan test centos7 xcpng74

**Comment by rhtyd** [comment]
@blueorangutan test

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test centos7 vmware-67u3

File: services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java [hunk 1]
```diff
@@ -811,6 +811,13 @@ public void allocCapacity(long dataCenterId, SecondaryStorageVm.Role role) {
     }
 
     public boolean isZoneReady(Map<Long, ZoneHostInfo> zoneHostInfoMap, long dataCenterId) {
+        List <HostVO> hosts = _hostDao.listByDataCenterId(dataCenterId);
+        if (CollectionUtils.isEmpty(hosts)) {
+            if (s_logger.isDebugEnabled()) {
+                s_logger.debug("Zone " + dataCenterId + " has no host available which is enabled and in Up state");
+            }
+            return false;
+        }
```
Comment (DaanHoogland) [inline services/secondary-storage/controller/src/main/java/org/apache/cloudstack/secondarystorage/SecondaryStorageManagerImpl.java:820]: separate method?

File: server/src/main/java/com/cloud/resource/ResourceManagerImpl.java [hunk 2]
```diff
@@ -1267,8 +1266,14 @@ private boolean doMaintain(final long hostId) {
...
                     // Migration is not supported for VGPU Vms so stop them.
-                    // for the last host in this cluster, stop all the VMs
-                    s_logger.error("Maintenance: No hosts available for migrations. Scheduling shutdown instead of migrations.");
+                    // for the last host in this cluster, destroy SSVM/CPVM and stop all other VMs
+                    if (VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType())
+                            || VirtualMachine.Type.ConsoleProxy.equals(vm.getType())) {
+                        s_logger.error(String.format("Maintenance: VM is of type %s. Destroying VM %s (ID: %s) immediately instead of migration.", vm.getType().toString(), vm.getInstanceName(), vm.getUuid()));
+                        _haMgr.scheduleDestroy(vm, host.getId());
+                        continue;
+                    }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/resource/ResourceManagerImpl.java:1275]: can you factor this out, including the comment, please?

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java [hunk 3]
```diff
@@ -682,29 +687,44 @@ public void cancelDestroy(VMInstanceVO vm, Long hostId) {
...
-                if (s_logger.isDebugEnabled()) {
-                    s_logger.debug(vm + " has already been stopped");
+            s_logger.info("Destroying " + vm.toString());
+            if (!VirtualMachine.State.Expunging.equals(work.getPreviousState())) {
+                s_logger.info("Destroying " + vm.getUuid());
+                if (VirtualMachine.Type.ConsoleProxy.equals(vm.getType())) {
+                    consoleProxyManager.destroyProxy(vm.getId());
+                } else if (VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType())) {
+                    secondaryStorageVmManager.destroySecStorageVm(vm.getId());
+                } else {
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:713]: the total method has grown from 23 to 40 lines, can you factor the new bits out please.

File: server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java [hunk 4]
```diff
@@ -1006,6 +1006,13 @@ private void allocCapacity(long dataCenterId) {
     }
 
     public boolean isZoneReady(Map<Long, ZoneHostInfo> zoneHostInfoMap, long dataCenterId) {
+        List <HostVO> hosts = _hostDao.listByDataCenterId(dataCenterId);
+        if (CollectionUtils.isEmpty(hosts)) {
+            if (s_logger.isDebugEnabled()) {
+                s_logger.debug("Zone " + dataCenterId + " has no host available which is enabled and in Up state");
+            }
+            return false;
+        }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/consoleproxy/ConsoleProxyManagerImpl.java:1015]: this is the exact same code as inSecondaryStorageManagerImpl.isZoneReady() can you factor out and reuse?

File: plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java [hunk 5]
```diff
@@ -214,6 +216,16 @@ public void createAsync(DataStore dataStore, DataObject data, AsyncCompletionCal
...
+        if (DataObjectType.VOLUME.equals(data.getType())) {
+            Volume volume = (Volume)data;
+            if (volume.getInstanceId() != null) {
+                VMInstanceVO vm = vmDao.findById(volume.getInstanceId());
+                if (vm != null && (VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType()) ||
+                        VirtualMachine.Type.ConsoleProxy.equals(vm.getType()))) {
+                    cmd.setBypassHostMaintenance(true);
+                }
+            }
+        }
```
Comment (DaanHoogland) [inline plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:228]: can you factor out and give a meaningful name?

File: engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java [hunk 6]
```diff
@@ -606,10 +610,18 @@ protected void advanceExpunge(VMInstanceVO vm) throws ResourceUnavailableExcepti
...
+                        command.setBypassHostMaintenance(true);
+                    }
                     cmds.addCommand(command);
                 }
                 if (nicExpungeCommands != null) {
                     for (final Command command : nicExpungeCommands) {
+                        if (VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType()) ||
+                                VirtualMachine.Type.ConsoleProxy.equals(vm.getType())) {
+                            command.setBypassHostMaintenance(true);
+                        }
```
Comment (DaanHoogland) [inline engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java:624]: I'm seeing this code fragment a lot, please factor out and reuse.

**Review by Pearl1594 — COMMENTED** [review]
Tested the fix - LGTM.
When the last host is put into maintenance mode(ACS end), the systemVMs are deleted from VMware end as well as seen in :

image

**Comment by shwstppr** [comment]
@blueorangutan package

@DaanHoogland refactored new changes to separate methods where possible. Unable to meaningfully factor out `SecondaryStorageManagerImpl` and `ConsoleProxyManagerImpl`. They need more in-depth refactoring as al lot of common code there, something we can attempt for `main` branch

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java [hunk 7]
```diff
@@ -680,31 +685,51 @@ public void cancelDestroy(VMInstanceVO vm, Long hostId) {
...
+    }
+
     protected Long destroyVM(final HaWorkVO work) {
         final VirtualMachine vm = _itMgr.findById(work.getInstanceId());
-        s_logger.info("Destroying " + vm.toString());
+        if (vm == null) {
+            s_logger.info("No longer can find VM " + work.getInstanceId() + ". Throwing away " + work);
+            return null;
+        }
+        boolean expunge = VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType())
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:711]:
```suggestion
        boolean expungeSystemVM = VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType())
```

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java [hunk 8]
```diff
@@ -795,7 +820,7 @@ private long getRescheduleTime(WorkType workType) {
             case ForceStop:
                 return ((System.currentTimeMillis() >> 10) + _stopRetryInterval);
             case Destroy:
-                return ((System.currentTimeMillis() >> 10) + _restartRetryInterval);
+                return ((System.currentTimeMillis() >> 10) + _stopRetryInterval);
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:823]: @shwstppr any reason to change to stop retry interval? if you want to keep it, move the case stmt after 'ForceStop'.

Alternatively, you can use different config (may be "_destroy.retry.interval_") for destroy operation, and set its value to the current value in "_restart.retry.interval_" on upgrade.

File: plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java [hunk 9]
```diff
@@ -211,10 +213,22 @@ public void createAsync(DataStore dataStore, DataObject data, AsyncCompletionCal
...
+            Volume volume = (Volume)data;
+            if (volume.getInstanceId() != null) {
+                VMInstanceVO vm = vmDao.findById(volume.getInstanceId());
+                return vm != null && (VirtualMachine.Type.SecondaryStorageVm.equals(vm.getType()) ||
+                        VirtualMachine.Type.ConsoleProxy.equals(vm.getType()));
+            }
+        }
+        return false;
+    }
+
```
Comment (sureshanaparti) [inline plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:227]: @shwstppr Is bypass host maintenance applicable for volumes in managed storage as well?

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java (hunk 7 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:711]: @sureshanaparti I think `expunge` name is better here as it is use irrespective of vm type in `destroyVM` method. Through it holds value - `true` only for ssvm and cpvm

File: server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java (hunk 8 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/ha/HighAvailabilityManagerImpl.java:822]: @sureshanaparti clubbed `Destroy` case with other cases.
Used `_stopRetryInterval` because it uses value of config - `stop.retry.interval`. The description for that config is - `The time in seconds between retries to stop or destroy a VM.`

https://github.com/apache/cloudstack/blob/4.15/engine/components-api/src/main/java/com/cloud/ha/HighAvailabilityManager.java#L50-L51

File: plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java (hunk 9 above)
Comment (shwstppr) [reply plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:227]: @sureshanaparti yes, bypasshostmaintenance flag could be true for volumes in managed stores as well if the volume is of cpvm or ssvm

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan package

**Review by vladimirpetrov — APPROVED** [review]
Feature tested, LGTM.

**Comment by rhtyd** [comment]
@blueorangutan test

**Review by Pearl1594 — APPROVED** [review]
LGTM. Verified behavior 
https://github.com/apache/cloudstack/pull/4644#pullrequestreview-651040061

File: plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java (hunk 9 above)
Comment (sureshanaparti) [reply plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:227]: ok @shwstppr how other drivers set this parameter ?

Comment (shwstppr) [reply plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:227]: @sureshanaparti other drivers don't seem to be using `DeleteCommand`.
```
~/lab/shapeblue/cloudstack|fix-uncleared-sys-vms-3719⚡ 
⇒  grep "new DeleteCommand" -R .
./engine/storage/image/src/main/java/org/apache/cloudstack/storage/image/TemplateServiceImpl.java:                            DeleteCommand dtCommand = new DeleteCommand(tmplTO);
./engine/storage/volume/src/main/java/org/apache/cloudstack/storage/volume/VolumeServiceImpl.java:                        DeleteCommand dtCommand = new DeleteCommand(tmplTO);
./engine/storage/src/main/java/org/apache/cloudstack/storage/image/BaseImageStoreDriverImpl.java:            DeleteCommand cmd = new DeleteCommand(data.getTO());
./server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:                    cmd = new DeleteCommand(volumeInfo.getTO());
./plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/driver/CloudStackPrimaryDataStoreDriverImpl.java:        DeleteCommand cmd = new DeleteCommand(data.getTO());
./plugins/storage/volume/sample/src/main/java/org/apache/cloudstack/storage/datastore/driver/SamplePrimaryDataStoreDriverImpl.java:         * DeleteCommand cmd = new DeleteCommand(vo.getUri());
./plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageSubsystemCommandHandler.java:                        DeleteCommand deleteCommand = new DeleteCommand(template);
./plugins/hypervisors/vmware/src/main/java/com/cloud/storage/resource/VmwareStorageSubsystemCommandHandler.java:                    DeleteCommand deleteCommand = new DeleteCommand(newSnapshot);
./plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java:                    DeleteCommand cmd = new DeleteCommand(volumeInfo.getTO());
./plugins/hypervisors/ovm3/src/test/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessorTest.java:        DeleteCommand delete = new DeleteCommand(vol);
./plugins/hypervisors/ovm3/src/test/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessorTest.java:        delete = new DeleteCommand(template);
./plugins/hypervisors/ovm3/src/test/java/com/cloud/hypervisor/ovm3/resources/Ovm3StorageProcessorTest.java:        delete = new DeleteCommand(snap);
./services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/NfsSecondaryStorageResource.java:            DeleteCommand deleteCommand = new DeleteCommand(newTemplate)
```
PS: SamplePrimaryDataStoreDriverImpl code is commented
