### PR TITLE
server: fix orphan db transaction issue

### LINKED ISSUE #11058: Orpahned transactions in logs
### problem

I am seeing the below error in logs. This error shouldn't occur and needs code investigation for fixing this.

```
2025-06-18 00:00:00,608 ERROR [c.c.u.d.T.Transaction] (Finalizer:[]) (logid:) Something went wrong that a transaction is orphaned before db connection is closed
```

### versions

4.20.1.0

### The steps to reproduce the bug

No specific steps.

### What to do about it?

Find the root cause and fix the issue.

### PR DESCRIPTION
**Pull request by shwstppr**
### Description
Fixes #11058

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
I don’t think the iso error is related, invesitgating, and also to verify the absence of the orphaned connection messages;
@blueorangutan test keepEnv

**Comment by DaanHoogland** [comment]
checked on both MSses of a lab env and the message no longer occurs with this change.

**Comment by DaanHoogland** [comment]
@shwstppr are you satisfied like this or due you want to work on this some more?

**Comment by shwstppr** [comment]
@DaanHoogland I've updated two more similar code blocks. Will run another round of tests and mark it ready.

@blueorangutan package

**Comment by shwstppr** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
previous version tested, and smoke tests pass, merging

File: server/src/main/java/com/cloud/alert/AlertManagerImpl.java [hunk 1]
```diff
@@ -290,8 +294,13 @@ protected void recalculateHostCapacities() {
                 Math.min(CapacityManager.CapacityCalculateWorkers.value(), hostIds.size())));
         for (Long hostId : hostIds) {
             futures.put(hostId, executorService.submit(() -> {
-                final HostVO host = hostDao.findById(hostId);
-                _capacityMgr.updateCapacityForHost(host);
+                Transaction.execute(new TransactionCallbackNoReturn() {
+                    @Override
+                    public void doInTransactionWithoutResult(TransactionStatus status) {
+                        final HostVO host = hostDao.findById(hostId);
+                        _capacityMgr.updateCapacityForHost(host);
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/alert/AlertManagerImpl.java:301]: @shwstppr 
I noticed an exception in the management-server.log which seems to be related to this change

```
2025-09-10 15:22:10,998 ERROR [o.a.c.f.m.MessageBusBase] (pool-18-thread-1:[]) (logid:) NO EVENT PUBLISH CAN BE WRAPPED WITHIN DB TRANSACTION! com.cloud.utils.exception.CloudRuntimeException: NO EVENT PUBLISH CAN BE WRAPPED WITHIN DB TRANSACTION!
        at org.apache.cloudstack.framework.messagebus.MessageBusBase.publish(MessageBusBase.java:168)
        at com.cloud.capacity.CapacityManagerImpl.updateCapacityForHost(CapacityManagerImpl.java:774)
        at com.cloud.alert.AlertManagerImpl$1.doInTransactionWithoutResult(AlertManagerImpl.java:301)
        at com.cloud.utils.db.TransactionCallbackNoReturn.doInTransaction(TransactionCallbackNoReturn.java:25)
        at com.cloud.utils.db.Transaction$2.doInTransaction(Transaction.java:48)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:38)
        at com.cloud.utils.db.Transaction.execute(Transaction.java:45)
        at com.cloud.alert.AlertManagerImpl.lambda$recalculateHostCapacities$0(AlertManagerImpl.java:297)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

Comment (shwstppr) [reply server/src/main/java/com/cloud/alert/AlertManagerImpl.java:301]: @weizhouapache I'm not seeing this in a few of my test environments. Any reproduction steps?
