### PR TITLE
Check for null volume pool ID when tagging

### LINKED ISSUE #6878: NullPointerException tagging a VM
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API
~~~

##### CLOUDSTACK VERSION
~~~
4.17.1.0
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When attempting to tag a VM, we're getting a NullPointerException in `TaggedResourceManagerImpl`. This NPE is happening in `informStoragePoolForVmTags` when the volume does not have a Pool ID associated with it. This issue is blocking our upgrade to 4.17.1.0.

```
2022-10-27 13:51:55,695 ERROR [c.c.a.ApiServer] (qtp1026055550-5193:ctx-3abf03c9 ctx-b53aa077 ctx-cca24aa6) (logid:847d7482) unhandled exception executing api command: [Ljava.lang.String;@7e515dd1
java.lang.NullPointerException
	at com.cloud.tags.TaggedResourceManagerImpl.informStoragePoolForVmTags(TaggedResourceManagerImpl.java:321)
	at com.cloud.tags.TaggedResourceManagerImpl$1.doInTransactionWithoutResult(TaggedResourceManagerImpl.java:225)
```

The issue appears to be that `volume.getPoolId()` returns a `Long` with a null value and `dataStoreMgr.getDataStore(long storeId, DataStoreRole role)` accepts a `long` (which cannot be null).   

https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java#L321.  

Adding a null check for `volume.getPoolId()` before calling `dataStoreMgr.getDataStore()` should take care of it.

##### STEPS TO REPRODUCE
Tag a VM with a volume which does not have a pool id.

##### EXPECTED RESULTS
VM is tagged

##### ACTUAL RESULTS
NPE when tagging

### PR DESCRIPTION
**Pull request by csquire**
### Description

Fixes #6878

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

File: server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java [hunk 1]
```diff
@@ -318,7 +318,11 @@ public Map<String, String> getTagsFromResource(ResourceObjectType type, long res
...
         for (VolumeVO volume : volumeVos) {
-            DataStore dataStore = dataStoreMgr.getDataStore(volume.getPoolId(), DataStoreRole.Primary);
+            Long poolId = volume.getPoolId();
+            if (poolId == null) {
+                continue;
+            }
+            DataStore dataStore = dataStoreMgr.getDataStore(poolId, DataStoreRole.Primary);
             if (dataStore == null || !(dataStore.getDriver() instanceof PrimaryDataStoreDriver)) {
                 continue;
             }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java:328]: can you combine these and put them in a separate method?
something like 
```
DataStore dataStore = null;
try {
    DataStore dataStore = retrieveDatastore(poolId);
} catch (<local>Exception e) {
   log.info(String.format("no data store found for vm %s with poolId %d", vm.getName(), poolId));
    continue;
}
```
and move the code to new method `DataStore retrieveDatastore(Long poolId) {..}`

**Review by DaanHoogland — APPROVED** [review]
code looks good, small improvement possible (no -1)

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java (hunk 1 above)
Comment (csquire) [reply server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java]: Hi Daan, I extracted it. I'm not sure I follow what the goal is with the throwing. It would still require a null check after the catch and another `continue`.

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java]: yeah, it was just an example. Your solution is addequate.

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
extra diligence
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java [hunk 2]
```diff
@@ -318,8 +318,10 @@ public Map<String, String> getTagsFromResource(ResourceObjectType type, long res
     private void informStoragePoolForVmTags(long vmId, String key, String value) {
         List<VolumeVO> volumeVos = volumeDao.findByInstance(vmId);
         for (VolumeVO volume : volumeVos) {
-            DataStore dataStore = dataStoreMgr.getDataStore(volume.getPoolId(), DataStoreRole.Primary);
+            Long poolId = volume.getPoolId();
+            DataStore dataStore = retrieveDatastore(poolId);
             if (dataStore == null || !(dataStore.getDriver() instanceof PrimaryDataStoreDriver)) {
+                s_logger.info(String.format("no data store found for vmId %d with poolId %d", vmId, poolId));
```
Comment (stephankruggg) [inline server/src/main/java/com/cloud/tags/TaggedResourceManagerImpl.java:324]:
```suggestion
                s_logger.info(String.format("No data store found for VM %d with pool ID %d.", vmId, poolId));
```

**Review by stephankruggg — APPROVED** [review]

**Comment by nvazquez** [comment]
@rohityadavcloud @DaanHoogland can this fix be considered for the 4.17.2 milestone?

**Comment by DaanHoogland** [comment]
@csquire 

> @rohityadavcloud @DaanHoogland can this fix be considered for the 4.17.2 milestone?

would you consider rebasing this on 4.17 , so we can honour @nvazquez' request?

**Comment by rohityadavcloud** [comment]
Thanks @csquire - hope you don't mind, taken the liberty to rebase your PR branch to 4.17.
@blueorangutan package

**Comment by rohityadavcloud** [comment]
@blueorangutan test
