### PR TITLE
Fix: Use Q35 chipset for UEFI x86_64

### LINKED ISSUE #4245: VM cannot run normally in kvm UEFI LEGACY mode
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
KVM 
UEFI
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0
~~~

##### OS / ENVIRONMENT

Hypervisor:  CentOS7.6
Compiled against library: libvirt 4.5.0
Using library: libvirt 4.5.0
Using API: QEMU 4.5.0
Running hypervisor: QEMU 2.12.0

OVMF: OVMF-20180508-6.gitee3198e672e2.el7.noarch

##### SUMMARY

Under KVM Hypervisor
In UEFI LEGACY mode, the VM cannot enter the system normally, and "Guest has not initialized the display (yet)." is displayed in the console.

image
VM starts normally in UEFI Secure mode

After comparison, we found that:
**In UEFI LEGACY mode, the VM uses pc-i440f chip,**
**In UEFI Secure mode, the Q35 chip is used.**

After I switched the VM chip from pc-i440fx-rhel7.6.0 to pc-q35-rhel7.6.0 (manually modify the configuration file), the VM can enter the system normally.

**so. UEFI under CentOS7 should run under Q35 chip (UEFI LEGACY AND UEFI SECURE)**

##### STEPS TO REPRODUCE

~~~
1.Deploy VM through template, boot type select UEFI.Boot Mode select LEGACY 
2.After the VM runs successfully, open the console

~~~

##### EXPECTED RESULTS

~~~
The console displays guest OS information, or UEFI shell.
~~~

##### ACTUAL RESULTS

~~~
Guest has not initialized the display (yet).
~~~

### PR DESCRIPTION
**Pull request by jairov4**
### Description
Fix #4245 

This PR uses Q35 chipset for UEFI in x86_64.
Currently this mistakenly only enabled for secure boot

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [x] Major
- [ ] Minor

#### Bug Severity

- [x] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?
Build and run a UEFI VM using OVMF firmware.
Both of Secure Boot and Legacy modes are working now

### CODE REVIEW

**Comment by rhtyd** [comment]
@jairov4 can you rebase to 4.15 branch?

**Comment by GabrielBrascher** [comment]
Considering that the bug was reported on 4.14.0.0, maybe this would be nice to have it rebased to branch 4.14, and fast forwarded to 4.15 and then master.

**Comment by jairov4** [comment]
Hi, I rebased it to 4.14

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java [hunk 1]
```diff
@@ -2247,8 +2247,8 @@ public LibvirtVMDef createVMFromSpec(final VirtualMachineTO vmTO) {
         if (MapUtils.isNotEmpty(customParams) && customParams.containsKey(GuestDef.BootType.UEFI.toString())) {
             guest.setBootType(GuestDef.BootType.UEFI);
             guest.setBootMode(GuestDef.BootMode.LEGACY);
+            guest.setMachineType("q35");
```
Comment (DaanHoogland) [inline plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2250]: should we make assumptions about running on intel platforms and/or would that hurt? cc @wido @rhtyd #raspberryrules

Comment (wido) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2250]: I know it's super fun to run on a Pi and people use it to dev with it.

But I think 99,999999% of all CloudStack installations runs on x86_64 CPUs from either Intel or AMD.

Comment (DaanHoogland) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2250]: i wanted to see that `AMD` thanks

Comment (wido) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2250]: > i wanted to see that `AMD` thanks

Keep in mind though that both AMD and Intel produce CPUs with the x86_64 Architecture.

As this is all virtualization I think this also works on AMD Epyc CPUs.

Comment (DaanHoogland) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2250]: Well, I did get some problem reports back on my quick search, but the general tone is that it should work indeed.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by rhtyd** [comment]
@blueorangutan test

File: plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java (hunk 1 above)
Comment (rhtyd) [reply plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java:2250]: I personally run a toy PI4 env for fun, so I would prefer a suitable if-else be added based on platform, arch parameters (I'm not sure if the hard-coded chipset works on RPi4)

**Review by rhtyd — APPROVED** [review]

**Review by rhtyd — APPROVED** [review]
LGTM (won't affect rpi4, which is uefi default, line no. 2245 has this check for aarch64)

**Review by shwstppr — APPROVED** [review]
LGTM
