### PR TITLE
ui: fix focus in deployvm form

### LINKED ISSUE #5087: UI: 4.15.1 RC1 - deploy VM instance UI automatically scrolls down...
* Bug Report

15sec video
http://somup.com/cr1j35qxiP

Has to be fixed for RC2

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5087

After changes:
deployfocus

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [x] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by Pearl1594** [comment]
@blueorangutan ui

**Comment by utchoang** [comment]
@shwstppr I think need to remove the autoFocus part from the file `NetworkConfiguration.vue` line 36 `:autoFocus="record.type!=='L2'"`. It won't cause scroll errors anymore

**Review by rhtyd — APPROVED** [review]

File: ui/src/views/compute/wizard/ComputeOfferingSelection.vue [hunk 1]
```diff
@@ -21,8 +21,7 @@
       style="width: 25vw;float: right;margin-bottom: 10px; z-index: 8"
       :placeholder="$t('label.search')"
       v-model="filter"
-      @search="handleSearch"
-      autoFocus />
```
Comment (rhtyd) [inline ui/src/views/compute/wizard/ComputeOfferingSelection.vue:25]: @utchoang could your change on autoFocus break other parts of the UI?

Comment (utchoang) [reply ui/src/views/compute/wizard/ComputeOfferingSelection.vue:25]: @rhtyd Yes, maybe I added unnecessary autoFocus in the child components of the deploy VM form. Just delete the contents of the child components of deploy VM and it will work properly.

**Review by utchoang — APPROVED** [review]

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by Pearl1594 — APPROVED** [review]
LGTM

**Comment by rhtyd** [comment]
@shwstppr the way to reproduce/test would be on tiny screens (tab or mobile mode) as per @andrijapanicsb 's video.

**Comment by rhtyd** [comment]
Tested on an ipad screen size and was able to see issue with 4.15/master but not with this PR - LGTM.

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
@blueorangutan help

**Comment by andrijapanicsb** [comment]
LGTM as well, thx
