### PR TITLE
server: fix listnetworkofferings with domain, refactor listvpofferings

### LINKED ISSUE #6745: API: list network offerings doesn't work with multiple domains
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Make sure you have 2 domains (called here X and Y)

~~~
cmk create networkoffering domainid=X,Y type=shared [...] (just fill in the required args)
cmk list networkofferings domainid=X type=shared
~~~

##### EXPECTED RESULTS

~~~
Should return the created networkoffering
~~~

##### ACTUAL RESULTS

~~~
Nothing is returned
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #6745

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Using API with cmk,

```
(local) 🍂 > create domain name=d1
{
  "domain": {
    "haschild": false,
    "id": "afd89eeb-da02-4701-8b87-df0701d8c4a8",
    "level": 1,
    "name": "d1",
    "parentdomainid": "fcb3da55-37e0-11ed-b99e-645d8651f45a",
    "parentdomainname": "ROOT",
    "path": "ROOT/d1",
    "secondarystoragetotal": 0
  }
}
(local) 🐷 > create domain name=d2
{
  "domain": {
    "haschild": false,
    "id": "e52fe7a9-0f29-4463-84c4-21bcadf0b99f",
    "level": 1,
    "name": "d2",
    "parentdomainid": "fcb3da55-37e0-11ed-b99e-645d8651f45a",
    "parentdomainname": "ROOT",
    "path": "ROOT/d2",
    "secondarystoragetotal": 0
  }
}
(local) 🙉 > create networkoffering name=n1 displaytext=n1 domainid=fcb3da55-37e0-11ed-b99e-645d8651f45a,fcb3da55-37e0-11ed-b99e-645d8651f45a guestiptype=Isolated traffictype=Guest
{
  "networkoffering": {
    "availability": "Optional",
    "conservemode": true,
    "created": "2022-09-19T12:07:33+0530",
    "displaytext": "n1",
    "domain": "/",
    "domainid": "fcb3da55-37e0-11ed-b99e-645d8651f45a",
    "egressdefaultpolicy": true,
    "forvpc": false,
    "guestiptype": "Isolated",
    "hasannotations": false,
    "id": "391ae3f6-a931-44d7-9ed4-5e24b8bbffe4",
    "internetprotocol": "IPv4",
    "isdefault": false,
    "ispersistent": false,
    "name": "n1",
    "networkrate": 200,
    "service": [],
    "serviceofferingid": "08886d07-11eb-48e1-ac7f-f0f92fbfe085",
    "specifyipranges": false,
    "specifyvlan": false,
    "state": "Disabled",
    "supportspublicaccess": false,
    "supportsstrechedl2subnet": false,
    "traffictype": "Guest"
  }
}
(local) 🍄 > list networkofferings domainid=afd89eeb-da02-4701-8b87-df0701d8c4a8 filter=id,name,state
{
  "count": 15,
  "networkoffering": [
    {
      "id": "32c33040-c64b-4f2a-aa4e-fefd72e5e4d4",
      "name": "DefaultSharedNetworkOfferingWithSGService",
      "state": "Enabled"
    },
    ...
    {
      "id": "391ae3f6-a931-44d7-9ed4-5e24b8bbffe4",
      "name": "n1",
      "state": "Disabled"
    }
  ]
}
(local) 🐞 > list networkofferings domainid=e52fe7a9-0f29-4463-84c4-21bcadf0b99f  filter=id,name,state
{
  "count": 15,
  "networkoffering": [
    {
      "id": "32c33040-c64b-4f2a-aa4e-fefd72e5e4d4",
      "name": "DefaultSharedNetworkOfferingWithSGService",
      "state": "Enabled"
    },
    ...
    {
      "id": "391ae3f6-a931-44d7-9ed4-5e24b8bbffe4",
      "name": "n1",
      "state": "Disabled"
    }
  ]
}
```

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java [hunk 1]
```diff
@@ -6614,25 +6614,26 @@ public Pair<List<? extends NetworkOffering>, Integer> searchForNetworkOfferings(
...
+                if (StringUtils.isEmpty(offering.getDomainId())) {
+                    continue;
+                }
+                boolean toRemove = true;
+                String[] domainIdsArray = offering.getDomainId().split(",");
+                for (String domainIdString : domainIdsArray) {
+                    Long dId = Long.valueOf(domainIdString.trim());
+                    if (caller.getType() != Account.Type.ADMIN &&
+                            _domainDao.isChildDomain(dId, caller.getDomainId())) {
+                        toRemove = false;
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:6626]: We could call `it.remove()` here instead of creating a variable and having to verify it later.

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java [hunk 2]
```diff
@@ -6614,25 +6614,26 @@ public Pair<List<? extends NetworkOffering>, Integer> searchForNetworkOfferings(
...
+                        break;
                     }
-                    if (toRemove) {
-                        it.remove();
+                    if (domainId != null && _domainDao.isChildDomain(dId, domainId)) {
+                        toRemove = false;
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java:6630]: We could call `it.remove()` here instead of creating a variable and having to verify it later.

File: server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java [hunk 3]
```diff
@@ -730,20 +730,21 @@ public Pair<List<? extends VpcOffering>, Integer> listVpcOfferings(ListVPCOfferi
...
-                    for (String domainIdString : domainIdsArray) {
-                        Long dId = Long.valueOf(domainIdString.trim());
-                        if (domainDao.isChildDomain(dId, caller.getDomainId())) {
-                            toRemove = false;
-                            break;
-                        }
-                    }
-                    if (toRemove) {
-                        it.remove();
+                if(org.apache.commons.lang3.StringUtils.isEmpty(offering.getDomainId())) {
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java:733]:
```suggestion
                if (org.apache.commons.lang3.StringUtils.isEmpty(offering.getDomainId())) {
```

File: server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java [hunk 4]
```diff
@@ -730,20 +730,21 @@ public Pair<List<? extends VpcOffering>, Integer> listVpcOfferings(ListVPCOfferi
...
+                    continue;
+                }
+                boolean toRemove = true;
+                String[] domainIdsArray = offering.getDomainId().split(",");
+                for (String domainIdString : domainIdsArray) {
+                    Long dId = Long.valueOf(domainIdString.trim());
+                    if (domainDao.isChildDomain(dId, caller.getDomainId())) {
+                        toRemove = false;
```
Comment (GutoVeronezi) [inline server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java:741]: We could call it.remove() here instead of creating a variable and having to verify it later.

**Comment by shwstppr** [comment]
Not ready. Need to test after latest commit

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java (hunk 1 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java]: done

File: server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java (hunk 2 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/configuration/ConfigurationManagerImpl.java]: done

File: server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java (hunk 4 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java]: done

File: server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java (hunk 3 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java]: done

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/user/DomainManager.java [hunk 5]
```diff
@@ -51,4 +51,6 @@ public interface DomainManager extends DomainService {
     public static final String MESSAGE_ADD_DOMAIN_EVENT = "Message.AddDomain.Event";
     public static final String MESSAGE_PRE_REMOVE_DOMAIN_EVENT = "Message.PreRemoveDomain.Event";
     public static final String MESSAGE_REMOVE_DOMAIN_EVENT = "Message.RemoveDomain.Event";
+
+    boolean domainIdListContainsAccessibleDomain(String domainIdList, Account caller, Long domainId);
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/user/DomainManager.java:55]: :+1:

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by shwstppr** [comment]
@DaanHoogland refactor to use DomainManagerImpl is failing build with unit test failures in `CreateNetworkOfferingTest`. I don't have a solution for it right now

**Comment by shwstppr** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java [hunk 6]
```diff
@@ -715,11 +716,22 @@ public Pair<List<? extends VpcOffering>, Integer> listVpcOfferings(ListVPCOfferi
...
 
+        if (domainId != null) {
+            Domain domain = _entityMgr.findById(Domain.class, domainId);
+            if (domain == null) {
+                throw new InvalidParameterValueException("Unable to find the domain by id=" + domainId);
+            }
+            if (!domainDao.isChildDomain(caller.getDomainId(), domainId)) {
+                throw new InvalidParameterValueException(String.format("Unable to list VPC offerings for domain: %s as caller does not have access for it", domain.getUuid()));
+            }
+        }
```
Comment (DaanHoogland) [inline server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java:733]: can this go in a separate `verifyDomainId()`, please?

**Review by DaanHoogland — APPROVED** [review]
code looks good.

File: server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java (hunk 6 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java]: Done

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test

**Review by vladimirpetrov — APPROVED** [review]
LGTM based on manual testing.
