### PR TITLE
server,config: respect storage.max.volume.size and make it dynamic

### LINKED ISSUE #5830: "storage.max.volume.size" config needs fixing
There is a global config to control the size of the volume
image

There are 2 issues with this config
1. This is marked as dynamic, but it is not, we need to restart the management server. This needs to either set the dynamic flag to false or fix the usage of the config.
2. In the case of root volume, when the root volume is first created this config is not considered, later if we try to resize the same root volume then the config is being considered.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Global Setting
~~~

##### CLOUDSTACK VERSION

~~~
4.16, main
~~~

##### STEPS TO REPRODUCE

~~~
1. set the config value of "storage.max.volume.size" to 2GB
2. create a VM with root disk size more than 3GB
3. Try to resize the root volume to some higher value 
~~~

##### EXPECTED RESULTS

~~~
Root volume with higher size should not be created.
~~~

##### ACTUAL RESULTS

~~~
Root volume is created with higher value and if we try to resize then operation failed with error stating the global setting.
~~~

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #5830

- Config - `storage.max.volume.size` is made dynamic.
- Enforced config during deployVM, volume creation and volume resize.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### How Has This Been Tested?

Using cmk while setting the config value to 15gb and then trying different operations deploy VM, create volume, resize volume over and within this limit.

**Update `storage.max.volume.size` to 15**
```
(local) 🦌 > list configurations name=storage.max.volume.size
{
  "configuration": [
    {
      "category": "Storage",
      "description": "The maximum size for a volume (in GB).",
      "isdynamic": true,
      "name": "storage.max.volume.size",
      "value": "2000"
    }
  ],
  "count": 1
}
(local) 🐑 > update configuration name=storage.max.volume.size value=15
{
  "configuration": {
    "category": "Storage",
    "description": "The maximum size for a volume (in GB).",
    "isdynamic": true,
    "name": "storage.max.volume.size",
    "value": "15"
  }
}
(local) 🐌 > set username user
(local) 🐌 > sync
Discovered 281 APIs
```

**Operations failing with volume size over 15gb**
```
(local) 🐠 > deploy virtualmachine zoneid=4fa5009b-36e0-4495-906e-e1668d89332c templateid=b67dc437-79c3-11ec-a92e-645d8651f45a rootdisksize=20 startvm=true serviceofferingid=4c01b261-3dfa-4e63-9860-ea506dafd78b iptonetworklist[0].networkid=55073eca-1107-4b0e-b309-e28ed821ae79
🙈 Error: (HTTP 431, error code 4350) Requested volume size is 21474836480, but the maximum size allowed is 15 GB.
(local) 🐈 > list diskofferings filter=name,id,disksize,
{
  "count": 5,
  "diskoffering": [
    {
      "disksize": 5,
      "id": "eed0dc90-d3ab-4793-b71f-e5a0d09da670",
      "name": "Small"
    },
    {
      "disksize": 20,
      "id": "9294a4f0-4731-4550-9b53-362dcd01b1a4",
      "name": "Medium"
    },
    {
      "disksize": 100,
      "id": "c0586e94-3bda-4bda-99b6-ff174e70e2df",
      "name": "Large"
    },
    {
      "disksize": 0,
      "id": "8b5de680-d3c2-4913-bcb7-ee5e0b9b426b",
      "name": "Custom"
    },
    {
      "disksize": 15,
      "id": "714d2b73-38d8-4ce4-994a-5195f6dcc4a2",
      "name": "15gb"
    }
  ]
}
(local) 🐶 > create volume zoneid=4fa5009b-36e0-4495-906e-e1668d89332c diskofferingid=9294a4f0-4731-4550-9b53-362dcd01b1a4 name=v1
🙈 Error: (HTTP 431, error code 4350) Requested volume size is 21474836480, but the maximum size allowed is 15 GB.
(local) 🐝 > create volume zoneid=4fa5009b-36e0-4495-906e-e1668d89332c diskofferingid=eed0dc90-d3ab-4793-b71f-e5a0d09da670  name=v1
{
  "volume": {
    "account": "user",
    "created": "2022-01-20T13:43:06+0530",
    "destroyed": false,
    "diskofferingdisplaytext": "Small Disk, 5 GB",
    "diskofferingid": "eed0dc90-d3ab-4793-b71f-e5a0d09da670",
    "diskofferingname": "Small",
    "domain": "ROOT",
    "domainid": "76250dec-79c3-11ec-a92e-645d8651f45a",
    "hasannotations": false,
    "id": "8a373941-6d28-408f-b004-b66da1e523ab",
    "isextractable": true,
    "jobid": "dce82ab2-0f11-4379-aa50-0a67f174c8cb",
    "jobstatus": 0,
    "name": "v1",
    "provisioningtype": "thin",
    "quiescevm": false,
    "size": 5368709120,
    "state": "Allocated",
    "supportsstoragesnapshot": false,
    "tags": [],
    "type": "DATADISK",
    "zoneid": "4fa5009b-36e0-4495-906e-e1668d89332c",
    "zonename": "Sandbox-simulator"
  }
}
(local) 🐻 > resize volume id=8a373941-6d28-408f-b004-b66da1e523ab diskofferingid=9294a4f0-4731-4550-9b53-362dcd01b1a4 
{
  "accountid": "b4c59d24-4340-46ac-b576-8de5fc0524cf",
  "cmd": "org.apache.cloudstack.api.command.user.volume.ResizeVolumeCmd",
  "completed": "2022-01-20T13:43:22+0530",
  "created": "2022-01-20T13:43:22+0530",
  "jobid": "44fc3383-63ca-4207-b6dc-f1a9b63a43c5",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 432,
    "errortext": "Requested volume size is 21474836480, but the maximum size allowed is 15 GB."
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "ab94c245-67ab-45c5-a08b-ddcf506072ed"
}
🙈 Error: async API failed for job 44fc3383-63ca-4207-b6dc-f1a9b63a43c5
```

**Operations working with volume size less than or equal to 15gb**
```
(local) 🐡 > deploy virtualmachine zoneid=4fa5009b-36e0-4495-906e-e1668d89332c templateid=b67dc437-79c3-11ec-a92e-645d8651f45a rootdisksize=15 startvm=true serviceofferingid=4c01b261-3dfa-4e63-9860-ea506dafd78b iptonetworklist[0].networkid=55073eca-1107-4b0e-b309-e28ed821ae79
{
  "virtualmachine": {
    "account": "user",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2022-01-20T13:44:02+0530",
    "details": {},
    "displayname": "VM-529d0073-4402-41df-9b02-0313b3ff5293",
    "domain": "ROOT",
    "domainid": "76250dec-79c3-11ec-a92e-645d8651f45a",
    "guestosid": "76176d58-79c3-11ec-a92e-645d8651f45a",
    "haenable": false,
    "hasannotations": false,
    "hypervisor": "Simulator",
    "id": "529d0073-4402-41df-9b02-0313b3ff5293",
    "isdynamicallyscalable": false,
    "jobid": "3643b7db-9124-4a68-8fb6-2b65f0ec5ba0",
    "jobstatus": 0,
    "lastupdated": "2022-01-20T13:44:05+0530",
    "memory": 512,
    "name": "VM-529d0073-4402-41df-9b02-0313b3ff5293",
    "nic": [
      {
        "broadcasturi": "vlan://128",
        "deviceid": "0",
        "extradhcpoption": [],
        "gateway": "10.1.1.1",
        "id": "c220b4c6-ff2a-4caf-8097-686f3eee5ac8",
        "ipaddress": "10.1.1.64",
        "isdefault": true,
        "isolationuri": "vlan://128",
        "macaddress": "02:00:4d:ab:00:01",
        "netmask": "255.255.255.0",
        "networkid": "55073eca-1107-4b0e-b309-e28ed821ae79",
        "networkname": "test",
        "secondaryip": [],
        "traffictype": "Guest",
        "type": "Isolated"
      }
    ],
    "osdisplayname": "CentOS 5.6 (64-bit)",
    "ostypeid": "76176d58-79c3-11ec-a92e-645d8651f45a",
    "passwordenabled": false,
    "pooltype": "NetworkFilesystem",
    "readonlydetails": "dataDiskController, rootDiskController",
    "receivedbytes": 0,
    "rootdeviceid": 0,
    "rootdevicetype": "ROOT",
    "securitygroup": [],
    "sentbytes": 0,
    "serviceofferingid": "4c01b261-3dfa-4e63-9860-ea506dafd78b",
    "serviceofferingname": "Small Instance",
    "state": "Running",
    "tags": [],
    "templatedisplaytext": "CentOS 5.6 (64-bit) no GUI (Simulator)",
    "templateid": "b67dc437-79c3-11ec-a92e-645d8651f45a",
    "templatename": "CentOS 5.6 (64-bit) no GUI (Simulator)",
    "userid": "ab94c245-67ab-45c5-a08b-ddcf506072ed",
    "username": "user",
    "zoneid": "4fa5009b-36e0-4495-906e-e1668d89332c",
    "zonename": "Sandbox-simulator"
  }
}
(local) 🐇 > create volume zoneid=4fa5009b-36e0-4495-906e-e1668d89332c diskofferingid=714d2b73-38d8-4ce4-994a-5195f6dcc4a2  name=v2
{
  "volume": {
    "account": "user",
    "created": "2022-01-20T13:44:22+0530",
    "destroyed": false,
    "diskofferingdisplaytext": "15gb",
    "diskofferingid": "714d2b73-38d8-4ce4-994a-5195f6dcc4a2",
    "diskofferingname": "15gb",
    "domain": "ROOT",
    "domainid": "76250dec-79c3-11ec-a92e-645d8651f45a",
    "hasannotations": false,
    "id": "3322c16c-95d9-4b6b-8024-25663138aa1b",
    "isextractable": true,
    "jobid": "39891090-e510-44f4-95ef-6dbe65dd40e9",
    "jobstatus": 0,
    "name": "v2",
    "provisioningtype": "thin",
    "quiescevm": false,
    "size": 16106127360,
    "state": "Allocated",
    "supportsstoragesnapshot": false,
    "tags": [],
    "type": "DATADISK",
    "zoneid": "4fa5009b-36e0-4495-906e-e1668d89332c",
    "zonename": "Sandbox-simulator"
  }
}
(local) 🐍 > resize volume id=8a373941-6d28-408f-b004-b66da1e523ab diskofferingid=714d2b73-38d8-4ce4-994a-5195f6dcc4a2 
{
  "volume": {
    "account": "user",
    "created": "2022-01-20T13:43:06+0530",
    "destroyed": false,
    "diskofferingdisplaytext": "15gb",
    "diskofferingid": "714d2b73-38d8-4ce4-994a-5195f6dcc4a2",
    "diskofferingname": "15gb",
    "domain": "ROOT",
    "domainid": "76250dec-79c3-11ec-a92e-645d8651f45a",
    "hasannotations": false,
    "id": "8a373941-6d28-408f-b004-b66da1e523ab",
    "isextractable": true,
    "name": "v1",
    "provisioningtype": "thin",
    "quiescevm": false,
    "size": 16106127360,
    "state": "Allocated",
    "supportsstoragesnapshot": false,
    "tags": [],
    "type": "DATADISK",
    "zoneid": "4fa5009b-36e0-4495-906e-e1668d89332c",
    "zonename": "Sandbox-simulator"
  }
}
```

### CODE REVIEW

**Comment by shwstppr** [comment]
@harikrishna-patnala I've made changes and ensured the config is respected during VM deployment, volume creation and volume resize. Also, to fix its dynamic behaviour.
Currently, the config affects even root admin vm and volume deployment. Also, I've purposefully not included check for root disk size when it is taken directly from the template. Can you please have an initial look at the changes

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by harikrishna-patnala — APPROVED** [review]
Code LGTM

**Comment by shwstppr** [comment]
Add test details in description

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by DaanHoogland** [comment]
Can you rebase to solve the conflicts,  @shwstppr  ?

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Review by DaanHoogland — APPROVED** [review]
clgtm, needs testing

**Comment by DaanHoogland** [comment]
@blueorangutan test keepEnv

**Comment by sureshanaparti** [comment]
@blueorangutan test keepEnv

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java [hunk 1]
```diff
@@ -856,11 +855,13 @@ public VolumeVO doInTransaction(TransactionStatus status) {
...
 
+    @Override
     public boolean validateVolumeSizeRange(long size) {
+        long maxVolumeSize = VolumeOrchestrationService.MaxVolumeSize.value();
         if (size < 0 || (size > 0 && size < (1024 * 1024 * 1024))) {
             throw new InvalidParameterValueException("Please specify a size of at least 1 GB.");
-        } else if (size > (_maxVolumeSizeInGb * 1024 * 1024 * 1024)) {
-            throw new InvalidParameterValueException("Requested volume size is " + size + ", but the maximum size allowed is " + _maxVolumeSizeInGb + " GB.");
+        } else if (size > (maxVolumeSize * 1024 * 1024 * 1024)) {
+            throw new InvalidParameterValueException(String.format("Requested volume size is %d, but the maximum size allowed is %d GB.", size, maxVolumeSize));
```
Comment (sureshanaparti) [inline server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:864]: @shwstppr Can you update the log so that both the sizes are in sync with the units. For ex:

_Requested volume size is 21474836480, but the maximum size allowed is 15 GB._  => `Requested volume size is 20 GB, but the maximum size allowed is 15 GB.`

**Comment by sureshanaparti** [comment]
@blueorangutan test keepEnv

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java (hunk 1 above)
Comment (shwstppr) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: @sureshanaparti I've made the change to fix this.
I see you've started a new test run. I don't think this change affects results. Up to you.

Comment (sureshanaparti) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java]: > @sureshanaparti I've made the change to fix this.
> I see you've started a new test run. I don't think this change affects results. Up to you.

if not further changes, would upgrade the package and verify this log.

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java [hunk 2]
```diff
@@ -856,11 +855,13 @@ public VolumeVO doInTransaction(TransactionStatus status) {
...
     }
 
+    @Override
     public boolean validateVolumeSizeRange(long size) {
+        long maxVolumeSize = VolumeOrchestrationService.MaxVolumeSize.value();
         if (size < 0 || (size > 0 && size < (1024 * 1024 * 1024))) {
             throw new InvalidParameterValueException("Please specify a size of at least 1 GB.");
-        } else if (size > (_maxVolumeSizeInGb * 1024 * 1024 * 1024)) {
-            throw new InvalidParameterValueException("Requested volume size is " + size + ", but the maximum size allowed is " + _maxVolumeSizeInGb + " GB.");
+        } else if (size > (maxVolumeSize * 1024 * 1024 * 1024)) {
```
[the remark this answers is not in the document]
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:863]: the specific conversion must be added in that class first. But I agree with the suggestion.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@shwstppr Set config "storage.max.volume.size" to 10, and performed the following tests. Check tests not working as expected (marked in bold).

- Deployed VM with 8 GB disk [Passed, Works as expected]
- Deployed VM with 11 GB ROOT disk override [Failed, Works as expected]

**- Deployed VM with 9 GB ROOT disk and 3 GB Data Disk [Failed, Not working as expected, Cumulative size of ROOT and DATA disk are considered for validation, in this case it is comparing against 11 GB size]**

- Deployed VM with ISO, having 5 GB fixed disk offering [Passed, Works as expected]

**- Deployed VM with ISO, having 11 GB custom disk offering [Failed, Works as expected, but size in the error message is incorrect (Requested volume size is 14.99 GB, but the maximum size allowed is 10 GB)]**
**- Deployed VM with ISO, having 20 GB fixed disk offering [Failed, Works as expected, but size in the error message is incorrect (Requested volume size is 23.99 GB, but the maximum size allowed is 10 GB)]**

**- Deployed VM with ISO, having 9 GB custom disk offering [Failed, Not working as expected, Cumulative size of ISO - 3.99 GB and DATA disk are considered for validation, in this case it is comparing against 12.99 GB size (Requested volume size is 12.99 GB, but the maximum size allowed is 10 GB)]**

- Created Disk Offering with disk size 11 GB [Failed, Works as expected]

**- Created Compute Offering with ROOT disk size 11 GB [Passed, Not working as expected, Shouldn't allow]**
**- Deployed VM with Compute Offering having ROOT disk size 11 GB disk [Passed, Not working as expected, Shouldn't allow]**

- Create DATA volume with 20 GB fixed disk offering [Failed, Works as expected]
- Create DATA volume with 1 GB custom disk offering [Passed, Works as expected]

- Resize DATA volume of a running VM, from 9 GB to 20 GB fixed disk offering [Failed, Works as expected]

- Resize ROOT volume of a running VM, from 8 GB to 11 GB [Failed, Works as expected]
- Resize ROOT volume of a running VM, from 8 GB to 10 GB [Passed, Works as expected]

- Resize DATA volume of a running VM, from 1 GB to 5 GB fixed disk offering [Passed, Works as expected]
- Resize DATA volume of a running VM, from 5 GB to 9 GB custom disk offering [Passed, Works as expected]
- Resize DATA volume of a running VM, from 9 GB to 20 GB fixed disk offering [Failed, Works as expected]
- Resize DATA volume of a running VM, from 9 GB to 11 GB custom disk offering [Failed, Works as expected]

- Resize ROOT volume of a stopped VM, from 8 GB to 11 GB [Failed, Works as expected]
- Resize ROOT volume of a stopped VM, from 8 GB to 9 GB [Passed, Works as expected]

- Resize DATA volume of a stopped VM, 9 GB to 20 GB fixed disk offering [Failed, Works as expected]
- Resize DATA volume of a stopped VM, 9 GB to 10 GB custom disk offering [Passed, Works as expected]

- Resize detached DATA volume, from 5 GB to 20 GB fixed disk offering [Failed, Works as expected]
- Resize detached DATA volume, from 5 GB to 7 GB custom disk offering [Passed, Works as expected]

**Comment by shwstppr** [comment]
@sureshanaparti I don't think the config applies to cumulative VM volume size. In my understanding it is for individual volumes.
I'll check and update for offering's root disk size and size mismatch in error message

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java [hunk 3]
```diff
@@ -3831,11 +3830,15 @@ private UserVm createVirtualMachine(DataCenter zone, ServiceOffering serviceOffe
         // check if account/domain is with in resource limits to create a new vm
         boolean isIso = Storage.ImageFormat.ISO == template.getFormat();
 
-        long size = configureCustomRootDiskSize(customParameters, template, hypervisorType, offering);
+        long volumesSize = isIso ? 0 : configureCustomRootDiskSize(customParameters, template, hypervisorType, offering);
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3833]: @sureshanaparti do we need to consider even ISO size for resource limit check done at line 3683? cc @DaanHoogland @rohityadavcloud @weizhouapache 
I've made the change as volume VMs deployed using ISOs will always have root volume created from the specified disk offering and ISO size shouldn't be considered

File: server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (shwstppr) [reply server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java:863]: @GutoVeronezi @DaanHoogland To use `ByteScaleUtils` new method(s) will need to be added. I feel we can do that in `main` in a separate PR and attempt to refactor similar ocurrences

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java (hunk 3 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3833]: Makes sense from a logical viewpoint but as an operator, will the ISO not also take its space on primary, i.e. will the user not have to be charged for that space?

Comment (shwstppr) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java:3833]: I'm not completely sure if ISO will be copied to primary store. But even if is and if the same ISO is used by 10 accounts to deploy a VM each, the operator will end up charging them all for ISO size.
Better for now, leave it as it is, too big a change for 4.16.1 :D I'm reverting it.

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Review by rohityadavcloud — APPROVED** [review]

File: server/src/main/java/com/cloud/vm/UserVmManagerImpl.java (hunk 3 above)
Comment (DaanHoogland) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java]: ok, as long as it's clear and consistent we can always revisit. @sureshanaparti, agree ?

Comment (sureshanaparti) [reply server/src/main/java/com/cloud/vm/UserVmManagerImpl.java]: agree @DaanHoogland

**Comment by sureshanaparti** [comment]
> @sureshanaparti I don't think the config applies to cumulative VM volume size. In my understanding it is for individual volumes.
> I'll check and update for offering's root disk size and size mismatch in error message

@shwstppr Verified the cases not working as expected, with the latest changes. Invalid error message in one case, check below.

- Deployed VM with 9 GB ROOT disk and 3 GB Data Disk [Passd, Working as expected]
- Deployed VM with ISO, having 11 GB custom disk offering [Failed, Works as expected]
- Deployed VM with ISO, having 20 GB fixed disk offering [Failed, Works as expected]
- Deployed VM with ISO, having 9 GB custom disk offering [Passed, Working as expected]
- Created Compute Offering with ROOT disk size 11 GB [Failed, Working as expected]
**- Deployed VM with Compute Offering having ROOT disk size 11 GB disk [Failed, Working as expected, But wrong error message - Please specify a size of at least 1 GB.]**

**Comment by shwstppr** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
> > @sureshanaparti I don't think the config applies to cumulative VM volume size. In my understanding it is for individual volumes.
> > I'll check and update for offering's root disk size and size mismatch in error message
> 
> @shwstppr Verified the cases not working as expected, with the latest changes. Invalid error message in one case, check below.
> 
> * Deployed VM with 9 GB ROOT disk and 3 GB Data Disk [Passd, Working as expected]
> * Deployed VM with ISO, having 11 GB custom disk offering [Failed, Works as expected]
> * Deployed VM with ISO, having 20 GB fixed disk offering [Failed, Works as expected]
> * Deployed VM with ISO, having 9 GB custom disk offering [Passed, Working as expected]
> * Created Compute Offering with ROOT disk size 11 GB [Failed, Working as expected]
> * **Deployed VM with Compute Offering having ROOT disk size 11 GB disk [Failed, Working as expected, But wrong error message - Please specify a size of at least 1 GB.]**

Verified the error message with the latest changes. LGTM.

**Comment by sureshanaparti** [comment]
@blueorangutan package
