### PR TITLE
UI: Update domain level configuration

### LINKED ISSUE #11570: ldap.search.group.principle Issue
### problem

ldap.search.group.principle by default is NULL in the database.  If you enter a value and then make it blank, it just results in a blank field in the database.  LDAP just ends up searching a blank value.  

In the logs you will see this entry:
`2025-08-20 10:39:56,759 DEBUG o.a.c.l.OpenLdapUserManagerImpl (qtp364604394-3267:ctx-e080a1e5) (logid:9d1297c5) adding search filter for '', using 'memberof'`

### versions

4.20.1

### The steps to reproduce the bug

1. Put a value in `ldap.search.group.principle`
2. Remove the value in `ldap.search.group.principle` **Note: Do not click reset to default**
3. Attempt LDAP login and review the logs
...

### What to do about it?

LDAP should treat a blank value the same as a NULL Value.

### PR DESCRIPTION
**Pull request by Pearl1594**
### Description

This PR fixes #11570 
Following issues were fixed:
1. When updating domain-level setting (from UI) it is observed that it doesn't pass the domain id, hence leading to the update of the global setting
2. On switching between different domains, the settings weren't getting updated. i.e., while the API returns the correct value, the settings displayed the older domains values.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Comment by shwstppr** [comment]
@blueorangutan ui

**Review by harikrishna-patnala — COMMENTED** [review]
@Pearl1594 does this need change in base branch to 4.20 ?

File: ui/src/views/setting/ConfigurationValue.vue [hunk 1]
```diff
@@ -280,6 +295,9 @@ export default {
         name: configrecord.name,
         value: newValue
       }
+      if (this.scopeKey === 'domainid' && !params[this.scopeKey]) {
```
Comment (shwstppr) [inline ui/src/views/setting/ConfigurationValue.vue:293]: do we need the this.scopeKey === 'domainid' check? Can it be 
```suggestion
      if (this.scopeKey && !params[this.scopeKey]) {
```

File: ui/src/views/setting/ConfigurationValue.vue [hunk 2]
```diff
@@ -254,6 +258,17 @@ export default {
     this.setConfigData()
   },
   watch: {
+    loading (newVal, oldVal) {
```
Comment (shwstppr) [inline ui/src/views/setting/ConfigurationValue.vue]: Is loading value for the element set somewhere in the code?
Similarly for property `configDisable`, though unrelated to the PR

File: ui/src/views/setting/ConfigurationValue.vue (hunk 1 above)
Comment (Pearl1594) [reply ui/src/views/setting/ConfigurationValue.vue:293]: I specifically added domainid, because it's taken care of for other cases.

**Comment by weizhouapache** [comment]
I could not reproduce the issue with updateconfiguration in 4.20, the domainid is passed

https://github.com/apache/cloudstack/blob/2cd7d8a315e2917d90cf6994977937d3752a6785/ui/src/components/view/SettingsTab.vue#L172-L175

it seems to be a regression of #10596 

moving to 4.22 milestone. cc @Pearl1594 @harikrishna-patnala

File: ui/src/views/setting/ConfigurationValue.vue (hunk 2 above)
Comment (Pearl1594) [reply ui/src/views/setting/ConfigurationValue.vue]: removed loading.

File: ui/src/views/setting/ConfigurationValue.vue (hunk 1 above)
Comment (Pearl1594) [reply ui/src/views/setting/ConfigurationValue.vue:293]: Are you fine with this change @shwstppr , because as mentioned, this only is an issue with domain scope, for other scopes the scoped resource'd id is being passed correctly

Comment (DaanHoogland) [reply ui/src/views/setting/ConfigurationValue.vue:293]: why not make it generic @Pearl1594 , is there a risk involved?

Comment (shwstppr) [reply ui/src/views/setting/ConfigurationValue.vue:293]: > Are you fine with this change @shwstppr , because as mentioned, this only is an issue with domain scope, for other scopes the scoped resource'd id is being passed correctly

@Pearl1594 I feel the scopeKey check be generic. But up to you if you want to go ahead with the current change.

**Comment by kiranchavala** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan package

**Comment by DaanHoogland** [comment]
@blueorangutan test
