### PR TITLE
server: check limit on correct store during snapshot allocation

### LINKED ISSUE #11551: Snapshot fails with secondary storage quota check when using Primary Storage | ACS - 4.20.0
The snapshots are configured to be stored on **Primary Storage**. However, when attempting to create a snapshot, CloudStack still performs validation against the **Secondary Storage resource limits**.

For example:

* If we have a 10GB volume and attempt to create a snapshot without sufficient secondary storage quota for the domain, the snapshot creation fails.
* This behavior is inconsistent, as the snapshot is supposed to be stored in Primary Storage and should not depend on secondary storage quota validation.

Image

This seems to be an issue in the snapshot workflow where quota checks are incorrectly applied to secondary storage, even when primary storage is used for Snapshot.

### PR DESCRIPTION
**Pull request by shwstppr**
### Description

Fixes #11551

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### CODE REVIEW

**Review by weizhouapache — APPROVED** [review]
code lgtm

@shwstppr 
the issue number seems incorrect

File: server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java [hunk 1]
```diff
@@ -1694,9 +1694,13 @@ public Snapshot allocSnapshot(Long volumeId, Long policyId, String snapshotName,
         Type snapshotType = getSnapshotType(policyId);
         Account owner = _accountMgr.getAccount(volume.getAccountId());
 
+        ResourceType storeResourceType = ResourceType.secondary_storage;
+        if (!isBackupSnapshotToSecondaryForZone(zoneIds.get(0)) || Snapshot.LocationType.PRIMARY.equals(locationType)) {
+            storeResourceType = ResourceType.primary_storage;
```
Comment (shwstppr) [inline server/src/main/java/com/cloud/storage/snapshot/SnapshotManagerImpl.java:1702]: I'm not sure if we should even check for the primary store

**Comment by shwstppr** [comment]
@blueorangutan package

**Review by vishesh92 — APPROVED** [review]
clgtm

**Comment by vishesh92** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
there is another issue: we may need to fix the process of resouce count calculation

https://github.com/apache/cloudstack/blob/70a4503ea16db57dbcd2535a55f90dbad538a52f/server/src/main/java/com/cloud/resourcelimit/ResourceLimitManagerImpl.java#L1497-L1504

similar change is needed when calculate the primary storage usage

**Comment by weizhouapache** [comment]
@blueorangutan package

**Comment by weizhouapache** [comment]
verified ok

- snapshot.backup.to.secondary = false
- take volume snapshot
- without this PR, the resource count of secondary_storage is updated
- with this PR, the resource count of primary_storage is updated

**Comment by weizhouapache** [comment]
@blueorangutan test

**Comment by weizhouapache** [comment]
Merging based on approvals and tests
