### PR TITLE
Guard OS type update for iso/template with existing vms

### LINKED ISSUE #10588: ISO Image OS Type is tied to the Instance, even after the ISO is disconnected, changes affect all Instances
### problem

We killed a bunch of our VMs due to this and I am pretty sure that this behavior cannot be intended, so I post it as a bug. I hope this is the correct way.

We created a bunch of (Windows) VM Instances by uploading the Windows ISO file, setting the OS Type to Windows Server 2022 and then creating instances based on that ISO (create a new instance, boot the ISO, install Windows...).
After the installation we usually disconnect the ISO from the instance.
Now to test various OS types, we changed the OS type on the ISO file and found out that all VMs that originated from that ISO got their OS type changed too.

This lead to all the affected VMs to boot into a BSOD (Bluescreen) and we could not fix them, so we had to recreate those instances from scratch.

It is a test environment, so no harm was done.

### versions

OS Ubuntu 24.04
Apache Cloudstack 4.20.0.0 installed via the ACS Quickstart guide, so not compiled from source here!
Hypervisor KVM QEMU emulator version 8.2.2
Libvirtd v 10.0.0

### The steps to reproduce the bug

1. Upload a ISO (Windows Server 2022 Evaluation in our case) and set the OS Type to Windows Server 2022
2. Create a new instance based on that ISO and turn it on, install Windows etc.
3. Disconnect the ISO from the Instance
4. Create as many Instances that way as you want
5. Go back to the ISO Image and change the OS Type to for example Other PV 64 Bit
6. In the ISO Image click on Instances to see which Instances are connected to this ISO. If you disconnected the ISO after the Instance creation / Windows installation, this list will be empty. No visible connection to an instance exists.
7. Check your instances and observe that the OS type changed for all of them from Windows Server 2022 to Other PV 64 Bit
8. You can repeat steps 5-6 as often as you want, the OS type of the instances that do not seem to have any connection to the ISO are always changing.

### What to do about it?

I do not know. I suspect that there is a reference in the Database somewhere telling ACS that all instances that where installed from a particular ISO / Image still get the OS Type passed down.

In my point of view, an ISO Image should never have any reference to an Instance when it is not connected anymore. And it for sure should not affect the OS Type of an instance when I change the OS type of an ISO Image. The OS Type of a Instance should only be changed when changing it on the instance.

The way it behaves currently is not obvious, unpredictable (you do not know which instances will be affected if you have hundreds) and dangerous if you have production workload.

The big issue here is, that with the change of the OS type from an ISO, you can basically kill all your VMs at once and there is no warning / nothing you can do about it.

### PR DESCRIPTION
**Pull request by abh1sar**
### Description

This PR fixes #10588 

The behaviour is as follows:
_If no VMs are present which were deployed using the ISO/Template_ - OS type change is allowed

_If VMs are present which were deployed using the ISO/Template_ - OS type change is disallowed but can still be done using the `forceupdateostype` parameter. In the UI, this field is displayed only if the OS type is changed.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):
Force option not visible by default
Screenshot 2025-07-16 at 1 07 24 PM

Only visible if the OS type is changed
Screenshot 2025-07-16 at 1 07 44 PM

The error:
Screenshot 2025-07-16 at 1 42 08 PM

### CODE REVIEW

**Comment by abh1sar** [comment]
@blueorangutan package

File: server/src/main/java/com/cloud/template/TemplateManagerImpl.java [hunk 1]
```diff
@@ -2238,6 +2238,12 @@ private VMTemplateVO updateTemplateOrIso(BaseUpdateTemplateOrIsoCmd cmd) {
                 sc.addAnd("state", SearchCriteria.Op.NEQ, State.Expunging);
                 List<VMInstanceVO> vms = _vmInstanceDao.search(sc, null);
                 if (vms != null && !vms.isEmpty()) {
+                    if (!Boolean.TRUE.equals(cmd.getForceUpdateOsType())) {
```
Comment (weizhouapache) [inline server/src/main/java/com/cloud/template/TemplateManagerImpl.java]: for backwards compatibility, I suggest to force update vm os types by default.

on UI, we can uncheck the checkbox by default.

Comment (abh1sar) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java]: @weizhouapache I can make this change, but the issue will still be there for the api calls.
Do you foresee this impacting any workflows? My initial thought was it would be relatively uncommon for users to change the OS type of a template or ISO after deploying VMs from them, so the risk of breaking existing setups seems low. Happy to proceed as you recommend. let me know your thoughts.

Comment (weizhouapache) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java]: @abh1sar
I am good with both.

@daanhoogland @sureshanaparti 
Your advise ?

Comment (DaanHoogland) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java]: @abh1sar I would say, keep existing functionality as default in the API as @weizhouapache says. We can change the default at any time if users massively protest.

**Comment by sureshanaparti** [comment]
@blueorangutan package

**Comment by sureshanaparti** [comment]
@blueorangutan test

File: server/src/main/java/com/cloud/template/TemplateManagerImpl.java (hunk 1 above)
Comment (abh1sar) [reply server/src/main/java/com/cloud/template/TemplateManagerImpl.java]: Done

**Review by rosi-shapeblue — APPROVED** [review]
LGTM. 

Force update is disabled by default in the UI. Changing the OS type with force update disabled, results in an error (if Instances created from that ISO - exist). 

image

Changing the OS Type with "Force update OS type" enabled - is possible. 

Via the API - changing OS type is possible without having to use the  'forceupdateostype' flag. If it is set to 'false' the OS type is not updated.

image

**Comment by sureshanaparti** [comment]
> @abh1sar check the cmk error msg cc @rosi-shapeblue

msg looks ok, with the updated results.
